### ISSUE TITLE
can't find more than two outputs in the vst plug in version

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#100]
I checked out this because it was mentioned in the user guide, but I can't make it work. Here's the comparison with kontakt that works in my system

![jamtaba vst multiout not](https://cloud.githubusercontent.com/assets/15310433/11016140/8982c746-8556-11e5-88f1-6ec6804d9ba6.jpg)

![kontakt vst multiout yes](https://cloud.githubusercontent.com/assets/15310433/11016143/90ab070e-8556-11e5-9f0f-ecec34879b23.jpg)

**Comment by jonjamcam** [comment]
ISSUE #100! let's have a party!!!!!

**Comment by elieserdejesus** [comment]
Jon, Vst plugin is a 4 in 2 out plugin, you can't use more than 2 outputs.
We are planning a multi out plugin, probabily with 16 outs.

**Comment by jonjamcam** [comment]
right...i misunderstood.

**Comment by Ezeer** [comment]
ah ah ah ... you just discovered how to open " portals " Jon "
baby night crawler is a big boy now !
When god created Jamtaba ... genesis : #1

**Comment by elieserdejesus** [comment]
Haha, very good! Back to genesis #1, a beatifull coincidence!

**Comment by jonjamcam** [comment]
Everything works in cycles.....lol
