### ISSUE TITLE
manual update for 2.1.4

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1000]
- [x] Transmiting and receiving video streams.
- [x] Allowing camera selection.
- [x] Grid layout for ninjam channels and bigger cams images.
- [x]  Easy to use private messages.
- [x] New 'Navy' theme.
- [x] Adding a collapse button for chat.
- [x]  Adding a collapse button for bottom area.
- [x]  Adding preferences checkbox to remember ninjamers details when enter in a server.
- [x] New boost button's method (using 2 small buttons).
- [x] Allowing private server hosting.
- [x] Suporting emojis in chat.
- [x] Allowing changes in chat font size.
- [x]  Remembering collapsed sections (bottom, left and chat) when starting JamTaba.
- [x]  Showing network usage (in Kbps) for each ninjamer channel.
- [x]  Adding a new 'Game' theme.
- [x]  Transmiting muted local channels (usefull when using direct monitoring).
- [x] Public chat.
- [x]  Showing Crash Report Dialog after a crashed jam.
- [x] Update screenshots with public chat images.
- [x] Reminding users if local tracks are not transmiting for long time.
- [x]  Showing unread chat messages when chat is collapsed.

WIP -> https://github.com/jonjamcam/JamTaba/wiki/Jamtaba%27s-user-guide

**Comment by elieserdejesus** [comment]
nice and big list 😄  👍

**Comment by jonjamcam** [comment]
@elieserdejesus The manual update is complete for 2.1.4.

 I plan to update some missing features left out here in the 2.1.5 version, but I need to restructure some parts of the manual so they fit in context.

**Comment by elieserdejesus** [comment]
big thanks @jonjamcam , really great work as always!
👍 👍 👍 👍
