### ISSUE TITLE
[Public Chat] filter users

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1003]
1.- I like the idea of a whitelist (only users in the list will appear in the public chat)
2.- Another idea that could be fun is create groups.

**Comment by Hitrate** [comment]
How about just a black list? Surely would be shorter and easier to maintain :)
I'm not for idea 2. lot's of stupid personal opinion reasons, so I'll spare you the details. But I just like the openness and uncluttered'ness of how it is now...Don't wanna see personal profiles, bunch of other pages etc. within the app...one windows is more than enough, on top of focusing on your instrument, DAW screen, Push or what have you, at the same time... And I'm afraid too much added on will bog down the resources even more - not ideal for smooth jamming for all types of systems out there.

**Comment by jonjamcam** [comment]
@Hitrate Let me expand on the whitelist idea. You enter a list of names of your friends and only they appear below "connected users". you can invite them to a server when they appear and no trolls will ever appear (I assume names are kind of unique in ninjam).

**Comment by elieserdejesus** [comment]
> (I assume names are kind of unique in ninjam).

This is a "little" problem! The public chat is not using the ninjam servers, is 100% separated. When you connected in public chat you can use any name. I added (if I remember correctly) some simple logic to avoid duplicated names, but we have no strong guarantees. 

The core problem is: **we have 2 conflicting situations**: 
1 - We are connecting in servers (ninjam or not) without username & passwords 
2 - We are trying to achieve authentication (unique names, avoid people impersonating another people)

**Comment by jonjamcam** [comment]
Obsolete...closing
