### ISSUE TITLE
Trolls

### ISSUE THREAD

**Issue by BlackCatPirate** [elieserdejesus/JamTaba#1004]
serious problem guys...u have 1 or more troll dat every day 
1) swarm users by saing dat they are bad ...
2) join and playing metal when everyone play jazz or somekind of music (if u mute him or them..they are rejoin rejoin rejoin forever..and settings of mute and block are refreshing and not work)
3) !!!! using vpn and normal users nicknames for scam each other!!!! (we have user with nickname Ponny from spain, and troll use his name and vpn when hes offline)

my opinion dats trolls is "creative" (nickname of troll) or "notme" , they are both love 2 agressive chat alot and hate people without even playing

this guys chat like troll dat i spot today, this guys are trolling my jam about 5 times of chat and metal guitar, this guys trolling not my jam too...just ask ur users pls about it

I leave jamtaba for future update dat will kick and ban users for more then 1 second 

sry my english :)

**Comment by elieserdejesus** [comment]
@BlackCatPirate , I agree 100% with @jonjamcam . In understand the issues you mentioned are a big problem, but these things are **ninjam community issues**, not JamTaba issues.
