### ISSUE TITLE
[Public chat] Invites can be duplicated or activated several times to different servers

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1006]
I think this could be a problem ending in abuse. You can invite many people to different servers and actually you don't need to connect to anyone of them. One Idea came to mind: after the invited user **accepts the invitation**, then you are encouraged to connect to that server via button in public chat and at this time invitations to other servers should be disabled for some minutes (or until you disconnect from that server). This way you are allowed to invite other people to the same server but not abuse the feature.

Another problem is you can invite one user several times to the same server and if accepted, jamtaba will disconnect the user and reconnect him/her again.

**Comment by elieserdejesus** [comment]
@jonjamcam , what you think about **invite to your current server only?** Only the current server (public or private) will appear in the invite list. If you are not connected in a server the invite list will not appear.

> Another problem is you can invite one user several times

Using the **invite to your current server only?** logic this can be solved hidding the invite context menu to already connected users.

**Comment by jonjamcam** [comment]
> invite to your current server only?

Yea @elieserdejesus that sounds good enough solution to me.
