### ISSUE TITLE
[Chat] Emoticons input start new line, not appearing next to each other

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1007]
![image](https://user-images.githubusercontent.com/15310433/36636824-b2b35422-19ac-11e8-8122-6c202cf7ce44.png)

**Comment by elieserdejesus** [comment]
now is fixed 😄 

![image](https://user-images.githubusercontent.com/1012741/36645989-1ac5f706-1a50-11e8-9810-e9f702ffa09f.png)
