### ISSUE TITLE
Dropped intervals

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1023]
All 64bit:
Windows10Pro 1709
Reaper v5.76
JamTaba 2.1.4 2018-02-14

I'm not sure how reproducible this is, so I'll provide a lot of detail, some of which may be irrelevant.

I'd been playing on the public servers for well over an hour, switching servers and using the "Listen" button.

First problem is that the "Listen" button starts failing - the server greys but the circle doesn't appear, neither does the signal graphic and there's no audio.

I'm not sure whether that's related but eventually someone told me I was not transmitting - ninbot "nb levels" agreed... most of the time.  Sometimes, though, I'd get audio through - without disconnecting or anything.

It's hard to detect as it relies on a remote monitor (like "nb levels") spotting it - and, of course, if you stop playing to type that in, you might hit enter after an interval when you really weren't playing.

Unfortunately, this is a major issue.  The purpose of the plugin is sending audio.  Everything else is just added bling factor.  If it doesn't get sending audio right, it's pointless.  Of course, it might not be JamTaba getting it wrong - could be anywhere...

So I'll try to see if I can pin this down a bit.  Any help would, of course, be appreciated.

**Comment by jonjamcam** [comment]
Hi @pljones . You can check if you are xmitting by using the listen button while you are connected to a server.

**Comment by pljones** [comment]
Like I said, it has nothing at all to do with settings in the plugin.

It's intermittent, regardless.

I was listening via a web link and checking with "nb levels".  It agreed.  Sometimes sound, sometimes not.

**Comment by elieserdejesus** [comment]
@pljones , when the "listen" progress indicator is not progressing this can be a symptom of low internet bandwith available. If this is the case (maybe others playing games or using netflix, or both in same time like in my house) your intervals willbe be delayed. You are transmiting, but very slow.

I know this is a very simple scenario to consider (very low bandwith), but in these days is very rare use an internet connection exclusively for ninjam. In general there are many devices using the same network in the houses.

I'm shure **nb levels** is not the best tool for the job, except if you are playing an endless loop in JamTaba.

**Comment by pljones** [comment]
http://www.speedtest.net/result/7110415580
I don't think it's internet bandwidth - our usage hasn't changed recently.

**Comment by pljones** [comment]
Ah, good idea.  I'll give that a go next week.

**Comment by jonjamcam** [comment]
> K - so pressing "Listen" will mute my local audio but that audio should still be being sent to the server, right? 

that's right

**Comment by elieserdejesus** [comment]
@pljones , thanks for investigate the problem. You mentioned 

> I had a successful session, then disconnected for a break

1 - "Disconnected" is really **disconnected from server**? Or just **turn off the xmit** button? 

I suppose you really disconnected from server, just checking ...

***

2 - you reconnected in the same server, right?

**Comment by pljones** [comment]
1. Yep, [x] button on the tab to close it.
2. Yes, the other participants were still there, so I'm _fairly_ sure.

**Comment by pljones** [comment]
OK..!

So, leave video on.  Leave channel.  Connect to any channel.  No audio.

Now, turn video on.  Leave channel.  Connect to the same channel.  Audio is back.

Hopefully that'll help pin it down.

**Comment by jonjamcam** [comment]
> So, leave video on. Leave channel. Connect to any channel. No audio.

> Now, turn video on. Leave channel. Connect to the same channel. Audio is back.

@pljones I don't understand what "leave channel" and "connect to any/same channel" mean. Is it "leave room" and "Connect to any/same room"? And about the video, why turn it on if it's already turned on?

**Comment by pljones** [comment]
Sorry, yes - I used channel for room and typoed - the second "on" should be "off", now edited.

Of course, after I posted, I wasn't able to reproduce the error, so it's definitely "intermittent"... so really annoying to find!

**Comment by jonjamcam** [comment]
Well it happened to me last night. Sometimes you appear transmitting, but no sound is being sent to the room. I don't know if video has something to do, but indeed I left one server and joined another while xmit button was always on.

**Comment by pljones** [comment]
Thanks -- for confirming it's not just me going mad  😌  😖

**Comment by jonjamcam** [comment]
I'm not sure it's video related. I was testing the new video codec with some reaninjam/jamtaba users and what I found is that one reaninjam user couldn't hear me when using video. I turned off video and still could not hear me. Restarted jamtaba...he could hear me just a bit and then nothing. I switched to old jamtaba with video off and no more problems.

The only conclusion I get is reaninjam users have the problem. I jammed earlier today with video and one jamtaba user and no issues whatsoever.

We'll need to do some heavy testing to find the problem. Slippery bug.

**Comment by pljones** [comment]
My only other thought on this has been if it's to do with stream order - if the receiver receives the video stream first and doesn't know what to make of it, it may simply ignore the client.  That would explain why the bots and server streams, along with reaninjam clients are affected but not JamTaba clients, too.

**Comment by jonjamcam** [comment]
> - if the receiver receives the video stream first and doesn't know what to make of it, it may simply ignore the client

Sounds reasonable. If this is the case, then a fast solution could be to separate video and audio and force video in channel 2.

**Comment by jonjamcam** [comment]
OK. I can confirm it's video related. As soon as you turn on video, the sound is muted in channel 1, but channel 2 sounds OK.

My tests with reaninjam are not conclusive because it receives sound correctly, so I suspect some versions of the plugin could have problems.

To reproduce:

1.- open jamtaba, connect to ninbot, send something on channel 1 with video off and start listening to the stream via listen button.
2.- after a while turn on video and wait. Sound will be muted after some intervals.
3.- turn video off and wait. sound appears again.

**Comment by elieserdejesus** [comment]
Yes @jonjamcam , I confirmed here running in localhost too. I'm working in this issue.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test this [PR](https://github.com/elieserdejesus/JamTaba/pull/1093)?

In this PR the video is always xmited in 2nd channel.

**Comment by pljones** [comment]
Hi,

I'm trying to build master and the video but the following fails to be found:
#include "miniupnpc.h"

Is there something I'm missing?  (That is, there *is* something I'm missing, but what? 😄 )

-- Peter

**Comment by elieserdejesus** [comment]
> Is there something I'm missing? (That is, there is something I'm missing, but what? 😄 )

@pljones , you downloaded the last pre compiled libs?

**Comment by pljones** [comment]
I'll try again but I grabbed them on 10 April.

**Comment by elieserdejesus** [comment]
> Might be worth sticking a version in the filename and a version file in the bundle.

A version file inside the pre compiled libs zip?

**Comment by pljones** [comment]
Yep, so each time the ZIP is built, it gets a version in the filename and a version file in the ZIP.  Then the build can depend on the right version of the libraries and issue an appropriate message if they've not been updated.

**Comment by pljones** [comment]
Oh, and this is the _include_ not the lib.  So it should be in `.../libs/includes/miniupnp`.

**Comment by elieserdejesus** [comment]
> So it should be in .../libs/includes/miniupnp.

Exactly, **this is my hard disk**: 

![image](https://user-images.githubusercontent.com/1012741/39182825-8063b0aa-4794-11e8-9480-fba846a58cf7.png)

**Do you have another file structure?**

**Comment by elieserdejesus** [comment]
created an issue: https://github.com/elieserdejesus/JamTaba/issues/1096

**Comment by pljones** [comment]
`JamTaba-static-libs.zip` doesn't contain the includes:
![image](https://user-images.githubusercontent.com/1549463/39199137-aa876380-47e0-11e8-8773-e7d09151117b.png)
So no.

**Comment by elieserdejesus** [comment]
I messed the zip in the last changes. It's fixed, the new zip (including the headers) is available.

**Comment by elieserdejesus** [comment]
>  the video as a 3rd "hidden" channel was really cool.

I have the same idea @jonjamcam , but we need extra channel in the servers. 

Tom send me an email another day comenting about a json file in every public server including some server details. Some server atributes can be "video_capable", video_fps, video_kbps, etc.  Video capable servers can allow a 3rd channel, and maybe accept video only.

A good option is detect (when entering in a server) if the server allow 3 channels, if yes use the 3rd channel to video, if not use the current approach. This is not complicated to implement, all servers have a "max_channels" attribute.

**Comment by pljones** [comment]
Good news: I can now compile.
Bad news: the `fix-dropped-intervals` still mutes if I enter the room with video enabled (this is using a private server). 
- turn on video
- enter room
- wait until green Transmit lights up
- (check levels in room with "nb levels" or however) At this point, as nothing has been transmitted, find silence
- start playing audio for several intervals
*Expected Result*
- should get told that your audio is coming through loud and clear
*Actual Result*
- get told you're silent still

**Comment by pljones** [comment]
I am alone on the server.
When I do not stream video, the bot hears me.
When I do stream video before connecting the bot does not hear me.
When I do stream video *BUT AFTER CONNECTING* the bot continues to hear me.

**Comment by jonjamcam** [comment]
@pljones . If you are testing the best plugin, then you need to compile the master. There are two commits that are not included in the original branch.

**Comment by pljones** [comment]
OK, this gets more interesting.

I've got Reaper rewired into MuLab.  Reaper is connecting with ReaNINJAM.  MuLab is connecting with Jamtaba.

If I hold down a sustained chord in MuLab, it's clear from the meters what happens.  The audio _sometimes_ gets through to the host and back.

I'll try to get a screen video capture.

**Comment by pljones** [comment]
OK, try this.  Video capture isn't one of MuLab's advertised features, I'll point out - it's a dirty hack, and depends on system capture codecs and I've none that work well...  But anyway, this clearly records what's going on.

http://www.drealm.info/mu.lab/AppMovie-20180425-121040.mkv (50Mb, 2 minutes 10 seconds -ish)

I've routed the B3 through Jamtaba and then to "No audio output", so it's not being heard except through the ninbot server.  ReaNINJAM is issuing metronome clicks that can be heard.  You can _see_ the audio level in the B3 rack.  Wait...

At about 44 seconds in - and you can hear from the click how many intervals have passed - the audio arrives.  Then stops again.  But it's still being sent.  Then comes back... and goes... etc.

Again, the video/audio alignment are ... dubious ... but it's enough to follow what's going on.

**Comment by pljones** [comment]
@jonjamcam - Sorry, missed your comment.  I didn't realise the fix branch had been merged / abandoned.

**Comment by pljones** [comment]
OMG  :blush:, it's worse than anything...  I forgot that MuLab picks its "known" version of a VST even if you drag-n-drop a different version into a slot.  So I'd not even been using the branch.

**Comment by elieserdejesus** [comment]
> Looks okay now.... 😊

LOL, very good news 😄
