### ISSUE TITLE
Add a cancel button to PluginFinder dialog

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#103]
When i choose a path , there is always a mistake actually .
Say i choose c:/VST/Pianos , the path will be truncated ( in my XP ) to c:/VST
That is a point to fix .

An other is that when i realized that i was scanning my huge c:/Program files/ instead of c:/Program files/ Pianos , i tried to close the pluginfinder with the red button ... crashed JTB .
So we should provide a cancel button .

**Comment by jonjamcam** [comment]
I think the plugin scanner can't be shut down until it finishes. Even if you close the scan window it continues in the background.....

For exqmple Reaper wil scan the plugins at start and won't let you cancel....

**Comment by elieserdejesus** [comment]
Fixed! The problem in scan paths was just a wrong debug line.
Now if you click in the red X in the scanning dialog the scanning is stopped "after the current plugin is completely scanned".

**Comment by Ezeer** [comment]
Good job !
