### ISSUE TITLE
Request - Display 32 bit vs 64 bit in Help, Current Version and Icon name

### ISSUE THREAD

**Issue by Irockus** [elieserdejesus/JamTaba#1040]
Request - Display 32 bit vs 64 bit in Help, Current Version and Icon name

**Comment by elieserdejesus** [comment]
Done in https://github.com/elieserdejesus/JamTaba/commit/4f1a53ebcc28a671425fca2707cbbd12db89e2d0

![image](https://user-images.githubusercontent.com/1012741/37462498-e510b8dc-2830-11e8-85d5-93372670ca17.png)

I changed the installer script to add **(xx bits)** in icon name, but after execute the modified installer I ended with 2 icons in my desktop. **For while let's avoid mess the users desktop and keep the current icon name. 😄** 
![image](https://user-images.githubusercontent.com/1012741/37462596-4f51d082-2831-11e8-90ec-88c2ddd61f18.png)
