### ISSUE TITLE
Request - Make prior version available for download

### ISSUE THREAD

**Issue by Irockus** [elieserdejesus/JamTaba#1041]
Request - Make prior version available for download  (eg current is 2.1.4, would be nice to still be able to download V2.1.3 from jamtaba.com)

**Comment by elieserdejesus** [comment]
Link to prev versions added in the site:
![image](https://user-images.githubusercontent.com/1012741/37438385-ddf4bc70-27d0-11e8-964f-388c5577a264.png)
