### ISSUE TITLE
Request - Further automation of "Entering Chord Progressions"

### ISSUE THREAD

**Issue by Irockus** [elieserdejesus/JamTaba#1042]
Chord progression display is very cool !   

Not enough people use it, possibly due to complexity of entering from the pc/mac keyboard ?

Would it be possible to display a control when you wish to enter a chord progression where you can bring up a "Circle of Fifths" or some other visual selection mechanism (dropdown) to allow mouse selection of notes, or better yet, midi recognition of notes being played and if you want to go all out, gtr tuner recognition for audio being played.

maybe a dropdown for number "notes" to be entered for the progression
then, either mouse/cursor selection of note or midi/audio recognition,
repeat - prompt for next note.

or

invoke a control to indicate you are about to enter a chord progression,
display the progression bars  and allow you to mouse select a note for each slot
eg:  bpi16 could have 1,2,4,8,16 slots - have not thought this out fully, but  you get the idea :)

Thanks for consideration of this request

**Comment by elieserdejesus** [comment]
> Not enough people use it, possibly due to complexity of entering from the pc/mac keyboard ?

It's my opinion too. We need a good chord tool, the "text based" is very primitive 😄

**Comment by elieserdejesus** [comment]
comming: https://github.com/elieserdejesus/JamTaba/pull/1132#issuecomment-429889377
