### ISSUE TITLE
Instrument icons

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1045]
The idea is show icon instrument for each remote track (not for local track).

**The first idea is:**
- Every remote/ninjam track will have a combobox to select one instrument icon

- A default icon will appear for all tracks until you select a different instrument for the ninjamer track

- The selected icon will be stored in JamTaba cache (in our local machine only). If the cache works as expected when we connect in a server with some friends the instrument icons will be loaded (no need to select the instrument icons again)

- Is possible try to "guess" the instrument icon checking the user channel name. For example, if the channel name is "guitar" we can show a drum icon 😄 

Some cool instrument icons: https://www.flaticon.com/packs/music-and-multimedia-linear

**Comment by jonjamcam** [comment]
Sounds good. Please don't forget to include a "troll" icon. 

![image](https://user-images.githubusercontent.com/15310433/37432119-18f611fe-27b6-11e8-86dc-1a638332f2e1.png)

![image](https://user-images.githubusercontent.com/15310433/37432137-2526e5c0-27b6-11e8-9112-ff4fb86dca78.png)

Many ninjamers use that as the primary instrument hehe.

**Comment by elieserdejesus** [comment]
> Sounds good. Please don't forget to include a "troll" icon.

hehe, good idea!

**Comment by elieserdejesus** [comment]
implemented in #1054
