### ISSUE TITLE
[New slider meter] Meters sometimes do not work

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1047]
Still don't know the pattern, but for example:

![image](https://user-images.githubusercontent.com/15310433/37437378-a406a1a4-27cb-11e8-9122-af43ddf586a3.png)

I noticed it happened with the local channel too. Sometimes only one Left or Right meter is shown, but sound is ok.

Here's and example using the looper:

![image](https://user-images.githubusercontent.com/15310433/37442270-1428da66-27e4-11e8-8f5d-9199a0d1fd7c.png)

The loop is stereo, no panning and the meter is shown partially

**Comment by elieserdejesus** [comment]
> Still don't know the pattern

@jonjamcam , I can't reproduce here too. I tested with Game theme and other themes, tested using looper too, listening the public servers, working fine in all cases.

Did you notice the problem in other themes, or maybe it's a Game theme issue only?

**Comment by jonjamcam** [comment]
> Did you notice the problem in other themes, or maybe it's a Game theme issue only?

Good question. Only tested using game theme. I'll check the other themes, but it's been a while since I've not noticed it. Maybe the problem went away. I keep an eye @elieserdejesus

**Comment by jonjamcam** [comment]
I've not seen this happening the last days. Closing for now.

**Comment by jonjamcam** [comment]
And as it was a joke. As soon as I closed the issue it happened again lol:

![image](https://user-images.githubusercontent.com/15310433/38968026-1bb61b58-4360-11e8-95a6-f5c0d84fe165.png)
