### ISSUE TITLE
Render images and video in chat

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1049]
Auto render/show links posted in chat when the url is pointing to images (.png, gif) or videos.

**Comment by jonjamcam** [comment]
is it possibe @elieserdejesus to render audio (wav, mp3, ogg, etc.) directly too?

**Comment by elieserdejesus** [comment]
> is it possibe @elieserdejesus to render audio (wav, mp3, ogg, etc.) directly too?

It's possible @jonjamcam .  Maybe keep the consistency and turn down the general audio volume when a video or audio is played? Similar to the "preview" feature? When a video or audio is played in chat the other audio sources volume are turned down.

**Comment by elieserdejesus** [comment]
To read images: [http://www.qtcentre.org/threads/1483-Qt4-How-to-load-Url-image-into-QImage](http://www.qtcentre.org/threads/1483-Qt4-How-to-load-Url-image-into-QImage)

**Comment by elieserdejesus** [comment]
Rendering images links!

**some https:// hosted images can't be download because my Qt is not compiled with SSL support**.

![jamtaba](https://user-images.githubusercontent.com/1012741/44634374-9a4cf980-a96f-11e8-8a04-410b22677668.gif)

**Comment by jonjamcam** [comment]
nice!
