### ISSUE TITLE
[New slider meters] Midi activity indicator still in old place

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1051]
![image](https://user-images.githubusercontent.com/15310433/37439096-0eb9009c-27d5-11e8-8d69-c76d5bad323e.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I can't reproduce the issue. 

I tried activate midi and, change to no input, change to audio input. 

I tried initialize jamtaba with midi controller disconnected too, but always working ok.

Can you help trying discover the bug pattern?

**Comment by jonjamcam** [comment]
@elieserdejesus Maybe it's not actually a bug,

 When you created the new slider-fader I was expecting the midi activity indicator to be on the side of the new meter (as it was on the side of the old meter), but that was a personal assumption hehe. The midi activity meter is centered like in the picture and now I see it is where it was expected to be.

**Comment by elieserdejesus** [comment]
> When you created the new slider-fader I was expecting the midi activity indicator to be on the side of the new meter (as it was on the side of the old meter), but that was a personal assumption hehe. The midi activity meter is centered like in the picture and now I see it is where it was expected to be.

Ok @jonjamcam 👍
