### ISSUE TITLE
max peaks in local channel not matched with max peak in master channel

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1055]
ATM the max peak in local channel is dotted:

![image](https://user-images.githubusercontent.com/15310433/37569216-c15ae072-2abd-11e8-8fb8-ea7ad673532b.png)

and the master channel has a solid continuous line::

![image](https://user-images.githubusercontent.com/15310433/37569211-b2022842-2abd-11e8-83e7-27b826a8d8fc.png)

EDIT: @elieserdejesus First I thought this was a game-navy theme only, but it happens in all themes. Well it's only a minor detail, but maybe worth matching for all themes to correlate max peak line of master channel and local channels.

I guess GAME-NAVY themes should use a solid continuous line and the rest of the themes a dotted line.

**Comment by elieserdejesus** [comment]
I will check this issue @jonjamcam , but the expected result master peak always stereo, so we need two peaks (L and R). Maybe your master is mono?

**Comment by jonjamcam** [comment]
> Maybe your master is mono?

I confirm the master is stereo. It's just the type of max peak meter

**Comment by jonjamcam** [comment]
> but the expected result master peak always stereo,

yes. Now I get it. that was the problem. stereo channels have stereo peaks
