### ISSUE TITLE
Fine-Adjuting Troll mechanism

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1059]
Some problems that I feel need to be addressed during the latest trolling season on ninjam:

1.- Troll impersonates real username and blocking in this case is not working as expected because the block applies to both, the troll and the normal user (screenshots by torben):

![image](https://user-images.githubusercontent.com/15310433/37709701-ceca0610-2ce9-11e8-90f1-500368fccbc7.png) 

more images here https://imgur.com/a/qcW7l

Torben was supplanted even worse because the troll used a proxy from the same country. He said he couldn't block him because he was using the same name (but I think the block would have worked right-clicking block on the troll's channel)

![image](https://user-images.githubusercontent.com/15310433/37710664-14d0bf98-2ced-11e8-9121-b6b71574422f.png)

2.- Troll attacks from ninbot lounge that are unblockable ATM.

***
Proposed solutions:

For **1** I think a good starter is making differentiation of same username possible (IP maybe?)
 
In the case of **2** I propose a simple idea: filter chat bot messages using a combobox or something that has these kind of options:

1.- filter all (or a ON/OFF button as in public chat)
2.- filter all messages, except VOTING and USER ENTER/LEAVE
3.- Filter only server messages (this will get the lounge trolling under control)

**Comment by Hitrate** [comment]
Thx, good work Jon

**Comment by elieserdejesus** [comment]
sad issue, and unfortunally necessary.

Apparently all your ideas are possible @jonjamcam . Maybe I will have some surprise when dive in the programming details, but I think is possible.

> For 1 I think a good starter is making differentiation of same username possible (IP maybe?)

@jonjamcam , the masked ip is available, and internally Jtba is using the pair name/IP to identify the users. 

Ideas: we can show the country flag along side username in every chat messages to make differentiation of same username, but if the troll is using a "same country" proxy this approach will fail.

Ideas about **how making differentiation of same username**  are welcome.

**Comment by Hitrate** [comment]
Idea: force only one same name username.. :)

**Comment by jonjamcam** [comment]
> Idea: force only one same name username.. :)

I think that is determined by the server admin

**Comment by elieserdejesus** [comment]
> Idea: force only one same name username.. :)
> I think that is determined by the server admin

Exactly, unfortunally can't be solved at jamtaba (client) level.

**Comment by jonjamcam** [comment]
> Ideas: we can show the country flag along side username in every chat messages to make differentiation of same username

Sounds good enough to me. And effective in most cases.

>  if the troll is using a "same country" proxy this approach will fail.

Not necessarily. There are many ways we can know who is who inside a server, so that should not be a problem imo. The important thing to solve is that jamtaba know the difference and allow blocking only one of them (the one the user chooses to block)

**Comment by jonjamcam** [comment]
Well just for the record a couple of days ago Tom has deactivated the lounge chat from ninbot indefinitely, so one less problem to worry about.

**Comment by jonjamcam** [comment]
Obsolete...closing
