### ISSUE TITLE
[Public chat] continuously disconnecting

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1060]
I tried to use the public chat last night, but It looks to me it disconnects automatically after a while (when connected to a server was my experience)

**Comment by elieserdejesus** [comment]
I see the same problem here, actually I see nobody in the public chat since the new version was released, hehe.  

Maybe this is the most useless feature in the ninjam history? 😄  Or maybe the public chat is just buggy, and nobody can use properly ...

**Comment by elieserdejesus** [comment]
I can't reproduce this issue, it's very trick see the bug pattern. 

I see the bug one time, and in all other tests It's just working.

I not tested connecting in a crowded server, maybe this is the cause.

**Comment by jonjamcam** [comment]
I have an idea for this feature to pick up steam. 

1. Public chat ON by default
2. Button state on/off saved in Jason file.

So everyone will have it active unless turned off. What do you think @elieserdejesus

**Comment by elieserdejesus** [comment]
Good ideas @jonjamcam! I created a new issue: https://github.com/elieserdejesus/JamTaba/issues/1097

**Comment by elieserdejesus** [comment]
> Is the connection to a ninjam server generating a glitch in public chat?

I tested in both localhost and public servers  and was working fine. I see the bug one time when connected in a public server. 

It's difficult see the bug pattern.

**Comment by pljones** [comment]
Can the state of the chat room connection be made clear in the tooltip for the "power" icon, please?

**Comment by jonjamcam** [comment]
> Can the state of the chat room connection be made clear in the tooltip for the "power" icon, please?

Something like green button for connected/red button for disconnected  @pljones ?

**Comment by pljones** [comment]
"Red" for "user wanted to be disconnected and there is no open network connection"
"Green" for "user wanted to be connected and there is an open network connection over which data is being reliably exchanged"

Clearly there are states between red and green 😄

**Comment by elieserdejesus** [comment]
No clues at moment about the chat disconnections. The code is pinging at the server (heroku) periodically (45 seconds) to keep the connection alive, but is not enough. In some weird conditions the chat is disconnecting. In 99% of my tests it's working fine, so I will work in this issue when have more clues about the problem.

**Comment by jonjamcam** [comment]
Obsolete.... closing
