### ISSUE TITLE
Jamtaba Crash and Hang trying to reload prior settings when using Kontakt

### ISSUE THREAD

**Issue by Irockus** [elieserdejesus/JamTaba#1063]
When I load Kontakt Vst  - initially after fresh install, all works fine.  

When I then exit and try to restart Jamtaba, it crashes and hangs trying to load previous session setings while loading Kontakt.   Cannot terminate the Jamtaba process, need to logoff of WIndows or reboot.

Is there a way to just clear the Jamtaba settings for which vsts and tracks were loaded previously ?
I do not know where the settings are stored.   Thus far the only way I have found to resolve the issue is to uninstall Jamtaba completely and then reinstall.

I have tested the behaviour with different instrument libraries and also not having any libraries loaded, just Kontakt vsti.  The problem occurs in both the X86 and 64 bit versions - release 2.1.4.

Here is a crash dump

default.INFO      [08:51:55:463] JamTaba Base dir: "C:/Users/Admin/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [08:51:55:744] "Starting Jamtaba 2.1.4 Standalone (x86_64) running on Windows  (x86_64)" [, line 0]
default.CRITICAL  [08:51:58:273] Configurator::signalHandler signal: 11 [, line 0]
default.CRITICAL  [08:51:58:592] 00007FF78B5ED5AD (Jamtaba2): (filename not available): StackWalker::ShowCallstack
 [, line 0]
default.CRITICAL  [08:51:58:594] 00007FF78B1C12F5 (Jamtaba2): (filename not available): Configurator::terminateHandler
 [, line 0]
default.CRITICAL  [08:51:58:594] 00007FF78B1C127A (Jamtaba2): (filename not available): Configurator::signalHandler
 [, line 0]
default.CRITICAL  [08:51:58:595] 00007FFC4654FB19 (MSVCR120): (filename not available): XcptFilter
 [, line 0]
default.CRITICAL  [08:51:58:603] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c (666): __tmainCRTStartup$filt$0
 [, line 0]
default.CRITICAL  [08:51:58:604] 00007FFC4654F14B (MSVCR120): (filename not available): _C_specific_handler
 [, line 0]
default.CRITICAL  [08:51:58:604] 00007FFC4F7B4C7D (ntdll): (filename not available): _chkstk
 [, line 0]
default.CRITICAL  [08:51:58:605] 00007FFC4F72D1D8 (ntdll): (filename not available): RtlWalkFrameChain
 [, line 0]
default.CRITICAL  [08:51:58:606] 00007FFC4F7B3BAE (ntdll): (filename not available): KiUserExceptionDispatcher
 [, line 0]
default.CRITICAL  [08:51:58:607] 00007FF78B11350D (Jamtaba2): (filename not available): ChatTabWidget::retranslateUi
 [, line 0]
default.CRITICAL  [08:51:58:608] 00007FF78B193897 (Jamtaba2): (filename not available): MainWindow::changeEvent
 [, line 0]
default.CRITICAL  [08:51:58:609] 00007FF78B63BB41 (Jamtaba2): (filename not available): QWidget::event
 [, line 0]
default.CRITICAL  [08:51:58:612] 00007FF78B67FB77 (Jamtaba2): (filename not available): QMainWindow::event
 [, line 0]
default.CRITICAL  [08:51:58:614] 00007FF78B745C55 (Jamtaba2): (filename not available): QApplicationPrivate::notify_helper
 [, line 0]
default.CRITICAL  [08:51:58:614] 00007FF78B745168 (Jamtaba2): (filename not available): QApplication::notify
 [, line 0]
default.CRITICAL  [08:51:58:617] 00007FF78BEA1E18 (Jamtaba2): (filename not available): QCoreApplication::notifyInternal
 [, line 0]
default.CRITICAL  [08:51:58:618] 00007FF78BEA3BF4 (Jamtaba2): (filename not available): QCoreApplicationPrivate::sendPostedEvents
 [, line 0]
default.CRITICAL  [08:51:58:620] 00007FF78BA18ED2 (Jamtaba2): (filename not available): QWindowsGuiEventDispatcher::sendPostedEvents
 [, line 0]
default.CRITICAL  [08:51:58:622] 00007FF78C0031A9 (Jamtaba2): (filename not available): qt_internal_proc
 [, line 0]
default.CRITICAL  [08:51:58:623] 00007FFC4E8FB85D (USER32): (filename not available): CallWindowProcW
 [, line 0]
default.CRITICAL  [08:51:58:623] 00007FFC4E8FB1EF (USER32): (filename not available): DispatchMessageW
 [, line 0]
default.CRITICAL  [08:51:58:624] 00007FFC4E91B947 (USER32): (filename not available): DialogBoxIndirectParamAorW
 [, line 0]
default.CRITICAL  [08:51:58:624] 00007FFC4E91B70E (USER32): (filename not available): DialogBoxIndirectParamAorW
 [, line 0]
default.CRITICAL  [08:51:58:625] 00007FFC4E91B5D2 (USER32): (filename not available): DialogBoxIndirectParamAorW
 [, line 0]
default.CRITICAL  [08:51:58:625] 00007FFC4E91B568 (USER32): (filename not available): DialogBoxIndirectParamW
 [, line 0]
default.CRITICAL  [08:51:58:626] 00007FFC11295B67 (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:627] 00007FFC10B1DC27 (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:627] 00007FFC105F83F2 (Kontakt 5): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [08:51:58:628] 00007FFC10AD5339 (Kontakt 5): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [08:51:58:628] 00007FFC1095047D (Kontakt 5): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [08:51:58:629] 00007FFC10A54B73 (Kontakt 5): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [08:51:58:629] 00007FFC10B02288 (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:630] 00007FFC10B59E63 (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:630] 00007FFC10B5A4E0 (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:631] 00007FFC10AFF2EA (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:631] 00007FFC10B59C5C (Kontakt 5): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [08:51:58:632] 00007FFC10AFD338 (Kontakt 5): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [08:51:58:633] 00007FF78B1FA0A8 (Jamtaba2): (filename not available): vst::VstPlugin::restoreFromSerializedData
 [, line 0]
default.CRITICAL  [08:51:58:634] 00007FF78B1E2190 (Jamtaba2): (filename not available): MainWindowStandalone::restoreLocalSubchannelPluginsList
 [, line 0]
default.CRITICAL  [08:51:58:634] 00007FF78B1E249B (Jamtaba2): (filename not available): MainWindowStandalone::initializeLocalSubChannel
 [, line 0]
default.CRITICAL  [08:51:58:635] 00007FF78B18BFB0 (Jamtaba2): (filename not available): MainWindow::initializeLocalInputChannels
 [, line 0]
default.CRITICAL  [08:51:58:636] 00007FF78B18BC10 (Jamtaba2): (filename not available): MainWindow::initializeLocalInputChannels
 [, line 0]
default.CRITICAL  [08:51:58:636] 00007FF78B1E1504 (Jamtaba2): (filename not available): MainWindowStandalone::doWindowInitialization
 [, line 0]
default.CRITICAL  [08:51:58:637] 00007FF78B18A137 (Jamtaba2): (filename not available): MainWindow::initialize
 [, line 0]
default.CRITICAL  [08:51:58:638] 00007FF78B1E0F04 (Jamtaba2): (filename not available): MainWindowStandalone::initialize
 [, line 0]
default.CRITICAL  [08:51:58:638] 00007FF78B1D585C (Jamtaba2): (filename not available): main
 [, line 0]
default.CRITICAL  [08:51:58:640] 00007FF78C3193A5 (Jamtaba2): (filename not available): WinMain
 [, line 0]
default.CRITICAL  [08:51:58:640] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c (618): __tmainCRTStartup
 [, line 0]
default.CRITICAL  [08:51:58:641] 00007FFC4CCF1FE4 (KERNEL32): (filename not available): BaseThreadInitThunk
 [, line 0]
default.CRITICAL  [08:51:58:642] 00007FFC4F77EFC1 (ntdll): (filename not available): RtlUserThreadStart
 [, line 0]

**Comment by jonjamcam** [comment]
@Irockus . Solved here: https://github.com/elieserdejesus/JamTaba/issues/1048

**Comment by elieserdejesus** [comment]
> Is there a way to just clear the Jamtaba settings for which vsts and tracks were loaded previously ?

Yes @Irockus , you can delete or edit the **Jamtaba.json** file in your **C:/[your user name]/AppData/Roaming/JamTaba**.
