### ISSUE TITLE
youtube dont work after using jamtaba2

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1064]
Strange . After using jamtaba2  as vst in reaper , i cant use youtube any more the player freeze .  Only solution i find is  starting my computer again . and after its ok .  A bit annoying ,
? any idea  

i dont see any apps  from reaper or jamtaba running  in the background,  

thanks for your help

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , Iet's check this problem.  

@jonjamcam , have you experienced this problem too?

**Comment by jonjamcam** [comment]
> @jonjamcam , have you experienced this problem too?

Just checked. No problems here.

**Comment by DoublebassOO** [comment]
I try using reaninjam  without this annoying problem  ...  in fact all streaming get impossible to work  but it takes 1 or 2 minutes ..?  very strange and very problematic for me.

**Comment by DoublebassOO** [comment]
i come back to an old version of jamtaba 2.1.0  and all was fine for using youtube and all streaming player with it .
Any idea of why the new jamtaba could  make it interfer with the streaming in the browser ?? 
For the moment i will stay  with 2.1.0  but otherwise i will have to leave   jamtaba ... oh  no !!!!!!! back to old reaninjam is so frustrating  :)
Please find a solution...

**Comment by elieserdejesus** [comment]
> Any idea of why the new jamtaba could make it interfer with the streaming in the browser ??

No idea at moment, we (me and Jon) tested and can't reproduce your problem. Without see the problem I can't fix.

**Comment by DoublebassOO** [comment]
how can i make you see the problem ? any idea

**Comment by elieserdejesus** [comment]
> how can i make you see the problem ? any idea

@DoublebassOO , are you using some internet proxy? Firewall? 

What internet browser are you using when you see the youtube player problem? Google chrome? Firefox?

Are you using some browser extension related to video? If yes, can you try to disable these browser extension and test again?

JamTaba is not using anything of our browsers, so this issue its very weird for me. JamTaba video encoder/decoder is 100% built-in, no external resources are used, so I can't understand how jamtaba video is conflicting with your browser. It's a very intriguing issue, but let's investigate the possibilities, sometimes the bugs are not obvious.

**Comment by jonjamcam** [comment]
@DoublebassOO have you tried creating a new project in reaper where only jamtaba is used? I believe in any case it should be the host (reaper) not jamtaba who may be conflicting with your browser

**Comment by DoublebassOO** [comment]
yeah   i think i got it    Jamtaba was not at all guilty . Sorry . I think i find the culpable  the driver of my breathcontroller was not update and strangely the conflict seems to block the streaming ... 

thanks for your help

**Comment by DoublebassOO** [comment]
resolved
