### ISSUE TITLE
[Navy theme] some meters have wrong color

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1065]
![image](https://user-images.githubusercontent.com/15310433/37892127-1bd6d7fa-30ad-11e8-8358-7fd8f5af33bd.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I tried to reproduce the error, but no success.

I tried change theme, change the track layout, the dB marks colors are always ok in Navy theme. Can you see some pattern in this issue?

**Comment by jonjamcam** [comment]
> Can you see some pattern in this issue?

Yes. Before selecting navy theme, select ice theme to reproduce
