### ISSUE TITLE
some "UNKNOWN" users inside the server seem to get local flag :D

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1068]
![image](https://user-images.githubusercontent.com/15310433/37944831-93da8c28-3153-11e8-83d7-afd11d39cb8e.png)

![image](https://user-images.githubusercontent.com/15310433/37947743-0f357efa-3163-11e8-84a8-63003eb67f36.png)

but...

![image](https://user-images.githubusercontent.com/15310433/37947789-388f481c-3163-11e8-91cd-27fd28e81f72.png)

![image](https://user-images.githubusercontent.com/15310433/37944858-b7821074-3153-11e8-9389-42c4c67ea254.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I can't reproduce this issue. I deleted the cache to force the "unknow" country flag but is always working as expected.

I think this commit https://github.com/elieserdejesus/JamTaba/commit/c10dc60cb8218cc0bab6f8683e8a84392f255e91 solved the issue.

Can you test again too, please?

**Comment by jonjamcam** [comment]
> Can you test again too, please?

It's hard to test. I believe this bug is triggered in these two specific cases:

1.-  when a user has a admin login that Jamtaba associate with the **ninjam server ip** in order to have a flag and congruent map location. This server ip is shown correctly in the map, but not inside the jam room.

2.- when a user has an ip other than 127.0.0.1, but still recognized by nekudo as "unknown", so JTB uses the ninjam server ip.

 these are my work hypothesis ATM . I will try to check again if the bug is still there @elieserdejesus .

**Comment by jonjamcam** [comment]
some more info. It keeps happening here (compiled using last commits to date in standalone): 

![image](https://user-images.githubusercontent.com/15310433/38715954-9a29e876-3eb4-11e8-8ec7-b5b873fe8ad1.png)

Bardo is probably logged using admin un and pw so he get's server location (normally he's at the bottom):

![image](https://user-images.githubusercontent.com/15310433/38715959-9f0e0a98-3eb4-11e8-8b6d-356cbcbf4692.png)

reaninjam shows no ip:

![image](https://user-images.githubusercontent.com/15310433/38716042-08e7571c-3eb5-11e8-9289-ebca0b8e943d.png)

**Comment by jonjamcam** [comment]
Obsolete.... closing....
