### ISSUE TITLE
fix the devil's name 

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#107]
mwah ah ah ah ... 
![midifix2](https://cloud.githubusercontent.com/assets/1283808/11021470/482f6f78-8642-11e5-85ba-2cd513ccb76a.jpg)

" Périphérique  " is no more supported by Jamtaba .
Put it in the black box ? lol
I think i will try iso-latin in some files ...
^^

**Comment by Ezeer** [comment]
Could it be in the css elieser ?

**Comment by Ezeer** [comment]
>Qt and QString don’t know what execution charset you chose when you compiled your source code
The execution charset isn’t constant: one object file can have a different charset from another object or library

http://blog.qt.io/blog/2011/03/26/on-utf-8-latin-1-and-charsets/

**Comment by Ezeer** [comment]
https://wiki.qt.io/Strings_and_encodings_in_Qt

**Comment by Ezeer** [comment]
I've found the devil's cave : 
QString RtMidiDriver::getInputDeviceName(int index) const{
    if(midiStreams.at(index)){

        return  QString::fromStdString( midiStreams.at(index)->getPortName(index)).toLatin1();
    }
    return "error";
}

So yeah , i tried to add .toLatin1() in case , that gives : 
![midifix3](https://cloud.githubusercontent.com/assets/1283808/11021728/a16e8d22-864b-11e5-9f3e-8caaaa476e29.jpg)

So it is the right place to convert the evil in angel ...

**Comment by Ezeer** [comment]
Tried toUpper() , in french there is no accentuation , but gives : 
![midifix4](https://cloud.githubusercontent.com/assets/1283808/11021802/95a5dbba-864d-11e5-9564-b2a1b3d34096.jpg)

pffff ...

**Comment by Ezeer** [comment]
ok , it's the lib that was coded in a different locale or encoder  that produces these artifacts .
It would be interesting to see if other french users have this problem too .

**Comment by elieserdejesus** [comment]
Ezee, change the code to always return "Périphérique". Let's see if the problem is really the library.

**Comment by elieserdejesus** [comment]
I'm looking at RtMidi.cpp
```
std::string MidiInWinMM :: getPortName( unsigned int portNumber )
{
...

#if defined( UNICODE ) || defined( _UNICODE )
  int length = WideCharToMultiByte(CP_UTF8, 0, deviceCaps.szPname, -1, NULL, 0, NULL, NULL) - 1;
  stringName.assign( length, 0 );
  length = WideCharToMultiByte(CP_UTF8, 0, deviceCaps.szPname, static_cast<int>(wcslen(deviceCaps.szPname)), &stringName[0], length, NULL, NULL);
#else
  stringName = std::string( deviceCaps.szPname );
#endif

...
  return stringName;
}
```

I compile the lib using UNICODE and _UNICODE flags, but is not working yet.

**Comment by elieserdejesus** [comment]
Ezee, please try this recompiled lib:
[librtmidi.a.txt](https://github.com/elieserdejesus/JamTaba/files/29564/librtmidi.a.txt)

I'm compiling using these lines because the ./configure file is not working here:
```
g++ -c -DUNICODE -D__WINDOWS_MM__ rtmidi.cpp -o rtmidi.o
ar rcs librtmidi.a rtmidi.o
```

**Comment by Ezeer** [comment]
The line below works :
return  QString::fromUtf8("Périphérique"); 

i'll report for your last lib , thx !

**Comment by Ezeer** [comment]
Good job , fixed !
You can close now .
Thank you !

**Comment by Ezeer** [comment]
Please push the new lib , i've got a merging problem here .
Push , i will delete mine , then pull yours .
Ok ? i close now .

**Comment by Ezeer** [comment]
You don't need to push now , i've fixed the merge and pushed

**Comment by elieserdejesus** [comment]
Nice Ezee, pull working here:
´´´
PS E:\Jamtaba2\jamtaba2> git pull
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 33 (delta 14), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/elieserdejesus/JamTaba
   1f1167d..32497ce  master     -> origin/master
Updating 1f1167d..32497ce
Fast-forward
 Client/libs/static/win32-mingw/librtmidi.a         | Bin 177066 -> 181082 bytes
 Client/libs/static/win32-mingw/librtmidi2.a        | Bin 0 -> 181082 bytes
 Client/src/Libs/SingleApplication/LICENSE          |  21 ++++
 Client/src/Libs/SingleApplication/README.md        |  69 +++++++++++
 .../Libs/SingleApplication/singleapplication.cpp   | 133 +++++++++++++++++++++
 .../src/Libs/SingleApplication/singleapplication.h |  36 ++++++
 Client/src/gui/PreferencesDialog.ui                |   2 +-
 Client/src/midi/RtMidiDriver.cpp                   |   7 +-
 8 files changed, 265 insertions(+), 3 deletions(-)
 create mode 100644 Client/libs/static/win32-mingw/librtmidi2.a
 create mode 100644 Client/src/Libs/SingleApplication/LICENSE
 create mode 100644 Client/src/Libs/SingleApplication/README.md
 create mode 100644 Client/src/Libs/SingleApplication/singleapplication.cpp
 create mode 100644 Client/src/Libs/SingleApplication/singleapplication.h
PS E:\Jamtaba2\jamtaba2>
```
