### ISSUE TITLE
some user's color in chat is changing on every comment

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1070]
![image](https://user-images.githubusercontent.com/15310433/37998907-f4b7e718-31f6-11e8-87b4-f15c631a6fc2.png)

**Comment by elieserdejesus** [comment]
I tested connecting 2 clients (ReaNinjam and VST) with Standalone and works ok. Entered in a server to check the chat behavior with more users and confirmed the issue:

![image](https://user-images.githubusercontent.com/1012741/38109942-33ed06a0-3370-11e8-992f-2e8f10c91890.png)
