### ISSUE TITLE
[EXPERIMENT] transfer files over the ninjam protocol

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1071]
I opened this issue just as a discussion, an experiment to see if it has any potential/interest.

One thing ninjam lacks is the capability to send images or any file (video, pdf, rar, etc.) without the need of external servers. Today we're all used to use whatsapp or other software of the kind and this type of file sharing is very common. I understand in the case of ninjam this can be risky beacause of abuse, viruses, etc. but the discussion is probably something we can have safely.

So what I was thinking is just as now @elieserdejesus has successfully incorporated video to our jams without affecting other clients, is it possible to use the same method to transfer a picture or an audio file or any file, for example via chat but streamed over the servers internally.

So in practice something like this:

1.- in the chat window you attach file
2.- when pressing send the file is streamed to all clients same way video is transmitted
3.- file is received in the chat of all clients, stored in some kind of local cache and capable of being saved via "do you want to save the file" button in the local computer.

Of course if you use it in combination with https://github.com/elieserdejesus/JamTaba/issues/1049 the results can be very ineresting

too crazy?

**Comment by elieserdejesus** [comment]
> is it possible to use the same method to transfer a picture or an audio file or any file, for example via chat but streamed over the servers internally.

> too crazy?

@jonjamcam , the idea is totally possible. I think is better disable transfer executables, but another file formats can be transfered. 

Another issue is the file size. It's important put a file size restriction to avoid people transfering some gigabytes during ninjam sessions. The server will be overloaded.

A good usage is transfer lead sheets from png or pdf files, for example. In some "jazzy" jams the guys are posting the links to the lead sheets.

**Comment by jonjamcam** [comment]
Next reincarnation maybe :D ...closing
