### ISSUE TITLE
Notify player locally if they're way too loud

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#1078]
Hey guys, back with another suggestion that I hope will be a lesson learned and a step in the right direction towards more congruent pleasing jams:

Instead of the main chat room stating that "this player is clipping some absurd number of decibels that doesn't make any sense to any normal person" like this:
![screen shot 2018-04-01 at 8 18 06 pm](https://user-images.githubusercontent.com/26333462/38176140-d8c5b598-35e9-11e8-9fb3-8f3f0ec581aa.png)

I suggest we fine tune first of all the message:

Firstly, change the amount of decibels stated, to be of a normal real world scenario number that the user can actually use to level out their levels correctly (ie turn down their gain/master). If the player has a RMS that's hovering 15db above everyone else/above or is 15db louder than the default -18db for instance, he should be notified that he is too loud, please turn down your volume at least 15db.

That way he knows he has to turn down his volume, and how much.

Secondly, I think it would be even better, if that message was delivered to the person privately, or more specifically (like the notice you get when you haven't been streaming for a while - if the user could get a similar non-obtrusive "pop up" text like that that's timed, so it goes away by itself, doesn't disturb the other users (ie local) and makes the user (hopefully) more aware that there's a problem.

This way we other users don't have to bend over because guitarists have no sense of dynamics or volume, we don't have to spend time trying to educate other players about how they're way too loud, they will get the message because there actually is a message telling them what to do. 

The messaging could even evolve, so if the user doesn't react the first time, the second message is phrased differently and perhaps the pop-up message more obtrusive maybe the second or third message the user has to click away the pop-up so they can't just keep ignoring it... Kind of like when you're speeding and the first sign says "you're speeding, slow down" then a mile later it says "you're still speeding, slow down !!!" :)

Cheers

**Comment by elieserdejesus** [comment]
> Firstly, change the amount of decibels stated, to be of a normal real world scenario number that the user can actually use to level out their levels correctly

These dB values are comming from ninbot. I don't know how translate these values to a "real world 
scenario". For example, 551 dB is the ninbot maximum dB reference? Is the 0 dB? Without reference values is complicated translate these ninbot dB values to something more "real world".


> I think it would be even better, if that message was delivered to the person privately

Good idea, and this can be done in JamTaba side.

**Comment by Hitrate** [comment]
So that's Tom's department? I'll try and write him see what he has to say about it :)

**Comment by elieserdejesus** [comment]
> So that's Tom's department?

Yes, the Tom's department 😄.

**Comment by Hitrate** [comment]
Here's what I got back:

_"The bot uses Justins ninjam client DB code.
I believe once the number >=0 you can just
say its 0"_


I wonder how it calculates the db's above 0db...That would be cool so they could be notified exaclty how much more they're peaking thatn they should. But maybe somewhere between above -12db and 0 db would result in a "warning" and if it could calculate someone being "constantly" above 0db a more hard warning could be had. Anywho, I guess at least it'd be possible given the nb levels feature and all, to remind someone personally if they're clipping, possible add in the message that they can add a limiter before jamtaba to keep their level below 0...so it becomes like a "guide" more than a "boss" like "Please turn down your level (or use a limiter), your signal is clipping above 0db" :)

**Comment by elieserdejesus** [comment]
I'm separating this issue in 2 small issues (it's better from the programming point of view). 

I created a new issue to "show usefull tips when user is too loud" https://github.com/elieserdejesus/JamTaba/issues/1081.

**Comment by elieserdejesus** [comment]
Fixed, this a simple test connected in the same server with JamTaba (left) and Reaninjam (right). 

ReaNinjam is showing some "Donati" level warning messages, JamTaba is skipping these messages:
![image](https://user-images.githubusercontent.com/1012741/39971369-358e14a8-56d0-11e8-9498-20dd2c337af0.png)
