### ISSUE TITLE
[Private Chat] issues when user leaves

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1084]
1.- Notification appears in common ninjam chat, not on private chat.

![image](https://user-images.githubusercontent.com/15310433/38348561-fb71cc44-3878-11e8-9235-4e3db6c95832.png)

2.- If new messages are sent to the same user, a notification revealing user's ip is shown in common chat:

![image](https://user-images.githubusercontent.com/15310433/38348581-18d1c67c-3879-11e8-851a-3975b6e1077f.png)

**Comment by elieserdejesus** [comment]
It's fixed in master branch. 

1 - Now the message (user has left the room) appears in both private and ninjam chat.
2 - When the user leaves the private chat is deactivated, is not possible send new messages.
