### ISSUE TITLE
Prevent Multiple launches for the standalone

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#109]
I'm sure this was another thread, but was unable to find it.

![multiple jamtaba](https://cloud.githubusercontent.com/assets/15310433/11021921/d488def4-862f-11e5-8b88-d0f7a9e07169.jpg)

**Comment by Ezeer** [comment]
That was fixed no ? We add spaghettis with the code last week and we perhaps have lost some data ?

**Comment by Ezeer** [comment]
no , it was in fact for the plugin instances -> https://github.com/elieserdejesus/JamTaba/issues/24

**Comment by jonjamcam** [comment]
right, the plugin, not the standalone.

**Comment by Ezeer** [comment]
They invented the wheel : https://github.com/itay-grudev/SingleApplication

**Comment by elieserdejesus** [comment]
Ezee, can you work on this?

**Comment by Ezeer** [comment]
Woaw , you let me touch to the QApp ?
Hey , i really have the license to kill now ...
k, i take it , thx .

**Comment by Ezeer** [comment]
How and where do you want to store the sources files ?
As sources files in SingleApplication folder here : https://github.com/elieserdejesus/JamTaba/tree/master/Client/src

or singles files in header and source respectively ?
Where to store their MIT license ?
lemme know please

**Comment by elieserdejesus** [comment]
Ezee, what you think about create a "libs" folder inside Client/src ?

and maybe create libs/SingleApplication folder too.

The MIT licence can be in the libs/SingleApplication.

**Comment by Ezeer** [comment]
As you want , that sounds good too me 2 .
C'est parti !
^^

**Comment by elieserdejesus** [comment]
Done!

**Comment by jonjamcam** [comment]
You're a Great team guys!

**Comment by Ezeer** [comment]
well , elieser is a great leader !
wohoo !
^^

**Comment by elieserdejesus** [comment]
Just one more bug and we can release the v2.0.5 !
Unfortunally this last bug is driving me crazy everytime :)

**Comment by jonjamcam** [comment]
no beta 3?

**Comment by Ezeer** [comment]
More RC2 ( release candidate 2 )
![r2d2-dvd-projector](https://cloud.githubusercontent.com/assets/1283808/11026049/4cdaf7d8-86a4-11e5-9fdd-dc20b12e3387.jpg)

**Comment by jonjamcam** [comment]
can't wait! lol RC

**Comment by Ezeer** [comment]
Follow these steps : 

1 - Download Qt OffLine Installer for Windows MinGW: http://www.qt.io/download-open-source/

2 - Download VST SDK: http://www.steinberg.net/en/company/developers.html

3 - Unpack the download VST SDK content inside a "VST_SDK" folder (you need create this folder) in Jamtaba source code path. After this you have something like that:

Jamtaba source code dir in your hard disk
    |_ Client
    |_ Icons
    |_ Server
    |_ VST_SDK 
        |_ base
        |_ bin
        |_ doc
        |_ pluginterfaces
        |_ plublic.sdk
        |_ vstgui.sf
        |_ vstgui4
        |_ index.html

4 - Run Qt installer and check the options below: Qt -> Qt 5.5 -> MinGW 4.9.2 32 bit Qt -> Tools -> MinGW 4.9.2 This will install Qt compiled with MinGW and install MinGW tools (compiler, debugger, etc) in [Qt install folder]/Tools.

5 - Open QtCreator (the Qt IDE). QtCreator is located in[Qt install folder]/Tools/QtCreator.exe. If you select Tools->MinGW in setp 3 QtCreator is configured to use MinGW, this is the easy way!

6 - Open the Jamtaba.pro file in QtCreator (use the button "Open Project in QtCreator start screen).

7 - [Optional Step]: In QtCreator click in "Projects" in left side to open the "Build Settings" page. In "Build Steps" section expand you will see "qmake" and "Make" details. Open "Make" details (click in the combo in right side). Now you see a text field for "Make arguments". Put "-j 4" in this text field, where "4" is the number of cores in your processor. This will speed up the compilation using all your processor cores.

8 - Have fun! This is the most important step!

**Comment by jonjamcam** [comment]
Ok I'll have to free some 4 GB of space,  I'll test it tomorrow afternoon I have some time. BTW you guys really fixed a lot today. Hard work. I love the program..it0s the best sounding and easier to use!

My goal for now as I can't contribute with code is finding bugs. Cya!

**Comment by Ezeer** [comment]
It's cool jon that you make the first step .
You will be able to run our night builds , test alpha versions , and more !
We have for example a css file used for all the Jamtamba appearance , you will be able to tweak
the interface colors , fonts , etc ...
And hopefully find bugs !
;)

**Comment by elieserdejesus** [comment]
Jon, I upload a RC2, please check the releases.

**Comment by Ezeer** [comment]
@jonjamcam 

**Release candidate**
A release candidate (RC) is a beta version with potential to be a final product, which is ready to release unless significant bugs emerge. In this stage of product stabilization, all product features have been designed, coded and tested through one or more beta cycles with no known showstopper-class bug. A release is called code complete when the development team agrees that no entirely new source code will be added to this release. There could still be source code changes to fix defects, changes to documentation and data files, and peripheral code for test cases or utilities. Beta testers, if privately selected, will often be credited for using the release candidate as though it were a finished product. Beta testing is conducted in a client's or customer's location and to test the software from a user's perspective.
