### ISSUE TITLE
JamTaba 32 bits not starting in Windows 8

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1091]
After installing JamTaba in Windows 8 (32 bits) I received an error: **missing MSVCR120D.dll**.

I think some 32 bits lib is compiled in debug mode: https://stackoverflow.com/questions/23114427/vs2012-msvcr120d-dll-is-missing

**Comment by elieserdejesus** [comment]
tested the installer using the new libraries (including the x264 codec) and is working, no more problems.

**Comment by jonjamcam** [comment]
Probably related to https://github.com/elieserdejesus/JamTaba/issues/1032
