### ISSUE TITLE
[VST plugin] when video channel is used audio sent to channel 3/4 is still being sent to server via channel 2

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1095]
When video is used I think channel 3/4 should be routed internally to channels 1/2 (for user's convenience) so when video is NOT used, channels 3/4 return to work independently from 1/2.

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm just disabling the 2nd channel input (in VST/AU) if the video is activated. 

The internal routing idea is too complicated. Let's try this new video scheme (2nd channel) and see what happens.
