### ISSUE TITLE
Keep a visual list of enabled Vsts ( and manage black list )

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#11]
i would like to keep the list on the panel , or with a button to view/hide the list . Having a listbox with checked button per line would be a must !

**Comment by Ezeer** [comment]
Cool ! I take that right now .
^^

**Comment by Ezeer** [comment]
Work in progress : 
![capture d ecran 2015-10-24 21 56 33](https://cloud.githubusercontent.com/assets/1283808/10712389/07081986-7a9a-11e5-9a28-c2c35d7f324f.png)

**Comment by elieserdejesus** [comment]
Nice Ezee!

Are you putting the plugins list in the PATH list?

I think wee need 2 lists:  The PATHs to scan list, and the "installed"
plugins list.

I see just one list in your image...

Elieser


Em sábado, 24 de outubro de 2015, Ezee <notifications@github.com> escreveu:

**Comment by Ezeer** [comment]
Ah ah ah !
I WAS ASKING YOU TO MAKE THE LIST FOR ME !!
lol

**Comment by elieserdejesus** [comment]
You need help to put the other list in the ui?

I remember I spend a lot of time in my first time using QtCretor GUI
editor. When you learn the tricks is very good and easy, but the first
experience can be a little complicated.

If you need help I'm working in JT right now.

Elieser



Em sábado, 24 de outubro de 2015, Ezee <notifications@github.com> escreveu:

**Comment by Ezeer** [comment]
HELLLLLLLLL...P !
" If you need help I'm working in JT right now. "
What is JT please ? Aaah ...Jamtaba ? JTB ?
^^

**Comment by elieserdejesus** [comment]
Are you in the chat?

Em sábado, 24 de outubro de 2015, Ezee <notifications@github.com> escreveu:

**Comment by Ezeer** [comment]
eh eh :+1:
21:38:06 ‹Elieser› now the work is in the code
21:38:10 ‹Elieser› PreferencesDialog.cpp
21:38:57 ‹ezee› QStringList vsts = mainController->getSettings().getVstPluginsPaths();^
21:38:58 ‹Elieser› check the PreferencesDialog::createWidgetsToNewScanPath
21:39:08 ‹ezee› ok
21:39:15 ‹Elieser› in Qt
21:39:30 ‹Elieser› the widgets are added to layout instances
21:39:37 ‹ezee› got it
21:39:43 ‹Elieser› you can't add a widget inside other widget
21:39:57 ‹Elieser› so we will end with something like:
21:39:58 ‹ezee› ok
21:40:21 ‹Elieser› ui->pluginsGroupBox->layout()->addWidget( ... );
21:40:41 ‹ezee› ok
21:40:45 ‹Elieser› pluginsGroupBox->layout() is the vertical layout create in the UI editor
21:40:54 ‹Elieser› you can set a layout in the code too, off course
21:40:57 ‹ezee› ok
21:41:06 ‹Elieser› the last puzzle piece
21:41:28 ‹Elieser› you will need a button and a label (to show the plugin name)
21:41:30 ‹Elieser› right
21:41:43 ‹Elieser› so you, need create a QWidget
21:41:56 ‹Elieser› put a button and a label inside this QWidget
21:41:59 ‹ezee› ok
21:42:07 ‹Elieser› and put this QWidget inside groupBox->layout()
21:42:16 ‹Elieser› this QWidget need a layout too
21:42:30 ‹Elieser› QWidget w = new QWidget();
21:42:46 ‹Elieser› w->setLayout( new QHBoxLayout());
21:42:54 ‹Elieser› horizontal layout
21:43:02 ‹ezee› ok
21:43:15 ‹Elieser› now you add a QPushButton and a QLabel in the new widget layout
21:43:23 ‹Elieser› wowow
21:43:29 ‹Elieser› Qt in 5 minutes
21:43:30 ‹Elieser› :)
21:43:36 ‹ezee› eh eh
21:43:42 ‹ezee› you rule !
21:43:47 ‹ezee› ;)

Thank you for that clinic on Qt elieser , i learned a lot !
;)

**Comment by Ezeer** [comment]
So your previous work on the detailed log is already useful for me , i can see where my code is activated in the program's logic : 
*INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
INFO:  Creating roomStreamer ...
INFO:  Starting portaudio driver using ASIO4ALL v2
INFO:  portaudio driver started ok!
INFO:  Connecting in Jamtaba server...
INFO:  "Starting Jamtaba 2.0.3 Standalone (i386) running on Windows XP (i386)"
INFO:  Creating MainWindow...
INFO:  Initializing local inputs...
INFO:  	Creating channel  "your channel"
INFO:  		Creating sub-channel 
INFO:  		setting Subchannel to no noinput
INFO:  Initializing local inputs done!
INFO:  MainWindow created!
INFO:  Restoring plugins list...
INFO:  Restoring plugins list done!

WARNING:  QMetaObject::connectSlotsByName: No matching signal for on_buttonAddBlackVst_clicked()static void QMetaObject::connectSlotsByName(QObject*) qobject.cpp3508

INFO:  Starting portaudio driver using ASIO4ALL v2
INFO:  portaudio driver started ok!*

BlackList : 
I have started to code an idea based on the searchPath for vst , but applied for .dll .

![capture d ecran 2015-10-26 23 39 49](https://cloud.githubusercontent.com/assets/1283808/10744490/964a8060-7c3a-11e5-9136-64f12140cb2e.png)

**Comment by elieserdejesus** [comment]
Nice Ezee, nice ideas!

Be carefull in the warning "No matching signal for
on_buttonAddBlackVst_clicked()". I think Qt is trying auto create the
signal/slot binding and is not working.  I suggest this:
http://doc.qt.io/qt-5/designer-using-a-ui-file.html#automatic-connections




Em segunda-feira, 26 de outubro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by Ezeer** [comment]
Thanks !
The problem was that i have used the visual editor to create the onClick() event , with PushButton as object's name.
So i have changed the default object's name to "AddBlackVst" and linked to the slot again .
Deleted the first PushButton onclick , but something was broken for the second onClick() generated for the AddBlackVst new name ....
Trials and fails ... eh eh

I'll check your document .
Ezee 
--------------------------------------------
En date de : Mar 27.10.15, Elieser Ademir de Jesus <notifications@github.com> a écrit :

 Objet: Re: [JamTaba] Keep a visual list of enabled Vsts ( and manage black list ) (#11)
 À: "elieserdejesus/JamTaba" <JamTaba@noreply.github.com>
 Cc: "Ezee" <h2oreggae@yahoo.fr>
 Date: Mardi 27 octobre 2015, 0h45
 
 Nice Ezee, nice ideas!
 
 
 
 Be carefull in the warning "No matching signal for
 
 on_buttonAddBlackVst_clicked()". I think Qt is trying
 auto create the
 
 signal/slot binding and is not working.  I suggest this:
 
 http://doc.qt.io/qt-5/designer-using-a-ui-file.html#automatic-connections
 
 
 
 
 
 
 
 
 
 Em segunda-feira, 26 de outubro de 2015, Ezee
 <notifications@github.com>
 
 escreveu:
 
 
 
 > So your previous work on the detailed log is already
 useful for me , i can
 
 > see where my code is activated in the program's
 logic :
 
 > *INFO: Reading settings from "C:/Documents and
 Settings/Salon/Local
 
 > Settings/Application Data/Jamtaba 2/Jamtaba.json"
 
 > INFO: Creating plugin finder...
 
 > INFO: Creating midi driver...
 
 > INFO: Initializing rtmidi...
 
 > INFO: rtmidi initialized!
 
 > INFO: Creating audio driver...
 
 > INFO: initializing portaudio...
 
 > INFO: Creating roomStreamer ...
 
 > INFO: Starting portaudio driver using ASIO4ALL v2
 
 > INFO: portaudio driver started ok!
 
 > INFO: Connecting in Jamtaba server...
 
 > INFO: "Starting Jamtaba 2.0.3 Standalone (i386)
 running on Windows XP
 
 > (i386)"
 
 > INFO: Creating MainWindow...
 
 > INFO: Initializing local inputs...
 
 > INFO: Creating channel "your channel"
 
 > INFO: Creating sub-channel
 
 > INFO: setting Subchannel to no noinput
 
 > INFO: Initializing local inputs done!
 
 > INFO: MainWindow created!
 
 > INFO: Restoring plugins list...
 
 > INFO: Restoring plugins list done!
 
 >
 
 > WARNING: QMetaObject::connectSlotsByName: No matching
 signal for
 
 > on_buttonAddBlackVst_clicked()static void
 
 > QMetaObject::connectSlotsByName(QObject*)
 qobject.cpp3508
 
 >
 
 > INFO: Starting portaudio driver using ASIO4ALL v2
 
 > INFO: portaudio driver started ok!*
 
 >
 
 > BlackList :
 
 > I have started to code an idea based on the searchPath
 for vst , but
 
 > applied for .dll .
 
 >
 
 > [image: capture d ecran 2015-10-26 23 39 49]
 
 >
 <https://cloud.githubusercontent.com/assets/1283808/10744490/964a8060-7c3a-11e5-9136-64f12140cb2e.png>
 
 >
 
 > —
 
 > Reply to this email directly or view it on GitHub
 
 >
 <https://github.com/elieserdejesus/JamTaba/issues/11#issuecomment-151304962>
 
 > .
 
 >
 
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Ezeer** [comment]
Thanks !
The problem was that i have used the visual editor to create the onClick() event , with PushButton as object's name.
So i have changed the default object's name to "AddBlackVst" and linked to the slot again .
Deleted the first PushButton onclick , but something was broken for the second onClick() generated for the AddBlackVst new name ....
Trials and fails ... eh eh

I'll check your document .

**Comment by Ezeer** [comment]
**Something cool with the BlackList concept :**
Not only you prevent the application for a crash with a bugged/incompatible vst , BUT you can also speed the loading time of Jamtaba . ( If you have a biiiiig vst folder and have some vsti that u know u won't use ).
And yeah , multi-select will be allowed !
I think to modify the VstSettings class to record on the .json file the blacklisted vst .
//+++++++++++++++++++++++++++++++++++++++++++
class VstSettings : public SettingsObject{
public:
   VstSettings();
    void write(QJsonObject& out);
    void read(QJsonObject in);
    QStringList cachedPlugins;
    QStringList scanPaths;
    **QStringList BlackListed ;**
};
Perhaps add a second button , RemoveFromBlackList , to remove selected vsts from the .json , etc...
^^

**Comment by elieserdejesus** [comment]
Nice Ezee, good ideas!

**Comment by Ezeer** [comment]
pfffiou ...
i spent a lot of hours trying to understand Qt editor , layout system etc ....
Now i got it .
Finally elieser , your idea to use textbox instead of lines+button seem to be the right choice .
![capture d ecran 2015-10-29 05 50 06](https://cloud.githubusercontent.com/assets/1283808/10810393/d6508d54-7e00-11e5-96c1-bee550966516.png)

The big trick will be now to refresh the text automatically after the pluginFInder returns :
I know it emits a signal when done, but can i catch it from PreferenceDialog ?
Then launch populateVst() to refresh is easy to do .

**Comment by elieserdejesus** [comment]
Ezee, In *MainWindow::on_preferencesClicked* the *PreferencesDialog* instance is created in the local scope, so unfortunally we don't have a reference to this object in *MainWindow::onScanPluginsFinished()*.

A solution is catch the signal emmited by *PluginFinder* in *PreferencesDialog*.

In *PreferencesDialog* constructor write this:
```
if(mainController){//just in case
    QObject::connect( mainController->getPluginFinder(),
                      SIGNAL(scanFinished()),
                      this, 
                      SLOT(onPluginsScanFinished));
}
```
declare your slot *onPluginsScanFinished* in *PreferencesDialog.h* in the section *private slots*:
```
private slots:
	// ... other slots
	void onPluginsScanFinished();
```
and in *PreferencesDialog.cpp*

```
void PreferencesDialog::onPluginsScanFinished(){
	//update your text component with the new plugin list here
}
```

**Comment by Ezeer** [comment]
ah ah ah ! Thank you boss !
![thank-you-card-message-to-boss-from-employee](https://cloud.githubusercontent.com/assets/1283808/10818241/3e71c030-7e40-11e5-8993-e295c388d1e4.jpg)

**Comment by Ezeer** [comment]
Done !
But i have a error in compil
>E:\Qt\JamTaba2\build-Jamtaba-Desktop_Qt_5_5_1_MinGW_32bit-Debug\Standalone\debug\moc_PreferencesDialog.cpp:223: erreur : multiple definition of `PreferencesDialog::onPluginsScanFinished()'

because of that declaration in moc_.PreferencesDialog.cpp
// SIGNAL 1
void PreferencesDialog::onPluginsScanFinished()
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}
QT_END_MOC_NAMESPACE

What the hell is that moc_ generated file ?
Doc ?
^^

**Comment by elieserdejesus** [comment]
Ezee, mocs are the C++ files auto generated by Qt. 

Try two things:
1 - Right click in the project name and run "QMake". This force the recompilation of slot/signals added, the MOCs are recreated.  

2 - Check your PreferencesDialog.h and .cpp for duplicated onPluginsScanFinished()

**Comment by Ezeer** [comment]
ok , i have since commented out and that works : 
>/* SIGNAL 1
void PreferencesDialog::onPluginsScanFinished()
{
    QMetaObject::activate(this, &staticMetaObject, 1, Q_NULLPTR);
}*/

cool !
I'm gonna code the blacklist again , and perhaps tonight the baby will be born ..
^^

**Comment by Ezeer** [comment]
Aaarrg...
The signal was not catched , jamtaba was reading the .json file .
But i'm on it , gonna have that holy sheet ( poetry ... ^^ ) works !

**Comment by elieserdejesus** [comment]
Ezee, I'm 90% shure your comment solution will be a problem. Never change the Qt auto generated files, because this files will be re-created and your changes are deleted. 

If you click in "Rebuild" you see this problems. Or if you use "Clean" and "Run" all MOCs are recreated.

If you have some problems to identify this error please push your branch and I can try help.

**Comment by Ezeer** [comment]
**If you have some problems to identify this error please push your branch and I can try help.**
i love the way you are eh eh .

**Comment by Ezeer** [comment]
yah know , i push for that baby lika woman ...
eh eh
https://github.com/elieserdejesus/JamTaba/pulls

**Comment by elieserdejesus** [comment]
Ezee, you write the **void onPluginsScanFinished();** in **signals** class section. Just change the *onPluginsScanFinished* to the **private slots:** class section, after the **void on_recordingCheckBox_clicked();**.

**Comment by Ezeer** [comment]
so you push now ?

**Comment by elieserdejesus** [comment]
Ezee, the code is not working, the signal is not catched. I will see this problem in one hour.

**Comment by Ezeer** [comment]
Ok , it is just a minor bug anyway .
I start to code the blacklist now
thx

**Comment by Ezeer** [comment]
So i added a refresh button for the user , working fine .
![capture d ecran 2015-10-29 16 01 30](https://cloud.githubusercontent.com/assets/1283808/10822080/d0746cf2-7e55-11e5-89af-f5f66d032838.png)

But auto-update is still broken .
I merged that stuff doc !
![4526481-3031949089-28074](https://cloud.githubusercontent.com/assets/1283808/10822144/2579b9aa-7e56-11e5-8972-5178b1c32be5.jpg)

**Comment by Ezeer** [comment]
Hey guys , we gonna have a nice blackbox : 
![capture d ecran 2015-10-29 16 27 06](https://cloud.githubusercontent.com/assets/1283808/10822881/3d92b12e-7e59-11e5-93a0-960e2cff0623.png)

A red color for the text inside of black box , or white ?
Doc ?

**Comment by elieserdejesus** [comment]
Red is good :)   I'm pushing the fixed code right now, some little problem with branch names heres, just a minute.

**Comment by Ezeer** [comment]
Hey doc , what about ... ORANGE ?
mwah ah ah ah ...
![bugs-bunny-4](https://cloud.githubusercontent.com/assets/1283808/10823011/dc497f82-7e59-11e5-95ef-d9de1468102a.png)

**Comment by elieserdejesus** [comment]
Fixed, pull to see the fix Ezee.

**Comment by Ezeer** [comment]
got an error here after the pull : 
>E:\Qt\JamTaba2\Client\VstPlugin\VstMain.cpp:13: erreur : expected constructor, destructor, or type conversion before '(' token
 #define VST_EXPORT _declspec(dllexport)

Perhaps Due to : Error Could not decode VstMain.cpp with Utf-8 encoding

I already had that type of error , i choosed one arbitrarly from the list , but that is too ugly ...
So my question is , wich should i use ?
                             ^

**Comment by elieserdejesus** [comment]
Ezee, the simple way to avoid these problems is open just the subproject
you are working. If you are working in Standalone try open the
"Standalone.pro" directly in QtCreator. If you are opening the Jamtaba.pro
all subprojects will be loaded, and you can have some problems. I will
write about this in wiki soon.

Another solution is open the file Jamtaba.pro and comment the line

SUBDIRS += VSTPlugin

and after this, right click in project name and run "qmake". Qmake will
parse your Jamtaba.pro file and the VST plugin subproject will dissapear in
your project tree (left side in QtCreator).


But every time you run a pull you have a new Jamtaba.pro, and if the
VSTPlugin subproject is uncommented you will see the error again. So, the
first solution is the best, just open the Standalone.pro file.


I think the error you pointed is in "_declspec(dllexport)".  This is a msvc
only stuff. It's needed to export the "VSTMain" function in the plugin DLL.
Without this the VST hosts can't see the "VSTMain" function in Jamtaba DLL,
and the plugin is not recognized as a plugin. I spend some minutes of my
life trying understand why the plugin was not recognized, and I see the
EXPORT stuff commented in the code. So, I say to myself: Owww myyy
goooodddd!!! Fuck, fuck, and one more fuck! hahahaha


Elieser

Em quinta-feira, 29 de outubro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by Ezeer** [comment]
ah ah ah , Homer on his greaaat stylee !
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/1283808/10824860/94e36a5a-7e62-11e5-8b04-7a3e9cdf06ba.jpg)

**Comment by Ezeer** [comment]
Ok doc , that rocks now !
thank you for the fix .
I continue with the blackbox

**Comment by elieserdejesus** [comment]
Ezee, when I click in "Clear cache" the text box it not cleared. Please add more this little task in your stack :)

**Comment by Ezeer** [comment]
ah ah ah ....
Ok doc , i am on it !
^^

**Comment by Ezeer** [comment]
Little task merged .

I am in the blackbox now !
![a_bugs_bunny_pc](https://cloud.githubusercontent.com/assets/1283808/10827646/6dba746a-7e70-11e5-854d-5d7cc1c22592.jpg)

**Comment by elieserdejesus** [comment]
Haha, this picture is the best :)

**Comment by Ezeer** [comment]
lol
I have a demo version in VstTab branch if you wan' test the funk doc .
But no data is stored yet .

**Comment by elieserdejesus** [comment]
Nice Ezee, the orange looks nice :)  The black listed plugins are not filtered yet in scanning, right?
![image](https://cloud.githubusercontent.com/assets/1012741/10830297/0efb5a84-7e66-11e5-8805-0dbc2f2dee38.png)

**Comment by Ezeer** [comment]
Oooh yeah doc ! Good Job with the Orange border !
U'right , it's not filtered now .
I have to cook then eat if i don't want to die , then i'll continue that cool stuff !
![6a00d83451bab869e2011570468c5e970c-800wi](https://cloud.githubusercontent.com/assets/1283808/10830378/978e78f4-7e7f-11e5-8bca-15649cd695aa.png)

**Comment by elieserdejesus** [comment]
Bon appétit!

**Comment by Ezeer** [comment]
Merci ! eh eh

**Comment by Ezeer** [comment]
Semi implemented Blackbox is able to write in config file now : 
>{
    "PrivateServer": {
        "password": "",
        "port": 2049,
        "server": "localhost"
    },
    "VST": {
        "BlackListPlugins": [
            "C:/Program Files/REAPER/Plugins/elastique2.dll",
            "C:/Program Files/REAPER/Plugins/elastique3.dll",
            "C:/Program Files/REAPER/Plugins/elastique21.dll"
        ],
        "cachedPlugins": [
            "C:/Program Files/REAPER/Plugins/Classic Master Limiter.dll",
            "C:/Program Files/REAPER/Plugins/DSK B3x/DSK B3x.dll",
            "C:/Program Files/REAPER/Plugins/DSK Brass/DSK Brass.dll",
            "C:/Program Files/REAPER/Plugins/FA3_Full.dll",
            "C:/Program Files/REAPER/Plugins/Guitar Amp 2.0 FE.dll",
            "C:/Program Files/REAPER/Plugins/jb_barricade_pro.dll",
            "C:/Program Files/REAPER/Plugins/Pedals.dll"
        ],
        "scanPaths": [
            "C:/Program Files/REAPER/Plugins"
        ]
    }
...
you can test at this push ( tabVstt branch ): https://github.com/elieserdejesus/JamTaba/commit/c11b7ff38e255e1e7f64dcfdf254808d097a8eb5

**Comment by Ezeer** [comment]
Blackbox now updates at populateVst()
https://github.com/elieserdejesus/JamTaba/commit/41fda4040fe7b938f89be62a5a3355de847997ed

**Comment by Ezeer** [comment]
Before finalize that Blackbox filter , i suggest : 

WRITE THE .JSON FILE ON DISK BEFORE THE APP CRASH .
So perhaps when the mainWindow is up and before loading the vsts  , create and SAVE the config .
( because users will be able to tweak by adding a line to BlackVstList if Jamtaba crashed because
of a bad vst at loading time ) .

**Comment by elieserdejesus** [comment]
Igree, very good idea.

**Comment by Ezeer** [comment]
Can you take that ?
Also you got a pre release of the blackbox on pull request , but that can wait .
Take it if you wan' to code the filter yourself , for example ...
^^

**Comment by elieserdejesus** [comment]
Ok Ezee, I can work in these 2 tasks
1 - Save config before start scanning
2 - filter black listed plugins

**Comment by Ezeer** [comment]
AH yes !
As usual , you are facing the goal keeper , and ....
![homer_simpson_fc_nantes](https://cloud.githubusercontent.com/assets/1283808/10834859/56c46b94-7e9d-11e5-84bb-9fcf4942afd7.jpg)

**Comment by Ezeer** [comment]
**GOOAAAAL !!!!!!!!**

I made a clear cache then rescan , the blacklisted was not loaded !
![capture d ecran 2015-10-30 02 12 41](https://cloud.githubusercontent.com/assets/1283808/10836225/651589b8-7eab-11e5-9838-3e78ccd29ee7.png)

**Comment by Ezeer** [comment]
Now it's time to call our good testers to find out the bugs and have new ideas with that baby ?

I propose to : 
_Make a crash test ( load a vst that will crash jamtaba )
Edit the .json manually , set the line that point to the bad vst , relaunch .

**Comment by elieserdejesus** [comment]
Man, I'm too tired to run this test. If have some energy I can upload a DLL from KorgLegacy plugin. I never fix the bug in this plugin.

**Comment by Ezeer** [comment]
ok , do that , thx !
i'm tired too .. but very happy again for that good result !
good job Elieser !

**Comment by elieserdejesus** [comment]
Ezee, thanks for your hard work and to get envolved, you are a great partner!
I will do the test tomorrow, I have at least one bad plugin here to test :)
See you!

**Comment by Ezeer** [comment]
hey ... that give me a new idea : 
YOU CAN PREVENT CRASH BY CREATING A DEFAULT LINE IN THE DEFAULT CONFIG FOR
THAT PLUG
( the only problem is the path ... we will need to check the names only , not the path i think to have
real freedom - because it could be installed everywhere ... )

Good night my friend , i'm gonna have some good rest too .
;)

**Comment by Ezeer** [comment]
i made some tests and found that we need to code : 
_ AUTO CLEAR THE CACHE
_ REDO A SCAN
after the user has choosen the vst(s) to exclude

**Comment by elieserdejesus** [comment]
Ezee, I test the black list putting the Korg LegacyCell.dll manually in black list (changing json). Works, when I start Jamtaba with a cleared VST list the audo scan starts and the black listed plugins are skiped, no crash.  

I add some log to see the scanned paths. I hope this help in future problems with users plugins.

**Comment by elieserdejesus** [comment]
One more thing: you add the button "Refresh" in Vst TAb. Now we have the button "Scan" in the top and the button "Refresh" in the botton. We need these two buttons?

**Comment by Ezeer** [comment]
Thank you dear leader for your crash test and ergonomy report !
Well , i was not thinking to modify tha work that was done before me , but yeah you've found
a case where it can be merged .
The refresh button now is refreshing all the TabVst , so ... You can remove it safely i think.

**" i add some log to see the scanned paths. I hope this help in future problems with users plugins. "**
Perfect !
;)

**Comment by Ezeer** [comment]
Wait wait wait  ....

**Comment by Ezeer** [comment]
Ok , it is safe now to delete the Scan button : https://github.com/elieserdejesus/JamTaba/commit/b850bdbd3280ee95061cc6e71671dd1bfe9aac02

**Comment by elieserdejesus** [comment]
Ezee, Qt logging has the built in log leves using macros:
```
qInfo() << "Some info";
qDebug() << "Some debug, usefull for programmers only in debug time";
qWarning() << "Using this when some problem is dected but I have a fallback solution";
qCritical() << "Now the problem is serious, like 'Portaudio can't initialize using negative sample rate'";
qFatal( "End of the game, some very serious shit here!);
```

In the file **qtlogging.ini** we can disable and enable categorized logging.

**Comment by Ezeer** [comment]
Okay , but i was thinking to give the hand to the end user by an editable entry in the config file.
You now , LogLevel=0 by default with a working Jamtaba.
If the user has a problem , he can set log=1 and retrieve moe information .
In case of severe crash , log=3 .

So we could code that using Qt logging , that's what you are saying ?

**Comment by Ezeer** [comment]
I remember the cas eof plJones who requires some log about his midi devices , perhaps also with
vist ports , etc ...
That kind of stuff could be accessible for advanced users , with log=1 or 2 .
Just an idea .
^^

**Comment by elieserdejesus** [comment]
I understand now Ezee, it's about "editable" log, or something like that. 
Two things agout this:
1 - At moment the qtlogging.ini is embbeded in executable, so users can't access this file. We need "externalize" this file :)
2 - Some categories in my qtlogging are messed, the names are not clear, we really need some more polished.  

I will create a new issue to this, I think this is an enhancement for advanced users.

**Comment by Ezeer** [comment]
**I will create a new issue to this, I think this is an enhancement for advanced users.**
I agree !

Hey , i forgot to code the " Remove Vst from black list " ....
Got to do it now .

**Comment by Ezeer** [comment]
Nightmare tonight .... big issues with git , corrupted file etc ...
I think i fixed that , but need to be tested .
The actual state should be : 
![capture d ecran 2015-10-31 02 53 52](https://cloud.githubusercontent.com/assets/1283808/10861266/29bededa-7f7a-11e5-8331-22d3b404d923.png)

**Comment by elieserdejesus** [comment]
Ezee, the git merge loose some modifications. I will try fix here in some minutes. 
So, I think is never a good idea work in same files. Sometimes git merge can't do magic :)

**Comment by Ezeer** [comment]
Yes , but you are a better magician than me ....
![apprenti_sorcier](https://cloud.githubusercontent.com/assets/1283808/10861350/fd8433f4-7f7b-11e5-8435-babc4f42f4f4.jpg)

**Comment by Ezeer** [comment]
Your last work on the log was lost ? Ow noooo ...

**Comment by elieserdejesus** [comment]
No, the log is here :)   Loose some GUI stuff, but is easy to redo.
I fixing now, finishing in 5 minutes.

**Comment by elieserdejesus** [comment]
Ezee, the is the result, please check if now we have the same code version:
![image](https://cloud.githubusercontent.com/assets/1012741/10861511/f9801434-7f68-11e5-8faa-533eb441ead1.png)

**Comment by Ezeer** [comment]
wow ! Nice Design , i like it !
I don't have pulled the code yet .

**Comment by Ezeer** [comment]
Tested , runs fine !
We work so well together , your final touch is perfect .
I consider that task like done , please close it if you consider it's done .
Thanks !

**Comment by elieserdejesus** [comment]
Ezee, just two more things to tweak and we are done:
1 - Where you code the color of black list? black background and orange text? I can't find in the code or in the .css file
2 - I see the text area for the loaded plugins is not transparent in your machine. This is a easy fix in the CSS file.

**Comment by Ezeer** [comment]
**1 - Where you code the color of black list? black background and orange text? I can't find in the code or in the .css file**

i have used the visual editor properties .
It is meant to be changed by the user ?
Please make any changes that you think are needed 
:)

**Comment by elieserdejesus** [comment]
Ezee, I will keep the colors, but change the code to jamtaba.css file. This file contains all color scheme and a lot of other visual things.

**Comment by Ezeer** [comment]
No problemo .
I realized after how stupid was my question .
( i was writing " Jamataba is higly configurable " in the User's guide ...
lol

And i should learn these css things on jamtaba , i know i know ...
How will i write about that without knowing it before ?
So you do or i do ? ( if you want quick changes , please do ... ^^ )

**Comment by elieserdejesus** [comment]
Ezee, the colors can't be changed by final users because the jamtaba.css file is a resource file, embbeded in Jamtaba.exe. So I think we don't need a antry to explain the css file in the wiki. I have an idea to a ThemeEditor applicaiton, so users can change the colors. But is a idea for the version 3.41.56 :)

**Comment by Ezeer** [comment]
ah ah ah ah .....
But there is an option " Themes " in the menu .
Related to the version  3.41.56 ?
^^

**Comment by elieserdejesus** [comment]
yeah, this is a shame :) I will remove the theme menu right now.

**Comment by Ezeer** [comment]
ah ah ah ah ...
It's good to comment for no-thing also !
![25834f8](https://cloud.githubusercontent.com/assets/1283808/10866050/b0bae68a-8020-11e5-8867-fa17f8718549.jpg)

**Comment by elieserdejesus** [comment]
This issue is done, right? All features working if I remember corrent, so I'm closing...
