### ISSUE TITLE
Strange connection behaviour

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1101]
Scenario

I'm testing a Release build of HEAD of the master branch, `git fetch` run this morning and no updates found, so it's up to date.  I've also named the VST DLL uniquely so that MuLab can identify it clearly (it uses the filename).

1. Run MuLab (you need the paid version to get ReWire; other hosts may be suitable)
2. Insert Reaper via ReWire into a rack slot
3. In Reaper, insert ReaNINJAM into the master rack
4. In ReaNINJAM, connect to a room on a Ninjam server
5. In MuLab, insert Jamtaba into a slot in a different rack

At this point, Jamtaba starts network activity, displaying the room maps with user locations, along with the public chat room.  Except the public chat room says "Connecting ..."

6. In Jamtaba, start up video (the second, remembered, channel becomes the video channel)
7. In Jamtaba, attempt to connect to the same room as in ReaNINJAM

**Expected result**
Jamtaba should connect successfully and the connection should be seen in ReaNINJAM.
![image](https://user-images.githubusercontent.com/1549463/39395399-3aa8905e-4ad6-11e8-8c2b-27758147c959.png)

**Actual result**
Jamtaba's connection hangs, with the "wait" indicator giving up after a while but no connection having been made.

8. In ReaNINJAM, disconnect
9. In MuLab, remove Jamtaba from the rack slot used

**Expected result**
Jamtaba should not be running.

**Actual result**
Shortly after this point, the following appeared:
![image](https://user-images.githubusercontent.com/1549463/39395436-6a931118-4ad6-11e8-87aa-aa237cda0506.png)

So it looks like Jamtaba didn't clean up a pending connection when being told to exit.  Exiting MuLab leaves a dangling process that triggers a MuLab error once the pop-up gets acknowledged.

**Alternative path**
If you stay waiting in Jamtaba long enough for the connection failure pop up, you also get kicked from the public chat.  Whether you'd ever connected to it, I don't know...

**Comment by pljones** [comment]
OK, additional problem.

1. Run Reaper
2. Insert a track
3. Insert Jamtaba on the master
4. Click "Listen" on a populated server

**Expected result**
You should hear whatever's happening

**Actual result**
![image](https://user-images.githubusercontent.com/1549463/39395697-814a8960-4ad9-11e8-98bf-3a93ac512ce4.png)

Note that entering the populated room is successful.

**Comment by jonjamcam** [comment]
Hey @pljones . One question. If you don't use reaper via rewire, I mean just Mulan hosting jamtaba, does it still happen?

**Comment by pljones** [comment]
@jonjamcam Actually, surprisingly, yes -- the plug-in appears to work okay in Reaper but seems to have connection issues from MuLab.  I can't think why MuLab would be preventing the connections, though.

**Comment by pljones** [comment]
Hm.  I also just got a burst of high volume audio when inserting the plugin (as if the audio buffers were passed through uninitialised).  Never had that before.

**Comment by pljones** [comment]
**Note**

The main point here is the error handling isn't working and handling closure notices from the host isn't working.

The VST should "hear" the host "saying" "I'm exiting" and clean itself up.  Jamtaba doesn't - it leaves a pile of mess around and the host will complain.

**Comment by pljones** [comment]
Closing as it's Windows *** firewall...

**Comment by pljones** [comment]
OK, here's some extra on how to test it.... 😊 

Disable the application hosting Jamtaba via Windows firewall settings.

Allow the application hosting ReaNINJAM via Windows firewall settings.

**Comment by pljones** [comment]
Double-checked Windows firewall...
![image](https://user-images.githubusercontent.com/1549463/39405075-145c393a-4b96-11e8-874b-58ffa558264b.png)
It's got the same settings as Reaper as far as I can see, so I don't think it's _that_ -- but I'm continuing to investigate as the networking settings in Windows Defender looked odd.

**Comment by pljones** [comment]
OK, so I tried the following with "2.1.5" (master/HEAD) and 2.1.4 actual release.  With 2.1.4, everything worked smoothly.  With 2.1.5, I get the following:
```
1. Start Reaper
2. Insert new track
3. Show master FX window and add Jamtaba
4. Connect to a NINJAM server

*Expected & Actual result*
Connection to server is successful.

--
1. Start MuLab
2. Add a track
3. Insert Jamtaba into a master rack slot
4. Connect to a NINJAM server

*Expected result*
Connection to server is successful.

*Actual result*
Connection times out.

--
1. Start Reaper
2. Insert new track
3. Show master FX window and add MUX; open the modular area of the basic effect preset, replace the mixer strip with a rack and wire up event inputs and outputs
4. Insert Jamtaba into a slot on the rack
5. Connect to a NINJAM server

*Expected result*
Connection to server is successful.

*Actual result*
Connection times out.
```
So something significant has changed in the network behaviour.

**Comment by elieserdejesus** [comment]
> So something significant has changed in the network behaviour.

1 - I can't remember network code changes.
2 - The last version is using QWebSocket, but for the public chat only. Maybe this is some Qt network issue when websocket is used.

**Comment by pljones** [comment]
@elieserdejesus I'm just trying to check if it's my local build causing the issue.  I've reverted to 2.1.4 and -- because the 2.1.4 static libraries aren't still available for building that release -- I've applied the h264 codec change (5e85f57).  That build has the same issues, so it looks like I'm still not getting correctly working builds here.  Oh well.  😢

**Comment by elieserdejesus** [comment]
I don't have the old static libs, so I think is not possible compile the 2.1.4 using the "correct" libs.

Another network related thing: the **miniupnp** library is communicating with your router trying to open a port (on when you are hosting a private server). Maybe this lib is generating some side affect, but is just an almost random guess :)

**Comment by pljones** [comment]
I have my router pretty locked down.  Anything like that is likely to get something black listed.  Nothing should be trying to interfere with my router setting except when authenticated as me.  This could lock me out of my router.

**Comment by pljones** [comment]
OK, I can confirm the connection problems appear to be build-related.  I'll close this ticket as that could also be affecting the error handling (i.e. if the networking library is causing problems, it could be causing problems with handling errors, too).
