### ISSUE TITLE
allow camera on/off status to be saved in json file or avoid 2nd channel to be created at launch

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1104]
I find this to be a visual issue. As camera status is always off ATM when starting Jamtaba, if you did use the video channel in a previous session, then the second channel is created with a video icon, but as audio only.  This has the appearance of a bug.

On the other hand if the idea is that the camera will be always off at launch, then I believe it is better that the second audio channel is not created at launch.

Personally I like the first option (camera status saved in json file)

(probably this issue is related with https://github.com/elieserdejesus/JamTaba/issues/1038)

**Comment by elieserdejesus** [comment]
I see the code and was easy skip the 2nd channel creation. It's done in https://github.com/elieserdejesus/JamTaba/commit/caf8db80c7fee6cfc08d47d62cd7940f87f75f80

I created a separated issue to handle camera on/off saved in jsonhttps://github.com/elieserdejesus/JamTaba/issues/1105
