### ISSUE TITLE
Help to test the new Beta!

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1106]
Hello everybody! A new JamTaba beta is available (v2.1.5)! 

If possible please download the beta and play some jams to check if it's working fine and stable enough to release.

Thansks in advance!

@jonjamcam , @pljones , @Hitrate , @qulf , @MagnusDrumsTrumpet , @DoublebassOO

**Comment by elieserdejesus** [comment]
the link: https://github.com/elieserdejesus/JamTaba/releases

**Comment by MagnusDrumsTrumpet** [comment]
i will )
 were is it
 and isnt it 2.6.5
cool eli ) i am so curious like cat  hehe
 

    Am Montag, 30. April 2018, 17:06:10 MESZ hat Elieser Ademir de Jesus <notifications@github.com> Folgendes geschrieben:  
 
 
Hello everybody! A new JamTaba beta is available (v2.1.5)!

If possible please download the beta and play some jams to check if it's working fine and stable enough to release.

Thansks in advance!

@jonjamcam , @pljones , @Hitrate , @qulf , @MagnusDrumsTrumpet , @DoublebassOO

**Comment by pljones** [comment]
(...Why can't I get _my_ builds to just work... 😭 ...)

Anyway, this build seems to work.  I've tried it in MuLab, with Reaper rewired running ReaNINJAM.  Instruments in both hosts successfully exchange audio with the other client via the server.  Video does not seem to interfere.

**Comment by elieserdejesus** [comment]
Hi @MagnusDrumsTrumpet , this is the link: https://github.com/elieserdejesus/JamTaba/releases

**Comment by elieserdejesus** [comment]
@pljones , I will create a new ticket to investigate this emoji issue.

**Comment by elieserdejesus** [comment]
@jonjamcam , @pljones , @Hitrate , @qulf , @MagnusDrumsTrumpet , @DoublebassOO, a new beta (v2.1.5-beta.2) is released. 

@DoublebassOO , can you test this new beta to see if video is still crashing, please?

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.5-beta.2

**Comment by elieserdejesus** [comment]
JamTaba v2.1.5 released, thanks!

**Comment by MagnusDrumsTrumpet** [comment]
hey Eli, thankyou for that beautiful Updates, the last qtwo you done with mich work again)i sadly found out that if i use jamtaba noe and loop something to jamtaba from external looper it doesnt sync after a time slipps away sadlymoe and more    never had that before   with our super internal looper all is fine  so somehow it has a minimal incorecct of timeholding somehowif i use reaninjam with same stuff it is perfect in time on hours 
sorry i hit your nerves with this  
maybe you can fix it in future time ) thank you for your outstanding work always) Stay healthy) 
 Magnus
    Am Mittwoch, 4. Juli 2018, 13:17:09 MESZ hat Elieser Ademir de Jesus <notifications@github.com> Folgendes geschrieben:  
 
 
JamTaba v2.1.5 released, thanks!

**Comment by MagnusDrumsTrumpet** [comment]
seems ther is alittle lack at the end of the bpi always like alittle dropout always 
i took th2018 version again and works normal without slipping

    Am Sonntag, 5. April 2020, 15:43:03 MESZ hat jojo jo <jojo4u72@yahoo.com> Folgendes geschrieben:  
 
  
hey Eli, thankyou for that beautiful Updates, the last qtwo you done with mich work again)i sadly found out that if i use jamtaba noe and loop something to jamtaba from external looper it doesnt sync after a time slipps away sadlymoe and more    never had that before   with our super internal looper all is fine  so somehow it has a minimal incorecct of timeholding somehowif i use reaninjam with same stuff it is perfect in time on hours 
sorry i hit your nerves with this  
maybe you can fix it in future time ) thank you for your outstanding work always) Stay healthy) 
 Magnus
    Am Mittwoch, 4. Juli 2018, 13:17:09 MESZ hat Elieser Ademir de Jesus <notifications@github.com> Folgendes geschrieben:  
 
 
JamTaba v2.1.5 released, thanks!
