### ISSUE TITLE
beta 2.1.5

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1109]
Hi all   and bravo to still make improvement  !

some bug on my side 
first i need to connect twice or more "host not find"

second when opening the cam after one minute jamtaba or even one time reaper crash ..  but not  without using video 

need i to report more precision

still colors change after two or more posts

win7pro  jamtaba beta as vst in reaper 5.78

**Comment by elieserdejesus** [comment]
In my side the video is not crashing, but when using video I hear a lot of cracles, so I shure something is not working like expected.

**Comment by pljones** [comment]
Ah, I was going to mention the crackling but I wanted to test further.  So I can confirm that :).

There's some weird behaviour on the mixer for users - it's too subtle to explain, as I was only partly aware of it.  It "felt" as it the user mixer channels were moving around -- but the chat window didn't show disconnect/connects that might have caused it.  @DoublebassOO -- is that what you meant by "colors change"?

**Comment by elieserdejesus** [comment]
>  It "felt" as it the user mixer channels were moving around

I saw this too. The channels are being reorded. I created an issue: https://github.com/elieserdejesus/JamTaba/issues/1110

**Comment by elieserdejesus** [comment]
The color changes mentioned by @DoublebassOO are related to chat text colors. I see this bug today too, some messages are using wrong colors (2 messages from same user but using different colors). 

Reopening the issue: https://github.com/elieserdejesus/JamTaba/issues/1070

**Comment by elieserdejesus** [comment]
Maybe (hard to test) the last commit https://github.com/elieserdejesus/JamTaba/commit/b8f06e590521f1f0885577837e0b0403bce84e51 fixed the audio cracles problem.

**Comment by DoublebassOO** [comment]
all seems fine on my side with the last beta 3    no more disconnection no more trouble...
only the text that disappear from the screen when typing and someone enter in the room . (but  i can find it back when scrolling in the chat )  Bravo again  !! great version for windows 10

**Comment by elieserdejesus** [comment]
JamTaba v2.1.5 released, thanks!
