### ISSUE TITLE
Add visual feedback when receiving midi

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#111]
Add some visual feedback when receiving midi messages. At moment we need insert some plugin to check if midi input is working. Reaper show a thin red line when midi messages are received, and the height of line is proportional to the received velocity.

**Comment by Ezeer** [comment]
I want a blue color , i want a blue color , i .....
lol

**Comment by elieserdejesus** [comment]
hehe, let's open another issue to discuss the color.

**Comment by Ezeer** [comment]
For accessibility , an audio signal would be nice too ( on mouse over the widget )

**Comment by Ezeer** [comment]
So the right place to code that is here i guess : 
>829 void MainWindow::timerEvent(QTimerEvent *){
...
//update local input track peaks
    foreach (TrackGroupView* channel, localChannels) {
        channel->updatePeaks();
    }}

we need to code something like : 

//update local MIDI input LED
    foreach (TrackGroupView* channel, localChannels) {
        channel->updateMidiLED();

**Comment by elieserdejesus** [comment]
It's a good place. Another solution is reuse the channel->updatePeaks. Inside this method we can update audio and MIDI "peaks". 

But I don't know yet how signalize the midi peaks. The audio peaks are computed in every audio call back. Look at AudioNode::processReplacing, line 104:
```
lastPeak.update(internalOutputBuffer.computePeak());
```

Maybe a similar aproach to comput MIDI "peaks". But I think the midi peak need be computed in the class LocalInputAudioNode because in this class we are doing the midi filtering by channel, midi device, etc. Every local input need compute your own midi peak.

The AudioNode class has a method
```
AudioPeak getLastPeak() const;
```

I think in two possible approaches:
1 - Rename the getLastPeak() to getLastAudioPeak() and add a new getLastMidiPeak()
2 - Keep the getLastPeak, but change the returned type (AudioPeak) to something more abstract: Peak. Add a new field in Peak class/sctructure to store the last computed midi peak. In most cases this value will be 0 (no midi input), but the LocalInputAudioNode class will put some usefull value in this field.  The GUI classes check for this value and draw something if the value returned is > 0.

**Comment by Ezeer** [comment]
" Maybe a similar aproach to compute MIDI "peaks".  "
I think the term 'peak' is misleading .
You want to show the midi activity AND the velocity ( good for fine tuning vsti + midi devices ) .
That information is given in each midi message , there is no computation to do i think , only updates
done for example in doProcessAudio() where you started to catch CC Messages .

Perhaps just blink a led when you receive noteOn , and more leds depending of the velocity ?
( a led can be a region in your peakmeter picture )

I'll look to the funks you're talking about .

**Comment by elieserdejesus** [comment]
done!

**Comment by Ezeer** [comment]
wow ! i'm curious to see what you've done !
cool .
