### ISSUE TITLE
Emoji issue -2.1.5 beta 2

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1112]
![image](https://user-images.githubusercontent.com/1549463/39642043-3062e382-4fc8-11e8-9361-5a77c0c61f2f.png)
Remote user said "nb levels" to ninbot.  ninbot displayed
> `<ninbot> (pljones@81.174.155.x -120 Db) ` (taken from ReaNinjam output)

Then the chat scrolled and the other ` -` prefixes all turned into thumb down signs, too...

So there's still something weird happening.

**Comment by pljones** [comment]
It needs to check for discrete text in the pattern matcher or random-looking things will happen.

**Comment by elieserdejesus** [comment]
Looking at the code I realized many emoji combinations are starting with the caracter ":", expect these four combinations: +1, -1, (y) and (n).

Changing all combinations to start with ":" is easy to detect +1 and -1 correctly. The new combinations will be:
- :+1
- :-1
- :n 
- :y 

The result:
![image](https://user-images.githubusercontent.com/1012741/39666469-64b17236-507a-11e8-9399-d7a5ef258f53.png)

**Comment by pljones** [comment]
How would (or should) `1-:-)(-:-1` parse..?

**Comment by jonjamcam** [comment]
I think the +1 and -1 shortcuts are generating more trouble than solving problems. Probably is best not using that combination

**Comment by elieserdejesus** [comment]
> How would (or should) 1-:-)(-:-1 parse..?

It's parsed correctly, the string contains only 2 valid combinations:

![image](https://user-images.githubusercontent.com/1012741/39673135-f36e50c4-510c-11e8-919d-5e3ee617cd08.png)
