### ISSUE TITLE
Transmit levels affected by "master" level?

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1121]
I'm still finding that JamTaba levels transmitted to a ninjam server are lower than when using ReaNINJAM.

I'm left having to assume that the "master" level - the level I want to hear the entire mix at - is affecting my send level.  This is, clearly, nonsense.  The level I hear my local mix at should have no effect on how loud I am to other users.

**Comment by elieserdejesus** [comment]
Tested the 4 scenarios again in VST plugin and found the same results. The master fader is not affecting the xmit level. 

The only thing reducing the xmit level is the pan law implemented in JamTaba. When the audio is centered the level is reduced in 3 dB.
