### ISSUE TITLE
in the first window of jamtaba 2.5beta some issue in the display of connected users in the chat

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1122]
In the rooms to play windows  of jamtaba vst  in reaper 
at the bottom right  i cant see the connected users in the public chat window , i need to click just a bit above the users to make the users name appearing. (even increasing the height view dont change the pb)
the names are colapsed at the bottom.
https://www.dropbox.com/s/hw9on064grcrglx/jamtaba%20connect%20users%20pb.JPG?dl=0

second question who are the connected users ;  the one using only the new jamtaba beta  ?  because i cant see some users who are using jamtaba standalone old version ?

**Comment by elieserdejesus** [comment]
@DoublebassOO , I tested the VST in Reaper and is working fine here. Are you using the[ last beta](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.5-beta.3)?

![image](https://user-images.githubusercontent.com/1012741/41604255-258952f0-73b5-11e8-9092-b24b272f81a0.png)
