### ISSUE TITLE
putting chords in jamtaba  syntax

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1124]
I am using lot chords input in jamtaba  but have some issue with some chords particulary.

i cant find where we discuss that in past  but  here some chords id like to be able to put in 

could we add   for instance  Cmajor chord s  CM  and CM7     only C7M and Cmaj7 seems to work   
 when writing CM in jamtaba it becomes  Cm after loading the progression

C6 G6 F6 ... refused as a chord in jamtaba  impossible to load it 

some even more important is when loading a progression the width of rectangles are not proportional with the length of the chords   ,   if that could be corrected  would be great . still on the last beta of jamtaba 2.5.1 that work flowly   great  work.  i think if  the mac version is as good  i should become the first class versoin

Thanks for your work and attention   ....   Cy Elieser

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , I confirmed your 2 first comments:

1 - CM and CM7 are not working as expected (is replaced by **Cm**)
2 - F6, G6, etc are not recognized

***
> when loading a progression the width of rectangles are not proportional with the length of the chords

I can't reproduce your 3rd comment (about chord rectangles). Can you post a example where the rectangles are not proportional?
![image](https://user-images.githubusercontent.com/1012741/43356540-c3d0817a-9248-11e8-87f1-a1eb970653ba.png)

**Comment by DoublebassOO** [comment]
Hello  Eilieser
for the moment my soundcard is out enable to open jamtaba for taking you
capture


2018-07-28 14:31 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
Issue is partially solved in https://github.com/elieserdejesus/JamTaba/commit/edad01c4da73769ebcd142552075d719a6986375 and https://github.com/elieserdejesus/JamTaba/commit/7b2bc7f3d21c79ed5d2d756b766b97ed77ff494e

![image](https://user-images.githubusercontent.com/1012741/43369102-4b865680-933e-11e8-9506-b82c8f9466ec.png)

**Comment by DoublebassOO** [comment]
Here the problem  in image

 my sound card is becoming dead today seems working




2018-07-29 19:48 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by DoublebassOO** [comment]
thanks my good friend

2018-07-29 19:56 GMT+02:00 Armand Dumonteil <armanidu33@gmail.com>:
