### ISSUE TITLE
Jamtaba 2.1.6 32 bit vst- does not work inside Ohmstudio

### ISSUE THREAD

**Issue by Irockus** [elieserdejesus/JamTaba#1131]
I don't think the prior version worked either, but I do recall at one time a version which did work inside Ohmstudio.  If I use Jbridge I can get it to work, would like to do it without jbridge if possible.

**Comment by elieserdejesus** [comment]
Hi @Irockus, I will try fix this issue. I think JamTaba never directly worked in OhmStudio.

**Comment by Irockus** [comment]
You're probably right my memory might be failing me but I have a few old version so I'll test and I'll let you know if something did work natively at one time.
I appreciated Elieser and I'm very impressed with the recent 2.17 chord progression capabilities !
I have some more suggestions for the program and I will open some tickets for each one but as a preview here's what I was thinking.
Ability to drag and drop the plugins to a different order.
Ability to hold control and copy a plug-in to another Channel.
Ability to change time signature in a progression. Using multiple time signatures in a progression.
As an exampleSo the first 16 bars are for 4/4 and get repeated 3 times, and then we switch to 7/8For one repetition and then back  to 4 /4.
I imagine this one is going to be very difficult to implement as well as you can Envision from an end-user standpoint.In a daw of course you have measures and you just set the change when you want it.
I've had some fun doing things other than 4/4 with Jam tab of I explicitly setting the measures so that it fits into other time signatures like 68 78 54 74 etcetera, but I always wanted a way to do more than one as you can do in the door it might be too much to ask though and I would understand completely :)
Best regards to you and thank you for doing so much all the time !
Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone
-------- Original message --------From: Elieser Ademir de Jesus <notifications@github.com> Date: 10/15/18  4:55 PM  (GMT-06:00) To: elieserdejesus/JamTaba <JamTaba@noreply.github.com> Cc: Ira Miller <irockus42@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [elieserdejesus/JamTaba] Jamtaba 2.1.6 32 bit vst- does not work
  inside Ohmstudio (#1131) 
Hi @Irockus, I will try fix this issue. I think JamTaba never directly worked in OhmStudio.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/elieserdejesus/JamTaba","title":"elieserdejesus/JamTaba","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/elieserdejesus/JamTaba"}},"updates":{"snippets":[{"icon":"PERSON","message":"@elieserdejesus in #1131: Hi @Irockus, I will try fix this issue. I think JamTaba never directly worked in OhmStudio."}],"action":{"name":"View Issue","url":"https://github.com/elieserdejesus/JamTaba/issues/1131#issuecomment-430028300"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/elieserdejesus/JamTaba/issues/1131#issuecomment-430028300",
"url": "https://github.com/elieserdejesus/JamTaba/issues/1131#issuecomment-430028300",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [elieserdejesus/JamTaba] Jamtaba 2.1.6 32 bit vst- does not work inside Ohmstudio (#1131)",
"sections": [
{
"text": "",
"activityTitle": "**Elieser Ademir de Jesus**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@elieserdejesus",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"elieserdejesus/JamTaba\",\n\"issueId\": 1131,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"elieserdejesus/JamTaba\",\n\"issueId\": 1131\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/elieserdejesus/JamTaba/issues/1131#issuecomment-430028300"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392883664\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by elieserdejesus** [comment]
Very good ideas @Irockus !! Please feel free to open new tickets.

> Ability to change time signature in a progression

This is more complex and need some discussion. I'm not shure how implemen this idea in ninjam context.

**Comment by elieserdejesus** [comment]
The problem in OhmStudio is fixed, now JamTaba is working inside Ohm without JBridge:
![jamtaba ohm](https://user-images.githubusercontent.com/1012741/47012623-fd127400-d11a-11e8-86d7-245679d16b37.gif)
