### ISSUE TITLE
Lost settings and can't set audio input to stereo since upgrading Reaper

### ISSUE THREAD

**Issue by Jon30b** [elieserdejesus/JamTaba#1135]
When I went into Jamtaba for the first time since upgrading Reaper, I found my user name and channels were reset, and no audio input was set. Also it's not possible to set audio input to stereo (not enough available inputs to make stereo). I haven't made any updates to Asio4All or anything else.

**Comment by elieserdejesus** [comment]
Hi @Jon30b , you mentioned Reaper in your comment. Are you using JamTaba as VST plugin (inside Reaper) or Standalone?

I'm asking because the VST plugin can't control the number of input channels (mono or stereo).

**Comment by fab672000** [comment]
Maybe you can try the next release, I fixed few problems there that also should apply to windows platform.
