### ISSUE TITLE
Discord Server not showing user location

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1141]
![image](https://user-images.githubusercontent.com/15310433/48102245-5305a380-e211-11e8-8c8b-be0f45a7ee18.png)

Ninbot has no problems:

![image](https://user-images.githubusercontent.com/15310433/48102801-e93ac900-e213-11e8-8b96-15a254631a90.png)

**Comment by fab672000** [comment]
the ip field is an empty QString when user info is passed to geolocation, that's why we don't see anything.
Now I don't know why the server sends us an empty ip, it for sure is not in the geolocation code...

**Comment by elieserdejesus** [comment]
Fixed a bug in JamTaba server when the ip is not masked: https://github.com/elieserdejesus/JamTaba-Server/commit/9bc93c6a935291746d039bf70b89b72d4e7860f6

![image](https://user-images.githubusercontent.com/1012741/49025012-e16ea480-f181-11e8-8699-53dcde555023.png)

**Comment by fab672000** [comment]
nice!
