### ISSUE TITLE
Rooms disappeared!

### ISSUE THREAD

**Issue by jtrozos** [elieserdejesus/JamTaba#1145]
Rooms are not showing in Jamtaba 2.1.6.
It was working an hour ago. Thanks!

**Comment by HammertheBammer** [comment]
Yep servers aren't listed.. Can connect as a workaround manual via menu Ninjam > Connect to privateserver bu

**Comment by jonjamcam** [comment]
they were gone, but working ok now.

**Comment by elieserdejesus** [comment]
Cockos changed the public servers layout.. The bug is fixed now!!!
