### ISSUE TITLE
Crash in Win 7 when Launching Jamtaba from installer (Jamtaba x64 only)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#115]
![crash installer launch](https://cloud.githubusercontent.com/assets/15310433/11060657/5aa9be3a-8780-11e5-9b8a-d17d3c038534.jpg)

It works OK guys if I launch from desktop win7x64, Jamtaba 2.0.5RC3 64bits

**Comment by jonjamcam** [comment]
Still happening in 2.0.12 64bits version. THe x86 version works ok.

**Comment by elieserdejesus** [comment]
I think this is related with Windows 7 admin privileges. 
Jon. can you try run the Jamtaba installer as administrator?

**Comment by jonjamcam** [comment]
Tested. Running installer as admin solves the problem.

**Comment by elieserdejesus** [comment]
This is a Win 7 problem only. I remember something about a flag in the installer to ask user about admin privileges before start installing. I will check again.

**Comment by elieserdejesus** [comment]
@jonjamcam , I tried reproduce this error in a win 7 64 bits (inside virtual box) but I can't see the bug. But I checked the installer docs and see a flag to solve this problem. I'm attaching a 64 bits installer modified to run Jamtaba a admin after install. Can you test in your win 7 64 bits?

[Jamtaba 2 (64 bits) installer.exe.txt](https://github.com/elieserdejesus/JamTaba/files/299100/Jamtaba.2.64.bits.installer.exe.txt)

**Comment by jonjamcam** [comment]
@elieserdejesus For some strange reason downloading the file above is taking a very long time (1 hour estimate) I'll test once it's finished.

**Comment by jonjamcam** [comment]
Solved! Now it launches ok after install. Good job!. closing....
