### ISSUE TITLE
Remote channel narrow when transmitting video

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1155]
Transmitting video is making remote channel narrow (as if using two audio channels) causing video image smaller than optimal:

![image](https://user-images.githubusercontent.com/15310433/49056612-8c637a80-f1e3-11e8-9b09-b0c691c0b348.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I see (in your picture) **anon** track is not narrowed, so I'm assuming the tracks receiving video are **forced** to narrow. Is this the problem?

**Comment by jonjamcam** [comment]
> the tracks receiving video are forced to narrow. Is this the problem?

Exactly @elieserdejesus . I suppose the cause is video uses the second channel.

**Comment by elieserdejesus** [comment]
@jonjamcam , I tested this issue with v.2.1.11 and can't reproduce the problem. 

Since is a old issue maybe the problem was fixed in some previous version. Can you confirm?

**Comment by jonjamcam** [comment]
> @jonjamcam , I tested this issue with v.2.1.11 and can't reproduce the problem.

> Since is a old issue maybe the problem was fixed in some previous version. Can you confirm?

yes. it's there @elieserdejesus . so to reproduce you first use no video:

![image](https://user-images.githubusercontent.com/15310433/80137256-fd41ca00-8570-11ea-8b08-f61ae5ef1960.png)


then you turn on video on remote. The track is narrow now, probably because in reality there are two tracks and one (video) is hidden:

![image](https://user-images.githubusercontent.com/15310433/80137555-74775e00-8571-11ea-8b98-61a3af14b897.png)
