### ISSUE TITLE
Server address shown in Chat appears cropped when too long

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1157]
![image](https://user-images.githubusercontent.com/15310433/49095348-6d9acd80-f24f-11e8-81b8-b289baf57c36.png)

The problem here as I see it is not only aesthetic, but the public chat is hidden, so hard to use while connected to the server. If the case was as in here:

![image](https://user-images.githubusercontent.com/15310433/49096511-dc792600-f251-11e8-8bcc-6de2272482ab.png)

I think this solution sould be good enough

**Comment by elieserdejesus** [comment]
I'm trying to understand the lenght of this specific server name. Why so many letters? Why? Why? 
😄 😆

**Comment by jonjamcam** [comment]
PR https://github.com/elieserdejesus/JamTaba/pull/1372 solves this one

**Comment by elieserdejesus** [comment]
solved in #1372
