### ISSUE TITLE
cleaner Rooms UI for small size screens/ crowded servers

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1160]
Sometimes when servers are full, specially when using small screens (laptops, vstplugin, etc.), too much information looks a little messy. I propose a small change to trigger only in some extreme cases:

![image](https://user-images.githubusercontent.com/15310433/49322947-d1492300-f4fb-11e8-9a2e-23461c66cda6.png)

I think this could be activated automatically for example when the relationship between the size of the map and the number of users in the server creates a "too crowded" type of view.

Remember at the moment the country name is appearing also as tooltip when hovering the player's marker in the map. This could be expanded for example if the room is in this "simplified view" to hovering the whole map making all country names appear. Some ideas to improve aesthetics in the long run.

**Comment by elieserdejesus** [comment]
Good idea @jonjamcam , it's a lot of duplicated info in this UI.
