### ISSUE TITLE
Chat focus issue since fix.

### ISSUE THREAD

**Issue by AndyMcProducer** [elieserdejesus/JamTaba#1164]
Hiya, since the jamtaba chat focus issue was fixed a chat box is all that remains when selecting jamtaba chat.
What would help a lot if auto focus to the chat when the window is idle but in focus.
Also the window now vanish and just leave the small type in box when clicked.

These are vst plugin issues I refer too.
Also if jamtaba can check for admin before installing and prompt used to run as admin if not.
And option to clear jamtaba setting, but remember not all daws like to be run as admin and will break drag and drop when they are.

Can their be a multithread option for the vst as running in multithread in a plugin can cause cracks and pops in a daw. This is why many vst's have the option in them. It's all redundant tbh so should be updated by daws but until then multi thread must be on on the daw or the vst plugin.

I think Jon posted about the new codec issue and peeps being disconnected. Could jamtaba not become a player of rtmp sources too, which will take some bandwidth pressure of the servers.
So people could select a Cam or RTMP source, but cam be limited to max res and fps, as not to cause disconnects.

Also consider using the amd, nvidia hardware to stream, or using the open source for both which is about.

**Comment by fab672000** [comment]
There are many different aspects discussed in this thread, I'll stick with the issue only here: I am understanding that you have a problem with the plugin version only, under Windows (version?) and also that you use a vst host (Cubase? DAW version?) that used to work before a certain change but now seems to cause side effect. Is it right? running video and also audio dsp processing can both contribute to clicks, and it depends on what you already loadedm in your DAW. 

OT: Admin mode is not something that the tread can decide but that the host can (i.e. your DAW), if you think it could help you then maybe try to start the DAW in admin mode (if not already the case). 

OT: Hardware acceleration would be nice but I think all we try to do here is reuse an opensource lib (ffmpeg) to handle video stream ; if/when  the lib handles acceleration we will also naturally benefit from it.

**Comment by fab672000** [comment]
check for 2.1.8 you should not hear cracks anymore.

**Comment by AndyMcProducer** [comment]
Yes most issues resolved now, no need to wrap in jbridge no more, chat works ok without leaving the type box up, audio isn't crackling now. Only issue is still the webcam causing disconnects for all, but apart from that the webcam looks cool when peeps have it on.

**Comment by elieserdejesus** [comment]
> Yes most issues resolved now

Nice news @AndyMcProducer !

>  Only issue is still the webcam causing disconnects for all

I think many users are still using the older version, the camera resolution bug fix is available only in the last version.

**Comment by elieserdejesus** [comment]
I will close the issue since is about the chat focus issue (and is solved).

**Comment by fab672000** [comment]
Thanks for the confirmation Andy! I'm expecting 2.1.8 to be actually running even a bit faster than before when loaded :)
