### ISSUE TITLE
Configuration & run of a private server

### ISSUE THREAD

**Issue by JAMACEDIA** [elieserdejesus/JamTaba#1165]
Hello,
I appreciate the idea of JAMTABA that I discoved recently.
I would like to setup & run a private JAMTABA 2 server but I've dont find the howto do it. Do U have some process or advice to do it properly?
I thanks U in advance,
Regards,

**Comment by elieserdejesus** [comment]
Hi @JAMACEDIA ! 

What are your plans using a private JamTaba 2 server? What you expect as result? 

I'm asking because if you are just interested in play in a private server you have a *private server* in JamTaba menus.

**Comment by JAMACEDIA** [comment]
Hi @elieserdejesus,

Thanks for Ur fast reply.
Yes I ask U that to be able to play in a local private JAMTABA 2 server, I mean, for it works like in a direct line with one other musician &, also, cause am interest in understanding how it works  & configuring it localy. Yes, I see & try the private sever on JAMBALA (seams to works) but it don't shows the server name, port & don't autorize much setup as I could understand so far. 

Thanks for Ur lights,
Regards,

**Comment by elieserdejesus** [comment]
>but it don't shows the server name, port & don't autorize much setup as I could understand so far.

Yes @JAMACEDIA, JamTaba server have no name, just an IP and PORT. The IP and PORT are showed in the server window. You can't set a public name for a private server.

Jamtaba server is a very simple version of *ninjam server*. There are no configurations because the idea is just "one click and let's play!". I suggest the real *ninjam server* to have total control of your private server, but is not a "one click and let's play" process, you must do some geek procedures to setup the server and get the server "visible" to your friends.

**Comment by JAMACEDIA** [comment]
Hi @elieserdejesus,

Thks for Ur answer & for the work U've done for this intutive & accessible version. :)
My problem is that I don't find enouth configuration information of it at this time. The official site is only one page on configurating the server, like the Ninjam_user_guide & seams both not really updated like JAMTABA 2 can be, that's where my hope & confusion came by...  ;)
Anyway, thanks for Ur usefull reply that's makes me understanding the problem with more accuity.
Let me know if U have any idea about how to solve it.

Regards,
& *** Merry Christmas ***

**Comment by elieserdejesus** [comment]
@JAMACEDIA , I suggest this document to learn how configure the server in your machine: https://www.freewebs.com/arxeia/Ninjam_User_Guide.pdf

If you share your IP and PORT with others they can connect in your server.

A more complex scenario is use a cool name for your server, so people can connect using the server name. Search by *dyndns* to see how create a server name pointing to your IP.

The last step to get a public servert (if you are interested)  is register your server name and port in the *Cockos public server list*. There is a page (search in ninbot.com) in Cockos site where you can register your server.
