### ISSUE TITLE
When standalone is started in mini mode the expand button of the window is greyed out

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#117]
![greyed out](https://cloud.githubusercontent.com/assets/15310433/11092191/0ffc39e0-8860-11e5-8626-8097d38490b4.jpg)

This makes it impossible to maximize if you decide to switch to full view. On the other hand when starting in full view mode and switching to mini mode this doesn't happen:

![not greyed out](https://cloud.githubusercontent.com/assets/15310433/11092235/5fb3d3da-8860-11e5-9f8c-b9a6a6f46d51.jpg)

I promised to be faster!

**Comment by Ezeer** [comment]
I was just listening to your session in the full room ... cool music !
( and was testing the new cpu/memory peak feature from elieser )
Ok jon , thanks for the report again !

**Comment by jonjamcam** [comment]
Well I'm just getting some feedback. There's a lot of Jamtaba users now! They love it. Karma also is a convert. YES love it.....it's the sound.......best

**Comment by elieserdejesus** [comment]
Karma is converted! Hahaha, the best comment!
Jon, I confirm this bug. I see this shit everytime here and I release the last version with this bug, shame on me. I spend almost 2 hours trying fix this, I quit :)
But I will try again, I promisse.
