### ISSUE TITLE
map appears broken when unknown user is connected

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1170]
![image](https://user-images.githubusercontent.com/15310433/50715452-72c81500-1064-11e9-8cac-ff80d7eda706.png)

and

![image](https://user-images.githubusercontent.com/15310433/50718290-68fadd80-1075-11e9-9ad5-f2a3ac921ebe.png)

when only one user is connected

**Comment by qulf** [comment]
I have suggestion simpler theme without map to save onscreen space or button to off/on map view to see all rooms without scrolling

**Comment by jonjamcam** [comment]
Some additional information regarding this issue:

1 .- not every UNKNOWN user appears in the map:

![image](https://user-images.githubusercontent.com/15310433/52013235-a4959580-24c3-11e9-9c4c-ee48bef95ed5.png)

**Comment by elieserdejesus** [comment]
fixed in https://github.com/elieserdejesus/JamTaba/commit/84b30665c1caab745c5a774f15f7b58e4a4f26fa
