### ISSUE TITLE
Where do we go from here?

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#1174]
Hello folks. I have several issues regarding audio quality, number of channels, video quality and size and such matters. 

The decisions that have dictated where we are currently, seems mostly political in the sense, that last time I raised some of these issues, I was met with typical political comments, that the reasoning behind slaughtering progression and lessening quality was due to being scared that even 0.00001% of Jamtaba user base would be hit with an umpleasant experience, should they use said software with less than ideal internet speeds, they would then blame said software on their bad experience, and not the fact that the laws of physics dictate that with their crappy internet, none of what they're trying to do should be possible in any event, unless they (and everyone else) are satisfied with blocky thumbnail size video that steal the musicians second audio channel, and an audio codec that no one want's to mess with or give the user the option to bump up in quality, again because they're scared some random user would complain about the software being the issue for their slow internet speed or prehistoric computer. 

The fact of the matter is, back in the day before Jamtaba came along, Ninjam was set to a much higher quality audio stream, than it is now, 

and previously in Jamtaba, we could at least video stream and transmit two channels of low quality audio that cuts off all the high end thus permanently leaving the jamtabbing experience to the amateurs who are just out to have a good time and otherwise don't care too much for quality (which again would generally be a falsity, since why the hell else would these folks spend thousands on equipment external sound cards etc. etc. if to only have it run through the crappiest codec quality setting)? 

You know why no one uses the webcams on jamtaba? Because they're way too damn small, and they steal your second channel.

You know why no one uses Jamtaba for anything professionally? Because no one has made any efforts to change it to a more serious professional environment. 

There should be nothing technically refraining people from "ninjamming" with much better audio quality, just as there should be nothing technically regraining people from being able to stream two channels of audio or for the video "preview" to be bigger and the video size to be something bigger than what, 340x240 or whatever it is set at now.

For years I've tried to explain on ninbot.com, that it would help if we could have some public rooms with fewer max ammount of people in the room to avoid the complete noobs or people who genuinely sound like shit constantly, from entering when 2, 3, 4 people are having a blast jamming and a 5th fucker comes in and ruins the whole thing - for some strange reason it's like the few people behind this have a golden rule that it must be minimum 5, 7 and 8 people rooms, and that it must for the next 30 years be capped at 64kbit .ogg vorbis crap shit audio quality because of stubbornness and pride getting in the way of progression. I don't even know if I'm right about the reasonings behind these decisionr or the motives behind. 

I guess i still have a smidge of hope that a few of you reading this, and who know what the fuck ninjamming is actually about and what it used to be, will chime in and start doing something about these fundamental things, that most of you don't give a fuck about, but that are actually very fundamental to the experience ! 

If all you are is a programmer geek who likes to fuck around on the guitar a bit now and then, sure, you wouldn't think cutting off all the high end with a nasty codec like that, would hurt anything because technically you can still hear the audio. yes, and technically u can still see the thumbnail sized video stream, and you can technically still jam with just one channel etc. 

I'm sure you could give me 10 bullshit reasons for not wanting to up the quality to a respectable level - but then guess what, that's what you'll get - disrespectful amateur users who could care less about audio fidelity or creating a great jamming experience for all for that matter, just egotistical bullshit like the excuse that this fucking app would be worse off if it had high definition options - bull fucking shit. Happy new year.

 jonjamcam commented Nov 27, 2018

    the tracks receiving video are forced to narrow. Is this the problem?

Exactly @elieserdejesus . I suppose the cause is video uses the second channel.

**Comment by Hitrate** [comment]
Also I would like to add: imagine if everyone started taking Jamtaba and Ninjamming serious`? Imagine if we actually had people interested in going out for a big server farm that could be used for super high quality jams, rather than pinning the excuses on poor servers and potential bandwidth limits (to put it in perspective, people are easily doing massive multiplayer gaming and even cloud compute gaming, but we can't do more than one mono audio at 96kbit crap quality channel and one 120p video crap quality - come on, does anyone see the stupidity of this?!) that could actually recorded on to each computer because the quality was that good? Imagine if we started treating this shit as if it could actually be used for something other than just endless 2 chord low bitrate guitar noodeling ? If we started approaching it at an angle where you could have rooms more focused on production, where you use the main golden feature of this app (fixed latency live audio collaboration) in a way that would be appealing to the pro environment? To where we could actually start talking about getting really skilled folks involved who sought after a way of interacting with their clients and vice versa with this technology? You think they'd be satisfied with the way it's currently run, or do you think some of you need to re-think your approach to some of these decisions which where made probably years ago, and never revisited with an open mind or current reality check? 

I hope you guys will take my points to heart and think about where you want this to go, because in many areas it is far from improving, when the rest of the world is improving along just fine, so let's be real here, it's 2019 not 2008 anymore.

**Comment by Hitrate** [comment]
I'm sure you can find the ticket/issue for the video stream being changed to take up channel 2, I haven't payed attention cause it seemed like there was no democracy in here really, just a few programmers who make the app and then the technical details are up the user, like jon being of the opinion that unless the user goes out of their way to up the quality, the users have not earned the right to have good quality stream, thus everyone should be penalised and receive bad quality streams...I don't know how anyone could have such a fucked up mentality towards life - on one hand you offer your free expertise and opinions on a free app, but you want the cripple all users experience of it with the lowest quality audio setting as default, that makes no sense - and you're not even paying for the server so really you could care less if people wanted good quality. Elisier seems to agree that the quality should be upped so there's not a cap at 16khz with poor dynamics but nothing changes since people are caught up in their own lives and selfish shit rather than try and take this to the next level - which I find is achilles heel of ninjammers - very few people are actually collaborating on serious stuff, most don't even say hi or goodbye so in that sense I get why such attitudes would trickle down into the people behind a "new" app like Jamtaba - but speaking from the perspective of someone who has invested probably more time combined on this shit than even AndyMC it seems, since 2009, I know a thing or two about what i'm talking about, and no way in hell do you make lazy egotistical people like that go in and change the code in an app, that stuff needs to be programmed into it. So we can either just keep it as it is and keep one or two people happy(?) cause the app doesn't crash when Nigerians wanna jam and stream, or we can have some decency and respect and offer up at least a good audio quality experience, and if the users has bandwidth, let them stream video at a respectable size and quality.

**Comment by elieserdejesus** [comment]
closing, not an issue.
