### ISSUE TITLE
Compile on OSX - 'aeffectx.h' file not found 

### ISSUE THREAD

**Issue by Brouilles** [elieserdejesus/JamTaba#1176]
Hi, 
I want to compile the standalone program on Mac OS X Mojave. But I have an issue. I followed steps describe in the README.md, but I have this error:
```
JamTaba/src/Standalone/vst/VstPlugin.h:5: error: 'aeffectx.h' file not found
#include "aeffectx.h"
```

 VST_SDK (last): vstsdk3612_03_12_2018_build_67
Thanks for your help.

**Comment by Brouilles** [comment]
I see here https://github.com/elieserdejesus/JamTaba/issues/1139

> Hi @elieserdejesus, thanks for the reply! I've successfully got it compiled and running! Much appreciated!
> 
> I did run into one issue with VST SDK versioning. With the latest release, I got a build error 'cannot open file aeffectx.h' I searched for the file on my computer and happened to have an older version of VST SDK (folder is called vstsdk3610_11_06_2018_build_37) that has the file and I was able to build and run.

But I don't find a link for download VST2. The version in the VST3SDK seem incomplete.

**Comment by jonjamcam** [comment]
> But I don't find a link for download VST2. The version in the VST3SDK seem incomplete.

Hi @Brouilles and @elieserdejesus . I'm having the same problem. Latest Steinberg SDK not working in my system.

![image](https://user-images.githubusercontent.com/15310433/53246794-64739e00-3690-11e9-8ea9-d915e55a466b.png)

 I Found here (https://forum.juce.com/t/steinberg-closing-down-vst-for-good/27722/124) the **vstsdk3610_11_06_2018_build_37** file available for download:

https://web.archive.org/web/20181016150224/https://download.steinberg.net/sdk_downloads/vstsdk3610_11_06_2018_build_37.zip

but It looks the path has changed, so I'm unable to build ATM.

**Comment by elieserdejesus** [comment]
[VST 2 is not manteined by Steinberg, only VST 3.](https://www.steinberg.net/en/newsandevents/news/newsdetail/article/vst-2-coming-to-an-end-4727.html)

The temporary solution is grab some old VST SDK version in internet.

The only long term solution is write JamTaba as a VST 3 Plugin.

**Comment by arnaudlecam** [comment]
Hi @elieserdejesus ,
Using VST3 would be nice, I agree... While awaiting, could you please put your VST2 into the drive (like existing static libs) ?

**Comment by elieserdejesus** [comment]
@arnaudlecam , this is the old VST SDK I'm using: https://www.dropbox.com/s/9lxowvn7k3bfkf1/VST_SDK.zip?dl=0

**Comment by arnaudlecam** [comment]
Thank you !
