### ISSUE TITLE
Cantabile is not closing because JamTaba VST plugin

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1178]
An user reported the problem in the title by email.

When JamTaba is used inside Cantabile this software can't be closed.

**Comment by toptensoftware** [comment]
Hi,

I'm the developer of Cantabile and had a quick look at this.

* This only happens after opening JamTaba's GUI.  If you just load the plugin and then delete it, it unloads correctly.
* I've double checked that effEditClose and effClose are being called correctly - as best I can tell they are. 
* The problem happens even if Cantabile's audio engine isn't running for the entire time the plugin is loaded - so this doesn't seem to be related to real-time audio processing.
* The hang happens in the call to effClose while unloading the plugin with the call stack as shown below.

I'm happy to help get this resolved if there's anything I can do to help just let me know.

Brad

Call stack for hang (dispatching effClose)

~~~
 	win32u.dll!NtUserMsgWaitForMultipleObjectsEx()	Unknown
 	user32.dll!RealMsgWaitForMultipleObjectsEx()	Unknown
 	JamtabaVST2.dll!00007ff8cc39a926()	Unknown
 	JamtabaVST2.dll!00007ff8cb81e608()	Unknown
 	JamtabaVST2.dll!00007ff8cc3857b1()	Unknown
 	JamtabaVST2.dll!00007ff8cb7a9a36()	Unknown
 	JamtabaVST2.dll!00007ff8cb7a9681()	Unknown
 	JamtabaVST2.dll!00007ff8cb69abf9()	Unknown
 	JamtabaVST2.dll!00007ff8cb69855b()	Unknown
 	JamtabaVST2.dll!00007ff8cb7d1501()	Unknown
 	JamtabaVST2.dll!00007ff8cb7ce24c()	Unknown
 	JamtabaVST2.dll!00007ff8cb7cf284()	Unknown
 	JamtabaVST2.dll!00007ff8cb7d7f6d()	Unknown
>	CantabileCore.dll!CVst2PluginHost::Dispatch(int opCode, int index, __int64 value, void * ptr, float opt) Line 2619	C++
~~~

**Comment by elieserdejesus** [comment]
Hi Brad, thanks for this detailed report.

**Comment by toptensoftware** [comment]
No problem.  Any ideas what might be causing this and/or any chance of a fix soon?  (not to hassle, but I get occasional queries about it and just wondering how to reply).

**Comment by elieserdejesus** [comment]
> No problem. Any ideas what might be causing this and/or any chance of a fix soon? (not to hassle, but I get occasional queries about it and just wondering how to reply).

Brad, I'm not active in this project at moment and received no contributions from other programmers in the last year. So, the fix will not be soon.

**Comment by elieserdejesus** [comment]
Eric reported by email:
With the newest Cantabile build 3.0.3652 and the latest Jamtaba 2 version 2.13.. this issue is fixed and I can finally use Cantabile for jamming instead of Ableton or Reaper..

Seems the updates got rid of the problem
