### ISSUE TITLE
i cant delete some loops name in the list

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#1186]
Hello  Long time not hearing you on ninjam   ... you are really missing @elieserdejesus 
I have an issue  with the looper  With time i create a lot of loops  and when trying to loading them  i cant see the last loops in alphabetical order so cant download them in jamtaba Lot of loops  i deleted in the folder  Looper  of jamtaba  but still are visible listed with the button load looper layers .. so with time the deleted loops name are growing and last in alphabetical order cant be loaded .
Any way to deleted those loops name  which are empty in fact ?
thanks in advance for your help

**Comment by DoublebassOO** [comment]
ok got it ! Didnt see the files that were at the bottom  end ,   in the folder just have to delete the   X.json  files  
This jamtaba such a great tool !

**Comment by elieserdejesus** [comment]
ok @DoublebassOO , great see you solved the problem!
