### ISSUE TITLE
libQt5WebSockets.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by brylie** [elieserdejesus/JamTaba#1188]
When trying to launch JamTaba on Linux, I get the following error:

> ./Jamtaba2: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory

**Comment by brylie** [comment]
It seems like the `libQt5WebSockets.so.5` is not included in the JamTaba download:

![image](https://user-images.githubusercontent.com/17307/71605836-d9e3b100-2b74-11ea-85e2-c480a3090798.png)

**Comment by brylie** [comment]
I was able to get around this on Ubuntu 19.10 with:

> sudo apt install libqt5websockets5

**Comment by strk** [comment]
To me it's not enough:
```
/home/strk/Jamtaba2/Jamtaba2: /home/strk/Jamtaba2/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5)
```

**Comment by brylie** [comment]
Hm, I can't remember any other steps I took to get it working. Do you have libqt5 installed?

**Comment by strk** [comment]
Uhm, found out the problem is ONLY when running `/home/strk/Jamtaba2/Jamtaba2.sh`
Directly runnin `/home/strk/Jamtaba2/Jamtaba2` does NOT have the problem !

**Comment by strk** [comment]
Note: the path to `/home/strk/Jamtaba2/Jamtaba2.sh` (the non-working one) is the one written in the Jamtaba2.desktop file installed by the installer on my Desktop

**Comment by strk** [comment]
@brylie how about sending a pull request to update documentation with your findings about this problem ? :)

**Comment by elieserdejesus** [comment]
Is a better option change Jamtaba2.desktop using the correct path?

**Comment by strk** [comment]
Possibly, but what's the point of the shell script in the first place ?
It was you adding it, with 28fc4a62bd809f0bab6373e7b067afba5ffdeb83 :)

**Comment by elieserdejesus** [comment]
> Possibly, but what's the point of the shell script in the first place ?
> It was you adding it, with [28fc4a6](https://github.com/elieserdejesus/JamTaba/commit/28fc4a62bd809f0bab6373e7b067afba5ffdeb83) :)

Long time ago, I can`t remember my today lunch 😄
