### ISSUE TITLE
Jamtaba Standalone on MAC crashes if used lowest latency (reported by YES)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#119]
![yes report](https://cloud.githubusercontent.com/assets/15310433/11092690/ed62fa0a-8863-11e5-92ad-02024239e740.jpg)

**Comment by elieserdejesus** [comment]
Mac users are blessed. Last time I test the mac version I run Jamtaba with a buffer size of 16 samples. This is ridiculous compared to Windows/ASIO stuff. And I run in mac just using my motherboard sound card, no external audio interface. Mac audio engine is really a piece of art when considering latency.

Maybe YES is trying using a really very little buffer size, like 8 or 4 samples.  This can be difficult to test.

**Comment by elieserdejesus** [comment]
Ah, another info: the mac version is 2.0.3, I don't update the code for the mac version yet, shame on me :)

**Comment by jonjamcam** [comment]
Pipaxis is waiting the MAC vst to be part of the Jamtaba cult lol.

**Comment by Ezeer** [comment]
https://www.youtube.com/watch?v=0Ei2UbMVAlA&feature=youtu.be

**Comment by elieserdejesus** [comment]
Cool video Ezee!

Jon, the plugin for Mac is a complicated thing. I never to this stuff in Mac, so I need a  lot of time to research how change the current code to work as a Mac vst plugin. Vst plugins in mac are not dll, they are bundles with .vst extension. These bundles contain all application files. The things are very different in Mac land, so is not just question of change one or 2 lines. Someday I will work on this, possibly in Jamtaba v56.0.34  :)

**Comment by Ezeer** [comment]
@jonjamcam  But say to pipaxis that there is some ways to use vst in mac : 
http://www.synthtopia.com/content/2012/12/28/free-app-lets-you-run-windows-vsts-in-your-mac-daw/
;)

**Comment by jonjamcam** [comment]
I think the standalone does the job well enough.....
