### ISSUE TITLE
Is jamtaba abandonware?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1192]
hi @elieserdejesus  . It's been some time. Just wanted to ask are you still active on this project?

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I`m not active in this project at moment. Maybe I can work in something in the future, but not at this moment. So I think JamTaba is more a frozen project instead an abandonware.

**Comment by jonjamcam** [comment]
well @elieserdejesus  fyi Jamtaba is not working atm

![image](https://user-images.githubusercontent.com/15310433/76719236-ee692b80-6717-11ea-84a0-24c7ed6e02ca.png)

**Comment by elieserdejesus** [comment]
Too many users in last days (Corona effect), the server daily costs are exausted.

**Comment by jonjamcam** [comment]
>Too many users in last days (Corona effect), the server daily costs are exausted.

lol

it'a working now

**Comment by strk** [comment]
I guess this ticket can be closed.
@jonjamcam install your server, it's simple to setup !
See https://www.cockos.com/ninjam/server-guide.php

**Comment by elieserdejesus** [comment]
@strk , the JamTaba server is not the same thing as a ninjam server. This is explained in a long conversation here in the github, please search if you are interested.
