### ISSUE TITLE
Jamtaba can't detect any audio device in your machine!

### ISSUE THREAD

**Issue by strk** [elieserdejesus/JamTaba#1193]
The 32bit download for Windows installs but on start it gives this error:
> Jamtaba can't detect any audio device in your machine!

**Comment by elieserdejesus** [comment]
Hi, try to install Asio4ALL http://www.asio4all.org/
Please report if this solve your problem.

**Comment by strk** [comment]
yep, that seems to work. I'm not sure how to test JamTaba can hear my microphone though (other apps do can hear it fine [ like audacity ]) -- Anyway this ticket is closed with ASIO (would be good to include a note about it in the README)

**Comment by strk** [comment]
Well, actually.. let's re-open as I'm not sure ASIO is doing it's job in the right way (any hint on how to debug it in isolation?)

**Comment by strk** [comment]
ok I confirm with some setup ASIO worked :)
