### ISSUE TITLE
Using 2 different "Documents" directories

### ISSUE THREAD

**Issue by strk** [elieserdejesus/JamTaba#1196]
By default ~/Documents/Jamtaba is used for jams recording and ~/Documents/JamTaba for loops recording. It would be good to be consistent and use only one.

**Comment by elieserdejesus** [comment]
Are you talking about Jamtaba in Linux, right? If yes please change the issue title or the description to be more specific, honestly this will help e a lot.

**Comment by strk** [comment]
Yes, on linuz. Issue title updated. I'm not sure how that configuration ended up in there, I think I installed it via the installer, so it could be the installer's fault (I dont' even know where configuration is stored yet)

**Comment by elieserdejesus** [comment]
@strk , this issue is fixed, but the wrong Jams path is stored in your config file. When the new version is release please delete the JSON file in /home/YOUR_USER/.local/share/JamTaba 2/
