### ISSUE TITLE
Crash in OSX 10.11 with Logic Pro X or Ableton Live 9.7 64 bits

### ISSUE THREAD

**Issue by elnenealegre** [elieserdejesus/JamTaba#1197]
Hello.
Jamtaba 2 doesn't work in my system as an AU plugin.
In Logic keep eternally "Preparing" and I cannot hear the metronome.
In Ableton, when I drag the Jamtaba AU to the Master track (or any track) Ableton crashes and it close.
Standalone mode works.

Any ideas?
Thanks in advance

Is there an option to stream as dual mono in the standalone mode?

**Comment by elnenealegre** [comment]
Sorry: Ableton sometimes crashes and closes, and sometimes Jamtaba says "Unknown error", but never tries to connect to the server.

**Comment by elieserdejesus** [comment]
please try the new version (v2.1.10)
