### ISSUE TITLE
Menu bar cut off in vst version 2.1.9

### ISSUE THREAD

**Issue by starwarswii** [elieserdejesus/JamTaba#1198]
In the 2.1.9 vst, the menu bar at the top is cut off (the preferences, view, ninjam, etc menus). vst version 2.1.8 did not have this issue.

![image](https://user-images.githubusercontent.com/6812820/77231294-584a6080-6b70-11ea-9abc-edd41966adb0.png)

In the image, you can see a small floating black line at the bottom and right. this is part of the window, with a transparent gap between it and the gui. i think this means the gui is shifted up and to the left, out of bounds.

I'm using Mixcraft 8 on Windows 10 64-bit. Was looking to get confirmation that this isn't just me, and happens to others in other daws.

**Comment by elieserdejesus** [comment]
Tested in Reaper and is working ok.

**Comment by jkingsDigiPen** [comment]
Having this issue in Reason 11 on Windows 10 64-bit.

**Comment by starwarswii** [comment]
As a temporary fix, I've just downgraded to 2.1.8 by just rerunning the 2.1.8 installer. It installed without issue.

**Comment by elieserdejesus** [comment]
clone of #1208
