### ISSUE TITLE
Pan "R" letter a little blocked by level meters in mini mode

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#120]
just a minor issue....

![pan mini mode](https://cloud.githubusercontent.com/assets/15310433/11096498/30559e3e-8879-11e5-99d9-cac7ad3a0966.jpg)

**Comment by Ezeer** [comment]
I don't touch at that mini mode , it's the elieser creation .
mmm..
![mini](https://cloud.githubusercontent.com/assets/1283808/11096726/d584c00c-889b-11e5-991c-6a998014d852.jpg)

... wah ah ah ah ....

**Comment by elieserdejesus** [comment]
ha ha, best picture.

**Comment by jonjamcam** [comment]
lol

**Comment by elieserdejesus** [comment]
Done!
