### ISSUE TITLE
Private server opening Mac and Windows

### ISSUE THREAD

**Issue by jovchaos27** [elieserdejesus/JamTaba#1203]
Two friends of mine cannot create their own private server. They both receive a similar error. This is the error on Mac:

[19:51:47] Server started
[19:51:47] Trying to open the port 2049 in your router (UPnP) to allow external connections ...
[19:51:53] ERROR in UPnP protocol: Found a (not connected?) IGD : http://192.168.1.1:39678/ctl/IPConn

How to solve this?

I report they’re both using wi-fi connection. 

Instead I can create and start a new server on my Windows system (I’m connected through cable) but it seams like people cannot join my private room, even if i give them my server’s IP.

How can i solve this? Should I enable or disable something on my router? Any specific UDP or TCP Fwd to perform?

**Comment by elieserdejesus** [comment]
Sorry man, no clue, it`s something in your router configuration.

Eleser

Em sáb., 21 de mar. de 2020 às 20:16, jovchaos27 <notifications@github.com>
escreveu:

**Comment by wjbuys** [comment]
I suspect the UPnP error just means that jamtaba can't figure out how to *automatically* forward a port on your router to your computer. I got the same error on my windows computer, but the server was running, and I was able to manually forward port 2049 on my router to get things to work.

You might be able to try the same: [how to forward a ports on your router](https://www.howtogeek.com/66214/how-to-forward-ports-on-your-router/)

**Comment by pljones** [comment]
JamTaba really ought not to go around managing people's routers for them.  That counts as hacking in my book and is bad.

**Comment by elieserdejesus** [comment]
> JamTaba really ought not to go around managing people's routers for them. 

JamTaba is not doing this, It`s just using a well known protocol (upnp). If upnp is disabled in the user router jamTaba can`t do nothing. 

Closing, this is not an JamTaba issue.
