### ISSUE TITLE
Server compatibility error versio 2.1.9

### ISSUE THREAD

**Issue by mendexman** [elieserdejesus/JamTaba#1204]
Hi after 30 minutos jamming  it went down and it's not starting up, and showing server compatibility error below

i'm on windows 10 64 bit
![image](https://user-images.githubusercontent.com/62488811/77239302-3f25cc00-6bd1-11ea-89ce-7acb98c738d8.png)

**Comment by miccio-dk** [comment]
same happened here. Curiously enough, after installing an older version, I get the same error.

**Comment by jovchaos27** [comment]
Same exact thing here, tried to clean reinstall and re-download but nothing ☹️

**Comment by mendexman** [comment]
> Same exact thing here, tried to clean reinstall and re-download but nothing ☹️

me too, i tried the 2.1.8...but same error

**Comment by elieserdejesus** [comment]
![image](https://user-images.githubusercontent.com/1012741/77239491-17773980-6bba-11ea-9e6d-23145ee320a7.png)

**Comment by elieserdejesus** [comment]
Closing the issue, it`s just server resources being exausted, it`s not related with version.

**Comment by mendexman** [comment]
> Closing the issue, it`s just server resources being exausted, it`s not related with version.

tank you brother
