### ISSUE TITLE
Code license is not clear

### ISSUE THREAD

**Issue by fabrixxm** [elieserdejesus/JamTaba#1205]
I'm trying to package jamtaba in AUR, but I don't know what to put in "license" metadata :)

**Comment by elieserdejesus** [comment]
me neither, if you know how to solve the VST2 SDK licence problem please tell me.

I think (not 100% shure) the JUCE project just abandoned the Steinberg SDK and rewrite the files form scratch, just to avoid the licence problems.

**Comment by pljones** [comment]
#1210 goes into more detail.

**Comment by elieserdejesus** [comment]
closing this issue, the discussion is going in #1210

**Comment by cbix** [comment]
> I'm trying to package jamtaba in AUR, but I don't know what to put in "license" metadata :)

@fabrixxm FYI, I managed to [create an AUR package](https://aur.archlinux.org/packages/jamtaba/) even without any of the dependencies from the Dropbox links, let me know if you want to co-maintain it ;)
