### ISSUE TITLE
Black Screen in AU plugin

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1206]
v2.1.9 is showing a black screen in v2.1.9. An user reported the v2.1.8 is working fine. Possibly this is related with the new qt version used in v2.1.9.
![image](https://user-images.githubusercontent.com/1012741/77324971-498db600-6cf6-11ea-86e1-47d5ad105401.png)

**Comment by h3dgecutter** [comment]
I have just installed the latest plugin from the Web page and it does the same for me. My system is high sierra. I tried both logic Pro x and ableton to no avail. Should I install an older version to test? Thank you.

**Comment by elieserdejesus** [comment]
yes @h3dgecutter , please try to install the v2.1.8 (the previous). Another AU plugin user reported the v2.1.8 is working fine.

**Comment by h3dgecutter** [comment]
Worked perfectly @elieserdejesus, than you. Test and jamming... Thank you. Great work!!!
