### ISSUE TITLE
jamtaba 2.1.9  vst2-plugin-window  corrupt

### ISSUE THREAD

**Issue by Immele** [elieserdejesus/JamTaba#1208]
![InkedJamtaba2_LI](https://user-images.githubusercontent.com/62607823/77440073-26433380-6de8-11ea-8a31-93010ff3df17.jpg)

Screen draw strange behavior. 

See the two Arrows drawn in screenshot.
Upper :  missing menü ?   ( cant change Themes )
Lower :  empty space ?

Standalone Jamtaba works
Previous version of Jamtaba worked

Win 10
Studio One 4.6.0
No DPI Scaling activated.

Kind Regards,
immele

**Comment by pirxthepilot** [comment]
this is my experience as well. standalone jamtaba seems to work ok.

Win 10 x64 VST with Ableton Live 9

**Comment by pljones** [comment]
It seems okay in Reaper...

**Comment by elieserdejesus** [comment]
clone of #1198
