### ISSUE TITLE
Jamtaba v2.1.9 Windows 7 (0xc000007b) Error

### ISSUE THREAD

**Issue by fireblade64** [elieserdejesus/JamTaba#1209]
I get the error message when I start the application on Windows 7 (0xc000007b)

**Comment by pljones** [comment]
> 0xc000007b error usually comes from mixing up 32bit environment with 64bit one. For example 32bit application loads a 64bit dll causing 0xc000007b error.

You'll need to say whether you've a 32bit OS or a 64bit OS.

**Comment by fireblade64** [comment]
I have a 64bit OS.
The error results with both Jamtba 32 and 64 bit

**Comment by pljones** [comment]
OK, the only other thing I can think of is there's a missing library - I don't know whether something got dropped between 2.1.8 and 2.1.9.

**Comment by chunguy** [comment]
I think missing library is: api-ms-win-core-winrt-l1-1-0.dll (Windows 10 64bits) Both versions 32 & 64 bits

**Comment by elieserdejesus** [comment]
My tests:
1 -installed a Win 7 in a virtual machine
2 - Installed JamTaba
3 - The bug was confirmed, I see the error about "api-ms-win-core-winrt-l1-1-0.dll" missing.
4 - Search for a fix. Installed msvc 2015 redistributable, not working.
5 - Installed Windows Update KB2999226

Nothing works, so I quit for while.

**Comment by Statine** [comment]
Hello, I have the same issue both with 2.1.9 and 2.1.10 : Windows7 (0xc000007b) error. I'm in 64bits also. Regards

**Comment by elieserdejesus** [comment]
Hi guys, teste a new beta version here and is working again in Windows 7. Can you test the beat in your win 7 too, just to confirm? 

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.11-beta

**Comment by Statine** [comment]
Hi Elieser

works great now !
Thks
Nicolas (Statine)

**Comment by fireblade64** [comment]
@elieserdejesus Thanks, works great on Windows 7 64bit.

**Comment by elieserdejesus** [comment]
thanks @fireblade64 !
