### ISSUE TITLE
User's manual is missing in 2.0.5

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#121]
lol
edit : i start to work with the separated folders in JTB2 right now ....

**Comment by jonjamcam** [comment]
BTW Ezee I don't know if the joystick support is being implemented in 2.0.5. I'm ready to add it to the manual when you are finished.

**Comment by Ezeer** [comment]
check the milestone bro' : #67

**Comment by elieserdejesus** [comment]
This is solved, right?
