### ISSUE TITLE
Support for "private" rooms

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1212]
Justin's added the concept of private rooms.  These have one of two identifying strings:
- when empty: "empty private server, [^!]+!"
- when in use: "private server, [^-]*-- "

This should be flagged in the room header.

**Comment by elieserdejesus** [comment]
it`s not clear for me: the idea is show the "private" rooms in the "public" servers list?

**Comment by DVL58** [comment]
Unable to enter the cockos servers; times out.

**Comment by pljones** [comment]
The servers are _public_ in the sense they are visible to everyone.

They "private" in the sense that once they are entered, only those invited are meant to enter.  As far as I know, there's nothing preventing entry.

Because JamTaba parses the BPM/BPI info, it's _probably_ getting confused, as this is different - best is to look at the server list response to see it.  I've not yet looked at the JamTaba code (but I had to rework my website's server display code).

**Comment by elieserdejesus** [comment]
perfect @pljones , thanks for the clarification.

**Comment by elieserdejesus** [comment]
Fixed in the server code!

**Comment by pljones** [comment]
Damn, then he went and changed it.

So now there's the concept of the lobby (no jamming) and really private room with a name.

Ideally, JamTaba would have pretty UI support for joining the lobby and chatting or creating a new room (actually, allocating the name to the next available private room and entering it), or joining an existing room...

My web site need to be fixed to parse the new string... and ignore it.

**Comment by elieserdejesus** [comment]
Now JamTaba is getting da public servers data from ninbot, and at moment ninbot is not parsing the cockos server.

**Comment by pljones** [comment]
I think he just changed it again...
