### ISSUE TITLE
Always put the port number in the room name

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1213]
Currently the port number is not always show in the room name.

It's possible this is due to a parsing issue with the new private server feature.  However, it's happening for most of the servers (e.g. neither of the two "new" live.ninjamer ones has a port number shown).

This is more important now there are more rooms on many of the servers so people know where they're going.

**Comment by jonjamcam** [comment]
hi @pljones you can do this here: https://github.com/elieserdejesus/JamTaba/pull/1215

**Comment by elieserdejesus** [comment]
solved in #1215
