### ISSUE TITLE
live.ninjamer stream support

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1214]
It's the same as ninjamer but with "live." on the front :).

ninjamer Icecast: http://ninjamer.com:15000/
live.ninjamer Icecast: http://live.ninjamer.com:15000/

**Comment by elieserdejesus** [comment]
added in the server repository

**Comment by jonjamcam** [comment]
@elieserdejesus One question: are the audio stream links for each room still coming from GAE server?

There are some missing Livestreams from new servers:

ninjam.discordonlinejammingcentral.com:8000/2050
ninjam.discordonlinejammingcentral.com:8000/2051
ninjam.discordonlinejammingcentral.com:8000/2052

**Comment by elieserdejesus** [comment]
@jonjamcam , now all servers stream urls are comming from ninbot
http://ninbot.com/app/servers.php
