### ISSUE TITLE
Small UI on 4K Laptop

### ISSUE THREAD

**Issue by DVL58** [elieserdejesus/JamTaba#1216]
User Interface is very small on 4K Laptop, and it does not scale with Windows 10 display settings.  Are there any settings to adjust the UI size.  The previous version of JamTaba was usable, the new version (2.1.9) is unusably small unless using the windows zoom tool; but then the rest of the Reaper interface is difficult to access.

Thanks for all your wonderful help; Jamtaba is a very nice application--great features!

**Comment by elieserdejesus** [comment]
I don`t how test this issue since I don`t have a 4k screen. Any ideas?

**Comment by DVL58** [comment]
Thanks for the response.  I can check any changes you want to try, but I don't know enough about software to really "test" it...  I think it has something to do with scaling the UI?  Forgive my ignorance.  

Changing the screen resolution manually seems to help.  The issue only presented itself a few months ago.  I use the VST version of JamTaba in Reaper; Reaper version 5.984 was the last version without the issue.  I'll try to contact the Reaper developer, but that won't help resolve the same issue present in the stand alone Jamtaba app.  I think the following link explains what's going on?  

https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6

Thanks again for your very generous contribution to the music community; JamTaba is a fantastic program!

**Comment by elieserdejesus** [comment]
> https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6

This link is showing a evry good clue. I will try a beta version soon and send for you to test in your 4k monitor.

**Comment by DVL58** [comment]
I tried creating an Environment Variable:  QT_AUTO_SCREEN_SCALE_FACTOR
I set it equal to 1, and it looks pretty good on my 4K 32" screen.  Hope this helps?

**Comment by elieserdejesus** [comment]
> I tried creating an Environment Variable: QT_AUTO_SCREEN_SCALE_FACTOR
> I set it equal to 1, and it looks pretty good on my 4K 32" screen. Hope this helps?

Nice, I will try a programatic solution (just one line of code) to avoid user manual setup.

**Comment by elieserdejesus** [comment]
@DVL58 , I compiled a beta version enabling high dpi scaling direct in the code.

Can you install the beta in your machine, please?

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.10-beta

**Comment by elieserdejesus** [comment]
@DVL58 , I compiled a beta version enabling high dpi scaling direct in the code.

Can you:
1 -  Remove your QT_AUTO_SCREEN_SCALE_FACTOR variable
2 - install the beta in your machine and see if the problem is solved, please?

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.10-beta

**Comment by DVL58** [comment]
Thank you for the quick response.  
The beta definitely increased the size of the view.  Not to be too picky, but it's actually a bit too large now; I can't see all the contents, and it seems I can't reduce the window size further.  I think it could be scaled down about 25% to 30% from the new size in the beta. 
QT_SCALE_FACTOR = 2 worked nicely on both computers and 3 different 4K monitors.  
Thanks again!  You're amazing!

**Comment by elieserdejesus** [comment]
I just enabled the high dpi scale factor, but the scale factor value is setted by Qt or Windows, I`m not shure.

**Comment by DVL58** [comment]
OK.  It works as expected then.  If I change the scale factor using windows or the QT_SCALE_FACTOR environmental variable, the UI scales as expect.  Great job!  Thanks again.
