### ISSUE TITLE
Can't install on linux ubuntu 18.04LTS

### ISSUE THREAD

**Issue by tonioliveira** [elieserdejesus/JamTaba#1217]
The .run file from the jamtaba.com does not install.

**Comment by elieserdejesus** [comment]
@tonioliveira , you changed the file permission to be an executable? (chmod +x) ?

**Comment by tonioliveira** [comment]
Yes, i did and the result in the terminal was:
<pre><font color="#55FF55"><b>tonioliveira@tonioliveira</b></font>:<font color="#5555FF"><b>~/Downloads</b></font>$ sudo chmod +x ./Jamtaba2_Installer_64bits.run
[sudo] password for tonioliveira: 
<font color="#55FF55"><b>tonioliveira@tonioliveira</b></font>:<font color="#5555FF"><b>~/Downloads</b></font>$ sudo ./Jamtaba2_Installer_64bits.run
Verifying archive integrity...  100%   All good.
Uncompressing Jamtaba 2 Installer  100%  
Installing Jamtaba 2 in  /home/tonioliveira/Jamtaba2
cp: cannot create regular file &apos;/home/tonioliveira/Desktop/&apos;: Not a directory
chmod: cannot access &apos;/home/tonioliveira/Desktop/Jamtaba2.desktop&apos;: No such file or directory</pre>
After that a folder named **jamtaba2** was created in my desktop. I opened the terminal into this folder and tried to run the **installer_script.sh** script and the terminal returns:
<pre><font color="#55FF55"><b>tonioliveira@tonioliveira</b></font>:<font color="#5555FF"><b>~/Jamtaba2</b></font>$ sudo ./installer_script.sh
Installing Jamtaba 2 in  /home/tonioliveira/Jamtaba2
cp: &apos;.&apos; and &apos;/home/tonioliveira/Jamtaba2/.&apos; are the same file
cp: cannot create regular file &apos;/home/tonioliveira/Desktop/&apos;: Not a directory
chmod: cannot access &apos;/home/tonioliveira/Desktop/Jamtaba2.desktop&apos;: No such file or directory
<font color="#55FF55"><b>tonioliveira@tonioliveira</b></font>:<font color="#5555FF"><b>~/Jamtaba2</b></font>$ </pre>
Obs: i also installed the dependency for Qt 5 Websockets as recomended.

**Comment by elieserdejesus** [comment]
@tonioliveira , please test the new beta? https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.10-beta

After run the installer you **will NOT see an icon in your desktop**. Open your applications when you will see JamTaba icon.

Tested in Ubuntu 18.

**Comment by tonioliveira** [comment]
I downloaded the new beta release. The instalation was done but the app didn't launch.
Sorry :(

**Comment by elieserdejesus** [comment]
@tonioliveira , since I tested using the same Ubuntu verion than you (Ubuntu 18) I can't reproduce the problem without more details. If you have some clues share here.

**Comment by tonioliveira** [comment]
Thanks

**Comment by tonioliveira** [comment]
I solved the problem.
When i openned a terminal inside the Jamtaba2 folder and run the Jamtaba2.sh, the return was:
`/home/tonioliveira/Jamtaba2/./Jamtaba2: error while loading shared libraries: libQt5Multimedia.so.5: cannot open shared object file: No such file or directory`
So i installed the libQt5Multimedia.so.5
`sudo apt-get install libqt5multimedia5`
Now, the program is running
Thanks

**Comment by elieserdejesus** [comment]
@tonioliveira , are you using the last version (v2.1.10)? I'm asking because this libqt5multimedia5 issue was solved. Please let me know if the qt lib is still missing in the last version.

**Comment by tonioliveira** [comment]
yes, the version is 2.1.10 from the download link in jamtaba.com

**Comment by elieserdejesus** [comment]
thanks, I will open a new issue to fix this.
