### ISSUE TITLE
Your Jamtaba version is not compatible with previous versions

### ISSUE THREAD

**Issue by mickrip** [elieserdejesus/JamTaba#1218]
Hi there, I'm running windows 10. Downloaded the 64bit version. Got this straight away. Any ideas?

![image](https://user-images.githubusercontent.com/320334/77814815-718d6880-70ac-11ea-90b8-1eb650e780aa.png)

**Comment by elieserdejesus** [comment]
just a temporary error in the server due to many users. Just try again.
