### ISSUE TITLE
1920x1080 display cannot fully contain JamTaba2 window (which is not resizable)

### ISSUE THREAD

**Issue by strk** [elieserdejesus/JamTaba#1220]
It could be I made some chages to QT config but I don't remember which ones, now the problem is that the JamTaba2 window does not fit into my 1920x1080 screen - ideas how I could solve this ?

**Comment by elieserdejesus** [comment]
no idea, sorry.

**Comment by elieserdejesus** [comment]
@strk , I have a beta version enabling high dpi scale. Maybe this will solve your issue too? Please install and test the beta: https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.10-beta

**Comment by strk** [comment]
I suppose my problemis_low_ DPI (or the GUI would be tiny, not
overlowing). I must have changed default QT widget sizes in the
past, to be able to use some QT based GUI from the couch
(2-meters distance), so I guess this issue is really about
"adaptability" of the GUI (like: why cannot I reduce the size
of the GUI?)

**Comment by elieserdejesus** [comment]
> why cannot I reduce the size of the GUI?

This is new for me, Standalone, VST and AU plugin are resizable.

Can you clarify?

**Comment by strk** [comment]
> Standalone, VST and AU plugin are resizable.

Standalone app, yes can be resized but not below
a given minimum width/height, which is what I think I'm hitting.

**Comment by elieserdejesus** [comment]
JamTaba has a minimum size to avoid a complete mess in the GUI.

But you mentioned " now the problem is that the JamTaba2 window does not fit into my 1920x1080 screen". I'm using a 1920x1080 monitor right now and I can't see the problem you are reporting. 

I think it's something in your side. Can you share a screenshot here?

**Comment by strk** [comment]
Here's a screenshot

![jamtaba](https://user-images.githubusercontent.com/289678/78179182-14edcd00-7461-11ea-82ad-259fb0b4dd7a.png)

**Comment by strk** [comment]
Found: I had this set: `QT_DEVICE_PIXEL_RATIO=2` -- unsetting that env variable fixes the problem for me (but it would still be nice if Jamtaba2 could be used with bigger widgets...
