### ISSUE TITLE
Problem with VstPugin : midi controller 

### ISSUE THREAD

**Issue by Sebls135** [elieserdejesus/JamTaba#1225]
Hi,

I use a Vstlugin with midi controller but I can't control my preset with it
when I can with the software of the plugin.

Could you help me?

In Addition, do you know how to add a audio file in a room?

Thank you

Best Regards

**Comment by elieserdejesus** [comment]
The midi capabilities in JamTaba are very simple, I think you will not be able to control the plugin.

About the audio file in a room: when you are connected in a room you will see the **Looper** button, closest to SOLO and MUTE buttons. Using the looper is possible load an audio file and keep this audio playing.

Another method is use jamtaba as a VST plugin in the master channel of your preferred DAW. Load the audio file in your DAW and now you have this audio playing in JamTaba.
