### ISSUE TITLE
Documentation Update: Windows 7

### ISSUE THREAD

**Issue by karanko** [elieserdejesus/JamTaba#1227]
Any chance the documentation can be updated to say 2.1.8 is that last version to support Windows 7. due to dependencies on api-ms-win-core-**winrt**-l1-1-0.dll, which looks like its part of the Windows 10 SDK.

**Comment by elieserdejesus** [comment]
@karanko , I will try fix this Win 7 problem using a old Qt version. 

The B plan will be update the documentation as you suggested.

**Comment by elieserdejesus** [comment]
Fixed, the new version (2,1,11) will be released soon.
