### ISSUE TITLE
Missing DLLs in Windows binaries

### ISSUE THREAD

**Issue by Spacechild1** [elieserdejesus/JamTaba#1229]
I tried to run the pre-built Windows binaries but can't because following DLLs are missing:

API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
DCOMP.DLL
IESHIMS.DLL

Some of them apparantly are private APIs introduced in Windows 8:

https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls?forum=windowsgeneraldevelopmentissues

Could it be that the plugins only run on Windows 8 and above? Just want to make sure. Thanks!

**Comment by elieserdejesus** [comment]
Hi Cristof, are you using Windows 7?

The last version is not working in Win 7, please download and install the
previous version.

I will try to tix this win 7 problem in this week.

Elieser

Em qui., 2 de abr. de 2020 às 18:02, Christof Ressi <
notifications@github.com> escreveu:

**Comment by Spacechild1** [comment]
Thanks!

**Comment by elieserdejesus** [comment]
Fixed, the new verson will be released soon.
