### ISSUE TITLE
weird crash with my spd-30

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#123]
when I use the looper function (midi looper) Jamtaba crashes. All I can tell is that the SPD is sending midi clock info through the USB to Jamtaba and when I press record or play (that means a start/stop msg) it crashes.

very odd...

EDIT: confirmed. Turning off the send start msg the problem is solved.

**Comment by elieserdejesus** [comment]
Ezee, I'm 87.45% shure the problem is in RtMidiDriver. We need check how many bytes are in this start/stop messages.  I don't have any device here to send this messages. 
Maybe we can write a "FakeMidiController" periodically generating midi messages to test :)

**Comment by jonjamcam** [comment]
87.45% sure? sure? lol

**Comment by Ezeer** [comment]
**" Maybe we can write a "FakeMidiController" periodically generating midi messages to test :) "**
Sure man , you need my joystick now ! eh eh ...
If i can crash Jamtaba with joybutton2 , i can send cc with button2

Nah ... just create a button somewhere and signal/slot it to sendStartStop() in your midi class .
That is fun to do , i like that kind of job .

about the midi msg : http://www.blitter.com/~russtopia/MIDI/~jglatt/tech/midispec/start.htm
only status byte is sent , no data . So if we read data .... crash ?

more readings : https://www.soundonsound.com/sos/1995_articles/oct95/midibasics3.html

**Comment by jonjamcam** [comment]
This crash not longer happening. closing

**Comment by elieserdejesus** [comment]
Nice news!
