### ISSUE TITLE
Hey ive been trying for the last few hours to connect my midi drums (Roland TD-1) To the jamtaba software, it has recognised when i hit the drums but it doesn't translate it to any sort of audio. The red line goes up and down but the audiotrack stays stationary. Can anyone help me? thanks :)

### ISSUE THREAD

**Issue by BenOgden72** [elieserdejesus/JamTaba#1235]
![Untitled](https://user-images.githubusercontent.com/63171838/78462874-5d5df280-76ce-11ea-9b29-444070a3e156.png)

**Comment by elieserdejesus** [comment]
@BenOgden72 , JamTAba is recognizing your Roland TD-1 as a MIDI controller. The red line you are seeing represents the MIDI input. MIDI is not sound, it's just data. You must add an VST plugin (in the bottom left) to generate sounds. 

Another method is plug the audio output of your TD-1 in your computer (using an external audio interface), and you can use the built-in drum sounds of TD-1.

Using TD-1 as a MIDI controller you can use any drum VST plugin and tons of new drum sounds.
