### ISSUE TITLE
Geolocalisation fails : error when writing in cacheDir ?

### ISSUE THREAD

**Issue by arnaudlecam** [elieserdejesus/JamTaba#1236]
It seems that geolocalisation functions fails:
> default.CRITICAL  [01:40:37:690] Can't open the file  "country_codes_cache.bin" [WebIpToLocationResolver.cpp, line 332]
> default.CRITICAL  [01:40:37:690] Can't open the file  "lat_long_cache.bin" [WebIpToLocationResolver.cpp, line 312]
> default.CRITICAL  [01:40:37:691] Can't open the file  "country_names_cache_en.bin" [WebIpToLocationResolver.cpp, line 322]

As a result, no flag appears on the map (default values 'UNKNOWN' for all the people).
During my tests, I noticed your API's account aren't valid yet. I tried with mine, without any succes.
So, I can't locate the bug : sorry...
But I suppose you should reproduce it, by deleting your cacheDir before runing/debugging JamTaba.

**Comment by jonjamcam** [comment]
Hi @arnaudlecam . As I understand @elieserdejesus  dropped that code here https://github.com/elieserdejesus/JamTaba/commit/4de08a48049e9e6c23d0649d7ac442334388f8cd

Maybe you're compiling a previous version.

**Comment by arnaudlecam** [comment]
Hi @jonjamcam 
You're right, it fixed it, thank you
