### ISSUE TITLE
private server

### ISSUE THREAD

**Issue by josepeps** [elieserdejesus/JamTaba#1241]
I installed the latest version and I can't get the private server to work ,It connects, opens the port, receives, I can use the chat and see the mixer from which I connect, but it does not send or receive the sound .with the same configuration if it works well on a public server .
I have already tried everything, the button that says "receive" catches my attention in the mixer because it could not always be activated .this happens in the stand alone version as in the plugin with reaper
thanks for helping

**Comment by elieserdejesus** [comment]
@josepeps , you have other musicians connected in your private server? 

I'm asking this because if others can connect in your server is very weird the audio is not sended or received. If you have some router configuration problem (this is the common problem with private servers) other users cant't connect.

**Comment by josepeps** [comment]
If I have tried with another remote musician, the only way to see the mixer is also to connect to the created server as the pop up asks me, I have opened the port of my router, I should check the router of the other musician, they are already tired of my insistence haha, the truth is frustrating given that due to the current situation I had to suspend any social activity and this was the glory haha
I appreciate a lot for your help

**Comment by elieserdejesus** [comment]
I understand the frustation @josepeps , but unfortunally in this case I don't know a easy to use solution.

The first thing to try is check if your router has UpNp support. If yes, try to enable and jamtaba will try to open the ports for you. 

To test if your port is opened use this site: https://www.yougetsignal.com/tools/open-ports/. If your port is not opened for this site your friends will not be able to reach your server.

If I put my own ip in this site and test against port 2049 I see the port is closed (this is ok, I'm not hosting nothing). If I change the IP address in the site to "ninbot.com" and test this is thre result:
![image](https://user-images.githubusercontent.com/1012741/78586197-7b803b80-7811-11ea-94c3-0711fb0045a4.png)

**Comment by josepeps** [comment]
indeed it is as I tested it and the result was open port, I also used current ports of nirsoft to see what happened. I will continue testing, if I find a solution I will comment on what the problem was, again thank you very much

**Comment by elieserdejesus** [comment]
@josepeps , are you using the corrent IP? Just asking to explore the possibilities.
you have 2 IPs, one local (useless for ninjam jams) and one external IP. You must use the external IP. Your external IP will be visible in the site I posted before. Sorry if you know about the external IP, i'm just trying to help.

**Comment by josepeps** [comment]
elieserdejesus! I was a great fool haha, I was not transmitting confused by the color status of the red-green button, it works wonders, thanks for your time and patience friend

**Comment by elieserdejesus** [comment]
nice news @josepeps 😄
