### ISSUE TITLE
Ableton and JamTaba vst

### ISSUE THREAD

**Issue by ikyquocked** [elieserdejesus/JamTaba#1244]
Hi, I installed jamtaba (win64) and Ableton doesnt find the vst plugin, are they compatible?

**Comment by elieserdejesus** [comment]
@ikyquocked , yes is compatible, I'm using Ableton sometimes without problems.

check if you installed JamTaba VST plugin in a folder where Ableton is "looking".
And check if your Ableton is 64 bits. 

I can't imagine another possibilites, just these 2.
