### ISSUE TITLE
Can't start private server: The bound address is already in use

### ISSUE THREAD

**Issue by jaimeiniesta** [elieserdejesus/JamTaba#1247]
Hi!

I'm using JamTaba on macOs Catalina. When I try to host a private server via `Ninjam > Host a private server in your machine` I get the following error:

`The bound address is already in use`

I'm not sure how to fix this, or choose another port.

**Comment by elieserdejesus** [comment]
hi @jaimeiniesta , at moment is not possible choose another port for private server.

the message "The bound address is already in use" means another software is using the port 2049 and jamTaba can't use the same port.

**Comment by Randgalt** [comment]
2049 is a reserved port for nfsd. Why did you use that?

**Comment by elieserdejesus** [comment]
> 2049 is a reserved port for nfsd. Why did you use that?

This is the default port in ninjam servers (defined very long time ago)
