### ISSUE TITLE
Doxygen doc for devTeam ?

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#125]
It is very hard for a coder that never touched the Qt environment , to understand the framework and
the hierarchy of objects . We can use Qt doc for that , but the way Qt is used in Jamtaba source is
independent from any source .

So i propose to make a doc that should speed our workflow ( you know your code elieser , i am still learning ) .I can make a doc for me , but a centralized is better .
Have a cron job to make the doc is something i've never done , but sounds cool ....

Doc for Jamtaba2 is up here : http://makeitezeeah.esy.es/Jamtaba2/master/html/index.html

**Comment by elieserdejesus** [comment]
Ezee, I like the idea, but I never work with doxygen. How this work?
My eperience with docs is just javadoc.

**Comment by Ezeer** [comment]
I have a cool doc i just compiled , i upload it in my personal site , then give a link here .
I use a wizard , you choose the source folder , check some options , press run , done !
http://www.stack.nl/~dimitri/doxygen/download.html

**How this work?**
http://www.stack.nl/~dimitri/doxygen/manual/starting.html
;)

**Comment by Ezeer** [comment]
Doc is here : http://makeitezeeah.esy.es/Jamtaba2/html/index.html
Unfortunatly ( because i'm dumb ) , that doc is not the Master doc BUT the configurator branch i was
working with in git ....
So you have some modifications that aren't official .
I will do an other one that point on master , but look how it's cool : 
file:///E:/JamTaba/DOC/html/class_configurator.html

**Comment by elieserdejesus** [comment]
These docs are really nice, let's do it.
We can't store these docs in github, right? I see portaudio doxygen stuff is in the official site, not in the repository: [http://portaudio.com/docs/v19-doxydocs/](http://portaudio.com/docs/v19-doxydocs/)

**Comment by Ezeer** [comment]
What we can store is the doxygen file used by the generator to produce the doc with the selected
options and specs .
To have a doc online is a must , i think you should try to make it yourself to not be dependent from
someone ( and also to manage the updates of the doc from releases to releases )
That is not a big effort , a doc is compiled easily in less 10 minutes .
Upload the first time takes times , but then for updates only the changed files are treated , so ...

I'm gonna make a doc for the actual master now , i'll put a link in the readme and the wiki .
;)

**Comment by Ezeer** [comment]
My special offer , today is my birth day : 
http://makeitezeeah.esy.es/Jamtaba2/master/html/index.html

**Comment by jonjamcam** [comment]
"today is my birth day"

![happpy birthday](http://www.fundraising-ideas.org/DIY/images/pieinface.jpg)

lol.  HAPPY BIRTHDAY MAN!

**Comment by Ezeer** [comment]
ah ah ah !
very good , i like the cream , thanks jon !
lol
