### ISSUE TITLE
Video friendly grid view

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1253]
Wishlist:

Video only tab/view with no mixer or a very simplified one (pan & level at most) so 6 cameras can fit propperly.

ATM  you can see only 4 cams max and this is at best because cams and no-cams appear at random order.

**Comment by elieserdejesus** [comment]
The grid view is a "cam view". I think we can just improve the grid view to be more video friendly, just to avoid create a new layout.
