### ISSUE TITLE
Autodisable xmit button when enter in a room

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#126]
Elieser said:

"I think the best approach is auto turn on the xmit after the second whole interval is received, not the first, because when an user receive the first interval he/she is still tracking the groove or chords. So, probabily when the second interval is received the user is now playing some good music and mathing with the interval. The problem with this approach are the big BPIs. Wait 2 intervals of 64 BPI to start xmit is a lot of time, specially if the bpm is slow. Maybe something like that:
1 - BPI up to 32: enable xmit after receive 2 full intervals.
2 - BPI less than 32: enable xmit after receive 1 full interval.

What you think? I'm not shure about 32 bpi, maybe we can replace 32 bpi with 48 bpi, because sometimes people play cool bluesy jams in 48 bpi."

**Comment by jonjamcam** [comment]
I'm thinking about this and it's specially important for long BPI (32-64) when used with slow tempo (<80 BPM), but should be active at any BPM/BPI

So you enter a room and you hear silence. A text should appear saying ("XMIT is off" IT will automatically turned in 30 seconds). The text must be non invasive (maybe something down at the left near the button itself) so you can see all other information to tune up with the jam.

 A good idea may be for the button to blink for example

In my opinion one complete interval is enough, because once the second interval starts, the musician already should know what to do and will not be heard by others until the interval ends, specially with long BPIs  it's an eternity.

Another thing is that there's a lot of fast minded musicians that mute their instruments until they are sure what to play. I cases like these they can use this time to tune or check levels. Very useful thing indeed.

Even though this feature is useful for both beginner and advanced musician I think there should be a way to disable it in the preferences menu, but it has to be enabled by default during install.

**Comment by elieserdejesus** [comment]
Cool ideas Jon, let's to it for the next release!

**Comment by jonjamcam** [comment]
Can't wait!

I was thinking Jamtaba is (and will be more and more) for ninjamers like the MAC computer was to common people who couldn't understand DOS back then.

**Comment by elieserdejesus** [comment]
Done! The feature is enabled by default, I'm creating a new issue to **I think there should be a way to disable it in the preferences menu, but it has to be enabled by default during install.**

**Comment by Ezeer** [comment]
nice !

**Comment by jonjamcam** [comment]
This will be very very useful!
