### ISSUE TITLE
Setting up private network on a Mac...

### ISSUE THREAD

**Issue by diegux74** [elieserdejesus/JamTaba#1260]
Hi, this soft is great! I hope this is the right place to ask.
I am having a problem trying to host a private network from my computer, I'm on a Mac OS 10.14

When it tries to connect to the server I'm hosting, I always get a timeout error, while other people are able to connect to it. I am able to join private networks that are not being hosted by my computer.

Any clues?

Thanks a lot, best!

**Comment by elieserdejesus** [comment]
Hi, I see this problem too. After create your private server click No when prompted to connect in the server. Go to ninjam menu and Connect in private server. Use localhost as your server ip.

**Comment by diegux74** [comment]
Yes! That did the trick. Thanks so much, awesome stuff
