### ISSUE TITLE
AU Crashing In Logic

### ISSUE THREAD

**Issue by andibuch** [elieserdejesus/JamTaba#1266]
I can't seem to get the AU to load in logic

When I try, Logic hangs indefinitely on the version-check screen.

Of note: the AU bundled into the latest release is still the 2.1.10 version; it tries to get you to update to the 2.1.11, but there is no release of this anywhere that I can find

I've tried older versions.  2.1.9 loads a blank screen; 2.1.8 loads, but is too buggy to use

Is the AU version being maintained?  Is it useable these days?  Is there a trick to getting it to run in Logic?

I have crash logs if they're needed / helpful

**Comment by elieserdejesus** [comment]
@andibuch , I checked here and you are right. I messed the last Mac installer and version is wrong.

I updated the Mac installer. AU plugin working fine here in Logic X and Sierra (Mac Osx 10.12).

The new/fixed installer: https://github.com/elieserdejesus/JamTaba/releases/download/v2.1.11/Jamtaba_2_Installer.dmg

**Comment by andibuch** [comment]
@elieserdejesus – thank you for updating it!

It's no longer crashing Logic; however, it's giving me the same issue I had on old versions I've tried

If I enter a room, nothing happens in the room.  The metronome never starts clicking, it never progresses past "Preparing," the count stays locked at beat 1/24 (or beat 1 of whatever the bpi is)

Similarly, if I just click "listen" instead of "enter," the loading circle fills up, but the audio is never played

Screenshots attached

<img width="981" alt="Screen Shot 2020-04-21 at 4 57 58 PM" src="https://user-images.githubusercontent.com/20821023/79913661-fe98b880-83f1-11ea-9824-326def37b56d.png">

<img width="983" alt="Screen Shot 2020-04-21 at 5 01 53 PM" src="https://user-images.githubusercontent.com/20821023/79913671-022c3f80-83f2-11ea-8285-241d8ab19329.png">

**Comment by elieserdejesus** [comment]
@andibuch , this is a Logic behavior. You have 2 options?
1 - Use JamTaba in Logic master output. But if I remember correctly you must add one track and turn on monitoring.

2 - Use JamTaba in a common track but turn on the track monitoring.

Understanding the situation: when the tracks are *not being monitored* Logic is not sending samples to jamtaba, so JamTAba is waiting for data to process.

The solution is simple: turn on track monitoring to send samples to jamtaba.
