### ISSUE TITLE
audio device not detected

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1269]
compiling last commits, I got a problem. No audio device

![image](https://user-images.githubusercontent.com/15310433/80132652-ffecf100-8569-11ea-9097-72f5e3cc8ae1.png)

![image](https://user-images.githubusercontent.com/15310433/80132662-03807800-856a-11ea-929a-4b8ea5f7d39d.png)

after delete json file, problem persists

win7 x64

**Comment by elieserdejesus** [comment]
@jonjamcam , can you activate the audio details in the log and share the result here, please?

**Comment by jonjamcam** [comment]
Clean log:

[log.txt](https://github.com/elieserdejesus/JamTaba/files/4525263/log.txt)

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test the last commit, please? Tested here and is working fine now.

**Comment by jonjamcam** [comment]
Perfect!

Working fine now @elieserdejesus

**Comment by jonjamcam** [comment]
@elieserdejesus I found there's still the audio not detected when json file has

`"audio": {
        "audioInputDevice": "NullAudioInputDriver"`

changing to `"audio": {
        "audioInputDevice": ""` solves the issue.

**Comment by jonjamcam** [comment]
@elieserdejesus This issue is still there. To reproduce (win7 x86) I did the folowing steps:

1.- My system defaults to ASIO4ALL:

![image](https://user-images.githubusercontent.com/15310433/81778805-8178d480-94c1-11ea-81b6-4478a52f1737.png)

Json file has the correct entry:

![image](https://user-images.githubusercontent.com/15310433/81779011-d61c4f80-94c1-11ea-9164-55d9ed0bad4d.png)


2.- I close Jamtaba, plug my ME-25 guitar pedal and select the corresponding driver:

![image](https://user-images.githubusercontent.com/15310433/81779191-3612f600-94c2-11ea-9cfd-548bd1724b5c.png)

Json file updates correctly when closing:

![image](https://user-images.githubusercontent.com/15310433/81779282-62c70d80-94c2-11ea-8c95-17df201691ad.png)

3.- Disconnecting the pedal, should make ASIO4ALL the active device again, but that's not the case:
 
![image](https://user-images.githubusercontent.com/15310433/81778449-e7b12780-94c0-11ea-96d1-cea7fdac6ffc.png)

while json file still shows the previous ME-25 as audio device after closing. Again as said previously in https://github.com/elieserdejesus/JamTaba/issues/1269#issuecomment-619974456

`changing to "audio": { "audioInputDevice": "" solves the issue`.

**Comment by elieserdejesus** [comment]
Thanks for the steps @jonjamcam , I will fix soon.

**Comment by elieserdejesus** [comment]
@jonjamcam , I hope it's fixed now.

**Comment by jonjamcam** [comment]
> @jonjamcam , I hope it's fixed now.

Workng fine now @elieserdejesus . thx!
