### ISSUE TITLE
Chat Autotranslate Button or setting

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#127]
I enjoy the humor and good vive of most gyus in the rooms and now with Jamtaba, I've been able to understand some of the conversations in other languages using translate, but Every time I have to click and click and click....and it can be a lot of clicks for a conversation; not to mention that the little button moves away from the pointer as the dialogs pass....:D

Some kind of setting or button to make it automatic would be of utility and maybe when automatic an *italic* font to know it's been translated would be great!

**Comment by Ezeer** [comment]
good idea , thx !

**Comment by elieserdejesus** [comment]
Good idea Jon.
In the left of chat text input we have a white icon. We can change this icon to a toggle button (auto translate on/off). and use a translation icon like this:
![image](https://cloud.githubusercontent.com/assets/1012741/11134753/5f53568c-8986-11e5-8438-ece975bade1c.png)

**Comment by jonjamcam** [comment]
yeah . Cool!

**Comment by Ezeer** [comment]
**We can change this icon to a toggle button **
Same idea here
