### ISSUE TITLE
Auto mute based in very high RMS level

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1273]
Since we have a troll spreading very high level noise in server a auto mute feature can save some ears.

Auto mute based in peak will not work, but use rms level instead peak can be interesting.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you help in this feature? The ideia is user Reaper to discovery ninjamers average RMS level (Reaper can show RMS os Peak values).

After discover a good enough RMS level we can add a threshold to an auto mute feature. If the RMS peak is very high the track will be auto muted.  

Reaper has auto mute feature too, I'm just "stealing" the good idea.

**Comment by jonjamcam** [comment]
> @jonjamcam , can you help in this feature?

Yes. Glad to help. I will do some research on which are these thresholds. Stay tuned!

**Comment by jonjamcam** [comment]
My first test did by streaming analog white noise via usb sound card:

1.- Matching Jamtaba and reaper's db reading. Jamtaba is lowering the signal by 3 db (as stated in https://github.com/elieserdejesus/JamTaba/issues/1121#issuecomment-408639147).

![image](https://user-images.githubusercontent.com/15310433/80273051-0fb92200-869d-11ea-851b-b5171ef5b3bc.png)


2.- as 0 db of analog white noise is not enough for triggering the automute function in reaper I had to raise Jamtaba's digital levels +18.6 db to get it done. This is equivalent to barely surpassing the +3 db mark of RMS levels:

![image](https://user-images.githubusercontent.com/15310433/80273009-96213400-869c-11ea-8a75-ef52acc9f374.png)

**Comment by jonjamcam** [comment]
now to his Harrpoonnn guy:

![image](https://user-images.githubusercontent.com/15310433/80290352-a673f600-8712-11ea-940b-8a8947aa1b28.png)

(Note that in the image the track level is reduced by 10 db so Automute doesn't trigger)

Sabotage? Of course...

**Comment by elieserdejesus** [comment]
@jonjamcam , auto mute is implemented in last commit. Auto muting in -3 dB RMS. Let me know if this threshold is good enough.

I will generate a beta to help people avoid this guy.

**Comment by jonjamcam** [comment]
The automute is working, but it's not instantaneous as in Reaper where the sound is not heard, just muted. The loud level in Jamtaba is heard for a microsecond and then the track is muted. I don't know @elieserdejesus if it's possible to detect the high level before sending to the channel?

**Comment by elieserdejesus** [comment]
>  I don't know @elieserdejesus if it's possible to detect the high level before sending to the channel?

Is possible @jonjamcam , but is necessary change more code in audio engine, I think is better avoid these changes in this moment to avoid side effects.

**Comment by jonjamcam** [comment]
@elieserdejesus just noticed some users muted because of the -6db threshold. This is a real jam, so I believe it should be raised. Maybe test with -3 db for the moment.

**Comment by elieserdejesus** [comment]
> Maybe test with -3 

Thanks @jonjamcam , changed in https://github.com/elieserdejesus/JamTaba/commit/9d650ef5825d385c748f40af8c30a776f163ce12
