### ISSUE TITLE
jamtaba 2 vst not connecting

### ISSUE THREAD

**Issue by modman2019** [elieserdejesus/JamTaba#1277]
No matter what DAW I use I cant get a connection to a room. I have never seen this before.  In the past it worked.   The standalone version works fine but not the vst version.

**Comment by elieserdejesus** [comment]
Check your firewall rules, if your DAWs are blocked in the firewall jamtaba can't use network.

**Comment by modman2019** [comment]
They are not

**Comment by modman2019** [comment]
I even turned off my firewall entirely and nothing worked

**Comment by modman2019** [comment]
I installed the older version for 2018 and I can get into some room. Theres something wrong with the newest version

**Comment by elieserdejesus** [comment]
no other user reported the same problem, and I can't fix a bug if I can't see the bug. 

Standalone and VST are sharing exatly same networking code, so this is another reason to think is something in your side (you mentioned standalone is working).

**Comment by modman2019** [comment]
So in the older version I see little triangles that say server is not connecting whereas the new version doesnt show that.  so it maybe I kept clicking rooms that were not actually set up

**Comment by jonjamcam** [comment]
@modman2019 check this other issue https://github.com/elieserdejesus/JamTaba/issues/1279

You're having this same issue in win10? It may solve the problem for the moment.

**Comment by modman2019** [comment]
yes its windows 10. will do next time I run it. do you want me to use the most recent version correct?

**Comment by jonjamcam** [comment]
> yes its windows 10. will do next time I run it. do you want me to use the most recent version correct?

Not really. First run jamtaba as it is now (not working) and share your log here.

Then download version 2.1.10 from here:

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.10

And see if it solves your problem. Again please post the results here (log file). Maybe we'll find hints to solve this issue in the futre. Thx.

**Comment by modman2019** [comment]
2.1.10 is working fine now. Not sure what was going on the other day.
