### ISSUE TITLE
VST can't connect to any room.

### ISSUE THREAD

**Issue by fmarinheiro** [elieserdejesus/JamTaba#1279]
Hi, I have been trying to use the vst but can never enter any room no matter what daw I use.

As stand alone app jamtaba is working flawlessly to me, no problems, but the vst version is always returning a connection timed out error.

Is this a known issue? Is there any extra configuration needed to work in vst mode? 
I already disabled the windows firewall but it doesn't seem to make much difference.

My main daw it's Studio One 4 but it's the same on other daws. 

Thanks for keeping up this awesome piece of software.

**Comment by elieserdejesus** [comment]
> Is this a known issue? Is there any extra configuration needed to work in vst mode?

No, it's not a known issue. No extra configuration is needed.

Can you **listen** the rooms before enter?

**Comment by fmarinheiro** [comment]
Hi, thanks for replying. 
Yes i can listen rooms without any problem just can't enter them, but oddly enough it takes just a couple of seconds to connect in the stand alone mode. 

Is then any logging i can activate that might be useful to help you debug this?

**Comment by fmarinheiro** [comment]
I don't  it helps, but I see this in the jamtaba vst logs:

`
default.INFO      [16:29:45:162] JamTaba Base dir: "C:/Users/Filipe Marinheiro/AppData/Roaming/Jamtaba 2/VstPlugin" [, line 0]
default.WARNING   [16:29:45:175] SetProcessDpiAwareness failed: "COM error 0xffffffff80070005  (Unknown error 0x0ffffffff80070005)" [, line 0]
default.WARNING   [16:29:45:249] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [16:29:45:260] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.INFO      [16:29:45:329] "Starting Jamtaba 2.1.12 Vst Plugin (x86_64) running on Windows 10 (x86_64) running in Studio One" [, line 0]
default.WARNING   [16:29:45:424] libpng warning: iCCP: known incorrect sRGB profile [, line 0]
default.WARNING   [16:30:45:244] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [16:30:53:381] QObject::disconnect: Unexpected null parameter [, line 0]
default.WARNING   [16:30:53:393] QObject::disconnect: Unexpected null parameter [, line 0]
default.WARNING   [16:31:45:244] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
`

**Comment by elieserdejesus** [comment]
the log you pasted here is mentioned in a Qt bug (JamTaba is using Qt). 

But only you is seeing this problem in JamTaba, no more ideas here.

**Comment by fmarinheiro** [comment]
OK thanks
I enable more logging in vst logging.ini and this is what i got when i press enter:

`jt.Core.DEBUG     [18:05:07:483] EnterInRoom slot [, line 0]
jt.Core.DEBUG     [18:05:07:494] connecting... [, line 0]
default.WARNING   [18:05:34:547] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
jt.Ninjam.Protocol.WARNING  [18:06:07:593] "Connection timed out" [, line 0]
jt.Core.WARNING   [18:06:07:607] "Connection timed out" [, line 0]
default.WARNING   [18:06:26:940] QObject::disconnect: Unexpected null parameter [, line 0]
default.WARNING   [18:06:26:962] QObject::disconnect: Unexpected null parameter [, line 0]`
`

It seems indeed related with qt but i don't really know what is can do, if anyone knows something about this please HELP us.

**Comment by jonjamcam** [comment]
@fmarinheiro What OS are you using?

**Comment by fmarinheiro** [comment]
Thanks @jonjamcam 
I'll try that later, and post the result here.

**Comment by Jonathhhan** [comment]
> @fmarinheiro What OS are you using? if win10, try an older version of Jamtaba. It has some problems because it was compiled with a newer version of QT, but it may work for you
> 
> https://github.com/elieserdejesus/JamTaba/releases/download/v2.1.10/Jamtaba.2.64.bits.installer.exe
> 
> if it works, share your log here. thx

thanks for the hint, it solved (so far) all the issues i had before...

**Comment by N0N3Diminished** [comment]
I had this same issue last night. Will post logs tonight. 

I found if it click option "help>version" in the VST while it's trying to connect it works. If I don't ask it to report version, I have exact same problem. 

Can listen, but not connect. Standalone works fine. Can't connect to any room, get connection timed out error. Bandmate running the server saw me connected on his end till timeout error.

**Comment by fmarinheiro** [comment]
@jonjamcam  Thanks, I tried the 2.1.10 and it seems to work fine like the others said above, the vst mode works ok.

Are there plans to update QT version or perhaps solving the issue? 

Here is the log for the 2.1.10 version:

` jt.Core.DEBUG     [00:24:44:127] EnterInRoom slot [, line 0]
jt.Core.DEBUG     [00:24:44:139] connecting... [, line 0]
jt.Ninjam.Protocol.DEBUG    [00:24:44:367] socket connected on  "ninjam.discordonlinejammingcentral.com" [, line 0]
jt.Core.DEBUG     [00:24:44:748] connected in ninjam server [, line 0]
jt.Ninjam.VorbisDecoder.DEBUG    [00:24:44:765] Destrutor Vorbis Decoder [, line 0]
jt.Ninjam.VorbisDecoder.DEBUG    [00:24:44:780] Destrutor Vorbis Decoder [, line 0]
jt.Ninjam.VorbisDecoder.DEBUG    [00:24:44:796] Destrutor Vorbis Decoder [, line 0]
jt.GUI.DEBUG      [00:24:44:808] hidding busy dialog... [, line 0]
jt.GUI.DEBUG      [00:24:44:822] creating NinjamRoomWindow... [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:44:836] NinjamRoomWindow::NinjamRoomWindow ctor [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:44:852] NinjamPanel::NinjamPanel ctor [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:44:875] NinjamPanel::NinjamPanel done [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:44:900] connecting signals in ninjamController... [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:44:911] NinjamRoomWindow::NinjamRoomWindow done [, line 0]
jt.GUI.DEBUG      [00:24:44:956] adding ninjam chat panel... [, line 0]
jt.GUI.DEBUG      [00:24:45:021] adding ninjam panels... [, line 0]
jt.GUI.DEBUG      [00:24:45:080] MainWindow::enterInRoom() done! [, line 0]
jt.Core.DEBUG     [00:24:45:091] starting ninjamController... [, line 0]
jt.Ninjam.Core.DEBUG    [00:24:45:101] starting ninjam controller... [, line 0]
jt.Ninjam.VorbisEncoder.DEBUG    [00:24:45:114] Initializing Encoder sampleRate: 48000  channels:  2  quality:  0 [, line 0]
jt.Ninjam.Core.DEBUG    [00:24:45:126] Starting Encoding Thread [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:45:137] channel added - creating channel view: "EtherNet@152.169.195.x"   "" [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:45:186] channel view created [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:45:201] channel added - creating channel view: "SLG@84.62.141.x"   "Acoustic Guitar" [, line 0]
jt.Ninjam.GUI.DEBUG    [00:24:45:242] channel view created [, line 0]
jt.GUI.DEBUG      [00:24:45:253] adding ninjam panels... [, line 0]
jt.Ninjam.Core.DEBUG    [00:24:45:264] ninjam controller started! [, line 0]
default.WARNING   [00:24:45:290] QPainter::begin: Paint device returned engine == 0, type: 2 [, line 0]
default.WARNING   [00:24:45:300] QPainter::setPen: Painter not active [, line 0]
default.WARNING   [00:24:45:312] QPainter::setFont: Painter not active [, line 0]
default.WARNING   [00:24:45:329] QPainter::begin: Paint device returned engine == 0, type: 2 [, line 0]
default.WARNING   [00:24:45:341] QPainter::setPen: Painter not active [, line 0]
default.WARNING   [00:24:45:352] QPainter::setFont: Painter not active [, line 0]
`

Thanks, let me know if you need more information.

**Comment by fmarinheiro** [comment]
Like @N0N3Diminished said just leaving the current version popup open helps a lot in the latest version it's pretty bizarre but it works somehow. 

After entering a room if i close that pop up the audio goes away in the next interval but if i open it it comes back in.

**Comment by Jonathhhan** [comment]
> Like @N0N3Diminished said just leaving the current version popup open helps a lot in the latest version it's pretty bizarre but it works somehow.
> 
> After entering a room if i close that pop up the audio goes away in the next interval but if i open it it comes back in.

I can confirm that. But because I cannot change anything while the pop up is open, I use the older version 2.1.10 for now.

**Comment by fmarinheiro** [comment]
Hi @Jonathhhan 

I think that opening the version pop up and then closing it when you just enter the room then keeping the metronome floating window might do the trick in this case.

But ideally the bug could be fixed, this discussion might offer have a good clue to what's happening, I don't know the app or the technology behind it to do it :) 
This is an awesome tool as it is already and i think it can become even better.

**Comment by elieserdejesus** [comment]
Hello @fmarinheiro , @Jonathhhan , @N0N3Diminished 

I compiled JamTaba beta using a newer Qt version. Can you test to see if the problem is solved?
https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.13-beta

**Comment by N0N3Diminished** [comment]
@elieserdejesus awesome thanks! Will give it a test over the next day and let you know.

**Comment by Jonathhhan** [comment]
@elieserdejesus thanks a lot. After a quick test it seems to work for me. I will do another test tomorrow.

**Comment by elieserdejesus** [comment]
> @elieserdejesus thanks a lot. After a quick test it seems to work for me. I will do another test tomorrow.

Nice news!!

**Comment by fmarinheiro** [comment]
@elieserdejesus Awesome, I quickly tested and it seems to be working perfectly. I'll try it later tonight to jam with it a more time and post my findings here, but right now seems fine. 
Thanks, keep up the good work.

**Comment by HammertheBammer** [comment]
Beta 2.1.13 version works for connection  to rooms again. I heard in te rooms  that 2.11 and 2.12 gives connection problems and they go back to 2.10.. In 2.13 I can conenct to rooms, had same problem as described above. Thanks for the good work..

**Comment by elieserdejesus** [comment]
Thanks for yout time testing the beta guys, I will release a new version soon the solve this connection issue.

**Comment by fmarinheiro** [comment]
@elieserdejesus  Jamming for hours and everything is normal.

**Comment by elieserdejesus** [comment]
Thanks for the feedback @fmarinheiro 👍 .
