### ISSUE TITLE
Bug when  come back in another room - Reported by DoubleBass

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#128]
Theres  a problem  when leaving a room,  it is impossible to come back in another room .  Even closing and adding the vst jamtaba,  i need to  close reaper and to restart it , after its ok

**Comment by Ezeer** [comment]
Just for the joke : A static window perhaps ? ( mwah aha ha , but i will put no money on this this time )
;)

**Comment by Ezeer** [comment]
While i was searching for something for my Configurator branch , i've found that : 

void MainWindow::**on_enteringInRoom(Login::RoomInfo roomInfo, QString password)**{

    //stop room stream before enter in a room
    if(mainController->isPlayingRoomStream()){
        long long roomID = mainController->getCurrentStreamingRoomID();
        if(roomViewPanels[roomID]){
            roomViewPanels[roomID]->clearPeaks(true);
        }
        mainController->stopRoomStream();
    }

    if(!mainController->userNameWasChoosed()){
//        bool ok;
//        QString lastUserName = mainController->getUserName();
//        QString newUserName = QInputDialog::getText(this, "", "Enter your user name:", QLineEdit::Normal, lastUserName , &ok, Qt::FramelessWindowHint);
//        if (ok && !newUserName.isEmpty()){
//           mainController->setUserName(newUserName);
//           setWindowTitle("Jamtaba (" + mainController->getUserName() + ")");
//        }
        QString lastUserName = mainController->getUserName();
        UserNameDialog dialog(this, lastUserName);
        if(isRunningAsVstPlugin()){
            centerDialog(&dialog);
        }
        if(dialog.exec() == QDialog::Accepted){
            QString userName = dialog.getUserName();
            if(!userName.isEmpty()){
                mainController->setUserName(userName);
                setWindowTitle("Jamtaba v" + QApplication::applicationVersion() + " (" + userName + ")");
            }
        }
    }
**PERHAPS THE PROBLEM COMES FROM BELOW ?**
>if(mainController->isPlayingInNinjamRoom()){
        mainController->stopNinjamController();//disconnect from current ninjam server
        //store the room to jump and wait for disconnectedFromServer event to connect in this new room
        **roomToJump.reset( new Login::RoomInfo(roomInfo));**
        passwordToJump = password;
    }
    else if(mainController->userNameWasChoosed()){
        showBusyDialog("Connecting in " + roomInfo.getName() + " ...");
        mainController->enterInRoom(roomInfo, getChannelsNames(), password);
    }

}

**Comment by Ezeer** [comment]
A possible memory leak could happen in  : 

roomToJump.reset( new Login::RoomInfo(roomInfo));
if Cleaned failed for exemple ...
inline void reset(T *other = 0)
    {
        if (d == other)
            return;
        T *oldD = d;
        d = other;
        Cleanup::cleanup(oldD);
    }

**Comment by Ezeer** [comment]
I see a possible problem linked to our issue : 
MainController.cpp line 301 : 

void MainController::setUserName(QString newUserName){
    if(!newUserName.isEmpty()){
        settings.setUserName(newUserName);
        userNameChoosed = true;
    }
    else{
       **qCritical() << "empty userNAme";** <----- JUST A MESSAGE ?
    }
}

DOublebass entered his nickname or just press enter ?
The problem continue here : 
maincontroller line 705
if(!mainController->userNameWasChoosed()){
//        bool ok;
//        QString lastUserName = mainController->getUserName();
//        QString newUserName = QInputDialog::getText(this, "", "Enter your user name:", QLineEdit::Normal, lastUserName , &ok, Qt::FramelessWindowHint);
//        if (ok && !newUserName.isEmpty()){
//           mainController->setUserName(newUserName);
//           setWindowTitle("Jamtaba (" + mainController->getUserName() + ")");
//        }

Nothing is done actually in that case ...

**Comment by jonjamcam** [comment]
I've tested it and for now, no problems. I can switch rooms properly. I'll keep an eye on this on next jams during the week.

**Comment by Ezeer** [comment]
Thank you Jon !

**Comment by Ezeer** [comment]
It is not possible normally to connect without a username ( aha ah ... elieser was smiling at that point ) : 
void MainController::tryConnectInNinjamServer(Login::RoomInfo ninjamRoom, QStringList channelsNames, QString password){
    qCDebug(jtCore) << "connecting...";
    if(userNameWasChoosed()){**//just in case :)** <------ LOL !
        QString serverIp = ninjamRoom.getName();
        int serverPort = ninjamRoom.getPort();
        QString userName = getUserName();
        QString pass = (password.isNull() || password.isEmpty()) ? "" : password;

        this->ninjamService.startServerConnection(serverIp, serverPort, userName, channelsNames, pass);
    }
    else{
        qCritical() << "user name not choosed yet!";
    }
}

**Comment by Ezeer** [comment]
If we had the log , we probably would be able to understand the issue .
@jonjamcam  As you are the first beta tester , could you inform the other beta to send to you or post
here their logs ? That would be very useful . Thx !
![bigstock-leadership-power-concept-d-i-44991157](https://cloud.githubusercontent.com/assets/1283808/11168443/69bb0880-8b8f-11e5-9c2e-07705812d2cb.jpg)

**Comment by jonjamcam** [comment]
Right, the log file......

**Comment by Ezeer** [comment]
Also that bug seem to be odd and old : #8

**Comment by elieserdejesus** [comment]
This bug it the same from #8, let's remember to close the two issues when this is fixed.
This problem is trick, In my tests I detect Jamtaba works perfect if you jump from an empty room to another. I do many tests in this conditions to avoid annoying ninjamers entering and leaving in your jams just to test. 
But, if I'm playing in a 3-4 users jam, leave, and enter in another 3-4 users jam the bug appears, and is not possible connect in any server now. No error message, nothing, just unconnectable.

This is difficult to test because we don't have many full servers everytime to test jumping around different servers. But off course this is a bug and need be fixed.

**Comment by Ezeer** [comment]
**But, if I'm playing in a 3-4 users jam, leave, and enter in another 3-4 users jam the bug appears, and is not possible connect in any server now. No error message, nothing, just unconnectable.**
That is a pretty good report !
I think i can work with that ... let's see if i can climb that mountain .
![zion-mountain-light-stephen-vecchiotti](https://cloud.githubusercontent.com/assets/1283808/11186854/0f799be8-8c84-11e5-9dbe-c295c0755654.jpg)

**Comment by Ezeer** [comment]
i had a log report #166 from DoubleBass that say : 
default.CRITICAL: GUID is not in map!

**Comment by elieserdejesus** [comment]
This is interesting, GUID is a ID used in ninjam protocol. Every ninjam interval has a GUID, a unique ID. 
When a interval reception starts Jamtaba receive a message from server, this message contains the interval GUID. This GUID is stored in a map. After this the server will transmit the interval parts. Every interval part is "marked" with the same GUID received before. 

So this log show a situation where a interval part was received, but the first step (the interval creation in Jamtaba map) not. we have the step 2, but the step 1 was skipped. 

I'm suspecting from a dirty map of GUIDs. I will look at this issue, this Double bass log is usefull and a very good clue.

**Comment by elieserdejesus** [comment]
bug fixed!

**Comment by jonjamcam** [comment]
Cool! I'm going to test this until exhaustion!!! lol
