### ISSUE TITLE
Auto level and automute enhancement

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1283]
@elieserdejesus further testing of the automute feature I see loud percussive instruments are being muted some very exeptional times. Some users use very high levels, but muting in these cases is not expected. 

So I was thinking about improving this feature by doing the following:

1. Raising the upper threshold similar to Reaper's automute (we can test 0 db and see if it works before going all the way to +3 db as last resort)

2. Adding an autoleveling feature that triggers the -12 db gain if actual -3 db used now is reached. 

I think overall this can improve a lot the jamming experience in the sense that very loud users will be adjusted automatically as they enter the server avoiding interruptions (this is specially the case for drummers)

What do you think?

**Comment by jonjamcam** [comment]
implemented in https://github.com/elieserdejesus/JamTaba/pull/1284

**Comment by elieserdejesus** [comment]
Nice @jonjamcam , the PR is merged. Thank you!
