### ISSUE TITLE
VST Timeout in Cubase

### ISSUE THREAD

**Issue by digatronicus** [elieserdejesus/JamTaba#1288]
Cannot enter rooms in Cubase 10.5.12 using the Jamtaba vst. I can listen just fine, but when I try to enter a room, it eventually says "Connection timed out". Standalone works fine. Also works fine in reaper.

As a side note, I also could not get this working in Studio One Pro 4. Same issue.

Any help would be appreciated!

-Dig

**Comment by jonjamcam** [comment]
@digatronicus  this was solved in latest release 2.1.13

**Comment by digatronicus** [comment]
> @digatronicus this was solved in latest release 2.1.13

Ah ok, thanks for the heads up. Didn't see the release yesterday.
