### ISSUE TITLE
Show Active Cams first in grid view

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1289]
In grid view show active cams first to avoid scrolling:
![image](https://user-images.githubusercontent.com/1012741/80702084-e04c5000-8ab6-11ea-8a64-d57b1ecb0042.png)

**Comment by jonjamcam** [comment]
@elieserdejesus  I noticed remote cams are too small now.  I was doing some tests with the variable `MAX_HEIGHT_IN_GRID_LAYOUT = 165` raising it to 210 I think it's a fairly good size specially if video will be at the top.

**Comment by elieserdejesus** [comment]
> MAX_HEIGHT_IN_GRID_LAYOUT = 165 raising it to 210

sure @jonjamcam 👍  , please create a PR with this change.

> And I would like to make a request (maybe this should be a separate issue) Allow camera quality to be changed in json file as with audio with same kbps as audio (64, 80, 128) for extended flexibility and standardization.

I agree, a separate issue is better.

**Comment by jonjamcam** [comment]
> I agree, a separate issue is better

Issue created https://github.com/elieserdejesus/JamTaba/issues/1293
