### ISSUE TITLE
Crash when Google chrome is open

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#129]
I'll be paying more attention to this one because I have only circumstantial evidence :D

Two times Jamtaba crashed while I had google Chrome open in the backgroud with Gmail inbox open. After I closed it not more problems....

**Comment by Ezeer** [comment]
This is  normal .
Jamtaba is coded to crash every wednesday 13 under circumstantial  only .
And no , chrome is not one of our supported plugin .
lol
![079cd3c6643828bf71e85857709b3992](https://cloud.githubusercontent.com/assets/1283808/11159275/66b2e59a-8a5e-11e5-9e7a-1b7d16363aac.jpeg)

**Comment by jonjamcam** [comment]
lol....

**Comment by jonjamcam** [comment]
Tested it today 2.0.7 and no problems at all. No more crashes with chrome open
