### ISSUE TITLE
Problem ASIO driver prevents JamTaba starting

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#1290]
When selecting a new ASIO driver in JamTaba - in this case ReaRoute ASIO driver - start up can fail:
![image](https://user-images.githubusercontent.com/1549463/80705398-426c7b80-8ade-11ea-899a-0533fb227b7f.png)
![image](https://user-images.githubusercontent.com/1549463/80705442-5ca65980-8ade-11ea-8af3-3793038189c1.png)
And then JamTaba exits, without offering the chance to try an alternative.

Of course, that means, you can't run the program to fix the problem.  Uninstall / re-install removes the settings, so you get prompted again as a work around but the problem should be detected and the user allowed to select a different driver.

Also, ReaRoute should _work_...

**Comment by jonjamcam** [comment]
Hi @pljones . I reported a similar issue here: https://github.com/elieserdejesus/JamTaba/issues/1269#issuecomment-619974456

In my case it was solved in https://github.com/elieserdejesus/JamTaba/commit/650d537be1315b83da6b8e4ac68ee27b6e35941d

**Comment by pljones** [comment]
And this time uninstall / reinstall didn't work.  Strange.
