### ISSUE TITLE
Add uncopmressed audio mode

### ISSUE THREAD

**Issue by billythehippo** [elieserdejesus/JamTaba#1299]
Hello! I'm not a good programmer, but I've managed to make an experiment with your sourcecode:
I've set the value of "EncoderQualityHigh" (vorbis.h) as 0.5f (from 0.3f), and this led to the delay encreasing when hearing on the other computer in a local network. The local server was running on Jamtaba under Ubuntu Studio with Behringer U-Phoria UMC-202 soundcard running under Jack (samplerate 48000, buffer 32 samples), the other computer (when I was hearing) gave the best result under Linux Mint and Reaper with ReaNINJAM and integrated soundcontroller directly under Alsa (Jack can't work with this controller) - the delay from Jamtaba to ReaNinjam was about 1/16 sec and from ReaNinjam to Jamtaba about 1/4 sec. The mode was VoiceChat.

This result has made an idea: could You add to the VoiceChat mode an option to connect WITHOUT the Vorbis compression (just PCM WAV) to decrease the delay better? This can give an opportunity to make the real repetition sessions inside one city which is very actual thing today due to Covid plague. Thanks!

**Comment by Jonathhhan** [comment]
I am not sure about it, but wouldnt PCM increase the delay because it has a higher bandwidth compared to Ogg Vorbis (of course depending on the bit rate and frequency range)?

**Comment by elieserdejesus** [comment]
> I've set the value of "EncoderQualityHigh" (vorbis.h) as 0.5f (from 0.3f)

This can be changed directly in the Preferences or in the json configuration file.


> could You add to the VoiceChat mode an option to connect WITHOUT the Vorbis compression (just PCM WAV) to decrease the delay better? 

Send uncompressed PCM data will drain people upload resources. The delay will are observing is related to TCP too. Real time audio works better/faster using UDP.

If are insterested in a system to transfer uncompressed audio I suggest Artsmesh https://www.artsmesh.com/

Unfortunally not work in windows.
