### ISSUE TITLE
midi implementation for the volume, pan and metro knobs and faders?

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#13]
Jon proposing in ninbot forum: Any chance of some midi implementation for the volume, pan and metro knobs and faders?

**Comment by elieserdejesus** [comment]
Are you interested Ezee?

**Comment by Ezeer** [comment]
ah ah ah !
It's nice to propose dear leader !
Of course i am !
Let's discuss the UI , widgets etc... and their placement first ?

**Comment by elieserdejesus** [comment]
Ezee, in the file NinjamPanel.ui you can see the current widgets (level and pan) for ninjam metronome. If I understand corrent Jon is wanting control the metronome level and pan with some midi control change. This can be very usefull for musicians using midi controllers with many configurable knobs. 

I think this feature open the possibility to something bigger, more complex, but bery insteresing: Midi learn.

I think other things in Jamtaba can be controlled by control change messages, and to be usefull this messages need be configured by users. The ugly way is put some kind of "Midi Controlls Preference Panel" and users can bind some defined controls in Jamtaba with some midi control change. Works, but is not intuitive in my opinion. 

The best way I can think is put a but a little button activating the "midi learn" feature (or activate the feature with right mouse button click). When midi learn is activated the users can rotate your midi controller knobs and the magic happens.

Imagine how funk is mix the ninjam tracks using knobs in your midi controller? Today the controllers have a lot of assignable knobs and faders, so this can be a very interesting feature.

What you think about this? Let's change the issue title to something bigger like "add midi learn in jamtaba controls"?

**Comment by Ezeer** [comment]
wow wow wow ....  ^^ slow slow slow ! lol

" Imagine how funk is mix the ninjam tracks using knobs in your midi controller? "
That will be fantastic . :100: 

And i am also a arduino user , so i can build a dedicated hardware for that !
Existing (broken and simple ) Example :
![arduino_midi](https://cloud.githubusercontent.com/assets/1283808/10712165/765d667c-7a92-11e5-8ff6-92e20364e71f.jpg)

( hey , we'll make money with that shit ? LOL )

" Let's change the issue title to something bigger like "add midi learn in jamtaba controls"? "
Do it !
^^

**Comment by elieserdejesus** [comment]
Haha, arduino is very fun.

Elieser

Em sábado, 24 de outubro de 2015, Ezee <notifications@github.com> escreveu:

**Comment by Ezeer** [comment]
well , my joystick thread made me remember of this one , and i am assigned to it !
ah ah ah ...
So i'll be working on the two sides of the moon ...
May be it is the starting point to a virtual class Elieser ?
This kind of class that can be derived to midi or joystick controler .
Sounds good , no ?

**Comment by elieserdejesus** [comment]
Yeah, sounds good. We are abstracting IO, just the input part actually. But, what kind of input? We can't name this abstract class a InputDevice, because this name conflicts with audio devices.

It's something like "NonAudioInputDriver" :)

I can't think in a good name for this abstraction, but shure it's an abstraction.

**Comment by Ezeer** [comment]
Hey , what about template classes also ?
http://www.tutorialspoint.com/cplusplus/cpp_templates.htm

**Comment by elieserdejesus** [comment]
UIController = UserInputController ?
If yes, audio is a user input too, and I can't see an abstraction for audio, midi, and joystick in the same class/interface. 

I can't see a use for templates in this case too. You have something in mind?

**Comment by Ezeer** [comment]
No , a controler is a physical object the abstract class will deal with .
You will have a template that implement controls on Jamtaba , like sliders and knobs , mute buttons etc ..
The derived classes will inherit the same functions but with a different implementation ( the way they use to communicate - midi signal or Joystick msg ) .

**Comment by Ezeer** [comment]
" audio is a user input too, and I can't see an abstraction for audio, midi, and joystick in the same class/interface. "

Audio signal is independent of the UIControler circuit .
But UIControler class send informations to the AudioEngine .
The AudioEngine deals with audio signals .

So UIControler can signal to AudioEngine " PUMP UP THE VOLUME  ".
But he never touch an audio signal , just send Actions .

**Comment by elieserdejesus** [comment]
Ezee, I like these abstractions, but I'm afraid this will be very complex to translate in a "working code" at moment. I can see a huge refactotation in this case.

About templates: I'm still blind for the C++ template application in your example. You mention an abstract class and some derived classes dealing with implementation details. We can achieve this result using a couple of pure virtual functions in base class and inheritance. So, I can't see an oportunity to templates. Can you see something to templates in this situation?

**Comment by Ezeer** [comment]
>Can you see something to templates in this situation?
Templates would use types <T> that i have exposed like specialized derived classes in the 
standard inheritance way ( with pure virtual functions , u're right  ^^ ).
<T> could also be structures designed for Midi and Joystick , used depending of the type of the controler . 
The use of templates would allow to not translate the types used by the devices , but use them 
in their natural form . 
A fader for example has a min and max value , or a range .
A Joystick axe has also that values .
A Midi value also
Can you see where templates could be used ?

But it's better to make a code exemple , i'll try that later .
( after having an idea of what your code is actually doing in that part of the program )
:)

**Comment by Ezeer** [comment]
Finally it's perhaps better to start to work with a very simple design , and work first on the midi messages being received by Jamtaba and map them to the right controls .

Thus we need to define first a way to store these assignments .
My idea : 
1_Code a onclick() or onDoubleClick() method to select the ... Control changes messages that the widget will react to .
See page 10 of that doc for details on CC : https://www.nyu.edu/classes/bello/FMT_files/9_MIDI_code.pdf

2_Add a property to the widgets that are able to deal the CC messages .
Perhaps use inheritance here .

**Comment by Ezeer** [comment]
Last minute problem i imagine is that the widgets are in Idle state the most part of the time , 
so there must be a piece of code that must listen in realtime the incoming midi CC .
And call the widgets with a funk we will write : 
(pseudo code )
>void QWidget::OnCCMidiMsg(MIDI cc) { //moove the knob }

**Comment by elieserdejesus** [comment]
Ezee, the idea is very good, I can see this working.

My suggestion is keep the Widget ID/CC pairs stored in the MainController class (maybe we need a better name for this class too).

MainController is processing the midi messages. When a midi message is detected mainController can check the widget IDs mapped to CCs and emit a signal. Something like that
```
void MainController::doAudioProcess(...){
    MidiMessage msg = ...;
    if( msg.isControlChange()){
         long widgetID = getMappedWidgetForControlChange( msg.getControlChange());
         if( widgetID >= 0){ //assuming -1 if no mapping is founded
              emit controlChangeMessageReceived( widgetID, msg.getControlChange());
         }
    }
}
```

So, this signal is catched/captured in the GUI. This is very necessary in Qt because the midi messages are handled in the audio thread, and the fader/pan changes are done in the GUI thread. In Qt, if you touch the widgets from the audio thread we have crash. Never touch GUI stuff outside the GUI thread, this is the Qt universal rule :)  When we use Qt signal/slots the threads communicate  in a  beatifull way, no problems, no crashes, etc.

So, the last step is receive the signal emited by MainController in the GUI classes (MainWindow, NinjamRoomWindow).
```
//MainWindow.h
class MainWindow{

private slots:
      void on_controlChangeReceived(long widgetID, MidiMessage msg); 
}

//MainWindow.cpp
void MainWindow::on_controlChangeReceived(long widgetID, MidiMessage msg){
      //we need some special widget
      JamtabaWidget* widget = getWidgetFromID( widgetID );
      if( widget ){
            widget.processControlChange( msg ); 
      }
}
```

**Comment by Ezeer** [comment]
**Ezee, the idea is very good, I can see this working.**
Hallelujah !

I start to miss pure c++ , but Qt really offers quick strategies with the Signal/Slot and Gui system .
So you idea is simpler than mine , but Homer is a blessed guy !

![homer](https://cloud.githubusercontent.com/assets/1283808/10945049/69e8f09a-831c-11e5-908d-37ccf8c066d4.png)
"His pants are the sky and tenderness is his food , etc ... " Lost Poetry Book .

So i naturally choose the blessed guy solution ! ( lol )
I will work for a single widget first , say the local volume fader , without using QPair .
But are you ok for using the class JTBMidiCcMsg ?
Or you prefer update MidiMessage class with getCcMsg() for example ?

**Comment by elieserdejesus** [comment]
Ezee, I never work with CCs in programming, so I'm not shure if the current MidiMessage is enough. If yes, I prefer use the MidiMessage and just add the isControlChange method, it's more simple in my opinion.

**Comment by elieserdejesus** [comment]
I think this feature will be huge, with a large impact in many parts of the code. So we need discuss some things before coding. I have some questions to discuss with you, let's think in this issues:
1 - The widget IDs used to pair Widgets and CC need be persistent. If I configure the CC 34 to control my first local input track level, close and reopen Jamtaba, I expect this configuration working. The question is: how we can manage this widgets IDs in this case? Is possible, is not a super hard problem, but we need think in some persistence model for this.

2 - The same CC can be mapped from 2 or more widgets? Or when a CC is mapped to a new widget is auto unmapped from the old widget? Make sense control 2 or more widgets using one CC? I think this no make sense, but I'm not shure.

3 - How users will do the bind/midi learn? Right button click in some widget and start learning? Maybe MainController will be a state machine with 2 states: learning mode or dispatching messages mode?
    
No more question for while :)

**Comment by Ezeer** [comment]
Well , i had the same questions than you yesterday , we will find the answers together naturally .
;)

1_ Write a new entry in the Json file for Cc assignments , use the same strategy we use already for the vst BlackBox . This time we'll code an ... orangeBox ?

2_ If your tracks have independent focus , we can use that : Each kind of widget ( volume, pan,mute,solo) is assigned the CC when parent track is focused .

3_ Just implement an action , double click sounds good if not assigned yet , or 3rd button click .
That would bring up a dialog with a listbox where you choose the CC you want .

I think we could code default assignment that the users could tweak by clicking on the widget like this.
Meanin each knob is for pan CC , slider for the volume ( exept the metronome ) etc ...

**Comment by elieserdejesus** [comment]
Ezee, about the question 1, I'm not talking about the store scheme (save in the file), we can use your idea, is good.
The problem is: how generate the widget IDs? We need generate this IDs and when we close and reopen Jamtaba, the generated IDs need be extacly the same IDs, or our binds don't work as expected.
Off course, if we store the IDs in json file we can load these exactly IDs. But, after load these IDs how rebind these IDs with the respective widgets?

I'm thinking in categorize the IDS:
1 - IDs for local input tracks
2 - IDs for metronome controls
3 - IDs for ninjam tracks

A possible solution is use triples, and not pairs. A triple is: [Category ID, Widget ID, CC]

Problems: The Widget ID is still a problem! My mind is stucked in this situation: 
1) I load the ID from json.
2 ) and now? What is the correct widget to receive this ID?

**Comment by Ezeer** [comment]
" how rebind these IDs with the respective widgets? "
well , find the parents ? So ID=controltype+ParentID ? 

CTRL_VOL_TRCK_1 //CTRL is header , vol=type , TRCK=parent , 1=index in list of parents widgets of this type

CTRL_PAN_TRCK_0 = CC code
CTRL_PAN_TRCK_2 = ...
CTRL_PAN_METRO = ...
CTRL_VOL_METRO = ...

" 2 ) and now? What is the correct widget to receive this ID? "

+ _You read the header , you know you got a control pair
+ _The second part of that worm is the type , read it in a switch( midiCctype ){...}
+ _ In the switch , you are at case=PAN, read the next part , the type
+ _ With the type , ask MainController the pointer to the widget child of this parent
+ _ You got a handle or pointer on the QWidget , assign it by our brand new : 
>JTBMidiCcControler role is to : 
_ Store the Widgets ID ( or pointers ? ) that are assigned to a Control Change Message (QPair )
_ Read incoming JTBMidiCcMsg 
_ Dispatch the Midi values to Widgets control using their ID or Pointers

**Comment by elieserdejesus** [comment]
Nice Ezee, I was thinking in a similar solution, but I stop when I start thinking how separate channels and subchannels.
In local input tracks you can create subchannels, each subchannel containing a fader, pan, etc. 
So maybe we need one more level of ID to identify the subchannel. For example, this code map the pan in track 0, subchannel 0
```
CTRL_PAN_TRCK_0_0
```

Another little issue is the ninjam tracks. Every time an user open Jamtaba we can restore the input tracks state, including the CC mapping. This works because the input tracks setup is persisted and reload when jamtaba is opened. 
But in ninjam tracks things are not too easy to map. Suppose a crazy user map a CC to every ninjam track in a jam, playing with 5 musicians. Now this users exit the jam, and enter another jam. We keep the CC mapping used in the last jam or the map is "per jam"?
I think a "per jam" mapping make sense.

Another little question :)
Widgets will receive CCs only when are focused or every time? I'm thinking in control my input level using some knob in my midi controller. If I'm chatting the focus is in chat text field. So I can't change my input level using the midi controller knob because the input track fader is not focused. In this case I think we need handle CCs every time, focused or not. But I'm afraid this can cause some problems.

But it's just a little detail, we can work in this in the last steps of this nice feature.

So, let's start coding? :)

**Comment by Ezeer** [comment]
" So, let's start coding? :) "
Cool ! But your questions are very good questions , especially the little eh eh .

So if we followed the previous strategy , each widget "Cc Able " is uniquely mapped to a Cc  message.
Thus we no more need in effect to have the focus because one physical slider = one virtual slider ( widget )

**But I'm afraid this can cause some problems.**
To filter and dispatch in real time CCmessages ?
For the time's cost of these operations ?
In the wirst case , we could use a thread to run in a different processor if any present in the user's system ? ( lol )
more about that idea : http://programmers.stackexchange.com/questions/181157/how-to-program-thread-allocation-on-multicore-processors

**Comment by Ezeer** [comment]
Hey ... focused is just a state ...must be easy to store by us...that introduce a console states manager now , that could store the sessions setup ( tracks, all widgets values , Cc assignements )
But that may be an other topic ( if i use 'thread' that could be misleading .. )
^^
First step to automation ?

**Comment by Ezeer** [comment]
For performances reasons with Midi : 

>MIDI RUNNING STATUS While reading bytes coming from a MIDI message, you must know that the STATUS byte can in fact be omitted (except in the first message of that type).
In such a case, you can receive a message that only has DATA bytes. The STATUS byte is then supposed to be the same as the last STATUS byte received.

>This is called MIDI RUNNING STATUS. It is useful for instance to optimize transmission when a long series of the same messages are sent. An example would be a pitch bend or crescendo volume curve.

>You can also use this MIDI RUNNING STATUS when you generate MIDI messages, but you should care about how the target synthesizer or software will receive it, to be sure it is well interpreted.

Source : https://www.cs.cmu.edu/~music/cmsip/readings/MIDI%20tutorial%20for%20programmers.html

**Comment by elieserdejesus** [comment]
Ezee, the thread is not necessary. Actually the midi messages are filtered in the audio thread (a high priority thread created by port audio). We will emit messages for received CCs. This messages will be handled in Qt main thread, the GUI thread. So the solution is naturally multi thread.

**Comment by Ezeer** [comment]
wow , you got it boss !
^^

**Comment by elieserdejesus** [comment]
Ezee, this feature will affect many pieces of the code. So I propose work in a new public branch. I think is not a good idea work in a big feature like this directly in master.

**Comment by Ezeer** [comment]
I was thinking EXACTLY the same .
:tada:

**Comment by elieserdejesus** [comment]
I create a branch called midiMap

**Comment by elieserdejesus** [comment]
are you in twiter?

**Comment by Ezeer** [comment]
@jonjamcam  So we had a cool chat session with twitter ( even if elie experienced connection problems ) , and have worked ( more elie than me mwah ah ah ! ) into grabbing Control changes midi codes .
Elieser is inspired , that will rock !
;)

**Comment by jonjamcam** [comment]
Good! Can't wait to test it!

**Comment by elieserdejesus** [comment]
@Ezeer ! I push a new code in the midiMap branch. It's working :)  Very fun man, I rotate the knob in my midi controller and the first input fader is moving, like magic :) This is very fun.

Ezee, I see you add some methods in the MidiMessage class, but when I pull your code I have a merge conflict here.
 I fix the conflicts but your methods added in MidiMessage class are not in the last commit. So we need be very carefull in these commits to avoid loose code. Your commit is in the history, so is easy copy paste in this case. The only problem is the changes in MidiMessage class, I hope.

**Comment by jonjamcam** [comment]
I guess we'll need to add it to the manual too...

![automatation snap](https://cloud.githubusercontent.com/assets/15310433/10969432/139962d4-83a7-11e5-8819-7cf461702447.jpg)

**Comment by Ezeer** [comment]
@jonjamcam  Prepare some room Jon ! Another chapter in our adventures need to be written !
Tadaaaa Tadaaa ! ah ah ah ...
http://rutube.ru/video/115a75112561f0a9b3b4290fb7f74f20/

@elieserdejesus  Good job ! I don't know where the problem came from as i followed : 
git add .
git commit -m"message"
git push
No problem for my funks , they were to test the push mainly , so ...

**Comment by jonjamcam** [comment]
adventures!

https://www.youtube.com/watch?v=hp5epzMM3QM

**Comment by elieserdejesus** [comment]
I not understand the last problem too Ezee, but I'm reading this: [http://stevebennett.me/2012/02/24/10-things-i-hate-about-git/](http://stevebennett.me/2012/02/24/10-things-i-hate-about-git/)

**Comment by Ezeer** [comment]
**"9. Git history is a bunch of lies "**
Ah ah ah Aaaaaarrrgh ....
:)

**Comment by Ezeer** [comment]
@elieserdejesus  To avoid make spaghettis like in the past , it is perhaps better that i work in parallel
with the Joystick controler branch ? That way i can experiment ideas that i have and use the code
you wrote in the MidiMap branch ? ( model<->view Signal<->Slot )
And perhaps you'll find some ideas good for you also in the joystick controler stuff .

**Comment by elieserdejesus** [comment]
Ezee, keep working in the joystick branch, I will keep distance from this branch :)
I was reading about merge various branches in git. The merging conflicts are common. I'm using [Meld](http://meldmerge.org/) to solve the conflicts. 

I will be very carefull in next mergings to avoid loose our work.

**Comment by Ezeer** [comment]
**" Ezee, keep working in the joystick branch, I will keep distance from this branch :) "**
It's the same tree anyway !
:+1:

**Comment by Ezeer** [comment]
Perhaps i forgot to pull from my local branch before add commit and push .
I remember that i've done a merge before the first push , then i forgot for the 2 last .
That is probably the problem we had ?

**Comment by elieserdejesus** [comment]
Yeah, I think this is the problem.
Always run a pull command before create a new branch, so the branch is created from a updated tree.

**Comment by Ezeer** [comment]
Hem ... no i made the pull to get the Joystick branch if that is what you are talking about .
I was talking about the last push you made late night , i'm not sure i updated my local midi branch
with pull ,
before using add . , commit and push .
That could explain the problem because when i have used merge after that  , perhaps i was not uptodate with the distant branch.
I should have verified that , but i was too tired ...
You see ?

**Comment by elieserdejesus** [comment]
Understand Ezee. I see your last commit with joystick branch and see my last changes in the MidiMessage class. So now we are in sync, I hope :)

**Comment by Ezeer** [comment]
Well , you do better than hope , you make it come real .
Your help is very effective , if you recruit other programers it could be a good idea to have
a brainstorming like we had . Because there is always sunshine after the clouds ...
https://www.youtube.com/watch?v=xzGV9Bl6CGg

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
