### ISSUE TITLE
FIX : User can enter a room with a space as nickname

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#130]
I was trying to reproduce the doublebass bug with rooms , and i noticed that if i type a space then press
enter , i am logged .
That is not good because a bad user could enter a jam anonymously to do bad things ...
Perhaps we should filter the username nickname with minimum , maximum characters and don't allow space at first place in the string ?

**Comment by jonjamcam** [comment]
In ninjam and reaninjam entering a blank username makes you appear as "anon" in the rooms. BTW a bad user can call himself anything and do bad things too....

**Comment by Ezeer** [comment]
Hi Jon . 
Yeah , i was thinking that too , and i am not sure it is possible to prevent that .
Probably it is a problem that concern the servers ( they got the ip ) and their rules , not Jamtaba that
is a client .

But now that i think of it , we got also the ip and elieser is the admin of Jamtaba server .
So it could be possible to not allow connections in case of complaints , for example .
Well , that is not an idea that i like anyway , the repressive way .
Education is better , meanwhile some say : 
https://www.youtube.com/watch?v=m55RDNlWnLI
;)

**Comment by elieserdejesus** [comment]
I agree Ezee, blanck name is not good. In ninjam the server will change a blank name to "anon", but I preffer disable this possibility in jamtaba. I think anon users need be discouraged. You can type anything  as nickname (including "anon") if you really want play as anonnymous.

About avoid bad users: I hope  never have to worry about it :)

**Comment by elieserdejesus** [comment]
Fixed!

**Comment by Ezeer** [comment]
cool , thx !
