### ISSUE TITLE
New Translation Italian, need developers to do release tasks.

### ISSUE THREAD

**Issue by Flightofbird** [elieserdejesus/JamTaba#1302]
I have translated the .ts file but now I need a developer to do release tasks.
Also I need access to create a branch and upload the file.

**Comment by elieserdejesus** [comment]
Hi @Flightofbird , you must create a **Fork** of JamTaba repository in your github. After create your fork you can create a new branch (in your fork) and commit + push in your branch.  
The last step is create a **Pull Request** here in this repository, so I can merge your contribution.

Github has 2 contribution models:
1 - Developers acessing the repository directly
2 - Pull request model

We are using the pull request model.

**Comment by Flightofbird** [comment]
Thanks for the help! I've Forked it, made the branch and created the Pull Request
