### ISSUE TITLE
Jamtaba not starting

### ISSUE THREAD

**Issue by camardelli** [elieserdejesus/JamTaba#1308]
My Jamtaba is not opening (Loading rooms list......)
Using MacOS High Sierra Version 10.13.6

**Comment by elieserdejesus** [comment]
AU plugin or Standalone?

**Comment by camardelli** [comment]
Standalone

Em seg, 11 de mai de 2020 às 18:43, Elieser Ademir de Jesus <
notifications@github.com> escreveu:

**Comment by elieserdejesus** [comment]
was working before?

**Comment by camardelli** [comment]
Sim, tenho usado bastante.
Usei ontem, naobatualizei nada no mac nem rebootei e hj fica em “abrindo
salas..”
Matei todos os processos pendentes e nada.
Reiniciei o Note e tb não funcionou.

Em seg, 11 de mai de 2020 às 18:51, Elieser Ademir de Jesus <
notifications@github.com> escreveu:

**Comment by camardelli** [comment]
Instalei em outra máquina com Windows 10, na mesma rede, demorou bastante
carregando as salas mas entrou.
Normalmente carrega de imediato.
No Mac nada ainda.
Testei Wi-Fi e está tranquilo (130Mbps up e down)

Em seg, 11 de mai de 2020 às 18:53, Alberto Camardelli <
camardelli.alberto@gmail.com> escreveu:

**Comment by camardelli** [comment]
Instalei a anti penúltima versão e dá o mesmo erro.
Desculpe encher o saco, tentando agregar no troubleshooting

Em seg, 11 de mai de 2020 às 19:12, Alberto Camardelli <
camardelli.alberto@gmail.com> escreveu:

**Comment by elieserdejesus** [comment]
Sem problemas, não está enchendo o saco não 😄 

Aqui está funcionando normalmente.

Você consegue habilitar um log detalhado alterando o arquivo logging.ini que está em 
C:/User/seu usuário/AppData/Roaming/JamTaba2

No Mac acho que está em **Application Support/JamTaba**

**Comment by camardelli** [comment]
nao localizei o log.
Ativei o logo do SO e retornou as seguintes msgs:
--------------------------------------------------
padrão	22:55:31.448149 -0300	launchservicesd	CHECKIN:0x0-0xa70a7 6374 teste.Jamtaba2
padrão	22:55:31.686063 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.732868 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.757057 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.801185 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.803042 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.804732 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.806710 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.817554 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.829535 -0300	Jamtaba2	Trust evaluate failure: [leaf TemporalValidity]
padrão	22:55:31.912610 -0300	Jamtaba2	123: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
padrão	22:55:31.920562 -0300	Jamtaba2	AudioHardware.cpp:3585:AudioDeviceAddPropertyListener:  AudioDeviceAddPropertyListener: listener was already added
padrão	22:55:31.924235 -0300	Jamtaba2	AudioHardware.cpp:3585:AudioDeviceAddPropertyListener:  AudioDeviceAddPropertyListener: listener was already added
padrão	22:55:31.928726 -0300	powerd	Process Jamtaba2.6374 Created NoDisplaySleepAssertion "JamTaba blocking screensaver" age:00:00:00  id:21474870516 [System: PrevIdle PrevDisp DeclUser kDisp]
erro	22:55:32.854403 -0300	Jamtaba2	nw_path_close_fd Failed to close guarded necp fd 23 [9: Bad file descriptor]
erro	22:55:32.857502 -0300	Jamtaba2	nw_path_close_fd Failed to close guarded necp fd 23 [9: Bad file descriptor]
erro	22:55:33.003080 -0300	Jamtaba2	nw_path_close_fd Failed to close guarded necp fd 23 [9: Bad file descriptor]
padrão	22:55:41.463241 -0300	Jamtaba2	LSExceptions shared instance invalidated for timeout.

**Comment by elieserdejesus** [comment]
> Jamtaba2 Trust evaluate failure

Será que não é aquele esquema do Mac de não confiar em aplicativos quem não vieram da App Store?

**Comment by camardelli** [comment]
pode ser, mas depois de mais de 1 mês de uso?
e entre funcionar e parar não reiniciei o Note nem fiz logoff..
achei que pudesse ser um problema de timeout na origem do serviço mas se esta funcionando normal vou gastar um tempo pra tentar achar algo que me de uma pista melhor!
Valeu o apoio, se achar mais alguma pista posto por aqui!
Tks

**Comment by camardelli** [comment]
SOLVED - aparentemente o app teve algum arquivo corrompido e apesar de ter removido e reinstalado mais de uma vez só voltou a funcionar depois que deletei (ou renomeei) todos os arquivos do Jamtaba via "Terminal" em todos os Diretórios e refiz a instalação do zero.
Obrigado pela atenção e parabéns pelo Jamtaba!

**Comment by elieserdejesus** [comment]
Caramba, que solução hardcore. Não tenho ideia do que pode estar acontecendo @camardelli , talvez seja o que vc falou mesmo, algum arquivo corrompido.
