### ISSUE TITLE
Allow the JSON file to hold new bot names ?

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#131]
I saw that the bot list is hardcoded : 
>QStringList Service::buildBotNamesList(){
    QStringList names;
    names.append("Jambot");
    names.append("ninjamer.com");
    names.append("ninbot");
    names.append("ninbot.com");
    names.append("MUTANTLAB");
    names.append("mutantlab.com");
    names.append("LiveStream");
    names.append("localhost");
    return names;
}

That mean in case of new server's bots releases , Jamtaba would be recompiled to update the list .
I think it's good to hard code that list , but very good to use Settings to add eventual new bots
in the list . 
We would just update the JSON file in ressources and Jamtaba would update itself at launch .

**Comment by elieserdejesus** [comment]
In general I don't like the hard coded things too, but in this case I think we have few options.
About put the bots in JSON: I see just one problem in this approach: users can change the json and delete the bots. Jamtaba will work, but now the bots are displayed in the rooms as "real players".

New servers are very rare in ninjam, and I see nome bot name changes in this years, but is very rare too. 
May be we can use a external hidden file "bots.txt". Off course if users can see this file they can edit, but using a hidden file we restrict this editions to advanced users.

**Comment by Ezeer** [comment]
**New servers are very rare in ninjam, and I see nome bot name changes in this years, but is very rare too. **
Yes , i think so .
In fact , i had the idea so i posted it to don't forget ...
*.txt is a good option , or even *.bot , Qt can read it .
Wait , i push that on your favorite milestone .
^^

**Comment by elieserdejesus** [comment]
Ah, I loose the tag "question" completely, I'm always reading the github stuff as "issues", I'm always in the "issues" mode. Needing a little update in my brain state machine :)
