### ISSUE TITLE
Huge delay between clients

### ISSUE THREAD

**Issue by stony245** [elieserdejesus/JamTaba#1311]
I have setup a ninjam server for my band on a remote host at my hosting provider.. 
When I connect with my Linux Clients (they all have a lowlatency kernel btw.) they are able to connect.
However sound between the those clients is severely delayed. The longer they are connected, the longer the delay takes. After some minutes the delay about 20 seconds. After 15 minutes, the delay is about some minutes.
So something very strange is going on here.
I also have the same delay when I start a Ninjam server out of Jamtaba on the remote host. 

The same applies when I start a local Ninjam server out of Jamtaba in the local network.

What is gong wrong here?

**Comment by elieserdejesus** [comment]
> I also have the same delay when I start a Ninjam server out of Jamtaba on the remote host.

> The same applies when I start a local Ninjam server out of Jamtaba in the local network.

Based in your informations I think this is not a JamTaba issue.

> What is gong wrong here?
Check your remote host bandwith. Maybe you have somehting reducing the host bandwith and the ninjam data transmission is delayed.

**Comment by stony245** [comment]
We have a Jamulus Server (for the same purpose) on the same host and I have overall latencies of 25 msec (ping time is 6 msec to Server). 
But our Band needs a metronome and some other features, that's why we are looking for a better solution here. But here we have delays in the order of seconds up to minutes.
I am an IT person with strong Linux skills, and I haven't seen something like this. I cannot imagine,  that the network in between is buffering for so long.
I will try to setup 2 systems without lowlatency kernel, maybe we have an issue here.

**Comment by elieserdejesus** [comment]
> We have a Jamulus Server (for the same purpose)

@stony245 , JamTaba and Jamulus are not for the same purpose. JamTaba is not realtime. Sorry if this info is redundant for you, but I`m seeing many people trying to use JamTaba as a realtime jam software without understanding the ninjam intervalic concept. 

If this is not your case (if you inderstand the intervalic concept) just ignore my comment.

**Comment by stony245** [comment]
I tested without low latence kernel, same result with lots of delay.

Anyone has managed to run this on linux without delay?

**Comment by stony245** [comment]
Ok, just read, that this is not for realtime. Thank you for your response.

**Comment by elieserdejesus** [comment]
> Ok, just read, that this is not for realtime. Thank you for your response.

No problem @stony245 . You know JamKazam? It's for real time.

**Comment by stony245** [comment]
Thanks. I know it,but it's not available as Linux client, plus I want to host my own server.
