### ISSUE TITLE
Serious latency issues (new user)

### ISSUE THREAD

**Issue by CarryLikeMariah** [elieserdejesus/JamTaba#1313]
Hello. My musician friends and I have since lockdown,  began investigating products or software that essentially attempts to do what Jamtamba does. We have tried a few and none of them seemed really suitable for what we are trying to achieve.

This app really does seem like the best for numerous reasons, but I have at least one issue we cannot seem to address.

The real issue we all experience is after we join a room. The lag before what we play being broadcast through the room is about 40 seconds. Playing through Jamtamba with my vst sound practically latency free. Extremely responsive. Perfect, even. 

We tried switching hosts with exactly the same outcome. We all have good internet connections. All of us have different interfaces and instruments and experienced the exact same issue. I assume there is a simple fix here, but we are all so new to this we don't know where to begin.

Any help would be appreciated. I really want to use this app!

Thanks for reading all that <3

**Comment by elieserdejesus** [comment]
Hi @CarryLikeMariah , I suspect you are trying to use JamTaba to real time jam sessions. 

JamTaba **is not real time**, to use JamTaba you must search for **ninjam** and learn about the **ninjam interval** concept. In general words, it's something like "musically controlled latency".

To play in real time try JamKazam or Jamulus.

**Comment by CarryLikeMariah** [comment]
This makes a LOT of sense. 

Thank you! I'll check out that interval concept first. Cheers.
