### ISSUE TITLE
valori minimi e massimi per BPI e BPM

### ISSUE THREAD

**Issue by mk030166** [elieserdejesus/JamTaba#1314]
Vorrei sapere all'interno di un server privato creato con JAMTABA quali valori minimi e massimi posso impostare per BPM e BPI.
Grazie.

**Comment by jonjamcam** [comment]
2<BPI<192
40<BPM<400

**Comment by mk030166** [comment]
OK thanks, but why these parameters don't work in every room? If I !vote... the metronome does not change as I would. 
Another question: the min/max parameters in ninjam server (in the cockos site) seems to be:
2 <BPI <1024
20 <BPM <400
Do you confirm? If I make a private ninjam server with these parameters, in JamTaba2 could I get the same?
Last question: is it possible hear the loop just in local without trasmitting it?

Thank you for the answer.
Best regards
Marco

**Comment by jonjamcam** [comment]
Public servers have a BPI limit of 64. This limit is set by each server admin, not by Jamtaba.
jamtaba private server hosting does not have any limit.

is it possible hear the loop just in local without trasmitting it?

yes. Just click the Transmit button so it turns red. This way all audio is local only.

**Comment by mk030166** [comment]
Thank you for your quick answer.
Perhaps I did not express myself well on the looper's speech. I would like to transmit the audio that I am generating with my instrument but at the same time listen to the looper layer only locally. In a nutshell I would like others to hear only what I am playing while I would like to hear both the instrument and the looper. Is it possible? Maybe you need to add a button in the looper to disable the transmission, a kind of MUTE.
Thanks.
Marco

**Comment by mk030166** [comment]
Hi. I confirm that I made my private server directly with NINJAM SERVER and it is not possible to go below 40 BPM and above 64 BPI. Why? It would be a very interesting and important thing for me. Thanks

**Comment by mk030166** [comment]
Please....

**Comment by elieserdejesus** [comment]
> I would like to transmit the audio that I am generating with my instrument but at the same time listen to the looper layer only locally

@mk030166 , this is a very, very, very , very specific and personal usage of the tool. Make no sense ask us to add more buttons in the UI just because one person (you) have very specific needs to this button.  If you can share an argument (a good one) about "How everybody can use this new button and improve your jams" we are listen.  For very specific usage you must get the JamTaba code here, change, recompile and get your own version of the tool.

**Comment by elieserdejesus** [comment]
> Hi. I confirm that I made my private server directly with NINJAM SERVER and it is not possible to go below 40 BPM and above 64 BPI. Why? It would be a very interesting and important thing for me. Thanks

Again, you are arguing about **how this is important for you**. I'm more interested in **how this is important for the others?**.
