### ISSUE TITLE
Split Transmit for each Channel ?

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#132]
can you split Transmit for each Channel ))) so i can send something and test inbehind on other channel ) thy elieser cool work greets Mag

**Comment by Ezeer** [comment]
hit ... hat ... hit ... hit ... Splash !!
Hello Magnus !
That is an interesting idea , i think it is possible yeah .
I 'll look at it today , but elieser will decide if he likes the idea or not .
THX

**Comment by Ezeer** [comment]
k, i had a look to the code , the main transmit funk is here (line 641 ):  
>void MainController::setTransmitingStatus(bool transmiting){
    if(this->transmiting != transmiting){
        this->transmiting = transmiting;
        if(isPlayingInNinjamRoom()){
            ninjamController->setTransmitStatus(transmiting);
        }
    }
}

( that's just my dev note here so you can see the WIP , i'll edit time to time , it's pre-prod time ^^ )

**Comment by jonjamcam** [comment]
That is a good idea.

**Comment by elieserdejesus** [comment]
Goo idea, I think many users want this feature.
Ezee, let me know if you have some complications on the code. I don't remember if this part of the code is clean.

**Comment by Ezeer** [comment]
so i take it ? cool !
**Ezee, let me know if you have some complications on the code. I don't remember if this part of the code is clean.**
a'right !

**Comment by MagnusDrumsTrumpet** [comment]
yesssss cool thy)

**Comment by Ezeer** [comment]
i have find the action on transmit button , i will use that with separate buttons i guess : 
//++++++++++++=
void MainWindow::on_xmitButtonClicked(bool checked){
    **foreach** (LocalTrackGroupView* localChannel, localChannels) {
       **localChannel->setUnlightStatus(!checked);**
    }
    mainController->setTransmitingStatus(checked);

**Comment by Ezeer** [comment]
And here the place where to add a transmit button per track : 

    LocalTrackGroupView *MainWindow::addLocalChannel(int channelGroupIndex, QString       channelName, bool createFirstSubchannel){
    LocalTrackGroupView* localChannel = new LocalTrackGroupView(channelGroupIndex, this);
    QObject::connect(localChannel, SIGNAL(nameChanged()), this, SLOT(on_channelNameChanged()));
    QObject::connect(localChannel, SIGNAL(trackAdded()), this, SLOT(on_localTrackAdded()));
    QObject::connect(localChannel, SIGNAL(trackRemoved()), this, SLOT(on_localTrackRemoved()));
     //TODO ADD A XMIT SIGNAL HERE

    localChannels.append( localChannel );
    localChannel->setGroupName(channelName);
    ui.localTracksLayout->addWidget(localChannel); **<---from here we can add a button , right ?**

    if(createFirstSubchannel){
        LocalTrackView* localTrackView = new LocalTrackView(this->mainController, channelGroupIndex);
        localChannel->addTrackView( localTrackView );

        if(localChannels.size() > 1){
            if(!mainController->isRunningAsVstPlugin()){
                //in standalone the second channel is always initialized as noInput
                localTrackView->setToNoInput();
            }
        }
        else{
            localTrackView->refreshInputSelectionName();
        }
    }
    localChannel->setUnlightStatus(!ui.xmitButton->isChecked()); <-- reuse that later to filter transmit off is master track is off
    if(!fullViewMode && localChannels.count() > 1){
        foreach (LocalTrackGroupView* trackGroup, localChannels) {
            trackGroup->setToNarrow();
        }
    }

    return localChannel;
}

**Comment by elieserdejesus** [comment]
Ezee, at moment the xmit button is added outside local input channels, because we have one xmit button to all channels. To have one xmit button per channel you need change the LocalTrackGroupView code. Every LocalTrackGroupView instance will contain a xmit button.

The class LocalTrackGroupView inherits from TrackGroupView, and you need add the button in the base class layout. This layout is protected in base class, so you can access this layour directly in LocalTrackGroupView construtor:
```
//inside LocalTrackGroupView constructor you need something like this:
this->ui->verticalLayout->addWidget( new QPushButton( "channel xmit button here" ) );

some cool trick with signal slots here
```

**Comment by Ezeer** [comment]
nice , thanks !

**Comment by Ezeer** [comment]
So i started to code , but the slot connections don't work ( buttons states don't change , only the original works ) .

    LocalTrackGroupView::LocalTrackGroupView(int index, MainWindow *mainFrame)
    :index(index), mainFrame(mainFrame), peakMeterOnly(false)
    {
    toolButton = new QPushButton();
    toolButton->setObjectName("toolButton");
    toolButton->setText("");
    toolButton->setToolTip("Add or remove channels...");
    this->ui->topPanel->layout()->addWidget(toolButton);
//MY CODE BELOW
    xmitButtonx = new QPushButton();
    QString indexTxt(index);
    xmitButtonx->setObjectName("xmitButton");
    xmitButtonx->setText("Transmit");
    xmitButtonx->setToolTip("Transmit to others...");
    this->ui->verticalLayout->addWidget( xmitButtonx );
   
    QObject::connect(toolButton, SIGNAL(clicked()), this, SLOT(on_toolButtonClicked()));
 //MY CODE AGAIN BELOW  
 QObject::connect(xmitButtonx,SIGNAL(toggled(bool)), mainFrame, SLOT(on_xmitButtonClicked(bool)));

    QObject::connect(this->ui->groupNameField, SIGNAL(editingFinished()), this, SIGNAL(nameChanged()) );
}

Result : ( of course the big transmit button will be deleted later ..)

![xmit](https://cloud.githubusercontent.com/assets/1283808/11207912/5da75596-8d18-11e5-8910-c9f8447ae594.jpg)

We want also individual xmit per sub i guess ?

**Comment by elieserdejesus** [comment]
Ezee, I can't understand why you paste the code
```
QObject::connect(this->ui->groupNameField, SIGNAL(editingFinished()), this, SIGNAL(nameChanged()) );
```
This signal is related with the channel name edition, it's not related with xmit.


I can't see any problem in your signal/slot code related to xmit buttons. To help in this issue I need see the code in my IDE, so I can inspect the details. 
But a common problem is wrong connections between signal/slots. Check your console, look for some Qt message warning about null receivers, or other crazy stuff related with signal/slot. 

I think is better (and easy at moment) keep the xmit button per channel, and not per subchannel. Subchannels are a Jamtaba only concept, ninjam servers are receiving just "a channel", not separated subchannels. Let's start using xmit per channel, if we see is not complex use xmit per subchannel we can improve this in future.

**Comment by Ezeer** [comment]
**Let's start using xmit per channel, if we see is not complex use xmit per subchannel we can improve this in future.**
ok

**Ezee, I can't understand why you paste the code**
because it's part of the original code  , nothing particular , exempt the scrollbar here that is misleading
for you i guess ^^ , wait i fix ....

**Comment by Ezeer** [comment]
@elieserdejesus  i have problem to use Qt here , i don't understand how to change the color of the xmit
button for example . I can't find where the funk is , and there is probably a css work on that .
Perhaps you should take that job as you better know Qt and obviously your code here ...

**Comment by elieserdejesus** [comment]
Shure Ezee, I will take this issue.

**Comment by Ezeer** [comment]
Thanks , i would be too long for trivial tasks with Qt here .
I am working with Presets today .
^^

**Comment by elieserdejesus** [comment]
done!

**Comment by Ezeer** [comment]
ah ah ah ... seems so easy .
good job
