### ISSUE TITLE
Precompiled Linux: hb_font_funcs_set_font_h_extents_func

### ISSUE THREAD

**Issue by josx** [elieserdejesus/JamTaba#1326]
It seems that func **_hb_font_funcs_set_font_h_extents_func_** symbol is not present locally.

BTW I have **Harfbuzz 1.0.1** installed and I am using **Ubuntu 16.04** at this time.

**Comment by arnaudlecam** [comment]
Hi @josx ,
hb_font_funcs_set_font_h_extents_func is not implemented on Harfbuzz 1.0.1 (provided by harfbuzz package in Ubuntu 16.04). To have it implemented, you need an upgrade to Ubuntu 18.04 LTS (providing Harfbuzz 1.7.2).

**Comment by josx** [comment]
ok thanks a lot
