### ISSUE TITLE
remove troll icon

### ISSUE THREAD

**Issue by jbaylies** [elieserdejesus/JamTaba#1327]
I bet you $3.50 that the troll icon that's selectable for tracks is partly what inspired the noise trolls that people are complaining about on the ninbot forums.

**Comment by elieserdejesus** [comment]
@jbaylies , the troll related problems are not something new in ninjam community.  The trolls are trolling before the icon. Actually, the icon was added just to mark and remember some users as trolls.

What you think about @jonjamcam ? @soulraymusic ? @arnaudlecam ?


> I bet you $3.50

At moment in Brazil I can buy a car with this money 😄

**Comment by jonjamcam** [comment]
Well...I launch Jamtaba.....not in a mood to play really......mmmmmm......hey! There's a troll icon....yay! Now it's fun times....!!!!

 Really???

The harpoon issue was triggered by his lack of selfcontrol, but I'm sure he's on the right track now. I witnessed his frustration with the destruction of a fragile ecosystem before he became mr. Hide.

Trolls are dangerous people, so you have a tool now that could be of some use in ninjamwindow., But I agree that there's no point of using it in localtracks.

@jbaylies there's been years of pain for some of us. Take a tour if you want here https://github.com/elieserdejesus/JamTaba/issues/1004 or here https://github.com/elieserdejesus/JamTaba/issues/306 . Ninbot is a Bible too with that regards. So for me, more is always better. My 3.50 cents :D

**Comment by jbaylies** [comment]
> Well...I launch Jamtaba.....not in a mood to play really......mmmmmm......hey! There's a troll icon....yay! Now it's fun times....!!!!
> 
> Really???

I'll admit this got a laugh out of me! I wasn't aware of the history and thought this was a recent thing.
