### ISSUE TITLE
can I transmit my sound without hearing it come out of JamTaba?

### ISSUE THREAD

**Issue by jbaylies** [elieserdejesus/JamTaba#1328]
Can I send my sound into JamTaba and only hear everyone else's sound come out? I'm monitoring my sound elsewhere and don't want it doubled.

**Comment by jonjamcam** [comment]
Yes. Local mute button only works for local audio. To send the audio there's a transmit button completely independent.

**Comment by jbaylies** [comment]
Thank you Jon!
