### ISSUE TITLE
Empty input/output comboboxes in Mac Standalone

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1329]
@soulraymusic , today I see your input and output are empty in audio preferences. You are using Duet as audio interface, but the input and output channels are empty.

I think this is a bug in Mac only, maybe in Linux too. Can you confirm?

**Comment by soulraymusic** [comment]
Hi Elieser,

Yes it has been empty for a while. Also loading saved Loop is also not
working properly.

[image: Screen Shot 2020-05-26 at 11.30.07 AM.png]

Ray

**Comment by elieserdejesus** [comment]
@soulraymusic , I builded a quick beta here just to see if this issue is fixed. Working fine now in my  side.

Please test this beta when you have some time https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.15-beta

**Comment by soulraymusic** [comment]
Hi Elieser,

It is still not showing the input and output device. Can you share your PC
screenshot that has correct window? So I can see what is normal?

Ray

[image: Screen Shot 2020-05-26 at 12.24.35 PM.png]

**Comment by elieserdejesus** [comment]
@soulraymusic , I see some devices are returning empty channel names. I`m using a workaround and showing generics names like In 1, Out1, In 2 Out 2, etc.

Can you test this new beta and check if the channel names are ok now?https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.15-beta

**Comment by soulraymusic** [comment]
Works!

[image: Screen Shot 2020-05-28 at 5.07.12 PM.png]

**Comment by elieserdejesus** [comment]
Nice, thank you! 

Fixed in https://github.com/elieserdejesus/JamTaba/commit/86d36608f0fc36f01a9957bb698959f224105174
