### ISSUE TITLE
Cant find the actual running BPM ( in vst under reaper )

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#133]
Hey ) i still cant find the actual running BPM maybe i dont see it in vst under reaper )

**Comment by jonjamcam** [comment]
Hi magnus.....the current bpm updates in the BPM window automatically.

**Comment by elieserdejesus** [comment]
![image](https://cloud.githubusercontent.com/assets/1012741/11259672/b9e7c6d2-8e4a-11e5-9739-f32097c16a9a.png)
