### ISSUE TITLE
Loading saved Loop not working properly

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1330]
@soulraymusic , can you add more detail about this issue?

**Comment by soulraymusic** [comment]
Yes,

So basically, The sections are empty even though the system is connected to
a USB interface.

The input section on the individual channel itself works fine. So we have
been assigning the USB input from the channel not in the audio preference
box.

Ray

**Comment by elieserdejesus** [comment]
@soulraymusic , this is another issue, I created a separated issue to discuss the "Loop not loading issue".

**Comment by camardelli** [comment]
Hi,
I'm having a problem to load a loop.
Mac OS High Sierra 10.13.6
Save loop works Ok, but the app closes completely when I try to load it.
Looking for old errors fixed here, I set my Audio Preferences to 48000, saved a loop, check the operating system to see if the file was 48000 (all checked), but the problem persists.

**Comment by soulraymusic** [comment]
The same issue detected. Mine does not shut off but failes to load. Saving is ok. My friend's loop shut off the program when loading it. High Sierra 10.13.6

**Comment by elieserdejesus** [comment]
fixed in https://github.com/elieserdejesus/JamTaba/commit/5f24092cfff46c365c5267c23229aa7eb1697250

**Comment by camardelli** [comment]
tested on Macbook Pro late 2011 High Sierra, working Fine (2.1.15 Beta 2)!
Thanks!
