### ISSUE TITLE
add saxophone icon

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1331]

**Comment by jonjamcam** [comment]
could it be:

![clipart2055814](https://user-images.githubusercontent.com/15310433/83957936-35a81980-a83a-11ea-81b6-03df6b092157.png)

I think there are some others important misses like flute and trombone.

**Comment by elieserdejesus** [comment]
> I think there are some others important misses like flute and trombone.

Exactly @jonjamcam . Can you add flute and trombone too, please?

**Comment by jonjamcam** [comment]
@elieserdejesus done in https://github.com/elieserdejesus/JamTaba/pull/1338
