### ISSUE TITLE
Lots of static/noise heard on MacBook due to very small buffer size

### ISSUE THREAD

**Issue by FrenchLobster** [elieserdejesus/JamTaba#1332]
This issue did not occur initially, but after a few days of using JamTaba on this computer.
Audio output has deteriorated with lots of static (see audio sample below), when listening to or joining any session.
Rebooting the mac + reinstalling a new copy of JamTaba (and its audio plugin)  didn't not resolve the issue.
- issue occurs even with no input device is connected or selected - just listening to any active channel inside the app exhibits the problem.
- issue is NOT happening with other music apps on the same computer - iTunes, YouTube, GarageBand all sound just fine.
- Issue is NOT happening running the same version of JamTaba on another laptop (2015 macbook pro)
Attaching audio output samples (captured with my phone)
[JamTaba-2.1.14-sound-samples.zip](https://github.com/elieserdejesus/JamTaba/files/4709446/JamTaba-2.1.14-sound-samples.zip)

Config:
2015 MacBook 12", 8Gb RAM, SSD.
MacOS 10.14.6
JamTaba 2.1.14

**Comment by elieserdejesus** [comment]
@FrenchLobster , I will assume **you are using the Standalone** version, not the AU plugin version.

What is the value of your **buffer size** in your **JamTaba Audio Preferences**?

These audio gliches can be the result of a **too small buffer** size value. Try **256** for buffer size and check if the audio glitches are solved.

**Comment by FrenchLobster** [comment]
@elieserdejesus ,
Yes, standalone 64-bit OSX build.
The buffer values listed in the dropdown list are "14, 28, 56, 112, 224, 448, 896, 1792, and 3584"  (unconventional numbers, intended?), so no "256", but the audio glitches seem to be gone after I switch to 448 (from 14). Hopefully this will last.
Obrigado!!

Suggesting to maybe set the *default* value to something higher than "14", which is the smallest buffer size available, to help prevent this issue for users with "low end" systems.

![Jamtaba_buffer_size_values](https://user-images.githubusercontent.com/66199477/83434112-b5735580-a3ee-11ea-8ffb-4e21eda6f423.png)

**Comment by elieserdejesus** [comment]
14 is a very small buffer size. I will filter out the small values to avoid the glitches.

> (unconventional numbers, intended?)

Yes, no common values. I will check this code, but I think these values are returned by the audio device.
