### ISSUE TITLE
Crash when user 'booga' is connected to server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1337]
booga is also a bot name, so the crash may be related. Deleting the bot fixes the issue (https://github.com/elieserdejesus/JamTaba/pull/1334)

**Comment by jonjamcam** [comment]
> The problem is only when theres a boot named 'booga' and an user with same name, right?

Yes. It happened to me some days ago. Server was ninjam.live:2049 I think. The user was from US.

I tried to enter several times, the crash happened when the first bpi interval of 120/16 ends so you need to wait some seconds while inside the server.

Edit: maybe it's relevant or not but 'booga' was sending audio

**Comment by elieserdejesus** [comment]
Bug confirmed here, just wait for the interval start and see the crash.
