### ISSUE TITLE
VST :  the chat window is cropped sometimes

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#134]
hey ) in small view (thy for that great) in vst the chat window is cropped sometimes at the right or even in the comments it croppes the last written lines )

**Comment by Ezeer** [comment]
Add a horizontal scroll bar would be enough for you ?

**Comment by jonjamcam** [comment]
There's already is a scroll bar for the control section when there's a lot of channels: see https://github.com/elieserdejesus/JamTaba/issues/85

-![snap](https://cloud.githubusercontent.com/assets/1012741/10946389/2c40a854-8309-11e5-8c43-f650c08a215c.png)

**Comment by Ezeer** [comment]
yeah , but not in the chat box bro .
That's what i was asking for .
So the idea is good , that's what you mean jon ?

**Comment by jonjamcam** [comment]
opps...chat :D

**Comment by MagnusDrumsTrumpet** [comment]
yeah i used already)that was the input for my idea to do that on the player channelstrips too id you are connected and then dont have to scroll and see all players atonce and can maybe handle their vol levels 


     jonjamcam <notifications@github.com> schrieb am 18:46 Sonntag, 15.November 2015:
   

 There's already is a scroll bar for the control section when there's a lot of channels: see #85-—

**Comment by jonjamcam** [comment]
I didn't read "chat", magnus. Sometimes the mind goes by it's own. :D

**Comment by elieserdejesus** [comment]
I see the problem. I hope this is fixed for nexts releases: [https://github.com/elieserdejesus/JamTaba/commit/00691c297c1b37e1053d84f22735edcfffa20492](https://github.com/elieserdejesus/JamTaba/commit/00691c297c1b37e1053d84f22735edcfffa20492)

**Comment by MagnusDrumsTrumpet** [comment]
![image](https://cloud.githubusercontent.com/assets/15855828/11191112/d569645e-8c99-11e5-83bf-760a04a50fcc.png)

**Comment by MagnusDrumsTrumpet** [comment]
here an example )))  and in both views same and the lines were much longer and it didnt return the writtenlines instead one longline but cropping
 somtimes alsi it crops the last line ))
 just for imagination

**Comment by Ezeer** [comment]
ah ah ah ... nice demonstration ! thx .
^^

**Comment by jonjamcam** [comment]
tread realted https://github.com/elieserdejesus/JamTaba/issues/118
