### ISSUE TITLE
v2.1.15-beta2 crash when change bpi. bpm

### ISSUE THREAD

**Issue by soulraymusic** [elieserdejesus/JamTaba#1345]
It freezes when changing bpi, bpm a couple of times. 
v2.1.14 works fine.

**Comment by elieserdejesus** [comment]
fixed inhttps://github.com/elieserdejesus/JamTaba/commit/34b075d841df69b00fbd6c8087c58a40509c392d

**Comment by soulraymusic** [comment]
@elieserdejesus it still contains the freeze issue when changing bpi/bpm.

See the video. https://drive.google.com/file/d/1W1eRmKez9o8LSBLHUfDvjuK0ST8UNgLs/view?usp=sharing
