### ISSUE TITLE
Public chat connection error

### ISSUE THREAD

**Issue by soulraymusic** [elieserdejesus/JamTaba#1346]
Macbook pro. OSX High Sierra. 
When launching Jamtaba, the public chat is not connecting. See many HTML errors in that chat window. It might be a ninjam server issue?

<img width="212" alt="Screen Shot 2020-06-28 at 8 00 18 AM" src="https://user-images.githubusercontent.com/65140559/85947042-6568af80-b916-11ea-958b-62b4634299a2.png">

**Comment by elieserdejesus** [comment]
The chat server free quota is exausted at moment. This public chat is separated from ninjam servers, is hosted in a free Heroku account.

**Comment by elieserdejesus** [comment]
Error message improved in https://github.com/elieserdejesus/JamTaba/commit/77bfc03e9e9c234a5e048396a22c96616219c6a4

**Comment by soulraymusic** [comment]
Perfect!
