### ISSUE TITLE
[FR] List private servers saved in a file

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#1347]
The idea is allow users to write a JSON file including your preferred private servers, user name and passwords for these servers.

The private servers are liste in the top, before the public servers. This a easy way to connect in private servers using one click and is helpfull for educational purpouses where professors can create some private servers, write the json file and share with your students.  Just for record this idea was proposed by @soulraymusic .

**Comment by elieserdejesus** [comment]
JamTaba will always export a json example file. This is just an example file and will not be loaded bu JamTaba.

![image](https://user-images.githubusercontent.com/1012741/86023510-2748ba00-ba02-11ea-9b46-f677163d438c.png)

**Comment by elieserdejesus** [comment]
User must rename the file to **private_servers.json** (it's copy the original file and rename the copy):

![image](https://user-images.githubusercontent.com/1012741/86023799-87d7f700-ba02-11ea-88dd-0125f4239069.png)

**Comment by elieserdejesus** [comment]
The example file is shoing 2 example servers. The first example is simple and is using just server name:port and max users. The second example is using a custom user name and password to connect in the private server. The passoword is not mandatory in the second situation, users can connect using a custom user name only.

```
{
   "servers": [
      {
         "server_name": "example_server.com:2049",
         "server_max_users": "4"
      },
      {
         "server_name": "another_example_server.com:2050",
         "server_max_users": "4",
         "user_name": "my cool name",
         "user_pass": "1234"
      }
   ]
}
```

**Comment by elieserdejesus** [comment]
Jamtaba will show the servers at the top:
![image](https://user-images.githubusercontent.com/1012741/86024376-4d228e80-ba03-11ea-8a69-dcc68e3735b0.png)

**Comment by soulraymusic** [comment]
@elieserdejesus the IDs and Passwords have to match with ones on the configuration file, correct? Also, instructors can use a text edit software to create a json.file by renaming copied version of any json files (e.g. loof file). Does this work?

**Comment by jonjamcam** [comment]
Sounds good feature to me. I think for the complete package it would be nice if the private server showed who's inside. Maybe not a map, but a list.

**Comment by elieserdejesus** [comment]
> the IDs and Passwords have to match with ones on the configuration file, correct? 

Exactly @soulraymusic , the IDs and password have to match the private server config file.

> Also, instructors can use a text edit software to create a json.file by renaming copied version of any json files (e.g. loof file). Does this work?

Yes, any text editor will work.

**Comment by elieserdejesus** [comment]
> Sounds good feature to me. I think for the complete package it would be nice if the private server showed who's inside. Maybe not a map, but a list.

I agree @jonjamcam , this can be done using the server stats password to quick connect, grab the users list and disconnect. But I never used these servers stats stuff, I need investigate the details.
