### ISSUE TITLE
make the channelstrips of the player smaller by choice

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#135]
hey) can you also make the channelstrips of the player smaller by choice to save some place and see all channels playing at once like you did at the own sending channels perfect on the left in small view... thy elieser

**Comment by Ezeer** [comment]
AH AH AH .... Hey magnus , can you make short intro fill for the title and develop your patern idea
in the description tab , please ? Wait ... i do it for  you .
![images](https://cloud.githubusercontent.com/assets/1283808/11168557/fac6c02c-8b93-11e5-8716-483519c3d50f.jpg)

**Comment by Ezeer** [comment]
You mean resize the remote tracks ?

**Comment by MagnusDrumsTrumpet** [comment]
hey
hm if i could make a picture but cant
so the players stripas there can be 8 of them should in minimal flip mode only exist of the meter and the fader over the meter 
as i forgot that we have to see the playes name akso maybe also behind the meter written vertically
 ohhh  alot work
at the end i always compare to original reaninjam window
 there the channels are horizontal 
 but you view is muuuch more attractive
thy for all that)
Mag

**Comment by Ezeer** [comment]
Thanks for your report Mag' .
We'll study that !
**but you view is muuuch more attractive**
elieser will be happy to hear that :)
Ezee

**Comment by Ezeer** [comment]
@MagnusDrumsTrumpet 
>so the players stripas there can be 8 of them should in minimal flip mode only exist of the meter and the fader over the meter 
as i forgot that we have to see the playes name akso maybe also behind the meter written vertically
ohhh alot work

nice , i've got the picture in my head now ! ;)

**Comment by MagnusDrumsTrumpet** [comment]
yeah  
 lets say the meter is pulsing behind the fader knob os so and in background maybe the name and flag faded to background wellat the end it should be practical 
it is as i thing all from the problem of using as vst you need place for the Daw too so the vst window has to ne smallenoufg to see all other from the Daw
 dont want to wor with two monitors right now hehe  or maybe like a pro   nonononn not at moment ))))

**Comment by Ezeer** [comment]
**smallenoufg**
lol ! wait ...
![schtroumpf-musicien_original_backup](https://cloud.githubusercontent.com/assets/1283808/11170047/20dde8aa-8bc9-11e5-8eb9-369c63d5006c.jpg)

**dont want to wor with two monitors right now hehe**
you read on my mind ...
But i need that feature for myself when i'm at drum , so i'll make it one of zeez dayz .
wait....
![music-iranja](https://cloud.githubusercontent.com/assets/1283808/11170052/9410e9e4-8bc9-11e5-8436-e9c09997282b.jpg)


^^

**Comment by MagnusDrumsTrumpet** [comment]
sweeeeetttttt ))))) 


     Ezee <notifications@github.com> schrieb am 18:49 Sonntag, 15.November 2015:
   

 smallenoufg
lol ! wait ...
dont want to wor with two monitors right now hehe
you read on my mind ...
But i need that feature for myself when i'm at drum , so i'll make it one of zeez dayz .
wait....
^^ —

**Comment by elieserdejesus** [comment]
Magnus, I think many users like the horizontal layour use in Reaninjam, and the horizontal layout can handle more tracks.
I have two ideas to improve the screen space usage:
1 - Add a collapse button in chat, like we have in local controls. So you can reduce the chat window and this extra space is used to show the users tracks/channels.
2 - Add a button to choose between horizontal or vertical layout for ninjam tracks. Add a horizontal layout is a lot of work, but is possible and I think this will add a lot of flexibility in jamtaba user interface. 

I'm addint this 2 issues in the list right now, so wee will see this in some future Jamtaba version :)

**Comment by MagnusDrumsTrumpet** [comment]
coool sounds goood  )))
