### ISSUE TITLE
Local Video recording

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#1358]
ATM recording local video is disabled. When enabling it I found some issues:

1. Local files are .mp4 and apparently have no container making them only playable with specific software like Vegas, but not VLC, etc.

2. Remote video tracks are not stored locally (because video uses channel 2 maybe?)

3. For editing purposes quality is very low and format 4:3 is outdated. Allowing custom quality and format could be nice.

Issue https://github.com/elieserdejesus/JamTaba/issues/983 related

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I never work serious in local video recording, so it`s very raw, just for debug purpose at moment.

If I remember correctly the video file content is a raw h264 without container, just the extension is mp4, but the content has no container information. I had some difficulties to xmit the mp4 data, so I just decide xmit the raw video data only.

**Comment by jonjamcam** [comment]
I added some code to record remote video streams locally and it's working very nicely, but I'm not sure if it's a good idea as a public feature. I'm concerned about privacy and potential misuse, but ATM I can't think about any safety feature. 

Closing for the time being...
