### ISSUE TITLE
Midi input or output don't work when Listen is on 

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#136]
I wanted to play offline with my midi keyboard , listening to the jam but i couldn't .
Is it specific to my midi driver or same for all ?

**Comment by jonjamcam** [comment]
Listen button mutes everything else. I think it was designed like that by Elieser.

**Comment by Ezeer** [comment]
Well , i think it's bad like this .
If i want to setup a vst chain with midi before enter the jam , or find what to play before jumpin' , i can't.
Or just play with the band when the room is full etc ...
It's less freedom .
Your point guys ?

**Comment by Ezeer** [comment]
hem ...okay there is the transmit also to allow tunings and setup , but play while listening should be 
possible in my opinion , just to taste the Jam .

**Comment by jonjamcam** [comment]
I would like the channel not to be muted while listening. Server slots are very few and sometimes the jam is so cool It would be enough to just jam along with the mix if you can't enter.

**Comment by Ezeer** [comment]
Same vibe here .
I'll work on that so .

**Comment by Ezeer** [comment]
That is not a bug but the elieser's design : 
>void MainController::playRoomStream(Login::RoomInfo roomInfo){
    if(roomInfo.hasStream()){
        roomStreamer->setStreamPath(roomInfo.getStreamUrl());
        currentStreamingRoomID = roomInfo.getID();

> //mute all tracks and unmute the room Streamer
        setAllTracksActivation(true);
        roomStreamer->activate();
    }
}

I was saying that the design was 'bad ' , it was quickly said ...
Jamtaba actual behavior was done by one man ( standalone ) and i am a ... plugin . ( lol )
So i think the original behavior must be saved , and mods proposed as options .

In that context , i may use my configurator stuff to add these mods to Jamtaba .
@jonjamcam I think to make an alpha version of 2.0.6 for win32 only , with no installer but inside
a winrar archive . I will include that mod on it ( play sounds when listening ) .Are you interested to test ?

**Comment by jonjamcam** [comment]
I rather think the design is convenient for the typical user, not a bad design. Probably not many are interested in "ghost" jamming. lol

"Are you interested to test ?"

Yeah.....let's see how it works.

**Comment by Ezeer** [comment]
Okay .
I don't know wich way to use , as elieser dislike the freefrominstallmingwreleasestuff . 
lol .
So i will upload somewhere a limited edition ( standalone win32 only , to test under x64 also ? ),
with the features i'm working on ( press 'q' to quit is awesome ... F1 to F4 shortcuts works etc ... )
I will call these releases "Jomtobo " , because they are unofficials for testers only .
They will work also in Jomtobo 2 folder , so they won't overwrite your Jamtaba 2 folder .
Thank you jon !

**Comment by Ezeer** [comment]
@jonjamcam  To stay in the private team cloud , as this release is unofficial BUT that you are official
jamtaba tester , check your InBox at ninbot.com . thx :)

**Comment by elieserdejesus** [comment]
guys, I totally agree with this, let's put in the next release, no problem.
you put 2 good enough arguments here:
1 - allow play with the jam without connect in the server.
2- allow play with the server stream when the server is full (very common case).

And the 2 is specially important, because sometimes we have something users refreshing the servers status and waiting to a free slot to play in a very cool jam. So, if users can warmup and play "offline", when this users have a free slot all stuff are setuped (this word exists?), chords are tracked learned, etc.

Let's change this, is something very easy in the code and can have a good impact in the user experience.

**Comment by jonjamcam** [comment]
ok so it goes mainsteam......:D

**Comment by Ezeer** [comment]
wohooo ! It's ....
![star-wars-episode-vi-han-solo](https://cloud.githubusercontent.com/assets/1283808/11188674/53589e24-8c8c-11e5-98dc-8e1d033f01b6.jpg)
