### ISSUE TITLE
can you make us see the number of allowed person in the rooms in the available rooms

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#137]
also the running bpi and bpm momentarily before enter the room
hehe alot nerdy wishes
thy ya great

**Comment by Ezeer** [comment]
**also the running bpi and bpm momentarily before enter the room**
In what we call the busydialog ? ( rolling sign ... )

**hehe alot nerdy wishes**
nah , that is a good idea indeed .
Just wait the elieser's opinion .
;)

**Comment by elieserdejesus** [comment]
Good ideas, and is easy to implement. We have this infos (bpm, bpm, and maxUsers) from each server, so it's just put this in the user interface.

**Comment by MagnusDrumsTrumpet** [comment]
what i was thinking )

**Comment by elieserdejesus** [comment]
done!
![image](https://cloud.githubusercontent.com/assets/1012741/11256114/3930d9c0-8e31-11e5-8f23-4436866a9bac.png)

**Comment by Ezeer** [comment]
Goooood Job ! That was really needed !

**Comment by MagnusDrumsTrumpet** [comment]
Wonderful ))) thy


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Elieser Ademir de Jesus <notifications@github.com> 
Datum: 18.11.2015  23:16  (GMT+01:00) 
An: elieserdejesus/JamTaba <JamTaba@noreply.github.com> 
Cc: MagnusDrumsTrumpet <jojo4u72@yahoo.com> 
Betreff: Re: [JamTaba] can you make us see the number of allowed person in the
  rooms in the available rooms (#137) 

done!
