### ISSUE TITLE
connect room as user 

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#138]
if i whant connect a room with user and pass  that should be possible
look in reaninjam if you enter a room you can see how it is done

**Comment by Ezeer** [comment]
The pass is needed for some privileges ?
Because Jamtaba tries to simplify the steps to enter a join .
I think you can already join like the old way using the ninjam menu ->private server .
( okay , there is no autofill for servers name , but that is not its primary role ^^ ).

It can be done magnus , but i'm waiting for elieser's opinion here again .

**Comment by MagnusDrumsTrumpet** [comment]
Yeah i am fried of easy use too)But some otions should be possible to do lets say in enhanced settings or soNo stress with all alot wishes


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Ezee <notifications@github.com> 
Datum: 16.11.2015  12:57  (GMT+01:00) 
An: elieserdejesus/JamTaba <JamTaba@noreply.github.com> 
Cc: MagnusDrumsTrumpet <jojo4u72@yahoo.com> 
Betreff: Re: [JamTaba] connect room as user  (#138) 

The pass is needed for some privileges ?

Because Jamtaba tries to simplify the steps to enter a join .

I think you can already join like the old way using the ninjam menu ->private server .

( okay , there is no autofill for servers name , but that is not its primary role ^^ ).

It can be done magnus , but i'm waiting for elieser's opinion here again .

**Comment by Ezeer** [comment]
**But some otions should be possible to do lets say in enhanced settings or soNo stress with all alot wishes**
ah ah ah .... i am that kind of enhanced user , and i have a silly tendancy to love the complication finally...

Freedom mean everything is possible , so let's say that Jamtaba is slave of freedom , lol !
Yes , i'm working on a configurator actually , i think i can handle that in my todo list .
Or a friend of mine : 
![earl-jason-lee-aurait-pour-une-fois-un-bon-karma_portrait_w532](https://cloud.githubusercontent.com/assets/1283808/10911967/9b5bbec6-8247-11e5-91c6-9a9c525daab0.jpg)

ah ah ah ah ...

**Comment by elieserdejesus** [comment]
Hi @MagnusDrumsTrumpet , I think put the options to login using username and pass in every server is a very bad thing. The terminology used in Reaninjam is very confuse. For example, you need fill a text box with your "nick name", and after this check the "annonymous". Try Reaninjam with a non ninjamer and you will see how confuse is this login scheme. 

Maybe we can change the Jamtaba Ninjam Private Server dialog to ask a user name and don't use the "public" user name. This make sense. But please, don't suggest change Jamtaba to the **old school very bad and confuse Reaninjam login scheme** , ha ha ha.

**Comment by Ezeer** [comment]
Well , i can add a menu entry that showup only when username=Marcus . (lol )
But in exchange @MagnusDrumsTrumpet  you allow me to record your session if i like it using my next DANGEROUS feature : 
https://github.com/elieserdejesus/JamTaba/issues/97

![le_parrain_disc_1-14153211062007](https://cloud.githubusercontent.com/assets/1283808/11188404/f284c056-8c8a-11e5-912b-580e73a965f4.jpg)

eh eh

**Comment by MagnusDrumsTrumpet** [comment]
right ))) no confusion 
 should only be an option one can choose maybe in settings before starting that it asks then 
 about login
 default always should be free incomming surely )

**Comment by Ezeer** [comment]
**right ))) no confusion**
a deal is a deal ! i fixed ' marcus ' lol ....

**Comment by elieserdejesus** [comment]
A simple solution: show a "user name" field in Private Server Dialog, this field appears with user name by default, but the field is editable and users can type any valid name.

**Comment by elieserdejesus** [comment]
Fixed in #ee5fe97 
![image](https://cloud.githubusercontent.com/assets/1012741/22078999/5eee85b6-dda1-11e6-92df-2398aa09954a.png)

**Comment by jonjamcam** [comment]
@elieserdejesus "Leave blank to connect as anonymous" calls the login dialog...

![image](https://cloud.githubusercontent.com/assets/15310433/22083547/59cca19e-ddab-11e6-8ee4-f4ca09c7d48d.png)

![image](https://cloud.githubusercontent.com/assets/15310433/22083563/6aaa9354-ddab-11e6-9189-8bd5b211b5f6.png)

so it's not working as expected?

**Comment by elieserdejesus** [comment]
> or maybe the tooltip is not showing the correct text.

Excatly @jonjamcam , this is the problem. 

>  I think it would be a good idea if the password was masked. 

I agree. 

Both issues are solved in the last 2 commits.
