### ISSUE TITLE
Cannot use Audio Unit on macOS BigSur with Apple Silicon / M1

### ISSUE THREAD

**Issue by fabiangebert** [elieserdejesus/JamTaba#1396]
I was able to pass verification of Audio Unit, it shows up in "Plug-In Manager" in logic with compatibility "successfully validated" and use is checked. However, I cannot add it as an insert. Used to work on my previous Mac with macOS 10.15. In both cases, I used Logic Pro 10.6.1.

**Comment by berndkeul** [comment]
is there any news on Jamtaba2 with M1 ?

**Comment by fabiangebert** [comment]
for some strange reason it works with latest Logic for me

**Comment by berndkeul** [comment]
can we have a chat on this ?
berndkeul@netcologne.de
