### ISSUE TITLE
VST plugin - problem with space bar - Resported by Karma and plJones in ninbot forum

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#14]
I just tested the VST and there is a problem with the space bar in the chat .When I press the bar spacing, the play of a track or a drum stops. Apart from this the vst work like a charm. Thank you very much. Good job dudes.

**Comment by elieserdejesus** [comment]
Solved!

**Comment by Ezeer** [comment]
good job !
