### ISSUE TITLE
Use of shortcuts ...

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#141]
I 've tested and found that  :+1: 

![prefs](https://cloud.githubusercontent.com/assets/1283808/11182071/412aada6-8c68-11e5-803b-1c37688a927c.jpg)

**Comment by Ezeer** [comment]
In order to work (Quit...) , i had to rewrite : 

      void MainWindow::on_preferencesClicked(QAction* action)
      {
      //Use of action now ! Ezee...
      if(action->objectName().contains("actionQuit"))
       {this->close();return;}
...
...

And i think to filter other actions too .
Elieser ?

**Comment by Ezeer** [comment]
About filter the other actions , i've seen you do it after ... I won't touch that now .
I just modified my code following your rules : 
//Use of action now !
    **if(!mainController->isRunningAsVstPlugin())**
    {if(action->objectName().contains("actionQuit"))
       {this->close();return;}
    }

**Comment by elieserdejesus** [comment]
Ezee, I'm not shure how this shortcuts will behave in Vst plugin, because host is the "big boss" capturing the key pressing.

**Comment by Ezeer** [comment]
Please test it ?
We can find a way to disable them on plugin , don't worry .
:)

**Comment by Ezeer** [comment]
And the update for shorcuts is here : bda3d1c

**Comment by elieserdejesus** [comment]
It's working here for standalone.

**Comment by jonjamcam** [comment]
Guys, just a suggestion. Since windows 3.11 I think until now the F1 key is reserved for the help function. I think most software keep this convention. Maybe F2-F5 could be a more standard approach?

**Comment by Ezeer** [comment]
Assignment can be easily changed .
It's true F1 is a standard Help button , let's link it to help .
But start with F2 for the preferences .... i prefer start from F5 to F8 , centered above the space bar
and grouped .
?

**Comment by Ezeer** [comment]
To work on that stuff prepare me to work with assignments with the Joystck class too ... ^^

**Comment by elieserdejesus** [comment]
I Agree, F1 to help and F4-F8 to preferences and ESQ to quit sounds very good.

**Comment by Ezeer** [comment]
F5 to F8 and it's a deal !
lol

**Comment by elieserdejesus** [comment]
Ops, wrong typing here :)  F5-F8, hehe.

**Comment by Ezeer** [comment]
DEAL !!
^^

**Comment by Ezeer** [comment]
Done here  : https://github.com/elieserdejesus/JamTaba/commit/8287b7225d2dd09aeaccb44b4cb08b6e4631ca5f

F1 works like a charm ...
