### ISSUE TITLE
handle the smalest view in reaper of jamtaba window what i found)

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#145]
when you open an vst in my reaper it is like that:
![image](https://cloud.githubusercontent.com/assets/15855828/11191893/3c2e0e52-8c9e-11e5-8883-2a43aaa542ee.png)

to get it without frame around doubbleclick on the written vst name ( here jamtabe on the frame at the upper left and you get this:

![image](https://cloud.githubusercontent.com/assets/15855828/11192084/42c3b144-8c9f-11e5-8b34-4028d2c6649c.png)

then just close the gray vst frame behind and you get  this ))))

![image](https://cloud.githubusercontent.com/assets/15855828/11192104/5550cbe4-8c9f-11e5-909b-218ca6f5fff6.png)

have fuuuun)
Mag

**Comment by Ezeer** [comment]
COoooOoool !
@jonjamcam a trick for the pluginPart in the doc , doc ?
![bugs-evolutionjpg-fb73c6b426915aaf](https://cloud.githubusercontent.com/assets/1283808/11192394/30cd11ea-8ca1-11e5-8bee-091f703be65c.jpg)

**Comment by jonjamcam** [comment]
Well, this is specific to reaper, so maybe in the reaper manual......oh wait!.....:D

**Comment by MagnusDrumsTrumpet** [comment]
what where when )))
 cant find it like that saw many possibilitys to reyh the vst´s but never on right clicking happend that (
 wich fx list you mean were did you showup the FX list )))

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , right click in the FX button:

![image](https://cloud.githubusercontent.com/assets/1012741/11197658/0b9a8db2-8ca6-11e5-8d20-ad0236fc6cfb.png)

**Comment by MagnusDrumsTrumpet** [comment]
cool works on most vst but on jamtaba i have the frameline above always like this  hm doesnt dissapear


![image](https://cloud.githubusercontent.com/assets/15855828/11217428/81b8182a-8d50-11e5-9b9a-822cae522a19.png)

**Comment by Ezeer** [comment]
I think it's just some lines of code to add to tell to Qt we no more want that type of window .
In standalone , there is the fullscreen mode that i have tested that just cut the upper part of the window,
just keep the screen .
May be try different windows style for MainWindow elieser ?

**Comment by Ezeer** [comment]
Perhaps that code  : 

window.setWindowFlags(Qt::Window | Qt::FramelessWindowHint);
window.show();

**Comment by elieserdejesus** [comment]
Ezee, I think the frame is created by Reaper, because we can see some Reaper controls (combos, knob, etc) in the top of window. These stuff are not created by Jamtaba, so I'm supposing the Qt window flags will not work in this case.

**Comment by Ezeer** [comment]
**cool works on most vst but on jamtaba i have the frameline above always like this hm doesnt dissapear**

That mean that for other vsts reaper couldn't draw his stuff .
Well , i just guess ( i suddenly hear a voice that whispers " static , static .. " , and i can't put more money to the jack's pot , lol )

**Comment by elieserdejesus** [comment]
I test here, my Reaper x64 always create the frame in the top for x64 plugins. But the 32 bits plugins are created in a separated windows, without the frame in top.

**Comment by Ezeer** [comment]
It's a draw  ! lol , watch that  : https://www.youtube.com/watch?v=mjEcj8KpuJw
uh hu hu ...

**Comment by MagnusDrumsTrumpet** [comment]
yeah 32 64 maybe the reason but really not so important)))

hehe the blaaack knite 

i love that look from 2.20min  hehehe
