### ISSUE TITLE
No more flag icons

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#146]
@Ezeer and @jonjamcam , maybe you notice Jamtaba is not showing the flag icons, except if you have the flags cached. In my machine I deleted the Jamtaba 2 folder to test some stuff, so I don't have any flags chache at moment, and I can see just the yellow waning icons.

Jamtaba is using a free service to translate users IP to country, and use the correct flag icon based in country code.
Unfortunally this free service is not working: [http://www.telize.com/](http://www.telize.com/) 

I will test other free services.

**Comment by Ezeer** [comment]
it's bad ...
But there is free hosting for Nginx that we could use to run our own telize server app using : 
https://github.com/fcambus/telize

**Comment by jonjamcam** [comment]
looks like ZENJAM has a better solution.....Any chance this is available for jamtaba? maybe ask tom.

![zenjam snap](https://cloud.githubusercontent.com/assets/15310433/11198446/74e7e13c-8ca3-11e5-9630-a32b404c296c.jpg)

**Comment by Ezeer** [comment]
Can you run java in your GAE environment elieser ? 
Look at that please : GeoIP2 Java API  https://github.com/maxmind/GeoIP2-java

Web Service Example

Country Service

// This creates a WebServiceClient object that can be reused across requests.
// Replace "42" with your user ID and "license_key" with your license key.
WebServiceClient client = new WebServiceClient.Builder(42, "license_key").build();

InetAddress ipAddress = InetAddress.getByName("128.101.101.101");

// Do the lookup
CountryResponse response = client.country(ipAddress);

Country country = response.getCountry();
System.out.println(country.getIsoCode());            // 'US'
System.out.println(country.getName());               // 'United States'
System.out.println(country.getNames().get("zh-CN")); // '美国'

global information and Api here : http://dev.maxmind.com/geoip/geoip2/web-services/

**Comment by jonjamcam** [comment]
only the chached ones too i think.....

![flagnoflag](https://cloud.githubusercontent.com/assets/15310433/11198585/aee27720-8ca4-11e5-9a5b-6eb3d65a2ebc.jpg)

**Comment by Ezeer** [comment]
From what i've read , a part of GeoIP2 is free of charge , and can be used in php .
So we should try to make it ourselves , me say .
http://php.net/manual/en/book.geoip.php

**Comment by jonjamcam** [comment]
" Telize is open source, and can be downloaded as tarball releases or on GitHub. The project will keep being maintained and anyone can install and run their own instance, there is no “vendor” lock-in. "

http://www.cambus.net/adventures-in-running-a-free-public-api/

**Comment by elieserdejesus** [comment]
I change the code to use http://geoip.nekudo.com/. It's free too and the api is very good. I'm avoiding run a "IP translation" service in GAE to avoid more costs. 

I think we need release the v2.0.6 right now to include this new "IP translation service".
I will release the new version so we can test a little before release.

**Comment by Ezeer** [comment]
**Iwill release the new version so we can test a little before release.**
Call it alpha perhaps ?
;)

**Comment by elieserdejesus** [comment]
Released guys, please help to test!

**Comment by jonjamcam** [comment]
working....It's a bit slower though.....

![new ip](https://cloud.githubusercontent.com/assets/15310433/11200216/cb77a190-8cb2-11e5-955d-a49d1e9a1797.jpg)

**Comment by Ezeer** [comment]
workiing also here .
But hey , where are my so coool changes ... no shortcuts , no midi on listen ... beuuuu .
And the configurator ? And ... And ... 
^^
Hopefully in the beta version ?

**Comment by elieserdejesus** [comment]
Ezee, I don't merge your changes yet because I'm afraid about merge conflicts. I see you have various commits in the configurator branch. Every commit can introduce merge conflicts, so this merge will be complicated. 
Let's release 2.0.6 as a quick fix to the "translation IP" problem and apply the other changes in 2.0.7

**Comment by Ezeer** [comment]
Well , if u want , but i try to follow a timeline , and my stuff were planified for milestone 2.0.6 .
( and i've merged the master in configurator to check , there was only one conflict with Jamtaba-common.pri . )
But seven is a great number , 6 known to be the beast's number . lol 
Okay , i'll wait for my sexy things 'til seven is up !
![lucas-sarah-1962-united-kingdo-seven-up-1209666](https://cloud.githubusercontent.com/assets/1283808/11209989/289fc268-8d25-11e5-9ca4-99a0edfbfd67.jpg)

ah ah ah ...

**Comment by elieserdejesus** [comment]
Just one conflict is easy to manage, I will check this right now.

Haha, the marketing guys and your logics:
How can I have a lot of women?
It's simple: drink plenty of soda!

Hahaha. Here in Brazil we have the same shit in beer and car TV commertials. 
![image](https://cloud.githubusercontent.com/assets/1012741/11210294/5fbf5cf2-8d0e-11e5-9bf8-253895cd2854.png)

**Comment by Ezeer** [comment]
uh uh uh uh ! ( i learned that from magnus lol )

**Comment by elieserdejesus** [comment]
Merge done, just a couple of little tweaks and all working!

**Comment by Ezeer** [comment]
Aaaaaah ! That is so cooool !
( but can i still have the women boss ? lol )

**Comment by elieserdejesus** [comment]
haha, drink a ton of soda everyday and you will have all the womans. If soda don't work try drink beer. If the beer don't work try a funk car, he he.

@jonjamcam and @Ezeer , I release a 2.0.6 beta including the last Ezee contributions and a little fix to the "fixed accent value when enter in a ninjam room".

**Comment by Ezeer** [comment]
I drink bear already , slowly comes ... perhaps should i try the funky car ?
![scooby2_1996628c](https://cloud.githubusercontent.com/assets/1283808/11211513/35feddc6-8d30-11e5-894f-188f9329e501.jpg)

**I release a 2.0.6 beta including the last Ezee contributions**
uh uh uh .... bzzzzzz....twiiiiiii....
