### ISSUE TITLE
Wrong chords parsing

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#148]
I enter in ninbot to test. The server topic message was "MUSIC here no fucker ... just peace", and Jamtaba show the button to "load the chords above".

**Comment by Ezeer** [comment]
uh uh uh ! **"MUSIC here no fucker ... just peace"** 
well , Jamtaba seem to be able to understand what is a chord , and interpret human langage  , if a chord is a peaceful harmony of tones ...
Perhaps Jamtaba try to say that "he" is able to translate words in sounds ?
"Our Final Invention" --Will Artificial Intelligence End the Human Epoch?
![brain](https://cloud.githubusercontent.com/assets/1283808/11210867/867bcb56-8d2b-11e5-8dd5-2b7b719a371a.jpg)
http://www.dailygalaxy.com/my_weblog/2013/10/artificial-intelligence-will-it-end-the-human-epoch.html

lol

**Comment by elieserdejesus** [comment]
Fixed! :)

**Comment by jonjamcam** [comment]
lol AI! 

"Jamtaba..........expanding the boundaries of the human race......" 

https://www.youtube.com/watch?v=7MXQSbjBL7Q&list=PLLgVDY8_xVLYhjw_pOkTnuX2NWQ9fsSy3
