### ISSUE TITLE
Plugin version of Jamtaba 2.0.6b crashed in Reaper

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#149]
lol , we are now in the blackbox of reaper ....
I am under windows XP SP3 using Reaper 5.01 

I don't remember the nature of the message , perhaps a problem with the dll entry point .
Crash occured while scanning ...

**Comment by Ezeer** [comment]
ok , i reseted reaper , and got the error message now : 
![error](https://cloud.githubusercontent.com/assets/1283808/11213297/7d9fbf46-8d3b-11e5-94c3-3d43285d406e.jpg)

**Comment by Ezeer** [comment]
And the problem may come from : 
Remarks

Starting with Windows 7 and Windows Server 2008 R2, Psapi.h establishes version numbers for the PSAPI functions. The PSAPI version number affects the name used to call the function and the library that a program must load.
If PSAPI_VERSION is 2 or greater, this function is defined as K32GetProcessMemoryInfo in Psapi.h and exported in Kernel32.lib and Kernel32.dll. If PSAPI_VERSION is 1, this function is defined as GetProcessMemoryInfo in Psapi.h and exported in Psapi.lib and Psapi.dll as a wrapper that calls K32GetProcessMemoryInfo.

Programs that must run on earlier versions of Windows as well as Windows 7 and later versions **should always call this function as GetProcessMemoryInfo. **To ensure correct resolution of symbols, add Psapi.lib to the TARGETLIBS macro and compile the program with -DPSAPI_VERSION=1. To use run-time dynamic linking, load Psapi.dll.

**Comment by elieserdejesus** [comment]
Exactly, I have the same error here when start coding the PerformanceMonitor. 
I change the code and the DEFINEs to solve the problem, but I think the last merge loose something.
I will check ...

**Comment by elieserdejesus** [comment]
Ops, my bad. The DEFINEs and correct lib are setted only in standalone, not in the VSt plugin subproject.

**Comment by elieserdejesus** [comment]
@Ezeer , I release 2.0.6-beta.2 fixing the problem. Please test again...

**Comment by Ezeer** [comment]
Nice , thanks . lemme download it  ...

**Comment by Ezeer** [comment]
No , same crash here , sorry .
It's the first time i test the plugin , i can't say if the bug is old or just that release .
@jonjamcam You can test on your xp please ?

**Comment by Ezeer** [comment]
2.0.5 works .
But i want to test the beta2 again , perhaps the old dll was loaded in an other path ...
i check that now

**Comment by Ezeer** [comment]
WORKING !
I had i think the first beta in an other path , was loaded first and crashed .
Very nice elieser , shortcuts are not working but it's normal in Vst , 
Great ! Thank you .
^^

**Comment by jonjamcam** [comment]
Just tested on xp with reaper 4. Reaper shuts down after inserting Jamtaba in a slot

**Comment by elieserdejesus** [comment]
Jon, the last versions was working in Reaper 4?

**Comment by jonjamcam** [comment]
I will test again the older versions and report ASAP

**Comment by jonjamcam** [comment]
2.0.5 working fine on XP under reaper 4 (except for the little flags :D)

**Comment by elieserdejesus** [comment]
Jon, can you test the 2.0.6 alpha and 2.0.6beta 1 in your Reaper 4 ?

**Comment by jonjamcam** [comment]
I'm on it

**Comment by Ezeer** [comment]
I am very happy with the " play while listen " feature of that version !
I can setup a track while the room is full , and if there's one guy that leaves , i jump and i'm ready to go !
It's nice , very nice .
The configurator class seems to work like a charm , that is very cool too , i am happy that this could
be achieved .

**Comment by jonjamcam** [comment]
with 2.0.6 beta1 and 2.0.6 alpha I get the following message in reaper:

"reaper.exe - Entry point Not Found

the procedure entry point K32GetProcessMemoryInfo could not be located in the dynamic link library KERNEL32.dll"

**Comment by elieserdejesus** [comment]
Ezee, it's the problem is related with performance monitor. I will remove the referenced for the Psapi lib until we have a better solution for performance monitor in windows. 
Jon, I will release a beta.3 version in some minutes, just to test this last issue.

**Comment by jonjamcam** [comment]
K, Boss

**Comment by elieserdejesus** [comment]
Jon, the 2.0.6-beta.3 is release. Please run this last test for us in your Reaper 4!

**Comment by jonjamcam** [comment]
Sorry, guys. Not working. Reaper is still shutting down once I load jamtaba2 vst :(

**Comment by elieserdejesus** [comment]
Jon, please test this:
1. delete the Jamtaba 2 folder
2. Run the plugin again
3 . Check if the Jamtaba 2 folder is created and if the log file was created.

**Comment by jonjamcam** [comment]
WORKS!

I deleted the Jamtaba2 folder and once I load the plugin on reaper it is created again

**Comment by elieserdejesus** [comment]
No more crash?

**Comment by jonjamcam** [comment]
tested again, no problems.

Log.txt is created inside "PluginVst" folder.

**Comment by jonjamcam** [comment]
[log_beta3.txt](https://github.com/elieserdejesus/JamTaba/files/37033/log_beta3.txt)

**Comment by elieserdejesus** [comment]
Nice, but I suspect the 2.0.5 users will have problems.  
Jon, can you run a last test to simulate the users upgrade from 2.0.5 to 2.0.6?
1 -  uninstall 2.0.6
2 - install 2.0.5
3 - Run the 2.0.5 plugin
4 - Install 2.0.6 and run the plugin.

**Comment by jonjamcam** [comment]
ok

**Comment by jonjamcam** [comment]
"1 - uninstall 2.0.6
2 - install 2.0.5
3 - Run the 2.0.5 plugin
4 - Install 2.0.6 and run the plugin." (uninstall 2.0.5 first?)

**Comment by elieserdejesus** [comment]
No Jon, just install the 2.0.6 without uninstall the 2.0.5.
I'm supossing many users don't uninstall.

**Comment by jonjamcam** [comment]
ok. did exactly that and now I doesn't work. Reaper shuts down as explained before

**Comment by elieserdejesus** [comment]
@Ezeer , I'm 99% shure it's some problem in the configurator. Can you put some light here?
If jon delete the Jamtaba 2 folder the confgurator will recreate the tree and the plugin works fine. But if the 2.0.5 dir tree exists, the plugin fail and crash.

**Comment by jonjamcam** [comment]
I noticed this last time that the "PluginVst" folder is not there. It was created only when I deleted the folder

**Comment by elieserdejesus** [comment]
Ah, this is a good clue. I will check the code right now.

**Comment by Ezeer** [comment]
Yes  guys , the configurator tests if the folder exists !
So the folder must be deleted before launch jamtaba 2 with the configurator .
We can remedy that by making configurator look in Jamtaba2 if the PluginVst exists , and if not ,
create the tree .

**Comment by Ezeer** [comment]
Because now , if it see that Jamtab2 exists , it won't create the tree ...
I can work on that if needed .

**Comment by elieserdejesus** [comment]
I'm fixing Ezee, no problem.

**Comment by Ezeer** [comment]
The problem is here  : 
bool Configurator::setUp(APPTYPE Type)
{
 AppType=Type;//plugin or standalone

 if**(!homeExists())**createTree();
  exportIniFile();
  setupIni();
  return true;
}

BECAUSE  : 
bool Configurator::homeExists()
{
    QDir d(QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation));
    if(!d.exists())
    {qWarning(jtConfigurator) << " HOME folder don't exist ! :" ;
     return false;
    }

    return true; <<<-------- "Jamtaba2 "is enough to skip the folder tree creation
}

**Comment by Ezeer** [comment]
Ok ! Thanks elieser !
^^

**Comment by elieserdejesus** [comment]
I just add another check:
```
if(!homeExists() || !pluginDirExists()){
     createTree();
 }
```

**Comment by Ezeer** [comment]
ah ah ah .. ART !
We could also change homeExists() by treeExists() for a better design .
?

**Comment by elieserdejesus** [comment]
Jon, I release the 2.0.6.beta.4 :)
Please test again when you have some time.
1 - uninstall everything (just to test in a clean scenario)
2 - install 2.0.5
3 - Run the 2.0.5 plugin (the Jamtaba 2 folder will be created)
4 - Install 2.0.6 and run the plugin.
5 - If the new version works you have no crash and a folder "VstPlugin" will be created inside Jamtaba 2 folder.

**Comment by Ezeer** [comment]
i make the test here too .... report when done

**Comment by jonjamcam** [comment]
Ok tested beta4 clean install. Working ok on xp and reaper4. "vstplugin" folder created. Good job guys!

**Comment by elieserdejesus** [comment]
affffff, my god. 
Let's release the 2.0.6 :)

**Comment by Ezeer** [comment]
Works here also , good job !
;)

**Comment by jonjamcam** [comment]
"1 - uninstall everything (just to test in a clean scenario)
2 - install 2.0.5
3 - Run the 2.0.5 plugin (the Jamtaba 2 folder will be created)
4 - Install 2.0.6 and run the plugin.
5 - If the new version works you have no crash and a folder "VstPlugin" will be created inside Jamtaba 2 folder."

done. folder created, no crash now! this is good!

**Comment by jonjamcam** [comment]
"Let's release the 2.0.6 :)"

YES!

Hopefully I'll have the manual updated too for tomorrow.

**Comment by Ezeer** [comment]
And hopefully it will be in pdf format in the 2.0.6 official release .
lol !

**Comment by jonjamcam** [comment]
Yes Ezee. I do it first on the pdf, then migrate it to the web page, then update the bottom link to the pdf, so It's always the same content

**Comment by elieserdejesus** [comment]
Released!
Jon, at moment we have just the link for the User's manual in Jamtaba Help menu. 
Are you thinking in release the PDF too? 
I prefer keep just the link, because users always have the updated content in the github page.

**Comment by jonjamcam** [comment]
I think for now it's OK to link to the page. The changes are still big and fast. Maybe in the future when changes are less we can include a copy so it doesn't get outdated too soon.

**Comment by Ezeer** [comment]
Good softwares have pdf in their releases , never noticed that elieser ?
ah ah ah ..
But i agree with the fact that one download link in the menu could be a trick ( just point to a url where
the updated pdf here )

**Comment by Ezeer** [comment]
well , i just tested the actual link from the menu , and the wiki is  ... very good !
lol 
No problem here guys , thanks for all that stuff we've done together !

**Comment by Ezeer** [comment]
@jonjamcam 
" A PDF copy of this manual can be downloaded from here : https://github.com/elieserdejesus/JamTaba/files/36200/Jamtaba.User.s.Guide.pdf "

You rock !!
^^
