### ISSUE TITLE
a main volume Fader for fade all channels in vst also the own local 

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#150]
i miss it some time you can fade out on several places also but really cool would be  to fade all out at once in the plugin
i saw it on the left corne of the reaper made headline as little knob already 
very usefull if you want to hear some example during the jam to compare or see how songs are played

hehe i am restless with it )))

**Comment by Ezeer** [comment]
well , i've seen your screenshot and you work with a lot of tracks , that's impressive .
( i have also sometime that type of personal projects with brass section , rythm section etc , choirs etc ... ) . So i understand your point(s) .

So , a global fader ?
But imagine that the levels of the tracks are all different , when you fade globally the result .
You expect faders moove equally ( they moove each of the same amount given by the master fader )
or what ? ( what being for example all tracks set to the same level as the master ...)

**Comment by Ezeer** [comment]
Perhaps we could use midi sounds ... 
I love the clave sound , for example eh eh

**Comment by MagnusDrumsTrumpet** [comment]
if you try that knob on left upper corner you have the effect already smth like this
![image](https://cloud.githubusercontent.com/assets/15855828/11226239/042947a6-8d7f-11e5-8f78-8cc2d121d0eb.png)
 yeah why not midi )

**Comment by MagnusDrumsTrumpet** [comment]
how do you mark so quick in the pictures to show details)?

**Comment by Ezeer** [comment]
**how do you mark so quick in the pictures to show details)?**
https://pixlr.com/

**Comment by MagnusDrumsTrumpet** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/15855828/11226678/b7d10062-8d81-11e5-9973-360fa2903315.png)

**Comment by jonjamcam** [comment]
realted to https://github.com/elieserdejesus/JamTaba/issues/9

**Comment by Ezeer** [comment]
lol ! thanks , i see now !
^^

**Comment by elieserdejesus** [comment]
I Agree with jon, Magnus is suggesting the issue #9. It's just a master vol. 
This is not complicated to program. This is fun, but the complicated part here is "where we will put the master fader (mute too?) in the user interface? :)

**Comment by jonjamcam** [comment]
"where we will put the master fader"

may I suggest just a little knob here:

![master knob](https://cloud.githubusercontent.com/assets/15310433/11231081/cbf65590-8d83-11e5-9b29-08afb805864e.jpg)

**Comment by elieserdejesus** [comment]
Jon I think it's not clear this is the master volume. 
The related controls need be grouped in the user interface, so users learn quickly. In your suggestion the master vol is closest to licence button and metronome controls. These are non related things. 

The master volume is a local control, so a good place is the left region (Your Controls), maybe in the bottom using 30-35% of height.
Put another track (the master track) with the local input tracks (side by side) is a option too, I do this in the first Jamtaba. But we will use a lot of horizontal space to show the master track and the possible 4 subchannels. Off course the screen space is not a problem in standalone, I'm thinking in the mini mode. 

Humm, if we put the master track in botton left when user create 4 subchannels in standalone (non mini mode) the left area will grow in width, and the master track will grow too and will be a very unecessary fat track. Can you imagine?

**Comment by jonjamcam** [comment]
Right.....maybe something like this?

![ch w master fader](https://cloud.githubusercontent.com/assets/15310433/11231753/6e87a862-8d8a-11e5-9a4d-0a12cf981e0f.jpg)

**Comment by MagnusDrumsTrumpet** [comment]
yess yess yessssss )))))  and maybe  call it      main vol      dunno )?
great

**Comment by Ezeer** [comment]
lol , sorry guys but for me it looks like a pan slider ... but a knob could fit  .
I don't like the idea of melting the axes like this ( hz vt  having the same function  is confusing for me )

**Comment by Ezeer** [comment]
We could add also a button in the first track ( that is the main for me ... ) that will act as a group
button .  (  'G' button above the 'M' for example )

When pressed ( will highlight ) , the fader control all the tracks  .
You see what i mean ?

**Comment by elieserdejesus** [comment]
The horizontal slider/fader do a better usage of horizontal space, but I totally agree with Ezee, looks like a pan fader. Mix horizontal and vertical can be very confusing.

Ezee, you are thinking in input tracks only? We need group all tracks, including remote tracks and metronome. I think is too mutch. 

I think wee need references. For example, Garage band is very easy to use:
![image](https://cloud.githubusercontent.com/assets/1012741/11238668/65c5ea9c-8dce-11e5-9949-774da208699a.png)

**Comment by Ezeer** [comment]
yeeah i was thinking of inputs only ( with the ninjam tracks also )
The group button is a nice idea , perhaps an other thread ?

**Comment by elieserdejesus** [comment]
the original idea in this issue was: add a master vol. But sometimes is not easy put a new control in the user interface without mess all the things. I think we need a new user interface, and I like the Garage band approach, it's clean and simple. We need be very carefull to not polute all the user interface like this guys:
![image](https://cloud.githubusercontent.com/assets/1012741/11238758/05061c4e-8dcf-11e5-8997-14b75c07f681.png)

**Comment by elieserdejesus** [comment]
Ezee, I agree, the group button is a new feature/issue.

**Comment by Ezeer** [comment]
Lol , the picture above is a nightmare ...

**Comment by Ezeer** [comment]
Perhaps the first idea of Jon is the good one ...
It is located near the metronome , and is intended to affect all the volume outputs .
I vote for this one . ( and we have the chance that Jon is also the maintainer of the doc eh eh )
Just add a hint on mouse over and the user will know what it is ?

**Comment by elieserdejesus** [comment]
the knob is inside the "room region". This suggests the knob will control the "room main vol" and not the real main vol, including inputs, because inputs are in a separated region in the user interface. If you look at Garage band image above is very clear the vol fader in bottom is a "global" fader. When the ui design is clear enough we don't need texts or tooltips to explain the things.

No worries, a master vol is not a critical thing. Let's think about and choose a real good approach. No problem if we found a good solution just in Jamtaba v2.0.87 :)

**Comment by Ezeer** [comment]
**the knob is inside the "room region". This suggests the knob will control the "room main vol" and not the real main vol, including inputs, because inputs are in a separated region in the user interface.**
true

**No worries, a master vol is not a critical thing. Let's think about and choose a real good approach. No problem if we found a good solution just in Jamtaba v2.0.87 :)**

a'right . Let's Jon and magnus find the trick , lol . 
Perhaps we have here the UI department that starts forming !
^^

**Comment by jonjamcam** [comment]
Another try......could be in the top too....

![master vol_tk2](https://cloud.githubusercontent.com/assets/15310433/11246643/4537cb1e-8df7-11e5-82a7-a24148fc9f32.jpg)

**Comment by Ezeer** [comment]
woaw .. your creativity is beyond any known region of space(s)....  lol 
I like this one too !
^^

**Comment by jonjamcam** [comment]
In this case I think the master vol could be collapsed by default. It's not used that often.

**Comment by Ezeer** [comment]
i think so .

**Comment by elieserdejesus** [comment]
Jon, the proglem in this approach is the "fat master track" :)
If you create 4 channels the region in left side will be large, and the master track will be enlarged too. So the result is a "fat master track".

**Comment by Ezeer** [comment]
@elieserdejesus  and if we use separators in the layout  ?

**Comment by jonjamcam** [comment]
"fat master track".

well I think a boost/attenuator button only for the master could be a better solution?

**Comment by elieserdejesus** [comment]
Ezee and Jon, I can't understand the "separators" and "boost/attenuator" ideas. Please, can you elaborate?
I'm not shure my "fat master track" idea is clear enough, so I spend 15 seconds in Paint (the best image edition software in the world):
![image](https://cloud.githubusercontent.com/assets/1012741/11250763/400c4138-8e15-11e5-98e6-e786b280ebe4.png)

**Comment by jonjamcam** [comment]
yea...not very nice.........You used this solution in the minimode.....to keep space.....can't be use for an extra master track?

![--](https://cloud.githubusercontent.com/assets/1012741/10946389/2c40a854-8309-11e5-8c43-f650c08a215c.png)

**Comment by Ezeer** [comment]
@elieserdejesus  Lol , okay .... beuark ...
![giphy](https://cloud.githubusercontent.com/assets/1283808/11251019/9f35b9a4-8e2f-11e5-813e-9c7fedba2872.gif)

**Comment by elieserdejesus** [comment]
Jon, in the idea is good and avoid the fat master. We can use a scrollbar all time and limit the horizontal space used by input (and master) tracks. 

But in this case we are forcing users with big screens to scrolling, and this is really not good. Imagine you using a big screen, with a lot of horizontal space and Jamtaba showing a scroll for the inputs and master. I'm shure you ask "what?? Why these guys are using a scroll here?"  Hehehe.

**Comment by jonjamcam** [comment]
so.....a very fat master track? and scroll for mini only?

![fattest](https://cloud.githubusercontent.com/assets/15310433/11251353/a6d2959e-8e0f-11e5-81c3-3a8f437771ad.jpg)

**Comment by jonjamcam** [comment]
Another approach could be use use one (-) key for lower master volume in steps (1 or 2 db) and the (+) to increase it .......If there's no space in the fader in the GUI...just a value 0, +4, -6 somewhere just to know what's the actual setting (like the CPU value for example)

**Comment by elieserdejesus** [comment]
Jon, these ideas are very good. I prefer the first idea (the image). The only negative aspect I can see is no horizontal space to write "master" in the top. So maybe some users don't realize this is the master/main track. But is a good solution.

JamKazam guys solved this problem using the same approach used in GarageBand: a horizontal panel used to the "global/main/master" controls.
![image](https://cloud.githubusercontent.com/assets/1012741/11252520/c472ca3e-8e1d-11e5-997e-41262480bd8d.png)

**Comment by jonjamcam** [comment]
Well you seem to have a clear mind on this. On last idea from reaper. They use tabs to switch between mixer and CPU, etc.....so they use the same space...

![reaper tabs](https://cloud.githubusercontent.com/assets/15310433/11252689/4205eb78-8e16-11e5-9677-928688b152c3.jpg)

I know any solution you choose will be elegant...:D

**Comment by elieserdejesus** [comment]
I'm thinking seriously in redesign the user inteface to use a panel in the bottom (like garageBand). This panel will be the "tool panel". In the center we can show the interval progress, show the chord progression, I think this is very clean. In the right (excatly like GarageBand) we can show the master vol (maybe a knob).  I like the record button in GarageBand, we can use this too.

So we have something to work in 2017 :)

**Comment by elieserdejesus** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/1012741/11767445/fc1f37b2-a194-11e5-9f03-06791de29979.png)

**Comment by jonjamcam** [comment]
It looks just great! Very important upgrade. Thx very much, Elieser.
