### ISSUE TITLE
rooms not updating

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#151]
![rooms not updating](https://cloud.githubusercontent.com/assets/15310433/11226540/5f00b65c-8d5f-11e5-9a1d-b9082692a98a.jpg)

**Comment by MagnusDrumsTrumpet** [comment]
yes  not updating

**Comment by jonjamcam** [comment]
It's updating now....

**Comment by elieserdejesus** [comment]
Closing the issue, I think this is solved now.

**Comment by jonjamcam** [comment]
Rooms are not updating often .Sometmes they get stuck for a long tme. To refresh I have to restart Jamtaba.

**Comment by elieserdejesus** [comment]
I experienced this problem some times too, but is a very trick bug, difficult to see "the pattern". Reopening the issue ...

**Comment by jonjamcam** [comment]
mmmm....restarting Jamtaba does not solve the issue now...

**Comment by elieserdejesus** [comment]
I suspect we have come cache problem. I discover a little flag in Qt to disable caching. I'm pushing the change, but I'm not 100% shure this will solve the problem. Let's keep an eye opened for this issue.

**Comment by jonjamcam** [comment]
I'm comparing the new code with 2.0.12 and it's still not updating. I use wahjam to compare

![wahjam-jamtaba new code](https://cloud.githubusercontent.com/assets/15310433/12538675/408ac7c8-c2be-11e5-9cf7-def02dec3bf0.jpg)

**Comment by elieserdejesus** [comment]
The refresh rate can be diferent in each application. Are you taking this in account? JamTaba is updating after 30 seconds.

**Comment by jonjamcam** [comment]
i understand this are different applications. I'm not talking about normal functioning here. Jamtaba works ok most of the time with good refresh rate. The point is the activity of the servers should be reflected with some accuracy. It doesn't make sense to me when this happens (no that often BTW) that wahjam updates almost instantly what happens inside the servers, but jamtaba takes about 1 hour te reflect changes. From a user prespective, if you open Jamtaba you want to jump into a room and jam, but if the server is empty and jamtaba says it's full it's just not working. 

Now the servers are ok as this morning, but who knows why this happens.

**Comment by elieserdejesus** [comment]
ok, I will investigate the problem in some days, I will be without computer or internet in the next week.
