### ISSUE TITLE
Create a download counter in website

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#155]

**Comment by Ezeer** [comment]
Github propose : https://help.github.com/articles/getting-the-download-count-for-your-releases/

**Comment by elieserdejesus** [comment]
this is gold, very nice!

**Comment by Ezeer** [comment]
:+1:

**Comment by Ezeer** [comment]
about the counts , i noticed an historical data for this week that shows that we are on the run : 
![lol](https://cloud.githubusercontent.com/assets/1283808/11249028/c6955fc8-8e24-11e5-8785-1f2e41952047.jpg)

lol !

**Comment by elieserdejesus** [comment]
Downloads counter in website:
@jonjamcam , @Ezeer check this:
![image](https://cloud.githubusercontent.com/assets/1012741/11249298/272c9986-8e0d-11e5-8aca-d925db693a58.png)

**Comment by Ezeer** [comment]
Woaw !
Very nice work elieser , congratulation !

**Comment by elieserdejesus** [comment]
The github api return a download_counter to every asset (zip, installers, etc) in each release. Just the public releases are counted, the alphas, betas, etc are not returned.

I'm just summing all counters:
```
<script>
            $(document).ready(function () {
                $.getJSON("https://api.github.com/repos/elieserdejesus/JamTaba/releases", "",
                        function (releases)
                        {
                            var totalDownloads = 0;
                            for (var i = 0; i < releases.length; i++) {
                                totalDownloads += calculateReleaseDownloads(releases[i]);
                            }
                            $("#downloadCounter").html("<br><p><strong>" + totalDownloads + "</strong> downloads since 10/27/2015</p>");
                        });
            });

            function calculateReleaseDownloads(releaseObject) {
                var downloads = 0;
                for (var i = 0; i < releaseObject.assets.length; i++) {
                    downloads += releaseObject.assets[i].download_count;
                }
                return downloads;
            }
  </script>

```

**Comment by Ezeer** [comment]
what we could next with their api ?
eh eh

**Comment by elieserdejesus** [comment]
My next job with this API is get the closed issues in the latest release and auto build the change log in the site. At moment I'm doing this manually.

**Comment by Ezeer** [comment]
oh ! good idea ! i was browsing the api trying to find inspiration ...
^^

**Comment by Ezeer** [comment]
284 downlooads !
wait ...284-269 = ?
NOT BAD !!
lol
