### ISSUE TITLE
Save Presets

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#156]
I'm working with the help of elieser on a Preset system for Jamtaba .
We gonna use the new configurator class introduced in 2.0.6 to make it  .
Each version ( standalone or plugin ) will have an extra folder named " Presets " with Json files on it .
Elieser had the very good idea  to use the actual track menu ...
![image](https://cloud.githubusercontent.com/assets/1012741/11246183/bd903370-8dfd-11e5-842a-3105117a0eff.png)

to later save and load the presets.

**Comment by elieserdejesus** [comment]
Ezee, just to help a little, look at 
```
LocalTrackGroupView::on_toolButtonClicked()
```

**Comment by Ezeer** [comment]
cool , thank you !

**Comment by Ezeer** [comment]
I remember what you said yesterday about little tasks to preserve mental sanity .
I've found a way to do that here by disabling the new funk to the user so that it can be pushed
without disturbing much ( and show the future features for alpha and beta testers ... )
![presets](https://cloud.githubusercontent.com/assets/1283808/11270101/4f1aced6-8ebc-11e5-8a24-30af6c71d53b.jpg)

Can i push that ?

**Comment by Ezeer** [comment]
well , as said previously , it's better that you decide when merge the branchs , so i just pushed to
configurator branch : https://github.com/elieserdejesus/JamTaba/tree/configurator
Now you can test !
^^

**Comment by elieserdejesus** [comment]
Nice Ezee! Please merge and push directly in master, no problem.

**Comment by Ezeer** [comment]
Ok , we go that way so !
nice .
^^

**Comment by Ezeer** [comment]
This is my actual WIP  : 
![preset](https://cloud.githubusercontent.com/assets/1283808/11274944/93d9ac26-8edb-11e5-910e-94875a88c1d1.jpg)

**Comment by Ezeer** [comment]
Now Jamtaba is able to write a portion of the Json file used as configuration file to a Presets folder .
We need to discuss now what we want to record in that file .

My first attempt was to record the user inputs of the track .
But we can also record more , like Audio or midi devices , etc ...

Let me show you the choice we have , the commented lines are not recorded ( but can be ) : 

     //PRESETS TEST

    void Settings::savePresets(InputsSettings inputsSettings,QString name)
    {
     this->inputsSettings = inputsSettings;
     QList<Persistence::SettingsObject*> sections;
     //sections.append(&audioSettings);
     //sections.append(&midiSettings);
     //sections.append(&windowSettings);
     //sections.append(&metronomeSettings);
     //sections.append(&vstSettings);
    sections.append(&this->inputsSettings);
     //sections.append(&recordingSettings);
     //sections.append(&privateServerSettings);

     //NEW COOL CONFIGURATOR STUFF INSIDE
     if(writePresetFile(sections,name))
     qInfo(jtConfigurator) << "Settings : Presets written :" << name;
     else
     qInfo(jtConfigurator) << "Settings : Presets couldn't be written :" << name;
   }

**Comment by Ezeer** [comment]
I have made my first attempt to use the  load preset option , and as always the result is unexpected : 

![capture-15](https://cloud.githubusercontent.com/assets/1283808/11290354/5a258db4-8f36-11e5-87fb-ab7b57cc7acf.jpg)

lol

**Comment by jonjamcam** [comment]
Great! 6 channels....... no wait!

lol

**Comment by Ezeer** [comment]
ah ah ah ah .... yeah ... you read in my mind .

**Comment by jonjamcam** [comment]
The preset are set for milestone 2.0.8, but the appear in 2.0.7 and they are not working.

?

**Comment by Ezeer** [comment]
they appear grayed to show to the user what will be available in the next release , to give them a preview of new features , and so to stay on touch .
That was my idea for the beta testers  in fact .
