### ISSUE TITLE
enhance the numbers indicating the db level of of the tracks

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#158]
reported by Ancibug: 
Is it possible to enhance the numbers indicating the level of the cursors of the tracks? Probably bigger fonts and also change the color (on the grey background) .  For example black / white or Blue in bold. I really cannot read them. ( i have also glasses)

**Comment by Ezeer** [comment]
( i have also glasses) Thank you for the detail Ancibug .
Do you think that is a case of accessibility ?
We could make a accessibility mode in the view menu , no ?
I'm working on adding the fullscreen Mode view in the menu  actually ...

**Comment by elieserdejesus** [comment]
I think this is a possible case of "color blindness".
The font used to show the track db level is very small, and the text color is not very contrasting. I choose these colors to avoid polute the interface with a lot of rarely used/readed texts. But my idea is draw a db scale and remove the db level text. This "text" approach is not good enough.
