### ISSUE TITLE
Multibytes characters broken in NINJAM chat

### ISSUE THREAD

**Issue by teamikl** [elieserdejesus/JamTaba#159]
Hello, guys.

I got a report from friend, he had tried JamTaba2 VST,
then he met Japanese message in chat was broken.
It shown characters like reported in #122

That was not a font missing problem, as tried
typing English word and translated to Japanese had
shown correct japanese letters.

I have detail and patch, can make PR soon.

Here is the unit test to demonstrate it,
toLatin1/fromLatin1 fail in multibyte case.

https://gist.github.com/teamikl/8e321bc90a6255601ec6

Chat message in NINJAM protocol parser was using toLatin1/fromLatin1.
Patch will avoid the data lost by using utf8 conversion.

## related issue #122

I don't know what is "Cirilic", my patch may solve also #122.
However, need to ask them for test before closing the topic.
so I don't mention to close #122 in commit message.
and that's why I put this as separate issue.

## fromUtf8 is ok? and why utf8

I am not sure this is safe for all cases or not.
JamTaba may recieve non-utf8 strings from another clients,
those will show broken letters. the message encoding are as I remmeber

| software                | encoding                         |
|-------------------------|----------------------------------|
| Ninjam standalone(win)  | native (e.g. cp932 for japanese) |
| ReaNINJAM(win)          | native (the same as well)        |
| ReaNINJAM(osx)          | utf-8                            |
| JamTaba v1              | utf-8                            |
| WahJam                  | utf-8                            |
| ZenJam                  | utf-8                            |

so utf8 is simple and easy solution at this moment.

If there was extra topic, they can be another issue. I can join the discussion.
I can foresee a report like this

> multibytes message from windows client show broken letters

so some of Windows users may want solution by toLocal8Bit/fromLocal8Bit.
But, this is not JamTaba specific problem,
It even happen between official client on Mac <=> Win.

## References

Qt documentation has some more details,
They mentions about latin1 and QByteArray to store raw data.

- [Qt5 QString - Detailed Description](http://doc.qt.io/qt-5/qstring.html#details)
- [Converting Between 8-Bit Strings and Unicode Strings](http://doc.qt.io/qt-5/qstring.html#converting-between-8-bit-strings-and-unicode-strings)

---

Last, late to say its off topic :)
Congraturation new JamTaba release,
I got the news from Doublebass.

Any place you have activity now? skype or facebook or irc.
or ninbot? I had not go for long time, hope to see you soon!

**Comment by elieserdejesus** [comment]
Hi Tea, you are very welcome! 

I choose the toLatin/fromLatin approach because I always have bad results using utf-8 in ninjam. In my tests a run Jamtaba and Reaninjam inside Reaper. Using utf-8 the letters é, á, ç, ã don't work. So I test other codecs and latin do the trick. 
Please try communicate Reaninjam with Jamtaba and you will see the problem. I hope I'm wrong and we can use utf-8 for all users. 
Maybe I'm missing some magic DEFINE in compilation?

Another thing: are you interested in this project as a contributor? It will be an honor to have you participating. You contribute a lot with first Jamtaba version, so will be great if you join in the team.

See you Tea!

**Comment by Ezeer** [comment]
Hi Tea !
It's great to see you here .
Your patch is very welcome , string conversion is a headache for me ...
Thank you for that pearl .
^^

**Comment by jonjamcam** [comment]
Good to see you Tea!

**Comment by teamikl** [comment]
I had forgot to attach the screenshot file
![jamtaba-chat](https://cloud.githubusercontent.com/assets/146129/11269709/1eec99e8-8efc-11e5-82b0-b350846838b2.png)

**Comment by Ezeer** [comment]
Lol tea , it chinese for me !
ah ah ah ah ....

**Comment by teamikl** [comment]
> Please try communicate Reaninjam with Jamtaba and you will see the problem

This is another issue, I know and I explained the encoding in the table.
It's not possible to make all cases success. NINJAM chat has mixed encoding strings.
but no parameter for charset.

about  é, á, ç, ã those letters, I dont know much since I have no chances to use them.
I will try to test them with Latin1/Utf8/Local8Bits

> Another thing: are you interested in this project as a contributor?

Yah, I think license is issue for me. at this moment public repo is Ok enough,
I can test code and send PR :)

**Comment by Ezeer** [comment]
**Yah, I think license is issue for me**
Well , we have started to talk about it in a thread , but none of us is qualified enough to decide to
choose the good one .
Perhaps you could bring some light here too ....
^^

**Comment by teamikl** [comment]
Hi Ezeer, Jon nice to see here

> string conversion is a headache

Yes, for me too. Japanese developers always have to work for that task.

> Maybe I'm missing some magic DEFINE in compilation?

I am not sure this, not following Makefile, yet.
those compiler options are look like option for string literals in source code.

**Comment by teamikl** [comment]
NOTE: edit message moved to explain the screenshot, I forgot attach file on the first post.

**Comment by teamikl** [comment]
Updated string conversion Unit Test https://gist.github.com/teamikl/8e321bc90a6255601ec6

The test result shows:

|           | ascii | extended latin | japanese |
|-----------|-------|----------------|----------|
| latin1    | PASS  | PASS           | FAIL     |
| utf8      | PASS  | PASS           | PASS     |
| local8Bit | PASS  | FAIL           | PASS     |

Mean between Jamtaba2 <=> Jamtaba2 in NINJAM chat, utf8 can pass all cases.
This issue is closed, communicate Reaninjam with Jamtaba can be another issue.

**Comment by Ezeer** [comment]
goood job Tea !

**Comment by elieserdejesus** [comment]
**communicate Reaninjam with Jamtaba can be another issue**
I agree Tea, please create this new issue. This is very important because Reaninjam -> Jamtaba communication is a very common case.
