### ISSUE TITLE
Video chat

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#16]
I was doing some tests online to debug the " BPI 4 " when a ninjam user asked me about a video chat for jamtaba2 . I know some people like it , that could be useful to share finger placements , rolls , smiles , etc ... ^^

**Comment by Ezeer** [comment]
I have found how to connect and acquire video from webcam with Qt : 
http://doc.qt.io/qt-5/qml-qtmultimedia-camera.html

**Comment by elieserdejesus** [comment]
I'm not shure about video codecs in Qt. In last case I think FFMpeg are the right tool for this job.

**Comment by Ezeer** [comment]
What do you imagine for the streaming of the frames with Jamtaba users ?
Peer to peer ? Broadcast from the server incoming streams at user request ( a user has a webcam connected , an other click the button to open the videochat window ?

**Comment by Ezeer** [comment]
I've found that : https://www.virag.si/2012/11/streaming-live-webm-video-with-ffmpeg/
But the server must be on linux only , and works for linux and windows , so mac ...

**Comment by Ezeer** [comment]
If we decide to use QT for that webcam project , we have to deal for with more than one object : 
The QCamera class provides interface for system camera devices.

>QCamera can be used with QCameraViewfinder for viewfinder display, QMediaRecorder for video recording and QCameraImageCapture for image taking.

>You can use QCameraInfo to list available cameras and choose which one to use.

I think there are some useful tasks done by them , but i've seen nothing yet about the codecs being
used

**Comment by Ezeer** [comment]
Ok , i am now in the batcave ... http://doc.qt.io/qt-5/qabstractvideobuffer.html#HandleType-enum

And here is the available formats allowed by QT for video frames types : 
>Identifies the type of a video buffers handle.
**QAbstractVideoBuffer::NoHandle**	0	The buffer has no handle, its data can only be accessed by mapping the buffer.
**QAbstractVideoBuffer::GLTextureHandle**	1	The handle of the buffer is an OpenGL texture ID.
**QAbstractVideoBuffer::XvShmImageHandle**	2	The handle contains pointer to shared memory XVideo image.
**QAbstractVideoBuffer::CoreImageHandle**	3	The handle contains pointer to OS X CIImage.
**QAbstractVideoBuffer::QPixmapHandle	4**	The handle of the buffer is a QPixmap.
**QAbstractVideoBuffer::EGLImageHandle**	5	The handle of the buffer is an EGLImageKHR.
**QAbstractVideoBuffer::UserHandle**	1000	Start value for user defined handle types.

**Comment by Ezeer** [comment]
>The return value of the handle() function may also be used to access frame data using the internal buffer's native APIs (for example - an OpenGL texture handle).

That is may be the right choice to draw the frames in Jamtaba client .
OGL is fast , double or triple buffers etc ...

**Comment by elieserdejesus** [comment]
Ezee, in first Jamtaba versions I do video chat, but only for real time rooms, not ninjam rooms.
I use p2p. The frames are grabbed from webcam and sended directly for other machines. I disable this feature because in realtime rooms upload audio and video is very bandwith consuming. So I focus in audio only.

I never work with cams and video stream in Qt, but I'm shure this stuff is very good in qt. So we can reuse a lot of Qt classes to handle webcams and get the video frames. But I suppose the streaming part is up to us. 
Ninjam protocol don't have a special/custom message to send aditional info, so we can create a new stuff. Probabily we can send video stream only for other Jamtaba users, not for all ninjamers in the same server.

**Comment by Ezeer** [comment]
Ok , thx !

**Comment by elieserdejesus** [comment]
closing by inactivity
