### ISSUE TITLE
VOTE : A new icon for presets in track menu

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#161]
Now that we are a real team ( 3 coders + 1 tester/documentalist ) i prefer ask your opinion before
going ahead and introduce a new resource in the repo .

I have found a free ico here : 
http://www.iconsdb.com/gray-icons/settings-5-icon.html

The license seem to be good , and i like the logo that fit with Presets idea .
I already made the resize : 
![rsz_settings-5-xxl](https://cloud.githubusercontent.com/assets/1283808/11271803/d204a8e2-8ec8-11e5-8941-1d2cc9d10d12.png)

Just waiting your approval ! ( hey ... i am officially the artist/animator in the project , my voice count*2 ? lol .... )
;)

**Comment by Ezeer** [comment]
i just had the 'clever' idea to look in our resource folder , there  is already an icon for that kind of stuff,
(gear.png )
but i prefer ' mine ' .
Can i overwrite ?

**Comment by elieserdejesus** [comment]
Ezee, to ovewrite the icon be carefull with the icon size and the "hover" variation.

**Comment by Ezeer** [comment]
Okay , i don't touch it , it's better to use that ico because it is already in the good format .
You'll see what to do with gear and gearhover later  .
K , i use it in configurator branch so .
can't wait for others , and the voice of the boss count*10 lol !
thx

**Comment by Ezeer** [comment]
I tried to follow your instructions in an other thread , this is what i've understood : 
>About the menu groups: We need put fequently used features are in menu top. I think make sense put the presets in top. To make a preset I need create channels, insert plugins, etc, and save the preset. After created 3 or 4 presets the most used feature will be "load another preset".

>So my suggestion is put the "load preset" in the top and save preset in the 2nd entry.

![presets](https://cloud.githubusercontent.com/assets/1283808/11273567/41dfeffe-8ed4-11e5-89bb-c0bb45458117.jpg)

**Comment by Ezeer** [comment]
other try : 
![presets](https://cloud.githubusercontent.com/assets/1283808/11273690/0483bf0e-8ed5-11e5-974b-4f8e4581fbe9.jpg)

**Comment by Ezeer** [comment]
And for your pleasure  : 
![presets](https://cloud.githubusercontent.com/assets/1283808/11273781/83e78442-8ed5-11e5-9f39-4683dd2fe318.jpg)

**Comment by Ezeer** [comment]
Lastly , a simulation of how it would be when enabled and at startup : 
![presets](https://cloud.githubusercontent.com/assets/1283808/11274103/5b3103aa-8ed7-11e5-82f6-3ac7be5028e2.jpg)

That's pretty cool !
^^

**Comment by elieserdejesus** [comment]
Very good, the last option including the separators is perfect for my eyes.
Working here:
![image](https://cloud.githubusercontent.com/assets/1012741/11279459/fe7650f6-8ed7-11e5-8ada-e91278eb24d9.png)

**Comment by Ezeer** [comment]
Good  Deal , that's perfect for me too .
:+1:

**Comment by Ezeer** [comment]
Wohooooo !! 
>Starting E:\JamTaba\build-Jamtaba-Desktop_Qt_5_5_1_MinGW_32bit-Release\Standalone\release\Jamtaba2.exe...
jt.Configurator.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
default.DEBUG:  MIDI DEVICES FOUND idx: 2   in  0
default.INFO:  "Starting Jamtaba 2.0.7 Standalone (i386) running on Windows XP (i386)"
jt.Configurator.DEBUG:  Path to presets is : "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Presets/testPreset"  in  0
**jt.Configurator.INFO:  Settings : Presets written in "testPreset"**

Historical ! First time ever preset recorded in Jamtaba2 !
well , i must admit that i was running in standalone mode AND that the preset was written in : 

![capture-13](https://cloud.githubusercontent.com/assets/1283808/11288305/305a2a0c-8f23-11e5-9d42-cd4d304646c2.jpg)

It's like if the first mission to mars landed  in ... jupiter .
lol

But enjoy the first preset ever of Jamtaba 2 
[testPreset.txt](https://github.com/elieserdejesus/JamTaba/files/39593/testPreset.txt)
@jonjamcam IT'S ALIVE !

**Comment by jonjamcam** [comment]
YES. I love it! Good job!

**Comment by Ezeer** [comment]
That time i planned "Venus" and we landed in the desired space port  ! 
>Starting E:\JamTaba\build-Jamtaba-Desktop_Qt_5_5_1_MinGW_32bit-Release\Standalone\release\Jamtaba2.exe...
jt.Configurator.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
default.DEBUG:  MIDI DEVICES FOUND idx: 2   in  0
default.INFO:  "Starting Jamtaba 2.0.7 Standalone (i386) running on Windows XP (i386)"
jt.Configurator.DEBUG:  Path to presets is : "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Presets/testPreset.json"*  in  0
jt.Configurator.INFO:  Settings : Presets written : "testPreset.json

![capture-14](https://cloud.githubusercontent.com/assets/1283808/11288677/884b2c0e-8f26-11e5-8ac5-615a54b5fbdf.jpg)

Success !
^^

**Comment by Ezeer** [comment]
Thank you Jon ;)

**Comment by jonjamcam** [comment]
Presets were a must. Thx for this, guys.

**Comment by Ezeer** [comment]
Well , write the file is the easy part .
Read it and assign each control , more difficult .
But i will use the excellent funks that elieser made already to load at startup .
As i know the boss will be curious to know wich way i've choosen to make it  : 

    void LocalTrackGroupView::on_SavePresetClicked()
    {
     mainFrame->getMainController()->savePresets(mainFrame->getInputsSettings(),"testPreset.json");
    }

**Comment by elieserdejesus** [comment]
Nice Ezee, I like this way.
I think here about how ask user for the preset name. A simple approach is [QInputDialog::getText](http://doc.qt.io/qt-5.5/qinputdialog.html#getText)

**Comment by Ezeer** [comment]
Hi elieser  .
Thanks for the tip , i'm gonna try that now .
^^
