### ISSUE TITLE
Add "Reset Track " option in track's menu

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#162]
I think we could add that option , to reset in a hurry a track .
Imagine we are in " panic " with a track , just click reset and calm is back !

**Comment by Ezeer** [comment]
Something like that  : 

![capture-1](https://cloud.githubusercontent.com/assets/1283808/11302264/a4ce4534-8f9c-11e5-9a42-89d9c93382d2.jpg)

**Comment by elieserdejesus** [comment]
Make sense, and usefull too for create another preset from scratch after using a preset using 4 subchannels and a lot of inserted plugins.

**Comment by Ezeer** [comment]
yes !

**Comment by Ezeer** [comment]
So i made good progress , i can now reset the midi and audio devices to none ,
reset the audio nodes vol,pan,boost to 0.0f 
But i have to reset the gui also ...
commit is here : https://github.com/elieserdejesus/JamTaba/commit/e2e5658a474fb618aea04994f5d09c249f018b59

**Comment by elieserdejesus** [comment]
I comment about the model->view updates in the commit Ezee.

**Comment by Ezeer** [comment]
seen , thx !

**Comment by Ezeer** [comment]
@elieserdejesus Can you please give me ( again ... ) the right reset values , for everything , this time ?
So that i could code them quick .

**Comment by elieserdejesus** [comment]
Gain: 1
Boost: 1
Pan: 0

Gain and boost are multipliers, if you use you are multiplying by zero. Maybe this is your problem?

**Comment by Ezeer** [comment]
lol , you prefer i insert a divide by zero in your master somewhere ?
NAN...

i try your values and push on configurator is it's fine .
wait , frank is midi aware ... i will update the little monster first .
thx !

**Comment by jonjamcam** [comment]
frank!

-![](http://cdn.collider.com/wp-content/uploads/Frankenweenie-image-11.jpg)

**Comment by Ezeer** [comment]
ah ah ah ! very good !
woof !
![9893974054f0f23a04c04d_bebe_chewbacca](https://cloud.githubusercontent.com/assets/1283808/11326515/d3c00578-916b-11e5-97b6-07ec015fc179.jpg)

**Comment by Ezeer** [comment]
Done : https://github.com/elieserdejesus/JamTaba/pull/187
