### ISSUE TITLE
Improve the meter curve values 

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#164]
hey you gus working fine on all that )))Thy
 as i played more often with jamtaba i felt thet the levels of incomming ppl often are very high
it works to level all but you have oten put them down very much and the faderposition does not always show the same meter range i felt somehow not so direct in level as fader it seems   hard to explain

greets from Mag

**Comment by Ezeer** [comment]
Hi magnus .
Yesterday i had a vision of mooving faders in Jamtaba , updating their positions to the right volume ,
a kind of mix with a limiter and the automation of a motorized console : 
https://www.youtube.com/watch?v=jJ1dhTtSU2A 

Weird that you talk about that today ....
Maybe my dream will become true .

dreaming apart , elieser coded that part so he will better explain what's goin on with the volumes .

**Comment by MagnusDrumsTrumpet** [comment]
i already have an M-Audio Projectmix I/O   looove it   reaper works like acharme with it 
my dream ??? 
here would be to be able to switch from the reapertracks also to the vst jamtaba faders  wow 
 the i could handle all players with my hardware fader  aaaand could read their names in the display of my console in yellow  ))))))))))))))

**Comment by MagnusDrumsTrumpet** [comment]
btw it has 8 fader and one main fader hehe
motorized and works somehow with that hui driver protocoll from mackie

**Comment by Ezeer** [comment]
I am interested to work on that magnus .
I have started to work on joystick support , and my goal was to enable control io with that kind of stuff later .
My joystick thread : #67

**Comment by MagnusDrumsTrumpet** [comment]
![projectmix](https://cloud.githubusercontent.com/assets/15855828/11313983/a09cd7e2-8fe1-11e5-9809-7b16e1610820.jpg)

**Comment by Ezeer** [comment]
yeah , i was trying to download a mackie sdk but all i got is a trojan ...
the protocol interest me , if you got info please share magnus .
but in an other thread please ( and let me kill that f***** trojan first ^^ )

**Comment by MagnusDrumsTrumpet** [comment]
it must be in reaper you can load an controllerinterface there 
i am sadly no programmer
 but ther is some community in reaper forum and a guy who wrote the controller driver to load it in reaper

**Comment by MagnusDrumsTrumpet** [comment]
http://forum.cockos.com/showthread.php?t=81818&highlight=projectmix
it is this guy called   Klinke

**Comment by Ezeer** [comment]
nice ! thank you .
I think i'm gonna start with generic control surface for Jamtaba , following my Joystick controler.
I've just found a git project that implement that for sonar , i think i could grab some stuff here : 
https://github.com/Cakewalk/Cakewalk-Control-Surface-SDK

And see what MCU midi protocol is also .

**Comment by MagnusDrumsTrumpet** [comment]
in reaper it is done here
![image](https://cloud.githubusercontent.com/assets/15855828/11317924/6e96990a-903f-11e5-976f-ad41d3077a26.png)
and looks like this
![image](https://cloud.githubusercontent.com/assets/15855828/11317935/afcff358-903f-11e5-8d7b-9f5bca4846ee.png)

**Comment by MagnusDrumsTrumpet** [comment]
there you can see alot already implemented protocols to choose origin in reaper and also OSC
for lets say android virtual console controllers 
 also very interresting )

**Comment by Ezeer** [comment]
Last year i planned to buy the behringer BCF2000 but i run out of money .. lol .
i think i should own a control surface before start to code for it .
But automation is something that i want to learn , and that can work before having a control surface.
Because it's the software that drives the controler in that case .

So back to your volume problem , can u describe better your need ?
:)

**Comment by MagnusDrumsTrumpet** [comment]
yeah )
lets say the elation of shown meter and position of fader isnt that equal 
 sometime fader really up but not much level of meter
 as i felt 
 sure it depends on level of person comming in
but i think it is to far away from each other

**Comment by Ezeer** [comment]
mmm... so you feel that there is no NORMALIZATION ?
i am talking about https://en.wikipedia.org/wiki/Audio_normalization

**Comment by jonjamcam** [comment]
Magnus, have you experimented with the Boost/attenuators before mixing? (Lower right corner below)

![](https://cloud.githubusercontent.com/assets/15310433/11015982/2ce7cb0c-8552-11e5-8ff0-b3e8887a22fd.jpg)

**Comment by MagnusDrumsTrumpet** [comment]
thy jon )
well i hold them at zero as i think it should be leveled neutral

**Comment by jonjamcam** [comment]
Yea...If someone is too "out of mix" first try to level him wth these buttons, then use the fader. It's for me a fast way to get a better mix

**Comment by elieserdejesus** [comment]
Guys, the boost is very usefull to correct bad mixes, I use a lot too. 
But Magnus is right, the meters are not 100% good. If I remember correctly the meters are showing in a exponencial curve. The high levels are high, the low levels are low, but the mid levels are too much low. I will check this soon and try some "more natural" curve for the meter values.

**Comment by MagnusDrumsTrumpet** [comment]
yes sound like that but no tragic thing )))

**Comment by teamikl** [comment]
This is a github tip
How about use this commit message format?
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by elieserdejesus** [comment]
Wow, very usefull tip, thanks Tea!
