### ISSUE TITLE
impossible to enter in a room after leaving room

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#166]
Running jamtaba2 in reaper theres a strange things happen.
When leaving a room it takes a long time no more seing my name ( long refreshing ?) and it is impossible some times to come back in any room . Even removing and adding the vst jamataba . The only things making possible to come back is to quit reaper and coming back after .
In version 2.04 it was very often in 2.05 it was ok , in 2.06 same problem come back.

Thanks for your improvement nice guys!!

**Comment by Ezeer** [comment]
Salut , ce bug est répertorié mais coriace .
Peux-tu me fournir le log après la manifestation du problème ?
( copier/coller çà ira .... )
Et quelle version utilises-tu STP 2.0.5 ou 2.0.6 ?

**Comment by DoublebassOO** [comment]
Salut Ezzee  cela fait un moment qu'on a pas jouer ensemble !! Je me rappelle tes incitations toujours positives  !!  Jamais eu de supporter comme toi depuis  :) !!

rappelle moi comment copier le log j'ai un trou....

a tout bientot!  Ravi de te voir dans l'equipe de developpement  !!

**Comment by Ezeer** [comment]
Ben oui je suis bien content de te retrouver aussi ^^ eh eh eh .
Pour le log , tu vas voir dans 
![capture-1](https://cloud.githubusercontent.com/assets/1283808/11312702/33fbb9e0-8fd8-11e5-9dc3-79ed87cbd4dd.jpg)

Coté copains , Tea est entré dans l'équipe hier !
çà va swinguer !
lol

**Comment by DoublebassOO** [comment]
tu peux aller eventuellement sur  le chat
http://makeitezeeah.esy.es/jamtabachat/

sinon je me connecte dans ninbot.com 2049 fait moi un coucou a ce niveau

a+

merci

**Comment by DoublebassOO** [comment]
J'ai la version  2.0.6  voilà le bug est réapparu ...

le chemin sous win 7  C:\Users\Pierre\AppData\Local\Jamtaba 2

mais que veux tu que je copie ?  le log c'est uniqt du texte que voici 

default.INFO:  Reading settings from  "C:/Users/Pierre/AppData/Local/Jamtaba 2/Jamtaba64.json"
default.INFO:  "Starting Jamtaba 2.0.5 VST Plugin (x86_64) running on Windows 7 (x86_64) running in Reaper"

cela va pas t'aider

**Comment by DoublebassOO** [comment]
il y a un autre log dans le dossier vst   

jt.Configurator.INFO:  Reading settings from  "C:/Users/Pierre/AppData/Local/Jamtaba 2/PluginVst/Jamtaba64.json"
default.INFO:  "Starting Jamtaba 2.0.6 VST Plugin (x86_64) running on Windows 7 (x86_64) running in Reaper"
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.DEBUG:  intervals discarded  in  0
default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0

default.CRITICAL:  GUID is not in map! 0


montre des erreurs semblerait - il  mais est ce  cela que tu me demandais ?

**Comment by Ezeer** [comment]
Tout à fait .Merci !
Nous avons mis au ponit un systeme poussé de debuggage auquel nous invitons nos testeurs
à utiliser .
Pour cela , tu dois editer le fichier logging.ini et mettre tout =true .
Exemple : 
jt.Ninjam.Core=true
jt.Ninjam.Protocol=true

Permettra de voir ensuite dans le log le suivi des operations relatives à ninjam dans Jamtaba .
Donc STP fais çà , et au prochain bug nous aurons plus d'infos ciblées .
Merci !

**Comment by Ezeer** [comment]
fais gaffe aussi par rappot au log : Si tu utilises le plugin , il sera dans le dossier PluginVst .
Sinon le standalone se trouve à la racine de Jamtaba 2 .

**Comment by Ezeer** [comment]
@elieserdejesus  what do think about that ?
default.CRITICAL: GUID is not in map!

**Comment by Ezeer** [comment]
Cela m'a permit de trouver la source de ce message dans Service.cpp
void Service::handle(const DownloadIntervalWrite& msg){
    if (downloads.contains(msg.getGUID())) {
        Download* download = downloads[msg.getGUID()];
        download->appendVorbisData(msg.getEncodedAudioData());
        User* user = currentServer->getUser(download->getUserFullName());
        if (msg.downloadIsComplete()) {
            emit audioIntervalCompleted(*user, download->getChannelIndex(), download->getVorbisData());
            delete download;
            downloads.remove(msg.getGUID());
        }
        else{
            emit audioIntervalDownloading(*user, download->getChannelIndex(), msg.getEncodedAudioData().size());
        }
    } else {
        **qCritical("GUID is not in map!");**
    }
}

C'est un bon début de piste .
This a good starting point .

**Comment by DoublebassOO** [comment]
afin d’éviter  ce fastidieux travail  je recopie cette modif du login , pour les prochains suffira un copier coller

[Rules]

#these are the logging rules. Change a rule to "true" to activate. For example, to se the
#details about VST plugins scanning change the line below to jt.Standalone.PluginFinder=true

jt.Standalone.PluginFinder=true
jt.Audio=true
jt.Midi=true
jt.Core=true
jt.GUI=true
jt.Ninjam.Core=true
jt.Ninjam.Protocol=true
jt.LoginService=true
jt.JamRecorder=true
jt.IpToLocation=true
jt.Ninjam.GUI=true
jt.Ninjam.VorbisEncoder=true
jt.Ninjam.VorbisDecoder=true
jt.Ninjam.RoomStreamer=true
jt.Standalone.VstPlugin=true
jt.Standalone.VstHost=true
jt.VstPlugin=true

#*.debug=true
#*.info=true

#supressing ssl warnings
qt.network.ssl.warning=true

**Comment by elieserdejesus** [comment]
**Perhaps showing that he is still connected to the previous server ?**
Exactly Ezee, It's my first suspect too. I will check this soon.

**Comment by DoublebassOO** [comment]
the log file "after the true" :)   is too big 69 mo  i will try to send it with gmail

**Comment by DoublebassOO** [comment]
Another question   after  all this "true" added  lot more bugs  seems (impossible to mute, chat very long  ,..)

is it me or ??

**Comment by Ezeer** [comment]
C'est normal , on demande à jamtaba de décrire tout ce qu'il fait .
Remet tout à false , sauf  : 
jt.Ninjam.Core=true
jt.Ninjam.Protocol=true
jt.LoginService=true
jt.VstPlugin=true

s'il te plait .
^^

**Comment by elieserdejesus** [comment]
I'm 99% shure this is solved in #8

**Comment by Ezeer** [comment]
![chris-hemsworth-joins-cast-all-female-ghostbusters-reboot-](https://cloud.githubusercontent.com/assets/1283808/11321084/afe504b0-90b1-11e5-9fb7-c7287e2f8dab.jpg)
