### ISSUE TITLE
"Quit" in jamtaba vst dont work in  v2.06 

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#167]
when choosen it go the recording page settings;

**Comment by Ezeer** [comment]
ah ah ah !
Merci pour ce retour , en fait un VST ne peut pas quitter .
Tu peux juste utiliser l'hôte comme tu fais d'habitude avec d'autres vst .
Nous devons enlever ces options pour Jamtaba version plugin 
C'est donc un oubli de notre part .

@elieserdejesus Can you hide or disable  Quit in VST version ?

**Comment by elieserdejesus** [comment]
done!

**Comment by Ezeer** [comment]
Thanks !
^^

**Comment by DoublebassOO** [comment]
great !
