### ISSUE TITLE
is it possible to let the version of jamtaba visible 

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#168]
even in help menu

**Comment by Ezeer** [comment]
Yes , it is possible .
where would be your preference ?
The help menu witha traditional about is a common choice ....

**Comment by DoublebassOO** [comment]
yes would be perfect

**Comment by elieserdejesus** [comment]
Hi Double, in standalone the version appear in the window top bar. I'm supposing you are talking about  VST plugins, right?

**Comment by DoublebassOO** [comment]
Hey Elieser 
Yes of course ,  i will take care to precise it more the next time

**Comment by elieserdejesus** [comment]
No problem Double, I was just confirming my supposition.

**Comment by DoublebassOO** [comment]
nice
