### ISSUE TITLE
Midi CC implementation for vst plugins' Knobs and Faders

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#169]
Hi guys. Jamtaba is right now a very complete app, but some midi implementation is still missing. I happen to control a lot with MIDI CC and still for some complex setups I have to return to reaper which I really don't like anymore. So I think two implementations are important in this stage:

1.- vst plugins receive MIDI
2.- midi control for volume, metronome, individual musicians, boost/att, pan, etc...

I hope this is not too difficult to implement and it will make Jamtaba complete with regards to my personal jamming experience. I happen to talk as a drummer in this issue and  I understand it's not that critical for other instruments :D

**Comment by elieserdejesus** [comment]
Jon, can you elaborate the first item (vst plugins receive MIDI)? At moment the plugins are receiving midi, we can use VSTis. Are you talking about plugins receiving midi CC?

About 2: we are working in this thinks. Ezee start some work to allow joystick and we discuss some possibilities to extend this feature and allow control jamtaba tracks using midi CCs. Im my last experiment I was rotating a knob in my midi controller and moving the Jamtaba first input track fader.  I think we have 40% of the solution done, the next challenge is how map CCs to Jamtaba controls.

**Comment by jonjamcam** [comment]
Yes I mean assignable MIDI CC for the knobs. I know this could be not that easy....

**Comment by Ezeer** [comment]
Actually , frankeinstein #177  react to modulation wheel on my keyboard and i control the master volume
of track 1 .
That is pretty fun !

I think we will make huge progess on that soon .
:+1:

**Comment by elieserdejesus** [comment]
Jon and Ezee, I was thinking in a "more easy" way to do this mappings. I like use the "right mouse" button and explore the context menu. All music software use this a lot, so Jamtaba users are probabily used with this approach. 

Imagining a common scenario: **You need control the metronome volume using your midi controller.** 
1. Right mouse click in metronome fader, 
2. Jamtaba show a menu with 2 options "map to control"  and "learn". 
3. If you put mouse over "map to control" a secondary menu (like Jamtaba inputs selection) is opened showing the possible (free to map?) controls.
4. If you click in "learn" Jamtaba enter in a "learning" state, waiting for the first midi CC received and auto mapping.

**Comment by Ezeer** [comment]
Deal !

**Comment by jonjamcam** [comment]
You have my blessings on that one, Boss!

although I think the learn is enough....

**Comment by elieserdejesus** [comment]
Jon, I prefer "learn" too, it's easy and quick. But I have some problems using midi learn in plugins and other software, and sometimes the map need be manual. So I think is good add the 2 possibilities in Jamtaba just to be shure users can do the mapping.

**Comment by jonjamcam** [comment]
Sure. Is your midi map idea like this when you click a knob?

![knobs midi](https://cloud.githubusercontent.com/assets/15310433/11326253/9ec8ad70-9143-11e5-9403-134b678841f9.jpg)

**Comment by Ezeer** [comment]
i let elieser answer to you for the question about .
About the 3.0.0 milestone  : 

I think we could have midi cc support for Jamtaba tracks before , say from 2.8 .
Then update 'til full support ( including vsti ) in 3.0

**Comment by jonjamcam** [comment]
good, but 2.8 will be available in 2020? right?

:D

**Comment by elieserdejesus** [comment]
Exactly Jon, your image is excatly what I'm thinking.

**Comment by jonjamcam** [comment]
It's from the hypersonic module. Clever way to map the 8 knobs. No learn function!

![](http://img.audiofanzine.com/image.php?lang=fr&identifier=id&size=normal&module=product&product_id=15578)

**Comment by Ezeer** [comment]
i just tested 2 DSK vsti that can learn midi cc , DSK Brass and DSK B3x .
So the plugins already receive midi cc ...

**Comment by elieserdejesus** [comment]
Shure, we are not filtering the midi messages passed to Vst plugins. If a plugin receive a note on/off the CCs will work too. 

the "UnLearn" is a very good thing, we need this too. :)

**Comment by Ezeer** [comment]
So i think it is irrelevant to code midi learn for vst(i) that don't provide it .
If vst(i) are midi cc aware , user control surface works .
So it is to the user to choose the right plugin for what they need .
I will work on jamtaba controls only .

**Comment by jonjamcam** [comment]
"If vst(i) are midi cc aware , user control surface works ."

Ezee there are vst plugins that are not vst(i) like compressors or effects in general. These are not instruments but it's necessary for them to be able to be controlled by midi.

**Comment by Ezeer** [comment]
Yeah jon , but same for vsti , it is to the vst author to make their plug midi cc aware .
Perhaps we should make a list of them ?
Then we'll decide what to do .
;)

**Comment by Ezeer** [comment]
list of midi cc aware : 
+ http://www.fabfilter.com/products/pro-c-2-compressor-plug-in

**Comment by jonjamcam** [comment]
I use t-racks and izotope ozone. I can control them via CC in reaper, but not in jamtaba

**Comment by Ezeer** [comment]
Okay , i'll test master here , perhaps as i'm working on dev branchs i have a support that you don't 
already have .
Perhaps they use also non-conventional cc ?

**Comment by jonjamcam** [comment]
they are traditional vst effects......most are! Even reaper own plugs are capable of cc remote control

**Comment by elieserdejesus** [comment]
Jon and Ezee, maybe we are taling about related, but different things. Many VST plugins are exposing your "attributes" to DAWs, so a DAW can create a automation, for example. Jamtaba is not using these "exposed attributes" from plugins, because I suppose (in the beginning) we don't need this features in Jamtaba. But now I think this can be usefull, not for automation, but for live control.

Jon, you say ** I use t-racks and izotope ozone. I can control them via CC in reaper, but not in jamtaba**. Can you elaborate? You click in the plugin GUI, and ... ??

**Comment by jonjamcam** [comment]
ok. In order to control the parameters of these VST plugin effects I have to tell the host what CC I'm using first. Do not confuse with the learn that some vsti have like KONTAKT. It's differen't. It's the host (in my case reaper) who "learns" the CC and maps it into the plugin. For example:

This is T-racks VST opened in one reaper track. the plugin has no learn nor map midi, but reaper's window has a learn function and shows me all the parameters that can be used:

![t-racks cc](https://cloud.githubusercontent.com/assets/15310433/11344205/a3fabc92-91ee-11e5-8991-5cfa335b5588.jpg)

**Comment by Ezeer** [comment]
Ok , i got it  !
It is a cool feature to implement finally .
^^

**Comment by elieserdejesus** [comment]
I confirm my suspects :)
These are not common midi CC handled by the vst plugin directly. In this case Reaper is mapping a CC to a VST plugin parameter. The parameter list is exposed by plugins, and the parameter list can be empty (this is the case in Reaninjam and Jamtaba). In general a empty parameter list means "you can't automate this plugin controls".

About Jamtaba: we can read VST parameters from each plugin and map a selected parameter to a midi CC, exactly as Reaper.  This can be usefull and add more flexibility for users.
Another cool thing is export/expose parameters (faders, pans, mutes, solos) in Jamtaba VST plugin, so the plugin users can change Jamtaba controls using CCs inside Reaper or another capable DAW.

**Comment by jonjamcam** [comment]
Just a little history. I was very active back in '98 when this "NEW VST" thing was created. It was possible with the appearance of the Pentium processor. Take a look at the Cubase VST Manual in 1998. This was the beginning of the age we are living now as a given:

![cubase 3 7 manual processor page](https://cloud.githubusercontent.com/assets/15310433/11345077/b7e189d4-91f3-11e5-8822-5865a7a18f95.jpg)

And this is what it looked like the first VST implementation:

![cubase 3 7 manual effects page](https://cloud.githubusercontent.com/assets/15310433/11345127/e01747d6-91f3-11e5-9bca-cb40bb706a19.jpg)

As you can see at this point there was no VSTi. That came later with the success of VST combined with ASIO that steinberg also created. This guys invented our present world!

**Comment by Ezeer** [comment]
**This guys invented our present world!**
icon 'Trash' ? lol

**Comment by jonjamcam** [comment]
Sadly I'm with you on that one, Ezee :(

**Comment by Ezeer** [comment]
I was also making a reference with one thread , where 'trash' icon was too much .
These guys worked with high tech on high tech , that's all .
The world is bigger than some circuitry ...
But it is good to work on something with and for someone .

I understand your idea about the respect for those worked before us on all that ... shit .
lol !

**Comment by jonjamcam** [comment]
It's more understand how this stuff grows bigger and bigger from a very tiny, but robust implementation. I must have read that whole manual several times and finally in 1999 I saved some money and bought my own custom PC with that specific implementations and Cubase worked like a charm. 8 mono tracks and plenty of FX. This idea Made a market

 Remember where we were coming from: Expensive studios on one hand and really bad home recording quality using 4 track cassette portastudios on the other. The time when the mp3 format was in it's first stages. All that was only 18 years back.

What we have now in a laptop was unthinkable in a workstation back then

**Comment by Ezeer** [comment]
yeah , i am happy to work on that .
And to not be alone .
^^

**Comment by jonjamcam** [comment]
sorry guys......made a mistake changed the milestone.......fat fingers :D

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
