### ISSUE TITLE
Scan VST plugins in a separated process to avoid crash when scanning

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#171]
http://www.cantabilesoftware.com/blog/posts/40-Robust-Plugin-Scanning

**Comment by Ezeer** [comment]
good project .

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test the plugin scan in the last release (2.0.7 beta)? Now the plugins are scanned in a separated process. Please test with a "bad" plugin. When scanning a bad plugin the scan process crash, but the Jamtaba process keep running.

**Comment by Ezeer** [comment]
that's cool elieser .
Perhaps you can keep a track of the bad vst in JTB process and add it in the blackbox ?
Or you already have done it ?

**Comment by jonjamcam** [comment]
Works better as jamtaba is isolated, but I had a crash of the separate process vstscanner. 

![vstscan crash](https://cloud.githubusercontent.com/assets/15310433/11432681/3df326fe-9492-11e5-8860-47ad78d75dcf.jpg)

**Comment by Ezeer** [comment]
pretty cool !

**Comment by elieserdejesus** [comment]
Jon, the VstScanner crash it's normal, but in windows 8 the process crash silent without this annoying screen. 
What happens after VstScanner,exe crash?

**Comment by jonjamcam** [comment]
I'm on win7 x64, the crash window just closes and a text appears saying it will blacklist the plugin, then I'm on the preferences/vst window again with no more problems

**Comment by elieserdejesus** [comment]
Jon, about the icomplete scan: when a bad plugin is loaded the VstScanner.exe process crash. The scan is interrupted, but the "bad" plugin is black listed. If you "Refresh" your plugins the VstScanner run again, and now the bad plugins is skiped.

**Comment by jonjamcam** [comment]
I'v been unable to run the scan a second time. The process is consuming all my resources. I have 4gb ram only and I don't use a swap file. Windows consumes about 1.5-2.5 GB and the scanner is is using about 1 GB by itself, so I can't test it completely in my win7.

I'll try later the win10 laptop and report.

**Comment by jonjamcam** [comment]
Testing the memory issue in 2.0.7 and now it works ok. No excessive memory used. Good job!
