### ISSUE TITLE
crete a way to disable the "preparing for transmit " in the preferences

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#173]
Jon: I think there should be a way to disable it in the preferences menu, but it has to be enabled by default during install.

Is interesing allow users to choose a number of intervals to wait for transmit. Some users need more time to "be prepared". A simple text input allowing only number from 1 to 4?  I think 4 intervals at max is enough.

**Comment by jonjamcam** [comment]
I agree. We could use 0-4 for a range (0 meaning disable, for example) and in the preferences add an option to set this default by the user. Installation can set it to 2.

**Comment by jonjamcam** [comment]
I've been testing this feature for some days now and my opinion is that It's not necessary to add a disable button in the preferences. Jamtaba's first two intervals are always empty. Let's see what users think about it. My bet is they'l love it!

**Comment by elieserdejesus** [comment]
I agree. 
Actually I see many times the third interval is useless too :)  Let's see if we have some feedback about this, I will close this issue for while, we can reopen if necessary.
