### ISSUE TITLE
"Disable button" needed for the chords function

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#175]
Sometimes after we had a jam wit chords and switch to "free mode" with no structured progression, there's no button or command to delete (or "hide") the previous chords.

**Comment by elieserdejesus** [comment]
Make sense. Maybe a button with a trash icon?

**Comment by jonjamcam** [comment]
trash? Icons are a funny thing...lol

**Comment by jonjamcam** [comment]
a hide icon?

-![](http://www.meetchaos.com/resources/images/hide.png)

**Comment by elieserdejesus** [comment]
I'm not shure it the "hide" is the best metaphor, because after "hide" a chord progression probabily you will not "show" this progression again. So I think the good metaphor is "discard" the chords.

**Comment by jonjamcam** [comment]
ok I agree, It's just I don't like the "garbage" analogy

**Comment by elieserdejesus** [comment]
Agree, the trash icon is too much :)

**Comment by elieserdejesus** [comment]
done! A quick feature :)

**Comment by Ezeer** [comment]
tried to merge master with frank , merge issue  : 
>Salon@salon-d59g9e2l8 MINGW32 /e/JamTaba/Client (frankeinstein)
$ git merge master
Auto-merging Client/src/resources/jamtaba.qrc
CONFLICT (content): Merge conflict in Client/src/resources/jamtaba.qrc
Auto-merging Client/src/gui/MainWindow.h
Auto-merging Client/src/gui/MainWindow.cpp
Automatic merge failed; fix conflicts and then commit the result.

i'm gonna try to fix
