### ISSUE TITLE
2.0.7 alpha presets are grayed out 

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#176]
![save-load grayed out](https://cloud.githubusercontent.com/assets/15310433/11325231/0bc7c432-9127-11e5-9df7-2024292763c1.jpg)

At least LOAD should be always available.

**Comment by elieserdejesus** [comment]
Ezee is finishing this job, we will test this feature in the beta.

**Comment by Ezeer** [comment]
yeah man !
The actual state is FRANK EINSTEIN : #177 
![capture-3](https://cloud.githubusercontent.com/assets/1283808/11325460/cf6f5400-914e-11e5-998c-b9f6f2ef45ac.jpg)

**Comment by jonjamcam** [comment]
Keep it up frank!

**Comment by Ezeer** [comment]
![young frankenstein](https://cloud.githubusercontent.com/assets/1283808/11338942/3b309ac0-91f7-11e5-8c52-208170fa7a48.jpg)

lol ...
