### ISSUE TITLE
Frank...einstein

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#177]
You know i am a crazy inventor .
With the help of a friend , we just created the magic : 
Merging of midi branch with configurator and master gives : 
https://github.com/elieserdejesus/JamTaba/pull/178

My soul sister sing for his birthday : 
https://www.youtube.com/watch?v=UhgqV6TPQQc

please help give some love to frank !
:heartbeat:

**Comment by jonjamcam** [comment]
Frank is closed? Presets still not working in beta 2.0.7

**Comment by Ezeer** [comment]
Frank is forked  : https://github.com/Ezeer/JomTobo/tree/frankeinstein
I'm working on presets actually , stuck with plugins load .
They load and works but the app crash on exit .
https://github.com/Ezeer/JomTobo/commit/4e4fd86a0231f9d6bb6cb165213f12441c99945a

**Comment by jonjamcam** [comment]
Fork? What does this mean, Ezee? Jomtobo is a sepatate project?

**Comment by Ezeer** [comment]
Yes , i make my own experimentations in a separate project now .
