### ISSUE TITLE
Should Full screen mode be saved after close?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#179]
Other software don't save the full screen configuration and so does Jamtaba, but could it be a nice thing just to launch the app and it goes full screen automatically when previoulsy selected?

Quitting th app in full screen mode is possible with the ESC key. This is different than opera or pdf viewer that forces you to get out of full screen first (unless you use alt+F4 in which case the full screen is not retained either)

related thread https://github.com/elieserdejesus/JamTaba/issues/140#

**Comment by Ezeer** [comment]
**Other software don't save the full screen configuration and so does Jamtaba, but could it be a nice thing just to launch the app and it goes full screen automatically when previoulsy selected?**
for me it would be perfect .

**Quitting th app in full screen mode is possible with the ESC key.**
Yeah , we think and do at light speed here .

The solo captain need to escape the empire often lol ...
![sideshow-hot-toys-millennium-falcon-picture-2](https://cloud.githubusercontent.com/assets/1283808/11326578/73abadca-916d-11e5-8555-4d6d9d3c4053.jpg)

**Comment by elieserdejesus** [comment]
I think this can be a good thing. Can you take this Ezee?

**Comment by Ezeer** [comment]
yes . ( appreciate the short answer )
^^

**Comment by Ezeer** [comment]
@elieserdejesus  u want it in master ? duno how plugin will react ...

**Comment by elieserdejesus** [comment]
Ezee, push to master, I will check the plugin after you push.

**Comment by Ezeer** [comment]
ok . Reads fine at startup  , fullscreen works , but i fail to write on exit ( const var shit ! lol ... )

**Comment by Ezeer** [comment]
![giphy 2](https://cloud.githubusercontent.com/assets/1283808/11328294/ac31ce30-9187-11e5-88ec-3fb76f9983ff.gif)

that kind of shit that make me crazy :

>E:\JamTaba\Client\src\gui\MainWindow.cpp:1223: erreur : passing 'const Persistence::Settings' as 'this' argument of 'void Persistence::Settings::setFullScreenView(bool)' discards qualifiers [-fpermissive]
           mainController->getSettings().setFullScreenView(false);



                                                                ^

**Comment by elieserdejesus** [comment]
getSettings() is a const method, is returning a const reference. This means getSettings can't change the state of the object, can't change the values of members. Setters can change the state, getters in general don't change, just return or calculate and return. 

You are taking a const reference calling getSettings() and after this trying call SetFullScreenView, a setter method.  You can't change the settings state in this way, this is about const correctness.

Try add a new function in MainController:
```
MainController::setFullScreenView( bool fullScreen );
```
Inside this new method you can access the settings instance inside MainController and store the new value.

**Comment by Ezeer** [comment]
thx , i try that , too much tired to think right now .

**Comment by Ezeer** [comment]
Done .
![giphy 1](https://cloud.githubusercontent.com/assets/1283808/11328453/2ffd28d8-918b-11e5-8dbb-497cd76ab557.gif)
