### ISSUE TITLE
Bad sound loop/freeze

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#18]
OS: WinXp SP3 Driver: Asio4all 512 sample 44100htzSound card : Sound card : Realtek AC97 Audio Codec :ALC850
When i listen to a room , if my track is not muted , when i switch to enter , there is an audio freeze that loops , could kill the ears , headphones etc ...

**Comment by Ezeer** [comment]
This is not a bug but a bad configuration of a mainboard soundcard .
I fixed my Pc , not the software .
Mwah ah ah !
