### ISSUE TITLE
Latency compensation implementation when using direct monitoring

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#182]
I have a ME-25 Pedal connected to th PC  via usb. The problem is that I can't disable the monitor input in the pedal and if I mute Jamtaba's channel it won't send it to the room. So I'm stuck with this duplicate sound that is really an unwanted FX.

So in ninjam and reaninjam I can solve this simply by muting the channel, but Jamaba is designed different, so I'm thinking for the average guy who just connect via usb there should be a preference to be able to mute the channels, but the sound to continue going to the room. Something like advanced (mute affects local channels only)

**Comment by Ezeer** [comment]
Are you using the ME-25 Pedal asio driver ?
![capture-1](https://cloud.githubusercontent.com/assets/1283808/11375284/b40d0dfa-92da-11e5-866d-28666d1713de.jpg)

**Comment by jonjamcam** [comment]
yes

**Comment by Ezeer** [comment]
Can't u use an other driver for Jamtaba ?
And use your phone output to the inputs of your alternate audio device ?

**Comment by jonjamcam** [comment]
Sure I can use my laptop asio4all, But I think many guitar players connect like this and listen to the jam via the pedal. Sounds really good and few connections and setup are needed.

**Comment by Ezeer** [comment]
If you use tricks to make it work on other softawres that mean that your pedal was not designed to work like this . I understand that it would be nice to work like this ( plug and play ) , but your pedal was not
designed to work that way .

You can ask the dev to find tricks , but it could be  nice too to ask the pedal's company owner to fix
that " detail " . They may improve their driver design in the future .

Perhaps elieser will find something to do in your case , i hope so .

**Comment by jonjamcam** [comment]
Ezze, it's not a problem for me. I'm trying to solve potential issues other users may find .

 What do you mean when you say "not designed to work like this". You mean not real time processing via the computer? 

in page 11 the manual says "You can use the ME-25 as an audio interface to the DAW via USB."

That's pretty clear to me.

**Comment by Ezeer** [comment]
ok , i just tried to understand your problem that seemed to be complicated but solved with just some different wiring .
I'm not saying that what you want can't be done here .
:)

**Comment by jonjamcam** [comment]
I know more expensive pedals like the gt-10 have internal capabilities to solve this issue. This could be a "Compatibility feature" hidden somewhere for advanced users.....let's see what's Elieser's take.

**Comment by elieserdejesus** [comment]
I think the Jamtaba current behavior is ambiguous. At moment we have 2 ways to disable audio transmition: 1) xmit button and 2) mute button.

The first option is very clear, but the second is obscure for users. The second approach is anbiguous too, because the mute button has 2 functions: mute and xmit off.    
So, we have:
1- the case reported here by Jon
2- The cases where users want use direct monitoring in your audio cards (and mute the inputs to avoid doubled sounds).
3- The problem of ambiguity in mute button.

I have no doubt in this case, the best (but not perfect) solution is transmit muted channels, so the 3 items in the list above are solved.

**Comment by jonjamcam** [comment]
I think for the regular user, if there's a configuration button that says "click here if you use your pedal board", for example it can be very interesting. Hope it's more general than that, but that's the Jamtaba concept isn't it?

**Comment by elieserdejesus** [comment]
Understood!
Maybe add a check box (on/off) in the preferences to "Transmit muted channels"?

**Comment by jonjamcam** [comment]
yea, that will do.......Simple and effective.

**Comment by elieserdejesus** [comment]
**Too much modifications to solve a tiny issue?**
Exactly Jon.

I thinked in a "direct monitor" control/button in each input track. But doing this we are showing this control every time in the user interface, and this control will be used rarely. This is not good.

In the first Jamtaba version I put 3 controls in the bottom of main window to show "low detail, normal detail and high detail" in user interface. I think this is a possibility, for example in "high detail" mode the "direct monitor" button appears in each track, but is a future work.

**Comment by jonjamcam** [comment]
I was thinking in another way to solve this:

I noticed that pedal boards that do not offer complex routing are also 2in 2out simple USB interfaces, so this problem of duplicate sound happens only with one channel.

So, in the audio preferences we can have a check box near the audio interface that says "Local monitor for this interface only". If uncheched nothing happens. If checked then when you select that input in the control section, the channel grays out completely and transmit only.

Do you think this could work, guys?

**Comment by elieserdejesus** [comment]
Jon, this solution is bit more complicated to program. A button "direct monitoring" in the tracks is more easy to program and more clear to users, but show this button every time don't make sense. So we need a way to change the detail level of user interface. This is more complex, but is usefull for many other things (reduce the controls in midi mode, for example).

**Comment by Ezeer** [comment]
@jonjamcam i am interested to see your log with the jt.Audio=true when you use your pedal driver .
Then we could see what kind of tweak we could do .

**Comment by jonjamcam** [comment]
@elieserdejesus "A button "direct monitoring" in the tracks is more easy to program and more clear to users"

So direct monitoring will mean in this case:

1.- mute local track audio (so it can be heard directly via the USB hardware)
2.- transmit to the room.
3.- no posibility for vst, volume/pan control.

right?

@Ezeer here's the log tested in win10 x64 jamtaba 2.0.6

[log_win10x64.txt](https://github.com/elieserdejesus/JamTaba/files/44160/log_win10x64.txt)

**Comment by Ezeer** [comment]
Thanks jon .
I will follow that  : 
jt.Audio.DEBUG:  using __WIN32 scpecific stream infos for inputs  in  0
jt.Audio.DEBUG:  using __WIN32 scpecific stream infos for outputs  in  0

to see what Jamtaba has in the box .
But it is at core PortAudio that we need more info , so perhaps you could use the 
console program i made for peter to see what we can use on your driver .
Peter reported that this console works on x64 too ( just remove .txt extension )
[HiJack.exe.txt](https://github.com/elieserdejesus/JamTaba/files/44192/HiJack.exe.txt)

**Comment by elieserdejesus** [comment]
Exactly Jon!

**Comment by Ezeer** [comment]
My idea would be to create a new kind of LocalTrack based on : 
**LocalTrackView**::LocalTrackView(Controller::MainController *mainController, int channelIndex, float initialGain, BaseTrackView::BoostValue boostValue, float initialPan, bool muted)
    :BaseTrackView( mainController, 1), fxPanel(nullptr), inputNode(nullptr)
{
    init(channelIndex, initialGain, boostValue, initialPan, muted);
}

That new local track could inherit from LocalTrackView , but implement specific behavior , 
without changes in the layout ( mute is donre internally for example etc ....) and created based
on a list of audio drivers names stored in a json for example .

The result would be that when the audio driver will be selected in preference and recognized as " special " , the tracks will be " special " too , but keeping the same layout .
It's possible also to give a different background color to that tracks to signal that they are " specials ".

**Comment by jonjamcam** [comment]
@Ezeer

" create a new kind of LocalTrack "

 you mean to have audio input, midi input and a custom input as separate type?

"so perhaps you could use the console program "

You mean tweak the driver to disable audio playback in the pedal?

I'm inclined to think this pedals are kind of hard wired.....

If that's possible we'll need to tweak all dirvers of all pedals......I think @elieserdejesus is on the right track on this one....unless I got your idea wrong.

**Comment by Ezeer** [comment]
It is easier for me to understand the output of the console than an human description of his machine , lol .... that's why i asked you to use the console so that i could see what kind of asio support you have.

The new track type is a feature that could hide to the user the complexity of special routing ,
without having to change the base tracks ( you create a new type of track instead of adding more
buttons in the usual tracks )

If the kind of problem you have is generic ( to different kind of hardwares that could use the same asio driver) we can handle it and provide assorted tracks .

**Comment by jonjamcam** [comment]
ok I'm running it on win10 x64. now what?

**Comment by Ezeer** [comment]
copy the screen please and paste here

**Comment by jonjamcam** [comment]
![hijack_snap](https://cloud.githubusercontent.com/assets/15310433/11409585/c408620c-939f-11e5-885e-1c1f13e247eb.jpg)

**Comment by Ezeer** [comment]
Thanks .
Here i see the benefits for u to use your pedal , looking at default low input latency .
My idea is for exemple to store the Asio driver name ( here ME-25 ) in a list , that will serve to 
create special tracks , or directmonitor if it's right .

**Comment by jonjamcam** [comment]
I see, so if the driver is in the list, then it's all automatic? I mean Jamtaba will create a "custom track" not a real time track?

**Comment by Ezeer** [comment]
what do you call a real time track ?

**Comment by jonjamcam** [comment]
ok, real time track I call the traditional track of jamtaba, capable of vst. It doesn't make sense for this architecture to exist other than in real time.

But a "custom track" can be non-realtime because the USB hardware is doing the job, so it can have   a lot of latency and it doesn't make a difference.

I'm using invented names here :D

**Comment by Ezeer** [comment]
**I'm using invented names here :D**
no problem , ia ma an inventor too .
^^
But we need to share the same references to be able to exchange our ideas .

**Comment by jonjamcam** [comment]
Using non-realtime tracks can open the door for Jamtaba to be used by any computer independent of the ASIO, like the ninjam client. I think Jamtaba has way many great features than the vst capabilities, but these are unavailable for non "pro" users. If you have a latency of say 100 ms jamtaba is pretty unusable and you loose the translate, the chords function, the circular metro, etc....

something to think about

**Comment by Ezeer** [comment]
i don't get your non-realtime thing , i really need a picture of it .
Jamtaba and ninjam are NON-REALTIME JAMMING . 
We take the time and put it in buffers , that we recompose later .
It's ILLUSION of realtime .
Realtime is the sound that your pedal produce when you play ( well near of it  ... )

**Comment by jonjamcam** [comment]
and realtime is the sound of KONTAKT triggered by my SPD-30 with latency of 2 ms

**Comment by Ezeer** [comment]
Ah ah ah ! EXACTLY !
;)

**Comment by jonjamcam** [comment]
If you use vst, you need some pro drivers and stuff, but if you use a mic and you monitor outside Jamtaba, then the latency can be anything

**Comment by Ezeer** [comment]
So if i mix the idea of elieser  : 
"  have no doubt in this case, the best (but not perfect) solution is transmit muted channels, so the 3 items in the list above are solved. "
and mine ( a new kind of track derived from the original to do the elieser idea in the background )

we perhaps have your solution .

**Comment by jonjamcam** [comment]
"Custom track" or "direct monitor button"......to be or to be.......:D I like both. The button is easier to implement I think.

**Comment by Ezeer** [comment]
Probably .
But with the kind of track i imagine , you click transmit and that's all .
All the stuff is handled into the numeric wiring of jamtaba and hidden to the user .
The normal features that can't be used could be hidden or just disabled .

**Comment by jonjamcam** [comment]
interesting....I like it.....create new track---->video chat

**Comment by jonjamcam** [comment]
@elieserdejesus I think this thread got somehow derailed. Just to summarize the ideas related to the specific "direct monitoring implementation" discussed before so it's easier to resume:

1.- In https://github.com/elieserdejesus/JamTaba/issues/182#issuecomment-159679120 you said:

>A button "direct monitoring" in the tracks is more easy to program and more clear to users, but show this button every time don't make sense. So we need a way to change the detail level of user interface. This is more complex, but is usefull for many other things (reduce the controls in midi mode, for example).

2.- in https://github.com/elieserdejesus/JamTaba/issues/182#issuecomment-159691872 I posted:

> So direct monitoring will mean in this case:

>1.- mute local track audio (so it can be heard directly via the USB hardware)
2.- transmit to the room.
3.- no posibility for vst, volume/pan control.
***
Now that some time has passed I think this implementation could benefit VST/AU users too, not only Standalone users. and could be hidden and simple to implement. Just right click on any local channel to display a drop down menu:

![image](https://cloud.githubusercontent.com/assets/15310433/25072736/7dde6aee-22ad-11e7-8085-18a9e8b99a6a.png)

This way the interface is no polluted. Do you think it's a good idea?

**Comment by elieserdejesus** [comment]
@jonjamcam , now the boost buttons are "condensed" in just one button and we have more "head room" to add new buttons without poputing the UI. I think a new "direct monitoring" button is not too bad now.

What you prefer? A new button (like "stereo invert") or a option in the right click menu?

**Comment by jonjamcam** [comment]
> What you prefer? A new button (like "stereo invert") or a option in the right click menu?

I like the idea of a hidden feature because you're right this is not something evryone will use. Mostly people with basic USB interfaces, pedals, keyboards, etc., so I'm inclined to the right click menu.

**Comment by jonjamcam** [comment]
@NakajimaYusuke proposed the following here https://github.com/elieserdejesus/JamTaba/issues/522#issuecomment-296367293 :

> Several ninjamer performances always sound a bit delayed from the metronome.
I guess most of the reason of this problem is because they are playing with direct monitoring.
>
>During the NINJAM session, direct monitoring brings monitoring without any latency.
This is the advantage compared to "input monitoring".
But on the other hand, direct monitoring brings latency between "monitor sound" and "actual transmitted sound".

@elieserdejesus I think this an is important point to consider when implementing the "direct monitoring" feature.

As I understand the problem is quite simple. If you have some latency and you choose direct monitoring you'll be playing that amount of latency behind the metronome. For low latencies this is no problem because <30 ms the ear can't really recognize so little delay as problematic, but if you have 50 or 100 ms of delay now you have a problem.

So what do you think about making this adjustment automatically when users choose direct monitoring in Jamtaba?

As Nakajima said in the same post:

> If the direct monitoring delay elimination method is implemented, and all of member uses direct monitoring, a perfectly delay-free session will be realized from anywhere on the Earth.

Of course this implementation does not solve the problem when users use other clients. For that cases we can discuss solutions in the other thread https://github.com/elieserdejesus/JamTaba/issues/522 .

**Comment by Pande** [comment]
I am a bass player and direct monitoring is essential for me using headphones to not feel disconnected from my bass. I have 13ms round trip latency so it has no effect on others whether I use direct monitoring or not.

I've been using the volume fader to adjust myself out of the mix, hearing just the direct monitor. This appeared to be working fine... when I first started, I was using Mute, which apparently stops xmitting too (but it does not tell the user this - BAD, led to me playing for about 2 weeks without knowing I wasn't being heard).

However I just updated and now even the fader is doing this.
This is again not clear to the user and is out of scope for a mixer that is displayed identically to the others.

The ideal fix for me is to fix the mute button to only work locally, the same way it does for every elses channel. the Xmit button is there for when you want to kill sending. 

Thanks for considering.

**Comment by elieserdejesus** [comment]
Hi @Pande !

> The ideal fix for me is to fix the mute button to only work locally, the same way it does for every elses channel. the Xmit button is there for when you want to kill sending.

I agree, this is the simple solution. I will fix the mute button behavior (xmit when muted) and keep this issue opened to improve the "direct monitoring" idea in future. The **direct monitoring** idea contains some complex details like **latency auto compensation**.

**Comment by elieserdejesus** [comment]
Hi @Pande , @jonjamcam , @MagnusDrumsTrumpet , @pljones , @DoublebassOO , @qulf !!

A **new JamTaba release** is available. If possible please help using/testing this pre-release. The change log is in the link too:
https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.4

Thanks in advance!!

**Comment by pljones** [comment]
Hi,

Overall comment
----|
For NINJAM to work, seriously - the only sound you reaching your ears _must_ be *through* the client.  Client can choose to send or not send to server or mix your local input with remote input to despatch to local output.  But the only way to local output is through the client when you're ninjamming and the only way from audio source to your ears must be through the client.  It kills jams if people do otherwise.|

Anyway.

Very brief session using the 2.1.4-pre build (I've messed up my local dev environment _again_) - seemed okay.  I had video running locally - couldn't find anyone with video remotely at the time, though.  Didn't try anything fancy.  Wasn't on long.  I'll try it again at the weekend.

-- Peter

**Comment by Pande** [comment]
Thank you very much for reverting the mute button!

To pljones, Sincerely, a 10-15 ms delay which is the most one can expect from roundtrip latency on most sound cards, on my end, is going to do much more to the jam (because it affects my playing) than it will to the overall jam if everyone else hears me 10-15ms late. More delay is experienced in a real room between you and your band mates guitar amplifier, for example.

If we're worried about maybe someone is using WaveOut or something and they are getting a 100-150ms delay... then yeah obviously that's going to affect the jam but that would never last anyway because neither performer nor audience would tolerate it.

**Comment by pljones** [comment]
If 10-15 ms doesn't affect anyone else, why does affect you?  What makes you so special?

**Comment by Pande** [comment]
Because it affects how you play the instrument, whereas just listening to a delayed signal that you have nothing to do with is indiscernible from an on time one.

The same reason applies to the mix fader for yourself, if it's still sending audio at the level of the local mix that's bad because it does not allow the player to make himself louder compared to others locally to better hear note-off technique or how much low end there is in the tone, for example, as a bass player.

**Comment by pljones** [comment]
I'm a drummer.  I play through NINJAM.  The indiscernible delay doesn't throw me because I'm listening to what I'm playing as part of the rest of the jam.

Again, I fail to see why you think a 10-15ms delay would affect you.

**Comment by Pande** [comment]
Are you monitoring louder than your source?

Bass is attached to my body so the delay causes a phase smearing that is very obvious. I know that if I was monitoring drums with isolation headphones on I would need the same thing. 

My point about it being indiscernable relates to the other players. Them hearing it with 1 ms or with 15ms delay makes no difference. So the benefit is all for the local mix.

**Comment by pljones** [comment]
The speed of sound in air is 1125 feet per second.

That means in 1ms, it travels 1 foot.

That means, if you're standing 10 feet from your monitors when playing, you're telling me you're finding it a problem.

That's why I find it hard to believe you.

**Comment by jonjamcam** [comment]
Guys I think the discussion here should be about the latency compensation. How to make jamtaba calculate how much latency the system has (as reaper does) and adjust automatically

**Comment by jonjamcam** [comment]
Now that you can monitor directly your input I suppose this will be a serious issue in the future. I propose a simple (I think) solution for the moment:

![image](https://user-images.githubusercontent.com/15310433/37435987-898aa0ac-27c4-11e8-95d2-c1bbd4210ab0.png)

manually adjust latency is commonly used for vst plugins: For jamtaba the idea is send the audio to the server with this amount of time subtracted from the interval. In theory it should work fine. what do you think @elieserdejesus ?

**Comment by elieserdejesus** [comment]
@jonjamcam , my first idea was compute the latency compensation "behind the scenes". 

In the standalone is possible ask the ASIO driver about the input latency.  In the VST/AU plugin is possible compute the latency compensation based in the buffer size reported by the hosts. 

In theory is possible compensate the latency without user interaction. 

***
@jonjamcam , can you help running a test? I'm not 100% convinced the buffer size will cause problems (I'm just 99% convinced 😄 ). My first idea in this issue is run this test:

1 - Change your audio buffer size to a big value (4096 if possible).

2 - Setup a loop in sync with the metronome. This loop need be 100% synchronized with your local metronome. A perfect loop will be a click audio track generated in Reaper, for example.

3 - Xmit the loop to a server and record the received audio using a 2nd ninjam client.

4 - Open the received files in Reaper and check visually **how out of sync is the received audio** when compared with the metronome. If the big buffers are really a big problem we will see the received audio very out of sync (delayed).

5 - Set your buffer size to a medium and common value like **256 samples**. Run the experiment again and check **how much out of sync are the people playing with 256 samples?** In theory we are always a bit delayed. If this is true (I think is true) auto compensation is a very interesing feature to add in JamTaba.

**Comment by jonjamcam** [comment]
@elieserdejesus my first tests were unsuccessful. My system has very low latency (2.3 ms) and with max buffer size I get 43 ms. So I did the above test, but no difference when comparing the original to the one streamed. It looks asio4all is compensating any latency I have automatically. Next test I will use my fuitar pedal which I'm sure has a lot of latency.

**Comment by elieserdejesus** [comment]
> I did the above test, but no difference when comparing the original to the one streamed

Thanks for your help @jonjamcam!  This result is very intriguing...

**Comment by jonjamcam** [comment]
> This result is very intriguing...

it is indeed. Well I did  it again. Here are the details:

1.- I created a perfect click track and loaded into reaper (set to 43 ms latency using asio4all)
2.- reaper sends the audio to Jamtaba (using the sync feature)
3.- jamtaba streams the audio to reaninjam (in another track or reaper) which records the jam.

when loading the recorded prject in reaper, the result is:

![image](https://user-images.githubusercontent.com/15310433/37478912-175b49aa-285a-11e8-937d-45ab0513c140.png)

As you can see there is a little gap, but I had to zoom a lot. It does not represent 43ms of latency, but if I'm correct, 1m of latency which is a rounding error IMO. Maybe it's reaper thst's compensating for the latency. what do you think @elieserdejesus ?

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm thinking again about your first test and the result is as expected. When using the pre-recorded loop and jtba sync the audio samples xmited will always be aligned. The buffer size is irrelevant. 

Your 3rd test is expected too and confirm the hypothesys behind this issue.

But your 2nd test is showing a very unespected result. 

Maybe this latency compensation is a ASIO4ALL only thing?

I will try a test in my audio interface too...

**Comment by elieserdejesus** [comment]
I tested using a **M-Audio fast track ultra.**

I connected an audio cable in the M-audio first input and hit my finger in the other cable side every time I hear the metronome to generate a peak. Pure science 😄. 

Tested with 2 jamtabas, one standalone (xmiter) and a VST plugin (inside Reaper and recording).
***
**First test**
Buffer size = 64 samples. The result is **good as expected**, The audio peaks are enough aligned, the small sync problems in every peak are from my fingers 😄 

![image](https://user-images.githubusercontent.com/1012741/37487924-cf998c86-2871-11e8-8ded-94ae41cc638b.png)

***

**Second Test**
Buffer size = 4096. The result is **bad** as expected. The audio peaks are always delayed. 
![image](https://user-images.githubusercontent.com/1012741/37488153-7d8d8f4a-2872-11e8-8a21-3d4948a8f1cd.png)

**Comment by elieserdejesus** [comment]
I tested using ASIO4ALL in my laptop. This time I'm just claping every time I hear the metronome to generate a peak, using the laptop mic.

Tested with 2 jamtabas too, one standalone (xmiter using ASIO4ALL) and a VST plugin (inside Reaper and recording).

***
**First test
Buffer size = 64 samples in ASIO4ALL. The result is good as expected.
![image](https://user-images.githubusercontent.com/1012741/37488594-fd50fb4e-2873-11e8-8d72-5b18dcafc8a7.png)

***
**Second Test
Buffer size = 2048. The result is **bad as expected**. The audio peaks are always delayed.
![image](https://user-images.githubusercontent.com/1012741/37488835-9217e71a-2874-11e8-99f8-4ac286cf9e43.png)

**Comment by jonjamcam** [comment]
Cool. So the only unexpected result was asio4all, but in good way😄

**Comment by elieserdejesus** [comment]
@jonjamcam , my test results are all as expected. No latency problem using small audio buffer size and big latency when using big buffer size.

Just your 2nd experiment is showing an unexpected result, right? Can you review this experiment, maybe  we are missing some detail.

In my experiments I used the **Dummy audio driver** in Reaper (the receiver/recorder side), maybe this a variable to consider too.

**Comment by elieserdejesus** [comment]
> So the only unexpected result was asio4all, but in good way😄

Exactly, ASIO4ALL is black magic 😄 .

**Comment by jonjamcam** [comment]
>Just your 2nd experiment is showing an unexpected result, right? Can you review this experiment, maybe we are missing some detail.

I'll check it out. The hypothesis is arm asio4all is compensating latency

**Comment by jonjamcam** [comment]
Obsolete... closing
