### ISSUE TITLE
show other musicians if not transmit 

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#184]
maybe cool or not, to see if somebody dont transmit in the room like a gray out os the fader or something similar if possible
and give  also the possibility to remind him about maybe turn on transmit
as i and many others played longtime without transmitting  lol
 maybe it is already the effect of frozen faders in the room when the person doesnt transmit  
 dunno 
 greetings from Mag

**Comment by elieserdejesus** [comment]
The first part is done and will be available in next release.
I'm creating a new issue for "give also the possibility to remind him about maybe turn on transmit
as i and many others played longtime without transmitting"
