### ISSUE TITLE
Presets don't work in 2.0.7

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#188]
save and load are still grayed out

**Comment by Ezeer** [comment]
i just finished them today , elieser needs first to test and make some minor changes before merge
into jamtaba . ( and test the compatibility with plugin version )

**Comment by jonjamcam** [comment]
2.0.7 was released this way. I don't understand. People will be confused....

**Comment by Ezeer** [comment]
elieser said that the presets would be for 2.0.7 beta .
For me , you've got 2.0.7 then beta , then 2.0.8 alpha , beta , 2.0.9 etc ....

**Comment by jonjamcam** [comment]
I have ready most part of the manual. There's lots of new stuff to include, but I think I will wait a bit. It just doesn't look completely finished to me.
