### ISSUE TITLE
Win XP problem - reported by EZee

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#19]
... install was done , but at launch time it crashes with " ... is not a valid win32 application "
 I just had the same problem with the newest filezilla 32 bit release . Exactly the same ... i switched to an older version , and it works fine . So there is something wrong with XP SP3 and the latests .exe produced by the linkers . I've found that : http://stackoverflow.com/questions/14633205/how-to-compile-32-bit-my-os-is-64-bit-error-exe-is-not-a-valid-win32-applica
Perhaps that will help ?

**Comment by elieserdejesus** [comment]
Ezee, I compile in my virtualized Win xp and works ok. But when I test the installer I receive the same error message you reported "is not a valid win32 application". I hope this help.

**Comment by Ezeer** [comment]
Ok , i'll inspect that this week , thanks elieser !

**Comment by Ezeer** [comment]
A picture is better than a long speech : 
![capture d ecran 2015-10-27 16 04 11](https://cloud.githubusercontent.com/assets/1283808/10761918/dbbe8c98-7cc3-11e5-80d0-805c18f6c08b.png)
It's when the setup tries to launch the app 

![capture d ecran 2015-10-27 16 06 50](https://cloud.githubusercontent.com/assets/1283808/10761961/17168ade-7cc4-11e5-8ff1-ddb9d108ff7a.png)
Manual launch from the install folder

still searching , should be a bad InnoSetup script ?
Or wirst , the vc2013 redistributable files ...
Elieser , could you verify you don't link InnoSetup with 64bits vc2013 redistributable files in your script ?

**Comment by elieserdejesus** [comment]
Ezee, I check and the script is ok. I think the problem is the Jamtaba exe. Maybe some lib missing? Or the exe is linked with some x64 lib? You the "Depency Walker" software? Dependency Walker works for exes, or only DLLs? 

When I compile in Win xp, using mingW 32, I have no problem. So I'm discarding the problem with libs.

**Comment by Ezeer** [comment]
**"Depency Walker"**
Hey , good idea .
The official site is down , i've found a 2.2  version here : 
http://www.clubic.com/telecharger-fiche11102-dependency-walker.html

**Comment by Ezeer** [comment]
Our great lead programmer elieser just fixed it !

**Comment by elieserdejesus** [comment]
I just paste the line, you found the answer, the credits are for you my
friend !

Em terça-feira, 27 de outubro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by Ezeer** [comment]
mmm.... not sure .
I was ready to enter the matrix with an hexadecimal editor ...
When i say it is better that i sit on my branch ....
![6873765-10507497](https://cloud.githubusercontent.com/assets/1283808/10773232/832235c6-7cfa-11e5-9e29-e37c6a51bf6c.jpg)

lol , 
but i am happy with that long day of work with you , in a football team , you are ...
http://sport.gentside.com/pel%E9/le-plus-beau-but-de-tous-les-temps-inscrit-par-pele-pour-la-premiere-fois-en-video_art45757.html

**Comment by Ezeer** [comment]
"the easy way is to add one extra line to your project’s .pro file".

they should have written " the ezee way is ... " , .bro ' .
Signs...
eh eh

**Comment by elieserdejesus** [comment]
ha ha, you are the master of pictures :)
