### ISSUE TITLE
! v2.07  quite unsuable in reaper the window of jamtaba dont fit

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#190]
hey guys !!

the windows of jamtaba2  vst   dont fit. We  need to scroll for all :
for enter in the room for chatting for the syncing    really annoying  

really need to be fixed  !! plz

**Comment by Ezeer** [comment]
This is a side effect of my code for fullscreen in standalone mode .
The shortcut was removed for the plugin , but not the initialisation code for the window .
Here is the actual code to modifiy for plugin ( i can't do it cos i don't have the tool to build the vst and test ..) : 

void MainWindow::initializeWindowState(){

    setFullViewStatus(mainController->getSettings().windowsWasFullViewMode());

    if(mainController->getSettings().windowWasMaximized() && fullViewMode){
        qCDebug(jtGUI)<< "setting window state to maximized";
        setWindowState(Qt::WindowMaximized);
    }
    else{
        //FULLSCREENMODE ? <<<<< add here AND PLUGIN ?
        if(mainController->getSettings().windowsWasFullViewMode())
            this->setWindowState(Qt::WindowFullScreen);
        QPointF location = mainController->getSettings().getLastWindowLocation();
        QDesktopWidget* desktop = QApplication::desktop();
        int desktopWidth = desktop->width();
        int desktopHeight = desktop->height();
        int x = desktopWidth * location.x();
        int y = desktopHeight * location.y();
        this->move(x, y);
        qCDebug(jtGUI)<< "Restoring window to position:" << x << ", " << y;
        qCDebug(jtGUI)<< "Window size:" << width() << ", " << height();
    }

}

**Comment by jonjamcam** [comment]
Hey @DoublebassOO . For the moment until it's fixed try the mini view.

**Comment by DoublebassOO** [comment]
Yes thats it ,cool idea 

thks Jon

**Comment by teamikl** [comment]
@Ezeer Hey
I introduce github tips, you can use permanent link to specific commit/version line of code
https://github.com/elieserdejesus/JamTaba/blob/v2.0.7/Client/src/gui/MainWindow.cpp#L512

in collaboration
paste a piece of code on thread is missing which branch or revision.
because HEAD is change by time.

I think on issue thread, no one need the detail info.
we can discuss implementation detail on commit or PR thread.
see also github markdown has syntax high-light for quote code.

**Comment by Ezeer** [comment]
>I think on issue thread, no one need the detail info.
we can discuss implementation detail on commit or PR thread.
see also github markdown has syntax high-light for quote code.
copy that !
thx Tea .
