### ISSUE TITLE
VstPlugins "Refresh" appears to do the same as "Clear Cache"

### ISSUE THREAD

**Issue by gevialex** [elieserdejesus/JamTaba#193]
Hi, after Jamtaba has scanned some folders I specified for vstplugins, I sometimes want to add more folders, or maybe install a new plugin to the vst plugin folder. So, in order to not have to rescan all the plugins over again I try using  the "refresh" button. But when I do this, jamtaba clears all the plugins and rescans all over again, isn't that what "Clear Cache" should do?
Shouldn't "refresh" only look for new plugins instead of resetting everything and rescanning everything again?
Thanks cheers

**Comment by elieserdejesus** [comment]
Hi Gevi, this make sense. We will improve this scan scheme. The issue #77  is related too.
