### ISSUE TITLE
Midi Controlled tracks

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#195]
Working in a beta version of jomtobo , you can test it here : https://github.com/Ezeer/JomTobo/releases/tag/v1.0.0-b
![capture-1](https://cloud.githubusercontent.com/assets/1283808/11713316/ec3be444-9f32-11e5-9d43-e9abf134ba88.jpg)
![capture-2](https://cloud.githubusercontent.com/assets/1283808/11713318/ef80d696-9f32-11e5-9b24-7b47d48912d4.jpg)

**Comment by jonjamcam** [comment]
I think this thread is duplicated with https://github.com/elieserdejesus/JamTaba/issues/13.

**Comment by elieserdejesus** [comment]
closing, keeping the issue #13
