### ISSUE TITLE
remind users if local tracks are not transmiting for long time

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#198]
Suggested by Magnus: "give also the possibility to remind him about maybe turn on transmit
as i and many others played longtime without transmitting"

**Comment by jonjamcam** [comment]
@elieserdejesus I had this idea of an "away icon" like skype or old msn that appears if you are muted for 10 minutes (or a user specified value, maybe)

-![](https://az705183.vo.msecnd.net/onlinesupportmedia/onlinesupport/media/skype/screenshots/fa3501/fa3501_5.png?width=43&height=40)

**Comment by elieserdejesus** [comment]
@jonjamcam , the icon is cool. Are you thinking put this icon in locall tracks? I'm not shure "where" this icon will be placed.

**Comment by jonjamcam** [comment]
The idea is to let the other players know that he/she is inactive:

![image](https://cloud.githubusercontent.com/assets/15310433/15678718/b3a980c0-2725-11e6-9f5d-042e562adf8b.png)

**Comment by elieserdejesus** [comment]
Ah, understand @jonjamcam, this is a very good idea.

**Comment by jonjamcam** [comment]
>"give also the possibility to remind him about maybe turn on transmit
as i and many others played longtime without transmitting"

I think this could be solved sending a local chat message to the user (same as in block user) when the yellow icon appears:

![image](https://cloud.githubusercontent.com/assets/15310433/15679661/0268dcb2-2729-11e6-945a-a892bc633a95.png)

**Comment by pljones** [comment]
Having the local track clearly marked would be very good (pulsing red-amber-green monster icon...).  Forgetting xmit is off is bad :).

**Comment by elieserdejesus** [comment]
Guys, I will use the "red blinking" strategy used in Looper rec button in the **xmit** button. If the **xmit** is deactivated for long time (I'm thinking in 2 intervals) the button will blink. 

@jonjamcam proposed an icon in remote channels, but I think is better handle this in a separated issue.

**Comment by pljones** [comment]
Please have a preference for this.  It can be intentional and blinking anything is annoying if not wanted.

**Comment by elieserdejesus** [comment]
> Please have a preference for this. It can be intentional and blinking anything is annoying if not wanted.

I agree, and I think my first idea of **wait 2 intervals to blink** is not good. 2 intervals without xmit is very common.  

Maybe **5 intervals** is good as default value? And configurable in the json?

Can you suggest a good name to store this property in json? Something like **notXmitingIntervalCounter**, but better? 😄

**Comment by Hitrate** [comment]
How bout a timer-off, so it doesn’t keep blinking...Users Intentionally non-xmitting would not get disturbed or distracted or feeling like they need to hurry and xmit....

Also, how about the same blinking thing on other ppls channels...many a time i jam with someone who’s grayed out, and also not transmitting...or they wont be grayed out but the xmit button is disengaged/red...I jam then later find out that had I hit the xmit button on their either grayed out or not channel, then they’re xmitting.....so basically we have potentially maaany users like me who has no real track of who is ACTUALLY xmitting and who is not....solution: make the other users xmit buttons blink IF a user is ACTIVELY transmitting audio AND has logged in while you where already logged in, OR if you log in after them. That way, you will get notified subtly that this user, who was not previously transmitting, OR whom you had previously disengaged by disabling his transmit button, is now in fact in the room with you and streaming audio thus you can take action and hit his or hers xmit button, if you wish....

In both examples I suggest a self time-out so we don’t get unstoppable blinking galore all over the damn place :)

**Comment by Hitrate** [comment]
To explain a bit further the above: this happens all the time due to me disabling other people’s channels, to save bandwith mostly, or cause the user sounds like s... or is not playing with other ppl in the room... but also cause so many have two/(four) channels and are only playing audio through one of their two stereo channels 😑 and many are sitting in a room not playing....BUT then later on or in another room or another day, someone that I had previously disabled like I just mentioned, is now actually playing something cool, suddenly is sounding okay and surprisingly is trying to jam with other ppl in the room - all of this, I don’t get to hear, cause I have no clear indication of this since jamtaba remembers the settings for each user 😆

**Comment by Hitrate** [comment]
So I propose a more visually clear way of knowing what’s going on with other people’s actual transmitting state 

and a heads up that this user is transmitting but you have him/her “blocked”

See as it is now, it’s hard to tell even if the xmit button for other users have been pressed or not...

Maybe also have a general rule of how the buttons should be in terms of brightness and colors so they are all more the same and visually clear across all themes, so you’re not I doubt if the button is gray or dark gray and which means which etc. :)

**Comment by pljones** [comment]
There are several separate idea:

- Am I transmitting?  Do I want to be transmitting and forgot to turn myself back on again?
- Is (other user) transmitting?  Do I want to _receive_ (other user) and forgot to turn them back on again?

And then, for each, there's whether or no I want to be reminded and, possibly separately, after how long.

**Comment by Hitrate** [comment]
Thanks for clarifying pljones :)

**Comment by Hitrate** [comment]
There are other points in my posts, for instance the “I’m playing, someone that I had previously disabled, let’s say the day before, logs in, and he is now “muted” to me...or lets say I muted him 10mins before, and still want to mute him (which is how it is behaving now) - I wanna make it clear, that I would like there to still be the option of not having him be automatically unmuted, when it was someone I muted 10mins ago...But I would also like the option to say this guy, I don’t wanna have transmitting regardles if it was yesterday I “muted” him, or 10mins ago....So perhaps a timer option would be the best idea!!!

Imagine, when you hit the transmit button, you get a drop down of options being + - digits in seconds to minutes to days... that way, jamtaba would be intelligent enough to remember your specefic settings for each individual user!!

That way, you could un transmit the ones you feel like, at the time, foethe set amount of time you want, thus you dont even need to touch your or their (meaning the remaining players) solo button, because there would be a timer on when each player jumps into the jam (from your local experience) and you don’t have to touch anything to make them transmit, since the transmit button would automatically be engaged when set time runs out ;) Bam!

**Comment by Hitrate** [comment]
+Forever 
+1 year
+1 month 
+1 week 
+1 day
+12 hours
+1 hour
+30 minutes
+15 minutes
+1 minute
+30 seconds
-30
-1 minute
-15 minutes 
-30 minutes 
-1 hour
-12 hours
-1 week
-1 month
-1 year
-Forever


Imagine the minus options being: you untransmit your own channel(s) for set time, while the ones you set the time on, transmit. 

That way, you don’t even have to touch your own transmit button, as it will be behaving depending on if or who ever you have in the room, for which you’ve set a time on their transmitting without your transmitting, and when you are gonna join the jam with your transmitting. Double bam!!

**Comment by Hitrate** [comment]
Perhaps even divide the time into “measures” meaning 1 measure being for instance one 16bpi count (if the bpi is set to 16) 
Then a “1/2 a measure” one, so you could be untransmitting for one measure, or half a measure at your pleasjng, and then automatically be transmitting without having to have your finger on the mouse to do it..

**Comment by elieserdejesus** [comment]
Guys, **can you confirm the xmit button state is remembered**? I suppose this is a bad default behavior. 

.
.

@Hitrate , you pointed very good ideas, but let's try simplify this issue to handle local tracks xmit only. I created another issue (https://github.com/elieserdejesus/JamTaba/issues/918) to work in the **remote tracks xmit**. I agree this is very important too.

.
.

> Imagine, when you hit the transmit button, you get a drop down of options being + - digits in seconds to minutes to days... that way, jamtaba would be intelligent enough to remember your specefic settings for each individual user!!

This is complicated to program, a lot of details to think and change in the code. Let's start with something more simple and we can improve in the next versions.

.
.

> I suggest a self time-out so we don’t get unstoppable blinking galore all over the damn place :)

I think the **time-out** is a very good idea. I will implement a first version soon, we can improve in the next rounds.

**Comment by elieserdejesus** [comment]
guys, implemented the "inactivity reminder" for the first channel only. I think the 2nd channel is often not transmit, use a reminder for the 2nd channel will be anoying for a lot of people. Let's start with the first channel only and we see if it's enough or can be improved.

![inactivity warning](https://user-images.githubusercontent.com/1012741/31779181-4946c2b6-b4d1-11e7-82c7-584ec949cebe.gif)

**Comment by jonjamcam** [comment]
>  Let's start with the first channel only and we see if it's enough or can be improved.

It is indeed very effective warning. Of course to keep the idea of warning someone who forgot to turn on XMIT I think it should be linked to activity in the channel. This way both channels can display the warning only if there is any kind of signal going on. If there's silence in the channel I believe the inactivity is on purpose, so no warning is needed.

**Comment by elieserdejesus** [comment]
> I think it should be linked to activity in the channel. This way both channels can display the warning only if there is any kind of signal going on. If there's silence in the channel I believe the inactivity is on purpose, so no warning is needed.

Very good point @jonjamcam , I created a [separated issue](https://github.com/elieserdejesus/JamTaba/issues/942) to improve the inactivity detection.
