### ISSUE TITLE
Plugin scanner don't work on Jamtaba 2.0.8 (win32)

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#199]
And when i try to launch the scanner directly in his folder  i have " is not a win32 application " error message .

**Comment by elieserdejesus** [comment]
I check the VstScanner.pro and the Win XP compiler flag is ok in the project, so I'm without clues at moment.

**Comment by Ezeer** [comment]
ok ... Have you experienced that problem too ?
I have tried with my last version of jomtobo and the scanner is working fine .
So i don't know too ... I will try with my verson of the scanner with jamtaba , i'll report later .
thx

**Comment by Ezeer** [comment]
thus my report is that my version of the scanner + jamtaba2.0.8 win32 works fine .
This is my compressed ( with upx ) version , in case you need a quick fix for your last win32 release : 
[VstScanner.exe.txt](https://github.com/elieserdejesus/JamTaba/files/60453/VstScanner.exe.txt)

**Comment by elieserdejesus** [comment]
I'm not shure yet if this is a win 32 general problem or a Win XP only problem. I will test soon.

**Comment by elieserdejesus** [comment]
It's a Win XP problem only. I have the same problem (not a valid win 32 application) in my win XP (virtual box) when executing VstScanner.exe directly.
I check the win XP compiler compatibility flag and is ok. Check all the windows libs and the libs list is exactly the same used in Standalone. So, is not a obvious problem. I'm suspecting from some weird thing in MSVC compiler versus Console App versus Win XP.

**Comment by elieserdejesus** [comment]
Another question just to remember: it's really a 2.0.8 problem?

**Comment by Ezeer** [comment]
Yes , i am talking about the 2.0.8 
Perhaps a side effect with your recent merges with tea ?
Or with mine , but i think not because files built in my Xp system are working good .
And a 64 versus 32 bits compatibility ? Perhaps the scanner is a 64 bits app ? How to verify that point ?

**Comment by Ezeer** [comment]
just tested the 2.0.7 , same problem ...
i made something on my jomtobo version , is to disable the +order option in the jamtaba.pro file .
( the order to compile and build sub projects ) .
That fixed a build problem i had ( with your 2.0.7 version that include the new scanner ) 
Perhaps something to look inside ?

**Comment by elieserdejesus** [comment]
Fixed,  the solution is here [http://liuyuanzhi.blogspot.com.br/2014/04/vs2013-qt5-windows-xp-compatible.html](http://liuyuanzhi.blogspot.com.br/2014/04/vs2013-qt5-windows-xp-compatible.html)

Just a little tweak in the VstScanner.pro file and is working.

**Comment by Ezeer** [comment]
good , thx for the fix's report .
