### ISSUE TITLE
No ASIO driver problem

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#20]
I see the problem when testing Jamtaba in a fresh Windows XP install whithout any ASIo driver installed. If no asio driver is detected Jamtaba can`t start.

**Comment by Ezeer** [comment]
I take this one !

**Comment by elieserdejesus** [comment]
done! Using NullAudioDriver when no ASIO driver is detected in user machine.

**Comment by Ezeer** [comment]
![bug-killer-game-for-s60v5-and-symbian-3](https://cloud.githubusercontent.com/assets/1283808/10719525/bac4c7b2-7b8a-11e5-88b4-fd6f2d8537b1.jpg)
