### ISSUE TITLE
vst window crop in full view mode

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#202]
![jamtaba-reaper-crop](https://cloud.githubusercontent.com/assets/15310433/11786246/4ef4059c-a264-11e5-9dd2-52aa4326c767.jpg)

**Comment by elieserdejesus** [comment]
Jon, in this image you start in mini mode and switch to full view?

**Comment by jonjamcam** [comment]
It's taken just after the plugin is added to a reaper track

**Comment by elieserdejesus** [comment]
Jon, I test here and is not a bug. 
First I test in a big monitor (1920 x 1080) and the VST window is ok, no crop, no scroll bars.
After this I test again in my laptop (small screen) and the result is the same in your image. 

It's a question of "not enough space in the screen". I have the same result with Addicitve Drums 2. This plugin use a big screen by default, and in small screen the Addicitive Drums window is cropped too.

**Comment by jonjamcam** [comment]
ok. thx. good to know.
