### ISSUE TITLE
Stereo problem with Energy Xt2 and the last Jamataba2 plugin 

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#205]
Frederic mavel reports that on the last version of jamtaba2 vst ( x64 ) , only the left channel works when 
the vst is inserted on the master FX chain on energy xt2.

**Comment by elieserdejesus** [comment]
Thanks for report.

**Comment by elieserdejesus** [comment]
tested in Energy Xt 3 without problems, closing the issue.
