### ISSUE TITLE
detect midi and audio devices whithou close and reopen Jamtaba

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#21]
ast time I test portaudio was requesting the audio devices list from OS in initialization (Pa_Initialize()). After this, if I plug another USB audio device portaudio can't see this new device. But I suggest test this behavior, may be I'm wrong. A possible solution can be finalize portaudio and call Pa_Initialize() again to force updated devices list. I think I read something about this in some forum, but I don't remember the details :)

Ezee: That give me the idea of a thread dedicated to watch the changes on devices . Or just a timer to update periodically the drivers list ? May be just map a signal to a menu button ( configuration , add track etc ...) to the Pa_Initialize() slot ? That depends on your app behavior , i'll check that soon .

**Comment by elieserdejesus** [comment]
@joncamcam, can you help testing this feature? Just start Jamtaba, plug your midi controllers or extra audio device and test these new devices. When you open the preferences dialog the new devices will appear, no need to close and reopen JamTaba.

**Comment by jonjamcam** [comment]
tested!. It's working, but the new devices appear unchecked by default

**Comment by elieserdejesus** [comment]
Thanks for the help Jon, I changed the code to auto select the new devices.
