### ISSUE TITLE
User names with the format X-XXX appear blank in Jamtaba's ninjam tracks

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#213]
![x-xxx error](https://cloud.githubusercontent.com/assets/15310433/12007790/65ac2b3c-abf3-11e5-95d1-32771350f8ea.jpg)

Examples of this are T-bar, A-bis, etc... if the name has a "-" it appears blank in jamtaba's track.

**Comment by elieserdejesus** [comment]
Interesing bug :)  A simple "-" is broking all the stuff, let's solve this in the next release.
Thanks for report Jon.

**Comment by teamikl** [comment]
does Track View use Persistence::CacheEntry?
related one, I've made CacheEntry setters to ignore invalid data.

it's a lack of research available letters.
better change to "escape", instead of "ignore all".

**Comment by teamikl** [comment]
it was by Persistence::CacheEntry::setUserName(). I will work on this fix.

**Comment by teamikl** [comment]
Question about version / release management for hot fix

How about micro version update for such small patch ? users may want the fix soon.
so make a release like a version v2.0.10.1 or apply [SemVer](http://semver.org/) v2.10.1

there is a little merit of SemVer for Qt application,
the next Qt5.6 has support a class for version number.

**Comment by elieserdejesus** [comment]
Tea, the problem with quick fixes: is not really quick in my side. To release something I need compile windows 32 and 64 bits releases, start my hackintosh (I don't have a real Mac), fix possible issues in (Mac/Hack)instosh, compile the mac release, generate the 3 installers (2 for windows and one for Mac) and upload about 50 MB (the 3 installers) using a poor internet connection (350 KB of upload bandwith).  When I have time (vacation for example) it's ok, but when I'm busy with my job stuff I can't do "quick" fixes, it's really impossible. This explain why I discarded the quick fixes in Jamtaba, is not possible.

You know the solution: Continous integration. I was looking in Travis CI another day and I will look again soon.

**Comment by teamikl** [comment]
@elieserdejesus 
Ok I understand your situation, and I think Continuous Integration can be the solution too.
Let's start the open issue, I have interest in CI for Qt application.

**Comment by elieserdejesus** [comment]
Merged, thanks Tea!
