### ISSUE TITLE
Jamtaba crashes when trying to enter a full ninjam room (via private server)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#214]
In earlier versions (2.0.6) it just disconnected. Now it's crashing.

**Comment by elieserdejesus** [comment]
Jon, just to clarify: in the title you wrote "via private server". This means: 
1 - you are connecting in server using the menu "Ninjam -> Private Server" or
2 - you are running a local/private server in your machine?

**Comment by jonjamcam** [comment]
I'm connecting via private server (no.1)

**Comment by teamikl** [comment]
Could be a timing bug?
e.g. if enter room and someone also enter same timing before you made a connection.

View class (user interface) may disable "Enter" but it's a possible scenario, emit enter action.
it was possible to make the situation via "Private Server" menu.

**Comment by jonjamcam** [comment]
Hi tea. If you install Jamtaba 2.0.6 and try to enter a full ninjam room it displays a text box "disconnected from server". This is the expected result just as reaninjam does. Something happened in the following versions...

**Comment by teamikl** [comment]
I tried to debug. Point I doubt was, a closing connection by server side.

- connect to local ninjam server
- shutdown the server
- then JamTaba crashed

got application log:
```
default.INFO:  "Starting Jamtaba 2.0.10 Standalone (i386) running on Windows 8.1 (x86_64)"
default.FATAL:  ASSERT: "d" in file C:\Qt\5.5\mingw492_32\include/QtCore/qscopedpointer.h, line 112void qt_assert(const char*, const char*, int)qglobal.cpp2966
```

**Comment by elieserdejesus** [comment]
Tea, this info will help, I will work on this soon, I think is a very quick fix. At moment I'm just reorganizing the code structure and trying clean some multiplatform stuff, etc. A lot of "house cleaning" work before start coding new issues :)

**Comment by jonjamcam** [comment]
Seems to me the bug is that the disconnect dialog box is broken

**Comment by jonjamcam** [comment]
Elieser the dialog box appears now, but in a very unusual place in my system

![disconnect](https://cloud.githubusercontent.com/assets/15310433/12224394/e3b6de38-b7cd-11e5-88d2-26d47a3170e7.jpg)

**Comment by elieserdejesus** [comment]
Jon, are you compiling from the last source version? I commited the fix for this problem, please check if your code is updated.

**Comment by jonjamcam** [comment]
it's ok now, Elieser.

**Comment by elieserdejesus** [comment]
Nice, thanks for the help testing!
