### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by teamikl** [elieserdejesus/JamTaba#216]
This is a software development topics.
NOTE: I use the term "CI" as "Continuous Integration" in this topic thread.

I just now pick up topic list for starting researches.
Each sub topics can be big ... if discuss details then let's open new issue for the subtopic.
I suggest "SQA" (Software Quality assurance) tag for related issues. (QA was like a question/answer)
## Travis CI supports:
- Build server
  - build GitHub repo on server side/or cloud platform, not bother network bandwidth
- [ ] Cross Compile for osx
  - [The OS X Build Environment](https://docs.travis-ci.com/user/osx-ci-environment/)
  - [ ] But Windows ? and how to install Qt ?
- [ ] One-click deploy (automation deploy tasks)
  - [Travis CI can automatically upload assets to your git tags on your GitHub repository.](https://docs.travis-ci.com/user/deployment/releases/])
- [ ] or research another CI services.
## Release management
- [ ] [Semantic Versioning](http://semver.org/)
  - [ ] micro version for patch
  - [ ] Release coordinate -- pre release build for testers.
- [ ] Nightly Build
  - for testers. publish new features and get early feed back.
- [ ] Minimum patch update
  - Java had .class/.jar  that could be dynamic link library for C++
    Qt support plugin framework. this is a big topic require change the software structure.
## There is another side, CI require to project.
- SQA (Software Quality assurance)
  - [x] revision control ... we use Git
  - [ ] Work flow / commit rules
    - use Pull Request always, not commit to master directly.
  - [x] code review
    - we can use GitHub Pull Request as code review tool
  - [ ] Auto Tests
    - there are a lot test topics...
    - automate regression test reduce the risk/cost of changes
  - Documentation
    - [ ] commit messages
    - [ ] API doc (doxygen, but doc is not written)
    - [ ] Project doc
- License
  - [ ] VST_SDK
  - [ ] there are a lot redistribute libraries in repo.

I know this is large tasks, and you may worry the development speed.
because of tests, document, review etc... much tasks but if quality was improved,
it will reduce total number of issues on success scenario. time is a precious resource.
if you still have tasks do manually, they should be automate as possible.

---

I know missing explain the details a lot. e.g. why should not commit to master directly? etc
but not start deep discussion about sub topics yet.
I am planning launch example project to use Travis CI, and feed back to JamTaba.

**Comment by teamikl** [comment]
I was writing a long, post it now as save draft.
I may add more sub topics later.

**Comment by teamikl** [comment]
## Development Chat

@elieserdejesus @Ezeer 
How about having a live chat?
I know Ezeer setup chat, but now it's for more development topics.

I wanna introduce the chat service [Gitter](https://gitter.im/)
it's easy to create room for GitHub repo. free for public project.
they has GitHub/TravisCI integration and IRC bridge.

Our time zone are different though, I can stay a while around new year's vacation.

**Comment by elieserdejesus** [comment]
**I am planning launch example project to use Travis CI, and feed back to JamTaba.**
Very good, this will be nice!

**Adding some requirements for Travis CI**
1 - Can build linux too? The port is the todo list, I'm almost starting my virtualized ubuntu here :)
2 - I see you mention Qt installing in Travis CI. Don't forget we need 2 Qt static build (32 and 64 bits), maybe this can be a problem in Travis CI.

**About Gitter chat service**
Time zone can be a problem, and when my mind is exploding with job related issues I have no time to eat, so chatting is not possible :)  I propose use git as the main discussion tool, chat for emergencies only.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
