### ISSUE TITLE
Plugin Mr Ray bug

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#22]
bug when audio is sended to Mr. Ray Vst Plugin. The old code was sending only 2 input channels for plugins. Maybe Mr Ray is expecting more channels?

Ezee comments: Mr Ray is indeed a very good vsti that we want to use . As you hired me , i could ask Gsi about that bug ? wait ... " Q: MrRay73 Mark II crashes in some versions of Logic/Mainstage.
A: It has been reported that MrRay73 Mark II may crash Logic 9 under Mac OSX 10.6.x in a 64 bits environment. The cause of this crash is still unknown and unresolved. We apologize for this. " src : http://www.genuinesoundware.com/?a=support#FAQ

**Comment by jonjamcam** [comment]
> bug when audio is sended to Mr. Ray Vst Plugin

Tested Mr Ray working fine in 2.0.17 32bits. It's a midi piano, so I believe it receives MIDI only.
