### ISSUE TITLE
Shirinking the repository

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#223]
@teamikl , @jonjamcam, @Ezeer , I have to do a maintence task in JamTaba repository to reduce the repo size. At moment the repository size is > 200 MB. 

As a git "noob" I added a lot or garbage (.exe files, big files, the entire VST SDK) in the repository when I started Jamtaba in my machine, and I don't cleaned the repository when I created the first public version (using the old repo in BitBucket). This garbage is not used, but all this stuff are in the respository history. 

I need shirink the repository, but all the solutions will **rewrite the respository history**. This means after the "cleaning" everybody interested in JamTaba need a fresh clone, because the old repository will be totally deprecated. If somebody add a contribution (a pull request) using the old repository history the "dead" commits will ressurrect. To avoid these "zombies" commits the "fresh clone" is very important.

@teamikl , you know some git magic to **remove very old commits AND keep the recent history untouched**?

**Comment by elieserdejesus** [comment]
Hi   @abramhindle @DoublebassOO @eriser @Ezeer @jonjamcam @MagnusDrumsTrumpet @teamikl @Zeyad-37

You are the "forkers" of JamTaba repo. I reduce the size of Jamtaba repository (~250 MB) to 25 MB. Unfortunally the commit history was rewrited. So, please update your forks and if possible do a fresh and clean clone to ensure you have the cleaned version of the code.

**Details of size reduction task**:

- Removing unused shared libraries binaries
- Removing big images in resources/icons folder
- Adding new Mac OS installer files. The old Mac installer was using a .dmg template
with 40 MB (bad idea). Now this .dmg is generated by script.
- Removing non used .jpg files
- Removing executables and other very old garbage files from commit history using
this nice tool: https://rtyley.github.io/bfg-repo-cleaner/
- Now the size of repo is 25 MB, the old repo size was about 250 MB, a little difference :)

**Comment by teamikl** [comment]
Hello, long time no see
I was going to report that I met conflict by the update.
Size reduction is nice. I will write additional notes.

The bare repo size is still big, git clone received objects 246MiB.
Testers who does not need the whole history can shallow clone only latest files,
 it was about 14 MiB now, try:  `git clone --depth 1 https://github.com/elieserdejesus/JamTaba`

* [git filter-branch gained speed](https://developer.atlassian.com/blog/2016/01/git-2.7-release/) --recent version of git improved the filter-branch speed too
* [How to handle big repositories with git](http://blogs.atlassian.com/2014/05/handle-big-repositories-git/) -- introduces tips for huge binary assets
* [10.7 Git Internals - Maintenance and Data Recovery -- Removing Objects](https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects)

----
NOTE: I mean repo size here `git git count-objects -vH` size-pack. `du -h` shows another size info.

**Comment by teamikl** [comment]
Sorry, I had unread messages
> @teamikl , you know some git magic to remove very old commits AND keep the recent history untouched?

I am not sure how to do the both remove and keep history together.

about the repo size, missing `git gc` ?

**Comment by elieserdejesus** [comment]
@teamikl , I read something about "GitHub take a while to garbage collect the repos". I did two tests to confirm the new repo size: I uploaded the new/clean repo to **bitbucket** (25 Mb upload) and clone. I did the same in GitHub. I created a new test repository in Github, upload the files and clone. Works perfect in both, the clone is quick (~25 MB). 

But the JamTaba repo is not updated yet in Github (check the image). I will wait some days to GitHub gargabe collector.
![image](https://cloud.githubusercontent.com/assets/1012741/13044941/8316027c-d3af-11e5-84da-252cca6e90c0.png)

**Comment by teamikl** [comment]
@elieserdejesus 
I see, `git clone --single-branch` downloaded 25MiB objects
so that garbage were the github's known issue.

**clean clone** was not easy for update the forked repo on github
I had to push with --force option, but that is dangerous task, will lose all branches.
to protect branches on github: https://help.github.com/articles/configuring-protected-branches/

## for more size reduction

1. Server to another repo or submodule ... currently no used?
2. Client/libs/statics
    - to be submodule, there are more extra tasks to build portaudio with ASIO for windows
      and portaudio repo was SVN, not simple solution.

it may gain repo's size again to include library binaries in repo, when update those libraries.
the static dir can be outside of repo that user setup dir, like VST dir.
how about make it download from DropBox?

----
github help had article for this topic.
[GitHub help - managing large file](https://help.github.com/categories/managing-large-files/)

**Comment by jonjamcam** [comment]
I don't know if this is relevant, but my recent clone (today) was >200MB

![jamtaba new repo clone](https://cloud.githubusercontent.com/assets/15310433/13064080/3286adb4-d42e-11e5-8df8-99ef99dc9938.jpg)

**Comment by elieserdejesus** [comment]
@teamikl , I'm not shure if understand correct your comment about protected branches, but the master branch is protected in Jamtaba repo. Off course I need temporary disable the protection to run a forced push.

About the server: actually the server is used. JamTaba client is connecting in Jamtaba server and requesting a new room list (including connected musicians) every 30 seconds. I'm using the server as a "cache" to avoid every Jamtaba client requesting the cockos public servers page (http://autosong.ninjam.com/server-list.php) and possibly overload the cockos server. I'm suposing the cockos server is not desined to receive tons of requests (ReaNinjam do just a few requests when user manually open the "Connect dialog", not 2 requests per minute like Jamtaba).

Split the Server and Client in submodules was my first idea too, but I give up after read bad things about submodules in git. Some problems when update a submodule and the "main repo" is not updated... 

I think separate the server in another repo is good enough and simple. The lib files can be stores in another repo too (a resource repo), but it's uncommon in github, so I think your idea about a dropbox is better. Put the files in dropbox and a instruction section in the README is very good for me. The Jamtaba repo will very small after this changes. Thanks for the ideas! I will work in these ideas soon, this week is very crazy here, no time to make these changes at moment.

**Comment by elieserdejesus** [comment]
@jonjamcam , same result here. I think GitHub is not updating the repository. I will wait more to see if the problem is solved. When I uploaded the files for another repo the result is correct, just 25 MB, but if I upload to this repo the result is the same 250 MB. No clues at moment, just waiting for GitHub garbage collecting.

**Comment by jonjamcam** [comment]
ok. I'll test again in a few days then. I have a compile problem too. Did a clean command, but this was the result:

![errors compile](https://cloud.githubusercontent.com/assets/15310433/13064345/a911b616-d430-11e5-9876-1619ed35e741.jpg)

**Comment by teamikl** [comment]
@elieserdejesus 
ok the protection branch was just mentioned for other forks.

about server, I had not read.
it's used by client application but no need for build Client?
then they can be another repo, and Client can stay in this main repo.

@jonjamcam 
`--single-branch` option could reduce the download objects size.

Which do u use mingw or msvc 32/64 and build type (release/debug?) and link type is static or shared?
Now Clients/libs has only static library, may be problem when shared link or debug build.
the compile error is reporting missing library files. temporary solution is
if you still have old working repo, copy Clients/libs may help pass the build. (I'm not testing yet)

the Client/libs part is where we are talking now move to DropBox.
so this build instruction may be changed.

**Comment by teamikl** [comment]
@jonjamcam 

I 've tested now, build state msvc64 release is ok, mingw32 debug/release was failed
and same error as your capture pic.

copy Clients/libs was not enough, there were no library link arguments for win32-mingw

@elieserdejesus 
Standalone.pro the win32-g++ section may be unreachable config?
```
    win32-msvc*{#all msvc compilers
        win32-g++{#MinGW compiler
```

**Comment by jonjamcam** [comment]
@teamikl I use mingw 32, release mode. I tested cloning my fork (updated about 1 week ago) and it works ok.

**Comment by teamikl** [comment]
@jonjamcam I open #265 let's move this topic

@elieserdejesus 
this is another size reduction topic, about distribution package size
vstscanner is big 9MB cos of static link qtcore. if it was required exe file for external process
main program can have the role with command line argument like `JamTaba.exe --scanvst`

**Comment by elieserdejesus** [comment]
@teamikl , I can't understand the relation between ´´Jamtaba.exe --scanvst´´ and size redution. Can you elaborate, please?

**Comment by teamikl** [comment]
@elieserdejesus 
it's about VstScanner.exe (not repo size) qtcore static link made the exe size big, isn't it ?
if JamTaba.exe could have the scanning role by given command line argument,
then can remove VstScanner.exe from distribution package.

NOTE: not issue for dynamic link, that use shared library.

**Comment by elieserdejesus** [comment]
@teamikl , I understand your idea now. Very good idea in my opinion. But I do a test compiling the installer without VstScanner to check the size reduction. This is the result of this "new installer":
![image](https://cloud.githubusercontent.com/assets/1012741/13110090/e4605cf6-d564-11e5-9412-a1e2abbaa4ae.png)

As you can see the size reduction is not drastic, I think **InnoSetup** is doind some compression magic behind the scenes.
.

**The static x shared libs is a long history, but I will try sumarize here:**

My  prefered option is shared libs. Change Jamtaba Standalone to use shared libs is easy, and this will reduce a lot the installer size. What is the problem? The VstPluginis the problem!  Is possible compile the VstPlugin to use shared libs too, but we need some tricks to load the DLLs. I see these tricks working in the project [VstBoard](http://vstboard.blogspot.com.br/). The VstBoard installer save the Qt DLLs path in the windows registry. So, you can put the plugin (vst_board.dll) in any folder in your machine, because when the host load your plugin (vst_board.dll) Qt librarys willbe loaded from a "fixed" folder saved in windows registry. Off course, if the user move the folder with Qt shared libs the whole scheme will fail.

So, because the little problem described before, I decide for a static compilation. Unfortunally the executables are huge and every executable has your own Qt copy, but the users are totally free to move these executables. 

Another possibility is mix shared and static. Standalone.exe and VstScanner.exe can be distributed with shared libs, and VstPlugin can be distributed with static lib. I like this solution, but to do this I need **5 Qt kits** in my machine (arghhhhh): **Qt static for 32 and 64 bits**, and **Qt shared for 32 and 64 bits**, and **mingw** kit, because sometimes I need fix some compilation problem specific for mingw. Possible, but terrible! :)

The big installer at moment is about 20MB. It's not a big problem for users wich are used to download some GB in sample libraries, right? We are not talking about "common" end users, the Jamtaba audience is very specific and used to "big downloads". So, my end conclusion is: at moment 20 MB in a installer is good enough for the target audience. 

**End of the little history** :)

**Comment by jonjamcam** [comment]
@elieserdejesus @teamikl have you tried UPX exe compressor to reduce size? Works for x86 and x64 exe files about half the size!

![upx test](https://cloud.githubusercontent.com/assets/15310433/13112508/b737ef0a-d569-11e5-8342-b9c799a76ccc.jpg)

**Comment by elieserdejesus** [comment]
Yes Jon, I tried UPX to reduce executables size before pack with InnoSetup. The final installer size was a little bigger using UPX. If you just pick the executables (without any compression) InnoSetup can reduce this files a lot. InnoSetup is using the same "magic" used by UPX. Upx is very usefull if you have  just one executable to distribute, without a installer pack including another files. Jamtaba scenario is a bit more complex because we need Vst Plugin instalation, a little script to clean the install folder in uninstall process, etc. These little (but important) things are not handled by UPX.

**Comment by elieserdejesus** [comment]
Repo is splited now. The server is a [new repo](https://github.com/elieserdejesus/JamTaba-Server) and the pre compiled static libs are stored in my dropbox. I updated the README to reflect these changes. Thanks Jon and Tea for the ideas.

**Comment by teamikl** [comment]
@elieserdejesus 

I see, thank you description.
I forget about compression in installer, that duplicated qtcore image are compressed well.

I thought vstscanner its very simple job, usually few KiB exe can do.
but rewrite without qt may gain maintenance cost.
loading dll and directory scan are platform specific, c++ standard spec does not have.

@jonjamcam
Yes, I have. it's my favorite utility.

about UPX in JamTaba use case.

JamTaba.exe and VstScanner.exe both contains qtcore library binary
If both exe files were compressed by UPX, then installer packer
may not find same data pattern for the qtcore library. (upto the compression algorithm)
I this this is why the final installer size became bigger.

**UPX** has side effect to another size,
there is a case which may effect to runtime memory usage, when used in multi-process.
OS has mechanism process to share working set if same exe files are lunched multiple times.
but the ex packed by UPX uncompress to heap at runtime, they can't share it.
JamTaba case now, vst scan is short running process, so the effect is little, though.


for me, the priority are
run-time memory usage,  download size, installed storage usage
its can be replace to cost of RAM, network bandwidth, Storage device.

the installed VstScanner.exe 9MB was just 3MB diff in installer.
and I agree that download 20MB is good enough.
