### ISSUE TITLE
crash when editing some VSTis

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#23]
Reported by Ancibug: for some VSTs during the editing of the sound or setting using the interface of the plugin the jamtaba2 crashes. This is with hypersonic2, rob papen blue, groove agent. Native Instruments are working well in the editing. I have the w10 64 operating system. Maybe this is the reason.
Korg plugins crashing too. I am using M1 and MonoPoly. The leagalyCell plugin makes a crash in the scan VST phase , i have removed the legalycell plugin from the folder.
Crash: Sometimes when closing the Korg VST using the X of windows (90% of cases). Sometimes browsing the preset. (i repeat this are very old and prob not vst2). The preset load is ok-
Hypersonic 2 makes a crash when using its internal mixer. This anyway occurs also with cubase 5. I use a hypersonic H20 version

**Comment by jonjamcam** [comment]
my tests show same happening with Jamtaba standalone (some plugins crash on x64 and others crash on x86) under win7 when changing internal parameters.

Reaper 5 has been very buggy for me in the case of plugins, so I think crashes in reaper are not related to Jamtaba.

Reaper 4 works fine with regards to this.

**Comment by elieserdejesus** [comment]
closing, keeping the issue #604
