### ISSUE TITLE
WindowsDllArchChecker not declared error

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#231]
Just did a git pull and can't compile in my system:

![dllarch](https://cloud.githubusercontent.com/assets/15310433/12236289/aa97128c-b857-11e5-967e-b9a71ad6b541.jpg)

**Comment by elieserdejesus** [comment]
Fixed Jon, my bad. I rename a class using QtCreator, but I'm using 64 bits by default, and the 32 bits code was not renamed. It's fixed now.

**Comment by jonjamcam** [comment]
No Problem. The more of us that can test the code, the less buggy for the next release. I'm Glad to help.
