### ISSUE TITLE
master volume enhancements

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#239]
My experience is I use the master volume most of the times at maximum and that is sometimes too low for softer jams. Maybe a solution could be to implement 12 db boost/att buttons for the master or just a higher max level.

Another thing that could be useful is that jamtaba remembers the position of the master level when closing. Now it's always in the same position when launched.

**Comment by jonjamcam** [comment]
The volume range is very comfortable now. For a loud jam it works well in the middle and the setting is kept after restart. Great!

**Comment by elieserdejesus** [comment]
Cool, thanks for the feedback.

**Comment by jonjamcam** [comment]
One little think though. The master fader position is saved after restart, but the actual volume is not. You have to click-move the fader to "refresh" the volume. It looks the value is still fixed.
