### ISSUE TITLE
avoid multiple VST instances

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#24]
avoid multiple Jamtaba plugin instances. Use a singleton for plugin instance?

Ezee: Yeah . Or try something like that : http://stackoverflow.com/questions/28153795/windows-prevent-multiple-instances-code-not-working
I've found that to go with the semaphore idea and Qt : *Shared Memory
The cross-platform shared memory class, QSharedMemory, provides access to the operating system's shared memory implementation. It allows safe access to shared memory segments by multiple threads and processes. Additionally, QSystemSemaphore can be used to control access to resources shared by the system, as well as to communicate between processes.*

**Comment by elieserdejesus** [comment]
done! When a second instance of Jamtaba is create inside host the plugin creation fail. So only a initialized Jamtaba instance is allowed in the same DAW instance. This methos fail if user create another DAW instance or open 2 different DAWs (like Reaper and Sonar).

**Comment by Ezeer** [comment]
:+1:
