### ISSUE TITLE
"Ghost" VST appears after restart when using two channels

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#243]
Duplicate vst when restarting Jamtaba using two channels and one subchannel in the first track. Well this is a tricky one. It doesn't happen everytime. I'm still trying to figure out how to reproduce the bug.

![ghost vst](https://cloud.githubusercontent.com/assets/15310433/12439713/8e2effb2-bf12-11e5-8c8e-3a187073e4e3.jpg)

**Comment by elieserdejesus** [comment]
Fixed now, the problem was related with the channel names. I was using the channel name to get the plugins list, but when the channel names are equals JamTaba get the wrong plugin list.
