### ISSUE TITLE
presets do not save current input device

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#250]
Is it possible that the device is saved in the presets? Jamtaba saves the last device used when closing, but not when a presets is saved.

**Comment by elieserdejesus** [comment]
It's possible, I will check this for v 2.0.13

**Comment by jonjamcam** [comment]
Another thing related. I'm not sure what I posted before is 100% accurate. In my system the first device (0) is loopBe which is used as default device always (after restart and with presets). I've been unable to set other devices (key (1), octapad(2)) as default. After restart it always uses LoopBe.

**Comment by elieserdejesus** [comment]
I check the preset file and the midi device is saved. 
Maybe the the midi device number is not saved correctly, or the problem is in loading.

**Comment by jonjamcam** [comment]
version 2.0.10 keeps the selected device after restart

**Comment by elieserdejesus** [comment]
Humm, usefull clue. I will check this soon.
