### ISSUE TITLE
GAP in master volume controls

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#252]
![image](https://cloud.githubusercontent.com/assets/1012741/12699146/49036142-c798-11e5-8dec-c4fce708d1e9.png)

**Comment by elieserdejesus** [comment]
@jonjamcam, your name is not appearing in the Jamtaba "contributors" list. Github put the name in the contributors list only if you do a "push". Are you interested in fix this bug in the master controls layout?

If you are interested you need:
1 - Fork the JamTaba repository in github website. The fork button is in the top.
2 - Create a local branch to work in the bug
3 - Fix the bug: open the file **MainWindow.ui**, click in the master volume slider, in the right side (properties panel) change the **sizePolicy, Horizontal Policy** to **minimumExpanding** (the current value is **minimum**)
4 - commit your changes
5 - push your changes (here git will ask you for a remote branch and will show the commands to push/create in the remote branch). No worries, you are not pushing in the JamTaba master branch, you are pushing in your fork, and just in your new branch.
5- Create a **pull request** in github, in the combo boxes choose the **master branch** in the left and **your branch** in the right.

**Comment by jonjamcam** [comment]
Sure. I'll do it. Thank you.

**Comment by jonjamcam** [comment]
Ok. I have commit in branch, but it's not appearing in master. I'm confused what to do next.

![branch-push](https://cloud.githubusercontent.com/assets/15310433/12700046/9d2e6e24-c7b1-11e5-9ebf-cdee58bd0d2e.jpg)

**Comment by elieserdejesus** [comment]
It's ok, pushes are related with ONE (and just one) branch. If you pushed to a branch named "A" this commit will not appear in other branches. You pushed to a branch named  "GAP-in-master-volume-controls", not to the master branch. To "mix" commits in different branches we use the git command "merge". 
But you don't need the merge command in this moment. You do all the steps I mentioned before, except the last step. Now you just need create a **pull request** (the last step) in Jamtaba repo, not in your fork. After you created the pull request in JamTaba repo I can **merge** your pull request here, and your commit will appear in the JamTaba master branch. 

This "flow" is common in open source projects and you can contribute any other projects using the same approach: create a fork, create a branch for your changes, do your changes, commit, create the pull request, wait for code revisions/comments and finally for the final merge.

I'm not shure, but think your forked master branch will not be auto updated with the last changes in the JamTaba master branch, but I suppose github will show some button or instructions to "sync with the original repository". If you keep your fork active is necessary update periodically to avoid the repository diverging. If your repository/fork is diverging too much can be difficult merge your commits without tons of conflicts.

**Comment by jonjamcam** [comment]
>  I suppose github will show some button or instructions to "sync with the original repository"

Yes. To sync the fork there's three simple steps:

1.- https://help.github.com/articles/configuring-a-remote-for-a-fork/

2.- https://help.github.com/articles/syncing-a-fork/

3.- https://help.github.com/articles/pushing-to-a-remote/

**Comment by elieserdejesus** [comment]
Nice, git is very complete, tons of commands and tricks.

Jon, you can delete the branches in your fork after your pull requests are merged. This will keep your fork clean, whithout 'dead' branches.

**Comment by jonjamcam** [comment]
Hi @elieserdejesus . I've been struggling with this issue for some weeks now. My fork is a mess. It has the old structure and the new one combined and I've tested some solutions to resync it so it's the same as the original from your account unsuccessfully.  So one thing I could do is delete my jamtaba repository and fork it again in order to submit PR again, but this warning appears. 

![delete fork](https://cloud.githubusercontent.com/assets/15310433/14069203/1a350b16-f46d-11e5-8708-6ff6d1d302c9.jpg)


What do you think? Is the cure worse than the medicine?

**Comment by elieserdejesus** [comment]
@jonjamcam , I think delete the fork and recreate is the best option. If you have particular data in your fork (comments, different wiki, different issues) these data will be deleted. I suppose this is not the case, so you can delete and recreate without problems.

**Comment by jonjamcam** [comment]
Ok. Just did that. Solved.THx,
