### ISSUE TITLE
First name in first server in the rooms list appears blank sometimes

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#259]
Names I've seen blank are Creative, Doublebass, an, etc. so it's happening independent of the name format. 

![frist no name](https://cloud.githubusercontent.com/assets/15310433/12869906/90f661ac-cd0b-11e5-8961-d4e14ede64b3.jpg)

Another example:

![frist no name_2](https://cloud.githubusercontent.com/assets/15310433/12870311/bcc6d4c6-cd1d-11e5-8f7d-ea044fd93ae2.jpg)

**Comment by elieserdejesus** [comment]
Crazy bug, just in the first server. I will check this...

**Comment by elieserdejesus** [comment]
Jon, I see this bug today and the problem is related to full servers, as you can see in your 2 images (the 2 servers are full). I will check the problem soon.
