### ISSUE TITLE
Users using voice chat in reaper are not showing in Jamtaba's room

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#264]
I noticed this one by pure chance. If you activate reaNINJAM's voice chat you will not appear in Jamtaba's room.

![voice cht not app](https://cloud.githubusercontent.com/assets/15310433/13028608/7c8c5a68-d252-11e5-99ee-0343f4ac54a8.jpg)

Time for a nasty bug?

**Comment by elieserdejesus** [comment]
This can be trick, I'm not shure about how Reaninjam works in voice chat. In "normal" mode the ninjam clients exchange some messages about user entering, user leaving, chat message received, etc. But I think these messages are different in voice chat, or maybe no messages. I will check this soon.
