### ISSUE TITLE
Build failed win32-mingw

### ISSUE THREAD

**Issue by teamikl** [elieserdejesus/JamTaba#265]
The first reported by @jonjamcam at https://github.com/elieserdejesus/JamTaba/issues/223#issuecomment-184462357
I've tested current HEAD (1c721a65c3e12509a00de0cebf7f169bac25a60b) and got the same result on mingw build.

two causes I found are:

- missing linker option in Standalone.pro
    - no `LIBS +=` portaudio etc for MinGW
    - win32-g++ section was inside win32-mscv*
- Client/libs now does not have dynamic link libraries

**Comment by jonjamcam** [comment]
Ok. Folowed the new instructions. Working in my system (MinGW 32)
