### ISSUE TITLE
Built-in loudness meter

### ISSUE THREAD

**Issue by NakajimaYusuke** [elieserdejesus/JamTaba#266]
Hi, I have an idea about level meter.

Currently, Jamtaba2 and NINJAM has a peak meter. Certainly, peak meter is valid to clip detection.
However, on the other hand, I think peak meter is not suitable for "volume monitoring for instruments" .

I recommend the "loudness meter" for volume monitoring during the session.
Loudness meter indicates the sensory loudness for the human ear.
It should be suitable than the peak meter as a guide for the volume adjusting.

http://crasher.orz.hm/ninjam/files/loudness1.mp3
I've prepared a very extreme example.
These are "very thin drum" and "very fat guitar."
The drum is a dry sound with no VSTeffect. It is peaky and attacky.
The guitar is heavily compressed sound with many VSTcompressor and limiter. It has been crushed the attack.

![loudness1](https://cloud.githubusercontent.com/assets/15982547/13500096/4d6e03ce-e1a4-11e5-905d-80ba22c5df11.png)
Their peak is the same. Both are -0.3dB.
But, ear sensation (loudness) volume is completely different. Guitar is terribly noisy.

As in this case, even if the peak value is the same, their feel volume is not necessarily the same.
Therefore, I think that the peak meter is not optimal standard of volume control in NINJAM session that appeared a lot of kind of sound. ,

I compared their loudness volume using loudness meter.

Loudness volume of the drum track was about 3.
Loudness volume of the guitar track was about 17.

So I modified the guitar volume "-14 dB".
![loudness2](https://cloud.githubusercontent.com/assets/15982547/13500116/5f8f7ce0-e1a4-11e5-95bc-78cbc1c15ba6.png)

This is the result.
http://crasher.orz.hm/ninjam/files/loudness2.mp3

I feel this is a good volume balance.
As shown in this example, I think the loudness meter is a better volume control standard than the peak meter.

If NINJAM Client has built-in loudness meter, and musicians decide the recommendation loudness volume range beforehand,
We will be able to volume decisions based on better criteria. By doing so, volume balance of the NINJAM session will be improved easily.

**Comment by elieserdejesus** [comment]
Hi @NakajimaYusuke , I totally agree with you, peak meter is usefull only for clip detection, and is almost useless in a "mixing" scenario.
I'm scheduling this issue for the next release, but Jamtaba development is in slow motion mode at moment :)

**Comment by NakajimaYusuke** [comment]
Thank you! I am looking forward to it.
Volume difference problem between players was a pain in the neck for me.

https://github.com/elieserdejesus/JamTaba/issues/232
As jonjamcam is described in this thread,
NINJAM musicians are fighting a loudness war unconsciously.
I think loudness meter is useful for the restraint for it.

Take it easy.

**Comment by elieserdejesus** [comment]
The [ITU BS.1770 algorithm](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.1770-2-201103-S!!PDF-E.pdf). The idea is replicate the human ears (including the human head) to get a loudness meter. 

**The problems I see in the moment are:**
1 - It's not easy to implement as a simple peak meter.
2 - Require more processor power.

**Comment by elieserdejesus** [comment]
@NakajimaYusuke , I implemented a RMS meter. Is not a loudness meter, but is simple and help ajust the faders. This is the result:
https://cloud.githubusercontent.com/assets/1012741/15554034/7bfaae74-2298-11e6-9ef4-05814e0a8069.png
