### ISSUE TITLE
miditools button makes additional channels look unaligned

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#267]
Hey Elieser, just compiled this cool new feature an this is what I got when adding a subchannel:

![miditools unline](https://cloud.githubusercontent.com/assets/15310433/14036325/9fa58360-f216-11e5-9270-b0e0fe959597.jpg)

**Comment by elieserdejesus** [comment]
Hi Jon, this behavior is expect, but I agree is not the most "beatifull" solution.
At moment I don't have very good ideas to show the midi tools button and keep the layout alignment. One possibility is put a blank space in all subchannels as a "ghost" MIDI tools button, so all subchannels will appear as vertically aligned. Another idea (I prefer this one at moment) is always show the MIDI tools button, and just enable/disable the button. Change show/hide by enable/disable will keep the alignment.

**Comment by jonjamcam** [comment]
Right. Have you considered using the MIDI button at the bottom? It's used just for label purposes only.

**Comment by elieserdejesus** [comment]
If I understand correct, your sugestion is remove the "track type label" in bottom and replace with miti tools button, right?

I think this is a good idea, the icons for "track type" are too simple and can be discarded.

**Comment by jonjamcam** [comment]
yea, that sounds good too. I think the actual track type button is very nice and the idea was to use as a button.

**Comment by elieserdejesus** [comment]
Jon, this is the final result, thanks for the ideas:
![image](https://cloud.githubusercontent.com/assets/1012741/14065841/a25bc222-f40f-11e5-8134-3f9d91938919.png)

**Comment by jonjamcam** [comment]
yeah, much better!
