### ISSUE TITLE
Bug in interval progress painting when "circle" is selected

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#268]
The bug appears only when BPI is > 32. Some ghosts circles are painted in wrong places.

![image](https://cloud.githubusercontent.com/assets/1012741/14045548/db18041e-f279-11e5-9ebe-df2b1df92134.png)

**Comment by jonjamcam** [comment]
I think this could be related: Turning accent on, then off the accented intervals don't reset:

![paint metro bug](https://cloud.githubusercontent.com/assets/15310433/14067856/80f2c3a2-f445-11e5-90b8-8ee724ed6d4b.jpg)

**Comment by elieserdejesus** [comment]
I'm redoing this piece of code, many small problems in circle painting.
