### ISSUE TITLE
Metronome sound database

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#270]
I was playing with new metro sounds and I found it's a bit tricky to get them right. I think it has to do with specific trimming and length. So I'm working on trying to establish the WAV archive requirements, but it occurred to me that a pop up menu with click sound options could be a good idea too.

Here's a couple of tests I did (rename to .rar):

[Jamtaba Click Tests.rar.txt](https://github.com/elieserdejesus/JamTaba/files/191130/Jamtaba.Click.Tests.rar.txt)

Sounds from here: http://soundbible.com/tags-click.html

Looks like the licences are CC 3.0 and public domain

Edit: Two more click sounds (RP_clck is reaninjam's original click)

[Jamtaba Click Tests2.rar.txt](https://github.com/elieserdejesus/JamTaba/files/191168/Jamtaba.Click.Tests2.rar.txt)

**Comment by elieserdejesus** [comment]
Jon, the Jamtaba code is trimming the silence in the start of audio file. It's a simple approach, just detecting the first non zero sample and use this sample as "first sample" in the file. 
These files you posted here are working or have some audible problems?

**Comment by jonjamcam** [comment]
All work fine, except "CW_clckH" that It starts a bit late like missing the first chunk or something. This is good hint you wrote above. I will do some more testing with that in mind.

**Comment by jonjamcam** [comment]
Ok here's 4 revised clicks (stereo and mono). What I find awesome is that stereo files are accepted. For drummers, when you have a lot of instruments it's not always enough to keep rising the click level. Sometimes a clever stereo image for the click can do the trick.

[revised clicks.rar.txt](https://github.com/elieserdejesus/JamTaba/files/191255/revised.clicks.rar.txt)

**Comment by elieserdejesus** [comment]
Thanks Jon, I'm thinking in create a "metronome" folder in Jamtaba instalation path and load the metronome files from this folder. The ideia is release Jamtaba with your sounds pack. Users can drop new files in this folder to "install" new metronome sounds. We need some kind of pattern in file names to recognize the new files as "primary" and "secondary" beat. Add a suffix in file name is enough, for example: **my_click_1st_beat.wav** and **my_click_2nd_beat**.

**Comment by jonjamcam** [comment]
ok. I used the suffix H for "high" and L for "low". Here's the files renamed using "1st" and "2nd"

[Jataba Clicks Revision2.rar.txt](https://github.com/elieserdejesus/JamTaba/files/191987/Jataba.Clicks.Revision2.rar.txt)

**Comment by elieserdejesus** [comment]
thanks, I will work in this feature soon.

**Comment by teamikl** [comment]
:+1: Nice feature, a lot NINJAM users wanted to change the click sounds.

> the Jamtaba code is trimming the silence in the start of audio file. It's a simple approach, just detecting the first non zero sample and use this sample as "first sample" in the file. 

Detecting silence by non-zero not enough?
the wav data may contains little air sounds or noise before the click head.
How about use threshold instead of "!= 0" ?

![clickwav](https://cloud.githubusercontent.com/assets/146129/14237995/3caee1d6-fa66-11e5-8c5a-be0df27bada3.jpg)

**Comment by elieserdejesus** [comment]
Hi @teamikl , good idea. I will add a new task (improve the silence detection) in the pull request.

**Comment by elieserdejesus** [comment]
Pull request #278 closed and integrated.
