### ISSUE TITLE
1st Beat metro sound disapears when the server is full

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#271]
While testing the metro sounds I noticed a little, but persistent bug that now I realize was there all the time unnoticed. When inside an empty server the click sounds perfect, but as the room is being filled the 1st beat sound starts to disappear. I know that it is certain that when the room is full this happens, but I can't tell when it's starting. I tested today inside a full server and to check I soloed the click and the 1st beat is clearly not there.

**Comment by elieserdejesus** [comment]
I will check this soon, it's a bit difficult to run a controlled test, but is possible. I think the problem is related with a lot off ogg vorbis decoding in first interval beat.

**Comment by jonjamcam** [comment]
tested in a room with full, 4 and 3 clients connected total and the 1st beat is never what it should be (unless the server is empty). I mean sometimes the 1st beat sounds like a "crack" or "tick" noise.

**Comment by elieserdejesus** [comment]
Jon, how many cores in yor laptop processor, and what is the processor frequency?

**Comment by jonjamcam** [comment]
Here's:

![processors](https://cloud.githubusercontent.com/assets/15310433/14080412/5607cec6-f4db-11e5-94c2-5d595059d69a.jpg)
