### ISSUE TITLE
User name is not appearing in Jamtaba VST

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#273]
Tested using reaper x64 and Jamtaba vst x64. It says (Jamtaba) where the username it's supposed to be.

![jamtaba 2 0 13 vst](https://cloud.githubusercontent.com/assets/15310433/14084473/3ddc14a4-f4f1-11e5-89fb-26ae4ee4f685.jpg)

**Comment by elieserdejesus** [comment]
Jon, Reaper is combining the plugin name and the "vendor string". All plugins can return a "vendor" string, and Jamtaba is just returning "Jamtaba". [Check this in the code](https://github.com/elieserdejesus/JamTaba/blob/master/src/VstPlugin/Plugin.cpp#L181); 

I will change this to return "www.jamtaba.com" as vendor string.

**Comment by jonjamcam** [comment]
ok. I understand. The problem is that Jamtaba vst users don't see what username they are logged with after they type it as opposed to Standalone where this feedback exist. May I suggest a simple solution (for both):

![jamtaba 2 0 13 vst_user name](https://cloud.githubusercontent.com/assets/15310433/14100998/c443f3a6-f567-11e5-9dc5-9e33d19510bc.jpg)

**Comment by elieserdejesus** [comment]
I totally agree, very good idea. 
I'm thinking in put a text field and allow user to change the user name directly in the GUI.

**Comment by jonjamcam** [comment]
Changing language replaces the user name for the old "your controls" text:

![user name change](https://cloud.githubusercontent.com/assets/15310433/14394505/f926b2f0-fda2-11e5-9884-c95dcf98e132.jpg)
