### ISSUE TITLE
Enter room notification in chat appears only once per user

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#274]
If a user enters/leaves a room several times during a jam, Jamtaba only notifies the first time the user enters. In the example below, the user "punktire" left and entered again, but the last time it was not shown in the chat as a notification.

![enter room](https://cloud.githubusercontent.com/assets/15310433/14104881/3e5d91a4-f57e-11e5-9ce7-051a1cc161c4.jpg)

**Comment by elieserdejesus** [comment]
![image](https://cloud.githubusercontent.com/assets/1012741/15506623/aa5f83b6-219e-11e6-9647-f604fa62cbc4.png)
