### ISSUE TITLE
Option to select language (other than default)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#283]
Now that the internationalization is working it would be good to have the option to change to other available language if the user chooses to (like the translate function is able to).

**Comment by elieserdejesus** [comment]
Done in PR #284

**Comment by jonjamcam** [comment]
Language Menu working fine! (to be able to compile I had to use some old .qm files for now)

**Comment by elieserdejesus** [comment]
Jon, if you run the **lrelease** command the .qm files will be generated. Can you try?

**Comment by jonjamcam** [comment]
Yes! qm files generated
