### ISSUE TITLE
English only (no translation available) items

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#291]
I found this two items that are still fixed in English only.

![clicks and license](https://cloud.githubusercontent.com/assets/15310433/14372511/b2b3fd7c-fd17-11e5-92fb-b7db077015d0.jpg)

**Comment by elieserdejesus** [comment]
Jon, just to clarify:
1 - your idea is translate the text items in custom metronome combobox?
2 - The licence button has no text, just an icon. But this button has a tool tip text. Your idea is translate the tool tip or translate the licence text?

**Comment by jonjamcam** [comment]
1.- the click names text (i.e. finger snap -> spanish, jap, etc)
2.- The idea is to let non-english speakers read the license text in their native language.

**Comment by teamikl** [comment]
@jonjamcam 

the license text is NINJAM server side resource.
private server may return their custom text, that can not translate as client side resource.

about Creative Commons license, there are translations.
link to the page is helpful? I think people does not read the license every time.

the license text use case in Japanese private server,
we use describe server local rules there, like README for new comers.

**Comment by teamikl** [comment]
about link to CC license page
If creative commons licence URL was detected then link to the language page with locale options

e.g. http://creativecommons.org/licenses/by-nc-sa/2.5/deed.ja

NOTE: http://creativecommons.org/licenses/by-nc-sa/2.5/deed.ja_JP was redirected to "deed.ja"

**Comment by jonjamcam** [comment]
@teamikl I think your solution is good enough. This is as you say not read too often. And most (if not all) servers are some kind of CC license.

**Comment by elieserdejesus** [comment]
good ideas CC links!

**Comment by elieserdejesus** [comment]
@teamikl , another piece missing translation is the country names in the public servers/rooms list or inside a room. I try some approaches with QLocale and the **nativeCountryName**, but no success. You know some trick in this field? I think translate the country names is very important, some english country names are very non intuitive in comparison with native language.

**Comment by teamikl** [comment]
@elieserdejesus 

I think QLocale does not support such translation for out of resources.
Qt's resource ./Src/qttranslations/translations/*.ts does not have translated country names.

Perhaps, there is a translated resource library ?

**Comment by elieserdejesus** [comment]
@teamikl , I found a way, a free webservice:

![image](https://cloud.githubusercontent.com/assets/1012741/14404006/8263f6aa-fe42-11e5-9371-ccafb6fb6af9.png)

![image](https://cloud.githubusercontent.com/assets/1012741/14404009/a7d40f74-fe42-11e5-8263-a0e9718cd798.png)

![image](https://cloud.githubusercontent.com/assets/1012741/14404017/e2ebe906-fe42-11e5-8c33-76f68c6f7040.png)

Now I'm thinking how we can cache the translated country names in JamTaba. A separated cache file for translated country names? How handle the multi-language users? Use different country name cache files? A cache file for french country names, another file for spanish contry names, etc?

**Comment by teamikl** [comment]
@elieserdejesus 
1 file for 1 language, can save memory usage.
the database size are small.

I was looking for the library, the data is about 4-12kB in json format.
https://github.com/hexorx/countries/tree/master/lib/countries/cache/locales

> how we can cache the translated country names

store CODE,NAME pair into LANG file.

Qt5 has QMap or QCache classes
I think QMap it's serialize-able by QDataStream.

**Comment by elieserdejesus** [comment]
@teamikl , I checked the file [https://github.com/hexorx/countries/blob/master/lib/countries/cache/locales/br.json](https://github.com/hexorx/countries/blob/master/lib/countries/cache/locales/br.json) the see the country names in portuguese, but the names are all in english. I'm missing something?

**Comment by teamikl** [comment]
@elieserdejesus 

or I am missing something? was not that translated country names resources.

output is country name in user's language.
what input is? need translation country name to country name?

If it was not, just take it as sample of the cache database size.

**Comment by elieserdejesus** [comment]
@teamikl 
`was not that translated country names resources ?`
It's not translated in portguese file (br.json). I look other files and somethings look like translated, but I'm not shure. Maybe this is an incomplete resource missing some translations.

After some simple testing I'm shure this is an icomplete translations resource. I check the translated country name for the **US** code in **fr.json**: the result is "US":"États-Unis". Google translator show almost the same thing, with a little difference :)

I checked the same country code in **br.json** the see the portuguese translation. The result is 
"US":"Stadoù Unanet". This is totally incorrect and is not portuguese. The correct translation in portuguese is "Estados Unidos".

**Comment by jonjamcam** [comment]
@elieserdejesus I see the service Jamtaba is using is https://geoip.nekudo.com/

if you go to the page it says it has parameters:

language	optional*	Two character language code like en or de.

**Comment by elieserdejesus** [comment]
@jonjamcam , I have to send a beer to you :D 
This is most obvious, best and simple solution. I test here using another languages as parameter and works fine.

**Now we have a little issue to solve:**
The Jamtaba users have country names stored in your cache files for every ninjamer IP. These country names are cached in english only. **How we can deal with this obsolete country names cache?**

The current cache format is something like:
**IP => contry_name_in_english**

We can change this to something like
**IP => [en:*country_name_in_english*, fr:*country_name_in_french*]**

@teamikl , another ideas to update the cache?

**Comment by jonjamcam** [comment]
@elieserdejesus did you test jp? didn't work for me

**Comment by elieserdejesus** [comment]
I tested my IP translated to **jp** and the result is **Brasilien**. @teamikl , please tell me this is the correct translation :D 

I think is very difficult found a 100% accurated database, specially in free services.

**Comment by jonjamcam** [comment]
I found this wonderful  resource with all the information we need for this coutry translation task.

http://www.foreignword.com/countries/English.htm

 The question is how to extract it for a proper use. Maybe Jamtaba could contain this information in some kind of database file or something. It's about 200 countries in the world only.

**Comment by elieserdejesus** [comment]
Nice resource Jon, I see it's translated for 15 languages only, but I think this is enough for a first try.

We can [extract the HTML content programatically] (https://wiki.qt.io/Handling_HTML)

So, we need decide:
1 - Use the language parameter in geoip.nekudo.com
or
2 - Use the parge mentioned by Jon in the last post

In both solutions we have to deal with the old country names cache. The solution (1) is very easy. The solution (2) need connect with the server, grab the content from HTML, etc, it's more working.

From the **programming perspective** I prefer the first solution. But from the **translation database reliability** I prefer the second solution.

**Comment by jonjamcam** [comment]
> The solution (2) need connect with the server, grab the content from HTML, etc,

If there's a way to do it so that Jamtaba can have this database internally I volunteer to transcribe the database (copy the content of the htlm to a file or code manually)

I'm thinking if this kind of array:

(AR;Argentina,	Argentine, etc)

**Comment by elieserdejesus** [comment]
The idea of an **translated country names database** sounds interesting for me. 

I'm thinking in create .TS files, so other translators can edit these files (probabily rare) or create new translations for other languages. We can automatically (a small application) or manually fill the .TS files for the 15 languagens in the [link](http://www.foreignword.com/countries/English.htm). Or we can reduce the work ammount and create .TS files just for the supported languages in Jamtaba. 

In a first moment I was worried about the database size, but I think the size will be the same in the current .TS files (very small).

**Comment by jonjamcam** [comment]
I think 200 names use little space too and country names have not changed much in 100 years. @elieserdejesus  do you think is better to organize the database by language? (easier) or by country (more work)? The use of .ts files are organized by language so it's very easy to copy/paste the content if this is the case.

**Comment by jonjamcam** [comment]
wikipedia has a very complete database too ordered by country:

https://en.wikipedia.org/wiki/List_of_country_names_in_various_languages

I think we should do only the 4 languages we have a translation for and see how it goes from there...

**Comment by jonjamcam** [comment]
Sry I missed @teamikl 's post

> I was looking for the library, the data is about 4-12kB in json format.
https://github.com/hexorx/countries/tree/master/lib/countries/cache/locales

It's just what I was thinking about :D

> I checked the same country code in br.json to see the portuguese translation. The result is 
>"US":"Stadoù Unanet". This is totally incorrect and is not portuguese. The correct translation in >portuguese is "Estados Unidos".
>
>I think these json files are not trustable at moment.

@elieserdejesus I checked the pt.json:

![image](https://cloud.githubusercontent.com/assets/15310433/14406242/c61f4f08-fe78-11e5-9191-e48ad3825103.png)

**Comment by jonjamcam** [comment]
@elieserdejesus Japanese works using the a nekudo app. It's not "jp". you have to use "ja"

![image](https://cloud.githubusercontent.com/assets/15310433/14406401/c9d65250-fe7c-11e5-9a7a-f3517c16105c.png)

**Comment by elieserdejesus** [comment]
Nice news @jonjamcam , let's adopt the nekudo webservice. Using this solution we need just discuss how handle the cache. Just to sumarize, I will copy/paste the idea I wroted before:

**How can we deal with the obsolete country names cache?**

The current cache format is something like:
IP => contry_name_in_english

We can change this to something like this?
IP => [en:country_name_in_english, fr:country_name_in_french]

**Comment by teamikl** [comment]
@elieserdejesus 

about database, two key => value pairs.

- IP => country code
- LANG file: country code => country name

QMap can be the simple key/value database.
LANG files can be embed resource in JamTaba.

if we need scale, then SQLite is often used as embed database module. Qt support sql module.
(but may be require re-build qt for static?)

possible scenario is if IP entry was too much data.
IPv4 address can pack into 32 bits (4 bytes) and country code is 2 bytes.
6 bytes for 1 entry, type info will be added though, its small.

just note:
long time ago, I had see stat list how many user names (not IP though) in NINJAM public servers.
500+ users in several years. that still 3000 bytes we can ignore the size cost.
but the numbers of object entries is sometime performance problem in a programming language which has GC.
I had not do stress test for Qt's objects.

**Comment by teamikl** [comment]
@elieserdejesus 

> It's not translated in portguese file (br.json). I look other files and somethings are translated, but I'm not shure. Maybe this is an incomplete resource missing some translations.

I could check was only ja.json.
was that incomplete, machine translated result ?

I think this resource was missing country code
the file path is ./locale/(language code).json

**Comment by elieserdejesus** [comment]
`the file path is ./locale/(language code).json`
Ok Tea, I was using the country code, my bad.

About the database, you writed:
`QMap can be the simple key/value database.
LANG files can be embed resource in JamTaba.`
Jon tested the nekudo webservice and is working, I think this is the best and simple solution: [http://geoip.nekudo.com/api/87.79.99.25/pt/short](http://geoip.nekudo.com/api/87.79.99.25/pt/short)

@teamikl , are you considering this solution? I'm asking because you mentioned a "database".

**Comment by teamikl** [comment]
@elieserdejesus 

I did not see about nekudo, yet. the API looks nice.

I wrote the approach assumed have the translation database as embed resource, though.
It is just idea for the cache's data structure. (no matter where the translated data come from)

now i see that you was thinking to cache the json result data.

**Comment by jonjamcam** [comment]
About the click names I think change to universal names is enough (i.e. tic-toc):

1.- "Custom Click" > "Custom"
2.- "Default" is already universal.
3.- "Finger Snap" -> "Snap!"
4.- ninjam click -> "Ninjam"

**Comment by jonjamcam** [comment]
@elieserdejesus and @teamikl . In case you like the idea it looks like this:

![image](https://cloud.githubusercontent.com/assets/15310433/14573466/9adcf590-032b-11e6-8db6-259a82e1d2c7.png)

**Comment by elieserdejesus** [comment]
Jon, It's perfect for me. This is the easy and good enough solution. It's complicated translate these metronome names.

**Comment by elieserdejesus** [comment]
The name "Custom" can be a little confuse, because in the same preference window we have the options to choose **custom metronome sounds**. I suggest change "Custom" to another name. No idea about a good name :(

**Comment by jonjamcam** [comment]
ok. I just PR, but let's wait until we find a better name for the custom. Then I commit.

**Comment by elieserdejesus** [comment]
Jon, I see the "Custom" is a bit more high pitch then "Default". And sounds like a [clave](http://imagem.buscape.com.br/guiadecompras/Claves.jpg) for me.

My name suggestions are:
1 - HighPitch (is not unversal enough)
2 - Clave (a bit more universal)

**Comment by jonjamcam** [comment]
@elieserdejesus . I tell you how it was made. It's a stereo file that has the ninjam click on one side and the jamtaba click on the other. The accent is done inverting the channels :D. It's made for drummers.

**Comment by jonjamcam** [comment]
Ok. the PR is updated now.
