### ISSUE TITLE
Changing language replaces the user name for the old "your controls" text

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#295]
![user name change](https://cloud.githubusercontent.com/assets/15310433/14394505/f926b2f0-fda2-11e5-9884-c95dcf98e132.jpg)

**Comment by elieserdejesus** [comment]
Ops, my bad! I forgot to check this possibility.

**Comment by teamikl** [comment]
This is a question as user side view point.

How could I change username without restart JamTaba ?

I had entered room as "test" by mistake, I wanted to change name but
second time the name input dialog was not shown.

**Comment by elieserdejesus** [comment]
@teamikl  and @jonjamcam , I will create a new issue to discuss a better way to handle the user name changing. This is the issue: #296

**Comment by jonjamcam** [comment]
This was solved in https://github.com/elieserdejesus/JamTaba/issues/296
