### ISSUE TITLE
Allow user name change

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#296]
In the issue #295 we start a discussion about improvements in user name change. At moment Jamtaba users can't change the user name without restart Jamtaba.

My initial idea is:
1 - Change the user name widget (a simple label at moment) to an editable/input widget (QLineEdit). Using this approach users can type your names in this field.
2 - First time Jamtaba is started there's no user name saved in .json file. So we can show a string "your name" in the current "your controls" field. 
3 - The user name dialog will be eliminated, and I will love this :)  If users don't change "your name" the user name in the server will be "your name". It's a very good name, like "anon" :)
4 - If the user name is changed when jamming (connected in a server) we need show a message like "Your new user name will be used when you connect in a new server". It's not possible change the user name in Ninjam protocol.

@jonjamcam and @teamikl , please share your thinkings!

**Comment by jonjamcam** [comment]
I like it! My only concern is that is you allow changing user name TEXT while connected to a server and not perform the actual change, this can confuse users about what name they are actually using (specially with the VST Plugin as no other feedback is available). A more intuitive approach I think is:

1.- Do not allow the name to be changed if connected to a server, so if someone tries to change the name during a session, then a message will warn him this can't be done while connected. Maybe use a  gray or white color for the name as a visual feedback for this.

2.- when not connected, use green color for the name (or the background) so users know they are allowed to edit it (to be used in the next session).

**Comment by jonjamcam** [comment]
> If users don't change "your name" the user name in the server will be "your name"

May I suggest (if possible) to use the computer name to generate a correct identity automatically (similar to what git console does for commits). I know this is a windows feature, but not sure about mac or linux

**Comment by elieserdejesus** [comment]
`use the computer name to generate a correct identity automatically`
Nice idea, I'm 99% shure this is possible and using Qt this will be easy to do.

**I have another idea for the feedback for name changing:**
When users are jamming we can disable the user name input field and show a lock icon in the field
https://cdn1.iconfinder.com/data/icons/free-98-icons/32/lock-16.png

**Comment by teamikl** [comment]
> 1. Do not allow the name to be changed if connected to a server
:+1: not change during a session.

my suggest, read-only and editable attribute for the text input.

read-only and enable/disable are a bit different stuff.
I am not sure Qt's stylesheet support those attributes.

> It would be very strange to enter a server full of "your name" players in the future! :D.

it's same there were a lot "anon" in the past!

"your name" can be placeholderText ? (QLineEdit has the property)

**Comment by elieserdejesus** [comment]
@teamikl , Jon suggest a cool idea for the placeholder text:
`use the computer name to generate a correct identity automatically`

I think we can "guess" the user name using **QStandardPaths::HomeLocation**. It's not 100% accurate, but I think is a very good guess about the user name.

**Comment by jonjamcam** [comment]
> I have another idea for the feedback in name changing:
When users are jamming we can disable the user name input field and show a lock icon in the field
image

much better!

**Comment by teamikl** [comment]
@elieserdejesus 

that is maybe default name ? used when users did not input any name.
placeholder is a text like "input your name" when the filed was blank, then it's show gray color text.

sending such environment variable info, people may worry the privacy.
there ware people who may use real name there,
It's not good if used as default name without their accept.

**Comment by elieserdejesus** [comment]
`sending such environment variable info, people may worry the privacy.`
I understand and agree. Use the "home location" as user name without confirmation can be too much invasive.

So, summarizing the discussion until this moment we have:
1 - Let's use a placeholder text "your name" in input field
2 - when connecting in a server we need show a user name input dialog if user don't fill the user name (still using the placeholder text). 
2.1 - Can we use the "guessed" user name from "home location" in the user name dialog? In this case user is confirming the "guessed" name.
3 - When user is jamming the user name field is changed to **read-only** and a **lock icon** appears in the field.

**Comment by jonjamcam** [comment]
> Can we use the "guessed" user name from "home location" in the user name dialog? In this case user is confirming the "guessed" name.

I agree with the privacy concerns. I think a name "suggestion" is a better approach (if name is ASCII). Additionally some names could be in other non-.ASCII alphabets and in that case the "suggestion" willl not work. Maybe a new issue is better for the "suggestion" so not to mess things up.

**Comment by teamikl** [comment]
@elieserdejesus 

the name input widget can have validator?

about allow non-ASCII alphabets
I remember the official client UI did not allow,
but need to see how it's handled in protocol and server implementation

- if user name was used to construct file name, must be escaped.
  this is even in ASCII only, path separator characters etc.
  - have to care server side case, e.g. ninbot use user names in the file.
- I did not touch about userName payload count ninjam/ClientMessages.cpp
  this may have same issue #294 for non-ASCII characters user name.

@jonjamcam 
> Maybe a new issue is better for the "suggestion" so not to mess things up

 Good idea about the "suggestion" :+1:
about non-ASCII alphabets for username, currently that is NINJAM's limitation.
JamTaba can implement however have to communicate with existing server and another clients.

**Comment by jonjamcam** [comment]
>Good idea about the "suggestion"

@teamikl I think Elieser already implemented this, but he calls it "guess" here: https://github.com/elieserdejesus/JamTaba/pull/298#issuecomment-207856890

**Comment by teamikl** [comment]
@elieserdejesus 

> I hope using the lock icon we don't need textual explanations.

it's good to show in visual icon, with explain in tool tip text also be more helpful.
at the moment when user see the lock icon, they may want to change the user name.
then tool tip can have short guide as explanation: disconnect server to edit this field.

for me the lock icon is good enough.
I know lock icon are often used for read-only visual. this is about another used cases
Lock icon also may reminiscent something private or secret things to users.
e.g. desktop use lock icon for require admin password.

I am not the accessibility expert, perhaps there are guideline for modern application looks?

**Comment by teamikl** [comment]
@jonjamcam 

> Elieser already implemented this

Ok thank you, now I have tested!

**Comment by jonjamcam** [comment]
Tested too @teamikl . It's really good!

**Comment by jonjamcam** [comment]
@teamikl One question: was the login suggestion close to your name? and did it appear in Japanese?

**Comment by teamikl** [comment]
@jonjamcam 

> One question: was the login suggestion close to your name? and did it appear in Japanese?

for me it shown "ikkei" my name in alphabets.

I use ASCII only letters as user name. Because I had experience that Japanese characters in path 
became often problem in foreign software. but other people may use Japanese letters there.

**Comment by elieserdejesus** [comment]
@teamikl , I understand your points about the lock icon, but I don't have another ideas at moment.

Add a tool tip in the user name field when is read-only is a good solution in my opinion. I think the tool tip text need explain why the field can't be edited. My suggestion is: **The user name can't be changed while you are jamming!**

**Comment by jonjamcam** [comment]
> @teamikl , I understand your points about the lock icon, but I don't have another ideas at moment.

@elieserdejesus what do you think about a freeze icon?

![image](https://cloud.githubusercontent.com/assets/15310433/14411422/13978430-ff1e-11e5-8eec-fe403370b884.png)

or

![image](https://cloud.githubusercontent.com/assets/15310433/14411420/fe835ec0-ff1d-11e5-8b23-99fbaeb31b33.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , searching in a icon database for "read-only" or "readonly" I see the two main variations are a lock and a closed eye icons: [https://www.iconfinder.com/search/?q=readonly&minimum=16&maximum=32](https://www.iconfinder.com/search/?q=readonly&minimum=16&maximum=32)

**Comment by teamikl** [comment]
@jonjamcam 

it's unique! I like though but I had not see others use the icon for this use.
I think the point here is it's easy to understand for everyone or not.

modern application trend is Universal design and accessibility,
following the guideline (if there was) is easy and good solution.


@elieserdejesus 

Editable <-> read-only (non-editable) are opposite

how about  pencil icon and pencil with X mark icon ?

**Comment by elieserdejesus** [comment]
@teamikl , I think this is a good idea. Now I see the problem is use only one icon. If we use two lock icons (open and closed lock) the feedback is improved. But the pencil icon is more intuitive then a lock icon. 

If you know some cool pencil icons please share.

**Comment by teamikl** [comment]
this idea was I got from thinking about @jonjamcam 's icon,
I think first that was icon has two opposite state

it was lock <=> unlock then
what is freeze <=> melt? flame? ... they are hard to image for writting

this is research how it's used,
for linux, freeze/melt were used for compress/uncompress (http://linux.die.net/man/1/freeze)

next I think is write <=> read
pencil and book ... book icon was ambiguous, look like blank note (it's for write, not readonly)
then I arrived write(editable) <=> read(non-editable)
semantic is a bit different, but I think looks intuitive too.

As total design, pencil with X mark, image if the X mark was red color.
that may catch user's attention. user see the icon during session.
X mark remain something bad, should be fix etc..
there user name is not editable is not so important info.
it is useful only when user wanted to change. I think lock icon with mono color is better for this point.

> If you know some cool pencil icons please share.

I did not search this. I think monolithic color is better for this use. and circled slash instead of X mark.
just google image search:

![non-editable icon](http://thumb7.shutterstock.com/display_pic_with_logo/971035/345157865/stock-photo-pencil-forbidden-icon-on-white-background-345157865.jpg)

This is not usable file (license and watermark), this is for share the image.

**Comment by elieserdejesus** [comment]
I love this icon, I think is very intuitive use the pencil and the "no pencil" pair.
I will search some similar icon soon.

**Comment by jonjamcam** [comment]
![](http://uxrepo.com/static/icon-sets/windows/svg/checkmark-pencil.svg)

![](http://pinpointlaser.com/wp-content/uploads/icon-pencil-square-o-000-200x200.png)

This looks pretty easy to modify to "no pencil":

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pencil_BLACK-01.svg/2000px-Pencil_BLACK-01.svg.png)

**Comment by elieserdejesus** [comment]
I like the last one. @jonjamcam , you have the web site link to download a small version? In general resize will loose quality.

**Comment by jonjamcam** [comment]
here : https://commons.wikimedia.org/wiki/File:Pencil_BLACK-01.svg

**Comment by elieserdejesus** [comment]
Ah, it's a svg, SVGs can stretch without loose quality. Thanks for the link!

**Comment by teamikl** [comment]
I vote :+1: for the circled pencil

and add back-slash to non-pencil.

**Comment by elieserdejesus** [comment]
Closing the issue, the PR is merged in master!
