### ISSUE TITLE
Chord progression display

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#3]
reprogram the Jamtaba 1 chord progresison display

**Comment by elieserdejesus** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/1012741/11188819/f592f19e-8c73-11e5-8e13-64c8b2863242.png)

![image](https://cloud.githubusercontent.com/assets/1012741/11188851/1f0cc1b2-8c74-11e5-8980-b1698420c3c7.png)

**Comment by Ezeer** [comment]
woaw ! Some work for @jonjamcam now eh eh .
good job !
^^

**Comment by jonjamcam** [comment]
at last!

 BTW remember guys the last version of the pdf manual will always be at the bottom of the user's guide page. I'll keep it updated.

**Comment by Ezeer** [comment]
**BTW remember guys the last version of the pdf manual will always be at the bottom of the user's guide page. I'll keep it updated.**
Good idea ! Thx Jon !

**Comment by Ezeer** [comment]
lol , you give me the chord names i make Jamtaba draw midi bars for you all .
eh eh eh
![drawbars_explained](https://cloud.githubusercontent.com/assets/1283808/11199973/8840f820-8cd2-11e5-94d1-0deef852acf9.jpg)

nice article here -> http://www.hammondjazz.com/drawbars.html

**Comment by jonjamcam** [comment]
chords recognized fine.......win7 x64 jamtaba 2.0.6alpha32bits.

![chords](https://cloud.githubusercontent.com/assets/15310433/11200183/84db81f2-8cb2-11e5-80f0-6f8c2e625f62.jpg)

**Comment by elieserdejesus** [comment]
The country flags are ok jon? To run a clean test is better delete your "cache.bin" file. You will loose your cached info and force Jamtaba to redo the IP translations using the new service.

**Comment by elieserdejesus** [comment]
The translation icon don't make sense in chord messages. Let's hide this in future versions.

**Comment by jonjamcam** [comment]
cleared cache and tested again....working......takes about 30 seconds to display the flag

**Comment by NakajimaYusuke** [comment]
Hi, this is my first post to GitHub.
I came here to say thank you and good luck to Jamtaba developers.

This chord progression display function is  really awesome.
I've been waiting for such feature in NINJAM Client for a long time.

This is not a mere chords display.
We can read the length of each chords from this chord progression display.
I thought this display format is very suitable for NINJAM session.

I'm counting on you guys!
![chords2](https://cloud.githubusercontent.com/assets/15982547/11395019/e46e1d14-93ab-11e5-8ea5-fac33c625bf8.png)

**Comment by elieserdejesus** [comment]
thanks Nakajima! You tested a interest situation, in general I always write the chords using a blank space as chords separator, but I see the chord recognition is working without spaces too, this is very good. Thanks again for your positive feedback!

**Comment by jonjamcam** [comment]
Very interesting. I'll update the manual with this information. Thanks Nakajima.
