### ISSUE TITLE
find the best accent value when change bpi

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#30]
quando trocar de bpi ver se ainda é possível usar a mesma acentuação procurando pelo valor antigo na nova lista

**Comment by elieserdejesus** [comment]
Done!

**Comment by jonjamcam** [comment]
I think this I found something related to this thread? If not I'll create a new one.

alpha 2.0.6 fixes the accent value to 4 every time I enter a a room. Changes are kept only while connected to the server. If you go to another room it sets by default to 4 again.

**Comment by elieserdejesus** [comment]
Fixed Jon, I fix the accent value to test this issue and forgot the fixed value. It's fixed now, when you enter in a room the accents combo is off by default.
