### ISSUE TITLE
User's Guide update

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#300]
- [x] Separate Each Chapter of the old Manual into folders.
- [x] Create the new interface with individual access to each topic as individual pages.
- [x] Rewrite the Wiki Page creating separate pages instead of one big page with links.
- [x] Fixed the Manual's main page url to match Jamtaba's link. 
- [x] rewrite "join a public server" Chapter including the new user name interface.
- [x] rewrite "Inside a Ninjam Server (overview)" Chapter (new pictures and new features).
- [x] rewrite "The Metronome use Explained" Chapter.(Custom metronome and new interface).
- [X] rewrite "Other Musicians Controls". (new pictures and new features).
- [X] rewrite "The Chat Window".
- [x] Change images in "Showing Chord Progressions during a Jam".
- [x] write "The Language Menu" Chapter.

 (This tracklist represents the changes in my fork, not yet in this repository) :

[moved from top] @elieserdejesus I think it's about time for the manual to incorporate the new stuff. Last version was 2.0.6!

**Comment by elieserdejesus** [comment]
Ok Jon. Can you change the manual in your fork and create a pull request? I'm not shure if pull requests work in this case.

**Comment by jonjamcam** [comment]
Ok. We try that.

**Comment by jonjamcam** [comment]
@elieserdejesus , @teamikl . The new Manual is still WIP (lots of new stuff to add), but I decided to change the navigation style. Let me know your opinions :D.

**Comment by elieserdejesus** [comment]
Perfect navigation Jon! It's a navigation menu and a features summary at same time. In general people are looking for some very specific detail, no need to read all manual content. 

Nice job!

**Comment by jonjamcam** [comment]
>Can you change the manual in your fork and create a pull request? I'm not shure if pull requests work >in this case.

This post says they don't :(.

http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by elieserdejesus** [comment]
Jon, I checked the post and see I can integrate your changes. I tested and works, your changes are integrated now. 

I discover the wiki is a separated repository in github. So the first step was clone the wiki repo in my machine:
`git clone https://github.com/elieserdejesus/JamTaba.wiki.git

cd JamTaba.wiki 
`

The second step was "download" the changes directly from your fork wiki:
`git pull https://github.com/jonjamcam/JamTaba.wiki.git master`

The last step is just a **push* to the JamTaba.wiki repository. 

When you have new changes to integrate just create an issue and I do the merge using these steps.

Thanks for the nice work!

**Comment by jonjamcam** [comment]
but, but...it's not finshed yet! :D

**Comment by elieserdejesus** [comment]
haha, no problem. Now we know the integration is possible :)

**Comment by teamikl** [comment]
@jonjamcam 

good job!  

> The new Manual is still WIP (lots of new stuff to add)

if you will work WIP on github then this is guide, first of start WIP
can you make the [TaskList](https://github.com/ZenHubIO/support/issues/160) on git issue comment ?
github will show progress bar and that task list will be check list for reviewers.

and Q. How do you make/change the style of manual?

Recently, I am studying epub3 (e-book) format personally,
If you have interest in programmer's documentation tool, we can share the info.
(the manual was generated from text data then the source files can be into repo)

**Comment by jonjamcam** [comment]
>can you make the TaskList on git issue comment ?

@teamikl Yes. It's in the second comment now https://github.com/elieserdejesus/JamTaba/issues/300#issuecomment-208048656 . Thx for the tip!

> and Q. How do you make/change the style of manual?

I do all the work using a PDF editor. When finished I copy the content to the website manually.

> If you have interest in programmer's documentation tool, we can share the info.

Sure! I'm interested, Tea. I'm swimming into developer's waters and I feel pretty naked right now :D

**Comment by teamikl** [comment]
@jonjamcam 

ah there were already,
then can you move the tasklist to top comment.

If the tasklist was on the head of the first comment,
progress bar of task done(checked) list will be shown on issue list.


about the document

you know markdown format, that is we are writing here on github issue.
there are a lot converter (e.g. http://pandoc.org/)
it's possible markdown text -> PDF, EPUB, HTML etc
if the content source was text, then it easy to make translations.

**Comment by jonjamcam** [comment]
>move the tasklist to top comment.

@teamikl 

there you go! cool!

![image](https://cloud.githubusercontent.com/assets/15310433/14438659/8b44a744-fffd-11e5-9c20-7f0b6dfb3682.png)

**Comment by teamikl** [comment]
@jonjamcam 

> I think the images are very important in the case of Jamtaba

True, but other side
image is hard to translate, translator have to take the same image and edit.
this is cost for origin creator too, when image is updated,
then update text and layout on image editor.

to avoid this, e.g. just mark number in image, instead of embed text in image.
then write explanation on text source and text can have embed image.
this approach will make image resource share-able for translations.


There were demerits of those documentation tools
they may not support fancy look & feel which you want,
those tool is often programable/customizable mean they provide the flexibility
but users have to write plugin/extension by own if there was not supported officially.


about document hosting, https://readthedocs.org/
this is possible scenario update document triggered by github commit. (via webhook)
I had not try this yet. this is one of task I wanted to try.

**Comment by teamikl** [comment]
@jonjamcam 
> In this update, I'm simplifying the most

Ok, I am thinking translation is for another chance.

Perhaps, I need to build the instructions first,
For windows, it was hard to setup those tools environment.

**Comment by jonjamcam** [comment]
@teamikl If I understood OK, you're talking about automated translation to any language for the wiki using? That sounds very interesting!

**Comment by teamikl** [comment]
@jonjamcam 

not automated translation
translation idea was separate image and text, then text will be translatable,
the automation idea was about deploy, when document source are committed
automatically generate HTML/PDF/EPUB then publish to web.

**Comment by jonjamcam** [comment]
>the automation idea was about deploy, when document source are committed
automatically generate HTML/PDF/EPUB then publish to web.

Sure. That sounds great! To be able to download an Epub made on the fly with updated info.

> I think these rest topics should be separate issue.

I agree. Let's discuss it separately.

**Comment by jonjamcam** [comment]
@elieserdejesus @teamikl Just finished the first revision of the manual. Probably there's some mistakes, but overall the new features and interface are there. Ready to publish..

**Comment by teamikl** [comment]
@jonjamcam 
good job. Is That the latest update is [Jamtaba's user guide](https://github.com/jonjamcam/JamTaba/wiki/Jamtaba%27s-user-guide) ?

I have little feedback

- add the target Jamtaba's version to top page
  - users can notice if the version was old or not.
  - or they may misunderstand the target version is v2.0.4 (shown in the introduction image)

during watching images in manual,
I noticed preset names had ".json" suffix @elieserdejesus they can be stripped?

**Comment by jonjamcam** [comment]
Thx for the review @teamikl . Added your suggestion in the first line of the root directory. The problem is if I change the title to "Jamtaba's user guide 2.0.14", then the link to the page is changed too.

 Did you find it easy to read and navigate?

**Comment by elieserdejesus** [comment]
> I noticed preset names had ".json" suffix @elieserdejesus they can be stripped?
Yes Tea, let's strip the json. New issue added #304.

**Comment by elieserdejesus** [comment]
@jonjamcam , the wiki is updated. Thanks for this nice job!

**Comment by jonjamcam** [comment]
Thx you both guys. Your work is very inspiring to me.
