### ISSUE TITLE
some room in server have no more enter/listen buttons ?

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#302]
Since yesterday some room in jamtaba cant have an access ? ninbot 2049 2051 ninjamer 2050

i try in reaninjam  and there not any problem.

any one know why ?

**Comment by jonjamcam** [comment]
Hi double. Still happening? Just tested ninbot 2049, 2051 and ninjamner 2050 and no problem. Are you being disconnected? If so check this issue https://github.com/elieserdejesus/JamTaba/issues/294. It's fixed for next release.

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , I tested these servers here and are working ok too. Maybe the "enter button" problem is something related with full servers? If you see the problem again please try save a screenshot.

**Comment by DoublebassOO** [comment]
yes still same room without enter button today
and they are empty and ok with reaninjam

No wrong caracter in the name of the room  its :  Play something

.. oh i change my name  from Halfbass to Doublebass and the buttons are back here  :)

what is associate to the name we give to enter in room  ?  pb of jamtaba window to large in full size with my name doublebass  not with halbass  ?

how to clean it ?

**Comment by elieserdejesus** [comment]
@DoublebassOO , please check [this issue](https://github.com/elieserdejesus/JamTaba/pull/299). 
This will solve your problem? If I'm understading correct the buttons are not visible, but you have a horizontal scrollbar in bottom.

**Comment by DoublebassOO** [comment]
Thanks Elieser 
But dont know if it i miss something or if it is my bad english , But how to change the layout, as you suggest  ? 
how the user name affect the layout ?

**Comment by elieserdejesus** [comment]
@DoublebassOO , 

> But how to change the layout, as you suggest ?

the link I posted before is a bug fix, will be available in the next Jamtaba version. 

> how the user name affect the layout ?

Big user names need more horizontal space, and the box used to show the user names in Jamtaba will grow (more width) to show big names. User names appears in 2 collumns, right? If the first collumn is big (wide) the second collumn will be cropped in small screens, and possibly the buttons (enter and listen) will not be visible. To see the buttons you need use the horizontal scrollbar in bottom.

The main layout problems in the current Jamtaba version is not your name. The problem are the AndyMc servers names. These servers are using big names and breaking the Jamtaba layout. But no worries, will be fixed in next Jamtaba version.

**Comment by DoublebassOO** [comment]
so i misunderstood  ... (shame on me  :) )


oh  i discover the little squares horizontal and vertical in the corner up right (  in the live room view)   (with vertical grey and horizontal black )
they change the view of ther different server  in rooms play mode i dont need to scroll anymore . 


For the first problem why those buttons was unable ; does it mean that as Halbass i was still connected i those rooms ? Why changing my login user  name resolve the problem ? 

thanks again

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO 

> For  the first problem why those buttons was unable ; does it mean that as Halbass i was still connected i those rooms ? 

The buttons are **unable** or **not visible**? I was supposing **not visible**.  About the second question: Jamtaba receive a fresh list of connected users every 30 seconds. If you disconnect from a server your name still appear in this server for some seconds. 

> Why changing my login user name resolve the problem ?

I'm not shure if the user name changing really solve the problem. I think is just a little coincidence.

**Comment by DoublebassOO** [comment]
yes the button were not visible but it was still unvisible after one hour ; i try it the day before and this happen . And no i dont really think it was a coincidence . 
Because it happens i second time (maybe the reaper  configuration memory ) and only this change of user name resolve the problem.  Yes forget to precise it  : jamtaba in vst mode.

But dont take care ..all works fine ......it was just to understand more jamtaba  

Cy great Elieser.

**Comment by elieserdejesus** [comment]
Ok @DoublebassOO , I hope this problem is solved in the next Jamtaba release.

Double, we are translating Jamtaba. The new version (2.0.14) will be translated to Spanish (Jon), Portuguese (Me) and Japanese (Tea). Are you interested in translate Jamtaba 2 for French?

**Comment by DoublebassOO** [comment]
for sure  all that could help you  and Jamtaba . Even my knowledge in computer is what it is   :).

you are wellcome   :)

**Comment by elieserdejesus** [comment]
Nice @DoublebassOO , I will create a new issue focused in these new translations. This is the new issue #315

**Comment by DoublebassOO** [comment]
Hey Elieser !

here is my contribution ..the ts files   . wow lot to translate :)

Cy

2016-04-16 0:41 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com>
:

**Comment by elieserdejesus** [comment]
@DoublebassOO , I can't see the TS file. I check my email and no attachment too. Can you send again , please?

**Comment by DoublebassOO** [comment]
ah strange  i try it again

2016-04-20 14:53 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
Closing this issue!
