### ISSUE TITLE
Add tool tip in user name input field

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#303]
@teamikl suggestion: **can add tooltip for the input field?**
that describe allowed letters and explains the space change to underscore.

**Comment by elieserdejesus** [comment]
@jonjamcam , are you interested in code this feature?
If yes, check **MainWindow::setUserNameReadOnlyStatus**.
At moment just the tooltip for read-only status is used, the tooltip for "non-read-only" is an empty string.

**Comment by jonjamcam** [comment]
Sure! I do it.
