### ISSUE TITLE
BPI/BPM feedback needed inside the server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#308]
This is an important detail. As we all know the only feedback we have of what BPM/BPI is the server currently using is the BPM/BPI combo boxes.

 So what happens in those cases that we type a value in the box to vote, but  the vote does not reach majority is that we are stuck with a suggested BPM/BPI in the combo box, but the actual BPI/BPM didn't change, so now we don't remember what values we are dealing with. The solution seems simple to me:

![image](https://cloud.githubusercontent.com/assets/15310433/14503266/b24b6bbe-0185-11e6-8730-bc1c692467be.png)

**Comment by elieserdejesus** [comment]
Good idea. 

I think at moment the combobox value is not changed/undo when the vote not reach majority. We can think in a solution for this problem too. The difficul in this case is **how we know the voting was aborted**? 

**A first idea**: the "voting" chat messages text contains the expiration time. We can use this time value, and if this time is expired before a change in BPI or BPM the combobox value is setted to the current BPI/BPM. 

**a second idea**: If I remember correctly the expiration time is 60s (configurable in server?). In this period (60 s)  users will see a "wrong" value in the combobox. I think use a different color in combobox text is interesting. For example, while waiting for votes the combobox text color will be yellow (same color of transmiting button in "preparing" state). When the votes are confirmed the combobox text color is changed to the "normal" color.

**Comment by jonjamcam** [comment]
>the expiration time is 60s (configurable in server?)

yes. Here's the section of the ninjamserver.cfg file that determines that:

![image](https://cloud.githubusercontent.com/assets/15310433/14504372/f1acc438-018a-11e6-880a-ca7352436096.png)

The second idea is great! :+1:
