### ISSUE TITLE
User name text is behind pencil icon

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#309]
![image](https://cloud.githubusercontent.com/assets/1012741/14544687/a5e6fc12-0270-11e6-8342-b49255e21602.png)

**Comment by jonjamcam** [comment]
May I add a suggestion for the pencil? 

![image](https://cloud.githubusercontent.com/assets/15310433/14554268/31ca5890-02c2-11e6-9eac-844b0a034039.png)

Circle a bit wider and red

**Comment by jonjamcam** [comment]
Now it looks that the first ten characters fit nicely into the box:

![image](https://cloud.githubusercontent.com/assets/15310433/14580625/9af205d8-03a9-11e6-8deb-dea2395e55ee.png)

, So what to do with the remaining six? Some ideas:

1.- Move the pencil up when the 11th character is typed:

![image](https://cloud.githubusercontent.com/assets/15310433/14580646/8d441934-03aa-11e6-8a63-733a3745622c.png)

Another issue here is that the 16 characters allowed do not fit entirely i the window, so may be decrease the size of the font combined with the moving up of the pencil can solve it.

**Comment by elieserdejesus** [comment]
@jonjamcam and @teamikl , I reduce the pencil icon a little bit and align in top. This is the result:
![image](https://cloud.githubusercontent.com/assets/1012741/14583224/9ef444f0-03f1-11e6-87af-78d40d03a404.png)

In my opinion is not good enough. It's difficult put these elements in the right place because we have limited horizontal space. I think the better/simplear approach at moment is show the icon only when the user name is read-only. In this state is no problem if the user name text is behind the icon.

I have another idea: remove the "local tracks collapse button" to gain some horizontal space. Put the "collapse option" in View menu as a menu item. But some users are used to collapse using the button, we are removing a possible interesting thing from the GUI.

Another ideas?

**Comment by jonjamcam** [comment]
How about this?

![image](https://cloud.githubusercontent.com/assets/15310433/14583294/1718d0ca-03f4-11e6-82f0-f0007462d890.png)

**Comment by elieserdejesus** [comment]
I like the second idea, will fit very well in "mini mode", and this mode is usefull in VstPlugin.
The old string in top of local controls was "Your Controls", I think we can use this string again. When we need translate this string again :)
