### ISSUE TITLE
Country cache not working as expected?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#310]
It looks to me that some part of the cache is not working:

1.- Jamtaba  recognizes the coutries OK and language.

![image](https://cloud.githubusercontent.com/assets/15310433/14564542/5d091326-02fd-11e6-8799-1fce1112ddb4.png)

2.- Close Jamtaba, and relaunch:

![image](https://cloud.githubusercontent.com/assets/15310433/14564565/77874344-02fd-11e6-9e01-45dc3aafd530.png)

Jamtaba is trying to connect to ip-resolving site for the same participants

**Comment by elieserdejesus** [comment]
It's fixed in master Jon.

**Comment by jonjamcam** [comment]
Working fine most of the time, but it fails with for example English language and NORWAY country:

![image](https://cloud.githubusercontent.com/assets/15310433/14571057/a158114c-031d-11e6-818f-4b091f592054.png)


Tested ja, es and pt and it works fine. Why is english is not working?

**Comment by jonjamcam** [comment]
I'm testing in another computer with win10 and I have no problems with the Norway cache. Can you guys check please is this is happening to you too?

**Comment by jonjamcam** [comment]
Ok solved it deleting the old cache.bin file

**Comment by elieserdejesus** [comment]
Nice news Jon. I wrote a code to delete the old cache.bin file after load the content. I commented the "delete old cache" line to avoid problems in testing phase, but I think now it's time to remove the comment.

**Comment by elieserdejesus** [comment]
I pushed the change in master. Now the old cache.bin is autonatically deleted.

**Comment by jonjamcam** [comment]
Just tested. Working fine. the cache is deleted. Closing....
