### ISSUE TITLE
Flag and country for admin users

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#311]
I've noticed that some ninjamers have admin user/password. If they login to the server as admin, then their ip is not shown. This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/15310433/14569040/90881f48-0312-11e6-8109-622633c732c7.png)

Reaninjam shows this:

![image](https://cloud.githubusercontent.com/assets/15310433/14569128/10f6f0e6-0313-11e6-841a-426b2fdec596.png)

that looks to me the kind of ip I use to configure my own router! Is it local?

Maybe have a special icon for this type of login.

Another thing, for these users, this is what happens when you change language:

![image](https://cloud.githubusercontent.com/assets/15310433/14569307/45196e5c-0314-11e6-8570-1ed0e8dbd0d1.png)

**Comment by elieserdejesus** [comment]
> that looks to me the kind of ip I use to configure my own router! Is it local?

Exactly Jon, this local IP is useless for us. Is not possible translate this IP for a country.

I like the white document replacing the country flag in left side of "AndyMc" name. We can use this white document and remove the parenthesis.

**Comment by jonjamcam** [comment]
Yea, the parenthesis are not good.

The white page is OK, but I was looking for an icon that represents this "admin" or no-ip. I found some:

![](http://www.tuktukdesign.com/wp-content/uploads/2014/08/free-user-icon-download-tuktukdesign1.jpg)

this is funny:

![](http://uninovafapi.edu.br/wp-content/uploads/2015/01/1422576327_Account.png)

it's like too elegant. lol!

**Comment by jonjamcam** [comment]
some tests......

![image](https://cloud.githubusercontent.com/assets/15310433/14575290/2f84e59e-0337-11e6-9c11-b67a8372a427.png)


![image](https://cloud.githubusercontent.com/assets/15310433/14575118/26ad6aaa-0336-11e6-871b-39200555d562.png)


![image](https://cloud.githubusercontent.com/assets/15310433/14574942/dedb2dee-0334-11e6-934a-e998af2204ca.png)


I agree the blank page is still the best option although the anonymois mask is quite impressive!

**Comment by elieserdejesus** [comment]
Hehe, the last image is cool, but I'm afraid this can be offensive for some people. The other images are working good too, but I think this images are showing the "hidden IP guy" as a "special" person, because everybody have just a country flag, but this guy is "special" and have a nice "person icon". I prefer the white empty image because is just empty, no special meanings, it's neutral.

**Comment by jonjamcam** [comment]
True.

**Comment by jonjamcam** [comment]
solved in https://github.com/elieserdejesus/JamTaba/issues/521. Closing...
