### ISSUE TITLE
Linux 32 bits release

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#314]
I received an email asking about a linux 32 bits version. At moment the release is 64 bits only.

**Comment by jonjamcam** [comment]
@elieserdejesus, @teamikl I did a test in a laptop that has no qt installed. I installed QTlinguist and loaded my own es_CL file. All GOOD! I think this is the easiest way for non-coders!

**Comment by elieserdejesus** [comment]
The linux 32 bits installer is released. Tested in ubuntu 14 32 bits running in virtualbox.
