### ISSUE TITLE
Translations for French and German

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#315]
@DoublebassOO and @MagnusDrumsTrumpet, are you interested in translate Jamtaba to French and German?

If yes, please read this [document](https://github.com/elieserdejesus/JamTaba/tree/master/translations) writed by Tea. This is a "step by step" guide to translators. If you have some problem or difficulties please report here in this issue and we can help.

Thanks!

**Comment by jonjamcam** [comment]
@elieserdejesus, @teamikl I did a test in a laptop that has no qt installed. I installed QTlinguist and loaded my own es_CL file. All GOOD! I think this is the easiest way for non-coders!

As Tea, said in the document, the file must be prepared for any of us.

**Comment by elieserdejesus** [comment]
> the file must be prepared for any of us.

It's true, I will generate the .TS files soon and post here.

**Comment by elieserdejesus** [comment]
@DoublebassOO, you need a **.TS** file containing the english messsages used in Jamtaba2. This file will be opened in QtLinguist software, as described by Tea in **translators guide**. This is the file you need to translate in French. Please extract the **zip** content before open in QtLinguist: 
[fr_FR.zip](https://github.com/elieserdejesus/JamTaba/files/222173/fr_FR.zip)

@MagnusDrumsTrumpet, this is the file you need to translate in German (if you accept the invitation):
[de_DE.zip](https://github.com/elieserdejesus/JamTaba/files/222174/de_DE.zip)

**Comment by DoublebassOO** [comment]
1. Could you generate/update ./translations/(locale).ts file for me

Thanks

2016-04-16 13:58 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
@DoublebassOO , you can download the .TS file here in my last post. I put the link to the file in the comment. Maybe your email reader is filtering the link. Please check the post here in github if you have problems to download the file. You have a link for github in the bottom of your email message.

**Comment by MagnusDrumsTrumpet** [comment]
Oh sry didnt check email here longI will have a look on it)


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Elieser Ademir de Jesus <notifications@github.com> 
Datum: 16.04.2016  13:58  (GMT+01:00) 
An: elieserdejesus/JamTaba <JamTaba@noreply.github.com> 
Cc: MagnusDrumsTrumpet <jojo4u72@yahoo.com> 
Betreff: Re: [elieserdejesus/JamTaba] Translations for French and German
  (#315) 

@DoublebassOO, you need a .TS file containing the english messsages used in Jamtaba2. This file will be opened in QtLinguist software, as described by Tea in translators guide. This is the file you need to translate in French. Please extract the zip content before open in QtLinguist: 

fr_FR.zip

@MagnusDrumsTrumpet, this is the file you need to translate in German (if you accept the invitation):

de_DE.zip

**Comment by jonjamcam** [comment]
@tea @elieserdejesus Elieser. I think those .ts you posted above (https://github.com/elieserdejesus/JamTaba/issues/315#issuecomment-210797183) files are outdated by now.

So are we definitive about the new workflow for the translations? If so, double and magnus should be updated on the matter (https://github.com/elieserdejesus/JamTaba/pull/312#issuecomment-210984174).

**Comment by elieserdejesus** [comment]
French translation integrated, thanks @DoublebassOO :
![image](https://cloud.githubusercontent.com/assets/1012741/14676894/c42ceece-06e5-11e6-909d-518d383335ed.png)

@DoublebassOO , the file I sent to you was missing some phrases. You can see the "Your controls" in top left of the picture, for example. I will send you a updated file soon. You need translate just the new phrase.  Thanks again!

**Comment by jonjamcam** [comment]
fantastique! :D

**Comment by MagnusDrumsTrumpet** [comment]
cooool )
 i am at work on it too for german need some days)

**Comment by elieserdejesus** [comment]
No problems @MagnusDrumsTrumpet , in your time!  And please try QtLinguist](http://qt-apps.org/content/show.php/Qt+Linguist+Download?content=89360), it's easy translate using this tool.

**Comment by MagnusDrumsTrumpet** [comment]
hey ya)here the german translate i hope it will work ) made in Qt 4.6have fun )Mag 

    Elieser Ademir de Jesus <notifications@github.com> schrieb am 22:03 Mittwoch, 20.April 2016:
 

 No problems @MagnusDrumsTrumpet , in your time! And please try QtLinguist](http://qt-apps.org/content/show.php/Qt+Linguist+Download?content=89360), it's easy translate using this tool.—

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , thanks for your contribution!

**A little problem**: I can't see the attached file. We have the same problem when Doublebass send the French translation. I think this is a github limitation (no attachments).

We have two possibilites:
1 - You can login in **github** and post your file directly in github, no email attachment.
2 - You can send the file to my email: elieserdejesus@gmail.com

**Comment by DoublebassOO** [comment]
Hey  the team ! Hey elieser
I will probably have to correct  a lot  after seeing how it appears in the
windows of jamtaba

a big question was  if the caracters    like   é  à .... are accept in
jamtaba ?

tell me , so i could change it , it will be much more undesrtand for french
people

2016-04-23 14:11 GMT+02:00 MagnusDrumsTrumpet <notifications@github.com>:

**Comment by DoublebassOO** [comment]
even only on this window i  can see quite lot mistake of translation ....
 :o(
(

the translation depending on such lot factors  ... the context change the
meaning ...

2016-04-23 14:35 GMT+02:00 Armand Dumonteil <armanidu33@gmail.com>:

**Comment by elieserdejesus** [comment]
> a big question was  if the caracters    like   é  à .... are accept in jamtaba ?

Yes @DoublebassOO, I'm using these caracters in portuguese translation. And Tea is using the japanese symbols (very complex) without problems. The only limitation are the chat messages texts, but this is out of topic at moment. In user interface texts we can use special caracters without limitations.

**Comment by DoublebassOO** [comment]
here is a better one   ....
waiting the new jamtaba .. :)  cool


2016-04-23 14:39 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
@DoublebassOO , I can see the attachment, please send the TS file to my email!
Thanks!

**Comment by MagnusDrumsTrumpet** [comment]
hey,
 here i loaded it up cause i am not sure if you got the .ts file
 get it here :
https://www.dropbox.com/s/o15vb37ufkrwzym/german_DE.ts?dl=0

btw, i tried twicw by yahoo mail )? it didnt come as attatched wired)

**Comment by MagnusDrumsTrumpet** [comment]
Martin did little corrections too on it )
 here the newest .ts file

https://www.dropbox.com/s/wojf4c4zzmw3eho/german_DE24042016.ts?dl=0

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , thanks!  I will integrate your translation right now!

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , german translation integrated, this is the result:
![image](https://cloud.githubusercontent.com/assets/1012741/14768682/51fed0be-0a1f-11e6-80f8-89d7eb611857.png)

Thanks again!

**Comment by jonjamcam** [comment]
@elieserdejesus . In my system, the french locale is missing some strings:

![image](https://cloud.githubusercontent.com/assets/15310433/14769519/bc9fc9c6-0a30-11e6-9c66-97c73127dfec.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I send the TS file to Doublebass to update some phrases and some items are not translated, like "M" and  "S" for mute and solo. So it's normal see some different numbers in lrelease.

**Comment by MagnusDrumsTrumpet** [comment]
hey 
as i see one button is to small for text (listen and enter over rooms)
i took anothet word for enter ... here new file 
https://www.dropbox.com/s/0z1jtj4i1g30cya/german_DE25042016.ts?dl=0

**Comment by MagnusDrumsTrumpet** [comment]
hey 
one more translate sorry seems still to long, also i am not sure about the fit of other text´s in their field untill i can see it in the programm ) step by step we develop )
the newest .ts here
https://www.dropbox.com/s/u1395cg4p3ywzg4/german_DE2504201602.ts?dl=0

**Comment by jonjamcam** [comment]
@MagnusDrumsTrumpet download the pre-release and test!

https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.14-alpha

**Comment by MagnusDrumsTrumpet** [comment]
i changed it to the word   enter   again ) in this ts.
https://www.dropbox.com/s/u1395cg4p3ywzg4/german_DE2504201602.ts?dl=0

there are some lines not written or choosable in the ts file  dunno were they are nor who wrote them)
![panel01](https://cloud.githubusercontent.com/assets/15855828/14797153/6dc7709a-0b31-11e6-931d-1fdb56b99692.png)

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , I'm trying to integrate your new translation file but I see the entire file is different. The problem is when I received your TS file I need remove some context lines info to avoid generate tons of changes in every TS files. So, your local file and the file store here in github are not the same, the file in github is small because some context lines are stripped. 

We have some options to improve this workflow:

1 - You can download the TS file from github before start a new translation update. Using this approach you will always work in the latest file version.

2 - I can strip the context info from your files when a new file is received. But this will generate some extra work in my side every time you change something in the translation file.

3 - (a bit complicated) You can strip the TS file using the command **lupdate** described in [translations guide](https://github.com/elieserdejesus/JamTaba/tree/master/translations). This is the more **geek** approach, but if you like ... :)

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , I changed the german (it's german or deutsch?) translation to match your picture. 

> i changed it to the word enter again ) in this ts.
The word "enter" will not be translated? In your file the translation is just "enter", same as english.

![image](https://cloud.githubusercontent.com/assets/1012741/14819999/0319f67c-0b9b-11e6-8661-6fb0c9b9c530.png)

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , as you can see in the picture above the term "sein Kontrollbereich" is cropped. Some suggestion to a small word? :)

**Comment by MagnusDrumsTrumpet** [comment]
coool)  "verbunden als elieser"   perfect) i choosed mostly to use small letters  only VST or maybe Jamtaba should be written with big letters ? question of taste
should be   "dein Kontrollbereich" but to get it shorter  "Dein Kontrollfeld"
yes i choosed   "enter"  cause all to long or sound wired) enter exists long in germany so cool to use
so can you send me your modded .ts file or? and i chanche only the things i see to be changed

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , you can get the latest TS file here in github, no need to send you the file by email. In **top left** you can see the **code** tab. Click in the **code** tab and you can navigate in all Jamtaba files. The TS files are in the folder **translations**.

I don't change the "dein Kontrollbereich" and "enter". Can you change and post the file here (just drag the file)?

**Comment by MagnusDrumsTrumpet** [comment]
https://github.com/elieserdejesus/JamTaba/commit/c8ace4ef03df88f93df7e86f4eb763272d1170ed

omg github jungle )  hope it is right

**Comment by elieserdejesus** [comment]
Thanks @MagnusDrumsTrumpet , the changes are integrated. You can check the changes here 3a0f45629b8c46f65e9df80e250d583bc93e972a

**Comment by MagnusDrumsTrumpet** [comment]
ok cool way to edit ) thank you elieser

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , I'm curious! You edited the file directly in github?
I'm asking because your link is pointing to one commit in this repository, but I can see this commit. The commit is not in your fork. 

@teamikl , you understand this situation? How Magnus is commiting in this repo directly? The repo collaborators list is empty ...

**Comment by teamikl** [comment]
Hello @elieserdejesus @MagnusDrumsTrumpet 

I am not following all conversation yet.
First I noticed is the fork repo's master branch is outdated.
(I could not find way to update this on github site)

I found that on branch, is this commit @elieserdejesus looking for?
https://github.com/MagnusDrumsTrumpet/JamTaba/commit/c8ace4ef03df88f93df7e86f4eb763272d1170ed

> The repo collaborators list is empty ...

It required work on branch to edit the file on github web.
(edit pencil icon on your repo page was disabled for me)
I do not see the commit on elieserdejesus/master, this show it on his forked branch?
https://github.com/elieserdejesus/JamTaba/network

**Comment by teamikl** [comment]
I think the user id on url make the situation confuse.

```
https://github.com/elieserdejesus/JamTaba/commits/c8ace4ef03df88f93df7e86f4eb763272d1170ed
https://github.com/MagnusDrumsTrumpet/JamTaba/commits/c8ace4ef03df88f93df7e86f4eb763272d1170ed
https://github.com/teamikl/JamTaba/commits/c8ace4ef03df88f93df7e86f4eb763272d1170ed
https://github.com/jonjamcam/JamTaba/commits/c8ace4ef03df88f93df7e86f4eb763272d1170ed
```

**Comment by teamikl** [comment]
> It required work on branch to edit the file on github web.
> (edit pencil icon on your repo page was disabled for me)

this was up to context, maybe I was looking Magnus's branch at the moment.
I could see on master branch, the peincil icon tooltip show "Edit the file in your fork on this project"
If I click that then show editor on browser and info message: 

> You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork teamikl/JamTaba, so you can send a pull request.

**Comment by elieserdejesus** [comment]
@teamikl , thanks to try solve this little mistery, hehe. I have to agree with Magnus, sometimes github is a jungle :)

When I clicked in the commit link posted by Magnus you got this:
![image](https://cloud.githubusercontent.com/assets/1012741/14885369/5dd4e586-0d21-11e6-8e04-b93114ba66e5.png)

Apparently the commit is in the jamtaba repo, not in a fork. This is a puzzle for me at moment, hehe.

**Comment by MagnusDrumsTrumpet** [comment]
yes hey ))
 i am also not sure how i did and what is the right way
 didnt use the fork at all
i just edit with pencil icon in "edit file" and looked the   "preview changes"
then you can Propose it 
and it brings up "comparing Changes"
 there i see my ts file as filelink "update de_De.ts"
this link file i drag an dropped  to here 

https://github.com/elieserdejesus/JamTaba/commit/c8ace4ef03df88f93df7e86f4eb763272d1170ed

really misty
