### ISSUE TITLE
Mini Mode GUI issues when big user name and/or big server name

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#318]
Using a 16 character username with capital lettters and ninjamers.servebeer.com

![image](https://cloud.githubusercontent.com/assets/15310433/14591769/2eed3cc8-04ed-11e6-9a94-d3f799e5cfe4.png)

It looks the server name is duplicated inside the ninjam window using valuable space. If it was not preset we'll still have the server information in the tab above.

![image](https://cloud.githubusercontent.com/assets/15310433/14592315/97f790b4-04f3-11e6-9902-2ac9e1397332.png)

**Comment by elieserdejesus** [comment]
Good Idea Jon, let's drop the server name in ninjam window. The server name in the TAB is enough.

**Comment by elieserdejesus** [comment]
Solving in #319

**Comment by jonjamcam** [comment]
@elieserdejesus One side question about mini mode: is this scroll bar expected to appear when adding only one channel?. I think the scrolling in this case is not that useful.

![image](https://cloud.githubusercontent.com/assets/15310433/14612316/d738cbb6-056c-11e6-8e39-abea1ecf559b.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , probably this scroll is the result of some little change in the layout. This scroll is not expected in this picture case. I will add another task in the PR.

**Comment by elieserdejesus** [comment]
Creating a new issue to fix the scroll problem: #331
