### ISSUE TITLE
too much "YOU"?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#320]
![image](https://cloud.githubusercontent.com/assets/15310433/14613498/03c4631a-0573-11e6-846b-e183763bacb6.png)

Aesthetically it's starting to look a little redundant to me.

**Comment by elieserdejesus** [comment]
I agree.  How solve this problem? 
"Your Controls" can be changed to "Local Controls", but I think is not easy enough for dummny (non geek users).

"You channel" can be just "Channel Name"

And "You are connected as ..." can be just "connected as ..."

**Comment by jonjamcam** [comment]
Some other options:

Keep "Your controls".
change "type your name" to `type user name` or `user name here`
change "Your channel" to `new channel`, `my channel` or `my instrument`

![image](https://cloud.githubusercontent.com/assets/15310433/14619781/8fe785fe-058f-11e6-9799-00896fac4e9c.png)





>And "You are connected as ..." can be just "connected as ..." :+1:

**Comment by elieserdejesus** [comment]
+1 for "user name here"
and 
+1 for "my instrument"

**Comment by jonjamcam** [comment]
> I suggest "instrument here", just to match with "user name here".

 I think this is the best option so we can have a "suggestion box" where input is needed correlated.

We must not forget that the instrument name text is shown to others when jamming, so In that case I would leave the actual suggested text blank until something is typed (only showing "instrument here" in gray letters)

**Comment by elieserdejesus** [comment]
> only showing "instrument here" in gray letters

Good idea, I forgot this detail. Use "instrument here" as a placeholder text.

> when connecting, then we can set a default instrument name like "my instrument".

Maybe keep the instrument name empty? It's easy to implement, and I think this represents the user intention.

**Comment by jonjamcam** [comment]
yea. empty is fine too.

**Comment by elieserdejesus** [comment]
@jonjamcam , I have a little problem with "instrument here". This string is too big/wide, and the word "instrument" translated to portuguese is one letter more wide. Another ideas?
![image](https://cloud.githubusercontent.com/assets/1012741/14687755/82c0c7d2-0715-11e6-8af1-22319d99d120.png)

**Comment by jonjamcam** [comment]
"channel name" seems to fit

**Comment by elieserdejesus** [comment]
After the last changes to clean the texts this is the result:

![image](https://cloud.githubusercontent.com/assets/1012741/14688234/f69f6526-0717-11e6-933b-da56d216faf0.png)

**Comment by jonjamcam** [comment]
looks pretty good to me!
