### ISSUE TITLE
Improve the tests dir layout

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#321]
Commented by @teamikl in #317: 

> about test code directory layout
the test code was manual test (it's for human looks the layout), it's not good to mix with unit tests.
e.g. assumed scenario is run all tests, app.exe() will block the test task.
manual test code can be another directory under ./tests.

**Comment by teamikl** [comment]
I did not notice here, I already had made PR #329

Sample directory I referenced is [qtbase repo](https://github.com/qtproject/qtbase/tree/dev/tests)
