### ISSUE TITLE
Crash when audio device is turned off with Preferences dialog opened

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#33]
If I'm using an external audio device (I'm using a M-Audio Fast Track Ultra), open the Preferences dialog, turn off the audio device and close the Preferences dialog I have a crash. 

Shure portaudio is trying to use same audio device, but this device is dead because I turn off the audio gear.

**Comment by Ezeer** [comment]
Crash when audio device is turned off or where there is no device ?
You implemented NULL DEVICE , is it occurring in that case ?
I couldn't reproduce the crash since i can't disable Asio at all from the preferences menu .
Is it yet of actuality ?

**Comment by elieserdejesus** [comment]
Ezee, I translate and update the issue comments. I hope is more clear now.

**Comment by Ezeer** [comment]
You turn off an external audio device with the power switch ?
ah...M-audio , ok i got it .
I noticed that when i close the preference tab , a popup of Asio4all appear in the taskbar .
So there is a call to the driver somewhere ... i will look after that .

**Comment by elieserdejesus** [comment]
Exactly, I'm using the power switch. This is just a bullet proof test. Off course users don't do this kind of shit everytime, but they do sometimes :)

**Comment by Ezeer** [comment]
We have 3 issues left to go to 2.0.6 , i'm checking that part of code now .

**Comment by Ezeer** [comment]
Have you got Asio4All installed Elieser ?
Can you try to switch off your M-audio and see if Jambata select Asio4All as fallback ?

**Comment by Ezeer** [comment]
For the critical part , perhaps here : 

void PreferencesDialog::on_okButton_released()
{
    if(mainController->isRunningAsVstPlugin()){
        this->accept();
        return;
    }
    int selectedAudioDevice = ui->comboAudioDevice->currentIndex();
    int firstIn = ui->comboFirstInput->currentData().toInt();
    int lastIn = ui->comboLastInput->currentData().toInt();
    int firstOut = ui->comboFirstOutput->currentData().toInt();
    int lastOut = ui->comboLastOutput->currentData().toInt();
    int sampleRate = ui->comboSampleRate->currentText().toInt();
    int bufferSize = ui->comboBufferSize->currentText().toInt();

    //build midi inputs devices status
    QList<bool> midiInputsStatus;
    QList<QCheckBox*> boxes = ui->midiContentPanel->findChildren<QCheckBox*>();
    foreach (QCheckBox* check, boxes) {
        midiInputsStatus.append(check->isChecked());
    }

    this->accept();

    emit ioPreferencesChanged(midiInputsStatus, selectedAudioDevice, firstIn, lastIn, firstOut, lastOut, sampleRate, bufferSize);
}

Who is the receiver for ioPreferencesChanged(...) ?
The problem is here , you will report an index for the device that is logically present ( in the box )
but off physically ...
You should verify that the Audio device is still there before , and assign NULL DRIVER if not .
Then emit .
Try that ?

**Comment by elieserdejesus** [comment]
Ezee, I suspect the problem is exaclty in PortAudioDriver::start()

After change the audio preferences the audio driver is restarted, and the audio stream is restarted too using the audio device index. But this audio device index is pointing to a turned off audio card. I suspect portaudio will generate some error, and probabily the code is not handling this error.

I can work in this, I have an external audio device to test. I think this test can't be done using just Asio4All.

**Comment by Ezeer** [comment]
** I think this test can't be done using just Asio4All.**
Sure , i was trying to help you as you are assigned in 3 tasks .
^^

**Comment by Ezeer** [comment]
GG !
