### ISSUE TITLE
Add a button "check server mix"

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#34]
a ideia do botão "check server mix" é muibo boa. Não tenho certeza se funcionaria, pois quando o usuário clica no botão ele parou de tocar. Ou seja, eu só conseguiria renderizar os intervalos que o usuário já enviou para o servidor. Como ele parou de tocar para clicar no botão e ouvir a mix, os próximos intervalos estarão zerados ou apenas com ruídos

**Comment by pljones** [comment]
> the idea of ​​the button "check server mix " is good muibo . Not sure if it would work , because when the user clicks the button he stopped playing . That is, I could only render the ranges that the user has sent to the server. As he stopped playing to click the button and listen to the mix , the next interval will be set to zero or just noise

On *ninbot* servers, issuing "nb levels" gets the server view of the channel levels at that point -- it's very useful for explaining to people using ReaNINJAM that their "local level" in the plugin has no effect on what others hear.  It also takes care of the "stopped playing" factor, as ninbot is listening to the previous interval still.

Other than that, the alternative is almost what the mixer is displaying already -- the local send level plus the remote receive levels at this client, as you say.  The useful addition would be "minimum level" for monitoring channel noise.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
