### ISSUE TITLE
User's Guide updated

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#346]
Last changes: German and french languages, new chat layout and some minor corrections. Now all images are contained within the wiki directory. No external links for images anymore.

**Comment by elieserdejesus** [comment]
@jonjamcam , the [language menu entry](https://github.com/elieserdejesus/JamTaba/wiki/The-Language-Menu) is missing french and german.

**Comment by elieserdejesus** [comment]
ah, I'm reading the Jamtaba repo, my bad!  I will update from your repo..

**Comment by elieserdejesus** [comment]
Wiki updated, thanks Jon!
