### ISSUE TITLE
Midi tool text is cropped when translating (mini mode)

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#347]
![image](https://cloud.githubusercontent.com/assets/1012741/14786691/6279dbd4-0ad6-11e6-9abc-178aafabf1ca.png)

@jonjamcam , when using mini mode in spanish, portuguese, or german the translated text for "Midi tools" is cropped. 

**I have some simple ideas to discuss:**
1 - Use just the word "MIDI"
2 - Use just "Tools", will be translated to "Ferramentas" or "Herramientas". Still a little big words.

What you think? have you another ideas? Maybe change "tools" to some similar word? I have no ideas for similar words ...

**Comment by elieserdejesus** [comment]
I have another idea, the "MIDI" word + gear icon:
![image](https://cloud.githubusercontent.com/assets/1012741/14787135/874d27c0-0ad8-11e6-9fcc-980aa898a9f5.png)

**Comment by jonjamcam** [comment]
I saw this too and I was thinking.... "MIDI menu" is short enough or just "tools" because this button only appears when using a midi input. Even if you use the "wheel" icon only I think that should be enough.

**Comment by elieserdejesus** [comment]
Done, using just the "Tools" word.

@teamikl  and @jonjamcam , I put my fat fingers in your TS files to change "Midi tools" to just "Tools" :)

![image](https://cloud.githubusercontent.com/assets/1012741/14853090/70166f6a-0c60-11e6-88e7-da98325a41dc.png)
