### ISSUE TITLE
disable sync habbit when press play 

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#349]
hey 
still i have the result that always if i hit space or play, or hit play over my controller the metro syncs on the 1
this is cool for sync once )  but if an jam is running  and all are playing fine  and i want to start an aditional loop  t with it, i maybe dont want to reset the metro suddenly just try to place it manually
 so i would appreciate an total disable   by choosing enable or disable of the sync funktion ungently)

thank you ya great )

**Comment by elieserdejesus** [comment]
Magnus, I work in this issue some time ago. I don't remember details now, but I'm not shure if is possible 100% disable the sync. I will check again soon.

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , I do some quick tests using Reaninjam and when I press "play" in Reaper the audio is messed too. I need more time to investigate the issue and check if is possible de-sync the plugin from the host time line. I will schedule this to the next version, it's not too simple to fix, need some time.

**Comment by MagnusDrumsTrumpet** [comment]
cool)))
but think of that otherwise when it always syncs every nerd in the jam will sync the jam  somewere 
by pressing space or start and so on 
so leave it off by default is i thinh important hehehe
