### ISSUE TITLE
Show english language names too in language menu

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#353]
@teamikl proposed:
> hoe about use the menu item field like "日本語 (Japanese)"

@teamikl , can you assume this task? If yes please check **MainWindow::initializeLanguageMenu()**.

**Comment by teamikl** [comment]
@elieserdejesus 
I think there is better quick way,
you can do this task with commit --amend on the branch you already made.
- change translators name and variable name
- commit --amend with new commit message
- rename branch name then PR

you already wrote the code 343787a1c06579a7f22f8adbdf11c4d9d2f3a470, no need to repeat similar task.
If I copy and paste the code, it will show I am the author for the code you wrote.

Instead, I will assume about box.

**Comment by elieserdejesus** [comment]
@teamikl , I pushed the 343787a1c06579a7f22f8adbdf11c4d9d2f3a470 directly in master. If I run a --ammend in this case I will rewrite the master history.

I will do this task soon.

**Comment by teamikl** [comment]
Oh sorry then that scenario does not work.
the commit was already in master I thought PR topic branch.

I can't find the related topic issue for 343787a1c06579a7f22f8adbdf11c4d9d2f3a470
it was a commit only?

**Comment by elieserdejesus** [comment]
> I can't find the related topic issue for 343787a   it was a commit only?

Yes Tea, just one commit. This is why I put directly in master, but was a bad idea :)

**Comment by elieserdejesus** [comment]
@teamikl , just to confirm, you mentioned
> Instead, I will assume about box.

The idea is an "About ..." entry in the menu? Or the idea is put a entry in menu to link to "translators section" in Jamtaba website?

**Comment by teamikl** [comment]
@elieserdejesus 
I did not think about link at the moment
let's move this topic to 343787a

**Comment by elieserdejesus** [comment]
Ok @teamikl , I will assume the "translators link" task.

**Comment by elieserdejesus** [comment]
Done in #355.
