### ISSUE TITLE
Translate button is elsewhere when themes active

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#357]
![image](https://cloud.githubusercontent.com/assets/15310433/14910258/369b9356-0dc2-11e6-828c-ea10218deb84.png)

**Comment by teamikl** [comment]
:+1: looks smart

**Comment by elieserdejesus** [comment]
Yes @jonjamcam , I changed the chat message layout (and other small things in general layout too). Was a bit messed and confuse in my eyes.

**Comment by jonjamcam** [comment]
ok. I thought it was a bug, closing.
