### ISSUE TITLE
New MIDI Devices are not recognized on start. Need to press F6 every time.

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#362]
@elieserdejesus can you confirm this? I just noticed that any device I connect and turn on before I launch Jamtaba is not recognized. I have to add maually pressing F6.

**Comment by elieserdejesus** [comment]
@jonjamcam , I have to test, but I remember sothing related too. I'm almost shure this is a bug.

**Comment by elieserdejesus** [comment]
The problem appear when 2 or mode midi devices are used. Fixed now!
