### ISSUE TITLE
Jamtaba Keeps loosing the audio focus

### ISSUE THREAD

**Issue by staticx** [elieserdejesus/JamTaba#363]
Hello

When I join a room, it takes a while till I hear the other players, and also after I do hear them, after a few seconds It suddenly reloading one of the players. 
so the situation is that suddenly I dont hear the guitars, and the next moment i cannot hear the drums... do I have to wait until its reloading again... and for desert, it kicks me out of the room 

any ideas?

thanks!

**Comment by elieserdejesus** [comment]
Hi staticx, based in your description I think you are using a very slow internet connection, or use a good internet connection but download a big torrent while jamming online :)  If you don't have enough network bandwith you will loose some audio players until the next first beat.  The server disconnection is related too, your Jamtaba need communicate with the server periodically or you will be disconnected.

**Comment by staticx** [comment]
@elieserdejesus so from what you're saying, there's no problem with ninebot server... the thing is... it was ok about two weeks ago, and suddenly all that happens...
I'm closing all the software that uses the bandwidth when opening Jamtaba so the line is free...
I've also checked with Speedtest.net and got 100down and 2.1up (yea it's not a symmetric line...upload sucks).

so now the problem is I cannot use rooms with more than 2 people... :(

**Comment by elieserdejesus** [comment]
@staticx , I think your internet is ok. I have 5 Mb down here and I can play without problems. I'm assuming other people are using Jamtaba without problems because we have no bug reports. We (me, @teamikl, @jonjamcam and Doublebass) tested the last Jamtaba version before release and we have no problems too. 

Please try ReaNinjam and check if the problem still exists. If you have no problems using ReaNinjam we can conclude JamTaba is doing some bad thing behind scenes.

Are you using the Vst plugin or standalone? Windows, mac or linux? 32 or 64 bits?

**Comment by staticx** [comment]
Thanks @elieserdejesus I'm using Windows 10 x64 and using the standalone x64 version. 
I'll try ReaNinjam and report back.

**Comment by jonjamcam** [comment]
@staticx Hello. are you using VST plugins in Standalone? Some Vsti can be very CPU intensive.

**Comment by staticx** [comment]
@jonjamcam I'm using Guitar Rig 5 on channel 1 , and Superior Drummer on channel 2. 
But they don't overload my CPU, and also I have a strong computer (FX8350+16GB DDR3+SSD)

**Comment by jonjamcam** [comment]
@staticx I see.  but just to discard, can you test Jamtaba using no VSTi and see if the disconnection problem persists?

In my experience with plugins sometimes they take control over most of your cores (like kontakt does) but this behavior can be turned off:

![image](https://cloud.githubusercontent.com/assets/15310433/15019719/85afa55e-11f5-11e6-96ca-82aa41e6f431.png)

See, if your VST are using multiple cores, this will be in conflict with Jamtaba, so try to configure ALL your VSTi to use SINGLE CPU (or turn multiprocessor off in each one).

Hope this helps.

**Comment by staticx** [comment]
![image](https://cloud.githubusercontent.com/assets/4776564/15027695/b7781898-124d-11e6-8959-bb794cb3c252.png)

whole system:

**Comment by jonjamcam** [comment]
@staticx Please try Jamtaba VST inside reaper or another D.A.W. and test a crowded room. This way we can discard it's Jamtaba's problem. if it works OK then there's probably a audio driver or some other thing that's limiting your connection when running the standalone version. If it doesn't work, try REANINJAM in a crowded room also.

If reaninjam doesn't work, then it's probably a firewall or connection thing.

**Comment by staticx** [comment]
@jonjamcam tried now with ReaNinjam and it's the same... cannot enter rooms with more than 3 people.

**Comment by jonjamcam** [comment]
@staticx  you posted:

>the thing is... it was ok about two weeks ago, and suddenly all that happens...

>ReaNinjam and it's the same... cannot enter rooms with more than 3 people.

If you have problems with reaninjam too, then it's not a Jamtaba problem. What I suggest is first try your connection directly (bypassing a router if you have -some routers have internal firewalls) and if this doesn't works try to connect with the same computer using other internet connection (another provider in an internet Café or a friend's house). This way you will know if your ISP is the problem.

Thx for reporting and I hope you solve the problem.

**Comment by elieserdejesus** [comment]
@staticx , have you installed some internet tool in last days? VirtualBox? VmWare? Hamachi? Antivirus?

**Comment by staticx** [comment]
@jonjamcam @elieserdejesus , finally I took an extreme step - I've installed a clean Windows 7 x64 (dualboot with my previous W10 )
and now everything is working great!
thanks a lot for a great support

**Comment by elieserdejesus** [comment]
nice @staticx , have good jams!
