### ISSUE TITLE
Unable to sync between Jam Taba VST2 v. 2.0.14 with Cubase Pro 8.5 64 bit

### ISSUE THREAD

**Issue by malafatoge01** [elieserdejesus/JamTaba#365]
Can we get the required steps to allow Cubase Pro 8.5 to sync up with the Jam Taba VST2 control.  I am unable to get this to work.

**Comment by elieserdejesus** [comment]
Hi, I can't remember the Cubase version I used in my last test, I'm no shure if was Cubase 8.5. 
But the steps are:
1 - Connect in a server/room
2 - Before sync you need manually change the **Cubase BPM** to match the ninjam server BPM. For example, if you are connected in a serving running in **115 bpm** you need **change Cubase bpm to 115**. 
3 - In the middle bottom of Jamtaba screen click in the button "Sync with Cubase". The ninjam server audios will stop, Jamtaba will enter in a "waiting for Cubase start" mode.
4 - Press play/start in Cubase and the ninjam audios will play in sync with Cubase.

I hope this help.

**Comment by malafatoge01** [comment]
Did all the above several times with different BPM - No luck.  When I press start (Step 4 above), the Jam Tamba Metronome is ahead of Cubase's click.   Tried this in Reaper and it seems fine there.   All my work is in Cubase however, but sounds like I will need to move some of the Jam tracks I am trying to build into reaper if I want this to work.   By the way I love the concept of what is built here....Thx for all the hard work you and others have put into this....

**Comment by elieserdejesus** [comment]
> By the way I love the concept of what is built here....Thx for all the hard work you and others have put into this....

Thanks!

@malafatoge01 , when you press start in Cubase the song is played from the current "cursor" point. I know this a simple issue, but I need check if this is the problem. Try put the Cubase "cursor" exactly in the measure start and sync with Jamtaba. Jamtaba can't move the DAWs cursor, users need do this step manually before sync. If your "cursor" is a bit ahead of measure start the result will be out of sync.

**Comment by malafatoge01** [comment]
It is exactly on the beat (measure start)...I guess I could manually try and set it before the 1st measure of the loop, but loop on the exact start and end (length of BPI)  - That might help - although it would still be "art" rather than "science"....Would love to know how to force the sync if possible ...I know you will look into it.... let me know how I can help...thx

**Comment by malafatoge01** [comment]
Additional info
Tried the above and realized that  starting before the beginning of the loop will mess up the BPI - To align the BPI and take care of the sync I actually have to sync with the Cubase cursor already passed the 1st measure - In the sample I am working with, I need to place the Cubase cursor on the 3rd 64th beat in. Then when I press start Cubase click is in sync with Jam Tamba and everything loops properly....Start cursor location is placed by trail and error however and this would change as the BPM changes....Bottom line Jam Tamba is ahead of Cubase, and skipping the first 3 64th notes puts it in this example, more or less in sync...

**Comment by elieserdejesus** [comment]
@malafatoge01, this is a Jamtaba bug. I will check this in Cubase 8.5 soon.

A last question: **what is your buffer size** in ASIO configuration? Can you try again using a small buffer size (128 samples, for example)?

**Comment by malafatoge01** [comment]
Running Windows 8.1 64 bit - 16GB DDR4  - I7 5820K -  6 Cores
Apollo | Twin USB 3.0 interface
UA Driver - Asio buffer set to 128  - Can go as low as 64, Sync is still off.. 

If this is a latency problem however, why is Reaper perfectly in Sync with the same settings?  
By the way I am working with empty projects just loading Jamtamba vst in my Stereo Bus and comparing Cubase to Jamtamba clicks 

Thank you for your attention on this - Getting help like this is awesome - thx

**Comment by malafatoge01** [comment]
Sorry 32 GB of RAM - but that's not an issue here

**Comment by elieserdejesus** [comment]
> Asio buffer set to 128 - Can go as low as 64, Sync is still off..

Ok, so we can discard the latency hyphothesys. 


> By the way I am working with empty projects just loading Jamtamba vst in my Stereo Bus

When you say **my stereo bus** are you saying "Cubase master bus**, right? Can you try again inserting Jamtaba in a common audio track? I think you need activate the track monitoring to hear Jamtaba audio.


> Thank you for your attention on this - Getting help like this is awesome - thx

You are helping a lot too, because without you we never will know about this sync bug in Cubase. It's very difficult (almost impossible) test all details in all OSs (windows, linux, mac) and all DAWs without help of users. 

You are very welcome!

**Comment by malafatoge01** [comment]
Yes the Cubase Master Bus (Its called "Stereo Out"  inside the DAW).   

I added the Jam Tamba VST as an insert on a regular Audio track.  Did not have to turn on track monitoring on to hear it (that's peculiar but Ok by me).   Same Sync issue - Cubase click behind J.T.

**Comment by elieserdejesus** [comment]
@malafatoge01, I'm scheduling this bug to the next version. I will check this inside Cubase soon, thanks for your infos.

**Comment by malafatoge01** [comment]
OK - Thx - Let me know if you need anything from me when u get to it...Thx again..

**Comment by elieserdejesus** [comment]
@malafatoge01 , I'm uploading a fixed version of Jamtaba Vst plugin. I tested in Cubase Elements 8 Trial, working fine now. Can you test too, please?

[JamtabaVST2 - sync bug solved.zip](https://github.com/elieserdejesus/JamTaba/files/254112/JamtabaVST2.-.sync.bug.solved.zip)

**Comment by malafatoge01** [comment]
Hi:

Tests successful on Cubase 8.5.15 64 Bit (latest version).
Sync'ing issue described in this ticket are now resolved.  Tried the sync functionality at very low and high BPMs - clicks from Cubase and JT VST remain in Sync 

Your attention and response to this is really very much appreciated.   Thx again.

**Comment by elieserdejesus** [comment]
Nice @malafatoge01 , the sync feature is very improved now. See you!

**Comment by Krill0** [comment]
Hi I'm having this issue w Reaper v5.92 and Jamtaba 2.1.5 64 bit. Sync starts OK but drifts off. Sometimes worse, sometimes better. Trying to have midi loop in Reaper sync w Jamtaba.

**Comment by elieserdejesus** [comment]
> Hi I'm having this issue w Reaper v5.92 and Jamtaba 2.1.5 64 bit. Sync starts OK but drifts off. Sometimes worse, sometimes better. Trying to have midi loop in Reaper sync w Jamtaba.

Hi @Krill0 , I think your problem is about **drift** (more specific). If you still have the issue please create a new ticket/issue describing the steps to reproduce your problem.
