### ISSUE TITLE
Ninjam or NINJAM

### ISSUE THREAD

**Issue by takeshitaleo** [elieserdejesus/JamTaba#366]
Hi.

We can't find the word **Ninjam** in [www.ninjam.com](http://www.ninjam.com).

I think the formal name of ninjam is not **Ninjam** but **NINJAM**...

**Comment by jonjamcam** [comment]
@takeshitaleo Hello. You're probably correct, but Ninjam is an acronym for "Novel Intervallic Network Jamming Architecture for Music":

![image](https://cloud.githubusercontent.com/assets/15310433/15093567/8dd01cb8-1462-11e6-88ad-da689e6e1bdf.png)

and "There is no universal standardization of the various names for such abbreviations and of their orthographic styling." 

![image](https://cloud.githubusercontent.com/assets/15310433/15093638/e27e75e2-1463-11e6-9632-f5164a56c25c.png)

so IMO it can be both ways.

**Comment by takeshitaleo** [comment]
@jonjamcam oh i see, thanks xD
