### ISSUE TITLE
Midi information is not transmitted from one VST slot to another (Standalone)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#367]
Audio VST slots communicate OK, this means the audio from the first slot passes to the next slot, but this doesn't happen with midi. The Midi VSt slot receives the midi from the input OK, but if the plugin has the capability to send midi data out, then this data is not passed to the second VST slot (this is assuming the second VST slot also has the capability to receive midi data)

I tested this using improvisator (sends midi out) on slot 1:

![image](https://cloud.githubusercontent.com/assets/15310433/15093542/be860e86-1461-11e6-89b6-97f18391954b.png)

 and M1 in slot 2. Both VSTi are 32bit. Tested in standalone 32bit. When I do this in reaper (using Jbridge), both communicae fine, but not in Jamtaba standalone

**Comment by elieserdejesus** [comment]
I never think in this possibility before, let's check this in next release.

**Comment by elieserdejesus** [comment]
Just to remember myself: discussion in [kvraudio forum](http://www.kvraudio.com/forum/viewtopic.php?t=387599)

the important part is:
> you can always send the MIDI back to the host (using sendVstEventsToHost)
