### ISSUE TITLE
Gain buttons in horizontal tracks layout in wrong position

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#369]
I find that the boost/att direction should follow the level meter as it does in the vertical tracks layout, but here it's reversed:

![image](https://cloud.githubusercontent.com/assets/15310433/15098499/a1b62476-1515-11e6-818b-af7e1cecd61c.png)

I always get it wrong when changing this setting during jams

**Comment by jonjamcam** [comment]
@elieserdejesus I thought this one was easy to solve, but when I changed the buttons order, the vertical layout is changed too, so I closed the PR https://github.com/elieserdejesus/JamTaba/pull/370.

**Comment by elieserdejesus** [comment]
@jonjamcam , check the file **NinjamTrackView.cpp**, like **151**:
```
boostWidgetsLayout->setDirection(QHBoxLayout::LeftToRight);
```

Try change the layout direction to **QHBoxLayout::RightToLeft**, this change will be applyed only in horizontal layout.

**Comment by jonjamcam** [comment]
Solved in PR https://github.com/elieserdejesus/JamTaba/pull/371. Closing...
