### ISSUE TITLE
Crash when trying to change the metronome sound in VST plugin x64 (Reaper x64 host)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#372]
![image](https://cloud.githubusercontent.com/assets/15310433/15099636/ed598074-1530-11e6-81a9-d53f0e45a393.png)

THis happens when using the button inside the ninjam room. I noticed the sound of the jam doesn't stop as it does in standalone when pressing the same button. When pressing Ok, the crash happens

**Comment by elieserdejesus** [comment]
Jon, tested here and can't reproduce the bug. 
Are you seeing the bug everytime? Can you see a pattern in the bad behavior?

**Comment by jonjamcam** [comment]
@elieserdejesus . It happens in my win7 computer every time. The only thing I can say is that this happens ONLY when you try to change the sound while jamming (inside a server). Let me test it in another computer (win10) tomorrow and compare.

**Comment by jonjamcam** [comment]
Ok Finally Tested in a win10 laptop with reaper and no bug. It's happening only in my system. I will check the cause.

**Comment by elieserdejesus** [comment]
@jonjamcam , maybe something in win7 privileges. Try run Jamtaba as admin just to check.

**Comment by jonjamcam** [comment]
@elieserdejesus This happens only in the VST plugin version. You mean run reaper as admin?

**Comment by elieserdejesus** [comment]
ah, I forgot this detail. I think run Reaper as admin will not change the plugin behavior.

I will reopen the issue an test inside a virtual box soon.

**Comment by jonjamcam** [comment]
The Crash happened in reaper 5.12. Now I've updated to reaper 5.18 and no crash, but when I change the sound during a Jam, the metronome mutes. This is probably a Reaper bug. I will test today on a XP machine with reaper 4 (more stable) and see.

**Comment by jonjamcam** [comment]
Upgraded to reaper 5.20. No more problems. Working fine now :D

**Comment by elieserdejesus** [comment]
let's keep the issue opened until finish the next Jamtaba release.

**Comment by elieserdejesus** [comment]
@jonjamcam , can we close this issue? No more problems?

**Comment by jonjamcam** [comment]
Tested on reaper 5.21. Working fine. Closing...
