### ISSUE TITLE
trouble on jamtaba vst loading to host energyxt standalone

### ISSUE THREAD

**Issue by squiergtr** [elieserdejesus/JamTaba#373]
hi to all having a bit of trouble trying to load my jamtaba vst  in to energy xt v1.4.1 getting a error that it is not a vst i have attach a demo of my standalone host energy xt  hope this will help troubleshooting the error
this is a awesome  host all your plugin install in the host can be place and layered so many option 
peaceout and thanks so much for jamtaba ..

[Uploading standalone.zip…]()
[Uploading standalone.zip…]()

**Comment by elieserdejesus** [comment]
@squiergtr , I will check this problem soon. 
We have another issue related with Energy Xt #205. In this issue a problem with stereo is reported in Energy XT 2.  

Are you using a older version? v1,4,1?

**Comment by elieserdejesus** [comment]
@squiergtr , the link you posted is not working, Can you check please?

**Comment by squiergtr** [comment]
hi elieserdejesus yes the ver is energy xt 1.4.1 i try to upload the install demo file the uploader would not take the zip or rar file is very small less then  600k ,,,ps i read the post of ver 2 which is totally 
different from version 1.4.1 they change the gui and so much more,,, version 1.4.1 one is a keep it simple style...lol..lol all my plugin,s like stylux and groove machine, and others working fine inside it..

if i could upload the demo that would help on the trouble..

**Comment by elieserdejesus** [comment]
@squiergtr , you can try rename the file to something like "installer.zip.txt". Using .txt as extension github will accept the file.

**Comment by squiergtr** [comment]
hi elieserdejesus cool i give a try 
[Uploading standalone.zip.txt.zip…]()
[Uploading standalone.txt.zip…]()
[standalone.pdf.zip](https://github.com/elieserdejesus/JamTaba/files/258639/standalone.pdf.zip)
it keeps see it as a zip it does not like  i can send it  thru yahoo but gmail  dont like it also 
is there a nother temp email you can use  my yahoo will sent it
[Uploading standalone.pdf.zip…]()

**Comment by elieserdejesus** [comment]
@squiergtr , the upload works. I tested Energy Xt 1. here and see the problem you are reporting. I will investigate the bug soon:

![image](https://cloud.githubusercontent.com/assets/1012741/15179694/d1421a16-1753-11e6-8220-ee5de0299f73.png)

**Comment by squiergtr** [comment]
hi elieserdejuess ....yahoooo it upload thats good news thanks soo much for your time on this trouble 
                                               (may the sound of music be with us all)

**Comment by elieserdejesus** [comment]
@squiergtr , I tested Jamtaba in energy xt 1.4.1 and the problem is not in Jamtaba code. The error appears when Energy Xt is loading the plugin dll file, but Jamtaba is never started.

So, I decided try Jamtaba in the last version of energy Xt. I downloaded the version 3 demo in Energy XT website and Jamtaba (32 bits, because energy is 32 bits too) is **working fine**. No error in the version 3. So my conclusion is: energy Xt 1.4.1 have some bug when loading plugin DLLs, I can't fix this bug in Jamtaba side because the Jamtaba code is never touched by energy Xt.

![image](https://cloud.githubusercontent.com/assets/1012741/15278256/73018c06-1aec-11e6-866f-3f7aaf65bd83.png)

**Comment by squiergtr** [comment]
thanks elieserdejesus on the issue energy ver 1.41 i was hopeing it could
work on my favorite host all my plugins work very well with this host i use
stylus,mpc akia,groove mach,guitar rig .ezkeys,roland canvas ..and several
other vst no problem no errors
these are pro plugin,s but i get what your saying this host is looking for
information that jamtaba is not sending  thanks for your time on this
trouble ..murphy law wins again lol lol ..ps this would have been a great
simple host too work with jamtaba
thanks to the all the team on this one...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
