### ISSUE TITLE
Inverse Stereo Image Button for Standalone

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#377]
To invert the stereo image on one specific channel is easy in Reaper (before send to Jamtaba), but there's no way to do it in Jamtaba Standalone and sometimes it's very important when the plugins do not have the option to do it (i.e. left handed drummers/percussionist)

**Comment by elieserdejesus** [comment]
@jonjamcam , the idea is invert stereo only in local channels?

**Comment by jonjamcam** [comment]
>@jonjamcam , the idea is invert stereo only in local channels?

yes. that's the idea. with a button if possible

**Comment by elieserdejesus** [comment]
@jonjamcam , you have ideas for the button text or icon? Something like "LR", and if you click the text change to "RL"?

**Comment by jonjamcam** [comment]
I'm looking into it. I'm thinking about something on these lines:

http://thumbs.dreamstime.com/z/stereo-symbol-10603870.jpg

but maybe with opposing arrows....I'm into it

**Comment by jonjamcam** [comment]
Another idea:

![image](https://cloud.githubusercontent.com/assets/15310433/15259727/5f2b4d76-1929-11e6-8503-c163cb32143c.png)

This is assuming L is blue and R is red.

**Comment by elieserdejesus** [comment]
another one: 
![image](https://cloud.githubusercontent.com/assets/1012741/15259836/e127e4ba-1929-11e6-9dec-fd6ca7f5be4c.png)

**Comment by jonjamcam** [comment]
That above looks really good!

**Comment by jonjamcam** [comment]
I found the Channel Pan control is inverted when the invert stereo button is pressed (need a separate issue for this?)

![image](https://cloud.githubusercontent.com/assets/15310433/15270594/95c9ba3e-19fb-11e6-9a64-50f58565ca06.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I keep the pan controls in "normal" because I think left side is always left side, even for left handed people. But I'm no shure what is more confuse: keep the pan controls in "normal" mode or change to R -> L. All this inversions are burning my brain.

You idea is flip pan controls entirelly? R -> L?

**Comment by jonjamcam** [comment]
@elieserdejesus . The inversion is supposed to work pre-fader, so it "corrects" a wrong incoming stereo image. All further control in the channel chain should work the same. For example:

a Right handed drummer sets his drum set like this:

-![](https://xmworld.files.wordpress.com/2012/03/c-plus-9sr_edrum_electronic-drum-kit_drums_how-to-drum.jpg)

This way the right hand has a circular view of all the cymbals:

-![](http://www.roland.co.uk/blog/wp-content/uploads/2013/04/VDFJ_Kids_EG_image.jpg)

A left Handed drummer's set is like this:

![image](https://cloud.githubusercontent.com/assets/15310433/15271387/3af4e99a-1a1d-11e6-8cea-9661c6a1c9ae.png)

Now, most plugins have a right handed setup by default, so we left handed drummers have to flip channels manually in Kontakt or reaper to get the above stereo image.

This is only one example, but percussionists may have the issue too or a wrongly made stereo cable, the same happens.

So the idea is to correct this early in the chain, but the pan, mute, solo, etc controls stay the same.

**Comment by elieserdejesus** [comment]
> The only thing to correct is the pan control that's working in reverse. It should pan left when you move the fader left, but it's panning to the right, now.

Understand now @jonjamcam , I will check this.
