### ISSUE TITLE
[WIP] Theme Developer's Manual

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#383]
- [x] Create new structure for the wiki (new dirs and subdirs) ( @jonjamcam ATM)
- [x] Create new entry "TDM" in the wiki page
- [x] part I: Explain where are .css files and how to create a new theme
- [ ] part II: Explain the basics of the syntax inside the .css file and show graphically where the changes apply (individual explanation with images)
- [ ] part III: Overview map of the most important items.

---

MOVED DOWN

I'm in the process of understanding the individual styles. I used the flat theme as template, so first  I took MainWindow.css and changed this few settings:

![image](https://cloud.githubusercontent.com/assets/15310433/15295281/17346b3a-1b66-11e6-947a-2aa9c704684c.png)

![image](https://cloud.githubusercontent.com/assets/15310433/15328929/3e683fac-1c2d-11e6-8566-98b7a3c7b760.png)

I will be posting here the progress, so in future themes it's easier to identify the parameters to change in a graphical way.

EDIT: @elieserdejesus . I'm thinking about writing a developer's manual to address this issue for easier use.

**Comment by elieserdejesus** [comment]
@jonjamcam , a developer's manual for these stylesheets will be nice.

**Comment by jonjamcam** [comment]
The goal of the manual is very simple: try to achieve a basic theme creation with no previous knowledge about QT stylesheets. If the interest is go further, then Tea pointed out full resource links here https://github.com/elieserdejesus/JamTaba/pull/354#issuecomment-215608770

> Qt provide styleshee http://doc.qt.io/qt-5/stylesheet.html

So I plan to incorporate this in the wiki as an additional manual with only basic explanation. (https://github.com/jonjamcam/JamTaba/wiki)

![image](https://cloud.githubusercontent.com/assets/15310433/15334664/94c62e00-1c45-11e6-9a9f-c8805c9a1468.png)

**Comment by elieserdejesus** [comment]
Very good idea @jonjamcam . Let me know if you can't understand something in the stylesheet. Some widgets IDs are very bad names.

**Comment by jonjamcam** [comment]
> Let me know if you can't understand something in the stylesheet

@elieserdejesus . Yes. I've been unable to find this two items:

1.- The background and text color for channel name:

![image](https://cloud.githubusercontent.com/assets/15310433/15337745/7ace7ec2-1c53-11e6-96be-09ba53687d0b.png)

2.- The background and text color of these two tabs:

![image](https://cloud.githubusercontent.com/assets/15310433/15337781/9f530268-1c53-11e6-9f9e-d383c27ee1cd.png)

**Comment by elieserdejesus** [comment]
@jonjamcam, background and text color for **channel name** are in **BaseTrack.css**, in the rule **TrackGroupView #groupNameField**.

The tabs rules are in **General.css**, check the rule **QTabBar::tab:selected**.

**Comment by jonjamcam** [comment]
@elieserdejesus I finished the first part of the manual, which is a description of how I did the process in the first steps. Can you review, please? I don't know if this is the correct way to do it or if there actually is another way, better or faster.

**Comment by elieserdejesus** [comment]
@jonjamcam , some little reviews

In **What is a Theme** section:

> Each theme is constituted of two sets of nine .css files:

I think is better change to "A theme is constituted or **one** set of nine .css files:", because "common" is always available for all themes. The idea is never touch in "common" files when creating new themes.

> These nine files are distributed in two folders:Common and Themes, for a total of 18.

Fix this text too.


The section **How themes are created** is very good, no changes in my opinion.

**Comment by jonjamcam** [comment]
OK. Corrections made. Thx for the review.

**Comment by jonjamcam** [comment]
Finishing the manual for 2.1.18 I'm not including theme developer's manual. Closing...

**Comment by jonjamcam** [comment]
@elieserdejesus Manual for 2.1.8 updated!

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam !
