### ISSUE TITLE
[Linux] launch error

### ISSUE THREAD

**Issue by takeshitaleo** [elieserdejesus/JamTaba#386]
Hello.

I found an error on launching Jamtaba from desktop on **Linux**(Ubuntu 14.04).

![screenshot from 2016-05-22 10 07 45](https://cloud.githubusercontent.com/assets/15683228/15451603/74508fca-2006-11e6-8527-8b20c10f8a34.png)

maybe, this error is caused of 

![screenshot from 2016-05-22 10 12 09](https://cloud.githubusercontent.com/assets/15683228/15451609/bee8473a-2006-11e6-9c09-a90a0b32f70e.png)

**Exec** path.

**Comment by elieserdejesus** [comment]
@takeshitaleo , can you try manually fix the Jamtaba.desktop file to see if this is the problem?

I'm shure this is a problem, but I'm just checking if we have another problems.

**Comment by takeshitaleo** [comment]
@elieserdejesus okay, i don't know if i can do it, but i'll try :)

**Comment by elieserdejesus** [comment]
@takeshitaleo , you can open the text editor and drag-and-drop the Jamtaba desktop file in the text editor.  Change the /home/elieser to /home/your_user_name.

I fixed this problem in linux installer, will be ok in the next release.
