### ISSUE TITLE
Qt Creator Debug mode don't close correctly

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#39]
this problem stil existis? Or was a portmidi issue?

**Comment by elieserdejesus** [comment]
This was a portmidi issue, I can't see the problem anymore, solved!

**Comment by Ezeer** [comment]
Good job !
A picture ?
^^

**Comment by elieserdejesus** [comment]
Ha ha, I habe a good picture:
![rambo-likes-machine-gun](https://cloud.githubusercontent.com/assets/1012741/10745690/1eab4800-7c2b-11e5-81f1-9cf02133f292.jpg)

**Comment by Ezeer** [comment]
ah ah ah !
OOooooh Yeaaaaah !!
^^
--------------------------------------------
En date de : Mar 27.10.15, Elieser Ademir de Jesus <notifications@github.com> a écrit :

 Objet: Re: [JamTaba] Qt Creator Debug mode don't close correctly (#39)
 À: "elieserdejesus/JamTaba" <JamTaba@noreply.github.com>
 Cc: "Ezee" <h2oreggae@yahoo.fr>
 Date: Mardi 27 octobre 2015, 0h47
 
 Ha ha, I habe a good picture:
 
 
 
 —
 Reply to this email directly or view
 it on GitHub.
