### ISSUE TITLE
Separate local monitor mix

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#392]
In reaper there's a way to control the local mix separated from what you send to the room, as well as in the first jamtaba client, but there's no way to do this in Jamtaba 2.

 We could try to think to achieve this in a non invasive way, meaning not something the average user should worry or care about.

I have a suggestion: use a "difference fader" when you right-click any channel or subchannel. This fader will attenuate or boost ONLY what is monitored locally.THen for example the handle can have a red color indicating the monitor mix is different from the sent mix.

What do you think @elieserdejesus ?

**Comment by elieserdejesus** [comment]
@jonjamcam , if I understand correctly the idea is use just one fader, but switching between 2 modes: **local** and **send**, right?

I think this is a good idea. Some additional ideas:

1 - Maybe a button in local tracks to switch between *local mix* and *send mix*? 
2 - when mixing the *send mix* will be cool draw the **local** mix with some transparency (like a "ghost" fader in background), so we can see the difference between the two faders.

**Comment by jonjamcam** [comment]
> use just one fader, but switching between 2 modes: local and send, right?

Yes. The idea is to "call" the secondary only function when needed. This is an important feature to have, but most players will never use it.

> Maybe a button in local tracks to switch between local mix and send mix? 

Sounds good. And the button must have a unique color when turned on (I think about violette or blue) not to be confused with solo for example. Hopefully place the button up (for seldom use) and it doesn't have to be big.

> 2 - when mixing the send mix will be cool draw the local mix with some transparency (like a "ghost" fader in background), so we can see the difference between the two faders.

that sounds really cool!

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
