### ISSUE TITLE
Fix track group layout for disabled tracks

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#396]
@jonjamcam proposed:

![image](https://cloud.githubusercontent.com/assets/1012741/15586254/c5e5dcd6-2359-11e6-8e68-018201bb879b.png)

**Comment by jonjamcam** [comment]
@elieserdejesus I find that the rounded theme has a very good look, it's the opposite solution than I proposed before: to change the **unmuted tracks**, not the muted tracks layout

-![](https://cloud.githubusercontent.com/assets/15310433/15585451/b39d6dd6-2355-11e6-8e95-8af478a4aeb0.png)

Which do you think looks better?

**Comment by jonjamcam** [comment]
@elieserdejesus I corrected the Rouded theme and there's no problem with the layout there https://github.com/elieserdejesus/JamTaba/pull/397#issue-157069362

This means this could be corrected using styles. I will do some more testing and see if I can correct this..

**Comment by jonjamcam** [comment]
@elieserdejesus Hypothesis proved correct!

![image](https://cloud.githubusercontent.com/assets/15310433/15589684/7683d9ca-236a-11e6-89ec-1422bf36466f.png)

The trick is to find a color that's different for both muted and unmuted.

**Comment by jonjamcam** [comment]
fixed for Flat theme in https://github.com/elieserdejesus/JamTaba/pull/398:

![image](https://cloud.githubusercontent.com/assets/15310433/15590499/8ea3dd8a-236e-11e6-97f1-dcd854fb9bcb.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , nice job!

> The unmuted channel upper color is the same as the top panel bottom color, so we're watching an optical illusion.

Exactly! :smile:
