### ISSUE TITLE
Change peak meter menu to be inside new "view" (ex-"view mode") menu

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#403]
I find very comfortable to have the block user in the right mouse button, but I think the peak meter is not related to this function and being a global menu (meaning affect all tracks) a good place to be is where we choose channels and subchannels (the little wheel at the side of the channel name).

**Comment by elieserdejesus** [comment]
@jonjamcam , I agree with the problem of a "global menu" appearing in every track. The tracks are not "global", so is a bit wrong. 
Put the peak meter menu in the **local tracks** wheel will suggest the peak meter menu is availale **only to local tracks**. It's not a global are too, but I agree is better than the tracks context menu.

What you think about change the menu **View Mode** to only **View** and put the peak meters menu in this View menu? I think this *View* menu is the best place to represet "global" visualization stuff.

**Comment by jonjamcam** [comment]
> What you think about change the menu View Mode to only View and put the peak meters menu in this View menu

sounds good to me.

**Comment by elieserdejesus** [comment]
Done:
![image](https://cloud.githubusercontent.com/assets/1012741/15629880/10eb4416-24fc-11e6-8e2c-d466a08ad38e.png)
