### ISSUE TITLE
Flat and round theme corrections

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#406]
While correcting the Black Theme I found some problems with the other themes:

1.- Horizontal mode for Flat Theme:

![image](https://cloud.githubusercontent.com/assets/15310433/15630811/a6af4bd6-2520-11e6-9c2b-0ab1b9ac11b7.png)

The **Color for the disabled Track** and the **handle color for the fader in the muted track** are wrong for the Flat theme

2.- Horizontal mode for Round Theme:

![image](https://cloud.githubusercontent.com/assets/15310433/15630816/f84b9cba-2520-11e6-8ba0-e0978629336c.png)

The **Color for the disabled Track**, the **handle color for the pan in the muted track** and **the handle color for the fader in the unmuted track** are wrong for the Round theme.

3.- Normal mode for Round Theme:

Colors for pan and fader handles in muted track are wrong.

4.- Stereo inverse button in rounded theme doesn't have hover nor hoover-check effect 

I will make a PR to correct this.

**Others:** (moved to https://github.com/elieserdejesus/JamTaba/issues/412)

In mini mode using the horizontal layout the channel name placeholder uses all the space, leaving no place for fader:

![image](https://cloud.githubusercontent.com/assets/15310433/15630899/e70e8eea-2524-11e6-8a13-f0fa00275951.png)

**Comment by elieserdejesus** [comment]
@jonjamcam 
> In mini mode using the horizontal layout the channel name placeholder uses all the space, leaving no place for fader:

This one is a bit trick to solve, I think is better create a separated issue to discuss some possibilities.

**Comment by jonjamcam** [comment]
> The handle color for the pan in the muted track and the handle color for the fader in the unmuted track are wrong for the Round theme.

I'm not so sure about this observation I made. @elieserdejesus I'm confused about the colors of the handles in unmuted and disables states. I really don't know which are which. For now I'm changing only the background color.

-![](https://cloud.githubusercontent.com/assets/15310433/15635958/02e87d28-25c6-11e6-9516-64a384645292.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I think change the background is enough.

**Comment by jonjamcam** [comment]
Ok, closing then....

1.- solved in https://github.com/elieserdejesus/JamTaba/pull/416
2.- solved in https://github.com/elieserdejesus/JamTaba/pull/417
3.- dropped
4.- solved in https://github.com/elieserdejesus/JamTaba/pull/418
