### ISSUE TITLE
Name placeholder for ninjamer tracks in minimode is using too much space (when expanding localtrack)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#412]
In mini mode using the horizontal layout the channel name placeholder uses all the space, leaving no place for the fader: 

-![](https://cloud.githubusercontent.com/assets/15310433/15630899/e70e8eea-2524-11e6-8a13-f0fa00275951.png)

This happens ONLY when the local tracks are expanded fully using two channels, for example. If local tacks are collapsed, the fader fits OK.

**Comment by jonjamcam** [comment]
Now I realize the Pan slider is very big too, maybe shrinking it can solve the problem and leave the name placeholder intact.

**Comment by elieserdejesus** [comment]
@jonjamcam , a possible solution is set the pan slider **max-width** for horizontal tracks only. I don't test in the code, but is something like:
```
NinjamTrackView #panSlider
{
       ... other properties ...

      max-width: 50px; 
}
```

**Comment by jonjamcam** [comment]
> the problem in this solution: in full view the pan slider will be always small.

OK. Tested in mini mode:

![image](https://cloud.githubusercontent.com/assets/15310433/15633995/09793dfc-2590-11e6-9e74-906d67736185.png)

I think now the fader is better, but the pan is still big.

and full view mode:

![image](https://cloud.githubusercontent.com/assets/15310433/15634000/22d54b60-2590-11e6-9263-d737c4a40ab2.png)

I see the pan in good size (not that small)

@elieserdejesus your opinions?

**Comment by elieserdejesus** [comment]
@jonjamcam , I like the result too.  Can you make a PR?

**Comment by jonjamcam** [comment]
PRs to solve this : https://github.com/elieserdejesus/JamTaba/pull/415 and https://github.com/elieserdejesus/JamTaba/pull/414
