### ISSUE TITLE
chords progression shown for new players entering a server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#413]
So this was ECHNATON's idea. He asked if the chord progression could be shown for new players when they enter the room, so they know instantly what the chords are and no need for asking, just start playing.

Maybe we could try to implement this for Jamaba users. Simple local chat message and accept button with chords text at the top of the chat when new user comes in:

![image](https://cloud.githubusercontent.com/assets/15310433/15634193/57d1be58-2594-11e6-85e9-faf48e4650aa.png)

If the progression was used >6 hours ago, then do not sow the message

**Comment by elieserdejesus** [comment]
Nice idea! Let's put this in 2.0.15.

> If the progression was used >6 hours ago, then do not sow the message

I think 6 hours is too much. Maybe 1 hour is enough? People don't use the same progression for 1 hour.

**Comment by jonjamcam** [comment]
> I think 6 hours is too much. Maybe 1 hour is enough?

:D. true. that was way too much!

**Comment by jonjamcam** [comment]
@elieserdejesus I've been trying to test this feature, unsuccessfully. I've tested with two laptops running Jamtaba, then load a chord in both and reenter a server, but no notification appears.

Can you explain what conditions have to be met for this to work, if any?

**Comment by elieserdejesus** [comment]
@jonjamcam , this feature is available for the public servers only at moment. 
The simple test is: enter in ninbot or ninjamer.com, type some chords in chat and load these chords. Every time somebody accept/load a chord progression a "vote" for this chords is computed in Jamtaba server. If you leave this server and enter again the chords will appear as the "last used chords". Jamtaba server will always return the most "voted/accepted" chords in the last hour.

**Comment by jonjamcam** [comment]
Ok. Tested. THx.
