### ISSUE TITLE
Compiling VST plugin in mingw32

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#419]
from https://github.com/elieserdejesus/JamTaba/pull/380#issuecomment-222554899

> I tried to do static compile as stated here #380 (comment) using mingw32 with no luck.
> 
> 1.- QT static builds ok in my system only if I add the flag -opengl desktop which is not in the flags you suggested. If I don't use this flag it gives a directX not found error when configuring Qt before compiling.
> 
> The standalone I can build OK this way, but the vst plugin shows this error:

-![](https://cloud.githubusercontent.com/assets/15310433/15658299/4b36c802-2691-11e6-8e7b-30aadc227cb0.png)

**Comment by jonjamcam** [comment]
> Compile 64 bits Qt apps in mingw is not simple, but if you can compile the Vst plugin in 32 bits this can be usefull enough.

I'm using qt 5.5.1 x86 and mingw32. The result should be a 32bit plugin. 

![image](https://cloud.githubusercontent.com/assets/15310433/15658694/f38f97dc-2695-11e6-99fb-c8727d64098c.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , try comment (use a # in line start) the lines 99 and 100 in VstPlugin.pro file. I note tested here, I don't have a qt static compiled in mingw.

**Comment by jonjamcam** [comment]
it passed, but I have another error later::

![image](https://cloud.githubusercontent.com/assets/15310433/15658974/a9f39318-2699-11e6-975e-04c6a1462bbb.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , this error is more complicated to solve, I need to compile qt for mingw to check this. I know this is related with differences in function exporting in DLL. The compilers (msvc and ming) are using different function export conventions.

**Comment by jonjamcam** [comment]
OK. BTW, this is how I made Qt compile in static: https://github.com/jonjamcam/JamTaba/wiki/Making-Jamtaba-as-Static-Compilation-%28mingw32%29-in-WIN7-x64 . I was hoping it would be of help to have it in the wiki if it works in the end.

**Comment by elieserdejesus** [comment]
@jonjamcam , I created a PR (#421) trying to fix this compilation issue in mingw. I advanced some steps, but the last step (generate the plugin DLL) is very complicated. At moment I see no way to compile a shared library (the DLL) using a static Qt build in mingw.

**Comment by jonjamcam** [comment]
OK. No problem. I understand. Thx for the effort.

**Comment by elieserdejesus** [comment]
Let's reopen, now I have some hope, I think the problem is my Qt :)

**Comment by elieserdejesus** [comment]
Mingw was abandoned.
