### ISSUE TITLE
Unable to compile using mingw32

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#426]
@elieserdejesus Tried to compile the last fixes, but I have several errors in my system:

![image](https://cloud.githubusercontent.com/assets/15310433/15802717/570afc7a-2a92-11e6-9643-acac6daf5b5d.png)

The usual clean, run qmake, rebuild didn't fix the problem. I tried deleting the contents of the **release** folder with no luck.

**Comment by elieserdejesus** [comment]
@jonjamcam , I have some errors here too after clean. I pushed a "fix commit", can you try again?

**Comment by jonjamcam** [comment]
Yes. It's fixed now.
