### ISSUE TITLE
Quick hyper Preset Buttons

### ISSUE THREAD

**Issue by ancibug** [elieserdejesus/JamTaba#428]
Hello,
It will be nice to have 4, 6 buttons, placed on the same row of the master meter, to quick recall presets for boot channels and sub-channels including loaded VSTs and slider levels. More or less a configuration like the one is loaded when starting jamtaba. Eventually with possibility to save, load and change colors. This will enhance the live possibility of the tool and to create library of hyper presets like real keyboards. 
-antonio

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
