### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ancibug** [elieserdejesus/JamTaba#429]
Jamtaba scans all the VST instruments and VST FX plugins in the indicated paths.
My question is: how to use the VST FX plugins since the chaining in the channel is only parallel with midi input. A possible way to utilise would be to route the output of channels to selected FXs but probably the live performance will be worst. 
-a

**Comment by elieserdejesus** [comment]
@ancibug , you insert a FX (reverb, delay, etc) in the end of chain. For example, insert kontakt in first slot and insert a reverb in the 2nd slot. The reverb will be applyed in kontakt generated sounds.

**Comment by ancibug** [comment]
Good
Il 06/giu/2016 15:42, "Elieser Ademir de Jesus" <notifications@github.com>
ha scritto:
