### ISSUE TITLE
ASIO4ALL overload when using LISTEN button in Jamtaba standalone X64

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#430]
![image](https://cloud.githubusercontent.com/assets/15310433/15807560/cf7b8580-2b37-11e6-8368-4f42522bbcd3.png)

This is NOT happening with the vst plugin (x64) and standalone 32bits. This started to happen for me in 2.0.14. I first thought there was some problem with my system, but I installed old 2.0.13 and I don't have any problem with the x64 standalone and the listen button.

**Comment by jonjamcam** [comment]
Testing in 2.0.15 pre release now. I suspect this is an ASIO4ALL problem. Tweaking some settings in the ASIO4ALL panel got it workong fine, but after close and relaunch, the problem starts again.

 Using ASIO4ALL v2.13 on WIN7 64bit

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm using Asio4ALL 2.13 here too, no problems using 128 as buffer size.

But I'm suspecting mp3 decoder is blocking the audio thread.

**Comment by jonjamcam** [comment]
>I'm suspecting mp3 decoder is blocking the audio thread.

One question:

is it possible for this to happen ONLY with the 64bit standalone? I use the 64bit VST plugin and the Standalone 32bit with no problems.

I tested 2.0.14 in another laptop with ASIO4ALL 2.13 too and I have the a similar problem: The 32bit standalone version works pretty good there (with buffer 128), but the 64bit version does not work at all (maybe some ASIO4ALL/Audio hardware problem)

I will do more experiments. It's not a big deal for me because the 32bit version works like a charm.

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm using the 64 bits version here (both standalone and plugin) without problems.

**Comment by elieserdejesus** [comment]
@jonjamcam , this problem is a bit complicated to fix, probabily it's not a quick fix. Since I can't reproduce the bug in my JT 64 bits I will release v2.0.15. If this is really a bug I can work in this task in the next round.

**Comment by jonjamcam** [comment]
Sure, no hurries. I'm good with the 32bit version.

**Comment by jonjamcam** [comment]
I think I found the problem (I hope so). I did some tests using my ME-25 pedalboard as ASIO interface in two different laptops and ASIO4ALL too for comparison.

Sometimes Jamtaba's LISTEN feature (in standalone only) has a lot of crackle (kind of similar problem was posted here https://github.com/elieserdejesus/JamTaba/issues/203)

So if **ASIO4ALL** or my **ASIO ME-25** is used as interface with the **32bit version of Jamtaba** it can handle this problem, but crackles a lot! (no overload in this case). Same thing happens if I use the **ME-25** interface with the **64bit version** of Jamtaba (just some ugly crackle). The solution is in this case to restart Jamtaba. Sometimes I have to restart two or three times to get it working correctly.

So I'm guessing when this "crackle" is overloading the 64bit version when using ASIO4ALL because in this case I don't get the crackle, only the overload.

Does this make sense?

One more thing related: I did an experiment connecting to a server and jamming when this crackle hapenned in x64 and surprise. i got the nasty bug discussed here: https://github.com/elieserdejesus/JamTaba/issues/209

Coincidence or causation? I can't really tell.

**Comment by jonjamcam** [comment]
@elieserdejesus I have a hint on when the problem could have started in this case. As I said 2.0.13 was the last version that worked OK for me, but I did try 2.0.14 alpha and it's working fine too! So the problem was introduced probably by some commit between 24/april and 30/april. I have an hypothesis: The only mayor addition between 2.0.14 alpha and 2.0.14 final was the THEME menu. Do you think this merge could have messed something else? Just a guess.
