### ISSUE TITLE
Chat Message Box Background not available for stylesheet

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#433]
I'm looking for the color of the "jamtaba" message that's color gray, **not** the user specific color:

![image](https://cloud.githubusercontent.com/assets/15310433/15810579/9b0e57d4-2b76-11e6-82ee-11a0f7f316fc.png)

This is because I see that in the black theme the background could be a bit less bright and the border in the gray tones.

I found the background color is hard-coded here:

![image](https://cloud.githubusercontent.com/assets/15310433/15810878/423cecda-2b79-11e6-8ed5-815690e04a21.png)

Do you plan @elieserdejesus to add this item to the stylesheet?

**Comment by elieserdejesus** [comment]
@jonjamcam , I think a easy (and generic) solution is use a semi transparent color to match in all backgrounds.

Try change the BOT_COLOR to **::BOT_COLOT(255, 255, 255, 30);**

The 3 first values are a WHITE color, but the 4th value is the alpha. This "alpha trick" will result in different chat background colors for each theme. The chat message color will be always a little more brighter than background. You can control the brightness playing with different alpha values.

**Comment by jonjamcam** [comment]
> Try change the BOT_COLOR to ::BOT_COLOR(255, 255, 255, 30);

This was the (yellowish) result:

![image](https://cloud.githubusercontent.com/assets/15310433/15827925/b93bf366-2be3-11e6-8944-eccc4816aec4.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I checked the code was ignoring the alpha in BOT_COLOR. I pushed a commit allowing transparent colors for chat messages. I tested in the 3 themes and is working ok.

**Comment by jonjamcam** [comment]
Looks Great! I did a PR https://github.com/elieserdejesus/JamTaba/pull/434 for the **T** buttton (in common stylesheet) to avoid mismatched backgrounds

**Comment by jonjamcam** [comment]
last two things I noticed is to correct the hover to match and the **B** button has to be transparent too. 

![image](https://cloud.githubusercontent.com/assets/15310433/15842893/75dccbfe-2c33-11e6-9760-432a35b2bee9.png)

I'll work on these via PR.
