### ISSUE TITLE
kontakt 4 64 bits in win7 x64

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#44]
Jon report kontakt 4 64 bits in laptop with win7 x64 not receiving midi notes, only CC is working.

**Comment by jonjamcam** [comment]
@elieserdejesus I think Kontakt 4 is obsolete. Kontakt 5 works very good in Jamtaba!

**Comment by elieserdejesus** [comment]
I agree @jonjamcam , I'm using Kontakt 5 without problems too, closing.
