### ISSUE TITLE
Jamtaba <=> Reaninjam communication 

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#441]
As stated in https://github.com/elieserdejesus/JamTaba/issues/159#issuecomment-158065575 : 

> Reaninjam -> Jamtaba communication is a very common case.

![image](https://cloud.githubusercontent.com/assets/15310433/15881095/b298eb0a-2d09-11e6-93ec-1a62feaf3dde.png)

I have and two ideas on how to address this issue for the time being:

1.- use the "right click" menu (for block chat user) to specify that this user is using reaninjam. This way Jamtaba can interpret the characters the right way.

![image](https://cloud.githubusercontent.com/assets/15310433/15881200/720d1556-2d0a-11e6-9ba3-c5c158d34f03.png)

2.- Autodetect wrong coded characters and ask via button (or not) to change coding for this specific user.

![image](https://cloud.githubusercontent.com/assets/15310433/15881133/0c00c1cc-2d0a-11e6-96e6-f38f5a8c16e7.png)

**Comment by NakajimaYusuke** [comment]
Hi, I am also anxious about this problem.
In the current situation, I confirmed "ReaNinjam users and Jamtaba2 users can not chat in Japanese".
![hi](https://cloud.githubusercontent.com/assets/15982547/16210943/a42f5462-3779-11e6-9fee-5b9a67b241e8.png)
This screen shot is a conversation between the reaninjam(from WINE) and jamtaba2.
 Is this a same problem as yours?

I am not an expert on this, but I have another ideas.
Does it possible to fix the ReaNinjam side encoding by cockos?

teamikl has explained this problem to me in the past.
https://github.com/elieserdejesus/JamTaba/issues/159#issuecomment-158065575
As described in this table, most of NINJAM Client's has UTF-8 encoding.
On the other hand, Ninjam standalone(win) and ReaNINJAM(win) has Native encoding.
So, they seem to outsiders.
If the root of this issue is their native encoding, I think cockos side fix is also one method to Improve this issue.

**Comment by elieserdejesus** [comment]
> Does it possible to fix the ReaNinjam side encoding by cockos?

@NakajimaYusuke , I think cockos is not touching the Reaninjam code in the last years. I believe the solution need be programmed in the clients, unfortunally.

@jonjamcam , the solution you proposed in the first post is possible, we can use another text decoder for some users to avoid the wrong letters, but this will solve only the "received" messages. We can't send messages to different ninjamers using different encoders, we need send the text to the server (using one encoder) and the server will retransmit (without change the encoded text). I can't see a solution for the "send" part at moment.

**Comment by jonjamcam** [comment]
@elieserdejesus @NakajimaYusuke  

I agree with that the problem relies on the other clients, not in Jamtaba. The chat works fine for different languages, so IMO the burden rest on Cockos in this case.

Having said that, let's say we find a way to make Jamtaba and reaninjam communicate correctly, then I propose a workaround to solve the issue:

 We could implement a global "chat compatibility mode" for Jamtaba **per session**. For example if a Chat message is detected with anomalous characters, then the Jamtaba client could suggest via button "Activate compatibility mode for the chat", so now both clients (Jamtaba and reaninjam) are communicating correctly. In this case other Jamtaba clients will detect incorrect characters at some point and ask the same.

 In this case the problem could be solved for everyone and when the session ends, the setting reverts to normal (like the block button) .

**Comment by elieserdejesus** [comment]
@jonjamcam and @NakajimaYusuke 

I in Reaper change log history the last change in ReaNinjam was done in **2014**:
```
v4.721 - August 19 2014
  + API: fixed GetSetTrackSendInfo() UI refresh issues [issueid=2642]
  + MIDI editor: fixed toggle states of Humanize/Transpose notes actions
  + ReaNinjam: fixed chat window crash on OSX [p=1390449]
  + Stretch markers: fixed marker visibility bugs when using take playrates
```

I think we can try request a litle fix in Reaninjam to use utf-8 in chat. Since is not a big change maybe a good soul in cockos can spend some minutes helping the community :) This will solve the problem in the root, I think worth trying.

**Comment by jonjamcam** [comment]
> last change in ReaNinjam was done in 2014:

Indeed. Damned posted it as a reaper bug in the cockos forum:

http://forums.cockos.com/showthread.php?t=144097

IMO the only way the Cockos people will see the post if it's in the **reaper bugs** section.

**Comment by jonjamcam** [comment]
@NakajimaYusuke @elieserdejesus 

I did some tests using Japanese and Russian characters involving Jamtaba2, Wahjam and NinjamJS. This is the result:

![image](https://cloud.githubusercontent.com/assets/15310433/16255408/eb14de6e-381f-11e6-9e44-63468f56c061.png)

So ATM Jamtaba2 and Wahjam (and I suppose Jammr too) are communicating OK to my surprise (Both use UTF-8). Tea has the full explanation here:

https://github.com/elieserdejesus/JamTaba/issues/159#issue-117787765

I can't test reaninjam osx, but if Tea is correct it will be working too!

So this leaves only reaninjam win and old win ninjam client encoding chat messages wrongly.

 I guess we can make a strong case in the cockos forum's **bugs report** for reaninjam win communicating incorrectly with reaninjam mac, specially (as Tea noticed):

> But, this is not JamTaba specific problem,
It even happen between official client on Mac <=> Win

Also, if we get Ninjam JS to adopt the UTF-8 standard too I think this can make a very solid case for the cockos crowd to correct the win reaninjam code for good.

**Comment by jonjamcam** [comment]
As @elieserdejesus  suggested, I just posted https://github.com/elieserdejesus/JamTaba/issues/441#issuecomment-227409322 in the reaper forum:

 http://forums.cockos.com/showthread.php?p=1697951#post1697951

I also created an issue in NINJAM JS Github page (https://github.com/BHSPitMonkey/ninjam-js/issues/6)

Let the force be with us.

**Comment by elieserdejesus** [comment]
@jonjamcam , great work, thanks for your engagement!

**Comment by NakajimaYusuke** [comment]
Thank you very much!
I expect good response from Cockos.

**Comment by jonjamcam** [comment]
@NakajimaYusuke This is off topic: we need Japanese translation of the new features for the upcoming 2.0.15 release . Are you interested to collaborate as a translator for us?

**Comment by jonjamcam** [comment]
@elieserdejesus @NakajimaYusuke @teamikl **It's fixed!!!** I can't believe it guys!

![image](https://cloud.githubusercontent.com/assets/15310433/16286466/e46bf3a2-38b2-11e6-82cc-cddcf9c91874.png)

**Comment by elieserdejesus** [comment]
Great news @jonjamcam , really great news!!!

**Comment by NakajimaYusuke** [comment]
I also confirmed. It's working. Thanks to you and cockos!

@jonjamcam
I'd like to cooperate if I can. But I'm sorry. I am not a coding guy.
Unfortunately, I do not understand how to use github. Sorry.

So, I think @teamikl or @takeshitaleo are the right person for this task.
Do they busy now? If both are busy, I'll do it.
But in that case, I can only just a text translation.
(Overwriting the Japanese words to the "unfinished" in ja_JP.ts )
Other github-related operations is difficult task for me.

**Comment by jonjamcam** [comment]
> Do they busy now?

@NakajimaYusuke 

Probably they are busy right now.

 The easiest way to do a translation is:

1.- download QTLinguist from here :

 http://qt-apps.org/content/show.php/Qt+Linguist+Download?content=89360

and Install.

2.- Download the ja_JP.ts File from here (right click "save as"):

https://github.com/elieserdejesus/JamTaba/raw/master/translations/ja_JP.ts

3.- open the ja_JP file in QTLinguist and translate. When you finish each phrase you just click on the **?** symbol. It will change to a Check. When finished, juse post the file here and @elieserdejesus will merge the transaltion.

Thank you very much for your interest. It is greatly appreciated. This is the last step before release. Any problem just ask in this thread if you want or in the translation thread here : https://github.com/elieserdejesus/JamTaba/issues/446#issuecomment-227528721

**Comment by NakajimaYusuke** [comment]
Thank you for detailed explanation. I will try soon.

**Comment by jonjamcam** [comment]
Ninjam JS just added UTF-8 Support too: https://github.com/BHSPitMonkey/ninjam-js/commit/7d0f102322323ef9151bec8439b02c0cfd27390a
