### ISSUE TITLE
new clipsort.log option creates an additional "audio" folder

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#444]
@elieserdejesus @pljones 

I tested only clipsort recording for the preferences:

![image](https://cloud.githubusercontent.com/assets/15310433/15993596/4ff59578-30c1-11e6-92c0-dec3e6db6bfd.png)

So I expected one folder to be created as happens with reaninjam, but:

![image](https://cloud.githubusercontent.com/assets/15310433/15993562/2a5b16ae-30c0-11e6-9e93-1ba095923f12.png)

The "audio" folder is not necessary in this case because all audio is contained in the clipsort folder and it opens fine in reaper. 

Am I missing something here?

EDIT: The audio folder is full of .ogg files too corresponding to the same session.

**Comment by pljones** [comment]
I'm on the case for that one already.

**Comment by pljones** [comment]
Hi,

(Rewriting the previous comment now I'm more awake...)

What's meant to happen is as follows:

1) The main "Save multi tracks" decides whether any recording of the jam is performed.
2) The checkboxes beneath decide what kinds of recording are made.  Currently there are two possible choices

- creating a Reaper Project file (RPP) and its associated audio files with human-readable clip names.
- creating a clipsort.log file and its associated audio files, where the names are random hex numbers.

I had noticed that the code doesn't check what is meant to be recorded when creating the output directory for the Reaper Project file audio clips.  However, I had _not_ seen that it was creating the clips - that shouldn't happen (indeed, I'm sure I tested that and it wasn't happening).  I'll have to investigate further.

-- Peter

**Comment by jonjamcam** [comment]
> I had not seen that it was creating the clips

Hi @pljones .Just tested with last fetched code. This is what I did:

1.- Run from QT creator (standalone version) and setup the folder to record in and check only this two boxes:

![image](https://cloud.githubusercontent.com/assets/15310433/16021389/c9a6af66-3188-11e6-9cce-999ae33fd716.png)

2.- Now I enter an empty ninbot server and wait a couple of cycles. This is the result:

![image](https://cloud.githubusercontent.com/assets/15310433/16021433/0f478f9a-3189-11e6-8e3b-86427e4276c5.png)

A Folder was created with today's date and time. Inside I have a **reaper** folder and inside this there's two more folders: **Audio** and **Clipsort**:

![image](https://cloud.githubusercontent.com/assets/15310433/16021496/6ac74dc4-3189-11e6-8cee-fda43946786e.png)

Now, the **audio** folder has one **.ogg** file:

![image](https://cloud.githubusercontent.com/assets/15310433/16021522/92bd7d08-3189-11e6-883a-f1c4056772f5.png)

and the **clipsort folder** has the expected numbered folder plus a **clipsort.log** file in the root:

![image](https://cloud.githubusercontent.com/assets/15310433/16021556/babee0d0-3189-11e6-89a0-2e85c24b3983.png)

You can see that inside the **6** folder there's an **.ogg** file:

![image](https://cloud.githubusercontent.com/assets/15310433/16021573/daeddca8-3189-11e6-9331-3ca7343c9d0b.png)

So in my system, the audio folder and the .ogg files inside are indeed created.

>the code doesn't check what is meant to be recorded when creating the output directory for the Reaper Project file audio clips

This is probably the problem, as the files in the **audio** folder look pretty much like the **generate reaper project file** option when it's checked.

**Comment by pljones** [comment]
Hi,

I've checked -- the audio directory is the audio before the files are put into the Reaper Project or copied into the name used by clipsort.log.

I'll try to see what the best approach to handling this is.

-- Peter

**Comment by jonjamcam** [comment]
Just to be sure I did the test in reverse:

![image](https://cloud.githubusercontent.com/assets/15310433/16022036/46aa64dc-318c-11e6-9108-13b410cce31b.png)

The result was two folders created inside the **reaper** folder:

![image](https://cloud.githubusercontent.com/assets/15310433/16022063/6bab84fa-318c-11e6-89bf-25129a9dfb56.png)

and now the RPP file is created. Inside the **audio** folder there's some .ogg files:

![image](https://cloud.githubusercontent.com/assets/15310433/16022125/b0ff15ee-318c-11e6-9097-2dffe8d45514.png)

and the **clipsort** folder is now empty.

**Comment by jonjamcam** [comment]
I did a third test. The system allows you to uncheck both options, but leave **save multi tracks** active:

![image](https://cloud.githubusercontent.com/assets/15310433/16022317/9607b2b8-318d-11e6-8145-25fa7c2e0b46.png)

The result is no recording at all (**not** even an empty folder is created). I think this option should not be allowed because if users only check the "save multi tracks" option then they will think they are recording and that will not be the case.

**Comment by pljones** [comment]
As noted above, I think the idea was to have the nicely named clips saved always if the multi-track recording is enabled, with the checkboxes used for the added features (clipsort.log and Reaper project file).

I could have a go trying clipsort.log with the nicely named clips but I don't think it'll work.

**Comment by jonjamcam** [comment]
>I think the idea was to have the nicely named clips saved always if the multi-track recording is enabled, with the checkboxes used for the added features

As I see it @pljones now we have two methods of storing the audio. Some will use the traditional clipsort method and others will prefer a RPP file. I see them both equal as options, but I think the user should choose one or another. If you choose both then you'll have sessions recorded twice.

 I see this could work the same way as the metronome options:

![image](https://cloud.githubusercontent.com/assets/15310433/16023789/d0d71f6c-3194-11e6-98d7-6254f469f1a6.png)

you want to use your own sounds **or** choose from a list that's pre-loaded. You can't have both.

**Comment by elieserdejesus** [comment]
@jonjamcam 
> As I see it @pljones now we have **two methods** of storing the audio. 

If I understand correctly @pljones is proposing **3 methods**:
1 - Save only audio clips (no clipsort file, no reaper project, usefull when we want drag these audio clips to DAWs (Reaper or not)).
2 - Save audio clips + reaper project
3 - Save audio clips + clipsort file

I'm understand correctly @pljones?

**Comment by pljones** [comment]
Hi @jonjamcam, @elieserdejesus,

For now, I've done a first simplification:
https://github.com/elieserdejesus/JamTaba/pull/451

This makes it so that the "writer" owns creation of the files its going to supply the metadata for (i.e. RPP or clipsort.log know what files they want, so they supply the file names and ensure the directories are in the right place).

If the non-specific audio clips are also wanted, my proposal would be to add a third writer.  This is on the basis most people will probably only have one running at a time...

Let me know if this sounds okay.

-- Peter

**Comment by elieserdejesus** [comment]
> This is on the basis most people will probably only have one running at a time...

I agree. I will check the PR.

**Comment by elieserdejesus** [comment]
@pljones , issue solved here?

**Comment by pljones** [comment]
It would be very easy to add the third writer if all that's needed is the separate ogg files (say in one sub-directory per "track").  I could get that done later today.  (Of course, you can use the Reaper Project recorder and just ignore the RPP file.)

I think it would also be possible to have a writer that had a single WAV per track, too, which might be more useful to non-Reaper users.  However, this would have to change where the audio data comes from - i.e. before encoding for local and after decoding for remote.  I'd probably need a while to work out how much change was needed to see if this was a realistic idea...

So @elieserdejesus, the issue as reported is solved.

**Comment by elieserdejesus** [comment]
@pljones , let's discuss the "single wav per track" in the issue #4.
