### ISSUE TITLE
Update translation for 2.0.15

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#446]
Hi @jonjamcam , @teamikl , @MagnusDrumsTrumpet, @DoublebassOO !!!
It's time to update the translation files for Jamtaba *v2.0.15*. We have **25 new phases/words** to translate in this new Jamtaba version. 

The updated translation files (.TS files) are available in this repository ([in master branch](https://github.com/elieserdejesus/JamTaba/tree/master/translations)).

After opening the TS file in QtLinguist you will see the missing translation as **yellow question marks**:

Thanks in advance, I will appreciate your collaboration!!

- [x] update portuguese translation
- [x] update spanish translation
- [x] update german translation
- [x] update french translation
- [x] update japanese translation

**Comment by jonjamcam** [comment]
@elieserdejesus es_CL translation is complete in https://github.com/elieserdejesus/JamTaba/pull/448.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !

**Comment by MagnusDrumsTrumpet** [comment]
huhua jungle  i did propose can you see it and use it ? hope so )greeets from mag  goodnight )
 

    Elieser Ademir de Jesus <notifications@github.com> schrieb am 15:42 Montag, 13.Juni 2016:
 

 Hi @jonjamcam , @teamikl , @MagnusDrumsTrumpet, @DoublebassOO !!!
It's to update the translation files for Jamtaba v2.0.15. We have 25 new phases/words to translate in this new Jamtaba version. The updated translation files (.TS files) are available in this repository (in master branch).After opening the TS file in QtLinguist you will see the missing translation as yellow question marks:Thanks in advance, I will appreciate your collaboration!!—

**Comment by elieserdejesus** [comment]
Thanks @MagnusDrumsTrumpet !

**Comment by jonjamcam** [comment]
@elieserdejesus One question:

Are this two translations (jp, fr) the only missing parts for 2.0.15 to be released?

**Comment by MagnusDrumsTrumpet** [comment]
did double get the messages?
 

    jonjamcam <notifications@github.com> schrieb am 17:58 Freitag, 17.Juni 2016:
 

 @elieserdejesus One question:Are this two translations (jp, fr) the only missing parts for 2.0.15 to be released?—

**Comment by elieserdejesus** [comment]
> Are this two translations (jp, fr) the only missing parts for 2.0.15 to be released?

Yes @jonjamcam , I'm waiting Double and Tea until this weekend. I'm not shure if they are receiving these github notifications.

**Comment by DoublebassOO** [comment]
i just discover the message...
but cant find how  to download the ts files, to open it in QT ling

thks

2016-06-17 21:28 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
Hey @DoublebassOO , this is the link to the french file: [https://github.com/elieserdejesus/JamTaba/blob/master/translations/fr_FR.ts](https://github.com/elieserdejesus/JamTaba/blob/master/translations/fr_FR.ts)

**Comment by jonjamcam** [comment]
@elieserdejesus Did you include the last merge (encoder quality) in the translation?

**Comment by elieserdejesus** [comment]
it's updated now @jonjamcam. 7 little changes in TS files.

**Comment by jonjamcam** [comment]
es_CL Translation updated

**Comment by DoublebassOO** [comment]
very sorry but still dont find any button to download it ?

2016-06-20 6:01 GMT+02:00 jonjamcam <notifications@github.com>:

**Comment by elieserdejesus** [comment]
no problem @DoublebassOO . To download the file:
1 - enter in this link

2 - Click in the **Raw** button (check the image) to see the "real" file.

3 - Using right mouse button choose the "Save as ..." action to save the file in your computer.

![image](https://cloud.githubusercontent.com/assets/1012741/16192037/7e134264-36bd-11e6-87f1-93917011ce77.png)

**Comment by DoublebassOO** [comment]
Wow not such evident for a noob like  me  :)

thks


2016-06-20 13:04 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by DoublebassOO** [comment]
Hello
here the translate ts file




2016-06-21 0:15 GMT+02:00 Armand Dumonteil <armanidu33@gmail.com>:

**Comment by elieserdejesus** [comment]
@DoublebassOO , I can't see the file. I think github is removing the attached file in your email. Can you send me the file again in my email?

**Comment by DoublebassOO** [comment]
ok i send it to your private email

2016-06-21 1:07 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com>
:

**Comment by elieserdejesus** [comment]
Thanks @DoublebassOO , your file is merged.

**Comment by jonjamcam** [comment]
@elieserdejesus I tried to fix all I could with the previous release in these PRs (https://github.com/elieserdejesus/JamTaba/pull/463, https://github.com/elieserdejesus/JamTaba/pull/464 and https://github.com/elieserdejesus/JamTaba/pull/465), but DE and JP still have relevant missing items. FR has only one unfinished item that does not appear so important (for me). here's the list:

DE (5): "Encoder quality:", "Low (good for slow internet connections)", "Normal (default)", "High (for good internet connections only)" and "Custom quality"

FR (1): "Can't open the link!"

JA (32): Pretty big list. Maybe we could ask Leo or Nakajima help to finish this translation?

**Comment by elieserdejesus** [comment]
@jonjamcam, thanks for this review in translations.

@MagnusDrumsTrumpet , can you translate these 5 items for us?
```
DE (5): "Encoder quality:", "Low (good for slow internet connections)", "Normal (default)", "High (for good internet connections only)" and "Custom quality"
```

@DoublebassOO , can you translate the phrase ** Can't open the link!** for us?

@jonjamcam , I don't know **Leo**. He is in github too? Can you invite Leo and Nakajima?

**Comment by jonjamcam** [comment]
> I don't know Leo. He is in github too? 

He made a contribution once. A correction of the Japanese translation:

https://github.com/elieserdejesus/JamTaba/pull/364

**Comment by DoublebassOO** [comment]
hi

** Can't open the link!**
translation       **Impossible d'ouvrir ce lien !**     or       **Ce lien
ne s'ouvre pas !"

2016-06-21 13:01 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by jonjamcam** [comment]
fr_FR translation updated in PR https://github.com/elieserdejesus/JamTaba/pull/466

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !

**Comment by jonjamcam** [comment]
@takeshitaleo Hello. I saw you contributed in the past with a translation to Jamtaba.  For next release (2.0.15) we have 32 phrases to translate for the new features.

 Is it possible for you to complete the ja_JP translation this time?

**Comment by NakajimaYusuke** [comment]
Here you are! I did Japanese translation. Is this OK?
http://crasher.orz.hm/ninjam/files/ja_JP.ts

However, many of the translation words ware new features related.
Therefore maybe there are some misunderstanding translations.
I want to check them again after the 2.0.15 release.

**Comment by jonjamcam** [comment]
> Here you are! I did Japanese translation. Is this OK?

Nice! @NakajimaYusuke I did revised it. I'm correcting some punctuation only. I will make the PR, so don't worry. It is complete, yes. Thank you very much!!!

@elieserdejesus. I'm making a PR for ja_JP transaltion.

**Comment by elieserdejesus** [comment]
thanks @NakajimaYusuke  and @jonjamcam !

**Comment by elieserdejesus** [comment]
@jonjamcam and @NakajimaYusuke , I created a pre release for [JT v2.0.15](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.15-pre). Let's run the last tests before the offcial release.

**Comment by NakajimaYusuke** [comment]
Amazing! 
I checked my work.
Fortunately, wrong translated word wasn't found. JP translation is OK.

**Comment by jonjamcam** [comment]
@elieserdejesus Echnaton9000 just accepted to translate the 5 missing german items.

**Comment by vector21** [comment]
This is the german translation for the 5 open strings:

"Encoder quality:" = **"Encoder Qualität:"**
"Low (good for slow internet connections)" = **"Niedrig (gut bei langsamer Internetverbindung)"**
"Normal (default)" = **"Normal (default)"**
"High (for good internet connections only)" = **"Hoch (nur bei schneller Internetverbindung")**
"Custom quality" = "Benutzerdefinierte Qualität"

Have fun coding!
Echna (aka vector21 ;-)

**Comment by jonjamcam** [comment]
@vector21 Thx! PR https://github.com/elieserdejesus/JamTaba/pull/468 created!

@elieserdejesus Translation is complete for 2.0.15 .

**Comment by elieserdejesus** [comment]
thanks @vector21  and @jonjamcam ! I will release the v2.0.15 in this afternoon!

It's energizing work with you guys, I really appreciate your collaborations and engagement!
