### ISSUE TITLE
Fire Theme

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#450]
@elieserdejesus Last night I took a look to your discarded orange theme and did some work based on the colors you were working on.. Orange is a difficult pallette to work with, but the results could be very pleasing to the eye if achieved:

![image](https://cloud.githubusercontent.com/assets/15310433/16022951/d097046c-3190-11e6-9aba-371531d7d6c1.png)

I noticed this colors created for me peace and rest. Remember the other themes are mostly gray or Black, very different mood I must say (for me at least). Do you think we should give it a chance? I'm thinking about version 2.0.16 for release.

**Comment by elieserdejesus** [comment]
@jonjamcam 
> Do you think we should give it a chance?

Shure, I like the orange palletes. Im my opinion you can explore yellow tones and drop all gray colors. My idea is a more a "Fire" theme than a "Orange" theme, but feel free to experiment:
![image](https://cloud.githubusercontent.com/assets/1012741/16023837/0e8e3af2-3195-11e6-9d1f-20eaf810b167.png)

**Comment by jonjamcam** [comment]
@elieserdejesus I made a new PR (https://github.com/elieserdejesus/JamTaba/pull/489) with the work I have so far so you can test both themes (Orange and Fire).  I'm not sure which one will prevail, so this PR contains both, which are very different. Any comments are very much appreciated :D

**Comment by elieserdejesus** [comment]
@jonjamcam , I really like the "Fire" theme. In my opinion the Orange theme not worth, I think is better drop the Orange files and work only in "Fire". 

In FabFilter Volcano plugin (the plugin in the image) a cool yellow gradient is used in the main controls. I suggest use the same color in faders (pan, level) and buttons.

**Comment by jonjamcam** [comment]
OK. let's drop the Orange. About the name do we keep "Fire"?

**Comment by elieserdejesus** [comment]
I like the "Fire" name, but "Volcano" sounds good too. Or  "Hot" and create a new "Cold" theme in future. 

At moment my vote is for "Fire", but we can keep this opened until release.

**Comment by jonjamcam** [comment]
I agree. That "cold" theme idea sounds good. I was thinking about a "Blue" theme some days ago. Maybe we can try an "Ice blue" kind of theme when this one is completed.

**Comment by elieserdejesus** [comment]
Ice Blue sounds perfect. Another idea for theme is a Reaper theme matching Reaper colors.

**Comment by jonjamcam** [comment]
@elieserdejesus I'm radically "burning" the fire theme:

![image](https://cloud.githubusercontent.com/assets/15310433/16863707/9481277c-4a23-11e6-872f-6e587b167bc9.png)

 So I need to change the color of the WavePeakPanel, but I found it's hard-coded. Is it possible to make it style-customizable?

![image](https://cloud.githubusercontent.com/assets/15310433/16863678/43d9632a-4a23-11e6-9d39-435dd65af3f6.png)

I need the color of the buffer circle too, but this one I can't find.

**Comment by elieserdejesus** [comment]
> So I need to change the color of the WavePeakPanel, but I found it's hard-coded. Is it possible to make it style-customizable?

I think is possible @jonjamcam , but I need investigate how expose these custom colors.

About the Fire theme, I think the background colors are too strong/hot, this is a problem if you look at the screen for long periods, your eyes will burn :)  I suggest a lighter version of these orange/red colors for backgrounds, will look more smooth.

**Comment by jonjamcam** [comment]
>  I suggest a lighter version of these orange/red colors for backgrounds, will look more smooth.

True, it too wild. Let's explore other options before push.

**Comment by jonjamcam** [comment]
here's some other source for palette:

![image](https://cloud.githubusercontent.com/assets/15310433/16898843/317557ce-4bb9-11e6-84da-7cb1ef99c994.png)

I've not been able to get away from the burning colors posted before:

![image](https://cloud.githubusercontent.com/assets/15310433/16898849/88ba6e8e-4bb9-11e6-8056-d97e562e7563.png)

so I found this softer fire to work with...

**Comment by elieserdejesus** [comment]
The fire image is very nice, good pallete.

**Comment by jonjamcam** [comment]
> The fire image is very nice, good pallete.

Ok so I'm pushing the changes. I did some more work with the buttons , but as you pointed out, the background should be darker.

**Comment by jonjamcam** [comment]
Fire theme was replaced by Volcano theme https://github.com/elieserdejesus/JamTaba/pull/507
