### ISSUE TITLE
New Jam folder is not created if time and date is the exactly the same as previously archived jam

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#452]
If more than one Jam is recorded at exactly the same date/time, then the sessions are mixed into one single jam.

I'm thinking about problems when changing timezone or winter/summer clock adjustments for example. Or if the local clock has problems, jams will be messed up.

Is there a possibility to force the creation of a new folder every time a jam is recorded?

**Comment by elieserdejesus** [comment]
@jonjamcam , I created a PR to create different jam folders. The solution is 99% bullet proof, please read the PR to see the %1 problem :)  #453

**Comment by jonjamcam** [comment]
@elieserdejesus  Tested. working much better now!
