### ISSUE TITLE
Vorbis encoder Quality option for users to choose

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#456]
@elieserdejesus @pljones @teamikl 

I did some tests today connecting to a public server just changing the parameter QUALITY for the encoder. The results were a big surprise for me, so I want to share them with you.

 The idea that users could choose the quality of their encoded sound is very important I think.

 For example if you have a bad connection, you could lower this value and still get Jamtaba work OK (the alternative now for bad connections is reaninjam or the old ninjam client) and don't loose all the goodies that other clients don't have like chords, block, cache, etc..

 On the other hand if you have a really good connection and a lot of Upstream bandwith you could have a near-studio quality session in a private server (this is not a good idea for public servers).

The idea behind this experiment was to test the limits and resilience of a server connection. I chose a ninbot.com public server for this, so there we go:

I used three values for the test:

 0.32f (jamtaba default quality)

0.99f (I suppose this is the maximum possible value)

0.01f (I suppose this is the minimum possible value)

I did a test sending exactly (by watch) 60 seconds of the same loop and capturing a screenshot of the data sent once the time was reached.

![image](https://cloud.githubusercontent.com/assets/15310433/16095763/7db3b5aa-331c-11e6-9f55-75e61844c0a0.png)

This test was only with 1 user and 1 channel, so the results may vary in other cases. For the moment the Maximum quality is out of the question (too much demanding IMO), but maybe in the future when internet speeds upload speed meet the requirements, why not? :D.

About offering a lower speed for upstream encoding I think it's much neccesary. There are some hours some days where I live where my own connection is unable to keep Jamtaba connected and I have 512 Kbit upload ATM and I'm sure I'm not the only one who have this problem.

EDIT: DATA RECEIVED is really DATA SENT by Jamtaba Client

**Comment by elieserdejesus** [comment]
@jonjamcam , I think these details about **encoding quality** are very low level to common users. So, I'm not shure about put another option in preferences.

A simple solution is create a new entry in **Jamtaba.json** to control the **vorbis encoder quality**. This is not complicated to implement, advanced users can use custom encoding quality and common users will use the default/current quality.

I have 2 things in mind:
1 - we need decide how users will "input" the encoding quality: values at [0, 1] or default pre-defined values like LOW_QUALITY, GOOD_QUALITY, KICK_ASS_QUALITY ?

2 - Maybe the current default encoding quality in Jamtaba is too high. The Kpbs in ogg vorbis is not same as in mp3 world. For example, a 96 kpbs ogg vorbis is equivalent to a 128 kbps mp3. In general people look to ogg vorbis kbps using the same mp3 "metrics". Possibly we can use a more low quality encoding in Jamtaba (using less upload bandwith) without affect the perceived audio quality. 

@jonjamcam , are you interested in a little experiment? Something like compress the same wave audio with different ogg vorbis qualities to determine the minimum quality for Jamtaba?

**Comment by jonjamcam** [comment]
> A simple solution is create a new entry in Jamtaba.json to control the vorbis encoder quality

To keep it simple this is a good solution and very flexible. I think if the installer can ask the user how good is the connection quality, then it can set a better default value in each case. For example:

![image](https://cloud.githubusercontent.com/assets/15310433/16121364/59a1b854-33b9-11e6-98bf-c81f8f16c8f8.png)

Using our experience we can set the Json values marching this conditions so the user never has to worry about this issue.

> Maybe the current default encoding quality in Jamtaba is too high. The Kpbs in ogg vorbis is not same as in mp3 world.

Yes. It's true. But to have a definite opinion I must do some experiments with my old acoustic drum set recordings

> are you interested in a little experiment? Something like compress the same wave audio with different ogg vorbis qualities to determine the minimum quality for Jamtaba?

 I'm very interested. Quality issues and knowing the best trade off between quality and bandwidth has become for me more like an obsession since I use Ninjam. But that's because I was shocked with the lack of flexibility the other clients have on this matter.

**Comment by elieserdejesus** [comment]
@jonjamcam , the "ask in installer" idea is good, but is a windows only solution because the linux and mac installers are totally different, maded with different tools, etc.

**Comment by jonjamcam** [comment]
> the linux and mac installers are totally different,

Mmmm, then what do you think about a menu option inside Jamtaba? Something like "Connection setup" so all clients have the same "user friendly" configuration?

**Comment by jonjamcam** [comment]
> we need decide how users will "input" the encoding quality: values at [0, 1] or default pre-defined values like LOW_QUALITY, GOOD_QUALITY, KICK_ASS_QUALITY ?

IMO we only need three at most: **low**, **normal** (or default) and **high** [0, 1, 2] I can do some tests this weekend so we have a better idea on what this means.

The criteria could be:

**Low**: similar to reaninjam's quality. Very low bandwith and acceptable quality for most instruments. In this case, stereo and high frequencies are very degraded, but it's a good tradeoff for bad connection environments.

**normal**: Depending on the results of the experiments to choose a value not exceding default ogg compression (0.3). This could result in bandwith usage in the range of 96-128 Kbit. Testing pending.

**High**: something between what we have now (0.32) and a value not exceding 0.6. I saw many comments about ogg compression in forums that say there's no point in compressing  0,7 or more. Subject to testing too.

**Comment by pljones** [comment]
My only comment here is to think carefully about the public servers.

If a user with a lower bandwidth connects and gets swamped with data from too many high quality streams, they're not going to be happy (I've seen people lose connections to very busy rooms with the settings people have now because of this).  A server with 10 users each with two stereo channel at high quality could end up taking more than the clock time of one interval to download.  Changing your upload quality won't help you.

So yes, in the end it comes down to deciding what's good enough and whether it does more harm than good.

**Comment by jonjamcam** [comment]
> If a user with a lower bandwidth connects and gets swamped with data from too many high quality streams, they're not going to be happy

That's a good point you make @pljones . My experience is in general with a standard connection of 2 MBit (until recently) is enough even if all users are using jamtaba with two channels. Let's do the math:

Jamtaba's 1 channel consumes 133 Kbit at the moment, this means:

2Ch = 266 Kbit of bandwith per user max.

If you enter a 7 slot server you'll need to have maximun :

6*266 Kbit = **1.6 Mbit** bandwith availabe for downstream.

This is less bandwith that a 720p stream uses, and this is worst case scenario, so I think the standards are not exceded in this case:

http://www.lockergnome.com/media/2013/02/07/how-much-bandwidth-do-you-need-to-live-stream/

Said that, if someone is having problems and need the streams to be smaller, another solution is to use the ogg ability for **bitrate peeling**.

https://en.wikipedia.org/wiki/Bitrate_peeling

"The purpose is to provide access to the clip for people with slower Internet connections"

 This is awesome feature, so if this can be applied to Jamtaba we'll get the best of all worlds.

So if someone has a crappy connection, hopefully Jamtaba can "Peel"  the incoming streams to a lower quality.

What do you think about this guys?

**Comment by elieserdejesus** [comment]
@jonjamcam , about bitrate peeling I was thinking "who decided" about the "best stream quality", clients or servers?  From the wikipedia text:
> The server automatically chooses which stream to deliver to the user, depending on user's connection speed.

This is a problem because the bitrate peeling need be implemented in ninjam servers.

**Comment by jonjamcam** [comment]
> This is a problem because the bitrate peeling need be implemented in ninjam servers.

well, it was too good to be possible :(

**Comment by jonjamcam** [comment]
OK. My first quality tests using an old recording of a jam using my acoustic drumset (2012). This is the same quality I used with the old reaninjam client and then it was degraded a lot after encoding.

 This mix is done using multitracks recorded before going into the computer using 24bit 48Khz WAV files (KORG d3200) and compressed the final output with FLAC. 

Change extension and unrar these files:
 
[sample.rar.txt](https://github.com/elieserdejesus/JamTaba/files/321583/sample.rar.txt)

Why I used this particular clip. Because the reaninjam quality was horrible. This is obvious when you hear the clip with quality -0.1 (similar to reaninjam).

I recommend you start by the original, then go Q = 0.3, then 0.2, then 0.1 and finally -0.1

Please listen to the clips before reading further.


****


Now if you heard the clips with a good pair of headphones you would agree with my following conclusions: 

Quality 0.1 is pretty good, but the stereo image of the hihat is reduced. I think this quality is enough for the average user (a default quality) and it consumes an acceptable amount of bandwidth (105 Kb/s).

Quality 0.2 and 0.3 is very similar to 0.1, but the difference is how high tones (hihat) and it's stereo image is compromised less than 0.1.

I won't go any further because of bandwidth concerns. So I think we can use **-0.1 as low**, **0.1 for default** and **0.3 for high**.

Overall if you compare 0.3 with the original you will see a huge difference in depth and clarity in the hihat as well as the details in the stereo image, but this can't be solved unless you use a lossless encoder and that's in the range of 700-1000 Kbit/s of bandwidth usage (totally out of the question) or if you record the audio using the WAV format, but take the signal before Jamtaba compresses it.

**Comment by elieserdejesus** [comment]
@jonjamcam , I tested your audios here using a AKG K 240 MkII phone, is a good enough phone. I agree with all your conclusions. But I'm confuse with the audio format you posted. You posted .flac files, not ogg vorbis files, and we are discussing the ogg vorbis quality. 
So, when you mentioned the quality values (0.1, 0.2, 0.3, etc.) **are you mentioning vorbis quality values, right**?  If yes, why the flac files? You just converted the ogg vorbis to flac?

**Comment by jonjamcam** [comment]
> you posted .flac files, not ogg vorbis files, and we are discussing the ogg vorbis quality. 

OK. I used the clipsort recorder to get the compressed file, but for this I have to open Reaper and render, so the render is in FLAC, but from a ogg compressed source

**Comment by elieserdejesus** [comment]
@jonjamcam , understand now, thanks for the experiment. 

I will work in a first version allowing different vorbis quality values in Jamtaba .json config file. This is quick to programming and can be done for the v 2.0.15.

**Comment by elieserdejesus** [comment]
@jonjamcam , I created a PR allowing custom encoding quality in .json file. Can you test too? To help testing you can enable the encoder logging to see a message about the encoding quality. This message will appear in the log file only if you enter in a server (when encoders are created).

**Comment by jonjamcam** [comment]
@elieserdejesus I activaded the logging

![image](https://cloud.githubusercontent.com/assets/15310433/16172913/e547488c-3568-11e6-8443-cbe2981a0258.png)

But I can't find the option in the json file:

![image](https://cloud.githubusercontent.com/assets/15310433/16172884/630d4f4c-3568-11e6-8d1c-75c60c82de5c.png)

...

![image](https://cloud.githubusercontent.com/assets/15310433/16172880/4818b7ee-3568-11e6-9ecb-fc3957eb6cd3.png)

**Comment by jonjamcam** [comment]
MY BAD I was'n in the correct branch. SRY, testing now....

**Comment by jonjamcam** [comment]
Another test: I tried to use 0.9 as a value in the json file, but it will only accept max 0.3 as expected

![image](https://cloud.githubusercontent.com/assets/15310433/16173147/76b5aca0-356e-11e6-85e0-e93f1869ad8d.png)

**Comment by jonjamcam** [comment]
@elieserdejesus One final test on ogg quality. I did this one because I'm finding it hard to find any difference at all between Q=0.2 and Q=0.3.

 I did find a little difference between Q=0 and Q=3 and that was very similar to my previous tests (https://github.com/elieserdejesus/JamTaba/issues/456#issuecomment-226920734) in the sense that I found only some little more stereo image in Q=0.3, so here are the files:

[ogg test 2.rar.txt](https://github.com/elieserdejesus/JamTaba/files/322112/ogg.test.2.rar.txt)

This was a drum loop with very good quality and a lot of stereo high frequencies. For each one the first half (two measures) are Q=0 and the final half is Q=0.3.

So my point here is that the default quality is too high IMO. I Q=0.1 or Q=0 could be more appropiate in this case. Not much difference in sound, but an important difference in bandwidth usage:

~64 – ~80  for Q=0
~80 – ~96  for Q=0.1
~96 – ~112 for Q=0.2

**Comment by elieserdejesus** [comment]
@jonjamcam , I gree with new values. If I understand correctly we will have:
```
LOW        = -0.1
NORMAL =  0.0
HIGH        = 0.1
```
Can you change the values and create a PR? Just change the values in **VorbisEncoder.cpp**, the first lines in the file.

**Comment by jonjamcam** [comment]
I think the HIGH value was a good choice at 0.3 (just to have different options), although I think most users will use the default:

LOW = -0.1
NORMAL =  0.0
HIGH = 0.3

Do you agree with these values @elieserdejesus ?

**Comment by elieserdejesus** [comment]
no problem @jonjamcam , I agree with these values.
