### ISSUE TITLE
Save Sessions using the OMF standard

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#458]
I think this could be a solution (if implementation is possible) for most non-reaper users of Jamtaba. Many times I've seen this format as a holy grail for cross plattform compatibility, but in forums the comments are not that favorable.

https://en.wikipedia.org/wiki/Open_Media_Framework_Interchange

**Comment by jonjamcam** [comment]
I understand Jamtaba is currently being used in FL Studio, Ableton Live, Cubase, Sonar and Logic to name a few. The only solution suggested in forums to convert .rpp to these other formats is a comercial product called **aatranslator** (www.aatranslator.com.au), but it's not free nor open source.

OMF format is the only one I could find on the Internet that support Cubase, Logic, Sonar among many others like Protools and Adobe Premiere.

I'm thinking that in next releases Jamtaba will contain Video too, so if the Video channel is going to be saved too (?) this could be a cross platform solution for the long term.

The specification I is here:

http://www.linuxmedialabs.com/Downloads/LSI/omfspec21.pdf

"The Open Media Framework (OMF) Interchange format is a standard format
for the interchange of digital media data among heterogeneous platforms. The
format encapsulates all the information required to transport a variety of
digital media such as audio, video, graphics, and still images, as well as the
rules for combining and presenting the media. The format includes rules for
identifying the original sources of the digital media data, and it can encapsulate
both compressed and uncompressed digital media data"

@pljones @elieserdejesus What do you think about this format? Any references?

**Comment by elieserdejesus** [comment]
I used the OMF long time ago. A session recorded in Logic was exported as an OMF. I opened the OMF in Sonar (an old version) and works like a charm.

I see Reaper can't open OMF without 3rd part extensions. Maybe it's a bad signal?

**Comment by jonjamcam** [comment]
> I see Reaper can't open OMF without 3rd part extensions. Maybe it's a bad signal?

Yeah. If Reaper is not jumping in then it looks fishy to me too.

**Comment by pljones** [comment]
Hi,

> © Copyright 1995, 1997 Avid Technology, Inc.

The referenced site, http://www.omfi.org/, looks like it's... um, dead and gone
and become adware (as of 2015).

Given it's had 20 years to become adopted and no one's heard of it yet, I'd be
wary of investing time and effort in it.

Cheers,

-- Peter

**Comment by jonjamcam** [comment]
> looks like it's... um, dead and gone

Let's look for better solutions....closing..
