### ISSUE TITLE
Make chordboxes of chorddisplay editable on doubleclick [ENHANCEMENT]

### ISSUE THREAD

**Issue by vector21** [elieserdejesus/JamTaba#469]
Hey guys... It's me... Echnaton9000 :-)

I have an idea for an enhancement:

Why not make the Chords editable? So that when you  doubleclick a "Chordbox" it opens up a simple dialog window, that allows to change the chord to something else. 

This could be a dialog like this:

![edit chord dialog](https://cloud.githubusercontent.com/assets/5586556/16305597/dd82d0c6-395a-11e6-9ad0-7b4bca2e9b4f.png)

You can enter a new chord for this "chordbox" wether by entering a string like "Am" into the field, or use a dropdown selectbox to choose from a list of widely used chords (maybe use more than one selectbox for "major/minor" plus the tonic? :-)

Hope that makes sense!

Great work by the way guys!!!
JT gets more and more a really good tool on its own!

**Comment by vector21** [comment]
If strings would be editable directly in the boxes... that would be even nicer! (but I think thats more complicated to implement...)

**Comment by elieserdejesus** [comment]
It's done in #479.
