### ISSUE TITLE
Startup Problem with App after use JamKazam - Reported by Stringer

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#47]
Observations on Startup Problem with App

Hi Elieser,

The VST seems to be working fine and I may have come closer to identifying the problem with the Jamtaba 2 app starting up that was described in detail several weeks ago on the 'Coming Soon' post.

http://ninbot.com/topic/jamtaba-2-comming

1) App loads and works
2) Other ASIO dependent apps used
3) Jamtaba app won't open

I've been doing realtime jamming on Jamkazam lately and noticed that it tended to lock out both Reaper and the Windows Media Player from ASIO use afterwards. Both of the other apps would start, but didn't seem to connect with my ASIO until a second or third restart of the apps was done.

Jamkazam seems to have lessened this problem in a recent release and it no longer seems to exist for Reaper and the Media Player, but it got me thinking that this may be the cause of the Jamtaba app not opening in some cases.

This time when the Jamtaba app didn't open I then opened the Jamtaba VST in Reaper which worked fine. This seemed to then make it possible to open the app which also now works fine (though maybe only until I use Jamkazam again.)

I'm thinking that the Jamtaba app may not boot up without a working ASIO connection, whereas both Reaper and Media Player will (they just won't play any sound.) Maybe if you allow the Jamtaba app to open without an ASIO connection and give a connection warning instead this will give it a chance to reconnect with the ASIO rather than just not opening.

One other thought, maybe the Jamtaba app is having trouble changing the local ASIO sample rate if they don't match. I've made some sample rate changes recently and this may be why Reaper and the Media Player stopped having these problems (rather than having anything to do with the recent Jamkazam update.)

I forgot to copy the error details for you when the Jamtaba app didn't open this time (sorry lol)... however, I'm guessing this is the same issue that was previously described. If you make some changes I'll be glad to try and recreate the problem using the current release before loading any fix.

**Comment by Ezeer** [comment]
" I'm thinking that the Jamtaba app may not boot up without a working ASIO connection, whereas both Reaper and Media Player will (they just won't play any sound.) Maybe if you allow the Jamtaba app to open without an ASIO connection and give a connection warning instead this will give it a chance to reconnect with the ASIO rather than just not opening. "

that will be fixed soon , i have that task to do about Asio driver missing : https://github.com/elieserdejesus/JamTaba/issues/20

**Comment by elieserdejesus** [comment]
Ezee, maybe a interesting solution in this case is detect the ASIO missing
and start Jamtaba using the Audio::NullAudioDriver.  Jamtaba will open, but
off course no sound. So is important show a warning message to users about
the "no sound" issue.


Em sábado, 24 de outubro de 2015, Ezee <notifications@github.com> escreveu:

**Comment by Ezeer** [comment]
Ok .
As you are aware of that , you take that bug ?

**Comment by elieserdejesus** [comment]
Ok Ezee, I will work on this issue.

**Comment by Ezeer** [comment]
Can you ask Stringer to make a test with the 2.0.5 RC , to see if there is a crash ?
And don't forget to ask him for the precious log ( so perhaps set all params to true in the .ini )

**Comment by elieserdejesus** [comment]
Email sended!

**Comment by Ezeer** [comment]
great , thx !

**Comment by elieserdejesus** [comment]
Stringer will test 2.0.5 tomorrow, and he say the problem is not present in 2.0.4. 
So, we are closest to close this issue, let's just wait for the 2.0.5 test.

**Comment by Ezeer** [comment]
cool , that was my intention , no problemo .

**Comment by elieserdejesus** [comment]
Closing, no more activity in this issue.
