### ISSUE TITLE
Add translation contributors to "translators" in Jamtaba.com

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#470]
For the 2.0.15 release new translation contributions were done by:

Japanese: Nakajima Yusuke and Leo Takeshita
German: Echnaton9000

**Comment by elieserdejesus** [comment]
Done, v2.0.15 is released! Thanks @jonjamcam !

**Comment by jonjamcam** [comment]
YEEESSSSS!
