### ISSUE TITLE
If Jamtaba.json file doesn't exist, launching Jamtaba 32bit creates wrong value for quality

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#471]
To reproduce the bug:

1.- Install Jamtaba64bit only (clean installation).
2.- Launch Jamtaba 64bit standalone.
3.-  Close Jamtaba. Now Jamtaba64.json file is created with correct value for quality (0).
4.- Launch Qtcreator and complie Jamtaba with mingw32.
5.- Close Jamtaba. Jamtaba.json file is created with wrong value for quality.

![image](https://cloud.githubusercontent.com/assets/15310433/16309587/9d9c90ac-393f-11e6-9670-a78025b7c0e7.png)

NOTE: Tested the 32bit installation (clean install) of the 2.0.15 pre release and the jamtaba.json file created has wrong value too.

![image](https://cloud.githubusercontent.com/assets/15310433/16310310/76fa583c-3942-11e6-9848-d86ab2634e53.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I uploaded a new installer in the pre-release fixing this bug.

**Comment by jonjamcam** [comment]
Tested. It's OK now.
