### ISSUE TITLE
User's guide update for 2.0.15

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#473]
These are the missing explanations to include in the manual:

- [x] Update chat page.
- [x] Show dim track when user not transmitting
- [x] update control section pictures (invert stereo, etc.)
- [x] license button and native language for link inside
- [x] Improving bpi/bpm input fields to show some visual feedback when voting
- [x] Adding a button in local tracks to invert stereo image
- [x] New 'Black' theme
- [x] Generating Reaper "clipsort.log" or Reaper project (rpp)
- [x] Improving meters to show peaks only, RMS only or peaks + RMS.
- [x] Now is possible mute/block users/trolls in chat.
- [x] [Standalone] Choosable ninjam audio encoding quality in audio preferences.
- [x] Showing last used chords (if available) for each ninjam server.
- [x] [Standalone] Transmiting midi information from one VST to another (midi chain, usefull for arpeggiators, for example).
- [x] Showing users using 'voice chat' mode in reaper.
- [x] Always showing current BPI/BPM inside the ninjam window.

Changes here: https://github.com/jonjamcam/JamTaba/wiki/Jamtaba%27s-user-guide

**Comment by jonjamcam** [comment]
@elieserdejesus Manual for 2.0.15 update Complete!

**Comment by elieserdejesus** [comment]
Wiki updated, thanks @jonjamcam .
