### ISSUE TITLE
Text in "Transmitting" button in local channels when not transmitting

### ISSUE THREAD

**Issue by gevialex** [elieserdejesus/JamTaba#476]
Hi, could the "Transmitting" button in the local channels show something like "Not Transmitting" when it's set to not transmit?
 It's cool that it has a red background color when not transmitting (and green when it is transmitting) but I think it might be confusing for new users if the button always says "Transmitting" no mather the color or setting. Just showing "Transmit" instead of "transmitting" might already be better, just a thing of   sintax :P but I think it helps
Thanks

**Comment by elieserdejesus** [comment]
Igree @gevialex , we can change the xmit button text in the next release.
