### ISSUE TITLE
BUG Standalone fails to start Win10-x64

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#49]
Hi,

Using the installer downloaded yesterday (with the Jamtaba2.exe inside "created" ‎23 ‎October ‎2015, ‏‎19:48:52 accoring to Windows, 16,053,248 bytes - no version information), I installed the 64bit standalone and VST versions.

I've been able to connect using the VST.

However, running the standalone fails -- no error.  Starting from a cmd window gets the prompt straight back with no error, either.

I have no other audio applications running.

This is the first audio application to be started since booting.

I _may_ have configured the standalone ASIO settings in a previous install but that was fully removed before this install.

Any ideas on how to get it to start?

Thanks,

-- Peter

**Comment by Ezeer** [comment]
Hello peter .
Unfortunetly i am using win32 XP only , so i can't directly help .
But you could find useful info in the log created by the application .
On my XP system , it's located in :
C:\Documents and Settings\Salon\Local Settings\Application Data\Jamtaba 2
Be aware that Local Settings and Application Data may be hidden by default on windows ,
so you would use the windows folder options to make them visible .

Some configuration problems may be resolved also looking at the  Jamtaba.json file , in the
same folder .

**Comment by pljones** [comment]
Hi,

I can't attached a document ("Attaching documents requires write permission to this repository.").  The file reads:
```

WARNING:  Can't load Jamtaba config file: "No such file or directory" 0



```
That should not cause the application to fail to start: it needs to start to get configured! :)

-- Peter

**Comment by Ezeer** [comment]
"That should not cause the application to fail to start: it needs to start to get configured! :) "
Exactly !
That file is created dynamically .
But that will help for know where the program ended .
Thank you !
;)

**Comment by elieserdejesus** [comment]
pljones, I'm suspecting from some ASIO driver problem. You have an ASIO driver installed in your machine?

**Comment by pljones** [comment]
Yes, it's the Echo Audio ASIO driver for my card.  I use it with:
- Reaper x64
- MuLab x64
- NI Kontakt x64
- Plogue Sforzando x64

It works reliably with all other this software.

**Comment by Ezeer** [comment]
I think we should add more desc in the log elieser , retrieve the max informations we can find on the
user machine/OS .
This way support will be easier .
Ah and .... thank you pljones ;)

**Comment by Ezeer** [comment]
looking for Qt ways to retrieve sys info :
 http://doc.qt.io/qt-5/qsysinfo.html

i'll edit if i'll find more .

**Comment by elieserdejesus** [comment]
Ezee, I add mode log lines describing Jamtaba initialization, try the last code version in your machine too see new log infos.

**Comment by elieserdejesus** [comment]
Ezee, I add more log lines describing Jamtaba initialization, try the last code version in your machine too see new log infos.

**Comment by elieserdejesus** [comment]
Ezee, I add more log lines describing Jamtaba initialization, try the last code version in your machine too see new log infos.

**Comment by Ezeer** [comment]
i got it !
The log now is much better : 

*INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
INFO:  Creating roomStreamer ...
INFO:  Starting portaudio driver using ASIO4ALL v2
INFO:  portaudio driver started ok!
INFO:  Connecting in Jamtaba server...
INFO:  "Starting Jamtaba 2.0.3 Standalone (i386) running on Windows XP (i386)"
INFO:  Creating MainWindow...
INFO:  Initializing local inputs...
INFO:  	Creating channel  "your channel"
INFO:  		Creating sub-channel 
INFO:  		setting Subchannel to no noinput
INFO:  Initializing local inputs done!
INFO:  MainWindow created!
INFO:  Restoring plugins list...
INFO:  Restoring plugins list done!
INFO:  Starting portaudio driver using ASIO4ALL v2
INFO:  portaudio driver started ok!*

good job again ( and reactivity ! )
:+1:

**Comment by Ezeer** [comment]
Can you make a release of this version now ?
I mean , the users's reports will be a good help now !
;)

**Comment by elieserdejesus** [comment]
Released!  I'm using the GitHub Releases now, mutch better my dropbox
account :)

Elieser

Em segunda-feira, 26 de outubro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by pljones** [comment]
Hi,

I just tried updating to 2.0.4 and running.  No difference.  So I uninstalled, cleared up the registry of all traces, cleaned disk of all traces and reinstalled 2.0.4.  Again, still failed to start.

However, the log has some additional lines now:

```
WARNING:  Can't load Jamtaba config file: "The system cannot find the path specified." 0

INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
```
At this point I do not know which of three possible ASIO drivers it's going to pick between (my soundcard, JackASIO and ReaRoute).  It could be failing because JackASIO has been chosen -- and that will break if Jack isn't running.

-- Peter

**Comment by Ezeer** [comment]
Peter , you are a good helper .

( that could be the beginning of a nice reggae song ! ah ah ah .... )
Thank you for your reactivity and your interest for jamtaba .

I think elieser will be able to fix the problem now , i go check the code if i can find something in
the direction you pointed ( choose one working Asio -the best ?- when there is more than one in a system ) .

Perhaps a dirty fix could be to rewrite the .json file with an entry for the Asio driver name ?
This way , a user could manually edit the file and give the proper driver name .

Elieser , as pljones is one of our best testers , you could use your dropbox to make beta release
for him ?

**Comment by elieserdejesus** [comment]
Thanks pljones!  If you start Jack the problem is solved?
If not, can you uninstall JackASIO and install ASIO4ALL, just to eliminate the hipothesys of a JackASIO issue? Sorry for propose a very intrusive test...

**Comment by pljones** [comment]
Hi,

I tried with Jack running and got the same as last time.

I could try the x86 build and see if that's any different if you think it would help?

-- Peter

**Comment by elieserdejesus** [comment]
pljone, please try the x86 installer to see. Waiting for your feedback...

**Comment by pljones** [comment]
Hi,

That got me a bit more info in the log:
```

WARNING:  Can't load Jamtaba config file: "No such file or directory" 0

INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
INFO:  Creating roomStreamer ...
INFO:  Starting portaudio driver using ASIO Echo FireWire

CRITICAL:  unsuported format:  Illegal combination of I/O devices sampleRate:  44100 0

```
It's picked the correct ASIO device.  Now - this time I had been using Reaper shortly beforehand, rather than being from a fresh boot.  However, the ASIO driver is currently reporting a sample rate of 48000, which is what Reaper requested.

Does JamTaba request a sample rate when it opens the ASIO device?

-- Peter

**Comment by elieserdejesus** [comment]
pljones, I'm suspecting portaudio is trying use differentes devices for input and output. I will add more log in this point and generate a new installer.  This last test was done with 32 or 64 bits installer?

Thanks for your help, vey usefull infos!

**Comment by pljones** [comment]
> This last test was done with 32 or 64 bits installer?
With the 32bit one for 2.0.5

**Comment by Ezeer** [comment]
2.0.5 ? Man , are you a VIP ?
Or you travel in time ?
lol

**Comment by pljones** [comment]
Well, I was basing that on downloading after the 2.0.5 milestone was marked -- but maybe it wasn't up for download.

**Comment by Ezeer** [comment]
yo , i was joking !
^^
And you could have a special treatment because you are a good fellow !
![goodfellas](https://cloud.githubusercontent.com/assets/1283808/10773781/b94ca53e-7cfd-11e5-8797-993f6f96dba5.jpg)

**Comment by elieserdejesus** [comment]
@pljones , please can you test this version? [https://github.com/elieserdejesus/JamTaba/releases/tag/2.0.4-test](https://github.com/elieserdejesus/JamTaba/releases/tag/2.0.4-test)

I just add more log to see the erro details...

**Comment by pljones** [comment]
OK, here's an interesting thing.

I had tried out the VST plugin yesterday and that worked.

Of course, that created the config file (even though it didn't specify any hardware IO).

The first time I ran the version #issuecomment-151682775 it worked -- although there was a long delay and I was prompted to download a newer version.  (It appeared to think it was 2.0.3, I think.)

So...  I uninstalled, cleared out the config files and any registry entries and then reinstalled.

This time, it failed:
```
WARNING:  Can't load Jamtaba config file: "The system cannot find the path specified." 0

INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
INFO:  Creating roomStreamer ...
INFO:  Starting portaudio driver using ASIO Echo FireWire  as input device.
INFO:  Starting portaudio driver using ReaRoute ASIO  as output device.
INFO:  Starting portaudio driver using 1024  as buffer size.
INFO:  Trying initialize portaudio using inputParams and samplerate= 44100

CRITICAL:  unsuported format:  Illegal combination of I/O devices sampleRate:  44100 0
```
So yes, it does appear to have grabbed two ASIO drivers (bad idea... :) )

Can I suggest two things:
- Add microsecond timestamps to the logging so you can see how long things take.
- If things are taking a long time on start up (e.g. looking up a host name and checking a version number), pop up a splash screen.

**Comment by elieserdejesus** [comment]
@pljones , thanks for this clear log. This behavior is not normal in Windows, in Mac we can mix the devices, but in Windows I never see this working :)

So this is a nice bug :)  

We have some conditional compilation in the portaudio code. I'm suspecting some compiler flag like #ifdef _WIN32  is failing in Windows 10. 

I will make a new testable version soon, thanks again pljones!

**Comment by elieserdejesus** [comment]
@pljones, can you test again? Now I change the code to use same audio device for input and output. I hope this solve the problem. [https://github.com/elieserdejesus/JamTaba/releases/tag/2.0.4-test](This is the link, I just update the installer executable)

**Comment by pljones** [comment]
Hi,

Good news: it started up!
```
WARNING:  Can't load Jamtaba config file: "The system cannot find the path specified." 0

INFO:  Creating plugin finder...
INFO:  Creating midi driver...
INFO:  Initializing rtmidi...
INFO:  rtmidi initialized!
INFO:  Creating audio driver...
INFO:  initializing portaudio...
INFO:  Creating roomStreamer ...
INFO:  Starting portaudio driver using ASIO Echo FireWire  as device.
INFO:  Starting portaudio driver using 192  as buffer size.
INFO:  Trying initialize portaudio using inputParams and samplerate= 44100
INFO:  portaudio driver started ok!
INFO:  Starting MIDI in  "AudioFire4 MIDI 0"
INFO:  Connecting in Jamtaba server...
INFO:  "Starting Jamtaba 2.0.4 Standalone (i386) running on Windows  (x86_64)"
INFO:  Creating MainWindow...
INFO:  Initializing local inputs...
INFO:  Initializing local inputs done!
INFO:  MainWindow created!
INFO:  Restoring plugins list...
INFO:  Restoring plugins list done!
```
I can see the servers, I can listen to the servers.  So audio from the servers is working.

I can configure my MIDI in.  I can configure my VST path.  I can happily load up Kontakt 5 and load a set of samples in.  Kontakt sees the incoming MIDI events and triggers layers of samples.  Same when I play its virtual keyboard.

But there is no audio out -- it looks like Kontakt thinks the audio outs from the VST go nowhere.

Now Kontakt is a multi-out VST - in this case, it has 8 outs, with only the first stereo pair being used.

If I use JM-1, a simpler VST with only a single stereo out, then I hear sound when I trigger it.

So, it looks like there's a problem with multi-out VSTis.

If it's just picking the wrong outputs to connect, you could "do what Reaper would do" and ask the user if they want them connected to multiple sub-channels or not give the option and simply connect them all to the same channel.

You could also add some logging of what happens on adding / removing channels/sub-channels, VSTs etc.  There's also nothing in the log about my MIDI port(s).

Do you want a separate bug for the VST issue?

Thanks,

-- Peter

**Comment by elieserdejesus** [comment]
Nice news, thanks @pljones !
I will check this problem with Kontakt 5 and other multi-out VST plugins.
I'm adding a new bug for this.
