### ISSUE TITLE
Light GUI

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#50]
Hi guys.

I was testing the jamtaba vst on my old audio winXP machine (p4) that has a delta1010 soundcard and reaper and I found something interesting worth sharing with you.

I was running reaper with 1 stereo track and jamtaba vst only. the connection was via LAN.

Once joining a room it consumed about all my cpu (70%) making it impractical to run, but if I turn off the GUI of the plugin (meaning close the plugin window) and let it work on the background it uses no more than 30%. 

So my question is can we have a "light GUI" theme or customizable GUI for the plugin?

This could work for old machines that have those nice PCI sound cards that sound so great!

**Comment by Ezeer** [comment]
Hi !
Thank you for that report that is very interesting .

" So my question is can we have a "light GUI" theme or customizable GUI for the plugin? "

Well , i can't speak for elieser who is the author of the plugin , but he already made efforts on the
GUI customization for the standalone .
If we can offer best performances by reducing the GUI impact on cpu , that will be on our todo list !
But wait for elieser answer ...

" This could work for old machines that have those nice PCI sound cards that sound so great! "
Nice idea indeed !

:)

**Comment by jonjamcam** [comment]
Hi Ezee.

my old p4 win xp machine is using the onboard graphics chip. It came to my mind after I posted that this could be a hardware's issue (meaning the graphic card uses cpu resources). I have time today to test an old nvidia AGP I have and see what happens. 

I'll report ASAP.

**Comment by Ezeer** [comment]
good .
Thank you !
;)

**Comment by jonjamcam** [comment]
Ok so I tested using my old AGP Nvidia card and the results were not much different with regards to performance. LAN connection used. Pentium 4 2.26 GHZ, windows xp sp3. Reaper 4.76. Jamtaba2.0.3 VST. Delta1010LT PCI soundcard (ASIO driver version 5.10.00.5057) using 48000 HZ rate and 64 block size. It reads  2.0 - 1.9 ms latency (according to reaper). 

So, summarizing:


using plugin GUI with onboard chip VGA: reaper performance varies from 70% to 90% usage (impractical)

closing plugin GUI and unsing onboard chip VGA: performance drops to 30-40% max.



Now, replacing the onboard VGA card and using AGP VGA card:

using plugin GUI with AGP external card reaper preformance stabilizes around 66%

closing plugin GUI with AGP external card reaper performance stays between 25-30%


these tests were performed using a private server with 3 users in total connected

**Comment by Ezeer** [comment]
Thank you , these are precious datas .
Please , how much memory in your graphics card ?
AGPx2 ,x4 ,x8 ?
That could help to create a minimum requirements list by systems .
But i'm not sure we are using agp functions , probably gdi calls .
How many ram in your system ? XP is limited to 3 .

**Comment by elieserdejesus** [comment]
Hi Jon, thanks for your details! Ezee I totally agree to work in a "light GUI". 
Jon, can you measure ReaNinjam performance for us? How much CPU ReaNinjam is eating?

Another test: please turn off xmit in Jamtaba and test with the GUI opened. In my test I see the ogg vorbis encoder (xmiting in reaninjam) is a CPU killer. Waiting for your results, thanks again!

**Comment by jonjamcam** [comment]
well, i'm testin reaninjam right now and I can tell the performance varies a bit depending on the size of the plugin.

So. using reaninjam almost full screen (can't see the performance bar in reaper if I expand to full) and with XMIT ON performance is between 15%-30% cpu usage with some peakes at 40%.

same as above, but turning OFF XMIT, peroformance drops to about 7%-10% with peaks at 15%.

Now if I resize the reaninjam window to it's minimum performance goes between 15% to 25% when XMIT is ON

If I turn OFF Xmit performance stabilizes between 10%-12%.

All this was tested using the AGP card. If you need I can take ot off and retest.

@EZEE I'll take off the card later and post the specifications. As far as I remember it has 256 MB ram and It's probably 4x or 8x. but I'll be sure tomorow

**Comment by jonjamcam** [comment]
I recently tested with 2.0.17 beta in my XP system and I noticed no difference in performance when closing the plugin, so I believe a light GUI is not longer necessary. closing....
