### ISSUE TITLE
Entering a chord like "CM7" not displaying any chords

### ISSUE THREAD

**Issue by vector21** [elieserdejesus/JamTaba#503]
Try to enter: !CM7 !Dm7   -->  no chords will be displayed at all.

The chord display seems not to recognize strings with uppercase "M" as chords. If you enter "!Cm7 !Dm7 everything works as expected.

**Comment by jonjamcam** [comment]
> The chord display seems not to recognize strings with uppercase "M" as chords

@vector21 

I'm no expert in notation, but as far as I know **C Mayor 7** should be typed as **C7**, shouldn't it?

**Comment by elieserdejesus** [comment]
I tested the chords **!CM7 !Dm7** in Jamtaba 2.0.15 and is not working. I just test in the current code (2.0.16) and is working ok. I can't remember when the chord parser was changed, but is working :)

![image](https://cloud.githubusercontent.com/assets/1012741/17084907/6f8b72f4-51a0-11e6-861a-a6601685dd32.png)
