### ISSUE TITLE
Copy menu for ninjamer channel name

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#506]
I see some ninjamers post their web sites using the channel name placeholder among other uses. Is it possible to be able to copy this text to the clipboard?

![image](https://cloud.githubusercontent.com/assets/15310433/16967860/4d360d2e-4dd9-11e6-8cec-bc5b07d37ae9.png)

**Comment by elieserdejesus** [comment]
Is possible @jonjamcam , and I think is possible recognize and use the text as a clickable link.

Maybe some people will abuse with clickable links?

**Comment by jonjamcam** [comment]
> Maybe some people will abuse with clickable links?

Sure they can, but what abuse are you thinking about? linking to nasty sites?

**Comment by elieserdejesus** [comment]
Yes @jonjamcam , nasty sites, malwares and all kind of "online traps" :)
But I think in general this is not a big problem, people are not forced to click in these links.

But, I think (too) use the channel name to publicity (personal sites, etc) is a bit abusive.

**Comment by jonjamcam** [comment]
>  nasty sites, malwares and all kind of "online traps"

I understand you concern. It's not good if someone clicks (willingly or not) and get a virus. I think a copy menu or something is enough.

**Comment by elieserdejesus** [comment]
> I think a copy menu or something is enough.

I agree.
