### ISSUE TITLE
Change the track input mode to MIDI when user insert a VSTi

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#51]
When a first plugin is inserted in standalone change the track input to MIDI using the first available midi device. This is usefull to VSTi users, because these users don't need change the input to MIDI manually. If the first inserted plugin is a VSTi so we can guess user need MIDI as input.

**Comment by Ezeer** [comment]
Nice idea .
Perhaps you can also add in the TabMidi a ComboBox where the user can select his default midi device ? (instead of the first one ...)
In case of using MidiYoke for example ,
http://www.midiox.com/index.htm?http://www.midiox.com/myoke.htm
in addition to his midi hardware ?

**Comment by jonjamcam** [comment]
working in alpha 2.0.6
