### ISSUE TITLE
2.0.16 Manual Update

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#519]
- [x] New feature explanations for 2.0.16
- [x] Horizontal/vertical layout snapshots missing
- [x] Low Cut frequency button explained
- [x] Replace Snapshots with new World Map interface

**Comment by jonjamcam** [comment]
@elieserdejesus The 2.0.16 manual is complete.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , wiki updated.

**Comment by elieserdejesus** [comment]
@jonjamcam , v2.0.16 is released, thanks again for your collaboration!

**Comment by jonjamcam** [comment]
@elieserdejesus I'm happy to help!
