### ISSUE TITLE
Add a ComboBox in Preferences Panel to select the default midi device 

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#52]
add in the TabMidi a ComboBox where the user can select his default midi device

**Comment by Ezeer** [comment]
ah ah ah ! You are so reactive , that's magic !
I am finalizing my learning curve with QtEditor and the c++ code .
When i will have successfully done the visualization of vsts in a list , i could take this task .

**Comment by elieserdejesus** [comment]
Nice Ezee, I like your energy too. For me all conversations are
possibilities, and all possibilities can be added as issues :)

Good ideas are always welcome.



Em segunda-feira, 26 de outubro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
