### ISSUE TITLE
Admins (no ip users) do not appear in map

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#521]
In this case **mutant** is logged as admin in mutantlab.com:

![image](https://cloud.githubusercontent.com/assets/15310433/17991513/c6f127f8-6b15-11e6-9cae-d3f113809956.png)

map appears empty, but mutant is actually there:

![image](https://cloud.githubusercontent.com/assets/15310433/17991624/a4d151f6-6b16-11e6-853f-bda2fba3bc96.png)

and

![image](https://cloud.githubusercontent.com/assets/15310433/17991565/23a9cc3e-6b16-11e6-9c69-a2add12ad6d3.png)

**Comment by elieserdejesus** [comment]
Related with #311. I have an idea to solve this directly in Jamtaba server. When the admin has no IP is possible use the server IP.

**Comment by jonjamcam** [comment]
Yeah, that sounds like a good solution!

**Comment by elieserdejesus** [comment]
It's fixed in JamTaba server https://github.com/elieserdejesus/JamTaba-Server/commit/ed678aa93c90dcc1e844f97c988048db6c172195 

Using server IP when users have no IP (admin, bots). Tested changing Jamtaba to show bots:
![image](https://cloud.githubusercontent.com/assets/1012741/22152705/47630f46-df0b-11e6-9d36-fa127ecbc886.png)

**Comment by jonjamcam** [comment]
@elieserdejesus does this fix work with 2.0.18?

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm 99% shure :)  The changes are in server only, so in theory 2.0.18 will receive bot and admins IPs correctly (using server IP).

**Comment by jonjamcam** [comment]
@elieserdejesus I report that at least for Andymc's server it's not working:

![image](https://cloud.githubusercontent.com/assets/15310433/22390191/65cfff94-e4c8-11e6-8cc0-df629e75ebfd.png)

![image](https://cloud.githubusercontent.com/assets/15310433/22390198/72e28602-e4c8-11e6-92c1-0fd0d0273215.png)

**Comment by elieserdejesus** [comment]
This is the admin panel in JamTaba server:

![image](https://cloud.githubusercontent.com/assets/1012741/22395902/9b097856-e532-11e6-8712-039de8f22788.png)


I change the server code, tested in my local server, and forgot to update the "online" server :)
