### ISSUE TITLE
Chat Window not on top for Vst Jamtaba . cannot type in chat dialog box 

### ISSUE THREAD

**Issue by Trashcanhead1111** [elieserdejesus/JamTaba#523]
I installed new update and was unable to chat in jamtaba using sonor x3 x64 .
when trying to type in chat it is not on top window and runs shortcuts in sonor instead of typing in chat dialog box.

**Comment by elieserdejesus** [comment]
Hi @Trashcanhead1111 , I will check this problem soon. We changed the key pressing detection to support Japanese input methods and I think these changes introduced some bug in Sonar.

**Comment by elieserdejesus** [comment]
@Trashcanhead1111 , I fixed the problem in Sonar X3. Can you test the attached file in your machine just to confirm if is working ok?

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/440883/JamtabaVST2.zip)

**Comment by Trashcanhead1111** [comment]
Yes works great. cant thank you enough or say it enough how awesome Jamtaba is. thanks Dave

**Comment by Trashcanhead1111** [comment]
One more thing with the chat window. for some odd reason the ? mark does not work. can you test this please thanks Dave
