### ISSUE TITLE
Freeze at startup in MiniMode (VST and Standalone)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#524]
when launching a .rpp file that contains Jamtaba VST 2.0.16 x64 Reaper gets stuck when Jamtaba displays "loading rooms list". This doesn't happen with 2.0.15. Tested in reaper 4 and reaper 5 x64.

![image](https://cloud.githubusercontent.com/assets/15310433/18037399/30352c56-6d59-11e6-88bd-dbc9959b0313.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I see this annoying bug too, and without a .rpp file. Sometimes I load Jamtaba in Reaper and gets stucked in "loading rooms". Same behavior in Sonar. 
I'm investigating the annoying problem. This is a bug in VST plugin only.

**Comment by jonjamcam** [comment]
@elieserdejesus Do you think the VST plugin should be released as a "2.0.16 fix only" this time? is this possible, I mean just recompile the windows version?

**Comment by elieserdejesus** [comment]
Exactly @jonjamcam , I will release a new version after fix this bug.

**Comment by jonjamcam** [comment]
@elieserdejesus I have this bug when starting Jamtaba in mini mode only (standalone too)

**Comment by pljones** [comment]
Same bug here loading in MuLab.  Spinner stops at the same point every time.

**Comment by jonjamcam** [comment]
@pljones Does this happen to you when using the full view mode?

**Comment by jonjamcam** [comment]
In order to avoid loosing presets as @pljones noticed above, just change the **FullView** entry in your .json file from **false** to **true**:

![image](https://cloud.githubusercontent.com/assets/15310433/18215297/ebf862b6-7126-11e6-9fce-9477cf233e4e.png)

**Comment by jonjamcam** [comment]
More tests I've made. This bug not always happen.

1.- When it does happen, both VST and Standalone freeze.
2.- When it doesn't happen, both VST and Standalone work OK in Mini mode.

As this is a 2.0.16 bug and the ASIO4ALL fix was reversed I guess that some map configurations may be causing the mini mode to have problems.

**Comment by jonjamcam** [comment]
@elieserdejesus Got the problem with this rooms configuration:

![image](https://cloud.githubusercontent.com/assets/15310433/18217196/c56947ea-7131-11e6-99f6-234c4866b006.png)

**Comment by elieserdejesus** [comment]
Thanks for the infos @jonjamcam, I will investigate this bug in this wekeend.
