### ISSUE TITLE
Lot of crash with the new version of Jamtaba 2.0.16

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#525]
Since the new version  lot of freeze of jamtaba VST, making crash reaper .  Only me ?
Win10Pro/64 bits
Not the same as Jon when loading room but after using jamtaba a while and making a change (writing in chat or changing tempo;...)
Like to come back to 2.0.15 where finding the old files ? 

Thanks

**Comment by elieserdejesus** [comment]
@DoublebassOO , the old releases are [here](https://github.com/elieserdejesus/JamTaba/releases/)

**Comment by jonjamcam** [comment]
Maybe the new "Decoding mp3 in separated thread" is causing the instability of the VST plugin. I Had a similar issue some time ago with Kontakt, where they suggest that if the host is controlling the cores, then the plugin should not. Kontakt has a Check box for this:

-![](https://cloud.githubusercontent.com/assets/15310433/15019719/85afa55e-11f5-11e6-96ca-82aa41e6f431.png)

**Comment by DoublebassOO** [comment]
Hey  great fellows !
Thanks for your help   Cy

**Comment by DoublebassOO** [comment]
Hello  Elieser and Jon
Thanks a lot, i will check and try that.   For the translation is there a
new file to work on  ?

2016-08-30 3:40 GMT+02:00 jonjamcam <notifications@github.com>:

**Comment by jonjamcam** [comment]
Hey @DoublebassOO . There were just three strings to translate this time. We used for 2.0.16:

"low cut": **coupe bas**

"transmit": **Transmission**

"Connecting with private Ninjam server ...": **Se connecter à un serveur prive Ninjam...**

are these the correct french translations in your opinion? We can make corrections for 2.0.17 if needed.

**Comment by elieserdejesus** [comment]
@jonjamcam , @DoublebassOO , @pljones , @Trashcanhead1111

Can you test the [pre release for v2.0.17](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.17-pre) in your DAWs? I hope the bug freezing Jamtaba in initialization is fixed in this version.

**Comment by pljones** [comment]
Hi @elieserdejesus,

Start up is now fine :)

-- Peter

**Comment by jonjamcam** [comment]
@elieserdejesus Working OK here too.

**Comment by DoublebassOO** [comment]
always depending the context of the word but  seems ok


just the accent on e         *Se connecter à un serveur privé Ninjam...*

2016-08-31 9:51 GMT+02:00 jonjamcam <notifications@github.com>:

**Comment by jonjamcam** [comment]
2.0.17 Working OK on XP too (standalone and VST).

**Comment by elieserdejesus** [comment]
nice news @jonjamcam , I'm fixing the little issues in the ninjam channel name copy action before release v2.0.17.
