### ISSUE TITLE
Volcano theme details pending

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#534]
Some details to discuss for the Volcano theme:

- [x] Gray buttons:
![](https://cloud.githubusercontent.com/assets/15310433/18226990/139900e8-71ed-11e6-9df9-3baa6b0122ed.png)

- [x] interval progress color:
![](https://cloud.githubusercontent.com/assets/15310433/18211676/548c3cd8-7115-11e6-87ff-1fa4f67d086c.png)
done in https://github.com/elieserdejesus/JamTaba/commit/6b4e8a89f7c06b19373db43f26ee319d07982877

- [x] Input combo box hover (not matching palette):
![image](https://cloud.githubusercontent.com/assets/15310433/18227146/1aedf110-71f1-11e6-9e12-6beec1316673.png)

- [x] menu selection color (too soft):
![image](https://cloud.githubusercontent.com/assets/15310433/18227279/87796fa4-71f5-11e6-9306-75c885c2a70c.png)

EDIT: (menu color fixed to this:
![image](https://cloud.githubusercontent.com/assets/15310433/18227785/60df3e94-7206-11e6-87e0-5ca6d33ce0a1.png) in https://github.com/elieserdejesus/JamTaba/pull/532)

- [x] FXpanel color too dim
- [x] zero gain button horizontal layout not correct
- [x] Low cut hover/hover check fix disabled ninjamer track

some other detail for the other themes so I don't forget:

TODO Black theme:

- [x] chat message selection colors
- [x] stereo inverse button hover/hover check fix disabled track mode
- [x] Low cut hover/hover check fix disabled ninjamer track

TODO FLAT theme:

- [x] stereo inverse button hover/hover check fix disabled track mode
- [x] Low cut and gain buttons hover/hover check fix disabled ninjamer track
- [x] check local track gain buttons hover check when track not xmit

TODO ROUNDED theme:

- [x] Low cut button state fix disabled ninjamer track
- [x] Horizontal zero gain button color fix ninjamer track
- [x] stereo inverse button hover/hover check local track not xmit

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixex the gray buttons and the  ninjam window buttons colors to match all Themes.

**Comment by jonjamcam** [comment]
@elieserdejesus I finished the details for all themes. I'll recheck tomorrow if something slipped my eye.

**Comment by elieserdejesus** [comment]
Ok @jonjamcam , thanks of your work!

**Comment by jonjamcam** [comment]
@elieserdejesus Do you think we should translate the volcano theme?

**Comment by elieserdejesus** [comment]
> Do you think we should translate the volcano theme name?

@jonjamcam , I think is a good idea since other Themes are translated too. I pushed a commit adding "Volcano" in translation files: cdc90566ba94ed9f83d73810bcbf289b862b0167.

**Comment by jonjamcam** [comment]
@elieserdejesus Spanish translation ready.

BTW: I'm sorry if I pushed so many commits or the Volcano theme. Ideas come in waves for me and I was constantly detecting little things to correct.

I hope now it's finally complete!
