### ISSUE TITLE
FR Auto update checker

### ISSUE THREAD

**Issue by pljones** [elieserdejesus/JamTaba#54]
Hi,

As JamTaba requires a network connection to be of any use, you could always add a "check for updates" to the software with the option for doing it automatically on start up.  If adding the on start up option, this should happen before any other initialisation (as the update could fix something that would otherwise cause the application to fail to start -- it would be nice to avoid that).

-- Peter

**Comment by elieserdejesus** [comment]
I like this idea too! I do something similar in Jamtaba 1. I have a "Launcher" executable checking for updates, and replacing the Jamtaba executable when necessary. I rember this works nice for the standalone, but I'm not shure if works for the VST plugin. To update the VST dll we need some more elaborated scheme. Maybe add the VST dll path in registry, so in case of updates the launcher/updater executable can replace the DLL in the correct path.

**Comment by Ezeer** [comment]
The autoUpdater is a neat idea !
I'm also very impatient to see how that will work in the code , i never did it before ...
cool !

**Comment by pljones** [comment]
I've taken the view in my software that the update checker needn't actually do anything other than alert the user a new version is available and allow them to go get it if they want it or ignore it if they don't.

**Comment by Ezeer** [comment]
That sounds good for a first step !
A lot of softwares are actually doing that , yeah .

**Comment by elieserdejesus** [comment]
Ezee, is not complicated build an autoupdater for the standalone. The trick is create another executable, a "launcher". This executable check for a new version, replace the Jamtaba.exe with a new version if necessary, and start Jamtaba.exe.  I use this solution in Jamtaba 1 and works very good. But to update the VST plugin is more complicated. The VST plugins "main/entry point" is in a DLL, and is invoked by host. We need think in some black magic to update the vst plugin DLL in this contidions. Off course use the autoupdate only in standalone is a easy solution. The VST plugin users can just receive a message "please, update or your HD will be formatted" :)

**Comment by Ezeer** [comment]
**"please, update or your HD will be formatted"**

AH AH AH ! 
:8ball:

**Comment by Ezeer** [comment]
"please, update or your HD will be formatted"

AH AH AH ! 
+1

Yeah , the pljones's idea seems to fit with the VST case .
I'll search in my black book a way to improove our magic skills ...
lol

--------------------------------------------
En date de : Mar 27.10.15, Elieser Ademir de Jesus <notifications@github.com> a écrit :

 Objet: Re: [JamTaba] FR Auto update checker (#54)
 À: "elieserdejesus/JamTaba" <JamTaba@noreply.github.com>
 Cc: "Ezee" <h2oreggae@yahoo.fr>
 Date: Mardi 27 octobre 2015, 16h38
 
 Ezee, is not complicated build an
 autoupdater for the standalone. The trick is create another
 executable, a "launcher". This executable check
 for a new version, replace the Jamtaba.exe with a new
 version if necessary, and start Jamtaba.exe.  I use this
 solution in Jamtaba 1 and works very good. But to update the
 VST plugin is more complicated. The VST plugins
 "main/entry point" is in a DLL, and is invoked by
 host. We need think in some black magic to update the vst
 plugin DLL in this contidions. Off course use the autoupdate
 only in standalone is a easy solution. The VST plugin users
 can just receive a message "please, update or your HD
 will be formatted" :)
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by pljones** [comment]
The very, very first step here is to have a json endpoint to query for the current version details.  That would need to be updated as part of publishing a new release build.  Once the format has been agreed, then the program code can be added to retrieve it and use it.  Maybe something like this:

```
{
  autoUpdate: {
    releaseVersion: {
      datePublished: YYYY-MM-DD-hh-mm-ss
      versionNumber: stringValue
      updateDescription: stringValue
    }
    (other values if they become needed, e.g. beta, alpha, snapshot versions...)
  }
  (other JSON API fields if so desired)
}
```

**Comment by pljones** [comment]
Actually, reading how github releases work, it would be a `git` request to get the latest release details.  I wonder if Qt has a nice `git` client library...

**Comment by pljones** [comment]
Huh, actually it seems this is done already!  Didn't find out till I started testing.
