### ISSUE TITLE
empty map, but users inside at launch

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#548]
![image](https://cloud.githubusercontent.com/assets/15310433/18228936/15987fb2-7239-11e6-93ea-96f9f2198628.png)

![image](https://cloud.githubusercontent.com/assets/15310433/18228938/1cda7d0c-7239-11e6-9daa-cc1504ea65cd.png)

I launched Jamtaba using the Volcano theme (and also flat theme), but changing theme the problem is solved:

![image](https://cloud.githubusercontent.com/assets/15310433/18228944/6ca4905c-7239-11e6-97f1-9aa60efd34ca.png)

Now launching again does not have problems, but if you delete the **lat_long_cache file**, the problem returns.

**Comment by elieserdejesus** [comment]
@jonjamcam , when user IP is not yet translated to [latitude, longitude] the user is not showed in map. In general this is solved after some seconds when Jamtaba receive the IP to geo location data.

**Comment by jonjamcam** [comment]
@elieserdejesus I did a clean install and no users are showing during the VST scan process. I waited more than a minute after this and no users appear either (total 3+ minutes). But if I change the theme, all rooms appear normally. It looks to me (I'm guessing) that this happens when no **lat_long cache file** is found and the 2.0.17 installer is not creating one.

**Comment by jonjamcam** [comment]
@elieserdejesus Now the clean installation is working OK.

**Comment by elieserdejesus** [comment]
@jonjamcam , let's wait some days until release 2.0.17, just to ensure this new version is bug free.
