### ISSUE TITLE
Copy menu for ninjamer channel name working, but it's not intuitive

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#564]
I tried to copy using the menu in standalone 2.0.17 beta:

![image](https://cloud.githubusercontent.com/assets/15310433/18233551/a74e2132-72c0-11e6-870c-30dfd45bb927.png)

but it's not working for me. tried CTRL + C, but the text can't be selected either.

EDIT: in JamtabaVST it works (text is copied if you select all before), but the menu behaves like it's not doing anything. In the standalone it works too, but you need to "select all" too before copy and the menu also behaves like it's not working.

@elieserdejesus It took me a while to figure out how it works:

1.- select all (copy disabled)
2.- copy

Now I think thee's nothing wrong, it's only not easy to follow. I will add instructions in the manual.

**Comment by elieserdejesus** [comment]
@jonjamcam , I think the problem is the CSS. We need a CSS rule to change the background of selected text. A secondary problem is the hover effect of disabled menu item. I think the ideal approach is not highlight (hover effect) the disabled menu item. If the menu item is grayed and not highlight users will not click. The highligh is causing a false impression of a "enabled/clickable" item.

**Comment by elieserdejesus** [comment]
@jonjamcam , the last 2 commits improved the visual feedback for this menu copy action,

**Comment by jonjamcam** [comment]
I see, much better. Now you can select parts. The problem is with long strings. They are truncated as shown in the marquee (for example: **default ch...**) and not copied complete even if you **select all**.

**Comment by elieserdejesus** [comment]
@jonjamcam , long strings problem fixed in 8e247d7e5ecb4e93130c1426055d21ce89c6265f

**Comment by jonjamcam** [comment]
@elieserdejesus I found the ninjamer name is off center now

![image](https://cloud.githubusercontent.com/assets/15310433/18259318/2625b710-73b9-11e6-9225-696d20badd96.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , the ninjamer name is center now f976696f6e0d081f08466b9a40b42c9728f5b098
