### ISSUE TITLE
"Reconnect option" when connection lost instead of exit

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#565]
If the connection is lost  Jamtaba Standalone just quits after showing:

![image](https://cloud.githubusercontent.com/assets/15310433/18253162/db44b494-7368-11e6-9840-52e975a4f1a3.png)

If you use the VST Plugin you'll need to close the host and relaunch which is inconvenient.

@elieserdejesus Is it possible to allow re-connection (automatic or manual) in these cases?

**Comment by elieserdejesus** [comment]
> Is it possible to allow re-connection (automatic or manual) in these cases?

Shure @jonjamcam, this can be improved in next versions.

**Comment by jonjamcam** [comment]
handled in https://github.com/elieserdejesus/JamTaba/issues/993 . closing
