### ISSUE TITLE
Jamtaba crashes sometimes for unknown reason

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#568]
This happened to me 2 or 3 times during testing this last days using one computer (WIN7) and two computers (XP and WIN7) too.

 After a while having a couple of jamtaba clients connected (but no sound being sent) I noticed one of them suddently crashed today(this happened yesterday too but with only one client connected to ninbot). I don't know why and I didn't pay attention to the details (server, connection times, etc) because I assumed it was my computer that did something wrong.

This last time it happened in XP so the problem is cross platform. I have a guess. My connection was a bit slow by the time the crash happened, but I'm not sure if this is the reason for the crash.

I can do some additional testing rounds during the day tomorrow and see what happens.

**Comment by jonjamcam** [comment]
@elieserdejesus I'm doing some test limiting jamtaba's available bandwidth and I get unstable behavior. 

I used a proxy and just cut the connection suddenly. This time i didn't get a crash, but the audio meters froze.

 Do you have any tools to "starve" jamtaba and see what happens?

**Comment by elieserdejesus** [comment]
@jonjamcam , I don't special tools, but an idea is upload a big enough file using dropbox or wetransfer (for example) while download a big torrent. This will consume upload and download bandwith and generate a good "worst case" test scenario.  

But I think this is not a test to v2.0.17, we can handle this issue in next release.

**Comment by jonjamcam** [comment]
> But I think this is not a test to v2.0.17, we can handle this issue in next release.

OK.

**Comment by elieserdejesus** [comment]
@jonjamcam , some news in this issue?

**Comment by jonjamcam** [comment]
@elieserdejesus No crashes lately in my experience. Closing......

**Comment by jonjamcam** [comment]
@elieserdejesus I had two crashes today using the latest 2.0.19 vst plugin you sent me yesterday (https://github.com/elieserdejesus/JamTaba/issues/656#issuecomment-274297253) in win7 for unknown reason. I had no problems before with 2.0.18 that I remember, but two crashes in one day is weird. I was able to take a snapshot:

![image](https://cloud.githubusercontent.com/assets/15310433/22187569/a8f4c596-e0e7-11e6-8ff8-00157d4ef9df.png)


I'm using Reaper 4.78 x64. The strange thing is that I played all day today and the crashes don't follow specific patterns that I could recognize. I'll upgrade to Reaper 5 and test again, but i think it's not worth reopen yet until it happens again. My suspect is Reaper in this case.

**Comment by elieserdejesus** [comment]
@jonjamcam , the plugin log file is clear? some clue about the crashes in log?

**Comment by jonjamcam** [comment]
> some clue about the crashes in log?

Nothing, olny this:

`default.INFO      [19:15:56:846] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [19:15:57:993] "Starting Jamtaba 2.0.19 Standalone (i386) running on Windows 7 (x86_64)" [, line 0]
`

**Comment by elieserdejesus** [comment]
no clues @jonjamcam  :(

**Comment by jonjamcam** [comment]
no worries @elieserdejesus . I'm sure it's something very specific. Remember https://github.com/elieserdejesus/JamTaba/issues/457 and https://github.com/elieserdejesus/JamTaba/issues/294 . I think the important thing is document the problem when it happens (if it happens again, I updated reaper to 5.32). Then we can analize the data.

BTW, 2.0.19 is working ver well. Lot's of fun lately jamming :D .

**Comment by elieserdejesus** [comment]
> Lot's of fun lately jamming :D .

I totally agree :) We did a great jam last weekend.

**Comment by jonjamcam** [comment]
> We did a great jam last weekend

It was fantastic!
