### ISSUE TITLE
notification when installing on win10 x64

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#570]
Windows 10 is suggesting not to install

![image](https://cloud.githubusercontent.com/assets/15310433/18281758/7955e538-7434-11e6-9c03-4eae6b134f49.png)

more information display this:

![image](https://cloud.githubusercontent.com/assets/15310433/18281802/b00ddc2a-7434-11e6-9278-6d4e29e37874.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , this installer is the pre-release? I think the pre-release url in git hub are not "trusted" by windows, and the official releases URL are ok. Can you test downloading a official release (v2.0.16 or v2.0.15)?

**Comment by jonjamcam** [comment]
@elieserdejesus Indeed it's the beta version. I already checked the option to install, so at the moment I can't revert to see the notification (I'm not awin10 savy), but I get similar notification with both 2.0.16 official and 2.0.17 beta in my win7:

![image](https://cloud.githubusercontent.com/assets/15310433/18284317/d540c556-743f-11e6-86ca-ad6a2cecc5dc.png)

**Comment by elieserdejesus** [comment]
I see other git hub repositories with the same problem. Some guys mentioned the solution: "We need a code signing certificate." These sign certificates cost some money.

**Comment by jonjamcam** [comment]
> These sign certificates cost some money.

OK. Closing then.
