### ISSUE TITLE
buttons for "save preset" do not follow css style rules

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#576]
![image](https://cloud.githubusercontent.com/assets/15310433/18297828/26254a06-748a-11e6-8d9e-e5fed4327ead.png)

should we add a separate rule for them?

**Comment by elieserdejesus** [comment]
@jonjamcam , I just dropped the custom rules for QInputDialog (the dialog used in 'Save Preset') and now the buttons colors are always matching the current theme.
