### ISSUE TITLE
Some CPU improvements discussion

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#583]
@elieserdejesus I've been testing 2.0.17 in my old Pentium 4 XP machine this week and found some little details that I would like to share with you to see if we can improve them.

This system is very slow compared with today computers, but this is an advantage when trying to see problems because they pop up instantly. I use a **native ASIO card** (delta 1010LT) with very low latency (**1.9ms**) which is very stressing to the overall system. For example if I'm connected to a server, if I use the mouse I have (USB) increases the CPU use to over 50%.

Within this context, some days ago **I connected to a full server** and I saw three things that made my CPU spike:

**1.- Marquee animation for ninjamer channel name:** Tests show marquee could be consuming big amounts of CPU when activated. I noticed this when changing to horizontal mode my CPU was less stressed.

**2.- Interval progress bar for ninjamers:** This appears to consume some CPU during a Jam when activated. I noticed it because the audio had little cuts when the one bar appeared. I can assume this could increase a lot if several bars are displayed at the same time.

**3.- peak/RMS meter:**  the peak meter animation increases the amount of CPU by a little bit (no more than 10%) when inside a ninjam room. I tested four scenarios: **NO METERS**, **RMS METER ONLY(NO PEAKS)**, **PEAKMETER ONLY (NO PEAKS)** and **SHOW PEAKS ONLY**. This were the results:

![image](https://cloud.githubusercontent.com/assets/15310433/18416835/a4430b98-77f6-11e6-926b-74fc170c8da5.png)

NEW **4.- When users turn on their channel that was previously off, I have some dropouts**. (By now I'm thinking anything that uses graphics a bit is messing with my old XP system when in reltime audio mode.)

I compiled a special version for testing preventing the above to activate and the results were much better. No more sudden spikes in CPU in a full server and overall CPU usage was less than 50% for about an hour of total testing.

I understand these are not real problems for today computers, but when you use VSTi, FX, etc in low latency environments, CPU start to increase a lot and improving these kind of details could be useful.

NOTE: All this tests were made using **Xmit off**. I did set Xmit on at some point, but the CPU went all up to 70%, the source being floor noise only. I noticed too that big changes in dynamics of the incoming audio during encoding forces heavy use of CPU resources, but I understand this is not possible to solve (unless the signal is reduced in dynamic range before the codec process). I have one more test pending: What's the less CPU consuming quality of all (from -0.1 to 1).

The only solution I can see for now is make Jamtaba detect CPU uses over 60% or 70% and trigger some protection stopping some animations, for example, but this is the PANIC approach :D. Maybe you have another ideas.

**Comment by elieserdejesus** [comment]
@jonjamcam , these are very interesting tests.  I think the 3 first items (Marquee animation, Interval progress and peak/RMS meter) can be improved. The performance of encoder is more complicated to tweak.

The peak meter animation is updated at a fixed rate (20 ms). This is a lot of drawing per second for a slow machine. In Reaper is possible choose this "refresh rate". This is very simple to implement.

@jonjamcam , In the file **MainWindow.cpp**, line **193** you will see
```
timerID = startTimer(1000/50)
```
This line is setting the peaks animation timer refresh rate to 1000/50 = 20 ms. You can try another values (50ms, 100 ms) and check if the CPU usage is reduced.

**Comment by jonjamcam** [comment]
@elieserdejesus The timerID is a very important factor in CPU consumption. I did two extreme tests in my P4 XP system to push the limits, but this time in a 3 player room only.

1.- TimerID set to 10 (1000/100):  the CPU meter went all up to 100%.

2.- TimerID set to 100 (1000/10):  CPU very relaxed about 15%-25%. In this case I turned on the Xmit button, loaded a VST plugin and played with no problems. CPU went no beyond 50%. **Drawbacks:** Meters move slowly (both PEAK and RMS) giving the visual impression of slow system.

**Comment by elieserdejesus** [comment]
> So @elieserdejesus is it possible add a json entry for the TimerID value? 

Sure @jonjamcam, and I think a GUI option is usefull too, and easy to implement.

**Comment by elieserdejesus** [comment]
@jonjamcam , Reaper is using 1000/30 (30 Hz, or 30 updates per second) as default value. Maybe this can be a good "default" value for Jamtaba too.

![image](https://cloud.githubusercontent.com/assets/1012741/18476655/48dab0f6-79a1-11e6-8a89-6d9d8a05b14e.png)

**Comment by AndyMcProducer** [comment]
Audio buffers processed asynchronously, can improve performance with some plugin/host combinations
