### ISSUE TITLE
Delete preset code?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#585]
I found there's still some code (probably from 2.0.7) for a **Delete Preset** feature:

https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/Configurator.cpp#L192
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/Configurator.h#L34
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/MainController.cpp#L607
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/MainController.h#L59
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/gui/LocalTrackGroupView.cpp#L314
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/gui/LocalTrackGroupView.h#L104
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/persistence/Settings.cpp#L830
https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/persistence/Settings.h#L368

but it has never been implemented. 

@elieserdejesus  Do you think it's better to clean it up or try to implement?

**Comment by elieserdejesus** [comment]
@jonjamcam , I think is better finish the feature.

**Comment by jonjamcam** [comment]
PR https://github.com/elieserdejesus/JamTaba/pull/586 merged, closing
