### ISSUE TITLE
Volcano theme gray icons in channel menu and fader do not match pallete

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#589]
![image](https://cloud.githubusercontent.com/assets/15310433/18457304/e3f3dd5c-792d-11e6-968e-efc780bbf038.png)

Same happens with fader icons:

![image](https://cloud.githubusercontent.com/assets/15310433/18457316/144c6dfc-792e-11e6-98e0-3f7fdd147d8c.png)

and the MIDI icon:

![image](https://cloud.githubusercontent.com/assets/15310433/18457346/5b127d12-792e-11e6-8d09-021138edb11f.png)

**Comment by elieserdejesus** [comment]
fixed in #592
