### ISSUE TITLE
Request/Issue VST popout window.

### ISSUE THREAD

**Issue by AndyMcProducer** [elieserdejesus/JamTaba#591]
Many of you maybe seen that many are streaming via obs to Facebook, twitch, youtube or just recording videos.
OBS is capable of pulling windows directly, making things much tidier then trying to grab a desktop area where a window will inhabit.

Problem comes from some vst's not being able to be popped out, some allow for this and some not.
This means obs and other cam/screen grabbing software can't see Jamtaba when it's an VST.

I can use jbridge which allows me to popout jamtaba so then I can grab it but issues like sync then not working arise.

Would it be possible to popout Jamtaba into an windows environment window, so obs and similar software's could then grab it.

Some have 1366x768 monitors too on laptops and so on and Jamtaba is larger than this area and not currently resizable, meaning it couldn't be grabbed as a screen area, so only if popped out could it be grabbed fully.

Pls don't stress over this, I personally could probably tweak jbridges settings to maybe get the sync working.

There is a RewireVST online, free for 2 channels, does Jamtaba use any form of MTC yet which the RewireVST could pickup? This would allow sync to and from via RewireVST from standalone to daws.

**Comment by elieserdejesus** [comment]
> does Jamtaba use any form of MTC

Andy, no MTC in Jamtaba at moment. The midi capabilities are very simple, just the basic (notes and CCs).

About Jamtaba window: I'm not sure if is possible create a separated window for the vst plugin, because this window is created by the DAW. So, I think this decision (create a separated window) can't be maded by the plugin, it's a DAW decision. But I'm not 100% sure about this.

**Comment by elieserdejesus** [comment]
@AndyMcProducer , you mentioned 
> Problem comes from some vst's not being able to be popped out, some allow for this and some not.

This "abble to be popped out" feature is **a plugin feature** or **a Cubase feature**? I suspect this window behavior is controlled by the host.

**Comment by AndyMcProducer** [comment]
I use jbridge with jamtaba now, so i get it in it's own window which obs can see, plus if any crashes i can just restart it without a daw crash.

**Comment by elieserdejesus** [comment]
Ok Andy, I will close this issue.

>  Would be great having couple or short cut keys for the inc and dec width and height, like CTRL + keys or ctrl and mouse wheel or something. Is a bit fiddly goign back to top file menu to adjust size.

I created a new issue for this: https://github.com/elieserdejesus/JamTaba/issues/936

I general short cut keys are very limited in plugins because the DAW is "eating" the key press events.

**Comment by AndyMcProducer** [comment]
Could be a like clickable boxes next to the other resize buttons.
H + -
W + -
