### ISSUE TITLE
Use 720 pixels as minimum height

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#594]
AndyMc proposed 720p as minimum height. At moment the current minimum height is not working nice in some laptops.

720p will work nice in VstPlugin too.

**Comment by jonjamcam** [comment]
is this a narrowing for the full view mode?

790
 V
720

**Comment by elieserdejesus** [comment]
yes @jonjamcam , but is necessary test to see if the layout will work without crops in 720 pixels.
