### ISSUE TITLE
Two additional gray icons that don't match palette

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#597]
![image](https://cloud.githubusercontent.com/assets/15310433/18555226/7c058abc-7b3d-11e6-95cc-04817f71d1cd.png)

![image](https://cloud.githubusercontent.com/assets/15310433/18555278/b297928c-7b3d-11e6-8f9f-64c3ba6913b2.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , this "loading" image is a gif file. I think is possible just edit the gif file and change the transparency to something like 60%. You know some tool to edit the whole gif transparency?

**Comment by jonjamcam** [comment]
> You know some tool to edit the whole gif transparency?

@elieserdejesus I don't know any :(.

But what do you think about changing the animation for something that's transparent ready? I mean try to find one.

**Comment by jonjamcam** [comment]
Looks like a completely black animation is working OK. But hard to find one with no white borders.

**Comment by elieserdejesus** [comment]
@jonjamcam , I tested this last gif and the result is nice in all themes. Just a little white border in black theme, but it's ok in my opinion.

**Comment by jonjamcam** [comment]
> Just a little white border in black theme

we can tweak a little bit the background to mask the white border then.

**Comment by elieserdejesus** [comment]
I created a PR including all these changes.
