### ISSUE TITLE
From 2.0.18 on, changes in themes made in the code will not be updated in the theme folders

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#602]
This could be a maintenance problem for future releases:

Once the **Themes** folder is created in every user's disk, then changes to the code will not updated in the corresponding folder.

I noticed this when trying to update some theme code. I had to do it directly in the .css, because changing it in QT didn't work.

My solution this time was to delete the themes folder and let Jamtaba create a new one with the updates.

1.- If Jamtaba could compare and ask via a dialog asking to update when there's difference could be one way to solve it.

2.- or Just replace files that have difference?

**Comment by jonjamcam** [comment]
@elieserdejesus Testing the new Ice theme integration as a built in theme, the ICE folder is not created unless the themes folder is removed (and thus created again on next launch).

**Comment by elieserdejesus** [comment]
@jonjamcam , at moment JAmtaba is checking if the Themes dir exists. If not the dir is created and the built-in themes are exported to AppData. In your case the Themes dir exists, and the theme export routine is not called. 
I think an easy (but not perfect) solution is run a separeted check for every built-in theme. If a built-in theme is not present in Themes dir this theme will be "exported".

**Comment by jonjamcam** [comment]
>I think an easy (but not perfect) solution is run a separeted check for every built-in theme. If a built-in theme is not present in Themes dir this theme will be "exported".

That will solve the issue for new themes, but if old ones are updated then new changes will not appear. For example. The new little buttons in the jamroom wave preview have it's own hover. These changes will not be updated for the common user. This will happen for every new feature in the future.

**Comment by elieserdejesus** [comment]
> ... "user's theme folder" separate from a "mainstream theme folder".

@jonjamcam , this is a good idea.

Another idea is keep the current solution, but check the lastEdited attribute in every css file in theme folder. If we have a new/last edited file in resources this file will be "exported". This solve the problem you mentioned before for new versions, but user changes in css files will be replaced.

**Comment by jonjamcam** [comment]
>keep the current solution, but check the lastEdited attribute in every css file in theme folder. If we have a new/last edited file in resources this file will be "exported". This solve the problem you mentioned before for new versions, but user changes in css files will be replaced.

nice! Very good solution @elieserdejesus .
