### ISSUE TITLE
Second channel in Jamtaba vst 2 and Ableton Live

### ISSUE THREAD

**Issue by HammertheBammer** [elieserdejesus/JamTaba#605]
Hi Elieser,

Eric here aka HammerOn in Ninjam/Ninbot.
I am trying to use Jamtaba latest version 64 bits VST with Ableton Live.
Works like a charm so far except that I cant route output to a second channel.

In REAPER with reaninjam vst its possible to route for instance channel 1/2 to Ninjam channel 1 and channel 3/4 to Ninjam channel 2.

How can I setup this in Jamtaba 64 bits VST.

Thanks in advance
Good job btw

Cheers
Eric

**Comment by elieserdejesus** [comment]
It's solved in ninbot: 
[http://ninbot.com/topic/jamtaba-2-released](http://ninbot.com/topic/jamtaba-2-released)
[http://ninbot.com/topic/ableton-live-and-jamtaba-no-multichannel](http://ninbot.com/topic/ableton-live-and-jamtaba-no-multichannel)
