### ISSUE TITLE
Jamtaba.json overwrite

### ISSUE THREAD

**Issue by Krill0** [elieserdejesus/JamTaba#609]
Hi

Just registred on GitHub. I am manually trying to edit Jamtaba.json. I run the VST-version. This file gets overwritten when I start and then exit Reaper and the Jamtaba plugin. Recordpath defaults to C:\Documents and Settings\User\Documents\Jamtaba, metronome reverts to default etc.
The overwrite seems to happen when closing Reaper, but the settings aren't read but ignored and then overwritten on exit.
Should logging.ini be edited in a certain way for changes to Jamtaba.json to be permanent?
I am running XP 32-bit

**Comment by elieserdejesus** [comment]
Hi @Krill0 , I tested here and you are right. When I choosed a record path using Jamtaba preferences works fine, but when I manually changed the .json file the record path is reseted.

It's a little bug in these record settings code.

**Comment by Krill0** [comment]
Hi
Good the issue can be reproduced.

Initially I started out editing Jamtaba.json to set encoder quaity to high, but then proceeded to experiment with buffersize and narrow tracks etc so I came to notice this issue.

**Comment by Krill0** [comment]
This bug is still present in VST version 2.0.19 (I'm on XP if that matters)

**Comment by elieserdejesus** [comment]
Hi @Krill0 , can you help showing more details? 
**What you are typing in json file exactly?** I'm interested in your slashes, because **C:/Documents** is different from **C:\Documents** (backward and forward slash).

**Comment by Krill0** [comment]
@elieserdejesus Sorry for late answer. The incorrect slashes were a typo, I updated them.

**Comment by Krill0** [comment]
> What you are typing in json file exactly?
@elieserdejesus Here's the file. I've changed bufferSize, encodingQuality and usingNarrowTracks. They all revert back to default on starting Jamtaba VST. In standalone version I can succesfully set high quality encoder in GUI. 
[Jamtaba.json.txt](https://github.com/elieserdejesus/JamTaba/files/957457/Jamtaba.json.txt)

**Comment by elieserdejesus** [comment]
Hi @Krill0 
> In standalone version I can succesfully set high quality encoder in GUI

The high quality encoding is not working in VST GUI?

**Comment by elieserdejesus** [comment]
@Krill0 , I opened your file and see 2 problems:
![image](https://cloud.githubusercontent.com/assets/1012741/25430850/a4a67532-2a54-11e7-9a60-1141a573b7bf.png)

1 - you are using **0,3** in *encodingQuality*, the correct is **0.3**. Replace the **,** with a dot.
2 - Be shure the **firstIn: 0** text is in the next line after encodingQuality line.

**Comment by Krill0** [comment]
> The high quality encoding is not working in VST GUI?
@elieserdejesus The menu item is actually missing. If it was possible to acces via GUI, I would gladly leave the json-file alone. Regarding the comma vs dot (, .) I don't change them, I only change the number. There are commas in several other places in the file, so I figured comma was correct. I tested with dot now. It resets to comma after exiting Reaper / Jamtaba VST. Also there is no input channel configured.

![jamtaba standalone preferences](https://cloud.githubusercontent.com/assets/23060456/25435268/c12321d4-2a8f-11e7-89fd-649503e21569.JPG)
![jamtaba vst preferences](https://cloud.githubusercontent.com/assets/23060456/25435269/c12d67e8-2a8f-11e7-8638-fbe1b5464bcd.JPG)

**Comment by elieserdejesus** [comment]
@Krill0 , I tested the value **0.3** in Vst plugin and is working fine. I fixed the syntax issues in your file:
[Jamtaba.json.txt](https://github.com/elieserdejesus/JamTaba/files/959327/Jamtaba.json.txt)

In programming the dot and the comma have different meanings. Commas are used to separate different properties. This is the correct syntax (using dot and comma):
![image](https://cloud.githubusercontent.com/assets/1012741/25449070/f2191ebe-2a90-11e7-96b7-efd81276f6d1.png)

**Comment by Krill0** [comment]
@elieserdejesus You make no sense.

**Comment by elieserdejesus** [comment]
@Krill0 , I suggest you to test the attached file in my previous comment or change your json file to match the image I posted before.

**Comment by jonjamcam** [comment]
@Krill0 ONe question. while you're editing the json file, is Jamtaba VST (and Host) open?

Remember that Jamtaba saves the json file when closed.

All editing should be done while the software is not operative.

**Comment by Krill0** [comment]
@elieserdejesus I'm sorry you do make perfect sense. It was the comma AFTER that I missed. If this comma is missing, the file is reset. Thanks and sorry for the confusion.

**Comment by elieserdejesus** [comment]
no problem @Krill0 , It's good see you solved the issue. 

And my english is just the minimum, so many times my words make no sense 😄
