### ISSUE TITLE
pl_PL country name translations showing in german

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#612]
@elieserdejesus  Nekudo is probably not supporting Polish language for translation of country names:

![image](https://cloud.githubusercontent.com/assets/15310433/20872674/20e32316-ba7f-11e6-9337-0a2dfee7d8a5.png)

![image](https://cloud.githubusercontent.com/assets/15310433/20872688/4348c528-ba7f-11e6-8836-c486355f87cc.png)

![image](https://cloud.githubusercontent.com/assets/15310433/20872668/0bd8c6f6-ba7f-11e6-85dc-0bcc426cf596.png)

**Comment by qulf** [comment]
maybe you can change german for english? that will be better

**Comment by elieserdejesus** [comment]
Nekudo API (used to translate country names) is supporting only a small language set (de, es, fr,  ja, pt, ru, zh). Now when user is using a non supported language (for country names) the country name will appear in  English.
