### ISSUE TITLE
refresh rate set to '0' instead of '30' in json file by default

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#614]
![image](https://cloud.githubusercontent.com/assets/15310433/21025352/d74a6e18-bd66-11e6-9981-dc20a9d54340.png)

Tested deleting _jamtaba.json_ file to simulate a clean install.

**Comment by elieserdejesus** [comment]
@jonjamcam , I think the problem is in [this line](https://github.com/elieserdejesus/JamTaba/blob/master/src/Common/persistence/Settings.cpp#L858)

Can you do the honors, please? Just change the zero value to 30.

**Comment by jonjamcam** [comment]
fixed in https://github.com/elieserdejesus/JamTaba/pull/615

**Comment by elieserdejesus** [comment]
thanks @jonjamcam

**Comment by jonjamcam** [comment]
@elieserdejesus Testing beta 2.0.18 I found that when doing a clean install, the Refresh Rate value in the .json file is set to 0 by default. The correct value of 30 appears if I delete the .json file so Jamtaba creates a new one when launching again.

Can you confirm if it's only me?

**Comment by elieserdejesus** [comment]
Confirmed @jonjamcam , the problem appears only when we install v2.0.18 without uninstall the previous version. I fixed the problem in the last commit https://github.com/elieserdejesus/JamTaba/commit/bb92fdf796ab617b21dc255933d2c989ce5c495e
