### ISSUE TITLE
No audio in Kontakt 5 multi-out and maybe in other multi-out VST plugins

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#62]
pljones reported no audio in Kontakt 5 8 out.

**Comment by Ezeer** [comment]
Okay ... i labeled task because 8 out is a special feature .
If someone use Kontact5 8 stereo outs but effectly use only 1 stereo out , it is better for everybody that this user choose the right Kontact dll .

Now that we have the blackBox working , we can set up Jamtaba to refuse to load this kind of baby
until Jamtaba is able to use it .
That's my point now for a quick answer .

Then  we'll have time  to work on that interesting feature , but that is not a priority .
Is it a priority ?
( i hear the drummers shouting " IT IS A PRIORITY " eh eh ... )
![rtemagicc_b100f3f854 png](https://cloud.githubusercontent.com/assets/1283808/10836692/dd7985bc-7eb0-11e5-874d-aff9caf72385.png)

**Comment by elieserdejesus** [comment]
Ezee, the multiout feature was working in last builds. I change the code to solve a problem in VST chain when using plugins like guitar rig, amplitube, etc. Now this chain problem is solved but I bug something in multi-out. I will check this problem soon. I'm a Kontakt user, so I'm very interested in fix this bug.

**Comment by Ezeer** [comment]
ah ah ah ...
I just give it to you dear Kontact user !
I use also Kontact , but for saxophone or trumpets ...
I am the 1 stereo out guy .... lol

**Comment by Ezeer** [comment]
Perhaps it is the right place ( 8 outs ... ) to introduce the idea of a **Jamtaba's user guide** .
And here , we could be in the " Advanced section " ?
mmm... That should be exposed in a new " Task " .
( people read "User Guides" ? ^^ )

**Comment by elieserdejesus** [comment]
@pljones, @Ezeer I can't reproduce the problem in Kontakt 5 multi out. I test my Kontakt (8 out and 16 out) here and is working without problems. Can you test the new beta in your machines?
[https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.5-beta](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.5-beta)

**Comment by pljones** [comment]
Bad news - the 64bit build does not start up:

[Jamtaba2.exe.6156.dmp](http://peter.drealm.info/Jamtaba2.exe.6156.dmp)

There is not even a log file, just the dump.

Have you changed the build?

**Comment by pljones** [comment]
OK, I tried the 64-bit installer, it crashed before creating a log.  I cleaned the install and tried again.  Same result, unfortunately.  Here's the crashdump if it helps:
```
Dump Summary
------------
Dump File:	Jamtaba2.exe.3964.dmp : C:\Users\Peter L Jones\AppData\Local\CrashDumps\Jamtaba2.exe.3964.dmp
Last Write Time:	01/11/2015 14:20:18
Process Name:	Jamtaba2.exe : D:\Program Files\JamTaba 2\Jamtaba2.exe
Process Architecture:	x64
Exception Code:	0xC0000026
Exception Information:	An exception handler returned an invalid disposition to the exception dispatcher. Programmers using a high-level language such as C should never encounter this exception.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.10240
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
Jamtaba2.exe	D:\Program Files\JamTaba 2\Jamtaba2.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	10.0.10240.16430
kernel32.dll	C:\Windows\System32\kernel32.dll	10.0.10240.16384
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	10.0.10240.16384
advapi32.dll	C:\Windows\System32\advapi32.dll	10.0.10240.16384
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.10240.16384
sechost.dll	C:\Windows\System32\sechost.dll	10.0.10240.16384
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	10.0.10240.16412
user32.dll	C:\Windows\System32\user32.dll	10.0.10240.16384
gdi32.dll	C:\Windows\System32\gdi32.dll	10.0.10240.16390
shell32.dll	C:\Windows\System32\shell32.dll	10.0.10240.16542
windows.storage.dll	C:\Windows\System32\windows.storage.dll	10.0.10240.16515
combase.dll	C:\Windows\System32\combase.dll	10.0.10240.16384
shlwapi.dll	C:\Windows\System32\shlwapi.dll	10.0.10240.16384
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	10.0.10240.16384
SHCore.dll	C:\Windows\System32\SHCore.dll	10.0.10240.16384
powrprof.dll	C:\Windows\System32\powrprof.dll	10.0.10240.16384
profapi.dll	C:\Windows\System32\profapi.dll	10.0.10240.16384
oleaut32.dll	C:\Windows\System32\oleaut32.dll	10.0.10240.16384
imm32.dll	C:\Windows\System32\imm32.dll	10.0.10240.16384
msctf.dll	C:\Windows\System32\msctf.dll	10.0.10240.16384
ws2_32.dll	C:\Windows\System32\ws2_32.dll	10.0.10240.16384
nsi.dll	C:\Windows\System32\nsi.dll	10.0.10240.16384
winmm.dll	C:\Windows\System32\winmm.dll	10.0.10240.16384
ole32.dll	C:\Windows\System32\ole32.dll	10.0.10240.16384
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	10.0.10240.16384
d3d9.dll	C:\Windows\System32\d3d9.dll	10.0.10240.16412
msvcp120.dll	C:\Windows\System32\msvcp120.dll	12.0.21005.1
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	10.0.10240.16384
msvcr120.dll	C:\Windows\System32\msvcr120.dll	12.0.21005.1
dwmapi.dll	C:\Windows\System32\dwmapi.dll	10.0.10240.16392
devobj.dll	C:\Windows\System32\devobj.dll	10.0.10240.16384
version.dll	C:\Windows\System32\version.dll	10.0.10240.16384
CRYPTBASE.DLL	C:\Windows\System32\CRYPTBASE.DLL	10.0.10240.16384
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	10.0.10240.16384
uxtheme.dll	C:\Windows\System32\uxtheme.dll	10.0.10240.16397
Start8_64.dll	C:\Program Files (x86)\Stardock\Start8\Start8_64.dll	1.5.5.0
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	10.0.10240.16384
winnsi.dll	C:\Windows\System32\winnsi.dll	10.0.10240.16384
dhcpcsvc.dll	C:\Windows\System32\dhcpcsvc.dll	10.0.10240.16384
dhcpcsvc6.DLL	C:\Windows\System32\dhcpcsvc6.DLL	10.0.10240.16384
wlanapi.dll	C:\Windows\System32\wlanapi.dll	10.0.10240.16384
MMDevAPI.dll	C:\Windows\System32\MMDevAPI.dll	10.0.10240.16384
propsys.dll	C:\Windows\System32\propsys.dll	7.0.10240.16384
wdmaud.drv	C:\Windows\System32\wdmaud.drv	10.0.10240.16384
ksuser.dll	C:\Windows\System32\ksuser.dll	10.0.10240.16384
avrt.dll	C:\Windows\System32\avrt.dll	10.0.10240.16384
AudioSes.dll	C:\Windows\System32\AudioSes.dll	10.0.10240.16412
WinTypes.dll	C:\Windows\System32\WinTypes.dll	10.0.10240.16384
msacm32.drv	C:\Windows\System32\msacm32.drv	10.0.10240.16384
msacm32.dll	C:\Windows\System32\msacm32.dll	10.0.10240.16384
midimap.dll	C:\Windows\System32\midimap.dll	10.0.10240.16384
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
asioechofirewire.dll	c:\Windows\System32\asioechofirewire.dll	5.8.0.0
setupapi.dll	C:\Windows\System32\setupapi.dll	10.0.10240.16384
wintrust.dll	C:\Windows\System32\wintrust.dll	10.0.10240.16385
msasn1.dll	C:\Windows\System32\msasn1.dll	10.0.10240.16384
crypt32.dll	C:\Windows\System32\crypt32.dll	10.0.10240.16384
jackrouter.dll	d:\program files (x86)\Jack\64bits\jackrouter.dll	0.2.1.0
msvcp100.dll	d:\program files (x86)\Jack\64bits\msvcp100.dll	10.0.30319.1
msvcr100.dll	d:\program files (x86)\Jack\64bits\msvcr100.dll	10.0.30319.1
libjack64.dll	C:\Windows\libjack64.dll	1.9.10.0
psapi.dll	C:\Windows\System32\psapi.dll	10.0.10240.16384
```

**Comment by pljones** [comment]
The 32bit one starts (it's still a very slow start - I keep thinking it's crashed).

I got Kontakt loaded up and it seems to be OK now.

**Comment by Ezeer** [comment]
I don't have Kontakt nor midi device on the machine i'm coding on ( shame on me :) ) .
So i can't test that now , i will try at my home-studio later .

**Comment by pljones** [comment]
You don't need Kontakt -- I didn't get MIDI In for any VSTi.  I could see the MIDI interface was enabled.

[Here](http://peter.drealm.info/log.txt)'s a rather big log.txt which may help.

**Comment by elieserdejesus** [comment]
@pljones, thanks for your help!
So, the 64 bits is not working in your Win 10, right?

About the MIDI in Kontakt 5: please try change Kontakt to receive from all channels (OMNI). I have a similar issue here with my AKAI PK 25 midi controller. This controller is configured to send messages in channel 4, so Kontakt can't receive MIDI messages from this controller until I change the Kontakt midi RCV for channel 4 or OMNI.  Please check if you have some similar issue in your environment.

**Comment by pljones** [comment]
Hi,

Kontakt is set to omni.  It's not a channel number issue.  The MIDI in indicator isn't showing any activity - that happens regardless of omni/channel setting.

Thanks,

-- Peter

**Comment by elieserdejesus** [comment]
@pljones, your log show a lot of things to work. 
A question: you edited the file logging.ini manualy?
I'masking this because I see "qt.core.logging.WARNING:  Ignoring malformed logging rule:" in your log. So I'm suspecting from some problem with line breakins.

**Comment by pljones** [comment]
> A question: you edited the file logging.ini manualy?
No - I didn't touch anything - it was a clean, blank install.

**Comment by elieserdejesus** [comment]
pljones, can you paste the content for your **logging.ini** file?
This file is in Users/your user/AppData/Local/Jamtaba 2

**Comment by elieserdejesus** [comment]
This log explain your slow starting. The logging configuration is messed, so your Jamtaba is starting with all log messages enabled, it's a lot of messages and it's slow down the performance.

**Comment by pljones** [comment]
[Here](http://peter.drealm.info/logging.ini)'s a link to the file.

**Comment by Ezeer** [comment]
@pljones  we are the rockers : https://github.com/elieserdejesus/JamTaba/wiki/Jamtaba's-user-guide
( look at the troubleshooting part for advanced users ;) )

**Comment by elieserdejesus** [comment]
Ezee, we some problem in the log scheme, maybe is a win 10 issue only, but we have some problem. The log rules are not parsed and pljones never touch the logging.ini  file. Pljones I will investigate this annoying problem.

If you still have some patience for Jamtaba please try the link posted by Ezee, try disable all log messages.

**Comment by pljones** [comment]
[Here](http://peter.drealm.info/APPDATA-Local-Jamtaba_2.zip)'s my complete "%APPDATA%\Local\Jamtaba 2" directory produced by:
1) delete existing content of directory
2) start Jamtaba 2 32bit
3) exit Jamtaba 2
(and nothing else)

**Comment by pljones** [comment]
According to the wiki page, my ini file is correct.  Is the syntax on the wiki page correct - should the ini not have {feature}.{loglevel}={boolean} rather than what is has ({feature}={boolean})?

**Comment by Ezeer** [comment]
@pljones thank you , looks correct !

Perhaps an admin right to open/read  a .ini file on win10 ?

**Comment by pljones** [comment]
The whole point of %APPDATA% is that the associate application can update the files.  Win10 does not put restrictions on files based on extension, only based on location, as far as I'm aware.

**Comment by Ezeer** [comment]
duno .
But found an article with Win7 : 
http://www.sevenforums.com/general-discussion/204784-access-denied-when-editing-ini-files.html

Should be tested on win7 and 8 also ...
^^

**Comment by Ezeer** [comment]
Perhaps create a new issue for that particular .ini case ?

**Comment by pljones** [comment]
> program folder (in C:\Program Files"

only admins can edit under Program Files on Win 7 and greater.  It's to stop file hi-jacking.

**Comment by Ezeer** [comment]
Ok.
But at code level , there is some restrictions also when opening files .
Perhaps the file was not opened and the logger used random values ...

**Comment by Ezeer** [comment]
But i'd better read again your log ...
thank you peter

**Comment by pljones** [comment]
> qt.core.logging.WARNING:  Ignoring malformed logging rule: 'jt.Standalone.PluginFinder=false#VSTpluginsscanning'QLoggingSettingsParser::setContent qloggingregistry.cpp226

That doesn't look random.  It looks like it's not liking whatever is meant to be between "false" and the "#" mark.

**Comment by pljones** [comment]
Yes, if I delete everything from "#" to the end of the line, it's happy.

**Comment by Ezeer** [comment]
working now ?

**Comment by pljones** [comment]
The default file written on first run needs to be fixed.

**Comment by Ezeer** [comment]
" And the wiki needs to be updated. "
At wich level ? FAQ ?

**Comment by pljones** [comment]
The wiki had the content of the default file.

The content of the default file was wrong.

Thus the wiki was also wrong because it was the same as the file that was wrong.

**Comment by Ezeer** [comment]
What ?
.... lol
Aaah... yes the user's guide is the page 2 on our Wiki .
So you are talking about the pictures on it ?
Thank you pljones , if elieser changes the format/content , i will make new screenshots .
I have good ?
^^

**Comment by Ezeer** [comment]
Meanwhile we have a new collaborator ( @jonjamcam  ) that is now the maintainer of our help system .
You can talk to him directly now for that kind of detail if you want or need to .

**Comment by Ezeer** [comment]
pljones finally helped me to understand ( total recall ) where the problem started with the logger.
He has located the *# blah blah that * thing that breaks the logging system .
Now i remember that the first screenshot i made for the user's guide was different from the actual ,
there wasn't additional comments AND IT WAS WORKING FINE !
@elieserdejesus : try to remove the additional comments in your code , i think that will fix the logger problem .

thx pljones ;)

**Comment by elieserdejesus** [comment]
Comments removed from logging.ini file!
pljones, thanks for your time and sorry for this mess, in general comments are just comments, but the log parser in Qt disagree :)

and about the multiout problem in Kontakt? You still have the problem?

**Comment by Ezeer** [comment]
I vote to have pljones in the support team .
( Also he supports ninjamers for years !)
If he wants , there is a badge here : 
![official support team](https://cloud.githubusercontent.com/assets/1283808/10866255/c9875120-8026-11e5-8192-e91297f1de41.jpg)

An other way to say ... thank you !
;)

**Comment by pljones** [comment]
Sorry I couldn't get back onto this earlier.

I've just logged a new bug -- standalone won't start up, looks like a bad choice of ASIO device.

**Comment by elieserdejesus** [comment]
Can you post your log file pljones?

**Comment by Ezeer** [comment]
>Ezee, the multiout feature was working in last builds. I change the code to solve a problem in VST chain when using plugins like guitar rig, amplitube, etc. Now this chain problem is solved but I bug something in multi-out. 

![ob_1d39c5_langfr-330px-back-to-the-future-svg](https://cloud.githubusercontent.com/assets/1283808/11021922/633059b8-8651-11e5-859b-cb3507fc4563.png)

**Comment by Ezeer** [comment]
Can you show me where to start to look with multi-out in the code elieser please ?
The plugin chain code fix is here : https://github.com/elieserdejesus/JamTaba/commit/13600d8fab5eff353a57090367021d415a6eb994

**Comment by elieserdejesus** [comment]
Ezee, the problem is in VstPlugin::process and AudioNode::processReplacing

I think AudioNode is the problem.
But, the big problem is: multi out works like a charm here! So I can't see the problems reported, I'm blind :)

**Comment by elieserdejesus** [comment]
@Ezeer and @jonjamcam  I test Kontakt 5 and Addictive Drums multi-out here, no problems. I test in Jamtaba 32 bits and 64 bits, working 100%.
Please test the last Release Candidate in your machines focusing in this multi-out plugins issue. I don't have this issue in any plugin, so for me it's impossible to fix a bug if I don't see the bug. Please help me to confirm if this is an issue  or not.

**Comment by jonjamcam** [comment]
I tested ADM which is a 13out plugin with no problems in Jamtaba. I will test kontakt and report ASAP

**Comment by jonjamcam** [comment]
ohh I found something in ADM........Once you start it it works ok sending audio to ch 1,2 which jamtaba routes correctly.

But once you start playing with the outputs and try to go back to the original configuration it's impossible. Eve if I select channel 1 as output....it doesnt respond. emoving the plugin and load it again solved the issue

**Comment by elieserdejesus** [comment]
Yes Jon, the multi-out is not really multi, but you can hear the main stereo output without problems.

**Comment by Ezeer** [comment]
About the standalone ?
I will try the plugin later and report .

**Comment by jonjamcam** [comment]
Testing Kontakt 5...no audio problems...no MIDI problems (like kontakt 4 has). I think Jamtaba should not support kontak 4 or earlier to avoid more problems.

**Comment by elieserdejesus** [comment]
Nice Jon, Kontakt 5 is 100% here, I'm a big fan :)
