### ISSUE TITLE
Pre-release v2.0.18

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#622]
@jonjamcam , @qulf , @AndyMcProducer , can you help testing new Jamtaba in your machines and DAWs, please?

[https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.18-beta](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.18-beta)

Andy, I fixed the problem with backspace and DELETE in Cubase. Teste in Cubase 8.

**Comment by jonjamcam** [comment]
@elieserdejesus Working OK so far (except for the translations).

And the manual for 2.0.18 is updated!

**Comment by qulf** [comment]
my polish wersion works ok but when i instal i get some problem . i send picture via facebok. i dont know if i can add photo here

**Comment by elieserdejesus** [comment]
@qulf , you can post pictures here too, just drag and drop. 
About your first picture: to avoid the windows message we need "sign" the executable to confirm we are not develping a malicious software. But this costs money, is necessary buy a digital certificate. This is not an option for this project.

About the second picture: I think the messages in the Midi tool window are not checked to be translatable, I will check this.

**Comment by elieserdejesus** [comment]
@qulf , the Midi tool translations are empty:
![image](https://cloud.githubusercontent.com/assets/1012741/21080665/1f4957ba-bf9c-11e6-888f-30b0c16cb4bb.png)

Can you translate these messages, please?

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , @MagnusDrumsTrumpet , @DoublebassOO, @qulf , @NakajimaYusuke, @takeshitaleo , can you help translating some texts for the new Jamtaba version?

The TS files in this repository are updated with the new untranslated texts.

Thanks in advance!

**Comment by jonjamcam** [comment]
es_CL locale updated in https://github.com/elieserdejesus/JamTaba/pull/628

**Comment by MagnusDrumsTrumpet** [comment]
hey eli did you get the german translate update from m e in github? i am never sure with that Git_rakle
greetings from Mag 

    Elieser Ademir de Jesus <notifications@github.com> schrieb am 17:24 Sonntag, 11.Dezember 2016:
 

 Hi @jonjamcam , @MagnusDrumsTrumpet , @DoublebassOO, @qulf , @NakajimaYusuke, @takeshitaleo , can you help translating some texts for the new Jamtaba version?The TS files in this repository are updated with the new untranslated texts.Thanks in advance!—

**Comment by elieserdejesus** [comment]
Yes @MagnusDrumsTrumpet , I merged your translation, works like a charm. Thanks!

**Comment by elieserdejesus** [comment]
Wiki updated, thanks @jonjamcam !

**Comment by elieserdejesus** [comment]
@jonjamcam , I see a message from you about release new Jamtaba this weekend. I'm working in VST PLugin for Mac, so maybe in the next weekend we can release a xmas version including a nice gift for mac users. People can use Jamtaba inside Logic or Garage Band, for example

**Comment by jonjamcam** [comment]
Great news! Xmas release, eh? :D

**Comment by elieserdejesus** [comment]
Jamtaba v2.0.18 released, thanks guys!
