### ISSUE TITLE
"Yes/NO" and "Copy/copy link location/Select all" not translatable

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#635]
![image](https://cloud.githubusercontent.com/assets/15310433/21171168/cbee9242-c1a8-11e6-9a5c-1ba9083b9a48.png)

![image](https://cloud.githubusercontent.com/assets/15310433/21171208/feb7b974-c1a8-11e6-8ce4-f979d3e48da9.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the code to translate Qt stuff. Unfortunally **Qt base** files are not translated for Portuguese and Spanish. Works ok for the other supported languages in Jamtaba.

I'm planning a contribution to Qt community (and to Jamtaba) translating Qt files to Portuguese. Maybe you can contribute too translating for Spanish. These are the [guidelines](https://wiki.qt.io/Qt_Localization).

**Comment by jonjamcam** [comment]
>Maybe you can contribute too translating for Spanish

Yeah! I'll check it out.
