### ISSUE TITLE
Accessibility ( for blind musicians )

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#64]
It is something that i wanted to do with ninjam client , but was too complicated because of its interface.
Perhaps here we could create a pseudo console to allow a blind user to use Jamtaba ?
Blind people use texttospeech and speech recognition to hear console output and to call functions .

Commands could be : 
_Open preference
_Select tab audio
_Set volume , Pan etc ...
_Get volume on track
etc ...

I am ok to work on that ( **W**onderful **w**orld )
![1363818032_ray charles](https://cloud.githubusercontent.com/assets/1283808/10838150/4dbcdf0c-7ec2-11e5-889b-1ec7532229dc.jpg)
What's up Ray
![k06-11-28-23](https://cloud.githubusercontent.com/assets/1283808/10838277/17e718e6-7ec4-11e5-86ef-19e2f62ac053.JPG)
                                                  ?  ^^

**Comment by elieserdejesus** [comment]
Ezee, I'm shure we don't need a simplified user interface to support screen readers. In general make the user interface accessible is a question of add labels/captions in UI controls, hotkeys and be more carefull with TAB order, because tab is very used to navigate. 

This is the approach used today in websites and modern accessible software. Qt has a accessibility module, maybe can help [http://doc.qt.io/qt-5/accessible.html](http://doc.qt.io/qt-5/accessible.html)

**Comment by Ezeer** [comment]
thank you , i've started to read it .

**Comment by Ezeer** [comment]
Very interesting documentation !
I noticed a good point for Jamtaba right now for accessibility with Qt : 
"  If you want your application to support accessibility, you will need to consider the following:

Qt already implements accessibility for its own widgets. We therefore recommend that you use Qt widgets where possible.
"
Nice that there is native solutions already .
In that project i think i will have to find blind testers in order to make it enjoyable for dem .
But first use accessibilty in each widget to see how Jamtaba will react to MSAA

A good article reporting experience with Accessibility with Qt 5 by a dev here : 
https://mayaposch.wordpress.com/2013/02/15/msaa-and-ia2-accessibility-in-qt/

**Comment by elieserdejesus** [comment]
Nice article!

**Comment by Ezeer** [comment]
So dear boss , could you start that project by doing  : 
>Then, when deploying the application make sure you have a folder named ‘accessible’ in your application’s folder with the executable and the file ‘qtaccessiblewidgets.dll’ (or comparable .so) in that accessible folder. This will cause the Qt 5 application to load the accessibility features for its widgets and enables MSAA and IA2.

And i will start to implement the basic :

**Comment by Ezeer** [comment]
So i'm gonna be the first tester for that new feature using NVDA that is the free alternative to screen readers . Can be downloaded here : http://www.nvaccess.org/download/

**Comment by Ezeer** [comment]
My first test captured by a camera on youtube ( dirty quality sorry ...) : 
https://www.youtube.com/watch?v=VxRs34HLN9c&feature=youtu.be

**Comment by elieserdejesus** [comment]
Ezee, I watch the video. Nice music in background, hehe :)
So, acessibility it's working whithout changes? Or you add labels in the Jamtaba controls in QtEditor?

**Comment by Ezeer** [comment]
The background music is from a friend's band .
These guys are very good musicians !
^^
**So, acessibility it's working whithout changes?**
Yes ! I just launched NVDA + Jamtaba  .

But i expect the accessibility is working because the Qtdll is in the same folder than 
the compiled .exe . ( ‘qtaccessiblewidgets.dll’ )

I will try with your last release , just to be sure ...

**Comment by Ezeer** [comment]
Just tried the 2.0.5 beta with NVDA , working fine .

I have notived that when i am in a room box ( at selection time ) , when the mouse pointer is on a
musician's name , that would be good to hear " Ninjammer " before his name.
That would help a lot in fact .

**Comment by elieserdejesus** [comment]
Nice news!  
I think we can override some acessibility method and return a "Ninjammer [the name]", but I'm never work with this. Please add a issue for this enhancement.

**Comment by Ezeer** [comment]
ok . Hey , u forgot again to change the version number on the window .
;)

**Comment by Ezeer** [comment]
I just had an interview using tweeter with a famous blind musician , a really cool and talented guy .
Discover him on Virgin youtube channel : 
https://www.youtube.com/watch?feature=player_embedded&v=Y8bsw3p_6dY&app=desktop

He gaves me the permission to share our interview , i made screenshots ( sorry if you are blind , i'm noob with tweeter and just couldn't copy the chat ... ) : 

![capture d ecran 2015-11-01 17 23 07](https://cloud.githubusercontent.com/assets/1283808/10869987/da5f46c6-80bf-11e5-94ea-a20bcdcac744.png)
![capture d ecran 2015-11-01 17 23 24](https://cloud.githubusercontent.com/assets/1283808/10869988/e2fb046e-80bf-11e5-97c9-b621b7234df8.png)
![capture d ecran 2015-11-01 17 23 44](https://cloud.githubusercontent.com/assets/1283808/10869989/ea797158-80bf-11e5-9a7d-1f6938e1352a.png)
![capture d ecran 2015-11-01 17 24 00](https://cloud.githubusercontent.com/assets/1283808/10869992/f4f7c10c-80bf-11e5-9af1-44f0346a93d7.png)
![capture d ecran 2015-11-01 17 24 29](https://cloud.githubusercontent.com/assets/1283808/10869996/fd1fa552-80bf-11e5-9806-51a75c6b9a1f.png)
![capture d ecran 2015-11-01 17 24 52](https://cloud.githubusercontent.com/assets/1283808/10869999/05b39e44-80c0-11e5-8e19-6186b3e270e0.png)
![capture d ecran 2015-11-01 17 25 11](https://cloud.githubusercontent.com/assets/1283808/10870000/0d039faa-80c0-11e5-91dc-5df4aa86ad4b.png)
![capture d ecran 2015-11-01 17 25 34](https://cloud.githubusercontent.com/assets/1283808/10870009/5d9f72ea-80c0-11e5-9fd4-a8d4d5bc696d.png)
![capture d ecran 2015-11-01 17 25 59](https://cloud.githubusercontent.com/assets/1283808/10870012/66270f18-80c0-11e5-8387-9a3b52676423.png)

**Comment by elieserdejesus** [comment]
Wowww, I have no words Ezee! This is great!

**Comment by elieserdejesus** [comment]
closing by inactivity
