### ISSUE TITLE
Tooltip duplicate country information in maps

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#641]
We could use the tooltip in the maps to display other type of information. Now it's showing country names:

![image](https://cloud.githubusercontent.com/assets/15310433/21411499/acce23e4-c7c7-11e6-95e0-6bfe12d6df75.png)

I was thinking a better use for this function like local city (if possible as in ninbot, for example) or we could show a picture of the participant. Just some ideas to avoid duplicate information.

**Comment by jonjamcam** [comment]
I find city information for geolocation purposes is not very reliable ATM. Another idea could be to show the IP when pointing to the little dot in the mouse.

**Comment by jonjamcam** [comment]
>  I think the ninjam creators (10 years ago) was trying to compensate a fragile login scheme with some way to identify users (by IP).

I agree. I used reaninjam for about 5 years so I got really "domesticated" in this regard. Now I've been using Jamtaba for 1 Year+ and I can see this kind of details that can be improved. 

> Some users are using a small picture in ninbot account, and is possible grab this image. Another source is facebook accounte,

I don't use Facebook, but I understand the point. Last night AndyMc and I were having this discussion. He points out that a Facebook integration is an important step forward for the community. ATM ninbot is not FB friendly, but maybe Jamtaba could fill that GAP.

 He has also this idea of a phone app that notifies you when someone connects to a server. He told me that he would jam a lot more if he knew some ninjamers are actually connected.

Finally I wish you and your family a happy new year, Elieser. I expect it to be very exciting and I wish you all the best, man.

**Comment by elieserdejesus** [comment]
> ... Facebook integration is an important step forward for the community.

I agree, but I'm not shure how "fill the gap" at moment. It's need some planning. 

 ***
> a phone app that notifies you when someone connects to a server.

I agree too. An email notification can be usefull too.

***
> Finally I wish you and your family a happy new year, Elieser. I expect it to be very exciting and I wish you all the best, man.

Thanks Jon, same for you! I wish the best year for you! Have a nice year!!!

**Comment by jonjamcam** [comment]
In the interest to update this old issue and understanding this info is public I think the city location, although not that precise could be a nice little gadget to show when hovering the little dot on the map.

![image](https://user-images.githubusercontent.com/15310433/81797852-4ab0b780-94dd-11ea-8099-fae94688b81b.png)

**Comment by jonjamcam** [comment]
Not a priority... closing
