### ISSUE TITLE
New Wave Drawing issues

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#644]
1.- The selection check mark is not being updated for both pixelated types ONLY. Non-pixelated work fine.

![image](https://cloud.githubusercontent.com/assets/15310433/21483077/91356880-cb5b-11e6-8d23-88dfd3244352.png)

2.- No buffer % and the circle looks a bit big in size :D

![image](https://cloud.githubusercontent.com/assets/15310433/21483170/b1555ee4-cb5c-11e6-902a-4036bbc71e97.png)

3.- Menu Selection check is gone when restarting (the selected mode before relaunch is kept OK)

![image](https://cloud.githubusercontent.com/assets/15310433/21483300/7bae1fd6-cb5e-11e6-9594-52838a3414c1.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , about the item 2: I removed the % text, I think the graphic only feedback is more clean and communicate the same info.

**Comment by elieserdejesus** [comment]
@jonjamcam , I choosed another approach: I dropped the menu and added 4 small buttons:
![image](https://cloud.githubusercontent.com/assets/1012741/21485426/9c763268-cb8a-11e6-856e-b4162f1d66d3.png)

**Comment by jonjamcam** [comment]
The buttons are much better. Now when you listen to different rooms a previously selected room does not go back to "bright" state again when not listening:

![image](https://cloud.githubusercontent.com/assets/15310433/21486989/80963e5e-cb9d-11e6-9b38-2f4fd916e47e.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , my bad, it´s fixed now https://github.com/elieserdejesus/JamTaba/commit/55dd5f4270c67ac2e24ec2ef16e68ab8ab0fa141
