### ISSUE TITLE
blur intensity

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#653]
I'm having a hard time starring at the blurred rooms. Maybe too much effect intensity?

Original (**p.fillRect(rect(), QColor(0, 0, 0, 140));**):

![image](https://cloud.githubusercontent.com/assets/15310433/21506444/04547dbc-cc4f-11e6-9b3a-526144d6578a.png)

lighter blur suggested (**p.fillRect(rect(), QColor(0, 0, 0, 100));**):

![image](https://cloud.githubusercontent.com/assets/15310433/21506463/2afe48da-cc4f-11e6-8eaa-f1bec600ee0f.png)

what do you think @elieserdejesus ?

blur = 100 still has the desired effect IMO:

![image](https://cloud.githubusercontent.com/assets/15310433/21506558/b65b5ada-cc4f-11e6-8691-0d41805c8766.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I tested other "blur values" too, the big problem is Flat and Rounded theme. The value 100 works nice in Black and Orange, but the constrast is not enough in Flat and Rounded.

**Comment by jonjamcam** [comment]
Sure. Closing...
