### ISSUE TITLE
muted audio when about to sync with Reaper (maybe other D.A.W too?)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#656]
When you are ready to sync with reaper (but not yet pressed play) all audio is muted.

![image](https://cloud.githubusercontent.com/assets/15310433/21563438/4e237380-ce61-11e6-83dc-f179b75797f8.png)

 And because Jamtaba is normally in the master channel, you can't do anything about it. It is inconvenient if you need to hear audio coming from a line input for example.

@elieserdejesus Is it possible for Jamtaba to allow incoming audio to be monitored at this stage?

**Comment by elieserdejesus** [comment]
It's possible @jonjamcam , I need check the code to be 100% shure, but I think is not complicated allow incoming audio only when waiting for host sync.

**Comment by jonjamcam** [comment]
Cool! thx!

**Comment by elieserdejesus** [comment]
@jonjamcam , this is the VST plugin with this feature (allow input while waiting for host sync start) implemented. Can you test ?
[JamtabaVST.zip](https://github.com/elieserdejesus/JamTaba/files/721596/JamtabaVST.zip)

**Comment by jonjamcam** [comment]
Working OK in Reaper here.
