### ISSUE TITLE
[OSX AU] Return Key not working in chat

### ISSUE THREAD

**Issue by vector21** [elieserdejesus/JamTaba#657]
Enter Key (Return Key) is not working as expected. At least on my Macbook (big return key over right shift key).

Works only when you hit "CMD + Enter" ...

Is this intentional? That might confuse users!! Like it confused me! :-)

But anyway... Very nice job on the AU port!!! Everything else works pretty much like as in the PC version.

**Comment by elieserdejesus** [comment]
@vector21 , thanks for helping testing the AU plugin.

You tested in Reaper only?

What is your OSX version? Mavericks? Yosemite? El Captain?

**Comment by vector21** [comment]
Yes I only have Reaper installed on my Mac - so I only cant test it with it.

OSX is 10.11.4 El Captain.

**Comment by elieserdejesus** [comment]
Hi @vector21 , can you help us testing the new beta? If yes [this is the link](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.19-beta)

Now JamTaba Standalone can load your AU plugins, and JamTaba can be used as an Audio Plugin too.

**Comment by vector21** [comment]
Link is not working... :-)

**Comment by elieserdejesus** [comment]
Hi @vector21 , this is the all releases link: [https://github.com/elieserdejesus/JamTaba/releases](https://github.com/elieserdejesus/JamTaba/releases)

**Comment by vector21** [comment]
Chat works as expected now! Thanks for fixing 👍

**Comment by elieserdejesus** [comment]
thanks @vector21 !
