### ISSUE TITLE
Add "sync server to D.A.W. BPM" option for VST/AU

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#658]
Normally you would want to sync your D.A.W. to the server's BPM, but there's times where you need the **server** to change to your D.A.W.'s BPM. I'm thinking of a simple way to do this using the current dialog box.

For example if Reaper's BPM is 100 and the server BPM is 120 and you click SYNC to REAPER button, this would be the result:

![image](https://cloud.githubusercontent.com/assets/15310433/21578688/d8e60c14-cf68-11e6-8ac9-1146da28e756.png)

**Comment by jonjamcam** [comment]
@elieserdejesus I think this feature could have a problem when implememented that could be very annoying: some servers use very high voting threshold and if not enough votes, the you'll have to wait even minutes. This is not a good thing when you are in a "standby state" waiting for the BPM change to sync. Additionally if vote time expires, you'll need another dialog to explain why the tempo can't be changed.

I think we should drop it. what do you think?

**Comment by elieserdejesus** [comment]
> I think we should drop it. what do you think?

I agree @jonjamcam. If I remember correctly the sync button is automatically unchecked when server bpm is changed, so I think a new click in sync button is enough to re-sync.
