### ISSUE TITLE
Ice theme

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#662]
Remember @elieserdejesus we talked about a "cold" / "ice blue" theme back then....

> create a new "Cold" theme in future.

 (https://github.com/elieserdejesus/JamTaba/issues/450#issuecomment-232773159)

![image](https://cloud.githubusercontent.com/assets/15310433/21821612/fe76e132-d752-11e6-998a-a4c0709b6e04.png)

or is there any other idea you have in mind? I'm pretty bad at choosing palettes, but if you start an idea I'd be glad to finish the details :D

**Comment by elieserdejesus** [comment]
@jonjamcam , I tried a first attempt. Please feel free to change.


The theme files, just unzip and drop in your AppData/Roamming folder: [Ice.zip](https://github.com/elieserdejesus/JamTaba/files/697738/Ice.zip)

![image](https://cloud.githubusercontent.com/assets/1012741/21830524/6034f20c-d784-11e6-9bfc-91463c97a4b7.png)

**Comment by jonjamcam** [comment]
great! I'm working on it.

**Comment by jonjamcam** [comment]
Halfway into completing the details. For the moment buttons, hovers, mainwindow and ninjamwindow are mostly finished.

[Ice_2.rar.txt](https://github.com/elieserdejesus/JamTaba/files/699867/Ice_2.rar.txt)

**Comment by elieserdejesus** [comment]
Nice @jonjamcam !
I'm not 100% shure of background color in local tracks. Can you try a darker blue, or another "ice/cold/iceberg" tone?

**Comment by jonjamcam** [comment]
like this?

![image](https://cloud.githubusercontent.com/assets/15310433/21866205/f7388788-d827-11e6-9ba7-d408fc3bf2cc.png)

**Comment by jonjamcam** [comment]
@elieserdejesus It's complete now. Let's give it a little time to digest. Probably there are some color choices that will change in the future.

[Ice_4.rar.txt](https://github.com/elieserdejesus/JamTaba/files/700522/Ice_4.rar.txt)
