### ISSUE TITLE
Limit autotranslate chat function only to remote users text or different language (if possible)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#665]
It looks like the autotranslate chat function is sending all chat message to google including local ones (which should not translate) in this video AndyMc posted:

https://youtu.be/hpcN5TiQ6WI?t=5191

at 1:26:40, the function is enabled and it keeps going for 1 hour. These are lots of words been sent to google and I fear it could be considered abuse and blocked in the future.

**Comment by elieserdejesus** [comment]
> chat function is sending all chat message to google including local ones 

@jonjamcam , by **local ones** are you saying the messages typed by AndyMc? I can't see these messages in the video. 

>  I fear it could be considered abuse and blocked in the future

Some idea to minimize the problem?

**Comment by jonjamcam** [comment]
>local ones are you saying the messages typed by AndyMc? I can't see these messages in the video.

That's right. Andy's messages appear in _italics_ too when using autotranslate:

![image](https://cloud.githubusercontent.com/assets/15310433/21988548/6db10acc-dbe6-11e6-8c19-15bd0591a426.png)

> Some idea to minimize the problem?

The only practical solution I see is to set a timer for the autotranslate function. I think half an hour is pretty much enough. If someone wants more time, the button has to be pressed again for another 30 mins (not the best solution, but will cut the excess)

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm thinking about this issue again:

**I think the easy solution is just disable auto translation for local user messages. **

Except when we are testing, **can you imagine scenarios where auto translate can be usefull for local user messages**? 

I'm missing something?

**Comment by jonjamcam** [comment]
>can you imagine scenarios where auto translate can be usefull for local user messages?

Not at all

> I think the easy solution is just disable auto translation for local user messages.

I agee
