### ISSUE TITLE
modified windows performance monitor

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#666]
@elieserdejesus I was doing some changes in the code of the abandoned CPU-MEM meter. I don't know if you plan to include it again in the future, but in any case these are the changes:

1-. The CPU meter was showing the current process usage. I changed the code to show the system total usage.
2.- the MEM meter was showing the current proces usage. I changed it to show total memory usage in %.

I tested it in XP working fine and these changes makes it very useful (for me at least) so I can see any overloading problems easily now.

It could be a good idea if the MEM meter appears when exceeded 90% for example so it's not there all the time. A visual warning of low memory is critical, specially for 32bit systems or the use of large kontakt libraries.

I pushed the code to a branch of my fork (https://github.com/jonjamcam/JamTaba/tree/Win-Monitor . See this commit for the details: https://github.com/jonjamcam/JamTaba/commit/e04b10f522267067cbf71e7eba18b24152fb47e9). If you think it's an improvement worth the try, I can create the corresponding PR.

The modified code for the CPU meter was adapted from here:

http://stackoverflow.com/questions/23143693/retrieving-cpu-load-percent-total-in-windows-with-c

NOTE: Originally the memory monitor was named **getFreeMemmory** because I wanted to monitor the available memory, but later I changed my mind and thought it's better to show the total memory used in %. Probably I should change the name of the function. EDIT: func name corrected :D

Another thing I noticed is the memory shows different % value from the windows task manager. the function gets the percentage dividing the same values shown by the task manager, so I don't know why the value is different. Task manager value of memory usage is lower.

![image](https://cloud.githubusercontent.com/assets/15310433/21972095/b0e7c8a4-db95-11e6-80fe-eb5ec9dc47cf.png)

but if you do the math, (3072/4042) * 100 = 76%

**Comment by elieserdejesus** [comment]
Hi @jonjamcam 
> I noticed is the memory shows different % value from the windows task manager.

I remember this was the big problem. The windows functions to get system resources usage are not accurated. In windows XP the result is good, but in Win 7 and later the result is very poor. If I remember correctly the windows functions are not considering multi core processors, so the filnal numbers are very inaccurated.

Can you test the same code in win 7 or another non-XP windows?

**Comment by jonjamcam** [comment]
>Can you test the same code in win 7 or another non-XP windows?

Yes. The image above was taken from win7 (dual core system). The readings are very close to the ones from the windows task manager, except the refresh rate is faster in Jamtaba.

 Testing in win10 laptop (i5, 4 cores), the results are similar (although the refresh rate of the task manager is very slow, so it's hard to compare accurately)

![image](https://cloud.githubusercontent.com/assets/15310433/21988195/308b3b46-dbe5-11e6-9d64-3ab66263e736.png)

![image](https://cloud.githubusercontent.com/assets/15310433/21988215/403a7048-dbe5-11e6-90ed-21b0764850fe.png)

![image](https://cloud.githubusercontent.com/assets/15310433/21988240/5a74def8-dbe5-11e6-84b0-d744cae439b9.png)

![image](https://cloud.githubusercontent.com/assets/15310433/21988266/6b30c180-dbe5-11e6-91b7-74ce4709c43e.png)

I opened PR https://github.com/elieserdejesus/JamTaba/pull/667  so you can test in your system

**Comment by elieserdejesus** [comment]
nice @jonjamcam , I will test soon.
