### ISSUE TITLE
Some ideas for Local Tracks enhancement

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#669]
I noticed a smaller size for the Full View Mode starting in 2.0.19:

![image](https://cloud.githubusercontent.com/assets/15310433/22047291/dd6eeaa4-dd04-11e6-924a-f55fc926ada7.png)

 This new size is great, specially for the vst plugin, but now the "Full View layout" will have very little space for the level meters:

![image](https://cloud.githubusercontent.com/assets/15310433/22047354/4e57a116-dd05-11e6-90f1-deacfcb21b37.png)

To solve this problem we could make the "Mini Mode Layout" also available in the Full View Mode, specifically for the vst plugin as it's not resizable. The standalone can be maximized, so no issue there.

![image](https://cloud.githubusercontent.com/assets/15310433/22047575/a7243ad8-dd06-11e6-9905-458b7c568d24.png)

Another problem is we'll have now less space for remote tracks (specially when the room is full), so we can save a lot of space if a Wide/Narrow button is available for Local Tracks (both vst and standalone).

 There's some unused space here to put a little button for example:

![image](https://cloud.githubusercontent.com/assets/15310433/22047421/ba3063e6-dd05-11e6-85d9-0b6be11a4d34.png)

***
Related, but off topic, @elieserdejesus what do you think about having a third view option "_Big screen Mode_" or "_Extended View Mode_"for the vst plugin with resolution in the range of 1280x720, 1360x790 or maybe even 1920 × 1080?

I'm thinking about Big LCD TV resolutions. I can test here in two big screen TV's we have at home.

**Comment by elieserdejesus** [comment]
@jonjamcam 
> what do you think about having a third view option

I'm in the opposite direction :)  I was thinking in remove these "Mini and Full" view options. I think these 2 options are confusing, no other software use these options and users are not used. The Full Screen option is clear and other software are using, but Mini and Full View are not clear enough in my opition. If you maximize JT window and switch from Full to Mini View you will see the effect is minimum. 

Some ideas:
1 - Drop Mini mode
2 - put the meters along side with level fader
3- VST/AU PLugin window start with small size (current mini mode size), but will be resizable

**Comment by jonjamcam** [comment]
> Some ideas:
1 - Drop Mini mode
2 - put the meters along side with level fader
3- VST/AU PLugin window start with small size (current mini mode size), but will be resizable

Yeah. Much better. The resizeable vst is the best solution.

**Comment by jonjamcam** [comment]
> put the meters along side with level fader

I was wrong about the Vst Plugin and the meters. They look OK in this new window size, no "little meter" problem because the plugin has no racks nor input box.
