### ISSUE TITLE
Joystick support ( to interact with the UI )

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#67]
That could sound ugly , but that is a nice (free) way to use a cheap remote controler for the end user.
When i'm at the drum , i am at two meters from the mouse and keyboard .
I actually use a sidewinder joystick usb to control cubase 5 , mapping Buttons to keystroke ( shortcuts..)
using JoytoKey : http://joytokey.net/en/

We could code that in Jamtaba , perhaps with a Qt module ( if exists ) or third party lib .
I've found that github project that seem good : https://github.com/ThemsAllTook/libstem_gamepad

**Comment by elieserdejesus** [comment]
Cool feature Ezee! I think this is not a priority, but is a cool thing.
Actually you remember me from other drummers talking about the same difficulties.
For Jamtaba v 2.99.145 relese we can think in a customizable hotkeys, maybe using midi too. Drumers can configure F1 key to say "Hi, or hello" in chat, like many multiplayer games do. But the drummer need press a key in the keyboard, and many times this is not possible as you know. If the drummer is using drum pads he/she can configure a drum pad or a pedal switch to do something interesting in jamtaba.

Other a ninjamer ask me about a MIDI switch to enable/disable the metronome. This is a common need, so we can think in something for future releases.

When I start thinking about these things my mind always reach the same conclusion: users need a fully customizable software. If we can customize everything so everybody is happy. But fully customization is very complex, so let's do bit a bit :)

**Comment by Ezeer** [comment]
" For Jamtaba v 2.99.145  "
ah ah ah ... you are as crazy as me  , lol !

>"But the drummer need press a key in the keyboard, and many times this is not possible as you know. If the drummer is using drum pads he/she can configure a drum pad or a pedal switch to do something interesting in jamtaba."

That is were accessibility joins : A headphone+a mic + texttospeech + voice Recognition = your drummer can chat !
eh eh

But : 
>" so let's do bit a bit :) "

Of course !
:)

**Comment by elieserdejesus** [comment]
Ezee, a switch can be a pedal (on/off) like sustain pedals for keyboards. 
But if users can map Jamtaba features to MIDI controls drummers can use something like this to start/stop, mute/unmute, say predefined phases in chat, etc:
![image](https://cloud.githubusercontent.com/assets/1012741/10853259/4a920bcc-7f1c-11e5-8a54-066e22279021.png)

**Comment by Ezeer** [comment]
Ok , but that is a feature for an other thread , wait .... this one #13 
Here it is for guys that don't have a midi device for exemple .
But it is true that today we can find midi controlers at the the price of a good joystick .
But again , a simle gamepad cost 12 $ in that case : http://www.newegg.com/Product/Product.aspx?Item=9SIA7252NK4658
![a725_130709437934007988gfkqdqude6](https://cloud.githubusercontent.com/assets/1283808/10853987/620542b6-7f39-11e5-89e3-dccec3ff0ba5.jpg)

At that price there is no midi controler .
There is a midi controler at that price ?
^^

**Comment by elieserdejesus** [comment]
$2 is not cheap enough, let's search in some chinese site, hehe.

**Comment by Ezeer** [comment]
![soccer-goal-brazil-flag-300x297](https://cloud.githubusercontent.com/assets/1283808/10854845/ae38f1fa-7f3e-11e5-9e5d-344bcef8314a.jpg)

**Comment by Ezeer** [comment]
I have created a branch for the Joystick , but i won't pull it on master elieser .
It is there just to allow you to play with it etc ...
I use SDL here for the joystick , are provided in the branch the win32 and win64 libs + headers

My log is : 
>default.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
##default.DEBUG:  new Joystick 0x1b68e228  in joyctrl.cpp 14##
##default.DEBUG:  idx: 0, name: S (axes: 3, buttons: 8, hats: 0)  in joyctrl.cpp 75##
jt.Core.INFO:  Creating plugin finder...
jt.Core.INFO:  Creating midi driver...
jt.Core.INFO:  Creating audio driver...
jt.Core.INFO:  Creating roomStreamer ...
jt.Core.INFO:  Connecting in Jamtaba server...
default.INFO:  "Starting Jamtaba 2.0.5 Standalone (i386) running on Windows XP (i386)"
jt.Core.DEBUG:  StandaloneMainController destructor!  in StandAloneMainController.cpp 287
##jt.Core.DEBUG:  Joystick destroyed!  in MainController.cpp 744##
jt.Core.DEBUG:  MainController destrutor!  in MainController.cpp 745
jt.Core.DEBUG:  Stopping MainController...  in MainController.cpp 921
jt.Core.DEBUG:  audio and midi drivers released  in MainController.cpp 930
jt.Core.DEBUG:  disconnecting from login server...  in MainController.cpp 941
jt.Core.DEBUG:  main controller stopped!  in MainController.cpp 751
jt.Core.DEBUG:  clearing tracksNodes...  in MainController.cpp 753
jt.Core.DEBUG:  clearing tracksNodes done!  in MainController.cpp 764
jt.Core.DEBUG:  MainController destructor finished!  in MainController.cpp 766
default.WARNING:  QWaitCondition: Destroyed while threads are still waitingQWaitCondition::~QWaitCondition() qwaitcondition_win.cpp158
default.WARNING:  QWaitCondition: Destroyed while threads are still waitingQWaitCondition::~QWaitCondition() qwaitcondition_win.cpp158

**Comment by elieserdejesus** [comment]
This is cool!
Today I detect a problem in the log scheme. I was playing with the midi CC
stuff and change the logging.ini to see some midi log messages, but nothing.
The problem is: I have Jamtaba installed in my machine, so when I run my
dev version the code is checking if a logging.ini file exists in
...User/AppData/Local/Jamtaba 2. This file exists, so it's used to controll
the logging stuff. This is good for users, but is bad for us, because now
we change the logging.ini in your dev machines and this file is not used by
Jamtaba.

I'm without ideas about how to solve this at moment, a tired brain is not
usefull :)

Please tell me if you have some cool solution for this.

Elieser

Em quinta-feira, 5 de novembro de 2015, Ezee <notifications@github.com>
escreveu:

**Comment by Ezeer** [comment]
A magic number ? A GUID ?
You would write it first in logging.ini , different if it was produced by a dev version or by a public version.
Perhaps start also to really work with version  check in your sources , say somewhere you check the version you are compiling and the version in loggin.ini being read ?
So the first thing to do when working in a new feature is to advance the Jamtaba version number
to avoid to read logging.ini from previous .
Et voilà !
^^

**Comment by Ezeer** [comment]
Fixed the joystick name that was truncated , now lo is correct : 
>default.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
default.DEBUG:  new Joystick 0x1b68d288  in joyctrl.cpp 15
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick (axes: 3, buttons: 8, hats: 0)  in joyctrl.cpp 68

**Comment by Ezeer** [comment]
Buttons working now : 
>default.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
default.DEBUG:  new Joystick 0x1b684768  in joyctrl.cpp 16
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick (axes: 3, buttons: 8, hats: 0)  in joyctrl.cpp 71
jt.Core.INFO:  Creating plugin finder...
jt.Core.INFO:  Creating midi driver...
jt.Core.INFO:  Creating audio driver...
jt.Core.INFO:  Creating roomStreamer ...
jt.Core.INFO:  Connecting in Jamtaba server...
default.INFO:  "Starting Jamtaba 2.0.5 Standalone (i386) running on Windows XP (i386)"
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 0 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 3 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 1 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 2 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 5 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 6 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 7 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 4 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 6 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 0 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 0 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 1 PRESSED  in MainController.cpp 638
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick BTN 1 PRESSED  in MainController.cpp 638
jt.Core.DEBUG:  StandaloneMainController destructor!  in StandAloneMainController.cpp 287
default.DEBUG:  Joystick destroyed  in joyctrl.cpp 125
jt.Core.DEBUG:  Joystick destroyed!  in MainController.cpp 776
jt.Core.DEBUG:  MainController destrutor!  in MainController.cpp 777
default.DEBUG:  JOYSTICK idx: 0, name:  BTN 1 PRESSED  in MainController.cpp 638
jt.Core.DEBUG:  Stopping MainController...  in MainController.cpp 952
jt.Core.DEBUG:  audio and midi drivers released  in MainController.cpp 961
jt.Core.DEBUG:  disconnecting from login server...  in MainController.cpp 972
jt.Core.DEBUG:  main controller stopped!  in MainController.cpp 783
jt.Core.DEBUG:  clearing tracksNodes...  in MainController.cpp 785
jt.Core.DEBUG:  clearing tracksNodes done!  in MainController.cpp 796
jt.Core.DEBUG:  MainController destructor finished!  in MainController.cpp 798
default.WARNING:  QWaitCondition: Destroyed while threads are still waitingQWaitCondition::~QWaitCondition() qwaitcondition_win.cpp158

default.WARNING:  QWaitCondition: Destroyed while threads are still waitingQWaitCondition::~QWaitCondition() qwaitcondition_win.cpp158

**Comment by Ezeer** [comment]
I think the joystick support could be a good accessory for accessibility .
In my case i use for my tests that joystick , and i imagine that kind of basic assignments : 
![sidewinder-joystick](https://cloud.githubusercontent.com/assets/1283808/10998413/45d45b52-8495-11e5-8715-df84b4bb2f3d.jpg)


You can control in your left hand the volume and the pan  to create nice effects in your solo playing for your right hand at keys for exemple ....

**Comment by elieserdejesus** [comment]
ah, the pan effect using a joystick is something very fun.

**Comment by Ezeer** [comment]
I'm working on axes now , here's your volume , pan , (?)  mix : 
"...
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick AXIS 2 VALUE=32767  in MainController.cpp 657
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick AXIS 0 VALUE=2341  in MainController.cpp 657
default.DEBUG:  JOYSTICK idx: 0, name: SideWinder Joystick AXIS 1 VALUE=261  in MainController.cpp 657

..."
About SDL Axis range values : http://forums.libsdl.org/viewtopic.php?t=3664&sid=964c840d9a6461f79e00ccd745da6c1c

**Comment by elieserdejesus** [comment]
Ezee, volume range ia Jamtaba is [0.0, 1.0], and pan range is [-4.0, 4.0]. 
You need convert your 16 bit values in joyistick to these Jamtaba ranges.

**Comment by Ezeer** [comment]
Sure , a little of math " et hop " !
Thanks for the data , that's all i needed .
:+1:

**Comment by Ezeer** [comment]
Et hop : https://www.youtube.com/watch?v=uctHAgIHG8U
ah aha ha!

**Comment by jonjamcam** [comment]
Ezee, shall I include this in the manual? is it working?

**Comment by Ezeer** [comment]
That will work .
Perhaps write a title and keep a blank page to be filled later .
I can give you soon the details how it will work .
Thank you for that initiative Jon , that's fine !

Also you can try to imagine how you would use it , that could gave me some ideas .
Right now Jamtaba reads all buttons and axis values , i don't have a hat to test .
But no mapping is done yet .

The joystick is for me a remote controler for Jamtaba .
So the title could be : Remote controlers .

**Comment by jonjamcam** [comment]
I have many ways to send midi to the computer, but a joystick looks cheap and easier to manipulate during a jam.

For example:

1.- Inside a room to say "HI". Move to the side to select the volume fader and up/down to adjust level of that particula individual.

2.- In the main room to select the room, then press the main button to enter or the secondary button to listen.

**Comment by Ezeer** [comment]
Great setup for accessibility also .... keep going !
;)

**Comment by elieserdejesus** [comment]
closing by inactivity
