### ISSUE TITLE
Vstplugin scanner window appears in the back of Preferences

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#670]
I found a problem with the vstpluginscanner while in preferences menu, pressing _**Refresh**_ or _**Clear and Scan**_, the scan window appears in the back:

![image](https://cloud.githubusercontent.com/assets/15310433/22076210/eb6c7890-dd8d-11e6-8097-e68f026ddcbb.png)

**Comment by elieserdejesus** [comment]
Now the Plugin Scan dialog will not appear if Preferences panel is opened. Now, If preferences panel is opened the scanned plugins and current scan path are showed directly in preferences panel:

![image](https://cloud.githubusercontent.com/assets/1012741/22089761/741477c4-ddd4-11e6-9dc4-0d9faa170d76.png)

**Comment by jonjamcam** [comment]
nice @elieserdejesus !

 In my system I have a wide cropped window though similar to https://github.com/elieserdejesus/JamTaba/issues/569

![image](https://cloud.githubusercontent.com/assets/15310433/22094118/c4edf200-dde9-11e6-999f-52f8f0b84776.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , can you check again, I fixed in this commit https://github.com/elieserdejesus/JamTaba/commit/e9b54fc8418c077ec52f59e40380e4932f3e28bd

**Comment by jonjamcam** [comment]
perfect!

![image](https://cloud.githubusercontent.com/assets/15310433/22107575/797ff860-de2d-11e6-8df5-75f79b50f870.png)
