### ISSUE TITLE
Drop the version number in the app name?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#671]
Isn't it better just "Jamtaba" in the title...

![image](https://cloud.githubusercontent.com/assets/15310433/22094619/64a1442a-dded-11e6-8546-3e669e9214b3.png)

as in the vst plugin?

![image](https://cloud.githubusercontent.com/assets/15310433/22094685/e4273da8-dded-11e6-970f-06b016329efb.png)

well...almost as the Vst Plugin :D .

**Comment by elieserdejesus** [comment]
@jonjamcam , I agree is better drop the version number from title. 

About the VST "title": this is Host dependent, but in general hosts are mergint the plugin name and vendor.  VSt specs have a "vendor string" too. I will improve these texts a little bit.

**Comment by elieserdejesus** [comment]
The VST vendor and product string are improved now:
![image](https://cloud.githubusercontent.com/assets/1012741/22106662/f8e75bc2-de30-11e6-9d6f-65b59521945e.png)
