### ISSUE TITLE
two instances of Jamtaba 2 VST

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#674]
I noticed a change in the .dll name from JamtabaVST2 to JamtabaVST.dll :

![image](https://cloud.githubusercontent.com/assets/15310433/22202844/d548223a-e148-11e6-8843-1519f3a51617.png)

This results in duplicate plugins. Probably a problem if users do not uninstall 2.0.18:

![image](https://cloud.githubusercontent.com/assets/15310433/22202819/ad213f26-e148-11e6-887c-810bc65d4b32.png)

**Comment by elieserdejesus** [comment]
It's true, I noticed this too. The bad news is: I don't have idea why this name changed. 
To avoid problems in user machines I think is better generate the DLL using the old name, avoiding the duplicated plugin.
