### ISSUE TITLE
Release 2.0.19 tasks

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#692]
- [x] ES translation
- [x] PL translation
- [x] PT translation
- [x] FR translation
- [x] DE translation
- [x] JP translation
***
- [x] update github readme text to mention AU plugin and AU support in Mac Standalone.
- [x] update website to mention AU
- [x] update change log in github releases
- [x] release a beta version
- [x] <strike>Change readme to explain the missing .qm files in first compilation</strike>. Adding .qm files in the repository. 
- [x] Update the screen shots in website
- [x] Update the screen shots in github readme

**Comment by jonjamcam** [comment]
@elieserdejesus I noticed that when cloning Jamtaba for the first time, the missing .qm files of the translation make the compilation fail. It would be good for the github readme text to show that you need to use the **lrelease** command in the case.

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , @qulf, @MagnusDrumsTrumpet , @DoublebassOO, @qulf , @NakajimaYusuke and @takeshitaleo!  **JamTaba version 2.0.19 is comming!!**

We have 23 new texts translate. Can you help us?

**Comment by jonjamcam** [comment]
@elieserdejesus Spanish Transaltion complete in https://github.com/elieserdejesus/JamTaba/pull/693

**Comment by DoublebassOO** [comment]
seems already done  probably jon did it

2017-02-04 23:45 GMT+01:00 jonjamcam <notifications@github.com>:

**Comment by jonjamcam** [comment]
> seems already done  probably jon did it

Hey @DoublebassOO ! I've not done the translations for 2.0.19, Only completed missing ones for 2.0.18. My french is very poor and I use google translate. Much better result if you can do it.

**Comment by jonjamcam** [comment]
@elieserdejesus FR_fr and JP_jp done in https://github.com/elieserdejesus/JamTaba/pull/698 . I marked the ones I made using google _unfinished_ so they can be easily revised and corrected if necessary by a native speaker.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam

**Comment by DoublebassOO** [comment]
Hello  !
I think i have made some correction in the french translation in github  .
But not sure of the good proceeding . Github really not much friendly for
me :)
.
If not could you tell me where to change the translation in github . Thanks.

2017-02-04 23:17 GMT+01:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , I checked your fork but I can't see the changes. I opened the FR translation file history (is available in github, top right corner) but your changes are no listed.

**Comment by jonjamcam** [comment]
@elieserdejesus The manual is complete for 2.0.19.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , this manual is really good, very clean, objective, the images are nice and helping a lot to understand the features. Big thanks for your great job!

**Comment by jonjamcam** [comment]
> If not could you tell me where to change the translation in github . Thanks.

Hi @DoublebassOO . correct the trnslations directly in github is very easy. Follow these steps:

1.- open the translation file in github. French Tr is here : https://github.com/elieserdejesus/JamTaba/blob/master/translations/fr_FR.ts

2.- click the little **pencil** at the **right top** of the window you just opened:

![image](https://cloud.githubusercontent.com/assets/15310433/22658882/6aae0e48-ec7a-11e6-9e3b-060a4b77158e.png)

3.- do the editing. If you need the search function you have to click **inside** the code window and press **ctrl + F**. A little search box will appear at the **top left** corner:

![image](https://cloud.githubusercontent.com/assets/15310433/22659000/d4b8823c-ec7a-11e6-8d7b-dcd691cbfa6e.png)

4.- When you finish, click **propose file change** to commit your changes:

![image](https://cloud.githubusercontent.com/assets/15310433/22659019/e9c34234-ec7a-11e6-9f2e-6df19b11fe3a.png)

5.-  Finally click **Create pull request** to update the changes to the origin.

**Comment by jonjamcam** [comment]
> this manual is really good, very clean, objective, the images are nice and helping a lot to understand the features. Big thanks for your great job!

Hey man, just trying to keep the high standard! The information is all there, but we still need better ways to get to individual explanations without going through whole chapters.

**Comment by DoublebassOO** [comment]
thanks jon   i will try again

**Comment by DoublebassOO** [comment]
great explanations thanks a lot.....

**Comment by MagnusDrumsTrumpet** [comment]
hey Eli, did you get it ?   i proposed it)
greets Mag 

    DoublebassOO <notifications@github.com> schrieb am 21:31 Dienstag, 7.Februar 2017:
 

 great explanations thanks a lot.....—

**Comment by elieserdejesus** [comment]
Yes @MagnusDrumsTrumpet , I see the changes in your forked repository. Thanks!

**Comment by elieserdejesus** [comment]
@DoublebassOO , I see you changed 2 texts in your forked repository: [https://github.com/DoublebassOO/JamTaba/commit/47ff4364599a5fc64edc347b6a3886a7e8132d8e](https://github.com/DoublebassOO/JamTaba/commit/47ff4364599a5fc64edc347b6a3886a7e8132d8e)

Can I merge these changes? Just confirming ...

**Comment by elieserdejesus** [comment]
@DoublebassOO , I merged your translation changes, thanks!

**Comment by elieserdejesus** [comment]
guys, I'm think the last beta is solid enough to release. What you think? Time to release?

**Comment by jonjamcam** [comment]
>the last beta is solid enough to release

I had no problems during testing this week.

**Comment by elieserdejesus** [comment]
new Jamtaba released guys!  Thanks all for your help!
