### ISSUE TITLE
[VST plugin & Standalone] Jamtaba/Reaper are crashing when another ninjam cilent connects

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#695]
Testing 2.0.19 Beta. I'm sad to report this one :( :

If I am connected to an empty server and other _old ninjam client user, jamtaba user, wahjam or reaNINJAM client_ connects to same server Jamtaba crashes. Tested in windows only.

EDIT: Not possible to connect to a non-empty server either.

EDIT2: If I use my own 2.0.19 compiled (standalone 32bits) I have no problems. Don't know why.

EDIT3: Deleting JamTaba folder solves the problem for the standalone. Vst plugin still crashing in this case.

I installed the beta over my existing files (previous 2.0.19 release from here: https://github.com/elieserdejesus/JamTaba/pull/677#issuecomment-275267639). Dong a clean install now.

Clean install makes Jamtaba crash too. 

I really hope it's nothing serious.....but for the moment it's not working in my system. I tried uninstalling and reinstalling. The previous version above (https://github.com/elieserdejesus/JamTaba/pull/677#issuecomment-275267639) is working perfect (although is more than a week old)

**Comment by elieserdejesus** [comment]
@jonjamcam , Pipaxis reported the same problem in Mac, fortunally is not serious, just a little missing code in NinjamTracks, every time a ninjam track is created the crash occurs. It's fixed, I will release a new beta in some minutes.

**Comment by elieserdejesus** [comment]
@jonjamcam , I released a fixed beta: [https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.19-beta.2](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.19-beta.2)

Tested Standalone and Plugin and is working ok now.

**Comment by jonjamcam** [comment]
Yes. Beta2 is working fine.
