### ISSUE TITLE
Audio looper

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#7]
something to load an audio file with a drum pattern, edit start and end point of loop, and play in sync with ninjam metronome/interval. Advanced features: stretch the audio file when bpm is changed, detect loop meta data for some audio loop formats, beat detection analyzing audio directly, etc.

http://www.recordingmag.com/resources/resourceDetail/323.html

**Comment by pljones** [comment]
Is this only needed for the standalone?  (DAW can probably do this and sync-with-host takes care of sync to metronome.)

**Comment by elieserdejesus** [comment]
closing by inactivity
