### ISSUE TITLE
jamtaba standalone on Mac OSX 10.11 not working ?

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#704]
My friend try jamtaba standalone on his Mac pro    without success
OS10.11  64 bits  
the circle never stop turning no server can be seen. 

Something to do for making it works

Maybe already asked ?

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , can you test the [last beta](https://github.com/elieserdejesus/JamTaba/releases)?

3 users tested and reported is working fine in Mac Osx.

**Comment by DoublebassOO** [comment]
my friend seems to have make it work with the new version  thks  . but he hadnt connect to server.... i will give news
