### ISSUE TITLE
PANIC button for Midi tracks [Standalone]

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#714]
Currently, when changing input midi channels or higher/lower notes inside the midi tools menu and simultaneously you are feeding these inputs with midi data (i.e. notes, sustain) sometimes the note off or sustain off message doesn't reach the plugins before the change is made. 

This results in infinite notes. If F6 worked as a panic button it would be OK, but it doesn't (during my tests), so the only way to stop the sound is restarting Jamtaba.

**Comment by elieserdejesus** [comment]
From [Crash Course MIDI book](https://books.google.com.br/books?id=ooSkrtmcplcC&pg=PA46&dq=Most+sequencers+and+many+MIDI+interfaces+have+a+panic+button.+This+doesn%27t+summon+a+SWAT+team+but+simply+sends+MIDI+Note+Off&hl=pt-BR&sa=X&ved=0ahUKEwi305eU5oLSAhWJEJAKHUpvAYAQ6AEIHDAA#v=onepage&q&f=false)

**THE PANIC BUTTON**
> Most sequencers and many MIDI interfaces have a panic button. This doesn't summon a SWAT team but simply sends MIDI Note Off messages to all notes on all MIDI channels (and all MIDI ports, if there's more than one) to kill stuck notes.

The best part is the SWAT team :)

I think the complicated part is **where we will put the panic button**? What is the best place in the UI for a panic button? Reaper, for example, don't have a button in UI, you need hit F3 to get the PANIC feature.  I suppose Reaper team choosed this approach to avoid polute the UI with a rarely clicked button.  I have no good ideas for this button at moment.

**Comment by jonjamcam** [comment]
> Reaper team choosed this approach to avoid polute the UI with a rarely clicked button. I have no good ideas for this button at moment.

I think a good place (with full of empty space) could be the _Midi Preferences dialog_(F6). It's quick enough to reach and pretty much invisible.

**Comment by jonjamcam** [comment]
> call some sendAllNotesOff() function every time midi engine is stopped

Yeah. Pressing F6 will trigger also the panic automatically. Nice!

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
