### ISSUE TITLE
Window not on top . Cant type in chat or name box 

### ISSUE THREAD

**Issue by Trashcanhead1111** [elieserdejesus/JamTaba#719]
I installed the new version and When you type in jamtaba in sonor x3 the window acts not active on on top .If i push a key nothing happens .

**Comment by jonjamcam** [comment]
@Trashcanhead1111 It is a bug specific to sonar. Can you please use 2.0.18 version until it gets fixed? Just uninstall 2.0.19 and reinstall 2.0.18 from here: https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.18

**Comment by Trashcanhead1111** [comment]
ok thats fine. I did and all is well. really like the new ice theme looked calming. ttyl 
thanks

**Comment by jonjamcam** [comment]
@Trashcanhead1111 You can still use the Ice theme in 2.0.18. Just change the extension of this file to **rar** and extract the files into the **themes** folder

[Ice.rar.txt](https://github.com/elieserdejesus/JamTaba/files/768188/Ice.rar.txt)

**Comment by Trashcanhead1111** [comment]
great thanks . appreciate it
