### ISSUE TITLE
WIKI IMAGES FOLDER

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#72]
I need to have pictures online for the Wiki .
I had the idea to use that thread to upload pictures that could be referenced later .
It is a way to keep our artworks and othe pictures saved in the project , not in an external site.

So the first picture is to help the users to find the Jamtaba2 user folder under windows : 
![capture d ecran 2015-10-31 16 54 18](https://cloud.githubusercontent.com/assets/1283808/10864582/bf38ca0c-7ff2-11e5-8b74-8ccec94c95c0.png)

you can check the result here : https://github.com/elieserdejesus/JamTaba/wiki/Jamtaba's-user-guide

default logging.ini : 
![capture d ecran 2015-10-31 18 59 53](https://cloud.githubusercontent.com/assets/1283808/10889729/ebb443c0-8193-11e5-9376-b15ebb58f9f0.png)

**Comment by Ezeer** [comment]
![user_manual_icon](https://cloud.githubusercontent.com/assets/1283808/10865530/6a6c96c2-800e-11e5-8b02-f241209d8d02.png)

**Comment by elieserdejesus** [comment]
The Wiki idea is nice, using images is a very user friendly approach. Nice job!

**Comment by Ezeer** [comment]
oh, thank you !
So i've got the key !
( you have the keys after all elieser eh eh)

**Comment by Ezeer** [comment]
![jamtaba logo 3d jpg 16x16](https://cloud.githubusercontent.com/assets/1283808/10866252/ba25f984-8026-11e5-86bb-a9a2b0205d2e.jpg)
![jamtaba logo 3d jpg 64x64](https://cloud.githubusercontent.com/assets/1283808/10866255/c9875120-8026-11e5-8192-e91297f1de41.jpg)

![jamtaba logo 3d jpg 32x32](https://cloud.githubusercontent.com/assets/1283808/10866253/bec787dc-8026-11e5-8722-202c2216d79c.jpg)

![jamtaba logo 3d jpg 88x88](https://cloud.githubusercontent.com/assets/1283808/10866259/df6b2b42-8026-11e5-98b8-cda2e0828e62.jpg)

**Comment by jonjamcam** [comment]
![snap overview from pfd 1 0 2 for wiki](https://cloud.githubusercontent.com/assets/15310433/10872538/c0eb27f0-80e2-11e5-9e98-1e81b534dfb7.jpg)

**Comment by jonjamcam** [comment]
![jamtaba ini](https://cloud.githubusercontent.com/assets/15310433/10872691/32ef1930-80e6-11e5-8047-f7382dd5cc43.jpg)

**Comment by jonjamcam** [comment]
![overview](https://cloud.githubusercontent.com/assets/15310433/10872788/53e24bf6-80e8-11e5-8ada-ab7330352d80.jpg)

**Comment by jonjamcam** [comment]
![joining a room](https://cloud.githubusercontent.com/assets/15310433/10872873/13dbe72c-80ea-11e5-9eff-41eb5b78ea4e.jpg)

**Comment by jonjamcam** [comment]
![loggin](https://cloud.githubusercontent.com/assets/15310433/10872876/1aa25226-80ea-11e5-9b6b-01b41c1366ac.jpg)

**Comment by jonjamcam** [comment]
![snap jar from pfd 1 0 2 for wiki](https://cloud.githubusercontent.com/assets/15310433/10872902/920d2e6c-80ea-11e5-8efb-0939eca6e73b.jpg)

**Comment by Ezeer** [comment]
co-munication ... woaw ... let me think about it !
I would refer to com+munication , but co could works indeed ...
com -> http://www.lexilogos.com/latin/gaffiot.php?q=com
So they say com = old cum ...
cum mean with ... munication ...

wait ... the root is *communicare* ?
Icare in french is icarus in english ...
" I believe i can fly with icarus " is co-munication ?
ah ah ah ... https://www.youtube.com/watch?v=GIQn8pab8Vc

good job jon !

**Comment by jonjamcam** [comment]
THX. My goal is to have the same content in the wiki and in a PDF file.....Did you like how the wiki is looking? I will try to use as much as I can from the text that's already there!

**Comment by Ezeer** [comment]
Elieser was really with it .
I follow elieser's desire , so we'll have to wait for his wish ?
;)

**Comment by jonjamcam** [comment]
anyway I kept the original code in case it's needed

[original jamtaba wiki for backup.txt](https://github.com/elieserdejesus/JamTaba/files/25013/original.jamtaba.wiki.for.backup.txt)

**Comment by Ezeer** [comment]
ah ah ah ... you're the man of the situation .
Keep going !
(my two cents for the library : 
![keepgoing](https://cloud.githubusercontent.com/assets/1283808/10873146/ef4bca8c-810f-11e5-97a6-011590e73975.png)
)

**Comment by elieserdejesus** [comment]
Jon and Ezee, the wiki pages are nice!
In the User's manual the images are difficult to read in my machine. Maybe some problem with low resolution images?

**Comment by jonjamcam** [comment]
Can you read them in the pdf?

[jamtaba manual_v.1.0.4.pdf](https://github.com/elieserdejesus/JamTaba/files/25054/jamtaba.manual_v.1.0.4.pdf)

**Comment by elieserdejesus** [comment]
Yes Jon, the images in pdf are clear, easy to read.

The first big image in the pdf is with a low quality. I suggest use a better image like this: https://github.com/elieserdejesus/JamTaba/blob/master/Icons/png/Jamtaba%20Logo%203d%20PNG%20469x400.png

Thanks for your help Jon.

**Comment by jonjamcam** [comment]
the images are not finished, but I'll work on the resolution for the wiki page.

**Comment by jonjamcam** [comment]
some Images improved........still under construction :D.

**Comment by Ezeer** [comment]
updated user's guide with the previous screen capture of loggin.ini

**Comment by jonjamcam** [comment]
![mini mode](https://cloud.githubusercontent.com/assets/15310433/10893892/f72fc3fa-8189-11e5-8b57-e942ea1b80c9.jpg)

**Comment by jonjamcam** [comment]
![aditional ch and subch](https://cloud.githubusercontent.com/assets/15310433/10893983/915dccc4-818a-11e5-836d-19c44a9990fe.jpg)

**Comment by Ezeer** [comment]
Hey jon , your work into the user's guide start to be very impressive .
Congrats !

**Comment by jonjamcam** [comment]
I really want it to be useful. I'm working in the control section now....not finish yet...I'm updating the user's guide as soon as I feel i makes sense.

[jamtaba manual_v.1.1.1.pdf](https://github.com/elieserdejesus/JamTaba/files/25810/jamtaba.manual_v.1.1.1.pdf)

**Comment by Ezeer** [comment]
WOOOoooo ! https://www.youtube.com/watch?v=_NO1-gLkUaU

**Comment by Ezeer** [comment]
A little debug session of your pdf , to assist , right ?
Here we go : 
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)

* Page 5 : ERROR :8ball:  i can't say that dave : 
>" JAMRABA too. "
* Page 7 : ERROR  :8ball: i can' say that dave : 
 " In this section you will learn how to use **all powerful the functions**
that Jamtaba has in order to expand your jaming experience. "
* Page 10 : WARNING :1234: Are you sure Dave ? : " By now you should know that a SERVER is a room where musicians enter to play music. " 
 + proposition is :  " By now you should know that a SERVER provides  rooms where musicians enter to play music. " 
* Page 10 : WARNING :1234: Are you sure Dave ? : " A PUBLIC SERVER is a room
provided for free for anyone to join by Generous People.  "
  + proposition is :  " A PUBLIC SERVER serves a room provided for free for anyone to join, by Generous People.  " 
End of debug session ... time : 2.49
Good job Dave

**Comment by jonjamcam** [comment]
I appreciate the debug. It's important. Comments and suggestions are always welcome. Now I realize I write very strangely....lol.

 Night mate. Cya tomorow. Long live JAMTABA

**Comment by jonjamcam** [comment]
"proposition is : " A PUBLIC SERVER serves a room provided for free for anyone to join, by Generous People. ""

"Server serves" makes some noise to me

what do you think about :"PUBLIC SERVERS are provided for free for anyone to join, by Generous People. """

**Comment by Ezeer** [comment]
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)
good morning Dave .
I am a computer but i have emotions too : 
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)
Compilation done , no error was detected .
https://www.youtube.com/watch?v=ptHdz-z3ess

;)

**Comment by jonjamcam** [comment]
Well, I must be halfway into the Manual by now....I think I can have a finished (BASIC) version by the weekend so everyone can read and check. I like your idea of distributing a pdf with the installation package.

Once approved I'll adapt it to the online manual.

**Comment by Ezeer** [comment]
Very nice .
I was impressed by the quality of your documentation , how you have organized the informations .
It is good looking and enjoyable to read .
Some people reads the doc before using tools , and that doc gives a nice preview of our product .
It was a good idea to come to help us .
^^

**Comment by jonjamcam** [comment]
You know, Every plugin, pedal and instrument (except the acoustic ones) I have, before I bought them I downloaded the manual fisrt and read it mostly complete and not only one, but the other models, brands, etc.
 Probably it has something to do with KARMA.

https://www.youtube.com/watch?v=skIb_gFoDiQ

**Comment by Ezeer** [comment]
I like to read too,eh eh . 
from your link above : 
" Letting go of responsibility for other people’s states of mind is fundamentally liberating. "
Jamtaba is done actually in that state of mind , i like it , i like it like this .

" the frenchs say ... "
ah ah ah !
Thank you , i like also what i hear !
^^

**Comment by jonjamcam** [comment]
yea, "the french say..."  lol.

I read a lot too. You know, never in the all history we had access to all the information whenever we wanted! All Books, All videos...aAAALLL.

but stil, there are a lot of people who don't know how to look for information.....too bad....well... NOT US!

I bought a KOBO last year and I'm reading more than ever.

ALL KNOWLEDGE COOOMMEEEE TOOOO MEEEEEEE!!!!!

**Comment by jonjamcam** [comment]
Hey guys, Just finished the "Your Control" Section of the Manual and corrected some mistakes Ezee pointed out. What do you think? Do you think it's clear enough for a beginner? Any comments, suggestions?

[jamtaba manual_v.1.1.7.pdf](https://github.com/elieserdejesus/JamTaba/files/26331/jamtaba.manual_v.1.1.7.pdf)

**Comment by Ezeer** [comment]
The first impression ? 
It's related to the first words : 
"  Welcome to the Jamtaba Experience. "
:+1: 

**Page 6 , can you try Orange instead of red ?**
Colors ... the control section colors are NEAT !
I like the Grey and blue tones you have choosen here .
wait ... ** as elieser took the " orange " direction , could you try that color ** with the border
of the box sayin : 
>The Control Section is Shared
between the Main Page and
the Room pages. This section
controls your sound and determines
what others will hear
from you during the Jam.

Orange and blue , it's a love story ...
![28b36e18fbc15d0ff9cb2345b5f7a636270f8fc4](https://cloud.githubusercontent.com/assets/1283808/10915895/196fc8aa-8259-11e5-8eaf-63e712448f87.jpg)

**i like also that term that i've never heard before :** 
"  It’s called INTERVALLIC. " p 15
:+1: 

Pretty good job , here .
Please lemme see the orange thing ?
:sunglasses:

**Comment by jonjamcam** [comment]
Ohh I see where you're going Ezee......the Logo Orange!

![control section_w textboxes_ezeeorange_sample](https://cloud.githubusercontent.com/assets/15310433/10916884/9baedb34-823c-11e5-8ef7-9941b91d2bcb.jpg)

**Comment by Ezeer** [comment]
@elieserdejesus  so what ?

For me , that's more in the " experience " than grey .
Elieser was saying to me that he get bored with sad tones ...
Perhaps you could also try orange on the " bubbles " too ?

My feeling of orange here is " tonic " .
I like it !

**Comment by Ezeer** [comment]
Also , can u use gradient colors inside of your boxes ?
You gave me the idea to reproduce the colors of the logo in some special boxes , like this previous
we're talking about .

And please try to change the red into orange ( it's ezee , put some :sunny: on it  ) page 6 ?

**Comment by jonjamcam** [comment]
ATM i'm using basic software for the drawings,so no gradients, but in the future it can be done.

![main page_orange](https://cloud.githubusercontent.com/assets/15310433/10918005/3fb4e732-8242-11e5-92d3-08684deaaafa.jpg)

I think It's a good concept. Let's wait what the boss has to say....THE VOICE OF THE MAN..HEHE

**Comment by Ezeer** [comment]
yeah , looks better in orange fashion .
The boss is actually busy with a mistake i made at my last push and merge of code .
A git shit ...
So he will look at your work after that i guess ( our workflow was broken )

**Comment by jonjamcam** [comment]
BTW, I'm starting to like the Blue-orange more than the green-orange

![main page blue-orange](https://cloud.githubusercontent.com/assets/15310433/10918678/c4ca57d8-8245-11e5-93b6-f946b6d66b02.jpg)

**Comment by Ezeer** [comment]
yeah  , less agressive this way .
But perhaps keep the green here for the transmit box ?

**Comment by jonjamcam** [comment]
What should be better for a manual, Soft colors or Agressive ones?

http://info.shiftelearning.com/blog/bid/348188/6-Ways-Color-Psychology-Can-Be-Used-to-Design-Effective-eLearning

**Comment by Ezeer** [comment]
I think you could use both .
For exemple , when what you explain is easy to follow , use agressive or funky tones ( groovy ) .
But if we need to concentrate , use soft colors to not overload our brains with different type of signals 
that will make saturation at neuronal range ...

As the logo is orange/green , perhaps use these colors to manifest what makes the original Jamtaba experience ?  ( servers , room , listen , chat )

The vst effects part is also a feature we love and should be highlighted .

**Comment by elieserdejesus** [comment]
Very good jon, thanks for all this work!  
About the color, be carefull with contrast. The blue background in text boxes not have a good contrast with the black text. The blue is dark and the text is dar too. Try a lighter blue, so you have a constrast.

I'm not god with colors, so I always use something to show me good [color schemes](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)

Color is a very difficult subject. It's like music. Some people have a very good and trained ears, and can listen every detail in music. Other people have very good and trained eyes. 

My eyes are not good, but I'm keep trying :) hehe

**Comment by jonjamcam** [comment]
True. Colors are tricky. Let's take it Ezze.

**Comment by Ezeer** [comment]
Ah Ah ! you like to play ? Take that so :  https://www.youtube.com/watch?v=RVmG_d3HKBA
lol

**Comment by Ezeer** [comment]
@jonjamcam  I use it : http://www.gimp.org/
Sometimes tricky because like Blender Gimp don't use ' traditional ' shortcuts etc ...
But some very good work can be achieved with it , and it's free .

**Comment by elieserdejesus** [comment]
I'm using this: [http://www.getpaint.net/index.html](http://www.getpaint.net/index.html)

**Comment by Ezeer** [comment]
Oh yes ! I was using it years ago , powerful enough and lighter than Gimp .
Perhaps a clever choice for you Jon , there is no learning curve to use it .
Thx elieser , i download it now .

**Comment by Ezeer** [comment]
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)
Error :8ball:   You can't do that ezee : Minimum spec is Windows 7

**Comment by jonjamcam** [comment]
I'll check it out guys. THx.

BTW: I was testing this afternoon Jamtaba on Windows Xp with mixed results, but I started to talk to this guy "CREATIVE" about Jamtaba in the Chat....well he didn't know Jamtaba was out, so he downloaded it and started using it on the fly. I gave him some tips like sync and add channel and from then on he started writing things like "this is awesome" "It's so flexible" "great" "will never go back", etc..

It seems to me that the VST plugin is having a lot of success because now you can choose your favorite DAW and be in perfect sync with it and that was never possible before Jamtaba.

Guys, this is the future happening NOW.

 CHEERS!
Long live the TABA!

**Comment by Ezeer** [comment]
CLAp CLAP CLAP CLAP !
^^

**Comment by elieserdejesus** [comment]
Jon, thanks for this works. I'm reading this at 08:28 morning in a raining day. Your words sounds like a sunset. Thanks!

**Comment by jonjamcam** [comment]
![installation2](https://cloud.githubusercontent.com/assets/15310433/10999648/f9169d3e-847b-11e5-8a99-e395b29264c9.jpg)

**Comment by jonjamcam** [comment]
![install_snap1](https://cloud.githubusercontent.com/assets/15310433/10999743/830ddd7c-847c-11e5-81f2-cec30c7fa715.jpg)

![install_snap2](https://cloud.githubusercontent.com/assets/15310433/10999758/94a2e0dc-847c-11e5-8f9f-21331d51f0ee.jpg)

![install_snap3](https://cloud.githubusercontent.com/assets/15310433/10999803/d2749568-847c-11e5-932c-c00f69a09743.jpg)

![install_snap8](https://cloud.githubusercontent.com/assets/15310433/10999810/de1024d2-847c-11e5-8831-fb52e59c5712.jpg)

**Comment by jonjamcam** [comment]
![scan vst](https://cloud.githubusercontent.com/assets/15310433/11000005/fe209152-847d-11e5-876e-7f5635445585.jpg)

**Comment by jonjamcam** [comment]
![vst box new](https://cloud.githubusercontent.com/assets/15310433/11000062/51f889f6-847e-11e5-9703-4530438333c2.jpg)

**Comment by jonjamcam** [comment]
![setting up jamtaba](https://cloud.githubusercontent.com/assets/15310433/11000122/b64e6b5a-847e-11e5-9fdd-d694067e15b8.jpg)

![preferences menu 2](https://cloud.githubusercontent.com/assets/15310433/11000145/d6941b08-847e-11e5-9f5b-6c63fa2e42a6.jpg)

![audio box](https://cloud.githubusercontent.com/assets/15310433/11000164/dfab9cf2-847e-11e5-8245-37dedcf86c25.jpg)

![midi box](https://cloud.githubusercontent.com/assets/15310433/11000182/f1f3b73c-847e-11e5-8bd5-7249d0c56b22.jpg)

**Comment by jonjamcam** [comment]
![the control section header](https://cloud.githubusercontent.com/assets/15310433/11000407/5ba79ecc-8480-11e5-8449-a1cb081857c6.jpg)

**Comment by Ezeer** [comment]
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)
 You hit the wrong button Jon !
guess who comes for dinner ?
![les-gardiens-de-la-galaxie-ecrasent-tout](https://cloud.githubusercontent.com/assets/1283808/11000587/f6340f3a-84a2-11e5-9a6f-e3bd969bc4ff.jpg)

lol

**Comment by jonjamcam** [comment]
yea....they are too close!

btw Green is a nice color.....

**Comment by Ezeer** [comment]
**btw Green is a nice color.....**
Ah AH AH ! 
:100:

**Comment by jonjamcam** [comment]
![add channel header](https://cloud.githubusercontent.com/assets/15310433/11005985/f990fa1a-849f-11e5-8d86-07f628252a98.jpg)

![multitrack header](https://cloud.githubusercontent.com/assets/15310433/11005993/ffba8d98-849f-11e5-9863-fea8b384b8f2.jpg)

**Comment by jonjamcam** [comment]
![private header](https://cloud.githubusercontent.com/assets/15310433/11006686/db3560ac-84a3-11e5-871c-51bd36bf5718.jpg)

![private serv menu](https://cloud.githubusercontent.com/assets/15310433/11006700/f02eb9fe-84a3-11e5-9ecf-3534528b4429.jpg)

![private serv box](https://cloud.githubusercontent.com/assets/15310433/11006709/00e9a5ba-84a4-11e5-83e8-f4315097554e.jpg)

**Comment by jonjamcam** [comment]
![ninjam menu header](https://cloud.githubusercontent.com/assets/15310433/11011710/d577e916-84c9-11e5-9323-4ea25f26692f.jpg)

![help menu header](https://cloud.githubusercontent.com/assets/15310433/11011713/dd292576-84c9-11e5-83f1-7f739a7b4876.jpg)

**Comment by jonjamcam** [comment]
![inside server big](https://cloud.githubusercontent.com/assets/15310433/11011919/e41dd938-84cb-11e5-8d2a-417df3c051fd.jpg)

**Comment by jonjamcam** [comment]
![metronome use header](https://cloud.githubusercontent.com/assets/15310433/11012046/62dd17f6-84cd-11e5-88ee-4900875eccc5.jpg)

![jamming header](https://cloud.githubusercontent.com/assets/15310433/11012058/7d4574bc-84cd-11e5-84de-ff518867637b.jpg)

![the metronome visual](https://cloud.githubusercontent.com/assets/15310433/11012069/9f59a4f6-84cd-11e5-8408-164d2b3ac588.jpg)

![the metronome controls](https://cloud.githubusercontent.com/assets/15310433/11012082/ce54aa26-84cd-11e5-8ad6-ccec524a0e82.jpg)

![bpibpm box](https://cloud.githubusercontent.com/assets/15310433/11012084/d51fcc0a-84cd-11e5-8fec-160e704d2347.jpg)

**Comment by jonjamcam** [comment]
![other controls header](https://cloud.githubusercontent.com/assets/15310433/11012239/3d32ee6a-84d0-11e5-8051-2d89075b58b5.jpg)

![chat header](https://cloud.githubusercontent.com/assets/15310433/11012241/42032888-84d0-11e5-926b-3563771afb34.jpg)

**Comment by jonjamcam** [comment]
![tweaks header](https://cloud.githubusercontent.com/assets/15310433/11015384/ef19d88a-853b-11e5-8b06-97bc14d70140.jpg)

**Comment by Ezeer** [comment]
![output_lvvgs1](https://cloud.githubusercontent.com/assets/1283808/11020386/d1d88080-861e-11e5-941e-1c6debe2fdb2.gif)

**Comment by Ezeer** [comment]
![output_xpo8v6](https://cloud.githubusercontent.com/assets/1283808/11020478/4ddda290-8620-11e5-8b6e-b77841268bb9.gif)

**Comment by jonjamcam** [comment]
it's alive!....ALIVE!

**Comment by Ezeer** [comment]
mwah ah ah , orange's heart got the pulse , yo !

**Comment by elieserdejesus** [comment]
This is cool, I will quit Stringer, Ezee is the new animator in the team :)

**Comment by Ezeer** [comment]
A promotion ? 
Wohoo ! 
Beer for everyone : 
![538249_526340387406838_710338910_n](https://cloud.githubusercontent.com/assets/1283808/11020719/58175532-8628-11e5-9fc0-a7bf01684920.jpg)

**Comment by Ezeer** [comment]
you like this one ? gradient effect ...
![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/1283808/11020730/0d9e58ba-8629-11e5-8e55-b8cd89b568c0.gif)

**Comment by Ezeer** [comment]
I've started to create a 3d logo for animation ( based on Stringer's logo ) , work in progress : 

![blender](https://cloud.githubusercontent.com/assets/1283808/11060344/d0b561a0-879f-11e5-99e8-18edbc33cfcf.png)

**Comment by jonjamcam** [comment]
made with....?

![playdoh](http://www.wisewonders.org/wp-content/uploads/2015/09/playdoh.jpg)

**Comment by Ezeer** [comment]
Ah ah ah , very good ... DOh !
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/1283808/11060462/b6578bc0-87a0-11e5-95fc-af7a3ac2832e.jpg)

Made with Blender of course !
;)

**Comment by Ezeer** [comment]
I was promoted as animator , you remember ?
I take that job seriously ( mwah ah ah ) , and try to use Blender to produce original pictures and animation .

This one could serve as background when Jamtaba server is down , for exemple : 
![wip](https://cloud.githubusercontent.com/assets/1283808/11087555/7d4647c0-885b-11e5-8bab-2319bcc74059.jpg)

**Comment by jonjamcam** [comment]
Yes, man. I remember. Your creativity is beyond measure

https://www.youtube.com/watch?v=8Xo8At6XEqE

**Comment by Ezeer** [comment]
Well , the best comment ever for me was : 
**" it's alive!....ALIVE! "**
LOL !! That is creativity !

Thanks for the " i remember " track , good for my soul !
;)

**Comment by jonjamcam** [comment]
![chords_more](https://cloud.githubusercontent.com/assets/15310433/11402877/bfcb9334-9378-11e5-9331-77798e0a4fb2.png)

**Comment by jonjamcam** [comment]
@elieserdejesus Now the wiki has all the images inside the directory, so no need for this thread anymore.

**Comment by elieserdejesus** [comment]
thanks for the info @jonjamcam, closing the issue!
