### ISSUE TITLE
jamtaba Mac OsX  10.11  stop working

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#720]
Hi 

I try to make a friend come in  with a mac. 

jamtaba last release  first time open the room without problem

now when tryin to open it    it is blocked on the circle loading rooms  and  dont move .

he try to restart  , to resintall  it without success   his firewall on osX 10.11  is not activated.

Any idea of the problem  

thanks for your help guys

**Comment by elieserdejesus** [comment]
@DoublebassOO , no clues about this problem. I have some ideas:

1 - Send (drag and drop the file here) the log file (**log.txt**) located in [Application Support folder](http://www.syniumsoftware.com/support-article/how-do-i-navigate-to-the-application-support-folder)

2 - Force a clean restart **deleting** the JamTaba folder inside **Application Support folder**. 

3 - Try ensure is not a general network problem: try Reaninjam inside Reaper if possible anc check if is possible conenctin some server.

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , I will close this issue because we have some MAc users using JamTaba without problems, so I will assume these problems you mentioned before are something in the user machine, not a JamTaba issue. If your friend see the problem again we can reopen the issue.
