### ISSUE TITLE
[Standalone] Wrong characters in plugin name when using some VSTi 

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#722]
It happens with Miroslav Philarmonik in Jamtaba standalone 32bit:

![image](https://cloud.githubusercontent.com/assets/15310433/23334902/aacb07e4-fb87-11e6-97c4-7eab445e6aa1.png)

![image](https://cloud.githubusercontent.com/assets/15310433/23334894/7ae61f32-fb87-11e6-9c5c-9480da308f17.png)

This an old 32 bit plugin. When used with Jbrigde in Jamtaba 64bit or reaper x64 the name appears correctly:

![image](https://cloud.githubusercontent.com/assets/15310433/23334968/2e3f3928-fb89-11e6-9c26-59e13bd4001d.png)

version I'm using: 1.1.1, not the last one:

![image](https://cloud.githubusercontent.com/assets/15310433/23334987/b278466c-fb89-11e6-9fff-eabe8d17c0bc.png)

**Comment by elieserdejesus** [comment]
@jonjamcam, can you share the Mirouslav DLL? Not the entire plugin including the sound library, just the DLL?

**Comment by jonjamcam** [comment]
> an you share the Mirouslav DLL?

Here it is:


[Philharmonik.rar.txt](https://github.com/elieserdejesus/JamTaba/files/890658/Philharmonik.rar.txt)

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam , but unfortunally I have a Windows Register error when loading the plugin. I suppose Philharmonik installer is adding a entry in Windows Registry, and the DLL is trying to read this entry.

**Comment by jonjamcam** [comment]
>  I have a Windows Register error when loading the plugin

@elieserdejesus No problem, this happens only with this plugin. It is kind of ugly, but it doesn't affect it's performance. 

If you had the installer will you be able to check it correctly?

**Comment by elieserdejesus** [comment]
Yes @jonjamcam , I think the installer is enough to install and test. But the installer is separated from the sound library?

**Comment by jonjamcam** [comment]
> the installer is separated from the sound library?

Yes I remember it was, but I can't find the original installer :blush: (I installed it years ago), but

I just installed PHILARMONIK CE, which has the same problem:

![image](https://cloud.githubusercontent.com/assets/15310433/24627695/2ea8b4c8-188c-11e7-9c86-0d759267cafa.png)

 The installer is 41MB (just tested it in my computer) and is available in my dropbox account:

https://www.dropbox.com/s/xhlgb4sjxdfqk34/Miroslav%20Philharmonic%20Disc1.rar?dl=0

You can use it safely with no library in demo mode. Just cancel the registration when it starts.

**Comment by elieserdejesus** [comment]
@jonjamcam , I installed PHILARMONIK CE here, no way to load this plugin in JamTaba. The plugin is working in Reaper. I tried load the plugin directly in **VstScanner** project and got an error. Tried in JamTaba (23 bits) and same error. No clues at moment.

**Comment by jonjamcam** [comment]
@elieserdejesus No worries, do not spend time on this one. It is an old plugin. I have the fortune to be able to use it :smile: in win7. I think there's version 2 out there. Let's add it to the unsupported list. closing
