### ISSUE TITLE
SPlash screen !

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#73]
A splash screen ( transparent window ?) with the logo and the version number would be very nice .
We could use the logo for example ? **--> stupid echo mwah ah ah**
 I imagine it showing with an effect ( the kind of effect from MovieMaker you know - in/out - )
Perhaps showing while vst's are loading ?
Or use the pluginFinder window ?

Okay , that is not the super priority , but will add some coolish fashion style to our baby .

**Comment by elieserdejesus** [comment]
Igree, it's cool :)
You know the OHM Studio? they have a cool animated splash too. 
The new Reaper too, a cool animated little splash.

When you open Jamtaba the "loading rooms" litle splash appears. And this little window appear in other moments (BusyDialog.h). May a CoolBusyDialog class ? :)

**Comment by Ezeer** [comment]
Ooooh YEah !
Thank you for the tip !
eh eh
--------------------------------------------
En date de : Sam 31.10.15, Elieser Ademir de Jesus <notifications@github.com> a écrit :

 Objet: Re: [JamTaba] SPlash screen ! (#73)
 À: "elieserdejesus/JamTaba" <JamTaba@noreply.github.com>
 Cc: "Ezee" <h2oreggae@yahoo.fr>
 Date: Samedi 31 octobre 2015, 20h59
 
 Igree, it's cool :)
 
 You know the OHM Studio? they have a cool animated splash
 too. 
 
 The new Reaper too, a cool animated little splash.
 
 When you open Jamtaba the "loading rooms" litle
 splash appears. And this little window appear in other
 moments (BusyDialog.h). May a CoolBusyDialog class ? :)
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Ezeer** [comment]
Wich animation format is used here ? looks like flash ...
Perhaps Stringer will be interested by that ?
I mean animate the logo he created .
![logojamtaba](https://cloud.githubusercontent.com/assets/1283808/10865727/c831b18c-8015-11e5-9f4c-b9cdf64c52d4.png)

**Comment by elieserdejesus** [comment]
I don't know what stringer is using, I suppose is just photoshop or CorelDraw.
The current BusyDialog animation is a animated gif.

**Comment by Ezeer** [comment]
good ! Gif is very easy to do ! ( perhaps even with online tools ...)
As it's Stringer's artwork , perhaps he will have a nice idea about the animation .
I can try something anyway .
( but have the original with the layers is better ...)

**Comment by elieserdejesus** [comment]
I will ask Stringer about the animation, I don't have the sources with the layers, etc.

**Comment by Ezeer** [comment]
Cool , thanks .
Waiting for news so .

**Comment by Ezeer** [comment]
I just had the idea to use Andre's louis jingles to come with : #83

**Comment by elieserdejesus** [comment]
good news! Stringer is working in a animation to use in the splash :)

**Comment by Ezeer** [comment]
Yes ! thank you Stringer !

**Comment by Ezeer** [comment]
Perhaps we should talk about the timing of the animation , in relation with jingles ?

**Comment by elieserdejesus** [comment]
Stringer ask me about the total time. I think 5 s is enough.

**Comment by Ezeer** [comment]
Okay , go for five : 
https://www.youtube.com/watch?v=PHdU5sHigYQ
;)

**Comment by Ezeer** [comment]
Some news from Stringer ?

**Comment by elieserdejesus** [comment]
Not yet.

**Comment by Ezeer** [comment]
I am on it .
I have played with the busyDialog class , i understand how it works .
Probably i will use it as ancestor for a new class SplashDlg
 , and use a Timer on it that will close the window automatically .

**Comment by Ezeer** [comment]
@elieser In BusyDialog class : 


//little to allow stylesheet in custom widget
    void BusyDialog::paintEvent(QPaintEvent* ){
        QStyleOption opt;
        opt.init(this);
        QPainter p(this);
        style()->drawPrimitive(QStyle::PE_Widget, &opt, &p, this);
}

**My question**: Can you tell me where to look in jamtaba.css ( line ) for it please ?
Because if it's in use , i will need to tweak it also for my child class SplashDlg .
Thx !

**Comment by elieserdejesus** [comment]
Ezee, check jamtaba.css in line 657.
```
BusyDialog{
  ....
}
```

If you create a new C++ class called EzeeDialog the stylesheet for your class will be
```
//in jamtaba.css
EzeeDialog{
     background-color: rgb(120, 120, 120);
     border: 1px solid red;
}
```

If you put a label (QLabel instance) inside your EzeeDialog, and you want a border in this label:
```
EzeeDialog QLabel{
     border: 1px solid black;
}

```

**Comment by Ezeer** [comment]
Nice ,thx !

**Comment by Ezeer** [comment]
As we already rock , i was thnking at a window that we could roll for the splash : 

![splash](https://cloud.githubusercontent.com/assets/1283808/11047845/c573e336-8734-11e5-9b92-7ed8eb113b01.jpg)

Rock and roll now !
lol

**Comment by elieserdejesus** [comment]
Interesing, a circular window :)

**Comment by Ezeer** [comment]
Yeah , for the floatings ones too !
;)

**Comment by Ezeer** [comment]
Tweak tweak tweak !
![tweak](https://cloud.githubusercontent.com/assets/1283808/11050297/e530b3f6-8744-11e5-9e0a-d60e4fce9676.jpg)

**Comment by elieserdejesus** [comment]
stylesheet are great hein Ezee? Now you are seeing why I totally adopt Qt :)

**Comment by Ezeer** [comment]
**hein Ezee?**
lol... your sister is back from Paris ?

Yeah , a lot of new things to learn for me , but the results are great when mastered is the stuff .
I think BusyDialog could be Orange man , and keep the workstation as great as it is .
( i can use Blender to make 3d models of tracks too , Gif it or whatever we'll need , even 3d opengl things. later.. having the console model (mesh ) in 3d space , monitor sound in 3d space etc ... )

**Comment by Ezeer** [comment]
twic twic twic ( some kind of groove eh eh )

![tweak2](https://cloud.githubusercontent.com/assets/1283808/11051173/2eccd0e6-874d-11e5-815e-7eb06074d28d.jpg)

**Comment by elieserdejesus** [comment]
Ezee, sometimes I use the QtCreator stylesheet editor to test some CSS stuff quickly. You type the css code and see the visual result:
![image](https://cloud.githubusercontent.com/assets/1012741/11051255/caa11e78-8734-11e5-8cd9-61883b9ab1fe.png)

**Comment by Ezeer** [comment]
Nice , thx !

A preview of orange squared Busy : 
![tweak3](https://cloud.githubusercontent.com/assets/1283808/11051283/25e06032-874e-11e5-9ee8-71ead0e3bbd6.jpg)

I'm gonna paint the gray gif in green to see if that could fit ...

**Comment by elieserdejesus** [comment]
I imagine something like this for the Jamtaba orange theme: 
http://www.fabfilter.com/images/screenshots/screenshot_volcano_full.jpg?v=1351607039

**Comment by Ezeer** [comment]
Ok , i'm gonna pick colors from there .
![greenloader](https://cloud.githubusercontent.com/assets/1283808/11051504/1c887eb4-8750-11e5-967d-e140057f8b9a.gif)

**Comment by Ezeer** [comment]
little preview for Orange/green busy : 
![tweak4](https://cloud.githubusercontent.com/assets/1283808/11053232/980cbfa0-875f-11e5-97d6-8b2940b713fd.jpg)

**Comment by Ezeer** [comment]
You know what ? Gif is somewhat limited for a great animated splashscreen .
And as it is planned to make a video chat one of these days , i was thinking : " why not use a video
for that splashscreen ? " 

So i will try to make a 3d animation with Blender , render in video and play it on Jamtaba splashScreen.
As it is planned also to use music with it , it could be embded in the video .
I'm gonna test that now ...
