### ISSUE TITLE
Large RAM use loading projects in Reaper

### ISSUE THREAD

**Issue by Krill0** [elieserdejesus/JamTaba#733]
Hi

When loading the projects created by Jamtaba, RAM use is quite high, one project was 600MB in Reaper RAM use. Not sure this is related to Jamtaba or Reaper, forgive me if this is unrelated to Jamtaba.

**Comment by jonjamcam** [comment]
hi @Krill0 . Maybe you have duplicates. Which of the options below did you check?

![image](https://cloud.githubusercontent.com/assets/15310433/23598476/7a6df690-0219-11e7-88c3-b618e7956c1b.png)

1.- Generate Clipsort file
2.- Generate RPP file
3.- Both

Each one of **Clipsort** and **Rpp** options are stored in complete separate folders (including the audio). This means if you checked both (default) you get jams recorded twice (more details here: https://github.com/elieserdejesus/JamTaba/wiki/Recording-your-Jams-in-multitracks)
.
It is safe to choose only one of the two (although "save multi tracks" has to be checked for jams to be recorded).

**Comment by Krill0** [comment]
Hi

I do have both checked. The issue I notice is after a jam is completed, opening the created project file (Reaper project.rpp)

**Comment by jonjamcam** [comment]
> I do have both checked. The issue I notice is after a jam is completed, opening the created project file (Reaper project.rpp)

Check your recording folder. If you're not using the "clipsort" folder you can safely delete it. It won't have any effect on the audio used by the "rpp" option (stored in the "audio" folder).

**Comment by jonjamcam** [comment]
> that should not be related to the amount of RAM used when opening the created project, right?

That's correct. The clipsort option should have no effect when opening the rpp file in reaper. Can you open the clipsort file (that's there anyway) and compare the RAM usage with the Rpp file?

**Comment by Krill0** [comment]
RAM use for the rpp is 573MB
RAM use for clipsort is 115MB

**Comment by jonjamcam** [comment]
> RAM use for the rpp is 573MB
RAM use for clipsort is 115MB

Well, that's some difference there. Can you please compare the folder sizes of both in disk("audio" folder vs "clipsort folder")? Both should be roughly the same size as they contain the same jam.

 If this is true (same size), then something's happening during the import process reaper does.
 If the sizes on disk are very different, then probably it's Jamtaba's issue, not reaper.

**Comment by Krill0** [comment]
Both folders are 138MB each (same size)

**Comment by elieserdejesus** [comment]
@Krill0 , can you share these projects to help test this issue? Maybe put in a dropbox account?  You can try compact and drop the files here in github too, but I'm not shure about the file size limit.

**Comment by Krill0** [comment]
I uploaded it to google drive: https://drive.google.com/file/d/0B0UiE9EuYy6sa3BEQUxKUk1zcXc/view?usp=sharing

**Comment by jonjamcam** [comment]
I imported the Rpp file into reaper. In my system it uses about 300 MB of RAM.

![image](https://cloud.githubusercontent.com/assets/15310433/23644945/7163f0e8-02e8-11e7-9ad1-8fae957f18e7.png)

The Clipsort file uses about the same RAM amount:

![image](https://cloud.githubusercontent.com/assets/15310433/23645064/06abd4c2-02e9-11e7-9b88-7490e94b69ca.png)

I'm using reaper 5.22 x64 in WIN7 x64. When imported I DIDN'T convert into WAV.

**Comment by elieserdejesus** [comment]
@Krill0 and @jonjamcam , I have no problems here, the 2 projects (clipsort and rpp) are using the same RAM ammount.

@Krill0 , by the way, this is a very nice jam, congrats!

**Comment by Krill0** [comment]
@elieserdejesus Thanks :)
Unfortunately I see that I uploaded the wrong project. Here is the one from which my original report or RAM use came: https://drive.google.com/file/d/0B0UiE9EuYy6sQmN5dVBIaXM4WWs/view?usp=sharing After updating Reaper to version 5.35 I get the following RAM use:
Merge 126MB
No Merge 482MB
rpp 498MB

**Comment by elieserdejesus** [comment]
hi @Krill0 , I loaded the clipsort and rpp and I have exactly **449 MB** in both. So we can discard a problem in JamTaba. The difference in *merge* size is not related with JamTaba too, this is a Reaper issue.
