### ISSUE TITLE
HELP !

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#74]
The Help menu on Jamtaba offers a link to the issue's page .
Cool .
But now we have a wiki and i just started to write a User guide .
So my idea is simple , add a new link to the wiki and the User Guide on Jamtaba's help menu .

And i need help guys to write that bible ...
![user_manual_icon](https://cloud.githubusercontent.com/assets/1283808/10865513/15aa3b30-800e-11e5-96d5-71aaace76499.png)

**Comment by jonjamcam** [comment]
I'm in.

**Comment by Ezeer** [comment]
Ooooh Yeaaah !
Man , i got only 2 words to say : YOU ROCK !
![giqqywl4](https://cloud.githubusercontent.com/assets/1283808/10865660/17af837c-8013-11e5-88c3-836af71c8ac7.jpg)

eh eh

**Comment by elieserdejesus** [comment]
Igree Ezee, I will add the links in website too.

**Comment by Ezeer** [comment]
Dream team !
Perhaps we could add Jon as collaborator in the project ?
That way we could assign him to that holy task ?
TaDaaaa !

**Comment by Ezeer** [comment]
Our dear lead programmer just made the changes , like i said : 
*" Just tried , fantastic . "*
:+1:

**Comment by elieserdejesus** [comment]
@jonjamcam , I add you as a contributor, now you can edit things. Thanks for your help!

**Comment by Ezeer** [comment]
![champagne](https://cloud.githubusercontent.com/assets/1283808/10866115/64dac698-8022-11e5-8fd7-d9443b9ea35b.jpg)

**Comment by Ezeer** [comment]
'found a tool to convert wiki help to pdf -> http://wkhtmltopdf.org/

**Comment by jonjamcam** [comment]
where do we start guys? I have read manuals for years, but never made one :D. 

On the other hand Jamtaba is very intuitive....

**Comment by Ezeer** [comment]
We have already a structure to fill for starter here : https://github.com/elieserdejesus/JamTaba/wiki/Jamtaba%27s-user-guide

Look at the upper right corner of that page , click Edit .
You are ready to go .
Feel free to improvise , we'll correct if needed , the most important will be the experience you transmit
to the user .
Also use the Markdown features to make a beautiful doc .
( click on styling with Markdown to see the detail of what you can do and how )
Welcome onboard !
:+1:

**Comment by jonjamcam** [comment]
ok. The user's guide has the basic info to start from. I was thinking about something more visual. Let me give you an example:

![codex seraphinianus_p38](https://cloud.githubusercontent.com/assets/15310433/10869768/bfc884e4-8097-11e5-9694-d8fc7fb4f070.jpg)

In this image above, you don't need to know what's written in order to understand what's happening. I like this approach into manual design because most people just want to start using the stuff, not reading much.

Does it make sense?

**Comment by Ezeer** [comment]
YOU ROCK !
^^

**Comment by elieserdejesus** [comment]
Totally agree, images rock! :)

**Comment by jonjamcam** [comment]
Playing with the overview page.

[jamtaba manual.pdf](https://github.com/elieserdejesus/JamTaba/files/24901/jamtaba.manual.pdf)

are we in the correct path?

**Comment by elieserdejesus** [comment]
Very good job jon, thanks for this!

**Comment by Ezeer** [comment]
Same here , congrats !
:)

**Comment by Ezeer** [comment]
About the images : 
Great for lambda users , but bad for blind people ...
Now we have an audience with that community , we should right now think " Accessibility " 
in each stuff we work on .

Perhaps with the help of Andre Louis ( https://twitter.com/FreakyFwoof ) our new friend we'll
find solutions that fit for visual diseases .

So Jon , keep going but think at our Accessibility label .
;)

**Comment by jonjamcam** [comment]
I agree Ezee. I'll do some research about  Accesibility. Here's what I've done so far with the manual. I took from all the links you provided. Any mistakes or suggestions are welcome!

[jamtaba manual_v.1.0.2.pdf](https://github.com/elieserdejesus/JamTaba/files/24933/jamtaba.manual_v.1.0.2.pdf)

**Comment by Ezeer** [comment]
Thanks Jon . I was talking to Andre Louis , and i paste your previous comment to him .
Here is his answer : 
>I'm really grateful to you guys for wanting to make your app the best it can be. Many developers simply don't care about accessibility at all, and it's irritating. There's one guy I work with, because I am a sound-designer as well. His app is for iPhone, and it's called BlindSquare. The developer's name is @IlkkaPirttimaa. He sent me this great testimonial. https://dl.dropboxusercontent.com/u/34719098/TestimonialAndreLouis.pdf …

**Comment by Ezeer** [comment]
Hey Jon , very good work !
I nticed an error in the overview part , the word " comunicate " .
Communicate is better eh eh

Good job !
:+1:

**Comment by jonjamcam** [comment]
I'm very close to finishing the manual. It's going to be at least 25 pages! But once it's done and everyone is satisfied, I'll merge it to the manuals page here. As always mistakes and suggestions are welcome!

[jamtaba manual_v.1.2.2.pdf](https://github.com/elieserdejesus/JamTaba/files/27496/jamtaba.manual_v.1.2.2.pdf)

**Comment by Ezeer** [comment]
I am looking at it , and i make a breakpoint at : 
**" But Why Jamtaba, instead of other simila programs? "**  page 4
Reason : We are not in competition but rather we encourage people to join a community with a
software that offers intuitive " gamaplay " and a nice interface ( plus VST use that is great ! )

So your formula sounds too competitive to me , we should position ourselves like "Yet another Client"
for ninjam . Then people will decide by themselves if we are the leaders or outsiders in that domain ?

But i understand your point , it is just a question of formula i think .

NOW : 
+ Page 7 is excellent ! ( just fix "To remove apath " ^^ )
+ Same for page 9 , just fix : **"You can use any comercially  "** ( but excellent too !! )
FIX :  end of page 12 **" affecting wha others"**
+ Page 13 is nice !

Your work is fantastic Jon , cool to read with beautiful screenshots !
To be continued ( i have to code a little ... )
^^

**Comment by elieserdejesus** [comment]
Jon, greate work!!  It's very good see all this info about Jamtaba in a PDF, thanks for this very helpfull thing!
I agree with Ezee, I prefer the "Another Yet Client" approach. 
Some months ago a ninjamer ask me in the chat: "What is yout sell point for Jamtaba?" And I say: I don't have one :)

In the chat page I found a typo: "tyoe".

The user's manual is beautifull!

**Comment by jonjamcam** [comment]
I'm on the same page, guys......just a little poison to the well......REMOVED!

**Comment by Ezeer** [comment]
P14 :  First check the “Save multi tracks” box and select the correct path in
the **Recrding** Tab

Keep going !
:v:

**Comment by jonjamcam** [comment]
"And i need help guys to write that bible ..."

MY GOD! ALLEEEEELLUYYYAAA!

**Comment by Ezeer** [comment]
Ah AH AH AH !
:100:

**Comment by jonjamcam** [comment]
Now updating part of the users guide so it is online. I´m using version 2.0.2 of the manual, It will be complete by Sunday (both, I hope).

[jamtaba manual_v.2.0.2.pdf](https://github.com/elieserdejesus/JamTaba/files/28923/jamtaba.manual_v.2.0.2.pdf)

**Comment by Ezeer** [comment]
It is not only in our code that there is trouble with the servers connection .
eh eh
**" Inside the Server in detail "**  p16 , the texts are ...mooving .
Fiction or reality ?

You know what , i will choose a good quality paper and print that babe !
:two_hearts: for Jamtaba's manual

**Comment by Ezeer** [comment]
And that would be great to have an *autograph* from you at the end !
;)

**Comment by jonjamcam** [comment]
LOL!

**Comment by jonjamcam** [comment]
The manual is complete guys and updated inthe page. Check it out! Hope nothing is missing.

[jamtaba manual_v.2.4_FINAL COPY.pdf](https://github.com/elieserdejesus/JamTaba/files/29400/jamtaba.manual_v.2.4_FINAL.COPY.pdf)

**Comment by elieserdejesus** [comment]
Jon, this is a very good work! Thanks for your time testing and collaborating, this is great!

**Comment by jonjamcam** [comment]
It's an honor to be part of the Jamtaba Team! BTW I will test a B/W version just in case for printing...

**Comment by Ezeer** [comment]
when i say that i read the doc .... p12
>In Jamtaba you can have up to two independent channels each of
which can have two sub channels more. The two channels are sent
to the jam room **separate separate** from each other so others in the
room can adjust the mix in their local computers.

**Comment by Ezeer** [comment]
last minute idea : 

It would be better to have another font for the code parts : 
>default.INFO: Reading settings from “C:/Documents and Settings/
Salon/Local Settings/Application Data/Jamtaba 2/ Jamtaba.json”
jt.Audio.INFO: initializing portaudio...
jt.Audio.INFO: Starting portaudio driver using ASIO4ALL v2 as
device.
jt.Audio.INFO: Starting portaudio driver using 512 as buffer size. 

or use italic ?
Because that must be ezee to read , yah know ?

**Comment by jonjamcam** [comment]
"And why you removed the Logo at the end ?"

It's still there. I just removed "by Jon". I think It's better to sign "the Jamtaba team".

BTW I'll correct the mistakes tonight! THX for revising it.

**Comment by Ezeer** [comment]
sorry sir , but the logo is no more in the pdf version .
It is just a detail anyway .
thx jon !

**Comment by jonjamcam** [comment]
Ohhh the pdf.....don't remember to put it at the end...what version of the manual has it?

**Comment by jonjamcam** [comment]
Should I put the logo at the end too? I think that was in the user guide....

**Comment by Ezeer** [comment]
well , it is springer's artwork and our magnetic signaletic !
lol

**Comment by jonjamcam** [comment]
Yea...Ezee can you explain again the corrections....I only understood the first one "separate separate" and the last one "add space line" to the debug lines...

**Comment by Ezeer** [comment]
lol , the other was congrats only !
I think you(ve got it : 
![image035](https://cloud.githubusercontent.com/assets/1283808/11017556/2f6129ea-85a3-11e5-8469-df789fa43404.gif)

**Comment by Ezeer** [comment]
lol -> https://www.youtube.com/watch?v=74Im6zOHeow

**Comment by jonjamcam** [comment]
lol!

**Comment by jonjamcam** [comment]
Corrected versions:

[jamtaba manual_v.2.53.pdf](https://github.com/elieserdejesus/JamTaba/files/29462/jamtaba.manual_v.2.53.pdf)

[jamtaba manual_v.2.53_B&W.pdf](https://github.com/elieserdejesus/JamTaba/files/29463/jamtaba.manual_v.2.53_B.W.pdf)

**Comment by Ezeer** [comment]
Nice !
I just think now that the 2nd page could be ... a table of content .
Because when you got a problem , you search quick to a solution ...

**Comment by jonjamcam** [comment]
Good idea Ezee!

**Comment by Ezeer** [comment]
thanks ! I updated also the manual online with our new magnetic badge : 
![output_j5j8ws](https://cloud.githubusercontent.com/assets/1283808/11020506/e6bec3e0-8620-11e5-981e-2080d4292be1.gif)

**Comment by jonjamcam** [comment]
I used "Owner's manual" in the first page, but "User's guide" may be a better choice

**Comment by elieserdejesus** [comment]
I gree, User's guide is better. It's a free software, so nobody is a real "owner" :)

**Comment by jonjamcam** [comment]
True......This brings to mind a talk Richard Stallman gave last year where he differentiates "free software" from "open source software".

https://www.youtube.com/watch?v=2lupgHYiK9Q
