### ISSUE TITLE
[Looper] Loading several audio files skips some files when not enough empty layers available

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#744]
What I found is that to load several files in one take you need to have first all the empty layers needed available. If there are too few layers, some will be skipped.

**Comment by elieserdejesus** [comment]
Exactly @jonjamcam , this is the expected behavior at moment. I implemented this "skip" behavior to preserve current loaded audio. 

We can change this behavior to preserve locked layers only, or just replace all layers. I'm not shure about the best option in this case.

**Comment by jonjamcam** [comment]
It works fine IMO. The only change I would make is that the looper detects how many layer it will need for import and add them automatically first, instead of the user adding them manually.

**Comment by elieserdejesus** [comment]
fixed in 295c988bca67215197201d92a89938abb42bbc26, the layers are automatically created now.
