### ISSUE TITLE
 [looper ] mute button for layers

### ISSUE THREAD

**Issue by qulf** [elieserdejesus/JamTaba#745]
yes when i using now i just looking for mute button for specific layers.

**Comment by jonjamcam** [comment]
One addition for a mute button for each layer could be the ability to group the mutes in Presets (quick buttons) to recall a certain "mute setup"

**Comment by elieserdejesus** [comment]
> "program" the mute

Nice idea @jonjamcam . 
**What you think about**: when looper is stopped the mute button will mute in "real time", and when looper is playing the mute button will wait for next round (programmed mute).  Same idea applyed for "unmute".

>  group the mutes in Presets

This is more trick, let's delay this to the next JamTaba version :)

**Comment by jonjamcam** [comment]
> when looper is stopped the mute button will mute in "real time", and when looper is playing the mute button will wait for next round (programmed mute). Same idea applyed for "unmute".

@elieserdejesus Mute in real time when stopped is good. But we need a way to mute in realtime also when playing. I will borrow an idea from mobius (that I used extensively before).

when playing:
1.- one click to the mute button: mute in the next loop.
2.- double click to the mute button: mute in real time.

when stopped always mute in real time.

Any thoughts?

**Comment by elieserdejesus** [comment]
> when playing:
1.- one click to the mute button: mute in the next loop.
2.- double click to the mute button: mute in real time.
when stopped always mute in real time.

Interesting @jonjamcam , I will try this approach soon.

**Comment by jonjamcam** [comment]
> Interesting @jonjamcam , I will try this approach soon.

One precision. It's not exactly a double click as a "fast click click" . It's more a "second click" over an already muted layer. But I let you @elieserdejesus decide which is more doable and intuitive.
