### ISSUE TITLE
[Looper] delete button for layers

### ISSUE THREAD

**Issue by qulf** [elieserdejesus/JamTaba#749]
We have reset button and that clear alllayers and settings. Mayby aditional button delete just for delete all layers but keep pan/volume settings ?

**Comment by qulf** [comment]
Or maybe one reset button with two modes. That is not necessary just small improvements. Loper looks and works nice.

**Comment by jonjamcam** [comment]
We could use the mouse click/double click feature to do the selection:

1.- one click to the reset button: reset layers only
2.- double click to reset button: reset all.

This way we don't add a new button. What do you think @qulf and @elieserdejesus ?

NOTE: Mute states of layers are not reset when pressing the reset button. I think this is related. Didn't want to create a separate issue for this :D .

**Comment by elieserdejesus** [comment]
@jonjamcam and @qulf , I'm thinking in add a menu in reset button with 3 entries: reset layers content, reset layers controls, and reset all. The menu will work like the "Load" button menu.

> Mute states of layers are not reset when pressing the reset button.

Is better create a separated issue @jonjamcam . Creating a separated issue is better to help remember missing/pending stuff.

**Comment by jonjamcam** [comment]
> Mute states of layers are not reset when pressing the reset button.
> Is better create a separated issue 

Issue created https://github.com/elieserdejesus/JamTaba/issues/755

**Comment by jonjamcam** [comment]
>  I'm thinking in add a menu in reset button with 3 entries: reset layers content, reset layers controls, and reset all. The menu will work like the "Load" button menu.

That sounds good to me @elieserdejesus .

**Comment by elieserdejesus** [comment]
Reset menu implemented: 
![image](https://cloud.githubusercontent.com/assets/1012741/24087004/cec46eca-0cf7-11e7-834b-dad9c448eb22.png)

**Comment by jonjamcam** [comment]
Nice! works great!
