### ISSUE TITLE
Cant vote under 60 bpm automaticly - reported by Magnus

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#75]
by hand typing it works) in VST mode on reaper 64 PC win8

**Comment by elieserdejesus** [comment]
Solved, and fixed bugs in BPI and BPM. Now Jamtaba is allowing BPI [3, 64] and BPM [40, 400]

**Comment by Ezeer** [comment]
wow , the return of BugKiller ?
![homer-gun-1jpeg](https://cloud.githubusercontent.com/assets/1283808/10869304/8261bf8a-80ab-11e5-8b8c-894c13280ceb.gif)
