### ISSUE TITLE
[Looper] Save loops as 32bit float files

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#751]
@elieserdejesus Is it possible to add in the preferences a 32bit wav file checkbox?

![image](https://cloud.githubusercontent.com/assets/15310433/24045919/7c7ec952-0aff-11e7-8c8e-4b7defa5f3d3.png)

Just to avoid the limiting (clipping) of the default 16bit files.

**Comment by elieserdejesus** [comment]
@jonjamcam , this is possible. 
But use the 2 checkboxes will be confuse because users can check the 2 checkboxes. I changed the layout to have ogg and wave with bit rate options:

![image](https://cloud.githubusercontent.com/assets/1012741/24050596/135629c0-0b0e-11e7-956d-be18e2ab0b4a.png)

**Comment by jonjamcam** [comment]
looks nice! so the 16 bit wav will be clipped and the 32 bit won't?

**Comment by elieserdejesus** [comment]
> so the 16 bit wav will be clipped and the 32 bit won't?

Exactly, JamTaba internal audio processing is 32 bit. Save the samples in a 32 bit wave file is just *dump the raw samples in a file*, no conversions, no hard clipping. But if you play very loud and save the loop, your audio will produce a audible clip/cracle in some moment, possibly when the samples reach the D/A conversor in your audio interface.

**Comment by jonjamcam** [comment]
>  But if you play very loud and save the loop, your audio will produce a audible clip/cracle in some moment, possibly when the samples reach the D/A conversor in your audio interface.

Ohh yes, i'm aware of that. No problem. THX for considering this @elieserdejesus . This is very good news for me.
