### ISSUE TITLE
[Looper] show each loop BPM when loading

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#754]
The problem is you can't know what loop has what BPM, so when loading into a different BPM, the loop doesn't fit.

I think adding the BPM of each loop in the loading menu can be of use:

![image](https://cloud.githubusercontent.com/assets/15310433/24084433/fbabd86c-0cc8-11e7-9c2f-74fcdd2882cb.png)

Another problem is getting the loop information when browsing loops outside the default folder. Is it possible @elieserdejesus to add the layers, BPI and BPM in some way? I've seen other software that show some extra info in the load dialog:

![image](https://cloud.githubusercontent.com/assets/15310433/24084487/c4348d42-0cc9-11e7-8ab3-d0c9042bfc13.png)

**Comment by elieserdejesus** [comment]
> The problem is you can't know what loop has what BPM

@jonjamcam , in your image all the listed loops are **120 BPM loops**. Only the "BPM matched" loops are listed:
![image](https://cloud.githubusercontent.com/assets/1012741/24087054/646b1b54-0cf8-11e7-9f42-a1f80f41823d.png)

> Another problem is getting the loop information when browsing loops outside the default folder. Is it possible @elieserdejesus to add the layers, BPI and BPM in some way? 

Is possible, I will work in this idea.

**Comment by jonjamcam** [comment]
>  in your image all the listed loops are 120 BPM loops. Only the "BPM matched" loops are listed

@elieserdejesus That is not the case in my machine. As a matter of fact all the loops saved are different 
BPM. Some examples from the image above:

![image](https://cloud.githubusercontent.com/assets/15310433/24087321/41831174-0cfc-11e7-87f0-18a08aeaea67.png)

![image](https://cloud.githubusercontent.com/assets/15310433/24087312/1f78b782-0cfc-11e7-86c1-aa403b57b92c.png)

![image](https://cloud.githubusercontent.com/assets/15310433/24087303/ff5fad5c-0cfb-11e7-9eab-c18d58d226ed.png)

 Maybe that is the problem? It has never filtered loops, at least in my system.

**Comment by elieserdejesus** [comment]
> Maybe that is the problem? It has never filtered loops, at least in my system.

I will check this @jonjamcam , I think this bpm filter issue is bugged.

**Comment by elieserdejesus** [comment]
@jonjamcam , it's too complicated show the loop infos in file browser. Using a native file dialog the solution is not cross plataform. I tested the Qt file dialog and works, but qt file dialog is very ugly and non intuitive. We can try again in future, for now I'm just moving on.

**Comment by jonjamcam** [comment]
>  it's too complicated show the loop infos in file browser. Using a native file dialog the solution is not cross plataform. I tested the Qt file dialog and works, but qt file dialog is very ugly and non intuitive. We can try again in future, for now I'm just moving on.

Thx for the try. No need to worry about this one in the future @elieserdejesus . It's really a minor detail.
