### ISSUE TITLE
[Looper] Possibility to program the play button to stop at the end of the loop

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#761]
From https://github.com/elieserdejesus/JamTaba/issues/712#issuecomment-288423422

It would be useful (at least for me as a drummer) to be able to program the play button to stop at the end of the loop so I can alternate from loop/live better. We could use the trick of one/two clicks used in the mutes, for example.

**Comment by jonjamcam** [comment]
@elieserdejesus what do you think about implementing the blinking buttons (used in the layer mute button) for REC and PLAY too?

**Comment by elieserdejesus** [comment]
> what do you think about implementing the blinking buttons (used in the layer mute button) for REC and PLAY too?

Shure @jonjamcam , I think this is the best idea too.  It's always very good reuse the UI patterns, users don't need re-learn how the UI works.
