### ISSUE TITLE
[Looper] Improve monitoring of input signal in recording waiting state

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#764]
About what you hear (input signal) during the recording **waiting** state. At the moment when **recording**, the input signal goes through the looper, not the channel and this is good behavior. But when in ** recording waiting state**, the signal is still going through the channel which I think should be going through the looper too.

It makes sense to me because the recording waiting state is related to the recording state and I think it's good to be able to listen to the "real" signal you're about to record.

**Comment by elieserdejesus** [comment]
> the signal is still going through the channel which I think should be going through the looper too.
It makes sense to me because the recording waiting state is related to the recording state and I think it's good to be able to listen to the "real" signal you're about to record.

I agree 101% :)
