### ISSUE TITLE
[Looper] Removing layers do not make "*" appear at the end of loop name

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#765]
![image](https://cloud.githubusercontent.com/assets/15310433/24293848/83e89fb0-1072-11e7-8455-dd40a714ae1c.png)

**Comment by jonjamcam** [comment]
@elieserdejesus I think this issue is related:

using "reset layer content"in the menu is not showing the "*" too.

**Comment by elieserdejesus** [comment]
Fixed in last commit @jonjamcam !

**Comment by jonjamcam** [comment]
@elieserdejesus another related issue :smile: : 

I think changing **looper mode** and **layer number** should also show the "*"

**Comment by elieserdejesus** [comment]
Done :)
