### ISSUE TITLE
[Looper] "Hear locked" during recording waiting state monitoring not as expected (Sequence mode only)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#767]
To reproduce:

1.- load a loop with three or more layers
2.- lock two layers and click "play locked" and hear all/locked.

At this point you can hear two layers only (locked ones) as expected.

3.- focus on any unlocked layer that has data and press record.
4.- During the **recording waiting state** you can only hear the layer that's being recorded (not expected). The expected behavior is to hear the two layers only (locked ones). 

If you actually let the recording start after the waiting state, then you can hear what was expected.

NOTE: Only if overdub is clicked, then the layer that's being recorded should be heard along with the locked ones (recording and recording waiting state)

**Comment by elieserdejesus** [comment]
@jonjamcam , can you check this issue again? I think the last commit in master solved this issue (at least in my test). The last commit in master changed Record and Waiting states, now Rec and Waiting are using same code to mix.

**Comment by jonjamcam** [comment]
@elieserdejesus 

Yes. It's OK now. The locked layers monitoring is solved.:D

**Comment by elieserdejesus** [comment]
thanks!
