### ISSUE TITLE
Release v2.0.20 tasks

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#769]
- [x]  ES translation
- [x]  PL translation
- [x]  PT translation
- [x]  FR translation
- [x]  DE translation
- [x]  JP translation (done with google translator)
- [x] Finish pending issues
- [x] Add Torben translation
- [x] Update translators in website
- [x] Update pre-built libraries link in dropbox
- [x] Post the new release in facebook page

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , @qulf, @MagnusDrumsTrumpet , @DoublebassOO,  @NakajimaYusuke and @takeshitaleo! JamTaba version 2.0.20 is comming! We have some new texts to translate. If you have some free time please help us updating the translation files.

Thanks in advance!

**Comment by MagnusDrumsTrumpet** [comment]
hey Eli thy so much  fantastic work)))did you get the translate on github   ?
cu soon ) 

Mag

 

    Elieser Ademir de Jesus <notifications@github.com> schrieb am 23:51 Samstag, 25.März 2017:
 

 Hi @jonjamcam , @qulf, @MagnusDrumsTrumpet , @DoublebassOO, @NakajimaYusuke and @takeshitaleo! JamTaba version 2.0.20 is comming! We have some new texts to translate. If you have some free time please help us updating the translation files.Thanks in advance!—

**Comment by elieserdejesus** [comment]
Yes @MagnusDrumsTrumpet , your changes are merged now. Thanks again!

**Comment by jonjamcam** [comment]
@elieserdejesus es_CL update complete in https://github.com/elieserdejesus/JamTaba/pull/773!

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , es_CL merged!

**Comment by DoublebassOO** [comment]
I done the translation in French  of this wonderful version  of Jamtaba  

Bravissimo !!!  You make a great job and this seems to work so greatly    *WOW  !!!!!!!!

I will try to propose things that i think are impossible to code ... :)

**Comment by elieserdejesus** [comment]
thanks @DoublebassOO 😄

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , @DoublebassOO , @MagnusDrumsTrumpet , @qulf , @Hitrate, @Trashcanhead1111 !!

JamTaba version **2.0.20 pre-release** is available [HERE](https://github.com/elieserdejesus/JamTaba/releases)!
Please give a try and help testing before the official release (possibly in next wekeed).

**The changes are:**
- [New] Built-in audio Looper
- [New] Improvements in audio processing performance
- [AU Plugin] Fixing AU plugin validation on Logic
- [AU Plugin] Fixing AU plugin crash in Logic when audio buffer size is changed
- [VST plugin] Fixing keystrokes in Sonar
- [Bug fix] Fixing misplaced midi routing arrow in Standalone
- [Bug fix] Fixing user and channel name change in VST/AU plugin
- [Bug fix] Fixing MidiTools Learn function 

Thanks in advance!

**Comment by Hitrate** [comment]
Hey Elieser, looks great ! I can't sync in Mainstage, is that possible to look into? It brings me the popup saying to set mainstage to bpm XXX unlike in logic where it then once the tempo is set says press start to sync...

Also on the sync issues: in lpx when the bpm changes while in a room, when I change the bpm in lpx and then sync up, my sequencer is now not starting at 1. I believe it might also have to do with things on my end (perhaps a setting I need to change) but it would be nice if somehow it could make sure to start back from 1 automatically..

Small feature request: resizable window so text and all would be bigger or smaller and/or everything else would be smaller or larger depending on your needs, so it could be full screen without having to lower the screen resolution for instance :) also I am having a bit worse connection than in reaninjam for some reason...oh and lastly: in mainstage jamtaba is using 100% CPU 

Cheers

Torben Scharling

**Comment by jonjamcam** [comment]
@Hitrate Hey Torben. Jon, here. One little trick to quickly increase the chat font size:

![image](https://cloud.githubusercontent.com/assets/15310433/24779809/00af995e-1b09-11e7-9120-60a9dfab09ac.png)

 Go to the **Themes Folder** ([user]/AppData/Roaming/JamTaba 2/Themes). Select the theme you want to edit and find the file called **Chat.css** in any text editor (every theme has a different file). 

Now add the following lines in red circles (please copy it EXACTLY AS BELOW):

`font-size: 20px;`

![image](https://cloud.githubusercontent.com/assets/15310433/24779900/b45f4206-1b09-11e7-9372-535695c117b0.png)

you can experiment with the PX number until you get a useful result. If you make a mistake, don't worry just **delete the themes folder** ONLY and Jamtaba will create it by default when launched again.

This is the result when using:

`font-size: 15px;`

![image](https://cloud.githubusercontent.com/assets/15310433/24780219/f0b84598-1b0b-11e7-908a-16a1d09a8891.png)

**Comment by elieserdejesus** [comment]
thanks for your detailed report Torben, I will add a new issue (#803) to work in these Mac details soon.

**Comment by elieserdejesus** [comment]
Hi again @jonjamcam , @qulf, @MagnusDrumsTrumpet , @DoublebassOO, @NakajimaYusuke, @takeshitaleo, @Hitrate , a new JamTaba pre-release is available. I will wait some days before the official release. Please help using this pre-release and reporting the problems.

[https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.20-pre-release-2](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.20-pre-release-2)

**Comment by Hitrate** [comment]
Awesome !! Looking forward to it :) I went ahead and translated the en.ts file (from beta 1) to Danish, but don't have access to do it via github so here it is...:
[translate-v2.0.20-ja_DK.ts.zip](https://github.com/elieserdejesus/JamTaba/files/953218/translate-v2.0.20-ja_DK.ts.zip)

**Comment by elieserdejesus** [comment]
Thanks for this translation Torben, very nice contribution. The result:
![image](https://cloud.githubusercontent.com/assets/1012741/25363889/8d019626-2934-11e7-9d75-f853742cba6e.png)

**Comment by jonjamcam** [comment]
@elieserdejesus and @qulf : 

With regards to translations there's only one string missing in **pt_BR** (L.453) and **pl_PL** (L.450) for all translations to be complete:

"Loop file already exists. Do you want to overwrite?"

**Comment by elieserdejesus** [comment]
> there's only one string missing in pt_BR (L.453) 

pt_BR translated in last commit @jonjamcam !

**Comment by Hitrate** [comment]
@jonjamcam & @elieserdejesus thx! I have corrected a few mistakes from last nights translation, but not added the two ones you mentioned jon, as they are correctly translated but there is no <translate> text underneath those two sentences, so I did not translate them and don't wanna put them in wrong in the code :) I really should learn how to program......

**Comment by jonjamcam** [comment]
>  I have corrected a few mistakes from last nights translation in the b2 zip file below

@Hitrate There were some last minute changes to all transaltions, so probably the file you used as source has some obsolete strings.

Can you please check the updated file here? https://github.com/elieserdejesus/JamTaba/blob/master/translations/da_DK.ts

If you want you can correct any string directly using github's little pencil:

![image](https://cloud.githubusercontent.com/assets/15310433/25386652/76f2752a-299e-11e7-8ca7-3c82b09c136a.png)

**Comment by jonjamcam** [comment]
> change this to: Sync with %1 : "synkroniser med %1") but there is no "translate" text field underneath those two sentences,

@Hitrate Sometimes there's a comment explaining the context in which the string is used:

![image](https://cloud.githubusercontent.com/assets/15310433/25399184/eae1742e-29c4-11e7-8d57-73a8ab9aabff.png)

Translations are very dynamic because of context. If you find more strings that need modification, just create another Pull Request before the final release is out. (I corrected this little one for your convenience in https://github.com/elieserdejesus/JamTaba/pull/840)

**Comment by jonjamcam** [comment]
To all who contributed to this amazing release I just want to say thank you. I just realized that during the last month something fantastic happened to me as a musician and the catalyst for this was the new tool available in this upcoming Jamtaba release (the ninjam looper). 

I went into composing little bits of music again for the first time in years. The possibility to record loops easily and in a reliable way made me tune again my guitar, load some keyboard plugins, etc. and record ideas before they went away. I have now more that 100 little riffs and ideas to work on for the next years!

 Last time I was in a creative mode like this was before I discovered ninjam, but back then it was not as fun as it is today.

So again, thanks for the ideas and for making it happen. Special thanks to you @elieserdejesus for all the love and energy you put into this project. I feel small compared to your huge input and energy. It's above all, truly inspiring.

Jon.

**Comment by elieserdejesus** [comment]
Jon, these are very nice words! Thank you for all help testing, thinking, planing, discussing, fixing, translating, etc. It's a pleasure for me receive your contributions, and a big pleasure see the people using JamTaba and being creative. 

Your contributions and feedback are keeping me "tuned". Without feedback and contributions an open source project like JamTaba make no sense. 

Thanks everybody, it's always a pleasure share ideas with very talented people. Long life for us! See you!!!

**Comment by jonjamcam** [comment]
@Hitrate 

Torben, I found one missing translation tagged "unfinished" in line 930 of the da_DK transaltion:

![image](https://cloud.githubusercontent.com/assets/15310433/25462262/4e8d1f82-2ac4-11e7-848e-333c4846d743.png)

this refers to the shape of the metronome:

![image](https://cloud.githubusercontent.com/assets/15310433/25462311/9018cb9a-2ac4-11e7-8c22-0be56ae9bf82.png)

**Comment by jonjamcam** [comment]
@qulf @elieserdejesus I completed the missing string of pl_PL locale with a google translation in https://github.com/elieserdejesus/JamTaba/pull/850.

Now all translations are complete!

**Comment by qulf** [comment]
Sorry i am busy now. I will look later today for pl wersion

**Comment by qulf** [comment]
ok . corrections are done now. On prerelase 2.0.20 polish translation for looper does not work properly. i just see english on loopers side.

**Comment by jonjamcam** [comment]
@qulf I closed https://github.com/elieserdejesus/JamTaba/pull/850 unmerged so you can translate it yourself.

**Comment by elieserdejesus** [comment]
@MagnusDrumsTrumpet , @jonjamcam , @DoublebassOO , @Hitrate , @qulf , a new JamTaba pre-release is available. I think this one is solid enough to be the official release. The plan is release officially until next friday: https://github.com/elieserdejesus/JamTaba/releases/tag/v2.0.20-pre-release-3

**Comment by jonjamcam** [comment]
> The plan is release officially until next friday

This one is going to be massive!

**Comment by jonjamcam** [comment]
> Update translators in website

Japanese revision and corrections for 2.0.19 and 2.0.20 by **Pipaxis**

**Comment by elieserdejesus** [comment]
> Japanese revision and corrections for 2.0.19 and 2.0.20 by Pipaxis

thanks for remember @jonjamcam

**Comment by jonjamcam** [comment]
@elieserdejesus Manual for 2.0.20 is complete!

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam , awesome work in Looper manual https://github.com/elieserdejesus/JamTaba/wiki/Ninjam-Looper.

**Comment by jonjamcam** [comment]
Thx @elieserdejesus This is a great project. Jamtaba works great!

**Comment by elieserdejesus** [comment]
Hello guys, new JamTaba version released! Thanks again for all help and contributions!

**Comment by jonjamcam** [comment]
I tested 2.0.20 in my old Pentuim 4 XP computer and the result is amazing. It uses much less CPU than 2.0.19. Very stable indeed.

**Comment by elieserdejesus** [comment]
> I tested 2.0.20 in my old Pentuim 4 XP computer and the result is amazing. It uses much less CPU than 2.0.19. Very stable indeed.

Nice news @jonjamcam !

**Comment by DoublebassOO** [comment]
great release !!  bravo




2017-05-04 23:31 GMT+02:00 Elieser Ademir de Jesus <notifications@github.com
