### ISSUE TITLE
Auto scan new VST plugins

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#77]
In modern and cool DAWs if you put some new VST plugin in yout plugin folder next time you open the DAW you see your new plugins. At Jamtaba is not showing the "fresh installed plugins". User need "Refresh" the plugin cache to re-scan.

**Comment by Ezeer** [comment]
good idea !
My first idea would be to call the Refresh->onClick() at loading time .

**Comment by Ezeer** [comment]
When i look to that code : 
//REFRESH VST LIST
      void PreferencesDialog::on_ButtonVst_Refresh_clicked()
             {
    if(mainController)
    {
        if(mainWindow)
        {//save the config file before start scanning
            mainController->saveLastUserSettings(mainWindow->getInputsSettings());
        }
        //clear the cache
        mainController->clearPluginsCache();
        //scan again
        mainController->scanPlugins();
    }

    populateVstTab();
}

i think we could make a global funk in mainController to make 3 on 1 : 

void UpdateVst()
{

 if(mainWindow)
        {//save the config file before start scanning
            mainController->saveLastUserSettings(mainWindow->getInputsSettings());
        }
        //clear the cache
        mainController->clearPluginsCache();
        //scan again
        mainController->scanPlugins();
}

That would give : 
void PreferencesDialog::on_ButtonVst_Refresh_clicked()
             {
    if(mainController)
    {
      mainController->UpdateVst();
    }

    populateVstTab();
}

**Comment by Ezeer** [comment]
The idea was to use mainController->UpdateVst() now at startup , and not the refresh button's method .

**Comment by Ezeer** [comment]
So elieser , you want an auto refresh at startup or not ?

**Comment by elieserdejesus** [comment]
Ezee, this feature is very good for users. When I add some new plugin I expect my DAW "see" this plugin automatically. At moment Jamtaba is not doing this.

I think the solution is not simple as run UpdateVst() in start. We need a more elegant solution. 
If we just re-run the UpdateVst() all the plugins are re-scanned, and this can be time consuming and annoying for users. A really good solution is detect the "new" plugins and scan just these plugins. If the user add one plugin we will scan just this new plugin, probabily a very quick scan.

**Comment by Ezeer** [comment]
Ok . So ... How do you know that a folder content has changed ?
You make an image of the directory ? ( there could be more than one , remember ? ) .

I think it's better to rewrite the scan for skip the files that are already in the Json file .
( record the names of all vst in the folder , next time compare with actual content ? If one is unknown , scan it )
And thus use UpdateVst() when jtb starts without being boring .
Also , we'll soon have a 5 seconds max splash screen that could serve to hide that process .

**Comment by elieserdejesus** [comment]
Ezee, I think this approach is good. 
Another improvement is "scan for new plugins"  whithout showing the ScanDialog. This is necessary to not polute the GUI. If we scan at start, and the splash is visible, we will show 3 windows for users: the main window in background, the splash, and the ScanDialog. 
Another possibility is change the scan status in splash, some DAWs are using this approach.

Again Qt is helping a little: [http://doc.qt.io/qt-5.5/qsplashscreen.html](http://doc.qt.io/qt-5.5/qsplashscreen.html)

**Comment by Ezeer** [comment]
thank you , i like " Another possibility is change the scan status in splash " .
