### ISSUE TITLE
[Looper] some translations of "hear all/locked" do not fit correctly

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#776]
@elieserdejesus and @qulf : 

It's happening with PL, PT, ES (and I guess french will too) translations:

![image](https://cloud.githubusercontent.com/assets/15310433/24355760/8dc6b1ea-12cd-11e7-8e4e-50c6acfd51fd.png)

I used abbreviation for the ES translation to fix it:

![image](https://cloud.githubusercontent.com/assets/15310433/24355845/e261ceb0-12cd-11e7-84b9-91a0ae979671.png)

**Comment by qulf** [comment]
i made shorter translation "odtwarzaj zablokowane" . corect way is "odtwarzaj wszystke zablokowane". shorter is still too long

**Comment by qulf** [comment]
let me think i need time

**Comment by qulf** [comment]
ok i add some changes. "Odsłuch/zabl.". can you help me with that? that is 433 line

 <source>Can&apos;t load the file &apos;%1&apos;</source>
        <translation type="unfinished"></translation>

i leave that untuched

**Comment by qulf** [comment]
sorry but github dont let me to copy code. that is on line 433 in pl_PL.ts

**Comment by jonjamcam** [comment]
@qulf I created PR https://github.com/elieserdejesus/JamTaba/pull/778 to correct the "Odsłuch/zabl.". string, but it's not in like 433

**Comment by qulf** [comment]
i know but on 433 there is something and i have problem with that

**Comment by qulf** [comment]
i try copy here
Can&apos;t load the file &apos;%1&apos;

**Comment by qulf** [comment]
but after post that change for only "Can't load the file '%1'" but code looks different

**Comment by jonjamcam** [comment]
@qulf Paste the translation of line 433 here. I will add it to the PR. You need to use Qtlinguist in this cases

**Comment by qulf** [comment]
translation for "Can't load the file '%1'"- "Nie mogę załadować pliku "

**Comment by elieserdejesus** [comment]
@jonjamcam  and @qulf , I think in this case is better keep the translations and just enlarge the looper window. The looper window is not big, add some pixels will be a good enough solution.

**Comment by jonjamcam** [comment]
> @jonjamcam and @qulf , I think in this case is better keep the translations and just enlarge the looper window. The looper window is not big, add some pixels will be a good enough solution.

OK @elieserdejesus .

@qulf I'll use PR https://github.com/elieserdejesus/JamTaba/pull/778 for  **"Can't load the file '%1'"- "Nie mogę załadować pliku "** then.

**Comment by jonjamcam** [comment]
@qulf the complete phrase is Nie mogę załadować pliku '%1'?

![image](https://cloud.githubusercontent.com/assets/15310433/24366004/339d1c88-12ee-11e7-914d-6318c73058cf.png)

**Comment by qulf** [comment]
yes looks good

**Comment by jonjamcam** [comment]
@qulf what phrase shall we use in the "hear all/locked"? I can correct it in the same PR:

1.- "odtwarzaj zablokowane"
2.- "odtwarzaj wszystke zablokowane".

**Comment by qulf** [comment]
"odtwarzaj wszystke/zablokowane" that is perfect

**Comment by qulf** [comment]
"odtwarzaj wszystkie/zablokowane" sorry that is perfect

**Comment by qulf** [comment]
misiing letter i

**Comment by jonjamcam** [comment]
Ok it's corrected with "odtwarzaj wszystkie/zablokowane"

**Comment by qulf** [comment]
ok :)

**Comment by jonjamcam** [comment]
@elieserdejesus the full transaltions of "hear all/locked" for es_CL and pl_PL are ready in https://github.com/elieserdejesus/JamTaba/pull/778 and https://github.com/elieserdejesus/JamTaba/pull/779 respectively

**Comment by elieserdejesus** [comment]
ok @jonjamcam , I will merge soon. Can you change the looper window width to work with the large translated texts? This width can be done directly in **LooperWindow.ui**

**Comment by jonjamcam** [comment]
> Can you change the looper window width to work with the large translated texts? This width can be changed directly in LooperWindow.ui

Sure @elieserdejesus I work on that.

**Comment by elieserdejesus** [comment]
Closing the issue, it's working nice now. Thanks @jonjamcam !
