### ISSUE TITLE
Add " Ninjammer " before musician's name ( Accessibility )

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#79]
I have noticed that when i am in a room box ( at selection time ) , when the mouse pointer is on a
musician's name , that would be good to hear " Ninjammer " before his name.
That would help a lot in fact .

**Comment by Ezeer** [comment]
Online exemple : http://doc.qt.io/qt-5/qtquick-quick-accessibility-example.html
lemme try that now ...

**Comment by Ezeer** [comment]
I have used the Qt methods provided in the visual editor .
My choice was to give a description of the area ( musician names ) that give sense to the names being pronounced .
Fo rme , it's enough to close .

**Comment by elieserdejesus** [comment]
I agree, is good enough.
