### ISSUE TITLE
[Looper] Show loop name when you save a loop

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#794]
At the moment you can only see the loop name when load loops, but when you save them it it would be good to see the name too so you know it's already a "saved loop".

**Comment by elieserdejesus** [comment]
@jonjamcam , this is working here. Can you check again? 

My steps here are simple:
1 - load a loop
2 - lock one layer just to change something and enable the save button
3 - click in save button

The result:
![image](https://cloud.githubusercontent.com/assets/1012741/24583267/cb5376aa-171a-11e7-8eb6-404dd3c7ddf6.png)

**Comment by jonjamcam** [comment]
> 1 - load a loop
2 - lock one layer just to change something and enable the save button
3 - click in save button

Yes, in this case it is working OK because you load a loop that has a name first. What I see is that if you create a loop from scratch and save it, the name is not appearing. To test:

1.- record a couple of layers in an empty looper.
2.-  save it
3.-  no name is shown.

**Comment by elieserdejesus** [comment]
> if you need a separate issue for this last issue, no problem I'll move it there.

It's ok keep all details in thsi issue @jonjamcam , all details are simple and related.
