### ISSUE TITLE
problem when jumping to another room

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#8]
Sometimes we can't enter in another room. Why? Why? Why?

**Comment by elieserdejesus** [comment]
fixed!

**Comment by Ezeer** [comment]
woaw ! great job , it was a monster !!
https://www.youtube.com/watch?v=ytAYsn__ZZI
^^

**Comment by elieserdejesus** [comment]
Jon,  I release a v2.0.7 alpha, so you can test the fixed stuff. I suggest test the closed issues for  the v2.0.7.
See you!
