### ISSUE TITLE
Jamtaba 2.0.5 beta crashes

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#80]
Hi

 Testing the 2.0.5 beta x64 on windows 7 x64 and worked fine the first time, but after close the app and restart it crashes after the "loading room list" dialog.

EDIT:

Plugin works fine, it's just the standalone

**Comment by Ezeer** [comment]
Can you attach the .log please ?
And perhaps set the four first parameters in logging.ini to true , then relaunch the app ?
We should have enough details to debug then .
thx !

**Comment by jonjamcam** [comment]
my log (C:\Users\jon\AppData\Local\Jamtaba 2) is

[log.txt](https://github.com/elieserdejesus/JamTaba/files/24960/log.txt)

**Comment by jonjamcam** [comment]
now the logging.ini had all settings false. changed the five you said to true. It looks like this (but still crashes):

[Rules]

#these are the logging rules. Change a rule to "true" to activate. For example, to se the
#details about VST plugins scanning change the line below to jt.Standalone.PluginFinder=true

jt.Standalone.PluginFinder=true    #VST plugins scanning
jt.Audio=true                      #Audio initialization
jt.Midi=true                      #Midi initiatlization
jt.Core=true                       #Main internal routines
jt.GUI=false                        #Graphic User Interface (GUI)
jt.Ninjam.Core=false                #Ninjam internal routine
jt.Ninjam.Protocol=false            #Log about ninjam client/server communication.
jt.LoginService=false               #Communication between Jamtaba and Jamtaba server. Jamtaba server just return a list of public rooms including the musicians in each room.
jt.JamRecorder=false                #Show the recording multitrack details when this option is enabled in Preferences.
jt.IpToLocation=false               #Jamtaba is using a free webservice to translate IPs to country names.
jt.Ninjam.GUI=false                 #Ninjam Graphic User Interface (GUI) details
jt.Ninjam.VorbisEncoder=false       #Ninjam audio encoding (transmiting audio)
jt.Ninjam.VorbisDecoder=false       #Ninjam audio decoding (receiving audio)
jt.Ninjam.RoomStreamer=false        #Log about public rooms audio previewing.
jt.Standalone.VstPlugin=true     #Log VST plugins initialization and other details in Jamtaba Standalone.
jt.Standalone.VstHost=false         #Log VST host stuff in Jamtaba Standalone. Jamtaba standalone is a VST host too.
jt.VstPlugin=false                  #This log is used only when you are running the VST plugin.

#*.debug=false
#*.info=false

#supressing ssl warnings
qt.network.ssl.warning=false

**Comment by Ezeer** [comment]
Okay , thanks for that report .
I checked my own log ( under win32Xp) , and i have the same kind of content : 
>" default.INFO:  Reading settings from  "C:/Documents and Settings/Salon/Local Settings/Application Data/Jamtaba 2/Jamtaba.json"
qt.core.logging.WARNING:  Ignoring malformed logging rule: 'jt.Standalone.PluginFinder=false#VSTpluginsscanning'setContent qloggingregistry.cpp226

qt.core.logging.WARNING:  Ignoring malformed logging rule: 'jt.Audio=false#Audioinitialization'setContent qloggingregistry.cpp226
etc ....
"
But Jamtaba2 is working fine ...
And all params in logging.ini are set to false .
So there is a problem with the logger , but the logger is probably not the reason of your crashs .
I will look closely to your log now , and report later .
 
At the time when i wrote the " Troubleshooting " part of the user's guide , the logger was working fine.
Elieser , perhaps look to the changes you've made since that could have break something ?

**Comment by Ezeer** [comment]
@jonjamcam  please try to use 44100 for your ASIO4ALL v2 device .
Try to edit the Jamtaba.json , go to audio and change 48000 with 44100
thx

**Comment by jonjamcam** [comment]
changed Jamtaba64.json, from 48000 to 44100 but still crashes. :(

**Comment by Ezeer** [comment]
Also remove all in the "cachedPlugins" .
Exemple from my case : 
before manual edit
> "cachedPlugins": [
            "C:/Program Files/REAPER/Plugins/DSK B3x/DSK B3x.dll",
            "C:/Program Files/REAPER/Plugins/DSK Brass/DSK Brass.dll",
            "C:/Program Files/REAPER/Plugins/Pedals.dll"
        ],
and after .
 "cachedPlugins": [
           
        ],

That was tested and works , PluginFinder will try to rescan your vst
then will see .

**Comment by jonjamcam** [comment]
Did that and it tries to scan all the plugins again, crashig after scaning two or three plugins. Well I noticed it tries to scan my x86 folder, but i'm using the x64 version. Could it be?. Any way to disable scaning at all?

**Comment by Ezeer** [comment]
Good job ! But can i see your log where the pluginFinder crashed ?
That mean you've got one BlackVst in your bank ( one that actuallly we don't support )
thx jon !
;)

**Comment by jonjamcam** [comment]
of course.

[log.txt](https://github.com/elieserdejesus/JamTaba/files/24976/log.txt)

**Comment by Ezeer** [comment]
Thank you for you last log .
I think elieser will have enough to work for a fix  .
He is actually alone to code the vst/plugin part , i need a special Dev kit to be in the party ( one of these days ... )

It seem as you said that while the Pluginversion loads vst successfully , they are not supported by the standalone .

Hopefully elieser will understand what's goin' on .

**Comment by jonjamcam** [comment]
I got it working.

 My take is that it tries to scan the x86 plugins by default (C:\Program Files (x86)\vstplugins) and that is wrong if you're using the x64 version. I deleted that path (wrongly added along with the x64 path (C:\Program Files\vstplugins) at the begining and got it working ok with the x64 vst plugins only. THe problem is if I delete all cache it tries to scan again the x86 folder and crashes inmediately.

**Comment by Ezeer** [comment]
If we had a forum i would pin your comment ....
Perhaps your kind of crash could be a **Q**uestion in the FAQ you will happilly write for the
version ... say 2.0.5 ?

But only if elieser is unable to fix , what i don't believe .
Congratulation , you are now by experience a labeled support team member .
( notice how i use the pictures of the thread you asked me about in the ... bat cave ^^ )
![support member](https://cloud.githubusercontent.com/assets/1283808/10866255/c9875120-8026-11e5-8192-e91297f1de41.jpg)

**Comment by jonjamcam** [comment]
"support team member" sounds really awesome! lol. I just do my best. THX.

I have a lot of experience detecting problems with vst plugins. Let's call it "learning by necessity". 

 Well I tested my theory again and indeed, when you delete the cache and restart Jamtaba, it sets up two paths by default (remember I already deleted all paths before closing it) and try to scan them. In my computer they were:

![jamtaba path](https://cloud.githubusercontent.com/assets/15310433/10872619/fbd8e120-80e4-11e5-8a68-b42285ed302b.jpg)

Unless you develop a wrapper like reaper has, the x86 plugins will crash the x64 app and vice versa.

**Comment by Ezeer** [comment]
" I have a lot of experience detecting problems with vst plugins. Let's call it "learning by necessity". "
lol !

That's weird ...
I don't think Jamtaba writes actually path in the registry .
So where it can find the paths if you deleted all ?
I know elieser coded a default path for vst(s) , perhaps the problem comes from here ....

Really nice intervention , jon "nightcrawler " !
![jonjamcam](https://cloud.githubusercontent.com/assets/1283808/10872721/361dfcee-8108-11e5-8592-7f265a416d49.jpg)

**Comment by jonjamcam** [comment]
jon "nightcrawler " ?

from google translate:

"Definitions of night crawler

noun
an earthworm, in particular one that comes to the surface at night and is collected for use as fishing bait.
"If you were to grasp one in your hand, it would squirm like a healthy night crawler trying to escape the hook."

you didn't mean THAT nightcrawler, did you ezee?

HAHA LOL!

**Comment by Ezeer** [comment]
Lol !
It seems that you have found 
![screen-shot-2011-02-03-at-8-46-46-pm](https://cloud.githubusercontent.com/assets/1283808/10872789/dd8464b8-8109-11e5-9104-d611d6553f25.png)

me here ....
That was written in the book also ...
^^

**Comment by elieserdejesus** [comment]
Hi guys, thanks for the logs. Jon, I think you is right about the x86 plugins problem. Jamtaba x64 is skipping x86 DLLs, but you found a bug.

Another problem are the default VST path. Jamtaba is getting the default VST paths in windows registry. But I'm getting the x86 and x64 paths. At moment this no make sense because Jamtaba x64 can't load x86 plugins. So I will remove the x86 plugins path.

Jon, if possible, can you try identify the bad x86 DLL and post this DLL here?

**Comment by elieserdejesus** [comment]
I removed the 32 bits VST path from Jamtaba 64 bits. This not solve all the plugin scan crash, but avoid unecessary scanning in 32 bits DLL.

I will generate a new beta for the v2.0.5. @jonjamcam, if you have some time please test again in your win 7 64 bits.

**Comment by elieserdejesus** [comment]
Tested in my win 7 64 and 32 bits, it's working now.

**Comment by jonjamcam** [comment]
Tested the new beta. The problem persists meaning that:

If I remove all path to the vstplugins, then close the aplication. When I open Jamtaba Again, the path 

C:\Program Files (x86)\Steinberg\VstPlugIns

appears by default. this path is somewhere in my registry because some other programs think (can they? :D) that this is the default path. Most use the correct one like the jamtaba installer (C:\Program Files\vstplugins)

**Comment by elieserdejesus** [comment]
Thanks Jon!
Jamtaba is asking the windows registry for the VST path. This path is stored in your registry by other softwares, Jamtaba just read the value. I check my registry in a win 7 64 bits (virtual machine) and the registry entry is pointing to a "Program Files x86" folder too.

So, I will change the code  (in v2.0.6) to read the registry entry added by Jamtaba installer.

I'm closing this issue and open another more focused in the VST scan PATH issue.

**Comment by Ezeer** [comment]
good job men !
;)
