### ISSUE TITLE
[VST PLugin - Looper] Some issues when JamtabaVST GUI is closed and opened again

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#802]
1.- Loop name disappears

2.- Looper layer numbering in local channel gets stuck

![image](https://cloud.githubusercontent.com/assets/15310433/24651836/b498e980-1905-11e7-8143-c9ad24903fdd.png)

**Comment by jonjamcam** [comment]
@elieserdejesus I found another issue when closing JamtabaVSt GUI and opening it again. The looper master fader position is reset (but not the looper actual master volume)

**Comment by elieserdejesus** [comment]
fixed @jonjamcam , thanks for report!
