### ISSUE TITLE
Allow chat font size increase

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#809]
@elieserdejesus what do you about adding a json entry to allow the chat font change for LabelUserName and LabelMessage?

I think it's the most simple solution. Torben asked for something like this here https://github.com/elieserdejesus/JamTaba/issues/769#issuecomment-292353267 and I've been thinking about it for some time too. The editing of the Chat.css file is a solution at the moment, but I think for the normal user is a little complicated.

**Comment by elieserdejesus** [comment]
@jonjamcam , maybe two icons (**A+** and **A-**) in chat corner?

**Comment by jonjamcam** [comment]
> maybe two icons (A+ and A-) in chat corner?

Yeah! much better

**Comment by Hitrate** [comment]
Hey guys, love your work. Lets talk about what I can do to help. 

Comments regarding the chat:

Would it be possible to have one or two more steps on the "increase" front? I know I know, I'm blind...but still,..would be nice :P 
Oh one more suggestion: Since you can have the other players lay horizontally, just like in old ReaNinjam, which I love, - it would also be cool to have your OWN channel be horizontal.... That way it makes more sense, than having ur own channel vertical and the others horizontal.. :)

![screen shot 2017-04-23 at 07 30 29 pm](https://cloud.githubusercontent.com/assets/26333462/25315798/638b057c-285b-11e7-84b3-87ca6ad287d3.png)


I have left a comment in this closed thread btw. https://github.com/elieserdejesus/JamTaba/issues/806

**Comment by jonjamcam** [comment]
>Would it be possible to have one or two more steps on the "increase" front? 

@Hitrate You can set the biggest size you want for the VST/AU, but you'll have to do it manually editing the Jamtaba.json . This is an example I did with a big TV I have in the house:

![image](https://cloud.githubusercontent.com/assets/15310433/25464536/4b1e6e00-2ad3-11e7-8b75-03e9d2118eb7.png)

The resolution was set to 2000 x 1000 px ! Probably enough for your needs :smile:

![image](https://cloud.githubusercontent.com/assets/15310433/25464952/bc2cebce-2ad5-11e7-9061-6450c947ecd3.png)

**Comment by Hitrate** [comment]
![screen shot 2017-04-27 at 04 38 19 am](https://cloud.githubusercontent.com/assets/26333462/25465584/685adcb2-2b03-11e7-95be-9760adda17e1.png)
![screen shot 2017-04-27 at 04 38 09 am](https://cloud.githubusercontent.com/assets/26333462/25465583/6852801c-2b03-11e7-9e00-2459cce03630.png)

Hey Jon, as you see, it's not really working for me in lpx/mainstage...I can drag the standalone app..but not get it to resize up to the higher value that i set in the file as you see...

**Comment by jonjamcam** [comment]
@Hitrate Close the software, edit json file, save and relaunch your host.

**Comment by Hitrate** [comment]
![screen shot 2017-04-27 at 04 41 04 am](https://cloud.githubusercontent.com/assets/26333462/25465645/c1d155d2-2b03-11e7-85bf-85c0ded15613.png)

here's how it looks in reaper lol

**Comment by jonjamcam** [comment]
> here's how it looks in reaper lol

ahh I see maybe it's working in windows only...donno

**Comment by Hitrate** [comment]
ya I did that..yup maybe something wrong where it doesn't size it up it only sizes up the "container"

**Comment by elieserdejesus** [comment]
> maybe something wrong where it doesn't size it up it only sizes up the "container"

Exactly @Hitrate , it's a bug, only the container is resized. I will check this soon.

**Comment by jonjamcam** [comment]
@elieserdejesus I tested the new chat layout (https://github.com/elieserdejesus/JamTaba/pull/857) to see how bigger letters fit and I found the bigger font it supports is `font-size: 14px;` without cropping the widget:

![image](https://cloud.githubusercontent.com/assets/15310433/25566629/39c55f1e-2db3-11e7-8ed0-671bcb18ff3f.png)

which is big enough I think.

**Comment by elieserdejesus** [comment]
implemented in 68a1ce3:

![chat font size](https://user-images.githubusercontent.com/1012741/35569173-8ba017b6-05b2-11e8-8f63-b72429b1fced.gif)

**Comment by jonjamcam** [comment]
Great!
