### ISSUE TITLE
Logging rules are not applyed in VST plugin

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#81]
the logging.ini file is not embbeded in the VST plugin DLL, so the strategy used in standalone don't work in VST plugin.

**Comment by Ezeer** [comment]
Sorry that i can't help here .
Can i help here ?
Perhaps in the standalone part ?

**Comment by elieserdejesus** [comment]
I think this problem is in VST plugin only Ezee, I will check this soon.

**Comment by Ezeer** [comment]
Hey , while you are here , please revert your logger comments in the code ..
pljones has probably found the root of the issue here #62 .
thx
