### ISSUE TITLE
[Looper] Main fader volume handle border cropped

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#813]
This appears to be a Volcano theme issue, but I really don't know for sure if it happens in all themes. It is hard for me to see in my monitor when I check other themes

![image](https://cloud.githubusercontent.com/assets/15310433/24832143/690e93de-1c7f-11e7-8398-66f0b5dd7d7c.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I can't reproduce the issue here. I deleted the themes folder to ensure I'm using the last CSS files the result is ok. I changed the themes and back to volcano, no problems:

![image](https://cloud.githubusercontent.com/assets/1012741/24867731/8d0e7496-1de4-11e7-8607-f8e5eb6489c8.png)

**Comment by jonjamcam** [comment]
> no problems

good to know...something I have wrong in my system. closing then
