### ISSUE TITLE
Jamtaba 2.0.5 beta crashes at startup in windows XP

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#82]
![jamtaba 2 0 5 beta crash win xp](https://cloud.githubusercontent.com/assets/15310433/10873419/d5c1820c-80ea-11e5-9d6c-e8abe48ef7f4.JPG)

Only the standalone have problems. The plugin works perfect under reaper

**Comment by Ezeer** [comment]
Hey , it don't crashed with me .
I had a previous version that i have deinstalled before this one , using the provided uninstall .
Did you do that too ?

Also , give us the log please .
^^

**Comment by jonjamcam** [comment]
Ezee, where's the logging.ini under xp?

**Comment by Ezeer** [comment]
the log you provided is the pluginVst : (line 86)
>default.INFO:  "Starting Jamtaba 2.0.4 VST Plugin (i386) running on Windows XP (i386) running in Reaper"

It is important thart elieser fix the logger now because each packet sent in audio buffer is written in
the log actually . That would make HUGE FILES if the users don't know the actual problem and use
it say , an hour ...

Can you send me the Standalone's log now , please ?
( mwah ah ah )

**"I noticed some problems with the special "don't download this version unless you are ezee"."**
Don't be afraid , just a brazilian voodoo trick !
eh eh

**Comment by jonjamcam** [comment]
"an you send me the Standalone's log now , please ?"

I have only one log.txt inside Jamtaba2 directory....

https://www.youtube.com/watch?v=ARJ8cAGm6JE

**Comment by Ezeer** [comment]
ah ah ah ! you are a king , stephen ?
lol

seriously , if you used the pluginVst after the standalone , it was overwritten .
Please launch the standalone again ( or tomorrow , you're not paid after all ;) )
^^
i'm gonna reload the " I'm sorry Dave, I'm afraid I can't do that" " for my pleasure now ,
thank you !

**Comment by jonjamcam** [comment]
Ok I solved. Once you uninstall it dowsn't remove the finles in the directory. So I deleted the jamtaba 2 directory, installed again and worked like a charm!

**Comment by Ezeer** [comment]
yeah ... of course .. you rock too !
Man , i just had that idea : 
You don't have to write the user's manual in the wiki and in a pdf .
Perhaps you have more freedom in a pdf format .
What i propose to the team now is to have the user's guide in a pdf format only .
I ( or i ... ) can redirect the link of the wiki to the page 2 to the pdf url that you will store using the #72 thread .
Then elieser would just have to code a new url in the jamtaba's help menu .

what do you think about that guys ?

**Comment by jonjamcam** [comment]
For me it's easier in PDF, but I think the html is more compatible....

**Comment by elieserdejesus** [comment]
I think PDF is difficult to keep updated. The wiki is very easy to change for any contributor, PDF not.
So I vote for HTML Wiki :)

**Comment by Ezeer** [comment]
ok , i'm at your side anyway .
you got my vote for html so .

My last idea : give the pdf in the release , in case the users lost their internet connecton , they'll
have something to do .
eh eh

**Comment by jonjamcam** [comment]
I'll do both. I'll design in PDF and post too in wiki with hopefully the same quality.
