### ISSUE TITLE
[Looper] 3db (aprox) volume difference between channel and looper monitoring when recording

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#820]
@elieserdejesus This is the opinion of my ears: I hear the local channel volume about 3db lower in volume when comparing it to the looper volume (recording and monitoring). 

Or is it the looper that has 3db more? isn't 3db the attenuation value of the pan law?

EDIT: After you use the pan of any of the layers, the problem goes away for that specific layer, but not for the other layers. If you use reset content or content&controls the problem disappears too (but not when using reset controls only). It looks to me as if the pan law for the layers is not initialized automatically and you need to move the pan fader or press reset to activate it.

To test:

1.- Launch Jamtaba and open the looper
2.- play something that loops itself outside Jamtaba so you can hear the difference.
3.- start recording. You'll hear the boost just when you press record.

EDIT2: BTW a dB indicator for the looper master fader could be handy, specially when you want to have the same level than the input channel:

![image](https://cloud.githubusercontent.com/assets/15310433/24985386/1a1e8858-1fca-11e7-84a2-ac2b55928111.png)

At the moment if the local channel is not at 0 db it's hard to "copy" the value so you have the exact same volume when recording in the looper.

**Comment by elieserdejesus** [comment]
You are right @jonjamcam , the pan was not correctly initialized in looper layers. It's fixed now.
