### ISSUE TITLE
[Looper] Some issues about the locked layers feature

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#823]
I.  If you record using **play locked checked**, after recording ends in last layer (when playing is switched automatically) you don't hear only locked layer in the first BPI cycle, **you hear all layers** first and then in the next BPI cycle the locked feature activates.

To test:

1.- load a loop with 3 or more layers in sequence mode.
2.- lock 2 layers.
3.- check "play locked" checkbox
4.- focus on any unlocked layer.
5.- record.
6.- after recording ends and play starts and you can hear all layers the first round.
***
II. Another problem I found when recording in sequence mode is that in the case when **play locked** and  **hear all/locked** are both checked the input audio is muted **while recording** and you can't hear what's being recorded (but it's NOT muted when in recording waiting state). EDIT: Just tested it and **this is happening also in selected layer mode** and if **play locked** is used in **all layers mode** same problem. So in short:

silent monitoring of input audio when:

1.- sequence mode: **play locked** and  **hear all/locked** are both checked.
2.- selected layer mode: **play locked** and  **hear all/locked** are both checked.
3.- all layers mode: **play locked** checked.
***
EDIT: there's a third issue different from the above happening in sequence mode:

III. Assuming a >2 loop arrangement, **if Layer 1 is locked**, recording of unlocked layers is not stopping after the last layer is recorded. It continues from the top from the first unlocked layer that has not been recorded and it stops just before reaching the layer you started recording from.

To test:

1.- load loop with 3 or more layers.
2.- lock layer 1
3.- focus on any of the unlocked layers (except layer 2) and start recording.
4.- recording will not stop after the last layer is recorded (unless you started on layer 2 in which case behavior is normal).

EDIT: This last issue happens in **sequence mode** and **All layers mode**

**Comment by elieserdejesus** [comment]
@jonjamcam , I worked in these issues in the PR https://github.com/elieserdejesus/JamTaba/pull/834

The 2 first problems are fixed (I hope :)).

I can't reproduce the 3rd problem, I added two auto tests to check the 3rd problem and is working. Maybe the 2 first fixes solved this 3rd problem too.

Can you test these problems again in the PR branch, please?

**Comment by jonjamcam** [comment]
Issue I solved. Now you can hear locked layers all the time after recording has finished.

Issue II and Issue III are still there. I posted the details in the PR https://github.com/elieserdejesus/JamTaba/pull/834 :
