### ISSUE TITLE
[Looper] Frippertronics mode or checkbox for selected mode (2.0.21)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#826]
I'm thinkng about this feature that could emulate the old frippertronics looping style. I think it should not be complicated to implement because it's very similar to selected layer mode using overdub. The differences are two in my opinion:

1.- old takes within a layer overdub become progressively lower in volume until they disappear over time.
2.- the old machines had lots of analog hiss that gives the looping experience a vintage touch and mood.

I posted this video before that I think it's the best explanation I found on youtube about how this looping technology works (or worked in the past, rather)

https://www.youtube.com/watch?v=FCXNxVWx3jY

What do you think about this idea @elieserdejesus ?

**Comment by elieserdejesus** [comment]
nice @jonjamcam , I see this too: [https://www.youtube.com/watch?v=LhkXNCmctHw](https://www.youtube.com/watch?v=LhkXNCmctHw)

I think this idea can be implemented as a variation of **Sequence** mode. The difference is the reduction of all layers gain in each cycle, right?

**Comment by jonjamcam** [comment]
> The difference is the reduction of all layers gain in each cycle, right?

Yeah I think that's the magic. It slowly fades so overs a couple of minutes you can have a completely different "composition".

I saw the video and it's true that a delay can do the trick too.

**Comment by jonjamcam** [comment]
@elieserdejesus Here's an example of Fripp himself using a 20 sec looping duration.

https://www.youtube.com/watch?v=uYE7XCVAiBQ&feature=youtu.be&t=95

20 seconds BPI can be translated in the ninjam world to : 

1.- 60 BPM 20 BPI
2.- 120 BPM 40 BPI

You can do the math to get other BPI/BPM, but I think that's the connection between both worlds. I think the big problem with delay pedals and effects is that they small max times so you never get those long ambient textures.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
