### ISSUE TITLE
[Looper] Space Bar behavior

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#828]
At the moment the space bar works as a play/stop shortcut after you pressed PLAY. But if you press RECORD it works as a REC/PLAY toolge button. I think it should be fixed to be the shortcut of only one of the two behaviors (RECORD would be my personal preference).

**Comment by elieserdejesus** [comment]
@jonjamcam , this behavior is expected. If you click in the rec button this button is focused, and space bar always will activate the focused button. Actually this works for any focusable control. Focused controls can be activated pressing space bar. This space bar behavior is not programmed in JamTaba, it's just common behavior for buttons.

**Comment by jonjamcam** [comment]
> this behavior is expected.

OK. I see. closing...
