### ISSUE TITLE
Music jingle at startup

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#83]
Andre Louis offered yesterday to me ( and by the way to the project ) 359 Mo of his shorts music ,
with a lot of different styles .
As you know , he is blind , but the most important , a really inspired musician .
I think it would be great to have one part of his heart in the project ( he considers his shorts as babies )
, and as he wanted to help us , this could be a way of contribution .

We were talking about a splash screen ( #73 ) , let's add to it a music ?

**Comment by Ezeer** [comment]
I just found on andre louis site , something very interesting : Ninjam sessions records .
A gold mine -> http://onj.andrelouis.com/ninjam/

**Comment by elieserdejesus** [comment]
I'm listen, very very good: [http://onj.andrelouis.com/ninjam/G%20minor%20jam%20-%20Onj,%20Brunello,%20Funkify.ogg](http://onj.andrelouis.com/ninjam/G%20minor%20jam%20-%20Onj,%20Brunello,%20Funkify.ogg)

I think this idea is good Ezee, but we need a option to disable the sound, so users have a choice.
I think a good idea is play very short pieces of music in a random way. Every time Jamtaba is started a new piece is played. 
The cons: this audio files need be embbeded in exe.

**Comment by Ezeer** [comment]
mmm.... let's be hardcore coders so .
Say we use only one file that contains all shorts we want , we use core audio to play short parts of this file reading directly to the buffer at predefined position ?

**Comment by elieserdejesus** [comment]
This is possible, but I prefere a simple approach. We can put any files in Jamtaba.qrc (the resource file). I'm using this for images, icons, the metronome audio file. For example we can create a folder "splash_songs" inside the resource file and put some mp3 inside the folder. We can open this folder in the code and list all the files inside folder. This is flexible because the file names are not hard coded, just the folder name is. We can add or remove new splash_songs without touch the code. Just add/remove a new song, rebuild and the resources are embedded in executable.

I wrote a class FileStreamerNode (or something similar) to test Jamtaba first versions. So we can use this class to plug a audio file stream in the current audio engine.

**Comment by Ezeer** [comment]
That sounds very good .
I still think to the chord recognition lib , and play with that " simple " task would have been a way
to reintroduce myself in audio buffering .
But you are right , keep the things simple as longer than we can .

So ... how could we proceed to submit the audio clips we like to the team ?

**Comment by Ezeer** [comment]
And yeah , the song you selected is great !
;)

**Comment by Ezeer** [comment]
I had a talk with Andre Louis , shared that thread with him .
This is for you guys : 
*"Wow... It's great the team like my music. I feel honored to work with you all. "* A.Louis

**Comment by Ezeer** [comment]
I vote for this song : http://onj.andrelouis.com/ninjam/Onj%20alone%20on%20Ninjam.ogg

**Comment by FreakyFwoof** [comment]
Hello hello, Andre here. this is my first ever post.
I have another link for you for you to enjoy. Thank you.
http://onj.me/freakyfwooftracks

And if you want the short tracks for the splash-screen probably better to look at the shorts project, as they are already defined with start, middle, end. And some variations. #justAThought
http://onj.me/freakyfwoofshortszip

Thanks very much for your time.

**Comment by elieserdejesus** [comment]
Andre, thanks for your good music, we are honored by your collaboration!

**Comment by Ezeer** [comment]
Big up Andre !
I am so happy to collaborate with you !
blessings !

**Comment by jonjamcam** [comment]
Fantastic Music Andre!

**Comment by DoublebassOO** [comment]
and please add some of Elieser too !!     :)

**Comment by Ezeer** [comment]
in the " about box " perhaps ?
lol
