### ISSUE TITLE
Use installer VST path as default scan PATH for VST plugins

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#84]
At moment Jamtaba is using the default VST path stored in registry by other software. 
Is better use the PATH stored by jamtaba installer (the path choosed by Jamtaba user).

**Comment by jonjamcam** [comment]
I agree.

**Comment by Ezeer** [comment]
How can i help ?

**Comment by elieserdejesus** [comment]
Ezee, at moment Inno Setup is automatically storing the VST path choosed by the user in installing time. This VST path is stored in windows registry. I search this entry in registry and founded, but the key/folder is a black magic hash code. So we can't access a simple key in registry and get the value (the VST path choosed by the user).

So, a solution is manually store the user VST path and read this entry when the VST path list is empty in Jamtaba.

**Comment by Ezeer** [comment]
**PATH stored by jamtaba installer (the path choosed by Jamtaba user**
But where the installer writes that PATH ?
...
Why we need the default path , the user can choose the path in settings ?
But we also can ask the user at startup , at the first launch , with a dialogbox asking for the vst path ?
Then store it in Json ?

**Comment by elieserdejesus** [comment]
**But where the installer writes that PATH ?**
Installer write the PATH in a werid key in registry. I suppose Inno setup use some kind of hash, and probabily this hash change in every machine Jamtaba is installed. So we can trust in this to get something in registry.

**Why we need the default path?**
It's a convenience to users, all DAWs use some similar. In Reaper, for example, we see the "Auto Detect" button. Reaper load the default VST path by default.
![image](https://cloud.githubusercontent.com/assets/1012741/11015244/9be49b80-853d-11e5-8847-f7f60d76e75a.png)

The default paths are define in [VST 2.4 documentation](http://www.dith.it/listing/vst_stuff/vstsdk2.4/doc/html/index.html) 
**On the Windows platform, a VST Plug-In is a multi-threaded DLL (Dynamic Link Library). A standard (default) folder for the VST Plug-Ins is defined in the registry under "HKEY_LOCAL_MACHINE\SOFTWARE\VST\VSTPluginsPath".**

**Comment by Ezeer** [comment]
So you want to read the key that was wrtten by jamtaba in the registry .
But this path was given by the user ?
If yes , why not remove the question from the installer and put it at the first runtime ?
It's the same process .

**Comment by elieserdejesus** [comment]
Ezee,If we ask users about VST path at the first runtime we are probably asking 2 times for the same info:
1 - We will first ask user "where you want install Jamtaba VST plugin" in installer.
2 - Jamtaba is opened at first time and we ask again: "Where are your VST plugins?"

Off couse the answer for the 2 questions can be different in some cases, but I think 99.99% of users will install Jamtaba VST plugin in your preferred plugins folder. So, I we have the right info (the preferred plugin folder) in installing time, no need to ask again in runtime.

**Comment by Ezeer** [comment]
I was saying to REMOVE THE INSTALL question to ask at launch time .
Not to keep the two .
It's a better design to ask at install time , but if it's too complicated to deal with the registry , 
let the lazy user moove his ass !
ah ah ah

**Comment by elieserdejesus** [comment]
I think the "add another entry in registry" solution is not complicated. 
1 - In installer we can add stuff in registry (the selected VST install Path).
2 - Jamtaba read the well know entry in registry to get the Vst Path, so we don't rely in "Default VST path" proposed by Steinberg.

I will work in this soon, my brain is a bit over clocked at moment :)

**Comment by Ezeer** [comment]
ouf ! that is too much boring for me .
You give me time to find another way to crash Jamtaba with my joystick .
eh eh eh
