### ISSUE TITLE
[Loopper] overdub recording woks for only one or two cicles some times

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#844]
The expected result I understand should be an infinite recording loop until one presses play again. THis does not happen all times. I'm trying to guess the pattern.

EDIT: This could be a false alarm. I'm testing win10 in a computer with a keyboard that's not in perfect conditions

**Comment by jonjamcam** [comment]
It was a indeed a flase alarm:smile: ..closing...

**Comment by elieserdejesus** [comment]
> a keyboard that's not in perfect conditions

hehe 😄
