### ISSUE TITLE
[Standalone] midi routing arrow pointing to audio meter instead of midi meter

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#845]
![image](https://cloud.githubusercontent.com/assets/15310433/25458597/dfcdbe0c-2ab0-11e7-8dff-4d2ea6e15978.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the code to improve these midi routing feedback. 

Sometimes (no input selected for example) the midi meter is not visible in first subchannel and is not possible use this element. So I changed the code to point to midi meter when available. The two images are showing these 2 scenarios (first subchannel midi meter available and not available):

![image](https://cloud.githubusercontent.com/assets/1012741/25461748/1ebe166a-2ac1-11e7-9468-eae5a4ece274.png)
