### ISSUE TITLE
[AU plugin] Manual resize via json file editing not working

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#849]
In windows is possible to resize the plugin window size to almost any size, but the AU plugin does not respond as expected to this method.

I don't know @elieserdejesus if the AU format allows this kind of flexibility, which could be of use. Here are some tests Torben did with not good results:

https://github.com/elieserdejesus/JamTaba/issues/809#issuecomment-297595463

https://github.com/elieserdejesus/JamTaba/issues/809#issuecomment-297595727

**Comment by elieserdejesus** [comment]
> I don't know @elieserdejesus if the AU format allows this kind of flexibility

Yes @jonjamcam , this is possible. I need check this AU code again to fix this problem.

**Comment by elieserdejesus** [comment]
@jonjamcam and @Hitrate , now is possible resize AU/VST plugin width and height. The resize behavior is better now, is possible work in a more retangular window (increasing width only) if you like:
![screen shot 2017-04-29 at 5 18 10 pm](https://cloud.githubusercontent.com/assets/1012741/25558585/247989d6-2d00-11e7-8a36-7702105045a2.png)

**Comment by jonjamcam** [comment]
Cool. @elieserdejesus . One question: how are the maximum/minimum limits set? I have a small screen (laptop) so I have to edit the json file to get any other size than default.

**Comment by elieserdejesus** [comment]
@jonjamcam , the maximum is your desktop window size minus the OS icons bars (Docker in Mac, task bar in Windows, etc). 

The minimum window size is hardcoded in https://github.com/elieserdejesus/JamTaba/blob/d65f40ccf556be94c800534f7b381e12865ff106/src/Plugins/MainWindowPlugin.cpp#L11
