### ISSUE TITLE
Mini Mode doesn't have XMIT button

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#85]
I LOVE THE MINI MODE!!!

but..there's only one control that I need that's not there when controls are collapsed.. TRANSMIT. I use it a lot, turn it on and off very often. At least we need to know if it's red or green don't you think?

**Comment by elieserdejesus** [comment]
Totally agree jon, I completely forgot this very important detail.

**Comment by jonjamcam** [comment]
And I found a GUI problem: while in midi mode and inside a room if you decide to expand the controls, the the metronome is SQEEEEZED....lol

**Comment by Ezeer** [comment]
Hello , i am a new user of Jamtaba .
I have read your user's guide , but i can't find something to explain to me what is the Mini Mode .
Can you help me please ?
Thank you a lot !
^^

**Comment by jonjamcam** [comment]
Nobody knows yet.....;P

**Comment by elieserdejesus** [comment]
Jon, can you add more details?
1 - Enter in a room
2 - Change to mini mode
3 - ?? Expand controls? Back to Full View mode?

**Comment by jonjamcam** [comment]
Yes. I'm using two channels in Full view Mode with the control expanded. So I go to Mini Mode and they are collapsed. Then let's say I expand them while i'm in mini mode, they look too wide for so little space and pushes the bpm/bpm box to the right squeezing  the Metronome to a little ball that barely moves.

If you use only onne Channel this doesn't happen.

**Comment by Ezeer** [comment]
You could also take a screenshot , and mail it if its still a secret !
![49168054-james-bond-collectibles-cover 600x400](https://cloud.githubusercontent.com/assets/1283808/10896194/9e66c37a-81b8-11e5-8f5d-83a53f7f5434.jpg)

lol

**Comment by jonjamcam** [comment]
ha! no secret, jut appeared instead of the themes menu remember? and I just click, click click to whatever moves hehe

**Comment by Ezeer** [comment]
ah ah ah , thank you james !
A brandy ? ( secret : Brandy (from brandywine, derived from Dutch brandewijn, "gebrande wijn" "burned wine"[1]) is a **spirit** produced by distilling wine. )
To the mini mode ,
:wine_glass:

**Comment by jonjamcam** [comment]
cheers! It will be very useful indeed for laptop jaming

**Comment by elieserdejesus** [comment]
Ezee, "mini mode" is just a cool name for this issue: [https://github.com/elieserdejesus/JamTaba/issues/76](https://github.com/elieserdejesus/JamTaba/issues/76)

**Comment by elieserdejesus** [comment]
Jon, I understand the problem now, thanks for the aditional infos.

**Comment by Ezeer** [comment]
Ah... we were in the plugin universe .... but you made me dream of a mini mode for the Standalone .
Talking of that , i think floating windows would be a nice feature for people like me that use multi-screens . A mini mode of the metronome could be a window with LARGE NUMBERS COUNTER FOR
BEATS AND BPI , THE DRUMMERS WILL LIKE !

**Comment by jonjamcam** [comment]
lol that big even a blind could see!

**Comment by Ezeer** [comment]
lol !
I hope so ...
;)

**Comment by elieserdejesus** [comment]
Ezee, I think is a good idea create a new issue (enhancement) for this idea. The BPI/BPM values play a very important rule in 99% of ninjam jams, so the possibility to have a floating panel showing the ninjam interval progress is a good idea. Other drumers ask me about this possibity before. Drummers have special needs because the drum kit is not close to the computer screen, etc. And drumers are the heart of jam, they need a very good click solution, customizable, enjoyable, etc.  So let's think in some cool for our drummers friends. Please create a new issue!

**Comment by elieserdejesus** [comment]
Now the xmit appears in midi mode too. Using a scroll in input controls to avoid use a lot of horizontal space. Now we have enough space for the metronome, no more squeezeee. :)
![image](https://cloud.githubusercontent.com/assets/1012741/10946389/2c40a854-8309-11e5-8c43-f650c08a215c.png)

**Comment by Ezeer** [comment]
Good job elieser !

**Comment by jonjamcam** [comment]
That's Fantastic!
