### ISSUE TITLE
[Vst plugin] Reset track controls mutes input for local channels

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#853]

**Comment by elieserdejesus** [comment]
@jonjamcam , this is the behavior in Standalone too.

In Standalone the reseted tracks are setted to "no input". In VST/AU plugin this will be a "muted/no input" channel.

The easy solution is just reset the track controls and not touch in track input selection. This will solve the VST/AU plugin issue and I think is good for Standalone too. What is your opinion?

**Comment by jonjamcam** [comment]
> The easy solution is just reset the track controls and not touch in track input selection. This will solve the VST/AU plugin issue and I think is good for Standalone too. What is your opinion?

Yes I agree it's a good solution too.

> just remove the line https://github.com/elieserdejesus/JamTaba/blob/ca24a9fc530e8329daa1c37f54099df3400552b6/src/Common/audio/core/LocalInputNode.cpp#L389 to solve the issue. Can you fix?

 I'll fix it @elieserdejesus

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , the fix commit is merged.
