### ISSUE TITLE
mono remote channel do not show metering when pan is 100% right

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#858]
![image](https://cloud.githubusercontent.com/assets/15310433/25566533/da03a47a-2db0-11e7-915e-cde123fe5a78.png)

**Comment by Hitrate** [comment]
I dunno what this is referring to, but the image is good for me to issue another issue: Whenever you have someone with two stereo channels, as opposed to two mono channels(?) you have very limited space to adjust those left right faders..so it becomes guess work if you're looking for a specific panning setting...Like finding 25% towards the left, the fader throw is half as long as single channels (on the wide setting) so theres not much room to work with...

**Comment by Hitrate** [comment]
Easy fix: drop the level meters down/ and/or raise the L/R fader above, so you can utilize the full width of the channel's container for the L/R fader, even with a stereo track..

**Comment by elieserdejesus** [comment]
@Hitrate , in the last version (beta not available yet) is possible see the current pan percentage when you mode the slider, so the problem you mentioned (the guess work) is not too severe:
![image](https://cloud.githubusercontent.com/assets/1012741/25568040/c9de00a2-2dd0-11e7-804c-c0f44911246b.png)

I don't like this small pan slider too. I configured the track layout in this way to avoid very small/tall meters in local tracks when connected in a server. The code used in ninjamer tracks is the same used in local tracks. Local tracks need more vertical space to show addtional buttons (Looper, Stereo Inversion) and the plugins rack:
![image](https://cloud.githubusercontent.com/assets/1012741/25568076/b41941fe-2dd1-11e7-9c4e-b73d1004994c.png)

Maybe in next version we can improve this track layout.

**Comment by Hitrate** [comment]
Ya, maybe two rows of buttons next to each other stacked vertically, rather than now only one tall row...M, S, OFF, loop, Stereo/mono buttons...or stack them all to the left of the levels indicator, that way the levels indicator can be moved down, and the pan fader be widened, and you would even get a longer levels indicator that way :)

**Comment by elieserdejesus** [comment]
> the levels indicator can be moved down, and the pan fader be widened, and you would even get a longer levels indicator that way :)

This is my preferred solution too Torben. If possible please create a new issue to handle this, just to keep the ideas separated and organized. Since this issue is fixed the ideas discussed here will probably get lost in time space :)
