### ISSUE TITLE
Network Bandwidth meter

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#859]
Jamtaba 1 has a bandwidth meter per channel for real time rooms. I think this could be useful in Jamtaba 2 for ninjam rooms too:

![image](https://cloud.githubusercontent.com/assets/15310433/25567588/825880a8-2dc7-11e7-9b73-b5a1a1a7709c.png)

And if possible a TOTAL BANDWIDTH meter near the MEM monitor. Ninjam uses very little bandwidth compared to what a typical house connection has, but as video is being progressively incorporated (obs and future ninjam video) I expect the amount of usage to start increasing inbound and outbound quite considerably.

This is a good way to know which channel to stop receiving data from, for example, specially for video channels

**Comment by Hitrate** [comment]
I have a random comment about bandwidth/quality that I could throw in here perhaps: I set my quality to max, but 1. It would be nice to have an even higher max setting perhaps...like 192..
2. it would be nice if the standard quality for all newbies was also higher (max setting) due to the fact that people are getting better and better internet connections and speed.
3. It would be even nicer, to then have an option to change the quality settings down (or up) within Jamtaba, instead of having to edit file manually...

**Comment by jonjamcam** [comment]
> 1. It would be nice to have an even higher max setting perhaps...like 192..

Hey @Hitrate This is a tough topic because at the moment servers require a lot of outbound bandwidth to operate and admins of public servers (Tom, Demned, mutant) are not able to control the quality variable. We had a very good discussion here: https://github.com/elieserdejesus/JamTaba/issues/456 about choosing the "best" values so not to stress public servers too much.

It will be a bad thing if public servers begin to shut down because of excessive bandwidth usage.

**Comment by elieserdejesus** [comment]
> It would be even nicer, to then have an option to change the quality settings down (or up) within Jamtaba, instead of having to edit file manually...

@Hitrate , in Standalone is possible set the quality in Audio preferences, but this tab (audio preferences) is not available in VST/AU plugin. This is bad thing and no doubt we need improve this "preferences" dialog.
![image](https://cloud.githubusercontent.com/assets/1012741/25567949/d0b47142-2dce-11e7-83d6-64b1414e5cac.png)

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907

**Comment by elieserdejesus** [comment]
Network usage meters implemented in c284688

![image](https://user-images.githubusercontent.com/1012741/35406682-c20b6b04-01f0-11e8-9c69-2ef275abde5e.png)

**Comment by jonjamcam** [comment]
Fantastic! Very much needed feature. Thx elieser
