### ISSUE TITLE
Uninstall don't remove Jamtaba2 folder

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#86]
All is in the title eh eh !
Perhaps just an option in innoSetup ?

**Comment by jonjamcam** [comment]
it doesn't remove the files inside the folder too

**Comment by Ezeer** [comment]
Okay , thanks .
So i think we could make a script that asks the user if he wants to keep his files or not .
With "no" selected by default ?

**Comment by jonjamcam** [comment]
"Everything is code..."

https://www.youtube.com/watch?v=Sj7TG-Wy0ZI

**Comment by Ezeer** [comment]
woaw ... thank you jon for that pearl !
" Life is a problem to be solved " 
" doors that open to unexpected ... "
Life was compiled ? Or we are in compilation time right now ?
A process with many child processes that compiles their own updates ?
I see that tree .

*With " no " selected by default* is hilarious in that dimension you just opened dear jon !
back to our subatomic tasks , i've found that in inno faq : 
After uninstalling, the directories created during installation still exist.

>There are several reasons why a directory may not be removed:

>It already existed prior to installation. By default, the uninstaller plays it safe and doesn't remove directories that the installer didn't create.
It contains files or subdirectories. Use [UninstallDelete] if you need the uninstaller to delete additional files/directories.
A running process has the directory as its current directory.
Note: In Inno Setup versions prior to 2.0.1, directories must be specified in either the [Dirs] or [UninstallDelete] sections for them to be deleted by the uninstaller. In newer Inno Setup versions, directories created by [Files] section entries will be deleted automatically by the uninstaller if they didn't exist prior to installation.

@elieserdejesus : Do you read that ?

**Comment by elieserdejesus** [comment]
Ezee, this part is interesting: **In newer Inno Setup versions, directories created by [Files] section entries will be deleted automatically by the uninstaller if they didn't exist prior to installation.**

I'm using the [Files] section, but auto uninstall is not working. I will check this soon, I hope this is a quick fix, just check some magic check box in Inno Setup.

**Comment by Ezeer** [comment]
You are our hero , you know that ?
That is what i assign you now , without other ceremonials .
^^

**Comment by Ezeer** [comment]
wait ... life is a bug ?
mwah ah ah

**Comment by jonjamcam** [comment]
is she ok?

when my daughter gets ill is the sky falling down.

**Comment by Ezeer** [comment]
http://www.cdkl5.com/about-cdkl5/default.aspx
And for me  , the sky start at the ground level ( or 1 micron upon it if you think lika scientist ^^ ), everything being considered .
That hurts less than falling from a cliff ...
Life is a bug or has a bug ?
lol
^^

**Comment by jonjamcam** [comment]
Man, I feel your Pain. Children are so Pure and this should not happen to them. I hope She recovers and I send you all my Love, really. Children are Sacred.

 I have a 9 years old daughter. I know the feeling when they get ill....

**Comment by Ezeer** [comment]
Thank you bro' , your love is welcome !
She's 10 and she enjoy a lot when i play some music for her , guitar mainly .
When she shouts , i know my playing and singing are good !
She has a very good hearing , and feeling too .
She is a dreamer ...like me .
^^
but back to the uninstall , how are the things elieser ?

**Comment by elieserdejesus** [comment]
Ezee, I wish the best for your daughter! 
So, we 3 are father of girls, nice!  My little girl is a 8 years old.
About the uninstaller, I don't work in this yet, this was a complicated week.

**Comment by elieserdejesus** [comment]
Testing here in win 8.1 and is working, maybe is a Win XP issue. Testing in win 7...

**Comment by elieserdejesus** [comment]
Guys, I test in win 7 64 bits, win 7 32 bits and Win XP. The Jamtaba folder is removed as expected in all tests. 
I'm using the Windows Control Panel to uninstall. How you are uninstalling?

**Comment by jonjamcam** [comment]
I tried with the conrol panel, but in my win 7x64 the folder isn't removed.

**Comment by Ezeer** [comment]
I use the uninstall from the shorcut in Start->All programs->Jamtaba 2->uninstall

**Comment by Ezeer** [comment]
I tested what jon said , but that don't work here on windows Xp

**Comment by Ezeer** [comment]
I use CCleaner to check the remaining entries after uninstall :
>Référence MUI manquante	C:\Program Files\JamTaba 2\unins000.exe	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\Documents and Settings\Salon\Mes documents\Downloads\Jamtaba.2.32.bits.installer (1).exe	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\DOCUME~1\Salon\LOCALS~1\Temp\is-UESSN.tmp\Jamtaba.2.32.bits.installer (1).tmp	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\Program Files\JamTaba 2\Jamtaba2.exe	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\DOCUME~1\Salon\LOCALS~1\Temp\is-T1VB1.tmp\Jamtaba.2.32.bits.installer.tmp	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\DOCUME~1\Salon\LOCALS~1\Temp\is-J8D9E.tmp\Jamtaba.2.32.bits.installer.tmp	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache
Référence MUI manquante	C:\DOCUME~1\Salon\LOCALS~1\Temp\is-2QD89.tmp\Jamtaba.2.32.bits.installer.tmp	HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache

Showing a problem with that key : 
HKCU\Software\Microsoft\Windows\ShellNoRoam\MUICache

I will try to fix the registry and make the uninstall test again ...

**Comment by Ezeer** [comment]
Tested uninstall after fixing the old registry keys , no change here , Jamtaba 2 folder still there .
I have used the shorcuts from the start menu , this is what usually people do i think .
( sometimes i use ccleaner that is more efficient than control panel for speed .... )

**Comment by jonjamcam** [comment]
Don't you think EZee that we need a special thread for windows XP? I've done some testing, but not published the results because XP behaves very different than modern O.S. and what happens there does not happen in my win7x64. OHHH....And only freaks like us still use it!!!

**Comment by Ezeer** [comment]
mmm... perhaps yes , as XP is no more supported , we are survivors ...
Elieser ?

**Comment by elieserdejesus** [comment]
About the survivors or about a win xp thread? hahaha

**Comment by jonjamcam** [comment]
https://www.youtube.com/watch?v=HYOXetfNEVY

**Comment by Ezeer** [comment]
**" About the survivors or about a win xp thread? hahaha "**
welcome in my world elieser ! ;)

Balboa is a cool guy .

My survivor point is : 
https://www.youtube.com/watch?v=2v4EphwE85o

**Comment by jonjamcam** [comment]
good music

**Comment by Ezeer** [comment]
An other survivor friend offered me that tune today : 
https://soundcloud.com/andre-louis/dinner-soon-come

**Comment by Ezeer** [comment]
>Guys, I test in win 7 64 bits, win 7 32 bits and Win XP. The Jamtaba folder is removed as expected in all tests. 
I'm using the Windows Control Panel to uninstall. How you are uninstalling?

we need to have more feedback from users for that issue ...

**Comment by jonjamcam** [comment]
I tested the latest release in xp and win7 x64 and the folder is removed.

**Comment by Ezeer** [comment]
I have used the Start->Jamtaba2->uninstall menu , the local folder is still here .
( on winxp sp3 )

**Comment by Ezeer** [comment]
It is a task that will grow for configurator class to compare Jamtaba 2 folders tree in the future .
( from old to newest versions )
So it may be important to fix that issue quickly .

**Comment by elieserdejesus** [comment]
Ezee, when you say "local folders is sill here" are you talking about the tree created by configurator?
If yes, I think this is a installer issue. By default the installer don't know the tree folder created in runtime, so it's necessary add the "delete" stuff in installer.

**Comment by Ezeer** [comment]
I don't know how to use inno you know .
Please recruit Tea and give him this task ?
lol

**Comment by elieserdejesus** [comment]
I will fix this, but I need confirm the details:
1- When you uninstall the folder created by installer in Program Files is removed?
2 - When you uninstall the folder created in AppData is removed?

I suppose 1 is yes, and 2 is no, right?

**Comment by Ezeer** [comment]
Actually , 1 = true and 2= false 

If you can remove "Jamtaba 2" and its content , maintain configurator will be easy !
thx by advance !

**Comment by elieserdejesus** [comment]
Solved! 
The only problem I detected is when user install Jamtaba logged in a guest account. I search for some magic flag in inno setup but I'm quiting for this job :)

**Comment by Ezeer** [comment]
wow ! Thank you ! It's pushed ? I need to make some tests right now to see how to proceed 
with treeExists() .
good job !

**Comment by elieserdejesus** [comment]
The uninstaller is removing all "Jamtaba 2" and subdirs, so it's flexible, we are free to create folders inside Jamtaba 2.

**Comment by Ezeer** [comment]
Magic !
![fantasia_mickey](https://cloud.githubusercontent.com/assets/1283808/11273220/47a24222-8ed2-11e5-8118-cea82aa85a12.jpg)
