### ISSUE TITLE
[VST Plugin] No separation between TopPanel and Channel in local tracks

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#861]
![image](https://cloud.githubusercontent.com/assets/15310433/25568673/547502f8-2dde-11e7-8f4c-07478f9386c8.png)

Standalone looks OK. Tested in Pre-release 3

**Comment by elieserdejesus** [comment]
Standalone (left image) and VST (right image) are still different, I could not find the code when the top margin is changed.

![image](https://user-images.githubusercontent.com/1012741/31509945-923b0342-af59-11e7-909e-6763a29f6d15.png)
