### ISSUE TITLE
[Looper] Loud recording levels through the looper

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#864]
I just started to do some looping to test the new pre-release3 and I found the monitoring level when **recording and recording waiting** is very loud compared to the normal channel input. PLaying sound good.

**Comment by jonjamcam** [comment]
@elieserdejesus I reverted to Release-2 and there's no problem here. I checked the history from the last week and the only changes to code related to the looper since last beta were https://github.com/elieserdejesus/JamTaba/commit/ca24a9fc530e8329daa1c37f54099df3400552b6 and  https://github.com/elieserdejesus/JamTaba/commit/469fca621171a54c8cfbbb7591ca1f6c7d80074d

Maybe there's the origin of the problem?

**Comment by elieserdejesus** [comment]
@jonjamcam , this bug was introduced in 380ed67f59d7ac7df4db32e80ea8ff75fecc89b2

I fixed this issue but the problem mentioned in #835 is appearing again. I see easy solution at moment for #835, so I will reopen the issue. This issue (#864) is more high priority.
