### ISSUE TITLE
No flag for Kosovo (.ks or .kv or .xk)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#868]
![image](https://cloud.githubusercontent.com/assets/15310433/25594861/d5f02852-2e98-11e7-8a12-ec33368fad48.png)

nop:

![image](https://cloud.githubusercontent.com/assets/15310433/25594932/2fcaa186-2e99-11e7-9429-ccdfa5538526.png)

Some context:

![image](https://cloud.githubusercontent.com/assets/15310433/25595023/a0024efe-2e99-11e7-8af5-b9d2a337d56d.png)
***
Some other Jamtaba flag names which are different from the accepted internet domain name:

catalonia -----------> .cat (https://en.wikipedia.org/wiki/.cat)
england ------------> N/A
europeanunion----->.eu
scotland  -----------> .scot (https://en.wikipedia.org/wiki/.scot)

I can create a PR fix this one @elieserdejesus , including creating the .KS (or .XK) flag

EDIT: Interestingly enough the domain name stored in the cache file for Kosovo is XK .

![image](https://cloud.githubusercontent.com/assets/15310433/25595686/058482d6-2e9c-11e7-87d0-64033ce0c5f6.png)

**Comment by elieserdejesus** [comment]
> I can create a PR fix this one @elieserdejesus , including creating the .KS (or .XK) flag

Shure @jonjamcam . Please use **xk.png** to the flag image file, I suppose will work out of the box.

***

> Some other Jamtaba flag names which are different from the accepted internet domain name:

The flag name is builded based in the **country code**, and the *country code* is returned by geoip.nekudo.com. We need to match nekudo api contry codes.

**Comment by jonjamcam** [comment]
> We need to match nekudo api country codes.

I'm unable to find more details on what are nekudo codes for .cat, .eu and .scot. I'll fix only the Kosovo flag/domain for the time being to be sure.

**Comment by jonjamcam** [comment]
It's working pretty good IMO:

![image](https://cloud.githubusercontent.com/assets/15310433/25597443/157453b6-2ea5-11e7-952f-d922ef613cd0.png)

PR: https://github.com/elieserdejesus/JamTaba/pull/869

**Comment by elieserdejesus** [comment]
perfect @jonjamcam !
