### ISSUE TITLE
[AU Plugin] New version notification could be not working

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#870]
Some AU Plugin users didn't know today morning that there was a new version available for download.

**Comment by elieserdejesus** [comment]
@Hitrate , the **new version available** message is appearing for you?

**Comment by Hitrate** [comment]
Yes but since I the updated to 2.1.1 no...if that’s what you mean

**Comment by Hitrate** [comment]
*then

**Comment by elieserdejesus** [comment]
> since I the updated to 2.1.1 no

It's ok, you will receive a new notification when we release **v2.1.2**.
