### ISSUE TITLE
Still some crashing in Mainstage here and there :)

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#871]
[jamtabacrash copy.docx](https://github.com/elieserdejesus/JamTaba/files/986273/jamtabacrash.copy.docx)

**Comment by Hitrate** [comment]
It happens when I mess around with soundcard settings and such mostly though.. One sticky problem is that there will be no sound when opening Mainstage up fresh - then I'll have to remove and re-insert jamtaba..like, I will see that my signal is coming into the soundcard, but no sound until I disable Jamtabe and re-enable/remove and reinsert jamtaba..

**Comment by Hitrate** [comment]
[JamtabaCrashSecondReport.docx](https://github.com/elieserdejesus/JamTaba/files/991400/JamtabaCrashSecondReport.docx)
This one made the whole thing crash when changing buffer size while in a room, by myself :P

**Comment by elieserdejesus** [comment]
@Hitrate, I will check these issues soon.

**Comment by elieserdejesus** [comment]
@fab672000 , can you help in this issue? Any experience in AU development?

**Comment by fab672000** [comment]
Using and building the standalone for now, not really experienced in AU as I used wdl iPlug encapsulation in the past, but will check that out next week-end. there must be a way to be notified in the plugin of a buffer size change and restart the audio engine when that happens ?
It is my first day on Jamtaba so still ramping up on / learning  it :)

**Comment by elieserdejesus** [comment]
> It is my first day on Jamtaba so still ramping up on / learning it :)

No rush @fab672000 , please take your time.

**Comment by elieserdejesus** [comment]
> One sticky problem is that there will be no sound when opening Mainstage up fresh - then I'll have to remove and re-insert jamtaba..like

Tested this issue in MainStage 3, no problems. After configure my inputs in MainStage preferences JamTaba is receiving the audio input as expected. 

> This one made the whole thing crash when changing buffer size while in a room

I changed the buffer size some times in MainStage 3 and JamTaba survive, no crashes.
