### ISSUE TITLE
Jamtaba for Android

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#872]
I understand the code is portable, but is it a pain to port Jamtaba (or a simplified version) to Android?

 I have a very nice Android phone that's more powerful than my computer and it's capable of recognizing USB audio hardware using a small adapter.

Latency in android is very high even in new devices, but if you could have direct monitoring, that should not be a problem in the ninjam world if the latency is compensated. And you could use the same USB interface you use on the computer. Pretty cool eh?

**Comment by elieserdejesus** [comment]
@jonjamcam , the idea is really cool, but after reading [How to Port From DEsktop to Mobile](https://wiki.qt.io/How_to_Port_From_Desktop_to_Mobile) I'm convinced it's a big pain (at moment) port to Android.  

The first big problem I can see is the UI. The entire UI need be redesigned to work in very small screens. 

Maybe a simplified version (MiniTaba 😄 ) can be possible.

**Comment by jonjamcam** [comment]
>Maybe a simplified version (MiniTaba 😄 ) can be possible

Sounds great! But this is definitely not a priority. Thx for considering the possibility.

**Comment by DoublebassOO** [comment]
i imagine myself playing flute in the forest a mic pluged in my android phone; birds singing around, and my dog running around.... what a wonderful world !

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907

**Comment by jonjamcam** [comment]
Hey guys. What's up. It's been some time since we discussed this issue. This last year I've been using my phone connected to the guitar pedal via usb to record some ideas mostly and I always miss not having access to ninjam servers on android. I wonder if at least could we have a test version of jamtaba as .apk to be sideloaded manually . I can try to compile in windows and test it in my phone. Maybe open some new roads to walk 😁.

**Comment by elieserdejesus** [comment]
Hi Jon!
I'm working in an Android App right now (not JamTaba related). The audio latency is good enough in modern devices, etc.

The big decision for me is: 

Keep the current code and strugle porting to Android or port everything to [JUCE](https://juce.com/) and get Android (and iOS) for free.

I suppose port the current code to Android is the same work to port the entire code to JUCE.

Both paths are a lot of work, very big, complicated and long term tasks. In my head it's something for a JamTaba 3.

**Comment by jonjamcam** [comment]
> Both paths are a lot of work, very big, complicated and long term tasks

I'm sure they are. Let me know if I can be of any help.

**Comment by MochaMage** [comment]
I'd be incredibly hyped with Jamtaba on Android, it would make it so much easier for more people to join, has there been any work on that? I've been curious about trying to build that but since I'm not super familiar with C++, it's been hard reading how a Ninjam server expects a client to behave
