### ISSUE TITLE
[LOOPER] Some sort of file select box for Loop Layer Sets

### ISSUE THREAD

**Issue by vector21** [elieserdejesus/JamTaba#874]
Hello everyone,

Thanks a lot for all the effort (hours) put into making the looper a reality - Its a very inspirational tool, love it! :-) The interface is very clean and easy to understand. Great work!

I tried saving some loops... and wanted to load the Loop Set a day later...

What i really miss is some sort of a file selection... Is it possible to add a standard (OS dependend) file select box here?

Greetings to all
Ech9000

**Comment by vector21** [comment]
Oh... btw... Is there any "file format definition" for Loop Sets yet? If not... I strongly suggest it! :-) 

*.JLS files ... (Jamtaba Loop Set)

**Comment by vector21** [comment]
Oh forget it... Im just to stupid to look! :-D
I found the load menu!!! Nice! :-)

**Comment by elieserdejesus** [comment]
It's solved @vector21?  Can I close the issue?
