### ISSUE TITLE
Some wrong english words and text enhancements

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#880]
Andy proposed:
... when Jamtaba scans for plugins in the standaloen version it says **founded**, its just **found** not founded.

Also **Built-in metronomes** should just be **Metronome** or **Metronome Sound** or **Metronome Effect**.

**Comment by jonjamcam** [comment]
> Also Built-in metronomes should just be Metronome or Metronome Sound or Metronome Effect.

I like "Metronome Sound"
***
"founded" string corrected in https://github.com/elieserdejesus/JamTaba/pull/885

**Comment by elieserdejesus** [comment]
@jonjamcam , "Metronome Sound" is good for me too. 

Just remember is necessary change all TS files 👍

**Comment by jonjamcam** [comment]
Ok @elieserdejesus . I'll complete it.

**Comment by DoublebassOO** [comment]
*fr_FR.ts* @DoublebassOO <https://github.com/doublebassoo>
Métronomes inclus : son du métronome

2017-06-28 5:18 GMT+02:00 jonjamcam <notifications@github.com>:

**Comment by elieserdejesus** [comment]
@jonjamcam , the PT-BR will be **Som do Metrônomo**.

**Comment by qulf** [comment]
@jonjamcam " Dźwięk metronomu: " is ok

**Comment by jonjamcam** [comment]
@elieserdejesus this issue is solved. It can be closed.

**Comment by elieserdejesus** [comment]
Thanks guys!
