### ISSUE TITLE
Easy to use private messages

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#882]
Proposed by Tom

> private messaging might be nice feature of jamtaba :) its available to all users but hard to type full ip addresses

```
/msg user@ip  WHATSUP
```

**Comment by jonjamcam** [comment]
@elieserdejesus I assume you need the full ip address for this to work? How to deal with truncated server ips?

**Comment by elieserdejesus** [comment]
@jonjamcam , I will test private messages with truncated IPs, I'm not shure if it's possible. If is not possible this feature will not be programable, no way to get complete IPs at moment. 

A solution to get full IPs is JamTaba connecting directly in servers using a special user name and password (like a bot). This is possible, but is necessary get user name and pass for all public servers contacting the servers admins.

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907

**Comment by elieserdejesus** [comment]
Good news in this issue!  I tested the private messages using ReaNinjam and works for masked IPs.

**Comment by elieserdejesus** [comment]
Hi @jonjamcam ! Now private chats are created with **right mouse button** in ninjam channels. But at moment the feature will not work because I need update the server to return the original IPs (including the mask). I tested the v2.1.0 with the changed server and **all country flags** will be replace with a Brazil flag. I like the flag, but I suppose ninjamers will not 😄

**Comment by jonjamcam** [comment]
XDDD . Nice feature btw

**Comment by jonjamcam** [comment]
Just tested it and It's amazing how simple it is to sen private messages to any client. For not-jamtaba users it's very messy to respond  though.

**Comment by elieserdejesus** [comment]
> For non-jamtaba users it's very messy to respond privately though.

Exactly @jonjamcam , very difficult send more than 2 private messages in ReaNinjam, the patience is not enough to type user@ip every time 😄
