### ISSUE TITLE
Looper offline mode

### ISSUE THREAD

**Issue by qulf** [elieserdejesus/JamTaba#888]
Hi all. Jamtaba is really good plugin. I have new idea to get looper to work offline.ls it possible?

**Comment by elieserdejesus** [comment]
Hi @qulf , can you ellaborate the **offline** term? 

Are you thinking in use the looper without connect in a server?

**Comment by qulf** [comment]
Yes

**Comment by elieserdejesus** [comment]
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907
