### ISSUE TITLE
VST Plugins makes asio4all collapse in Standalone 2.0.5 beta2 win7 x64

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#89]
Hey Guys....I was testing some  VST plugins in the Standalone version and once I add any plugin my ASIO4ALL icon starts flashing red (!) and the audio starts cutting out. I noticed this happens when using the listen button too.

Previous releases worked fine, but not this one.

EDIT: I reinstalled 2.0.4 and I can confirm there's a problem in 2.0.5 beta 2. The 2.0.4 is working just fine!

**Comment by Ezeer** [comment]
Hi jon !
You know the titile of my prefered song ?
It's " send me your log " !
( " Heaven must have sent you from above , heaven must have sent your precious looog ... " )

**Comment by elieserdejesus** [comment]
Ezee, If I can read your mind correct (mwah ha ha ha) you are suspecting form a huge log file? 
Possibly the last besta version is writing all log messages, this cause a overload and can be the explanation for the red icon in Asio4ALL.

**Comment by Ezeer** [comment]
I was joking with that real tune :
https://www.youtube.com/watch?v=mxgvmRbUG6w

In human words , jon , can you send us your log , please ? ( your love being already there )
eh eh

**Comment by jonjamcam** [comment]
I am using for comparison 2.0.4 official release, so that's the log I have now. Sorry I should have saved it :(. I will install beta again, test and send you the log.

**Comment by jonjamcam** [comment]
Ok I reinstalled, but now it's working fine ( :/) . mmmmmm.....anyway I'll keep an eye on this one. Seems to be my ASIO4ALL or my system.....

**Comment by Ezeer** [comment]
About vst4all and Jamtaba : It is set up with 128 as buffer size by default .
When you got troubles , check that value first .
I use 512 on my win32 Xp Sp3 with a basic motherboard sound chipset and works fine .
