### ISSUE TITLE
Crazy idea... AI Jam

### ISSUE THREAD

**Issue by qulf** [elieserdejesus/JamTaba#890]
Hi all. i Have fun idea. I found that on youtube

https://www.youtube.com/watch?v=QlVoR1jQrPk

and that is here

https://github.com/tensorflow/magenta-demos

Could it be possible to connect to jamtaba?

**Comment by elieserdejesus** [comment]
Hi @qulf , I think Artificial Intelligence based jams is a very interesting idea. It's not something I can work right now, but let's keep the idea open. It's very interesting!

**Comment by elieserdejesus** [comment]
issue moved to https://github.com/elieserdejesus/JamTaba/issues/907
