### ISSUE TITLE
Improve default recordings directory

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#891]
I'm using the default recording path in my machine and the result is messed, specially when I'm trying to find a previous saved loop. A first idea is just put all recorded jams inside a new **Jams** folder, and avoid the mess in the image:

![image](https://user-images.githubusercontent.com/1012741/29966653-405b1ce6-8ee9-11e7-9b13-c4189589e40b.png)

**Comment by jonjamcam** [comment]
Jams folder sounds good to me
