### ISSUE TITLE
To have floating windows for multi-screen

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#90]
I would like to have floating windows at my disposal , to moove them in a second screen , to display
for exemple the metronome informations or chat , depending on where i am located in my home-studio.
Also the possibility to have BIG LETTERS OR NUMBERS DISPLAYED would help when i am in a distant
place from the screen .
So : Floating windows with a ZOOM MODE .
Please ?
^^

**Comment by elieserdejesus** [comment]
I think is a good idea break this in 2 features: 
1 - Floating windows for the main screen sections.
2 - Zoom in windows. All floating windows need zoom?

**Comment by Ezeer** [comment]
2 _For accessibility ( visual deseases has more than one degree ) , it would be great .
But we need to have dedicated testers that have these deseases to judge what is useful or not .
 
 Now that Freak ( Andre Louis ) is on the team , i think it would be a good thing that he participates
to that kind of project as he has connections with a lot of people we don't know .
Perhaps create an Accessibility department in Jamtaba and give a chair to Freak to admin that stuff .
If the idea is good for you , can you propose it to him ?

**Comment by elieserdejesus** [comment]
Ezee, I like the idea. Please propose this idea to Andre Louis. You are contacting Andre, so I think you are the diplomat and the right person to ask Andre Louis about the a11y department :)

**Comment by Ezeer** [comment]
Done !
;)

**Comment by FreakyFwoof** [comment]
Yes, an #a11y department is all good, but not with just musicians like me. 
I'm not a programmer, I have no real way to contribute to this topic 
although I'd like to. You need some real, diehard hardcore programmers of 
which I have mentioned a few to Ezee, so I hope he will find the time to get 
in-touch with a few of them at least.
All I can do is provide music and sound for the app, and test it as an 
end-user.
Thanks.


----- Original Message -----

**Comment by Ezeer** [comment]
No problem FreakyFwoof , i've started the " touch and go " with twitter , thanks for your help here .

**Comment by elieserdejesus** [comment]
done in #fc2db02d75f30f7e077eba48dc08986cf451a734

**Comment by jonjamcam** [comment]
Interesting feature. Just tested and it looks to me that the shape of the metro is reset every time you enter a server:

![circle not kept](https://cloud.githubusercontent.com/assets/15310433/14230113/1fcc7fd8-f921-11e5-8aeb-c6b71176eb1d.jpg)

**Comment by elieserdejesus** [comment]
Some bug in this combobox, I will check soon. Thanks for report.

**Comment by elieserdejesus** [comment]
Bug solved in [this commit](https://github.com/elieserdejesus/JamTaba/commit/967006450cdfcf5cf0da546cf37d87214918fb38)
