### ISSUE TITLE
no sound being transmitted to the room when xmit is previously set to off

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#906]
I still haven't found why happens, but vadim and I were Xmitting to the room but others heard no sound. I suspect it could be related to entrering a room with xmit off and then turning xmit on. We both had to restart reaper and all went ok.

**Comment by jonjamcam** [comment]
@elieserdejesus I confirm this is exactly the problem. If you enter a server when xmit is off, then you wait for the preparing to end and turn on xmit, no sound will be transmitted to the room. If you enter with xmit on, there will be no problem.

**Comment by elieserdejesus** [comment]
I will check soon @jonjamcam , thanks for the infos.
