### ISSUE TITLE
Chat lag sometimes when using video

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#912]
I experienced a large amount of delay in the chat last night when some of us used video. It went from 5 sexonds to over 30 seconds

**Comment by jonjamcam** [comment]
Testing the new code for video, lag isn't happening anymore. Closing...

**Comment by elieserdejesus** [comment]
> Testing the new code for video, lag isn't happening anymore. Closing...

Very good news 😄
