### ISSUE TITLE
Rooms disapeared!

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#92]
Hey guys.

Something strange just happened. I was playing around with the vst menu in 2.0.5 beta2 and after some crashes (due to blacklisted plugins) restart didn't show any rooms.

Weird. So I uninstalled 2.0.5 beta and reinstalled 2.0.4 and same issue.

![no rooms snap](https://cloud.githubusercontent.com/assets/15310433/10974284/1bb07e26-83c0-11e5-801d-c4763a028871.jpg)

I forgot (again) to save the log file (my bad :/), but I will send you the actual log from last install..

[log.txt](https://github.com/elieserdejesus/JamTaba/files/28212/log.txt)

 Looks to me that my computer is having a bad day, but there's a possibility that is a Jamtaba issue. Can't say.

BTW connecting to rooms seems to be OK via private server.

Cheers!

**Comment by elieserdejesus** [comment]
Same problem here Jon, its' a problem in the server. I'm checking this right now.

**Comment by elieserdejesus** [comment]
It's some problem in ninbot,com. Ninbot is not showing the [servers](http://ninbot.com/app/servers.php) but I can see the servers in cockos url, and some ninjamers playing: [http://autosong.ninjam.com/server-list.php](http://autosong.ninjam.com/server-list.php).
Let's wait, probabily Tom will fix soon.

**Comment by jonjamcam** [comment]
yeah. Reaninjam appears normal too. Wahjam shows the list normally also.

**Comment by jonjamcam** [comment]
well rooms came back as soon as ninbot page was OK.

**Comment by Ezeer** [comment]
Yeah but that particular case was intersting and gave me the idea to display a picture instead
of the gray saaaaad cos' empty panel .
Perhaps a logo of kind " no connection to server " ?
![no-connection-landscape](https://cloud.githubusercontent.com/assets/1283808/10984147/c9a33ecc-8417-11e5-825b-b3fa384fa682.png)

**Comment by jonjamcam** [comment]
i'll leave it open then.....?

**Comment by Ezeer** [comment]
I'll let elieser answer to you on that subject because i'm not aware actually how Jamtaba connects ,
if think this is in the jamtaba's server part .

Anyway i followed my idea and started to tweak the css to have an idea of a working background : 
![capture d ecran 2015-11-06 00 28 00](https://cloud.githubusercontent.com/assets/1283808/10984936/800cfb76-841d-11e5-8d15-920cea2762b5.png)

**Comment by Ezeer** [comment]
Connection problem could be of kind : 
![capture d ecran 2015-11-06 00 33 37](https://cloud.githubusercontent.com/assets/1283808/10985014/04c5a0de-841e-11e5-863f-8d77e604c9c5.png)

**Comment by Ezeer** [comment]
**" how about an emergency dialog box with the old way to connect? like reaninjam or wahjam above.... "**
Perhaps the Ninjam private server could be used for that ?

**Comment by jonjamcam** [comment]
As I understand it jamtaba uses the ninbot app to connect, that shows the countries, listen button, etc, but that's not the way the original ninjam client and reaninjam connect. They connect using the servers list on ninjam.com

http://autosong.ninjam.com/server-list.php

this old way is very basic, but does not depend on ninbot.com to be working or not. 

I think it's a bad idea to only depend on the ninbot site having other more reliable ways......that BTW the other clients use.

Looks like Martin is using Jamtaba too because I was playing and he asked me what happened to the rooms...You see more and more people are using Jamtabaa nd if it doesn't work, they'll go back to reaninjam....

**Comment by elieserdejesus** [comment]
Guys, Jamtaba connect with jamtaba server and receive a list of public servers and connected musicians. Jamtaba server is requesting this list from 2 sources: [http://autosong.ninjam.com/serverlist.php](http://autosong.ninjam.com/serverlist.php) and [http://ninbot.com/app/servers.php](http://ninbot.com/app/servers.php).

Why 2 sources to make a single list?

In the first link I have the **maxUsers** from every server. Jamtaba is using this info to disable the "Enter" button when a server is full. Some servers allow 6 users, other allow 8, etc.
But in this first link we can't get the users IP, and without user IPs we can't translate the IP to a country name, and show a cool flag for the country. The Ninbot link is returning users IPs, but not the server **maxUsers**.
To have all necessary info jamtaba server is merging this 2 sources.

A third and dirty solution is use this: [http://autosong.ninjam.com/server-list.php](http://autosong.ninjam.com/server-list.php)

In this cockos official site is possible get **maxUsers** and users IPs, but we need get this infos directly in HTML code [scrapping], not very fun, but possible.

**Comment by jonjamcam** [comment]
just for the record rooms are down again..... well maybe when ninbot list is down use the third solution? instead of an empty page ;)

**Comment by Ezeer** [comment]
IT IS CRITiCAL  TO FIX THAT S**** !
@jonjamcam  :+1:

**Comment by Ezeer** [comment]
@elieserdejesus  I think at the " safe mode " of windows system .
We could implement that at connection level perhaps ?
But it's mainly server side i guess .

**Comment by elieserdejesus** [comment]
Ezee, I start a fix for this shit. I'm trying the HTML scrapping solution. But the HTML code in cockos public servers is the worst HTML code I see in my life. Unfortunally the code is completely unstrutucted, very hard to get something usefull.

I keep trying...

**Comment by Ezeer** [comment]
May the force be with you !
:trophy:

**Comment by elieserdejesus** [comment]
I think I have found a good enough solution. Now when ninbot fail Jamtaba server is using the autosong (the common url used by all ninjam clients) infos. In this situations we can't see the country flags/names in public rooms window, because autosong don't return the users IPs, so we can't translate IP to country name. 

I prefer the room list populated but without country names than a empty room list. So, I think is a good solution :)

**Comment by jonjamcam** [comment]
Great! Bullet proof Jamtaba!

**Comment by elieserdejesus** [comment]
Jon, these links are returned by ninbot (when works). We can type these links directly in the code when ninbot fails, but the servers admin can change these links, so is not a 100% solution. If some server admin change the links our code is pointing to wrong url.

I'm working in Jamtaba for some years and this is the first time I see ninbot failing. So I'm shure this is just a little issue in the ninbot servers. If we have more and frequent problems we can use the links directly in the code, is not 100% bullet proof but works.

Let's wait, for while we have a good enough solution.

**Comment by Ezeer** [comment]
**Let's wait, for while we have a good enough solution.**
my two cents for improve your solution : 
So you like flags ? why not use something like this : :soon:  :warning:
as flags for the player ?

That woul sdhow something unusual is happening , but we deal with it ?

**Comment by elieserdejesus** [comment]
Done!
![sem titulo](https://cloud.githubusercontent.com/assets/1012741/11017866/491584b6-8595-11e5-8fa8-36f0d72325eb.png)

**Comment by jonjamcam** [comment]
That's what I call Transparent. You leave the quality bar very high, Elieser!

**Comment by Ezeer** [comment]
good job !
:+1:
