### ISSUE TITLE
channel name placeholder (enabled channel only) in local channels too narrow for "channel name" to appear complete (all themes except black theme)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#923]
![image](https://user-images.githubusercontent.com/15310433/31563284-c18b6dea-b034-11e7-8735-f178819f7712.png)

EDIT: Rounded theme has the problem in both enabled and disabled local channels:

![image](https://user-images.githubusercontent.com/15310433/31563775-d957c624-b036-11e7-9dc7-5a3463b4beaf.png)

**Comment by elieserdejesus** [comment]
Can you fix this @jonjamcam ?  I think it's the **padding-left** and **padding-right** in CSS files.

**Comment by jonjamcam** [comment]
>Can you fix this @jonjamcam ? 

Sure @elieserdejesus . No problem.
