### ISSUE TITLE
ninjampanel not expected when collapsing bottom area before connecting to a server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#926]
Also the bottom area does not show the line metronome as expected.

![image](https://user-images.githubusercontent.com/15310433/31580495-87668ad4-b127-11e7-9778-ebde749c4fcf.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , my bad, it's fixed in the last commit https://github.com/elieserdejesus/JamTaba/commit/2cc1539c9e43d583e9bd28840174e49fce948411

I changed a lot of things in the layout code to allow collapse. Many code changes means more bugs :(
