### ISSUE TITLE
if you collapse bottom area and restore it, the LINE metronome is always shown regardless of what the ninjampanel is set to

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#928]
![image](https://user-images.githubusercontent.com/15310433/31580459-ba3ac890-b126-11e7-9165-4bf7afea8586.png)

I think the expected behavior is to return to elipse, circle or pie too when restoring bottom area if that was previously selected

**Comment by elieserdejesus** [comment]
It's fixed in last commit.
