### ISSUE TITLE
Can we have a little cpu/memory meter?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#93]
you can't tell if the system it's being overloaded when using plugins, specially those memory hungry sample libraries.

what do you think guys?

**Comment by Ezeer** [comment]
Good idea jon , we should do something because that meter is useful .
Thank you !

**Comment by Ezeer** [comment]
A good thread with a lot of information for windows and linux : 
http://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process

**Comment by Ezeer** [comment]
Si Jon , where do you you think it should , visually ?

**Comment by jonjamcam** [comment]
I like this place......similar to kontakt's one....Discrete an non invasive.....

![cpu meter](https://cloud.githubusercontent.com/assets/15310433/11039787/168fd1b4-86e8-11e5-9d32-f796c926de3a.jpg)

**Comment by Ezeer** [comment]
@jonjamcam  That looks good to me ! 
@elieserdejesus  Your opinion ?

**Comment by elieserdejesus** [comment]
Ezee, I post in another issue, I'm working on this:
![image](https://cloud.githubusercontent.com/assets/1012741/11088668/29168878-884b-11e5-878c-034724ec58b4.png)

**Comment by elieserdejesus** [comment]
closing, partially done in #667
