### ISSUE TITLE
Video decoder crashing

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#930]
Reported by @jonjamcam :

**FFMpegDemuxer::decode** is crashing, no more clues about the crash context:

```
default.CRITICAL  [23:28:05:616] 000007FEE5ABB21D (JamtabaVST2): (filename not available): StackWalker::ShowCallstack

default.CRITICAL  [23:28:05:791] 000007FEE560B065 (JamtabaVST2): (filename not available): WindowsStackWalker::topLevelExceptionHandler
default.CRITICAL  [23:28:05:807] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn
default.CRITICAL  [23:28:05:814] 0000000077509450 (kernel32): (filename not available): UnhandledExceptionFilter
default.CRITICAL  [23:28:05:816] 00000000777243B8 (ntdll): (filename not available): MD5Final
default.CRITICAL  [23:28:05:817] 00000000776A85A8 (ntdll): (filename not available): _C_specific_handler
default.CRITICAL  [23:28:05:818] 00000000776B9D0D (ntdll): (filename not available): RtlDecodePointer
 
default.CRITICAL  [23:28:05:819] 00000000776A91AF (ntdll): (filename not available): RtlUnwindEx
 
default.CRITICAL  [23:28:05:821] 00000000776E1278 (ntdll): (filename not available): KiUserExceptionDispatcher
 
default.CRITICAL  [23:28:05:900] 000007FEE55A0E5F (JamtabaVST2): (filename not available): FFMpegDemuxer::decode
 
default.CRITICAL  [23:28:05:916] 000007FEE55974A3 (JamtabaVST2): (filename not available): QtConcurrent::RunFunctionTask<void>::run
 
default.CRITICAL  [23:28:06:188] 000007FEE626BD4B (JamtabaVST2): (filename not available): QThreadPoolThread::run
 
default.CRITICAL  [23:28:06:333] 000007FEE623EBCA (JamtabaVST2): (filename not available): QThreadPrivate::start
 
default.CRITICAL  [23:28:06:335] 000007FEEECD4F7F (MSVCR120): (filename not available): beginthreadex
 
default.CRITICAL  [23:28:06:338] 000007FEEECD5126 (MSVCR120): (filename not available): endthreadex
 
default.CRITICAL  [23:28:06:340] 000000007748652D (kernel32): (filename not available): BaseThreadInitThunk
 
default.CRITICAL  [23:28:06:341] 00000000776BC521 (ntdll): (filename not available): RtlUserThreadStart
```

**Comment by elieserdejesus** [comment]
@jonjamcam  send me another crash, but from standalone. Crashing in same function:
```
default.INFO      [23:30:41:466] "Starting Jamtaba 2.1.1 Standalone (x86_64) running on Windows 7 (x86_64)"

default.CRITICAL  [23:43:26:612] 000000013FCCC63D (Jamtaba2): (filename not available): StackWalker::ShowCallstack

default.CRITICAL  [23:43:26:674] 000000013F86D0E5 (Jamtaba2): (filename not available): WindowsStackWalker::topLevelExceptionHandler

default.CRITICAL  [23:43:26:676] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn

default.CRITICAL  [23:43:26:677] 0000000077509450 (kernel32): (filename not available): UnhandledExceptionFilter

default.CRITICAL  [23:43:26:678] 00000000777243B8 (ntdll): (filename not available): MD5Final

default.CRITICAL  [23:43:26:680] 00000000776A85A8 (ntdll): (filename not available): _C_specific_handler

default.CRITICAL  [23:43:26:681] 00000000776B9D0D (ntdll): (filename not available): RtlDecodePointer

default.CRITICAL  [23:43:26:682] 00000000776A91AF (ntdll): (filename not available): RtlUnwindEx

default.CRITICAL  [23:43:26:683] 00000000776E1278 (ntdll): (filename not available): KiUserExceptionDispatcher

default.CRITICAL  [23:43:26:731] 000000013FBCC4DF (Jamtaba2): (filename not available): av_read_frame

default.CRITICAL  [23:43:26:805] 000000013F802C31 (Jamtaba2): (filename not available): FFMpegDemuxer::decode

default.CRITICAL  [23:43:26:819] 000000013F7F9503 (Jamtaba2): (filename not available): QtConcurrent::RunFunctionTask<void>::run

default.CRITICAL  [23:43:26:965] 00000001405ACFAB (Jamtaba2): (filename not available): QThreadPoolThread::run

default.CRITICAL  [23:43:27:101] 000000014057FF9A (Jamtaba2): (filename not available): QThreadPrivate::start

default.CRITICAL  [23:43:27:102] 000007FEF2E04F7F (MSVCR120): (filename not available): beginthreadex

default.CRITICAL  [23:43:27:103] 000007FEF2E05126 (MSVCR120): (filename not available): endthreadex

default.CRITICAL  [23:43:27:105] 000000007748652D (kernel32): (filename not available): BaseThreadInitThunk

default.CRITICAL  [23:43:27:106] 00000000776BC521 (ntdll): (filename not available): RtlUserThreadStart
```

**Comment by elieserdejesus** [comment]
Another video decoder crash log sended by Andy:

```
default.INFO      [01:38:10:334] "Starting Jamtaba 2.1.1 Vst Plugin (x86_64) running on Windows  (x86_64) running in Cubase"
default.CRITICAL  [02:44:44:500] 00007FFE1493939D (JamtabaVST2): (filename not available): StackWalker::ShowCallstack

default.CRITICAL  [02:44:44:502] 00007FFE14488ED5 (JamtabaVST2): (filename not available): WindowsStackWalker::topLevelExceptionHandler

default.CRITICAL  [02:44:44:503] 00007FFE6BFF6913 (KERNELBASE): (filename not available): UnhandledExceptionFilter

default.CRITICAL  [02:44:44:504] 00007FFE6F2BDA9D (ntdll): (filename not available): memset

default.CRITICAL  [02:44:44:505] 00007FFE6F2A6466 (ntdll): (filename not available): _C_specific_handler

default.CRITICAL  [02:44:44:506] 00007FFE6F2BA07D (ntdll): (filename not available): _chkstk

default.CRITICAL  [02:44:44:507] 00007FFE6F229C58 (ntdll): (filename not available): RtlLookupFunctionEntry

default.CRITICAL  [02:44:44:508] 00007FFE6F2B90FE (ntdll): (filename not available): KiUserExceptionDispatcher

default.CRITICAL  [02:44:44:533] 00007FFE143169E1 (JamtabaVST2): (filename not available): ff_clear_blocks_sse

default.CRITICAL  [02:44:44:554] 00007FFE145C5EF2 (JamtabaVST2): (filename not available): ff_mpeg4videodec_static_init

default.CRITICAL  [02:44:44:556] 00007FFE145B023A (JamtabaVST2): (filename not available): ff_h263_decode_end

default.CRITICAL  [02:44:44:557] 00007FFE145AFB94 (JamtabaVST2): (filename not available): ff_h263_decode_frame

default.CRITICAL  [02:44:44:583] 00007FFE1458FB91 (JamtabaVST2): (filename not available): avcodec_send_packet

default.CRITICAL  [02:44:44:584] 00007FFE1458F9EB (JamtabaVST2): (filename not available): avcodec_send_packet

default.CRITICAL  [02:44:44:586] 00007FFE1458EF8D (JamtabaVST2): (filename not available): avcodec_send_packet

default.CRITICAL  [02:44:44:587] 00007FFE1458F4CA (JamtabaVST2): (filename not available): avcodec_send_packet

default.CRITICAL  [02:44:44:599] 00007FFE14420E6A (JamtabaVST2): (filename not available): FFMpegDemuxer::decode

default.CRITICAL  [02:44:44:600] 00007FFE14417713 (JamtabaVST2): (filename not available): QtConcurrent::RunFunctionTask<void>::run

default.CRITICAL  [02:44:44:624] 00007FFE150E825B (JamtabaVST2): (filename not available): QThreadPoolThread::run

default.CRITICAL  [02:44:44:627] 00007FFE150BB0DA (JamtabaVST2): (filename not available): QThreadPrivate::start

default.CRITICAL  [02:44:44:628] 00007FFE4B0E4F7F (MSVCR120): (filename not available): beginthreadex

default.CRITICAL  [02:44:44:629] 00007FFE4B0E5126 (MSVCR120): (filename not available): endthreadex

default.CRITICAL  [02:44:44:630] 00007FFE6C922774 (KERNEL32): (filename not available): BaseThreadInitThunk

default.CRITICAL  [02:44:44:631] 00007FFE6F280D51 (ntdll): (filename not available): RtlUserThreadStart
```

**Comment by jonjamcam** [comment]
I don't know if this helps, but we were using 3 cams at the time of the crash:

![image](https://user-images.githubusercontent.com/15310433/31591249-107035b0-b1f4-11e7-9d96-0446b037d094.png)

(nice pict tho :smile: )

**Comment by jonjamcam** [comment]
I'm testing last couple of days Jamtaba standalone compiled with QT5.6 (non-static) to check it's behavior. Today I got a crash just after closing it (no video used) and there are similarities with above logs:
***
Starting C:\Users\jon\Documents\_Jamtaba github\My_Fork\JamTaba\PROJECTS\build-Standalone-Desktop_Qt_5_6_3_MSVC2013_64bit-Release\release\Jamtaba2.exe...
default.INFO      [21:11:39:010] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [21:11:43:929] "Starting Jamtaba 2.1.1 Standalone (x86_64) running on Windows 7 (x86_64)" [, line 0]
default.CRITICAL  [21:20:19:534] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:20:19:536] invalid channel index ( "1" ), can't update the channel! [, line 0]

(ML_WAIT_TIMEOUT)
1396default.CRITICAL  [21:25:05:467] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:26:10:195] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:31:50:553] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:35:17:487] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:38:43:571] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:40:49:540] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:41:39:160] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [21:56:05:442] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:00:01:074] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:01:11:418] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:10:14:727] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.DEBUG     [22:14:32:490] "JamTaba closed without crash :)" [, line 0]
default.CRITICAL  [22:14:32:510] avioContext is null [, line 0]
default.CRITICAL  [22:14:35:079] 000000013F648ABD (Jamtaba2): (filename not available): StackWalker::ShowCallstack
 [, line 0]
default.CRITICAL  [22:14:35:172] 000000013F1EC535 (Jamtaba2): (filename not available): WindowsStackWalker::topLevelExceptionHandler
 [, line 0]
default.CRITICAL  [22:14:35:198] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn
 [, line 0]
default.CRITICAL  [22:14:35:205] 0000000077B89450 (kernel32): (filename not available): UnhandledExceptionFilter
 [, line 0]
default.CRITICAL  [22:14:35:205] 0000000077CA43B8 (ntdll): (filename not available): MD5Final
 [, line 0]
default.CRITICAL  [22:14:35:206] 0000000077C285A8 (ntdll): (filename not available): _C_specific_handler
 [, line 0]
default.CRITICAL  [22:14:35:206] 0000000077C39D0D (ntdll): (filename not available): RtlDecodePointer
 [, line 0]
default.CRITICAL  [22:14:35:206] 0000000077C291AF (ntdll): (filename not available): RtlUnwindEx
 [, line 0]
default.CRITICAL  [22:14:35:207] 0000000077C61278 (ntdll): (filename not available): KiUserExceptionDispatcher
 [, line 0]
default.CRITICAL  [22:14:35:207] 0000000004CA1243 (ADM_x64): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [22:14:35:208] 0000000004C91339 (ADM_x64): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [22:14:35:208] 0000000004C8B566 (ADM_x64): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [22:14:35:209] 0000000004C8B6D9 (ADM_x64): (filename not available): VSTPluginMain
 [, line 0]
default.CRITICAL  [22:14:35:209] 0000000077C34371 (ntdll): (filename not available): LdrShutdownProcess
 [, line 0]
default.CRITICAL  [22:14:35:210] 0000000077C34180 (ntdll): (filename not available): RtlExitUserProcess
 [, line 0]
default.CRITICAL  [22:14:35:210] 000007FEE7A629A7 (MSVCR120): (filename not available): initterm_e
 [, line 0]
default.CRITICAL  [22:14:35:382] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c (662): __tmainCRTStartup
 [, line 0]
default.CRITICAL  [22:14:35:383] 0000000077B0652D (kernel32): (filename not available): BaseThreadInitThunk
 [, line 0]
default.CRITICAL  [22:14:35:383] 0000000077C3C521 (ntdll): (filename not available): RtlUserThreadStart
 [, line 0]
***
as you can see Jamtaba closed without a crash:

` [22:14:32:490] "JamTaba closed without crash :)" [, line 0]`

but then it crashed :thinking:

**Comment by elieserdejesus** [comment]
> I see the code has samplerate hardcoded to 44100 in FFMpegMuxer.cpp. I use 48000. Could this be a problem?

No @jonjamcam , at moment the muxer is video only, the audio code is never called because the audio stream is sepparated from video. This code you are pointing will be usefull to generate ONE stream including audio and video (this will be not compatible with other ninjam clients).

@jonjamcam , about your last crash log: I see the line
```
default.CRITICAL [22:14:35:207] 0000000004CA1243 (ADM_x64): (filename not available): VSTPluginMain
[, line 0]
```

Is **ADM** a VST plugin? I think this plugin is crashing when deleted or JT is crashing. 
If yes (ADM is a plugin) can test with another VST plugins?

**Comment by jonjamcam** [comment]
> Is ADM a VST plugin?

Yes. ADM Is working fine but making jamtaba crash when exiting. ATM no problems with other plugins.

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the video decoding strategy to something more safe (in theory). Please help testing and let's see if is stable now.

**Comment by jonjamcam** [comment]
Testing. Only me with camera. I got a crash exactly at the moment when switching between my laptop camera and droidcam (phone). I will keep testing with only one camera to avoid complications, but this is the log for the record:

-OKC:\Users\jon\Documents\_Jamtaba github\My_Fork\JamTaba\PROJECTS\build-Standalone-Desktop_Qt_5_6_3_MSVC2013_64bit-Release\release\Jamtaba2.exe exited with code 0

Starting C:\Users\jon\Documents\_Jamtaba github\My_Fork\JamTaba\PROJECTS\build-Standalone-Desktop_Qt_5_6_3_MSVC2013_64bit-Release\release\Jamtaba2.exe...
default.INFO      [22:07:07:445] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [22:07:07:797] "Starting Jamtaba 2.1.1 Standalone (x86_64) running on Windows 7 (x86_64)" [, line 0]
default.DEBUG     [22:07:16:656] Setting video resolution to QSize(640, 480) [, line 0]
default.DEBUG     [22:08:33:860] Setting video resolution to QSize(160, 120) [, line 0]
default.DEBUG     [22:08:41:032] Setting video resolution to QSize(640, 480) [, line 0]
default.CRITICAL  [22:10:26:987] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:10:26:988] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.DEBUG     [22:13:49:628] Setting video resolution to QSize(640, 480) [, line 0]
default.DEBUG     [22:13:54:678] Setting video resolution to QSize(160, 120) [, line 0]
default.CRITICAL  [22:13:58:625] 000000013FDEC8ED (Jamtaba2): (filename not available): StackWalker::ShowCallstack
 [, line 0]
default.CRITICAL  [22:13:58:627] 000000013F98FED5 (Jamtaba2): (filename not available): WindowsStackWalker::topLevelExceptionHandler
 [, line 0]
default.CRITICAL  [22:13:58:629] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn
 [, line 0]
default.CRITICAL  [22:13:58:631] 0000000077849450 (kernel32): (filename not available): UnhandledExceptionFilter
 [, line 0]
default.CRITICAL  [22:13:58:632] 00000000779643B8 (ntdll): (filename not available): MD5Final
 [, line 0]
default.CRITICAL  [22:13:58:634] 00000000778E85A8 (ntdll): (filename not available): _C_specific_handler
 [, line 0]
default.CRITICAL  [22:13:58:635] 00000000778F9D0D (ntdll): (filename not available): RtlDecodePointer
 [, line 0]
default.CRITICAL  [22:13:58:637] 00000000778E91AF (ntdll): (filename not available): RtlUnwindEx
 [, line 0]
default.CRITICAL  [22:13:58:638] 0000000077921278 (ntdll): (filename not available): KiUserExceptionDispatcher
 [, line 0]
default.CRITICAL  [22:13:58:640] 000007FEE977C630 (MSVCR120): (filename not available): memcpy
 [, line 0]
default.CRITICAL  [22:13:58:643] 000000013FA60C6E (Jamtaba2): (filename not available): ff_write_quant_matrix
 [, line 0]
default.CRITICAL  [22:13:58:646] 000000013FA4EBED (Jamtaba2): (filename not available): ff_mpv_encode_picture
 [, line 0]
default.CRITICAL  [22:13:58:649] 000000013FA40A90 (Jamtaba2): (filename not available): avcodec_encode_video2
 [, line 0]
default.CRITICAL  [22:13:58:651] 000000013F9277B6 (Jamtaba2): (filename not available): FFMpegMuxer::doEncodeVideoFrame
 [, line 0]
default.CRITICAL  [22:13:58:654] 000000013F925D85 (Jamtaba2): (filename not available): FFMpegMuxer::encodeImage
 [, line 0]
default.CRITICAL  [22:13:58:659] 000000013F920BE4 (Jamtaba2): (filename not available): QtConcurrent::RunFunctionTask<void>::run
 [, line 0]
default.CRITICAL  [22:13:58:663] 0000000062FEBD6B (Qt5Core): (filename not available): QThreadPoolPrivate::reset
 [, line 0]
default.CRITICAL  [22:13:58:674] 0000000062FEF13A (Qt5Core): (filename not available): QThread::start
 [, line 0]
default.CRITICAL  [22:13:58:675] 000007FEE9764F7F (MSVCR120): (filename not available): beginthreadex
 [, line 0]
default.CRITICAL  [22:13:58:677] 000007FEE9765126 (MSVCR120): (filename not available): endthreadex
 [, line 0]
default.CRITICAL  [22:13:58:679] 00000000777C652D (kernel32): (filename not available): BaseThreadInitThunk
 [, line 0]
default.CRITICAL  [22:13:58:680] 00000000778FC521 (ntdll): (filename not available): RtlUserThreadStart
 [, line 0]
The program has unexpectedly finished.
C:\Users\jon\Documents\_Jamtaba github\My_Fork\JamTaba\PROJECTS\build-Standalone-Desktop_Qt_5_6_3_MSVC2013_64bit-Release\release\Jamtaba2.exe crashed.

**Comment by elieserdejesus** [comment]
@jonjamcam , I will create a new issue, because this last log is about the video encoder and cam changes.

**Comment by elieserdejesus** [comment]
@Hitrate , can you help testing the beta? https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.2-beta

**Comment by Hitrate** [comment]
Ya thx I will :)

**Comment by Hitrate** [comment]
Oh nooo..this is not good, not good :) 
All themes have the same red and green metronome section...Impossible for color blind people ;)

![screen shot 2017-10-20 at 4 18 07 pm](https://user-images.githubusercontent.com/26333462/31825438-8e3fd236-b5b2-11e7-8d19-94ec612b9ed8.png)


Also I keep getting this crash in the 2.1.1 mentioning my sRGB profile...

default.INFO      [02:41:12:439] JamTaba Base dir: "/Users/torbenscharling/Library/Application Support/JamTaba 2/AUPlugin" [Configurator.cpp, line 219]
default.INFO      [02:41:12:480] "Starting Jamtaba 2.1.1 AU Plugin (x86_64) running on OS X El Capitan (10.11) (x86_64) running in Logic10" [MainController.cpp, line 970]
default.WARNING   [02:41:13:058] libpng warning: iCCP: known incorrect sRGB profile [, line 0]


And so far with several tries, restarts and re-insertion of the plugin and of my sound card in soundcard settings in LPX, can't connect...bpi button stays at 1 and in preparing mode..

**Comment by elieserdejesus** [comment]
This red background is unexpected, I will create a new issue.

> Also I keep getting this crash in the 2.1.1 mentioning my sRGB profile...

This is just an warning about one of the JTBA images using a incorrect sRGB profile, this is not causing crashes. I have some of these warning in Windows too.

**Comment by Hitrate** [comment]
Ah okay great, was thinking it can't be my choice of screen sRGB profile so glad it's not that ;)
