### ISSUE TITLE
[AU Plugin] Crashed when changing metronome sounds.

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#934]
Reported by email:
```
These past two days both crashed when changing metronome sounds.
```

**Comment by elieserdejesus** [comment]
@Hitrate , I tested changing metronome sounds in AU plugin and have no crashes. Can you remember more details about the **crash when changing metronome sounds**?

**Comment by Hitrate** [comment]
I have not been changing metronome sounds, so that’s easy: all my crashes has been from other issues..

**Comment by elieserdejesus** [comment]
> I have not been changing metronome sounds

Another user reported the problem, possibly it's not related with change metronome sounds.
