### ISSUE TITLE
Possibly force chat typing in Jamtaba

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#937]
I have this problem where I sometimes start typing while in logic window or plugin, cause I thought I was already in “chat” mode...

Would there be a way to force the focus of the typing to the jamtaba chat, so that I don’t accidentally activate a bunch of things in logic that I shouldn’t have, or stop the sequence and things like that...? Since I’m fiddling around with sounds and stuff and going back and from typing mode, I sometimes mess things up cause the system acts as if I’m trying to use shortcuts within logic, when I’m actually trying to type in the chat...

I have a bunch of midi controllers to adjust things so I could live with being in forced “typing in the jamtaba chat window” mode...Obviously this could be debated if it should turn into the default way it works, or if it should be an option in preferences for users like me :)

**Comment by elieserdejesus** [comment]
@Hitrate , keyboard focus is a pain both in VST or AU world. The DAW is always controlling the keyboard focus.

> Would there be a way to force the focus of the typing to the jamtaba chat ...?

I don't know a way to do this.

Hi @fab672000, you have some idea to help us?

**Comment by Hitrate** [comment]
Ok. I guess if there was a way Jamtaba could have its own “controller or typing input” independently of the daw, one could have a cheap usb or bluetooth keyboard hooked up that would always type on the Jamtaba chat...one can dream right?! :D

**Comment by Hitrate** [comment]
Andy mentioned Jbridge in another thread and the positives of having it (the plugin it’s bridging) crash independently of the daw...perhaps that means it could be used for the keyboard focus/input also?

**Comment by fab672000** [comment]
> @Hitrate , keyboard focus is a pain both in VST or AU world. The DAW is always controlling the keyboard focus.
> 
> Would there be a way to force the focus of the typing to the jamtaba chat ...?
> I don't know a way to do this.
Try opening the plugin as a floating window ? (Control-Option-double-click)

**Comment by elieserdejesus** [comment]
> AFAIK jamtaba has no standard way of changing the keyboard focus as an AU plugin

I agree with @fab672000, I can't see a programable solution at moment. The best idea is the @fab672000 suggestion.


> Ok. I guess if there was a way Jamtaba could have its own “controller or typing input” independently of the daw, one could have a cheap usb or bluetooth keyboard hooked up that would always type on the Jamtaba chat...one can dream right?! :D

Great idea @Hitrate 😄 , but too complex for my skills.
