### ISSUE TITLE
The output volume of chained plugin decreases compared to one single plugin in 2.0.4

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#94]
Let me explain this. I am testing using two audio plugins in chain (ADM [drum machine] and mobius[looper]). Adm generates a beat first and passes it to mobius which captures the loop and plays it indefitively. What I found is that the total volume is correct when recording the loop, but once you stop ADM and let mobius play alone, the volume decreases. I can hear some doubling and this could mean that we hear both added rather than a serial configuration. The sound should be olny from the last plugin in the chain

I tested the same chain in reaper and the volume stays constant.

**Comment by elieserdejesus** [comment]
Jon, I work in some similar problem in 2.0.5. Can you test the same plugin chain in 2.0.5?

**Comment by jonjamcam** [comment]
the problem persists in 2.0.5, Elieser.

**Comment by elieserdejesus** [comment]
ok thanks, one more but to fix :)

**Comment by Ezeer** [comment]
Robots never sleep !
![220px-hal9000 svg](https://cloud.githubusercontent.com/assets/1283808/10899516/c2821b70-81d5-11e5-9f3d-49d5203e2088.png)
lol

**Comment by jonjamcam** [comment]
hey man, you are a watchdog!

**Comment by Ezeer** [comment]
I just discovered that i rule the world man !
check your six !
^^

**Comment by jonjamcam** [comment]
Elieser, I found that when the input is analog audio this problem doesn't happen at least with mobius. Remember this happened when the chain was purely digital

**Comment by elieserdejesus** [comment]
Jon, this is a very good clue and will help me solving this bug, thanks.

**Comment by elieserdejesus** [comment]
@jonjamcam , you report this problem, can you test the new 2.0.5 RC3?

**Comment by jonjamcam** [comment]
Workig Perfect now Elieser!.....hey you are THE BOSS!

**Comment by elieserdejesus** [comment]
Nice jon, every time I need touch this part of the code I have bad dreams :)
