### ISSUE TITLE
[VST] Chat text being wiped when someone joins

### ISSUE THREAD

**Issue by elieserdejesus** [elieserdejesus/JamTaba#947]
Reported by Andy:

> when ya type somethign int he chat on the vst, nto sure ifits same onstandalone but when when someone joins it wipes out what ya typed in the white type box

**Comment by elieserdejesus** [comment]
Andy added some info:
> i wrap jamtaba in jbridge but i don't think that is the issue but just to let you know that info too.

**Comment by jonjamcam** [comment]
I think this has to do with the vst hack to catch keystrokes. I remember once typing some text but not sending, then change the focus to other part (maybe mute something) and when I returned to complete the text it disappeared.

**Comment by Remeslennik** [comment]
v2.1.3 If someone wrote a long message in the chat, then the text field does not increase. And so you can see only first line of text.

**Comment by elieserdejesus** [comment]
I tried reproduce the issue in the VST plugin but is working ok. I tested Standalone x VST plugin. When I enter in the server the text in VST plugin chat **is not wiped**, it's working as expected.

Maybe this was fixed (by accident) in last commits or this is a JBridge issue as mentioned by Andy.

The problem mentioned by @Remeslennik is fixed too in the last (not released yet) version.
