### ISSUE TITLE
Chat translate language is set by default. Can we choose to change it?

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#95]

**Comment by elieserdejesus** [comment]
Not possible at moment, but is not difficult add this feature.

**Comment by Ezeer** [comment]
a feature for ezee if not difficult ?
^^

**Comment by Ezeer** [comment]
some poetry : 

>"void **ChatMessagePanel::on_translateButton_clicked()**{
    if(ui->translateButton->isChecked()){
        if(translatedText.isEmpty()){
            QNetworkAccessManager* httpClient = new QNetworkAccessManager(this);
            **QLocale userLocale;**
            **QString targetLanguage =  userLocale.bcp47Name().left(2);**
            QString encodedText(QUrl::toPercentEncoding(originalText));
            QString url = "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl="+ targetLanguage +"&dt=t&q=" + encodedText;
            QNetworkRequest req;//(QUrl(url));
            req.setUrl(QUrl(url));
            req.setOriginatingObject(this);
            req.setRawHeader( "User-Agent" , "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" );
            qDebug() << url;
            QNetworkReply* reply = httpClient->get(req);
            QObject::connect(reply, SIGNAL(error(QNetworkReply::NetworkError)), this, SLOT(on_networkReplyError(QNetworkReply::NetworkError)));

>QObject::connect(httpClient, SIGNAL(finished(QNetworkReply*)), this, >SLOT(on_networkReplyFinished(QNetworkReply*)));
        }

QString targetLanguage is the thing to tweak , right ?

**Comment by elieserdejesus** [comment]
Excatly Ezee!
Using QLocale we can get the machine default language (maybe the language of Operational System? I'm not shure).

The simple solution is allow a "languageForChatTranslation" in json. If the property is in json we use, if not use QLocale.

The language format is 2 letters (en, pt, fr, etc,), this is the format expected in the google translator webservice.

**Comment by Ezeer** [comment]
Ok , let me try it so .

**Comment by Ezeer** [comment]
DOne .
How it works : By default , Jamtaba will use your locale settings .
But if you edit **Jamtaba.json** , give for exemple "fr" as parameter at this line : 
*"translation": "fr",*

you will end up with the chat translated in french .
Can you add that in the manual Jon , somewhere ?
thx

**Comment by elieserdejesus** [comment]
Nice work Ezee, thanks!
I think now the Jamtaba GUI is mature enough to ask some friend to write translation files for Jamtaba, so users can choose you language. Probably DoubleBass (the ninjamer) can write the French translation for us, and Magnus (the drummer) propose a German translation.

My idea is add these guys as collaboratos, so they can change the translation files when some things in Jamtaba GUI are updated.

**Comment by jonjamcam** [comment]
Can you add that in the manual Jon , somewhere ?

Of course, man. Nice Work!

**Comment by Ezeer** [comment]
Cool...Thanks , that was fun to do and we are so .... on time !
DoubleBass and Magnus are very good musicians and ninjamers , it's cool to be in 
such a team !
:+1:
