### ISSUE TITLE
default.CRITICAL can't open file  ""  in logs

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#954]
I noticed this warnings when connected to a server recently:

default.WARNING   [08:53:20:280] QFSFileEngine::open: No file name specified [, line 0]
default.CRITICAL  [08:53:20:287] can't open file  "" [, line 0]
default.WARNING   [08:53:28:274] QFSFileEngine::open: No file name specified [, line 0]
default.CRITICAL  [08:53:28:281] can't open file  "" [, line 0]
default.WARNING   [08:53:36:300] QFSFileEngine::open: No file name specified [, line 0]
default.CRITICAL  [08:53:36:308] can't open file  "" [, line 0]

To reproduce:

1.- launch jamtaba
2.- activate camera
3.- enter a server

**Comment by elieserdejesus** [comment]
@jonjamcam , I can't reproduce the issue here. 

I see your log has no info about the file where **can't open file** was generated. Can you try run in debug mode to see more infos in the log?

**Comment by jonjamcam** [comment]
Yeah, more info is available in debug mode:

Starting C:\Users\jon\Documents\_Jamtaba github\My_Fork\JamTaba\PROJECTS\build-Standalone-static_x64-Debug\debug\Jamtaba2.exe...
default.INFO      [22:10:06:607] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [Configurator.cpp, line 219]
default.INFO      [22:10:06:819] "Starting Jamtaba 2.1.2 Standalone (x86_64) running on Windows 7 (x86_64)" [MainController.cpp, line 981]
default.DEBUG     [22:10:27:717] Setting video resolution to QSize(640, 480) [video/FFMpegMuxer.h, line 127]
default.WARNING   [22:10:43:546] QFSFileEngine::open: No file name specified [qfsfileengine.cpp, line 199]
default.CRITICAL  [22:10:43:552] can't open file  "" [JamRecorder.cpp, line 134]
default.WARNING   [22:10:51:537] QFSFileEngine::open: No file name specified [qfsfileengine.cpp, line 199]
default.CRITICAL  [22:10:51:544] can't open file  "" [JamRecorder.cpp, line 134]
default.WARNING   [22:10:59:536] QFSFileEngine::open: No file name specified [qfsfileengine.cpp, line 199]
default.CRITICAL  [22:10:59:543] can't open file  "" [JamRecorder.cpp, line 134]

BTW in debug mode, the exe is about twice as big, but the specific line and file now appears:

![image](https://user-images.githubusercontent.com/15310433/31975511-107ffb06-b908-11e7-8ec0-b5ef9b174bbf.png)

In release mode only "line 0" is available:

![image](https://user-images.githubusercontent.com/15310433/31975533-3276bf7e-b908-11e7-9ba1-405f6ddd4178.png)

**Comment by elieserdejesus** [comment]
> and because it's a recorder issue

Exactly @jonjamcam , now I can reproduce the bug. I checked the **clipsort** in recording options and can see the same error messages here.
