### ISSUE TITLE
Remember layout of collapsable sections (bottom, left and chat)

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#955]
Suggestion: Remember the size and position of Jamtaba. 

Suggestion 2: Also remember the layout choice and sizing you've made. 

Thx !

**Comment by jonjamcam** [comment]
I'd like to add a suggestion Jamtaba remembers the settings for bottom area and local channel:

![image](https://user-images.githubusercontent.com/15310433/32017870-746accc2-b99e-11e7-8709-862aa17b497c.png)

so when Jamtaba is restarted you have all the space available from the start. Maybe not by default though,

**Comment by elieserdejesus** [comment]
Good ideas.

@jonjamcam , Torben suggested **Remember the size and position of Jamtaba.**. I programmed these features in Standalone, but not shure if still working. Maybe the problem (not remembering size and position) is VST and AU only?

**Comment by elieserdejesus** [comment]
Separating the "resize problems" in a new issue: https://github.com/elieserdejesus/JamTaba/issues/979
