### ISSUE TITLE
Metronome floating window not matching ninjampanel metronome

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#957]
![image](https://user-images.githubusercontent.com/15310433/32013787-840aa08c-b992-11e7-847c-fffcd6dcfdf9.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I suppose this problem is appearing after a BPI change, right?

**Comment by jonjamcam** [comment]
> I suppose this problem is appearing after a BPI change, right?

Not really. I entered an empty server, changed it's shape a couple of times and checked the hide bottom area in this case.
