### ISSUE TITLE
Navy theme's level meters looks not accurate

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#960]
Comparing same input aprox all other themes ae roughly the same, but not Navy that looks lower on average:

![image](https://user-images.githubusercontent.com/15310433/32027018-219ba420-b9bd-11e7-8a93-0b96e46a708f.png)

**Comment by elieserdejesus** [comment]
I changed the code to draw a solid bar (no segments), this chage is subtracting some pixels and showing wrong meter. 

It's easy see the problem if you activate the **show max peaks** option. The max peaks are always higher than meter bar.
