### ISSUE TITLE
Sync starts at 13 bpi

### ISSUE THREAD

**Issue by Hitrate** [elieserdejesus/JamTaba#965]
There seems to be a pre-roll thing going on where it'll start in sync, but at 13bpi out of 16. This f.... up my outboard sequencer and other things as they are now already on beat 8 (or whatever its set at) instead of being at beat 1 when beat 1 hits...So instead of syncing properly immediately, when im in LPX and hit sync and then hit play in logic - things start playing in logic but the sync is started from the 13th bpi position and goes on from there, thus leaving the whole thing out of whack, but in metronome tempo sync - so the sync is there but the sync start is off by a bar..... I have found no consistensy with this problem but with the latest version it seems to have gotten worse..previously it was fixable by restarting logic pro x from scratch and or selecting different audio card in device settings and then re-enable back the sound card u where using..and or removing jamtaba from the fx and re-inserting it...all time consuming tasks so I suggest looking into forcing jamtaba to always start on beat 1 when syncing.

**Comment by Hitrate** [comment]
Do you guys understand the issue or does it need clarification?

**Comment by elieserdejesus** [comment]
@Hitrate , I understood the general problem, but I need some details to reproduce the bug:

1 - the bug is appearing in any BPI?
2 - where is the playback head of LPX when you observed the bug? At the very first beat? Or in the first beat of 2nd or 3rd, 4th measure?

**I have a guess where is the problem**: when you click, for example,  in the 3rd beat of some measure in LPX and click sync in sequece, JamTaba will try compute **how many beats until the next measure first beat**. The idea is: **the sync always start in the first beat of the current (or next measure)**. So, if the playback head in the DAW is not located in the first beat JamTaba need calculate the **distance** from current point to next measure first beat. I guess this calculation is wrong in some cases.

**Comment by Hitrate** [comment]
I will test more but no, I always out of habit make sure to be at the start of the sequence in the daw (lpx) 

The loop will be activated by hitting play with the mouse or from one of my external devices like the Arturia BeatStep...Then the playhead goes for whatever bpi length the room is at, and usually for starters I’ll set the loop length in lpx to be one measure...

Since the BeatStep is a 16 step sequencer and has illuminated pads that light up for each measure, I can clearly verify that it goes through the first row of 8 pads when set at 1/8, before jamtaba “catches up”. Since jamtaba is the one that is starting “before” the first beat, in the sense that in a 16 bpi scenario, after hitting play, jamtaba starts from beat 13 and goes 4 steps forward to 16 then back to 1 and so forth, whilst the daw has obviously started at beat 1 which I set it to (rewind the playhead to the default start position and hit play) so the daw and thus my step sequencer and other things are now not in line with jamtaba, they are instead 4/8 steps ahead of time.....

**Comment by Hitrate** [comment]
Many times the problem happens if I: sync up like normal but then right after hit stop, maybe to adjust length of the sequencer loop or whatever, then click the stop/rewind back to start and re sync to jamtaba: the first instance works but then the second sync try will do the above mentioned..And from then on it will persist even sometimes to be point of me having to give up syncing even leaving the room and doing lots of other things like removing jamtaba from plugins window and reinserting, or completely close down logic and then reopening..It’s as if it remembers it’s own fault so you’re forced to live with the initial sync up or battle with the above mentioned problem :) 

Maybe there’s a way to program jamtaba to be forced NOT TO start it’s “playhead” at ANYTHING other than bpi 1...That way it would not technically be possible on the surface at least, for jamtaba to start at any of the 7, 15, 31 or 63 bpi steps and thus not askew the timing of loops in ones daw, as long as one is starting ones daw at the correct local playhead position.

**Comment by Hitrate** [comment]
[https://youtu.be/a8YmFyw7G8s]()

**Comment by Hitrate** [comment]
https://youtu.be/a8YmFyw7G8s

**Comment by Hitrate** [comment]
I figured out what caused the problem: In LPX preferences - plugin latency compensation the “playback pre-roll” was unticked...enabling it solved the problem..yay :)

**Comment by Hitrate** [comment]
Well now it’s reversed so I need to all of a sudden uncheck pre roll for it to sync properly...hmmm. Well at least I know where to fix it back and forth

**Comment by elieserdejesus** [comment]
> I figured out what caused the problem: In LPX preferences - plugin latency compensation the “playback pre-roll” was unticked...enabling it solved the problem..yay :)

Good news 😄 

I tried reproduce the problem in Logic Pro (not LPX) but the sync is always ok (with PDC on or off). 

I don't now a alway to ask host **how many samples are being compensated**, so I can uncompesate the host compesation 😄 .

I suppose I can do nothing in the JamTaba plugin code, PDC is host stuff.

I will close the issue, we can reopen if have some news about the topic.
