### ISSUE TITLE
Small design change proposal: greatly simplify RtMidi lib (multiple!) linkage options

### ISSUE THREAD

**Issue by fab672000** [elieserdejesus/JamTaba#968]
Context: 
RtMidi needs special care on each platform to build properly. Besides, each platform introduces more variations like arch and on osx the minimum target sdk that needs to be considered when generating static libs.

Problem: 
It becomes hard to maintain and bugs that are easy to fix just by changing the build options (not changing the lib source code hopefully!) can't be deployed rapidly.

Proposed Solution:
Incorporate *small only* libs source code like RtMidi directly in the app project (we should need to add only one extra .cpp file in the standalone to be able to remove the static lib dependency).
(The JUCE toolkit as an example also solves this problem by generalizing the limiting of the libs dependencies and uses a tool (projucer) that helps incorporates source code directly in your app.)

Thoughts @elieserdejesus and others ?

**Comment by elieserdejesus** [comment]
> Incorporate small only libs source code like RtMidi directly in the app project (we should need to add only one extra .cpp file in the standalone to be able to remove the static lib dependency).

@fab672000 ,  I totally agree, it's a good solution. 

Inside **src** you will see a **Libs** dir. This is the **3rd part** (non static) libs folder.

**Comment by fab672000** [comment]
Thanks @elieserdejesus, I'll propose shortly another pull request applying this change shortly and that will hopefully solve the rtmidi build problems on all platforms, after work hours of course :)
