### ISSUE TITLE
Mp3 record in the lounge

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#97]
I call lounge the front panel containing rooms .
I was looking to the listen button when i had the idea to add a volume slider on his left .
( now i imagine also a mini eq eh eh )
![radio](https://cloud.githubusercontent.com/assets/1283808/11013263/a78f6466-8505-11e5-85d4-afdb2718dc8d.jpg)

Then each room box started to seem like a radio ... one step ahead is to add a record button ,
and we got the magic .

No more need to hunt for a file in a remote server , you hear it , you got it !
Perhaps write in the mp3 tags the players in the session and the server name ?

**Comment by Ezeer** [comment]
If you like it , perhaps you will like to have a special feature for your records , a kind of browser .
I've found a site thate produce this online : 
![vrg33](https://cloud.githubusercontent.com/assets/1283808/11013321/569a7494-8508-11e5-9ed2-ce50030132bf.jpg)

We could make something similar , to every records , played in a jukeBox .
That could be found in a second front panel , hidden at startup .

**Comment by jonjamcam** [comment]
cool idea, but dirtydeeds NOOOOOOOOOOOOOOOOOO

lol

**Comment by Ezeer** [comment]
He is a legend , no ?
ah ah ah !

**Comment by jonjamcam** [comment]
Hey Ezee, when wil I see you in the rooms? never played with you, man!

**Comment by Ezeer** [comment]
I am a full time coder these very days , even don't listen to music much ..
But yeah , it is a great meeting in perspective !
^^

**Comment by elieserdejesus** [comment]
Ezee, the idea is cool!
But I'm very, very, very afraid with this because some ninjamers can be hungry with us. I see some discussions about this things in the pass. If we record the content of the server probabily some people will say we are "stealing their music".  

the idea of put the server name AND all musicians names in the mp3 tags is good, this can reduce anger :)

Another problem is mp3 encoder. As you know decoding mp3 is a legal thing, but encoding is not. To encode a mp3 you need pay the royalties to Fraunhofer guys, or use the russians pirate solution called lame_mp3 :)

As you can see we have very, very good options to encode mp3, hehe. This explain why some softwares choose ogg vorbis. Ogg vorbis is reall free to encode and decode, mp3 is free only for decode.

**Comment by Ezeer** [comment]
ok ... let's go to ogg vorbis .
And ...
Perhaps we could code something that prevents the " steal of music " : 
When a listener click on record , a message is sent to the chat by Jamtaba : 
" YOUR ATTENTION PLEASE , SOMEONE ASK TO RECORD YOUR SESSION , PLEASE VOTE
YES OR NO " .
If there is no answer in a delay of 60 s , it's no ... If 4 yes and one no , it's yes : the record start .

What do you think about that ?

**Comment by elieserdejesus** [comment]
We can't interact with chat until user enter in a room/server. The idea is put the REC button in the "lounge", right (see the first jon comment)?  In the lounge user is not yet connect in any room, so is not possible use chat.

**Comment by Ezeer** [comment]
Ok ...
I was not aware of possible conflicts , and perhaps i need to read again the servers licenses ...

**Comment by Ezeer** [comment]
I think a volume slider is a good starting point , would make the lounge room more : 
found one : 
>By connecting to this server and agreeing to this notice, you agree to the 
following:

>First of All you Agree to Love Puffer and obey his commands when commanded,
you do also agree to stfu if he wishes it and not to bother him with techincal questions as this may lead to a melt down in his frontal lobes.

>Please be aware that your music will be saved, stolen and sold to the highest bidder and you could be included in this deal. So say bye to your family before you begin to play as this process could be sudden and immediate.


>You also agree that all data, sounds, or other works transmitted to this server
are owned and created by you or your licensors, and that you are making these
data, sounds or other works available via the following Creative Commons 
License (for more information on this license, see 
http://creativecommons.org/licenses/by-nc-sa/2.5/ ):

>Attribution-NonCommercial-ShareAlike 2.5

>You are free:
    * to copy, distribute, display, and perform the work
    * to make derivative works

>Under the following conditions:
    Attribution. You must attribute the work in the manner specified by the 
    author or licensor.

   > Noncommercial. You may not use this work for commercial purposes. 
 
   > Share Alike. If you alter, transform, or build upon this work, you may 
    distribute the resulting work only under a license identical to this one.

    * For any reuse or distribution, you must make clear to others the license 
      terms of this work.
    * Any of these conditions can be waived if you get permission from the 
      copyright holder.

>Your fair use and other rights are in no way affected by the above.

**Comment by jonjamcam** [comment]
lol!

 I remember some time ago when you entered to the mutantlab.com server the license said "you agree that all the music in this server is owned by mutant" :D. funny guy

He changed it since.....
