### ISSUE TITLE
can't compile masterin win7

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#976]
hi @elieserdejesus 

I just installed from scratch visual studio 2013 and QT 5.6.3 in another computer and I have an error when compiling the master

![image](https://user-images.githubusercontent.com/15310433/35452673-1ae85f74-02a6-11e8-8e59-79df04e2fdac.png)

I had to use an old VST_SDK folder because the latest download from steinberg is different and gave me even more errors. I'm using lso latest lib zip file from dropbox

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I change the common code used in Standalone and VST plugin in a lib named "Common".  The idea is compile the common code one time and just reuse the same code in Standalone and VST. 

I will revert this commit, I don't like the result.

For while you can open **JamTaba.pro** and build (I'm assuming you opened *Standalone.pro* or *VstPlugin.pro*). The main project (JamTaba.pro) is compiling the common.lib correctly.

![image](https://user-images.githubusercontent.com/1012741/35460049-a39af4f8-02c9-11e8-9a7f-8ea56e6d7172.png)

**Comment by jonjamcam** [comment]
@elieserdejesus Can't make it work for some reason, but no worries. I'll be back home tuesday next week and then I'll be able to test the new features with my own system. Just wanted to check how easy it was to compile in another computer and it is quite simple to build the standalone version in windows 7. I managed to compile 2.1.3 from source.

But as I said before, the VST_SDK which the link is pointing to is different in folder structure and it didn't work for me so I had to use the old one I had in a backup.

 And the only QT version that actually installed properly was 5.6.3 .

**Comment by elieserdejesus** [comment]
@jonjamcam , I reverted the commit related to the **Common.lib**. I hope it's easy to compile now.

**Comment by jonjamcam** [comment]
> I hope it's easy to compile now

The above issue was solved, but I got this new one now @elieserdejesus :

![image](https://user-images.githubusercontent.com/15310433/35487110-c4545f3e-0456-11e8-9f63-63065efdb951.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I pushed a little fix to the master branch.

**Comment by jonjamcam** [comment]
> I pushed a little fix to the master branch.

It passed ok that last error. It looks though that this computer I'm at has very little memory (2GB) and it's not capable of finishing compiation.

![image](https://user-images.githubusercontent.com/15310433/35487708-888f7cc0-045d-11e8-82a1-b96ebb47e938.png)

I'm sure this is a local issue.

**Comment by jonjamcam** [comment]
@elieserdejesus same error in my system. There's a process called "d" that uses a lot of memory

**Comment by elieserdejesus** [comment]
@jonjamcam , I see the problem. In my machine the memory usage peak was 2.5 GB.

I dropped 2 big background images and the memory peak is 1.5 GB. This high memory usage is related with the emojis.

Can you try this branch in your machine? https://github.com/elieserdejesus/JamTaba/tree/fix-compilation-memory-usage

**Comment by jonjamcam** [comment]
Now it compiles correctly, Elieser. Tested vstplugin and standalone

**Comment by elieserdejesus** [comment]
@jonjamcam , I used this [image optimizer](https://tinypng.com/) and re-add the images in the branch  https://github.com/elieserdejesus/JamTaba/tree/fix-compilation-memory-usage.

Here the memory peak was 1.5 GB, same peak I have without the optimized images. 

**Can you test again in your machine, please?**

The expected result is:
![image](https://user-images.githubusercontent.com/1012741/35637931-cee91ac8-069c-11e8-9fca-d20c78a1dbdd.png)

**Comment by jonjamcam** [comment]
Yes. Looks amazing. It's compiling ok now

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !
