### ISSUE TITLE
MidiInDummy: This class provides no functionality.

### ISSUE THREAD

**Issue by Ezeer** [elieserdejesus/JamTaba#98]
We have a problem here .
2 weeks i am stuck with that usb device and Jamtaba : 

![image](https://cloud.githubusercontent.com/assets/1283808/11014510/68c1a8a0-8539-11e5-8814-2091270d012c.jpg)

It is known to work only when attached to a hub ...
http://www.kvraudio.com/forum/viewtopic.php?t=137002
Well i just found a way to make it work under windows using a 2nd usb cable : 
![149384_28](https://cloud.githubusercontent.com/assets/1283808/11014495/12b5c720-8539-11e5-8f4d-88f7ae20adfb.JPG)
that winXP takes that cable for a hub , don't ask me why .

Thus i tried reaper , and it works !
But not with Jamtaba , so we must improve this part of code to support more devices .

And so that i could use my 
![71vcjsbcvel _sx522_](https://cloud.githubusercontent.com/assets/1283808/11014653/71829024-8540-11e5-85d8-ac79f283ecf9.jpg)

**Comment by Ezeer** [comment]
I checked the code , this bug will be hard to fix because the problem depends of rtMidi ,
not jamtaba : 
>int RtMidiDriver::getMaxInputDevices() const{
    RtMidiIn rtMidi;
    return rtMidi.getPortCount();
}

In my case return 0 , because swiwssonic is not officially recognized by windows as midi driver ....
![midiproblem](https://cloud.githubusercontent.com/assets/1283808/11014812/be4d3f5c-8546-11e5-89c3-8adfcf2f7e59.jpg)

**Comment by elieserdejesus** [comment]
We are totally dependent of RtMidi here, I think we can't solve this.

**Comment by Ezeer** [comment]
**We are totally dependent of RtMidi here, I think we can't solve this.**
I downloaded the rtMidilib and i try to fix it , i am here : 
class RtMidi
{
 public:

 > //! MIDI API specifier arguments.
  enum Api {
    UNSPECIFIED,    /*!< Search for a working compiled API. */
    MACOSX_CORE,    /*!< Macintosh OS-X Core Midi API. */
    LINUX_ALSA,     /*!< The Advanced Linux Sound Architecture API. */
    UNIX_JACK,      /*!< The JACK Low-Latency MIDI Server API. */
    WINDOWS_MM,     /*!< The Microsoft Multimedia MIDI API. */
    RTMIDI_DUMMY    /*!< A compilable but non-functional API. */
  };

Perhaps i can tweak one thing in the lib itself , i'll try .
My console program returns the same than Jamtaba , " dummy ... " .
But my device works with WINDOWS_MM i think , it is just that swissonic may use and hardware
that microsoft don't signed ...

Reaper uses a lib that works , i will search in that direction .
Also native instruments standalone piano works ...

**Comment by Ezeer** [comment]
I 'VE GOT IT !
It is really rtMidi that sucks boy .
^^
rtMidi for windows is based on win32SDK mmsystem : 
>unsigned int MidiInWinMM :: getPortCount()
{
  return midiInGetNumDevs();
}

So i tried to call it myself directly by bypassing the rtMidi procedure , and the funk
returned 2 , that is the right number of devices in my system .

I think i will be able where is their bug , because the way the filter the devices is not good .
I wonder why rtMidi exclude my device when windows reports that it exists ....

**Comment by elieserdejesus** [comment]
Ezee, this is a very nice thing. If you fix RtMidi please propose the new version to the RtMidi guys, this is a great contribution to the community.

Can you test your swiwssonic in another machine? Maybe this is a Win XP problem only?

**Comment by Ezeer** [comment]
Well , it's the second pc i try , and the two have xp .
If i can find someo... ah , i've read that under seven there is also a problem .
Anyway , rtMidi is failing to find the devices that are recognized by Windows , 
mwah ah ah ah !

I feel there is a problem with their #defines , there is a lot , probably they missed something ,
or it's us ( the users that compile the lib that don't know how to parameter it correctly ... )
I will try to give some parameters to check that possibility .

**Comment by elieserdejesus** [comment]
Humm, you have a good point here.
you are using my pre compiled rtMidi lib. This lib was compiled in a Windows 8.1. 
Try compile the lib in your XP. I don't remember if I change some flags/defines in the compilation. I remember was a easy compilation compared to portmidi.

**Comment by Ezeer** [comment]
i have compiled it under msvc9 , done a litlle console app : 

#include "RtMidi.h"
#include "stdafx.h"

#include <conio.h>
#include<windows.h>

#include <MMSystem.h>

int _tmain(int argc, _TCHAR* argv[])
{
//my code start here
int i=midiInGetNumDevs();
printf("devices = %d",i);
// end here ...
//below the official exemple at https://www.music.mcgill.ca/~gary/rtmidi/index.html#download
//
	RtMidiIn *midiin = 0;
  // RtMidiIn constructor
  try {
    midiin = new RtMidiIn();
  }
  catch (RtMidiError &error) {
    // Handle the exception here
    error.printMessage();
  }
  // Clean up
  delete midiin;
  getch();
	return 0;
}

The output say :+1: 
![error](https://cloud.githubusercontent.com/assets/1283808/11015292/fdf9a78c-8558-11e5-896d-97382a5c263a.jpg)

now what reaper say : 
![error2](https://cloud.githubusercontent.com/assets/1283808/11015295/11a364ee-8559-11e5-925f-2d83cd09cd7a.jpg)

Jamtaba say what rtMidi say ...
eh eh

I will try to fix rtMidi so .

**Comment by elieserdejesus** [comment]
So we can discard the problem with my pre compiled lib, right?

**Comment by Ezeer** [comment]
++Totally !

**Comment by Ezeer** [comment]
I have found the problem and solved here elieser .
For windows YOU MUST USE  " __WINDOWS_MM__ " on your preprocessor definitions .
That's all folk !
Please make it so we are sure ....

**Comment by Ezeer** [comment]
wait ... it was set by default on the lib project ...
But i use the .h and cpp directly in my application , and my preprocessor def is : 
WIN32;NDEBUG;_CONSOLE;__WINDOWS_MM__

I don't understand why , but use the lib compiled don't work BUT use the sources lib works ...
Strange no ?

**Comment by Ezeer** [comment]
Or ... we must use __WINDOWS_MM_ in our .pro file ?
two cents that it's that !
lol

**Comment by Ezeer** [comment]
answer is here : http://stackoverflow.com/questions/17514638/compiling-rtmidi-qt-project-mingw
i'm gonna try it when my git problem will be solved ..

**Comment by Ezeer** [comment]
TadAaAaaaa !!
![midifix](https://cloud.githubusercontent.com/assets/1283808/11018521/bb5a862a-85cc-11e5-81ab-f0132df8df67.jpg)


i had to include that line in rtMidi.h : 
#ifndef RTMIDI_H
#define RTMIDI_H

#define RTMIDI_VERSION "2.1.0"

#include <exception>
#include <iostream>
#include <string>
#include <vector>
**#define __WINDOWS_MM__**

The problem now is that if used on mac or linux it will give Dummy to them ...
So i'll try to define WIN32 or _WIN32 before ....

**Comment by elieserdejesus** [comment]
Ezee, nice see this working. 
But change the rtMidi files is not a clean solution. Let's search for a more clean solution.
Probabily the lib can be compiled using the WINDOWS_MM pre processor flag, so you can use the pre compiled lib directly.
I will recompile the lib and we can do this test.

**Comment by Ezeer** [comment]
All right !
https://www.youtube.com/watch?v=PWgvGjAhvIw
