### ISSUE TITLE
Game theme level meters too wide in collapsed mode

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#980]
![image](https://user-images.githubusercontent.com/15310433/35643636-afb79cd4-06a5-11e8-8749-663ee9642571.png)

This happens when changing from other theme to game.

**Comment by elieserdejesus** [comment]
Adding some info: the bug occurs only if start with some theme and change to "Game" theme. 

If JTBA is started with the Game theme the collpased local channels are ok.
