### ISSUE TITLE
translations outdated (pending revision needed for ja_JP, da_DK and pl_PL)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#988]
@elieserdejesus maybe next release could have updated transaltions. what do you think?

- [x] pt_BR
- [x] es_CL
- [x] ja_JP
- [x] da_DK
- [x] de_DE
- [x] pl_PL
- [x] fr_FR

**Comment by elieserdejesus** [comment]
> maybe next release could have updated transaltions. what do you think?

Shure @jonjamcam . The TS files are updated in master branch.

Can you assume this task? Ask the translators to help, maybe use google translator in the very simple cases, etc?

**Comment by elieserdejesus** [comment]
The pt-br translation is finished https://github.com/elieserdejesus/JamTaba/commit/49f22725de93b92aaba4f2061894a022794d2523

**Comment by jonjamcam** [comment]
> Can you assume this task?

Sure @elieserdejesus .

**Comment by jonjamcam** [comment]
Hello @Hitrate , @MagnusDrumsTrumpet , @DoublebassOO and @qulf . There's a new Jamtaba release coming soon with a lot of cool new features. If you have the time to update your translations that would be fantastic. Thank you!

**Comment by MagnusDrumsTrumpet** [comment]
Hey eli,tell me me you got the translate from me in github jungle) greets Mag
 

    jonjamcam <notifications@github.com> schrieb am 13:01 Samstag, 17.Februar 2018:
 

 Hello @Hitrate , @MagnusDrumsTrumpet , @DoublebassOO and @qulf . There's a new Jamtaba release coming soon with a lot of cool new features. If you have the time to update your translations that would be fantastic. Thank you!—

**Comment by elieserdejesus** [comment]
Hi @MagnusDrumsTrumpet , your translations are merged, thanks!!!

I see **3 missing translations**. Can you translate these last 3?
- You are not transmiting for a long time! This is intentional?
- Private chat with %1
- Your Private Server

**Comment by elieserdejesus** [comment]
Qulf updated the translation: https://github.com/elieserdejesus/JamTaba/commit/cb5d9c1a5cb8107ca08479e248c2fffa8a10063f

Thanks @qulf !

**Comment by elieserdejesus** [comment]
@jonjamcam , some new strings in the TS files after the last PR, but it's ok if we have some untranslated entries.

**Comment by jonjamcam** [comment]
> some new strings in the TS files after the last PR,

Updated! in https://github.com/elieserdejesus/JamTaba/pull/1005

**Comment by MagnusDrumsTrumpet** [comment]
I do it here the translate 
    You are not transmiting for a long time! This is intentional?
       du überträgst lange zeit nicht

Private chat with %1
   privater chat mit 1%    

Your Private Server
   dein privater server

i hope you can merge it )

**Comment by jonjamcam** [comment]
> i hope you can merge it )

Created PR https://github.com/elieserdejesus/JamTaba/pull/1009

Thank you @MagnusDrumsTrumpet

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam and @MagnusDrumsTrumpet !

**Comment by jonjamcam** [comment]
@elieserdejesus I completed ja_JP transaltion for this release using google translale in https://github.com/elieserdejesus/JamTaba/pull/1013

As always strings are tagged "unfinished" so they can be corrected in the future.

**Comment by DoublebassOO** [comment]
Hello  the fantastic team ! Can you check if my translation in french was done right ! Not easy for me coming back on github after some month  ;)
   Thanks

**Comment by elieserdejesus** [comment]
Hi @DoublebassOO , thanks for your translation work!

I checked the translation file and see some missing entries. Can you translate for us (just here in github is enough)? The pending translation entries are:

- type here ...
- Public Chat
- Private chat with %1
- Uploading
- Downloading
- Collapse bottom area
- Remember these options when a musician enters the jam:
- Pan

Thanks for your attention!

**Comment by jonjamcam** [comment]
@qulf there's a new feature called "public chat" for which the pl_PL translation is incomplete. the new strings are 14:

* Turn on/off this chat
* chat is off
* Connected Users (%1)
* Public chat
* Let´s play in %1 : %2 ?
* Let's play in my private server?
* Connected with public chat!
* Connecting ...
* Block %1 in chat
* Unblock %1 in chat
* Public chat disconnected!
* Invite %1 to play in %2 [%3]
* Accept!
 * You can´;t send messages using an empty user name!

can you translate them please? Thank you!

**Comment by MagnusDrumsTrumpet** [comment]
- Turn on/off this chat                                   schalte diesen chat an/aus    

   - chat is off                                                 chat ist aus   

   - Connected Users (%1)                              verbundene Benutzer (%1)   

   - Public chat                                              öffentlicher chat   

   - Let´s play in %1 : %2 ?                             lasst uns spielen in %1 : %2?   

   - Let's play in my private server?                   lasst uns in meinem privaten server spielen?   

   - Connected with public chat!                        verbunden mit öffentlichem chat!
   - Connecting ...                                           verbinde...   

   - Block %1 in chat                                      blockiere %1 in chat   

   - Unblock %1 in chat                                  blockieren aufheben %1 in chat   

   - Public chat disconnected!                         öffentlicher chat unterbochen!   

   - Invite %1 to play in %2 [%3]                      lade 1% zum spielen in %2 [%3] ein   

   - Accept!                                                    akzeptiere!   

   - You can´;t send messages using an empty user name!                 du kannst keine nachrichten ohne usernamen senden!

hey i hope this helps) German hyroglyphes  for jamtabe by MAG
 

    jonjamcam <notifications@github.com> schrieb am 0:27 Freitag, 2.März 2018:
 

 @qulf there's a new feature called "public chat" for which the pl_PL translation is incomplete. the new strings are 14:   
   - Turn on/off this chat
   - chat is off
   - Connected Users (%1)
   - Public chat
   - Let´s play in %1 : %2 ?
   - Let's play in my private server?
   - Connected with public chat!
   - Connecting ...
   - Block %1 in chat
   - Unblock %1 in chat
   - Public chat disconnected!
   - Invite %1 to play in %2 [%3]
   - Accept!
   - You can´;t send messages using an empty user name!
can you translate them please? Thank you!—

**Comment by jonjamcam** [comment]
Great! Thank you @MagnusDrumsTrumpet PR incorporating your changes is https://github.com/elieserdejesus/JamTaba/pull/1020

**Comment by elieserdejesus** [comment]
Thanks @MagnusDrumsTrumpet !

**Comment by jonjamcam** [comment]
@Hitrate and @qulf pending da_DK and pl_PL were google-translated. These strings are still tagged "unfinished" for easy correction.

**Comment by jonjamcam** [comment]
@elieserdejesus I made one PR (https://github.com/elieserdejesus/JamTaba/pull/1029) out of two commits by @DoublebassOO (details in PR) for fr_FR translation with some minor corrections.

Now all translations are complete for 2.1.4

**Comment by elieserdejesus** [comment]
> I would suggest if possible to make these thread sticky at the beginning so google-translated strings could be revised.

@jonjamcam , unfortunally "pinned" issues are not possible in github.
