### ISSUE TITLE
private server host and new game and navy themes not translatable

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#990]
only english atm

**Comment by elieserdejesus** [comment]
@jonjamcam , I don't have idea about how to translate "Navy" 😄 

Navy is a [color pallete](https://www.google.com.br/search?q=Navy+palette&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiZ88Kkn6vZAhWJhJAKHb-6DW0Q7AkIOA&biw=1216&bih=675), but I'm not shure if is possible translate.

**Comment by elieserdejesus** [comment]
Private server window are translatable now, I added a new commit in the master branch.

**Comment by elieserdejesus** [comment]
Private server window strings are translatable now, I added a new commit in the master branch.

**Comment by jonjamcam** [comment]
> Navy is a color pallete, but I'm not shure if is possible translate.

Smells like... 

![image](https://user-images.githubusercontent.com/15310433/36332074-78134c5e-134f-11e8-8c7b-e4898e909e5e.png)

:smile:

**Comment by elieserdejesus** [comment]
😄 , agree, it's "marinha" in portuguese

I was inspired in Logic when working in this theme:
![image](https://user-images.githubusercontent.com/1012741/36333628-06cd15ec-135f-11e8-85a9-ca5275e09189.png)

**Comment by jonjamcam** [comment]
@elieserdejesus we still have the server log messages only in english. Is it possible to allow these to be translated?

**Comment by elieserdejesus** [comment]
> @elieserdejesus we still have the server log messages only in english. Is it possible to allow these to be translated?

@jonjamcam , I pushed new commits to master branch.

**Comment by jonjamcam** [comment]
>  I pushed new commits to master branch.

working ok. es_cl updated @elieserdejesus . Allowing new Themes names translation is the only issue left for this one to be closed.

**Comment by elieserdejesus** [comment]
New themes are translatable now @jonjamcam
