### ISSUE TITLE
Some strings not updating in private server host window when changing language

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#995]
for example when changing from english to spanish:

![image](https://user-images.githubusercontent.com/15310433/36340582-30a23d74-13bf-11e8-81d7-98197ec4a92c.png)

some strings are still in english. The log entries update correctly though.

**Comment by elieserdejesus** [comment]
@jonjamcam , this issue is fixed. 

But the previous log lines are not translated when you change the language. Just the new log entries will be translated.
